### ISSUE TITLE
[Docs page] Release Notes

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#1001]
**Description**

:tickets: [Asana ticket]()

:mag: File path: /website/docs/cdktf/TBD

Might be a single page or a section with sub-pages. Information to include: 

- [Feature flags](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/feature-flags.md)
- Release cadence
- Release notes

**Comment by skorfmann** [comment]
> Release notes

Do you mean publishing release notes to terraform.io docs?

**Comment by schersh** [comment]
Yes - the idea here was to publish release notes to terraform.io/docs/cdktf/ 

Open question as to what that looks like - if it's just linking to a the changelogs, or something more involved. 

We might want to coordinate with @laurapacilio to see if other products have plans to do this, so that it can be consistent (Laura, I think that you and Daniel discussed this a little bit?)

**Comment by laurapacilio** [comment]
Hello! Sorry for the delay on this. My opinion is that if we're doing release notes, we should provide something that's more user-friendly than what's in the change logs. I am happy to discuss what that looks like when the time comes! You asked if other products have release notes. I know that Loann (TW on Vault) came up with a release notes template and has been working with them to publish Vault release notes. Here's an example: https://www.vaultproject.io/docs/release-notes/1.9.0

 TFE has also been doing release notes: https://www.terraform.io/docs/enterprise/release/v202111-1.html. But I like how Vault's give a bit more context and include links where appropriate, etc. 

Anyway - let's talk more about this if/when we're ready to implement and come up with a plan!
