### ISSUE TITLE
Add Python unit testing support

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#1002]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We should extend [initial testing support](https://github.com/hashicorp/terraform-cdk/pull/952/files) to add support for running snapshot and assertion tests using Python.

**Comment by edge7** [comment]
Hello,
Any news on this?

**Comment by jsteinich** [comment]
@edge7 It is tentatively scheduled for the 0.13 release.

**Comment by DanielMSchmidt** [comment]
This is a part of the 0.12 release 🎉
