### ISSUE TITLE
[Docs page] Functions

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#1005]
**Description**
This page should explain to new users of CDK for Terraform and Terraform what functions are and when/how they should use them in CDK for Terraform applications

Content should go in:[ /website/docs/cdktf/fundamentals/functions.html.md](https://github.com/hashicorp/terraform-cdk/blob/terraform-io-docs/website/docs/cdktf/concepts/fundamentals/functions.html.md)

This document requires **engineering support** for:
- Review existing page content for accuracy
- Respond to TODOs in the markdown file, which reflect places where we need additional examples or information. 

----
Transfer existing doc content - DONE

**Comment by laurapacilio** [comment]
I have:

- Transferred content from the original GitHub docs page
- Copyedited the content
- Significantly reorganized the content - Please push back where necessary.
- Added several TODOs in throughout the markdown file where I feel we need additional examples, explanations, etc. Please let me know if any of these don't make sense!

Once engineering reviews the content and makes any necessary additions and corrections, I will review/copyedit again and we can mark this ready for publishing.
