### ISSUE TITLE
Stale javascript from typescript compilation

### ISSUE THREAD

**Issue by matschaffer** [hashicorp/terraform-cdk#1012]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
❯ yarn list | grep -e cdk -e typescript
├─ @cdktf/provider-google@0.3.7
├─ cdktf@0.5.0
├─ typescript@4.4.3
```

### Affected Resource(s)

Any

### Debug Output

N/A

### Expected Behavior

Any change to `*.ts` should be reflected in the next deploy.

### Actual Behavior

Usually it is, but not always.

### Steps to Reproduce

Still unclear. Tends to happen after a number of edits and deploys. I tend to run this to fix it.

```
./node_modules/.bin/tsc --build --clean
```

### Important Factoids

Another way I've found to work around this is to add `ts-node` as a dependency and update my `cdktf.json` to have `"app": "npx ts-node main.ts",`

### References

None

---

I'm posting this partly for discussion to see if others have encountered this. 

Using ts-node directly seems to work well so far and avoids having `.d.js,.js` files peppered around my working directory.

Would it make sense to maybe have the default be to run via ts-node?

**Comment by skorfmann** [comment]
> Another way I've found to work around this is to add `ts-node` as a dependency and update my `cdktf.json` to have `"app": "npx ts-node main.ts",`

I'm wondering if we should make this the default - thoughts? /cc @DanielMSchmidt @ansgarm

**Comment by ansgarm** [comment]
I like using `ts-node` for that. Another thing that we could consider, is using a separate `dist` directory for the compiled JS files, but I'm happy with either way.

**Comment by ansgarm** [comment]
Oh, yeah, right.

**Comment by matschaffer** [comment]
Thanks @DanielMSchmidt !
