### ISSUE TITLE
Json parse Error with cdktf get

### ISSUE THREAD

**Issue by romainPrignon** [hashicorp/terraform-cdk#1013]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
lang: typescript
cdktf: 0.5.0
cdktf-cli: 0.5.0

### Debug Output

https://gist.github.com/romainPrignon/dd220d105fb02bc2a7a2a90ab062e334

### Expected Behavior
Modules and providers should have been downloaded to .gen folder

### Actual Behavior

Json parse error related to provider schema. See Gist

### Steps to Reproduce

- see files from gist
- npm run prepare or npm ci (which calls prepare)

### Important Factoids

- Everythings works locally, but not in the CI (github actions)

- #0000

**Comment by jsteinich** [comment]
Perhaps there's an issue with the particular versions used. I tried those providers with node v14.17.6 and Terraform v0.14.7 and didn't run into any issues. Which versions are you using locally?

**Comment by romainPrignon** [comment]
That's what I thougth.
It failed with Terraform v0.14.11 on github CI
I used terraform v0.14.10 locally
Our CI still use node 14.4
I'll try to upgrade to  v14.17.6 later today

**Comment by romainPrignon** [comment]
no :'(
still the same issue
```
Run hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.14.7
    cli_config_credentials_hostname: app.terraform.io
    terraform_wrapper: true
```
```
Run actions/setup-node@v2
  with:
    node-version: 14.17.6
```

I have no issue locally. 
It's not related to aws/heroku credentials either. I tried `cdktf get` locally with false creds

Seems related to github CI ? is there any form of git clone during cdktf get  ?

**Comment by romainPrignon** [comment]
The stacktrace point to this line
```
providerSchema = JSON.parse(await util_1.exec(terraformBinaryName, ["providers", "schema", "-json"], {
                cwd: outdir,
            }));
```
when I try `terraform providers schema -json` `locally` AND in the `CI` I get:
`{"format_version":"0.1"}`

**Comment by jsteinich** [comment]
> when I try `terraform providers schema -json` `locally` AND in the `CI` I get:
> `{"format_version":"0.1"}`

`cdktf get` runs that command in a temporary directory with a generated terraform configuration file.

Can you please try running with the `CDKTF_LOG_LEVEL` environment variable set to `debug` or `all`? I believe that will let us see the output of the terraform command before trying to parse as JSON.

**Comment by ansgarm** [comment]
I was able to reproduce this locally using [act](https://github.com/nektos/act)
It seems to fail for any provider (also for example for `hashicorp/random` which I used as it is smaller than aws or heroku).

With debugging enabled the Terraform output looks like this:
```
| [2021-09-15T10:02:09.615] [DEBUG] default - ::debug::stdout: {"format_version":"0.1" …
```

Our JSON parsing chokes on the unexpected `::debug::stdout: ` which is added via the wrapper that `setup-terraform` uses.
I could get it to work by disabling that wrapper:
```yaml
- uses: hashicorp/setup-terraform@v1
  with:
    terraform_version: 0.14
    terraform_wrapper: false
```

**Comment by romainPrignon** [comment]
I also confirm that disabling the wrapper works
Tell me if there something else I can do to help :)

**Comment by ansgarm** [comment]
Is that workaround okay for now? If yes, feel free to close this issue as I created #1020 for supporting the wrapper.
If you want to, you can have a go at #1020 – we're happy to take a PR there 😄 If needed, I could also outline which parts of the codebase might need to be touched :)

**Comment by romainPrignon** [comment]
Ok, I'll close for now
It might be a good idea to highlight the part of the codebase for me, or others, so we can fix this :)

**Comment by ansgarm** [comment]
@romainPrignon I just added the affected code locations to #1020
