### ISSUE TITLE
Prebuilt provider request: `azuread`

### ISSUE THREAD

**Issue by brad-lucas** [hashicorp/terraform-cdk#1019]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure's identity model is incredibly tied to Azure AD, so presumably many projects using the prebuilt `azurerm` provider would also stand to benefit from a prebuilt `azuread` provider.

### References

Added [an issue over in the `cdktf-provider-azurerm` repo](https://github.com/hashicorp/cdktf-provider-azurerm/issues/446) as well; please feel free to clean up as necessary, and sorry for added paperwork. :)

**Comment by skorfmann** [comment]
Please find the provider over here https://github.com/hashicorp/cdktf-provider-azuread
