### ISSUE TITLE
Use deep equality check in `toHaveResourceWithProperties` / `toDataSourceWithProperties`

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1047]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the check uses strict equality:
https://github.com/hashicorp/terraform-cdk/blob/cb9772fa20f4119e97f20ec25a2ea72ac43ba929/packages/cdktf/lib/testing/matchers.ts#L44-L44

This results in this matcher call to fail:
```ts
expect(synthesized).toHaveResourceWithProperties(aws.S3Bucket, {
  bucketPrefix: `sls-example-frontend-test`,
  website: [
    {
      indexDocument: "index.html",
      errorDocument: "index.html",
    },
  ],
});
```

Using deep equality is what I'd have expected to work here for the `website` attribute.

**Comment by Marvin9** [comment]
I would like to work on it @ansgarm.

**Comment by ansgarm** [comment]
Hi @Marvin9,
We would have loved your contribution on this!
However @DanielMSchmidt had already started [working on this](https://github.com/hashicorp/terraform-cdk/pull/1052).
If there's anything else you'd like to contribute on, I'm happy to help :)

**Comment by Marvin9** [comment]
No worries @ansgarm Looking for good first issues.

**Comment by ansgarm** [comment]
Hey @Marvin9!
I suspect you've already seen the [issue label](https://github.com/hashicorp/terraform-cdk/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)?
If there are any particular things that are interesting for you, feel free to message me via e.g. the [CDK Dev Slack](https://cdk.dev/) or Twitter or email or whatever 👍
