### ISSUE TITLE
Synth Error: AWS S3 Bucket with SSE 

### ISSUE THREAD

**Issue by chiayuan** [hashicorp/terraform-cdk#1074]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
- cdktf: 0.6.3
- Python: 3.7
- Terraform: 1.0.2

### Affected Resource(s)
AWS S3 Bucket

### Debug Output
https://gist.github.com/chiayuan/654b16547bc398d19dcd04a460a1b9bf

### Expected Behavior
It is an official Terraform example code.
Should be able to synth and deploy an S3 bucket with SSE.

### Actual Behavior
A `jsii.errors.JSIIError: Missing required properties for aws.S3BucketServerSideEncryptionConfigurationRule: applyServerSideEncryptionByDefault`. 
error occurs when synthesizing.

### Steps to Reproduce
By `cdktf convert` feature, I just copy terraform s3 bucket [example](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket#enable-default-server-side-encryption). 
and use `pbpaste | cdktf convert --language python` to get converted python codes to paste in my stack.

### Others
Also just wondering, it will be great if there are some guides to use complex attributes.
Actually, I can write IaC with cdktf smoothly most of the time, but I stuck and didn't know how to do when i saw something like:  
```python
server_side_encryption_configuration: typing.Optional[typing.Sequence["S3BucketServerSideEncryptionConfiguration"]] = None,
```
That's the reason why I use  `cdktf convert` to give it a try.

**Comment by danieldreier** [comment]
@chiayuan thanks for reporting this!

**Comment by jsteinich** [comment]
I suspect that this is similar to #934.

Try using something along the lines of:
```python
aws.S3Bucket(self, "mybucket",
    bucket="mybucket",
    server_side_encryption_configuration=[S3BucketServerSideEncryptionConfiguration(
        "rule": [S3BucketServerSideEncryptionConfigurationRule(
            "apply_server_side_encryption_by_default": [S3BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefault(
                "kms_master_key_id": aws_kms_key_mykey.arn,
                "sse_algorithm": "aws:kms"
            )
            ]
        )
        ]
    )
    ]
)
```

Sometimes jsii (technology behind the multi-language support) is able to infer the correct types, but not always.

**Comment by chiayuan** [comment]
@jsteinich Thank you for helping.
Python code that works will look like:
```python
S3Bucket(
    self,
    "mybucket",
    bucket="mybucket",
    server_side_encryption_configuration=[
        S3BucketServerSideEncryptionConfiguration(
            rule=[
                S3BucketServerSideEncryptionConfigurationRule(
                    apply_server_side_encryption_by_default=[
                        S3BucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefault(
                            kms_master_key_id=kms.arn,
                            sse_algorithm="aws:kms",
                        )
                    ]
                )
            ]
        )
    ],
)
```
And yeah, the `jsii` converted `Sequence["S3BucketServerSideEncryptionConfiguration"]` type confuses me lol.
Thanks a lot!

**Comment by mutahhir** [comment]
This is related to: https://github.com/hashicorp/terraform-cdk/issues/270

**Comment by mutahhir** [comment]
It's hard to test this anymore because the AWS provider has changed to remove this specific resource configuration. However, with the new changes to convert on main right now, I expect this to be solved already. 

If that's not the case, please reopen with a terraform config that we can use to reproduce the issue.
