### ISSUE TITLE
Is there any way I can execute such as the command “init”,"plan" in CDKTF？

### ISSUE THREAD

**Issue by LetLetMe** [hashicorp/terraform-cdk#1081]
I want to enter a xxx.tf file in CKDTF and execute "init", "plan", "apply". Instead of building the infrastructure step by step or call CMD command in the program （This is ugly）.Is there any way I can do this？

**Comment by ansgarm** [comment]
Hey @LetLetMe!
You could put your Terraform file into a Terraform Module (use `variables` and `outputs` to define its boundaries) and use that module using [`TerraformHclModule`](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-modules.md#terraformhclmodule).

What is your underlying use case? Do you want to transfer from HCL to CDKTF? Or do you want to use HCL and CDKTF constructs for the same project?

**Comment by DanielMSchmidt** [comment]
I would understand the question as @LetLetMe not wanting to iterate manually by invoking cdktf over and over again. In this case we have the new `cdktf watch` command for nicer iterations. It seems like there hasn't been any activity on this issue for a while now, so I'm closing this for now. I hope one of our answers helped, if not please let us know 👍
