### ISSUE TITLE
Get one element from module output list(target_group_arns of terraform-aws-modules/alb/aws) 

### ISSUE THREAD

**Issue by Anton7K** [hashicorp/terraform-cdk#1087]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf 0.6.3
cdktf-cdktf-provider-aws 2.0.11
terraform-aws-modules/alb/aws@5.16.0
Python 3.8.10

### Affected Resource(s)

- aws alb module(TerraformAwsModulesAlbAws - https://registry.terraform.io/modules/terraform-aws-modules/alb/aws/latest)
- EcsService

I created several aws albs via module and want to get single element from their output list (target_group_arns) to create subsequent resources(ecs services).
I tried different approaches, the last one was as following(for test purposes I hardcoded index values):
```
lb = self.load_balancers[0]
target_group_arn = Fn.element(Token.as_list(lb.target_group_arns_output), 0)  
```
### Expected Behavior
I thought, that in json output will appear something like:
`"target_group_arn": "${element(module.stack-name-lb2.target_group_arns, 0)}"`
And then this string will be substituted with needed value during apply

### Actual Behavior

I can synthesize code successfully, but during the plan I get several errors like this one:

> Error: Invalid character
> │ 
> │   on cdk.tf.json line 2704, in resource.aws_ecs_service.stack-nameecs-cluster-construct-service-33_EEFE3F15.load_balancer[0]:
> │ 2704:             "target_group_arn": "${element(${module.stack-name-lb2.target_group_arns}, 0)}"
> │ 
> │ This character is not used within the language.
> ╵
> ╷
> │ Error: Invalid expression
> │ 
> │   on cdk.tf.json line 2704, in resource.aws_ecs_service.stack-nameecs-cluster-construct-service-33_EEFE3F15.load_balancer[0]:
> │ 2704:             "target_group_arn": "${element(${module.stack-name-lb2.target_group_arns}, 0)}"
> │ 
> │ Expected the start of an expression, but found an invalid expression token.

**Comment by jsteinich** [comment]
Related to #287 and #525, but does seem to be a standalone issue.

One workaround:

- Pass `lb.fqn + '.target_group_arns'` to the element function
