### ISSUE TITLE
TerraformOutput fails to output resource object

### ISSUE THREAD

**Issue by marengaz** [hashicorp/terraform-cdk#1088]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.6.3

### Affected Resource(s)

TerraformOutput

### Expected Behavior

snippet of the output json corresponding to the output object

```json
  "output": {
    "a_taxonomy": {
      "value": "${google_data_catalog_taxonomy.a_taxonomy_resource}",
      "description": "a taxonomy"
    }
  }
```

### Actual Behavior

snippet of the output json corresponding to the output object

```json
  "output": {
    "a_taxonomy": {
      "value": {
        "jsii_byref": "google-beta.GoogleDataCatalogTaxonomy@10003"
      },
      "description": "a taxonomy"
    }
  }
```

### Steps to Reproduce

synthesise the following: 

```python
from constructs import Construct
from cdktf import App, TerraformStack, TerraformOutput
from imports.google_beta import (
    GoogleDataCatalogTaxonomy,
    GoogleBetaProvider,
)

class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)
        googleBeta = GoogleBetaProvider(self, "google-beta")

        taxonomy = GoogleDataCatalogTaxonomy(
            self,
            "a_taxonomy_resource",
            provider=googleBeta,
            project='my-project',
            region='europe-west1',
            display_name="a_taxonomy",
            description="a taxonomy.",
            activated_policy_types=["FINE_GRAINED_ACCESS_CONTROL"],
        )

        TerraformOutput(
            self,
            'a_taxonomy',
            description='a taxonomy',
            value=taxonomy
        )

def main():
    app = App()
    MyStack(app, "my_stack")
    app.synth()

if __name__ == "__main__":
    main()
```

### Important Factoids

work around for the mean time

```python
        TerraformOutput(
            self,
            'a_taxonomy',
            description='a taxonomy',
            value={"id": taxonomy.id, "name": taxonomy.name}
        )
```

### References

- #0000

**Comment by jsteinich** [comment]
I'm actually surprised that even compiles. I'm also not sure how Terraform handles that.
Assuming Terraform supports passing a reference to a resource, then this should be doable. Event if it doesn't, there are potentially some ways to make it work.

**Comment by marengaz** [comment]
if i manually change the *.tf.json to show the 'expected result' above, then use it in another module it works just fine!
