### ISSUE TITLE
Design support for dynamic blocks, iterators, count

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#1089]
This is a meta-issue tracking the need to support dynamic HCL language features. This is a research and design task, and the expected outcome is documented designs and ticketed improvements in the 0.9 and 0.10 releases.

**Goal**
The HCL language has dynamic features that allow users to conditionally create resources based on dynamic data. A common use case is to take data from a data source, modify it with built-in functions, and then create one or more resources depending on those values. This is currently only possible using the CDK for Terraform escape hatch, and is [not very well documented](https://github.com/hashicorp/terraform-cdk/issues/837). 

The goal of this ticket is to concretely plan the implementation of idiomatic CDK for Terraform support for `count` and `for_each` both for individual resources and for modules. 

**References**

- #842 
- https://github.com/hashicorp/terraform-cdk/issues/435
- https://github.com/hashicorp/terraform-cdk/issues/1094

**Comment by danieldreier** [comment]
I'm tentatively assigning the design of this to 0.8 as a stretch goal, and a placeholder implementation ticket in 0.10. If this isn't completed in 0.8 it should be considered `committed` in 0.9.

**Comment by DanielMSchmidt** [comment]
Documented the findings in https://github.com/hashicorp/terraform-cdk/issues/1094
