### ISSUE TITLE
Design state-move resource rename refactoring 

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#1091]
Terraform Core is actively working on an improvement that will make it easier to refactor HCL code. It will add dummy resources that are pointers to a new resource. For example, if you refactor a resource into a module, you put this dummy resource into the old location pointing to the new location. When the Terraform plan is evaluated, Terraform Core will rename the resources in state, avoiding the need to script a bunch of `terraform state mv` commands.

The purpose of this ticket is to track the need to coordinate and design matching CDK for Terraform support, and to track the need to design a similar refactoring user experience that allows users to refactor code without needing to manually adjust state afterward. This issue should be resolved when the desired UX is planned and ticketed out into engineering-ready work.

I'm initially putting this on the 0.9 milestone to ensure that we check in with Core, but the delivery date isn't guaranteed so it's not a firm commitment.

**Comment by jsteinich** [comment]
The AWS CDK has very basic renaming capabilities: https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_core.Stack.html#renamewbrlogicalwbridoldid-newid

**Comment by xiehan** [comment]
Duplicate of #1292 / #219
