### ISSUE TITLE
Implement support for dynamic blocks and iterators

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#1094]
To support dynamic list iterations on the block / resource level we will introduce a new API, called `Iterator`.

An iterator can be created from any list and either be passed on a new meta-level `forEach` property to create multiple instances of the resource. To access data on the list that's iterated over the iterator has `getStringProperty`, `getNumberProperty`, ... accessors. To create dynamic blocks one can use `iterator.dynamic([...])` and the block will be repeated for each item in the list.

```ts
import { TerraformStack, Iterator } from "cdktf";
import { S3Bucket, DataAwsSubnets, DataAwsAllowedOrigins } from "./.gen/providers/aws-ficticious";
import { Construct } from "constructs";

export class MyStack extends TerraformStack {
 constructor(scope: Construct, id: string) {
   super(scope, id);

   const subnets = new DataAwsSubnets(this, "subnets", {});
   const subnetIterator = Iterator.fromList(subnets.subnets);

   // Fictitious data source that returns [{method, origin}]
   const allowedOrigins = new DataAwsAllowedOrigins(
     this,
     "possibleOrigins",
     {}
   );
   const allowedOriginsIterator = Iterator.fromList(allowedOrigins.origins);

   new S3Bucket(this, "my-bucket", {
     forEach: subnetIterator,
     bucket: `my-bucket-${subnetIterator.key}`,
     subnetId: subnetIterator.value,
     corsRule: allowedOriginsIterator.dynamic(
       {
         allowedMethods: [allowedOriginsIterator.getStringProperty("method")],
         allowedOrigins: [allowedOriginsIterator.getStringProperty("origin")],
         maxAgeSeconds: 42,
       },
     ),
   });
 }
}

```

**Comment by jsteinich** [comment]
Creating iterators via a static method will work for primitive types, but a lack of generic support will make it not work for complex types. We can still pull of something similar, but it will require more code generation on `ComplexList` and `ComplexMap` implementation classes.

Perhaps this would just be under the hood, but it would be good to support something similar when using `count`.

We'll also want methods for accessing the `for_each` created resources as a list/set/map. Perhaps using a similar approach on the resource class itself.

**Comment by DanielMSchmidt** [comment]
Splitting this into #1797 and #1798
