### ISSUE TITLE
cdktf get fails if .cdktf folder doesn't exist

### ISSUE THREAD

**Issue by JonCubed** [hashicorp/terraform-cdk#1098]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.6.3

### Affected Resource(s)

cdktf-cli

### Debug Output

```
Error: ENOENT: no such file or directory, open '/root/.cdktf/config.json'
#11 595.8     at Object.openSync (fs.js:498:3)
#11 595.8     at Object.writeFileSync (fs.js:1524:35)
#11 595.8     at getId (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/lib/checkpoint.js:97:16)
#11 595.8     at getUserId (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/lib/checkpoint.js:114:12)
#11 595.8     at Object.ReportRequest (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/lib/checkpoint.js:139:31)
#11 595.8     at report (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/lib/get/constructs-maker.js:292:24)
#11 595.8     at ConstructsMaker.generate (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/lib/get/constructs-maker.js:260:19)
#11 595.8     at async get (/usr/local/share/.config/yarn/global/node_modules/cdktf-cli/bin/cmds/ui/get.js:50:17) {
#11 595.8   errno: -2,
#11 595.8   syscall: 'open',
#11 595.8   code: 'ENOENT',
#11 595.8   path: '/root/.cdktf/config.json'
#11 595.8 }
#11 595.8 ⠋ downloading and generating modules and providers...
#11 595.8 ENOENT: no such file or directory, open '/root/.cdktf/config.json'
```

### Expected Behavior

`cdktf get` complete successfully

### Actual Behavior

`cdktf get` fails when `.cdktf` folder doesn't exist

### Steps to Reproduce

make sure that `.cdktf` folder does not exist in the users home directory and run `cdktf get` in your project

### Important Factoids

I am upgrading from 0.5.0 to 0.6.3, when I run `cdktf get` in my docker build it fails with the above error. I believe the following doesn't account for the folder not existing.

https://github.com/hashicorp/terraform-cdk/blob/fae06c5e18e5ac6837c62927ab2a4bfe2194afdf/packages/cdktf-cli/lib/checkpoint.ts#L104

If I turn off telemetry `cdktf get` works fine

**Comment by nadworny** [comment]
How can you turn off telemetry?

**Comment by JonCubed** [comment]
@nadworny by setting an environment variable `CHECKPOINT_DISABLE` with a non-empty value. You can find more info at https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/telemetry.md

**Comment by JonCubed** [comment]
thanks @jsteinich
