### ISSUE TITLE
[CLI] `date-fns` dependency is huge

### ISSUE THREAD

**Issue by brad-lucas** [hashicorp/terraform-cdk#1135]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- `cdktf-cli` @ any

### Affected Resource(s)

- `cdktf-cli` NPM package

### Steps to Reproduce

1. Install CDKTF CLI: `npm install -g cdktf-cli`
2. Navigate to `cdktf-cli`'s `node_modules`.
3. List package folders by size.

```bash
➜  du ./node_modules/* -s | sort -n -r | head -n 10
50808   ./node_modules/typescript
27256   ./node_modules/date-fns
20204   ./node_modules/prettier
14124   ./node_modules/react-devtools-core
10604   ./node_modules/rxjs
9184    ./node_modules/spdx-license-list
8528    ./node_modules/@apollo
8048    ./node_modules/core-js-pure
5212    ./node_modules/@graphql-tools
5028    ./node_modules/lodash
```

### Important Factoids

Lib is only used in [one spot](https://github.com/hashicorp/terraform-cdk/blob/9f73f202968ff411d22340f0bf6413b70039a4da/packages/cdktf-cli/bin/cmds/ui/watch.tsx#L119).

**Comment by DanielMSchmidt** [comment]
@skorfmann Is this fixed now or was that part of the modules you did not include in the bundle?

**Comment by ansgarm** [comment]
Should be fixed, as it is part of the bundle (i.e. not excluded [here](https://github.com/hashicorp/terraform-cdk/pull/913/files#diff-d768f3a5afbea250e07262489aaeee93bbdeb11096017fd1074d7e95b5a9d382R61-R69)).
