### ISSUE TITLE
Handle small terminal sizes with lots of resources to display

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#115]
Due to the nature of the text rendering, using the `cdktf` cli for stacks with lots of resources in small terminal windows leads to lots of scrollback and flickering, broken text output.

Essentially, we'll have to adjust the output size dynamically to the terminal size. 

A few ideas:

- Define a fixed size for our canvas based on the terminal dimensions, and make sure elements exceeding the size won't be rendered. This would need us to implement some kind of scrolling mechanism
- Generally reduce dynamic elements shown on the screen, and use static text where possible
- Calculate canvas size and cut off overflowing elements

**Comment by skorfmann** [comment]
> > Generally reduce dynamic elements shown on the screen, and use static text where possible
> 
> I think that's the only viable option for now.
> 
> * Resources in progress would be displayed "live"
> * Resources which got applied will be rendered as static text above the "live" view
> * When everything is done, we could render a final summary (similar to `diff`)
> 
> To keep it simple, this should be the only behaviour we support for now (so, no dynamic change of rendering modes based on terminal size and resource count). Thoughts?

This could look like this and use [static elements](https://github.com/vadimdemedes/ink/tree/259edd47968081b23b176b7a7cfecc5e5757845d#static)

```
Stack: hello-terra
Done: (a static list)
 ✔ AWS_DYNAMODB_TABLE   helloterra_Hello    aws_dynamodb_table.helloterra_Hello_698
 ✔ AWS_SNS_TOPIC        helloterra_Topic0   aws_sns_topic.helloterra_Topic0_E9AB776
 ✔ AWS_SNS_TOPIC        helloterra_Topic10  aws_sns_topic.helloterra_Topic10_F78BE0
 ✔ AWS_SNS_TOPIC        helloterra_Topic11  aws_sns_topic.helloterra_Topic11_219D04
 ✔ AWS_SNS_TOPIC        helloterra_Topic12  aws_sns_topic.helloterra_Topic12_19C0FD
 ✔ AWS_SNS_TOPIC        helloterra_Topic13  aws_sns_topic.helloterra_Topic13_FE30A3
 ✔ AWS_SNS_TOPIC        helloterra_Topic14  aws_sns_topic.helloterra_Topic14_E676CF
 ✔ AWS_SNS_TOPIC        helloterra_Topic15  aws_sns_topic.helloterra_Topic15_1E2290
 ✔ AWS_SNS_TOPIC        helloterra_Topic16  aws_sns_topic.helloterra_Topic16_64479D

Resources (10 pending / 3 in progress)

 + AWS_SNS_TOPIC        helloterra_Topic17  aws_sns_topic.helloterra_Topic17_5BEE61
 + AWS_SNS_TOPIC        helloterra_Topic18  aws_sns_topic.helloterra_Topic18_FF324C
 + AWS_SNS_TOPIC        helloterra_Topic19  aws_sns_topic.helloterra_Topic19_02E397
```

I think this would solve the scrollback issue in almost all cases (given that Terraform CLI does 10 operations in parallel by default) and would likely have a very positive impact on the high cpu usage of the CLI as well.

**Comment by DanielMSchmidt** [comment]
Adding another train of thought, we could also think about remodelling the interface in a similar direction as tig.

![https://www.flickr.com/photos/jonasfonseca/3316428506/in/album-72157614470764617/](https://live.staticflickr.com/3537/3316428506_26c75859cf_z.jpg)

We could take the types on the left side (with a progress indicator?) and the resources on the right with keyboard navigation only for the left side.

**Comment by pshuman-heb** [comment]
I'd really like to see progress on this. I have a CDK Stack I'm running right now with 750 resources and it pretty much makes my entire terminal unusable during a deploy. It also seems like the terminal is locked to a 80 character width on the other side, where my terminal is much wider, which just makes everything cramped and ugly, while also making the scrollback issues even worse by breaking each resource to 2-3 lines.

**Comment by DanielMSchmidt** [comment]
We removed this view in favour of the terraform logs, so we can close this thanks to #1596
