### ISSUE TITLE
Python cdktf imports throwing error

### ISSUE THREAD

**Issue by raghavmri** [hashicorp/terraform-cdk#1152]
I am running `cdktf get` and all the modules are being loaded onto my imports folder but after that, if I try to run my app I get the following error

> Process SpawnProcess-1:
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
>     self.run()
>   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
>     self._target(*self._args, **self._kwargs)
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/env/lib/python3.9/site-packages/uvicorn/subprocess.py", line 76, in subprocess_started
>     target(sockets=sockets)
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/env/lib/python3.9/site-packages/uvicorn/server.py", line 68, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
>     return future.result()
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/env/lib/python3.9/site-packages/uvicorn/server.py", line 76, in serve
>     config.load()
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/env/lib/python3.9/site-packages/uvicorn/config.py", line 448, in load
>     self.loaded_app = import_from_string(self.app)
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/env/lib/python3.9/site-packages/uvicorn/importer.py", line 21, in import_from_string
>     module = importlib.import_module(module_str)
>   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 850, in exec_module
>   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/./main.py", line 3, in <module>
>     from imports.aws import InstanceConfig, S3BucketConfig
>   File "/home/mriblog9/gogamic-managed-cloud/backend/api-python/./imports/aws/__init__.py", line 4922
>     import aws.lambda
>                ^
> SyntaxError: invalid syntax

but there is no error in the syntax
here is a screenshot of my code
![Screenshot (207)](https://user-images.githubusercontent.com/62844922/137616276-ea81b613-af1d-49f6-947b-28e067fb5938.png)

**Comment by raghavmri** [comment]
Quick Update After the code is converted from typescript to python using **jsii** module. In the python code that is generated under the AWS folder in  __init__.py file in line 4922, the code imports AWS lambda service but the Python interpreter considers it as `lamba` keyword
Kindly refer the below screenshot for more info
![image](https://user-images.githubusercontent.com/62844922/137624531-f1d47966-0098-4c80-901c-5a08e0bc61df.png)

**Comment by raghavmri** [comment]
@jsteinich  I tried to simulate the CLI version you specified above. At first, on my windows machine, I was getting an error from jsii but I thought that it was my PC issue so I tried to create a new Instance in the digital ocean cloud and simulate the same but I get the same jsii error

The following is the output from my ubuntu instance

    > NOTE: Temp directory retained due to an error: /tmp/temp-iMj8H1 Error:
    > jsii compilation failed with non-zero exit code: 137   | Killed  
    > +----------------------------------------------------------------------------------   | Command: /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii
    > --silence-warnings reserved-word   | Workdir: /tmp/temp-iMj8H1   +----------------------------------------------------------------------------------
    >     at newError (/usr/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:58:20)
    >     at ChildProcess.<anonymous> (/usr/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:75:29)
    >     at Object.onceWrapper (node:events:510:26)
    >     at ChildProcess.emit (node:events:390:28)
    >     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12) ⠇ downloading and generating
    > modules and providers... jsii compilation failed with non-zero exit
    > code: 137   | Killed  
    > +----------------------------------------------------------------------------------   | Command: /usr/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii
    > --silence-warnings reserved-word   | Workdir: /tmp/temp-iMj8H1   +----------------------------------------------------------------------------------

The output from my windows machine 

    NOTE: Temp directory retained due to an error: C:\Users\mribl\AppData\Local\Temp\temp-xCoqOD
    Error: jsii compilation failed with non-zero exit code: 1
      | 'C:\Program' is not recognized as an internal or external command,
      | operable program or batch file.
      +----------------------------------------------------------------------------------
      | Command: C:\Users\mribl\AppData\Local\Yarn\Data\global\node_modules\jsii\bin\jsii --silence-warnings reserved-word
      | Workdir: C:\Users\mribl\AppData\Local\Temp\temp-xCoqOD
      +----------------------------------------------------------------------------------
        at newError (C:\Users\mribl\AppData\Local\Yarn\Data\global\node_modules\jsii-srcmak\lib\util.js:58:20)
        at ChildProcess.<anonymous> (C:\Users\mribl\AppData\Local\Yarn\Data\global\node_modules\jsii-srcmak\lib\util.js:75:29)
        at Object.onceWrapper (node:events:510:26)
        at ChildProcess.emit (node:events:390:28)
        at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
    ⠇ downloading and generating modules and providers...
    jsii compilation failed with non-zero exit code: 1
      | 'C:\Program' is not recognized as an internal or external command,
      | operable program or batch file.
      +----------------------------------------------------------------------------------
      | Command: C:\Users\mribl\AppData\Local\Yarn\Data\global\node_modules\jsii\bin\jsii --silence-warnings reserved-word
      | Workdir: C:\Users\mribl\AppData\Local\Temp\temp-xCoqOD
      +----------------------------------------------------------------------------------

## The following versions were used for simulation
1. Node version - v16.11.1
2. Python version - Python 3.6.9
3. Npm Version - 8.0.0 / Yarn Version -  3.0.2
5. cdktf - 0.6.4 
6. cdktf-cli - 0.6.4
7. Terraform - v1.0.9
8. OS - Ubuntu 18.04.6 LTS / Windows 10 Home

**Comment by skorfmann** [comment]
> I'm also unsure how the python aws example test isn't failing.

That's indeed concerning.

**Comment by DanielMSchmidt** [comment]
We could generate test cases for every resource in each submodule to find these issues earlier 🤔

**Comment by raghavmri** [comment]
> > I am getting the same error as mentioned above
> 
> Could you try with `cdktf-cli@next`? @raghavmri 

I did try but the same problem occurs

**Comment by jsteinich** [comment]
I'm getting a new error with the latest pre-release: https://github.com/aws/jsii/issues/3078

**Comment by raghavmri** [comment]
Hey Running `cdktf get` for python takes a very long time even in my CD environment it takes more than an hour by any chance is there a way to improve the performance for getting the constructs?

**Comment by jsteinich** [comment]
> Running `cdktf get` for python takes a very long time(>1hr) even in my CD environment it takes more than an hour by any chance is there a way to improve the performance for getting the constructs?

@raghavmri which providers / modules are you generating? I'm also see some rather slow times, so we can definitely look into that.

I'm also seeing that same error.
