### ISSUE TITLE
Check Terraform 0.13 Compatibility 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#118]
Check if there are any changes to the output of the Terraform CLI. 

Also have a look at this, to verify our current approach to provider definition still works https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md

**Comment by anubhavmishra** [comment]
Look into the official registry namespace and rewrite to `.gen/{PROVIDER_NAME}`. Essentially, we want to trim the registry specific string and make it conform to what we use in the project today. Custom providers will be generated with the long-form path of provider.

**Comment by skorfmann** [comment]
@anubhavmishra since I'll add a test for this, we'll need #36 somehow to get it merge.

**Comment by skorfmann** [comment]
All examples except Docker are working for `cdktt get`. Will look into what's the reason for this:

```
Could not find required providers, but found possible alternatives:

  hashicorp/docker -> terraform-providers/docker
```

```
cat cdktf.json

{
  "language": "python",
  "app": "pipenv run ./main.py",
  "terraformProviders": [
    "docker@~> 2.0"
  ],
  "codeMakerOutput": "imports"
}

```

**Comment by skorfmann** [comment]
docker doesn't work:

```
{
	"provider": {
		"docker": {
			"version": "~> 2.0"
		}
	}
}
```

aws works:

```
{
	"provider": {
		"aws": {
			"version": "~> 2.0"
		}
	}
}
```

**Comment by skorfmann** [comment]
Perhaps related to the Docker provider not being present in the registry? @anubhavmishra 

![Screenshot 2020-07-28 at 17 30 33](https://user-images.githubusercontent.com/136789/88687204-46696300-d0f8-11ea-8980-5b80b704c58e.png)

**Comment by skorfmann** [comment]
Ok, as described [here](https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md#explicit-provider-source-locations)

> In order to establish the hierarchical namespace, Terraform now requires explicit source information for any providers that are not HashiCorp-maintained, using a new syntax in the required_providers nested block inside the terraform configuration block

```
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
    docker = {
      source = "terraform-providers/docker"
    }
  }
  required_version = ">= 0.13"
}
```

The docker provider is not maintained in the registry and therefore fails.

So, we probably really should make the full reference mandatory in `cdktf.json`:

```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "hashicorp/aws@~> 2.0",
    "terraform-providers/docker"
  ]
}
```
For hashicorp maintained providers, this would work as well:

```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "aws@~> 2.0",
    "terraform-providers/docker"
  ]
}
```
For the actual provider block, we could probably just split by `/` and take the last element. Thoughts @anubhavmishra

**Comment by anubhavmishra** [comment]
@skorfmann I like that proposal. I think the providers are still in flux but I think they will all be moved over to the registry.
