### ISSUE TITLE
AWS Wafv2WebAcl Missing default_action

### ISSUE THREAD

**Issue by vu-bui** [hashicorp/terraform-cdk#1182]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf: `0.7.0`
language: `typescript`
prebuilt AWS provider `@cdktf/provider-aws`: `2.0.13`

### Affected Resource(s)
WAFV2.Wafv2WebAcl

### Debug Output
https://gist.github.com/vu-bui/9b2b66eaab08794edc9ad4324ee6665d

### Expected Behavior
It should be able to create a Wafv2WebAcl

### Actual Behavior
It throws `defaut_action` is missing though I did specify an empty default action
```
      defaultAction: {
        allow: {},
      },
```
It works on the previous `cdktf` and `@cdktf/provider-aws` version

**Comment by vu-bui** [comment]
I've tried, but it requires me to have at least 1 `insertHeader`...

**Comment by jsteinich** [comment]
Try
```typescript
webAcl.addOverride('default_action', [{allow : {}}]);
```
