### ISSUE TITLE
Exported APIs cannot use un-exported type "@pahud/cdktf-aws-eks.EKS.EksCluster" 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#1203]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- 0.7

### Affected Resource(s)

- aws provider

### References

> Hi  @skorfmann 
> 
> I ran into this error when I upgrade cdktf 0.6.0 to 0.7.0 from this  https://github.com/pahud/cdktf-aws-eks/pull/61
> 
> <img width="1783" alt="圖片" src="https://user-images.githubusercontent.com/278432/138653293-0f021b79-2d3d-4447-8b45-fa5d9ca94207.png">
> 
> The complete CI log https://github.com/pahud/cdktf-aws-eks/runs/3993893529?check_suite_focus=true
> 
> Looks like the `EksCluster` is an exported class but somehow it complained not an exported class:
> https://github.com/hashicorp/cdktf-provider-aws/blob/2c441c164977d7124602468bc5232dee7e03e8a9/src/EKS.ts#L659
> 
> Do you have any idea about this error?

See https://github.com/hashicorp/cdktf-provider-aws/issues/465 for more details

**Comment by skorfmann** [comment]
@pahud could you give the latest pre-release `0.8.0-pre.1` a try? it should solve the issue you saw around types

**Comment by ansgarm** [comment]
@skorfmann I think we need to first release the aws pre-built provider using cdktf 0.8 😅 Otherwise a lot of local linking (and building that pre-built provider locally) is needed.

**Comment by ansgarm** [comment]
Seems to work, I created a [PR](https://github.com/pahud/cdktf-aws-eks/pull/63) that updates to `v0.8.1`.

**Comment by ansgarm** [comment]
I'm going to close this issue as the PR I posted compiles without the error originally described in this issue. Feel free to open a new issue if any further errors might come up 👍
