### ISSUE TITLE
Handle Breaking Changes in cdktf prebuilt providers

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#1204]
The breaking change release for cdktf providers didn't work as expected. This has to be fixed for the next release cycle

**Comment by ansgarm** [comment]
Where does it create the commit message, @skorfmann?

**Comment by DanielMSchmidt** [comment]
Here: https://github.com/hashicorp/cdktf-repository-manager/blob/main/.github/workflows/upgrade-repositories.yml#L72

I chatted with @skorfmann about this today, we want to have an input to this workflow to say either breaking or not breaking change and possibly add a comment with link to the workflow to a PR when the workflow finishes.
