### ISSUE TITLE
Explicitly Test Namespaces in AWS Provider

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#1209]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- 0.7

### Affected Resource(s)

- AWS provider

The provider should be built and testes on a per namespace basis, since we had issues with single namespaces

**Comment by skorfmann** [comment]
> @skorfmann How would that look like? Having synthesizable example code for every namespace the AWS provider has?

I was thinking about some sort of auto generated testing. Not sure if that's feasible though

**Comment by DanielMSchmidt** [comment]
We figured that this is actually an upstream issue where a safe-guard was missing, tracking it under aws/jsii#3178

**Comment by ansgarm** [comment]
obsolete because this is both an upstream issue (improved there already) and because as of 0.13 we don't have specific namespaces for AWS anymore.
