### ISSUE TITLE
Bug(cdktf-cli): ink updates its dep react-reconciler that requires latest react 17.x as peer

### ISSUE THREAD

**Issue by LumaKernel** [hashicorp/terraform-cdk#1217]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

node, 0.7.0

### Affected Resource(s)

N/A

### Debug Output

N/A

### Expected Behavior

N/A

### Actual Behavior

N/A

### Steps to Reproduce

<npm client> install cdktf@0.7.0

I'm using pnpm with strict peer mode and get following error.

```text
 ERR_PNPM_INVALID_PEER_DEPENDENCY  <my-project> > cdktf-cli > ink: react-reconciler@0.26.2 requires a peer of react@^17.0.2 but version 16.14.0 was installed.
```

- https://github.com/hashicorp/terraform-cdk/blob/ac3d3902ffcf3571cff69976d7a87c320eeb68ea/packages/cdktf-cli/package.json#L69
- [ink package.json manifest line about react-reconciler](https://github.com/vadimdemedes/ink/blob/8b8e6e562c2a9b4fef917afb48948d5edda050aa/package.json#L52)
- [ink commit to drop 16.x](https://github.com/vadimdemedes/ink/commit/5b10413f57e35f542e93ab70692aee9fb08e1058#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R52)

Possible solutions: update react version, or restrict ink version with `<...` specifier in the manifest.

### Important Factoids

N/A

**Comment by ansgarm** [comment]
Hi @LumaKernel!
Thank you for submitting the issue – I added a PR that upgrades the React version.
