### ISSUE TITLE
Prebuild AWS provider doesn't have all the expected import symbols

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#1218]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf = "^0.7.0"
cdktf-cdktf-provider-aws = "^2.0.13"
python = "^3.6"

### Affected Resource(s)

Large majority of data sources are absent...
These ones are present:
```
>>> caws.DataAws
caws.DataAwsCloudcontrolapiResource(        caws.DataAwsIdentitystoreGroupConfig(
caws.DataAwsCloudcontrolapiResourceConfig(  caws.DataAwsIdentitystoreGroupFilter(
caws.DataAwsDefaultTags(                    caws.DataAwsIdentitystoreUser(
caws.DataAwsDefaultTagsConfig(              caws.DataAwsIdentitystoreUserConfig(
caws.DataAwsIdentitystoreGroup(             caws.DataAwsIdentitystoreUserFilter(
```

### Important Factoids

I inspected the source of the package `cdktf-cdktf-provider-aws` from `2.0.12` and it seems like the package structure has changed from an indirect resource generation from jsii to some manually written python classes? Not sure if this was intentional, because the data sources module is very incomplete.

**Comment by rirze** [comment]
I see. Thanks for clarifying that for me.

I'm dissatisfied with how Terraform has categorized some resources, like putting `SecurityGroup` under the `vpc` module, but after accounting for that, I am able to import it correctly. Thanks for bearing with me. 

FWIW, I tried clicking on the autogenerated API page for the provider package but it says it's an invalid URL. I would've figured this misunderstanding on my own if that API was online and accessible. Or if there's some other link to an API spec page I missed, I would be glad to be made aware.

**Comment by jsteinich** [comment]
> I'm dissatisfied with how Terraform has categorized some resources, like putting `SecurityGroup` under the `vpc` module

Yeah, we just followed the organization from within the Terraform AWS Provider docs. I believe AWS itself started with security groups under vpc and only later dual listed with ec2 within the console.



> FWIW, I tried clicking on the autogenerated API page for the provider package but it says it's an invalid URL. I would've figured this misunderstanding on my own if that API was online and accessible. Or if there's some other link to an API spec page I missed, I would be glad to be made aware.

Unfortunately there really isn't anything else at the moment. See #748 



> On top of that, my autocomplete does not pick up service level modules and their import symbols. I'll try to see if something is wrong with my editor setup, since that would also make discovery of these classes easier.

That's unfortunate. One of the goals of splitting the modules was to improve the editor experience. Please let us know if you find any improvements. Also, what editor are you using?
