### ISSUE TITLE
Add `.fqn` for `TerraformLocal` like resources.

### ISSUE THREAD

**Issue by LumaKernel** [hashicorp/terraform-cdk#1243]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`TerraformLocal` has no member `.fqn`. `.expression` is not enough.

Example: Having following script

```ts
const some = new SomeResource(this, 'some', {...});
const auth = `${some.user}:${some.pass}`;
const authLocal = new TerraformLocal(this, 'authLocal', {
  value: auth,
});
```

and want to combine with tf build-in functions.

- `` `\${base64(${auth})}` ``: `auth` is in form of `${...}`.
- `` `\${base64("${auth}")}` ``: `"` will be escaped.
- `` `\${base64(${authLocal.value})}` ``: in form of `${...}`.
- `` `\${base64("${authLocal.value}")}` ``: `"` will be escaped.
- `` `\${base64(${authLocal.expression})}` ``: in form of `${...}`.
- `` `\${base64(local.authLocal.value)}` ``: working.

- `` `\${base64(${authLocal.fqn}.value)}` ``: want.

### References

- https://github.com/hashicorp/terraform-cdk/issues/577
- https://github.com/hashicorp/terraform-cdk/issues/577#issuecomment-782172148
  - > You could use the fqn method of the resource object to get the name. Theres also a TerraformLocal class to represent locals.
  - But cannot combine them.

**Comment by ansgarm** [comment]
Hi @LumaKernel!

Have you tried to use the Terraform function wrappers [we expose](https://www.terraform.io/docs/cdktf/concepts/functions.html)?

```ts
import { Fn } from 'cdktf';

const some = new SomeResource(this, 'some', {...});
const auth = `${some.user}:${some.pass}`;
const authLocal = new TerraformLocal(this, 'authLocal', {
  value: Fn.base64(auth),
});
```

**Comment by ansgarm** [comment]
Found a workaround for the meantime:
```ts
// import { Pet, Password } from "@cdktf/provider-random";

const pet = new Pet(this, "pet");
const pass = new Password(this, "password", { length: 10 });

const auth = `${pet.id}:${pass.id}`;

const local = new TerraformLocal(this, "local", { value: auth });

const base64Local = new TerraformLocal(this, 'base64', Fn.base64encode(Fn.lookup(local.expression, "value", "")))

new TerraformOutput(this, 'out', {
  value: base64Local.asString
});
```

But it probably still makes sense to expose a more native way to access properties from user-defined maps (such as happening here with the `local.value`).

**Comment by LumaKernel** [comment]
Thank you, I didn't know `Fn.*` modules and proper usage of `.expression`, `.asString` and others.

**Comment by jsteinich** [comment]
There generally isn't a need to use `TerraformLocal` as you can use a local variable within your program instead. i.e.
```typescript
const auth = Fn.base64(`${some.user}:${some.pass}`);
```

Perhaps the object was intentional, but in general that isn't needed. You can use directly:
```typescript
const authLocal = new TerraformLocal(this, 'authLocal', Fn.base64(auth));
```

**Comment by DanielMSchmidt** [comment]
Seems like a proper workaround was found 👍
