### ISSUE TITLE
Convert function cdktf-cli always errors with Maximum call stack size exceeded

### ISSUE THREAD

**Issue by nandac** [hashicorp/terraform-cdk#1247]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

**cdktf-cli version:** 0.7.0
**Terraform version:** 0.15.5
**Python version:** 3.9

### Affected Resource(s)

`cdktf convert` command fails with the error `Maximum call stack size exceeded` whatever the file used maybe. Downgrading the CLI to 0.6.4 did not help. Upgrading to the latest development version also did not help.

### Debug Output

https://gist.github.com/nandac/7f7522a6e0de22ea01f6f5428943c7df

### Expected Behavior
Converted CDKTF content should either be available in the file provided or printed to stdout.

### Actual Behavior
Errors out with `Maximum call stack size exceeded` with output provided in the gist.

### Steps to Reproduce
Assuming `versions.tf` contains the following content:
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }

    external = {
      source  = "hashicorp/external"
      version = "~> 2.0"
    }

    local = {
      source  = "hashicorp/local"
      version = "~> 2.0"
    }

    null = {
      source  = "hashicorp/null"
      version = "~> 3.0"
    }

    spotinst = {
      source  = "spotinst/spotinst"
      version = "~> 1.0"
    }

    template = {
      source  = "hashicorp/template"
      version = "~> 2.2"
    }
  }

  required_version = "0.15.5"
}
```

On the console I tried:
`cat versions.tf | cdktf convert --provider hashicorp/aws --language python`

### References

- #0000

**Comment by ansgarm** [comment]
Hi @nandac!
Thank you for the reproduction steps, I could reproduce the issue. It seems that `findFileAboveCwd` does not properly break the recursion if no `cdktf.json` file could be found.

A workaround would be to run the `convert` command in a directory that contains a `cdktf.json` file. It is only used to [determine the Terraform providers used](https://github.com/hashicorp/terraform-cdk/blob/2b681d4ec6705355d9ab3fb7e07ea3433ba215ea/packages/cdktf-cli/bin/cmds/convert.ts#L85) – so it won't affect the output from convert if no providers are specified in the `cdktf.json`.

I will also create a PR with a fix, but that would need to be released first (or merged if you want to use the pre-release build).

**Comment by nandac** [comment]
Thank you so much for your reply.

I will try out what you have suggested.

Many thanks.
