### ISSUE TITLE
golang: how to include providers with dashes?

### ISSUE THREAD

**Issue by figadore** [hashicorp/terraform-cdk#1250]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.6.4

### Affected Resource(s)

google-beta.*

### Debug Output

```
generated/hashicorp/google-beta/google-beta.go:2:15: syntax error: unexpected -, expecting semicolon or newline
cdktf encountered an error while synthesizing
```

### Expected Behavior

google-beta should be converted to google_beta or googlebeta? or a way to alias providers should exist?

### Actual Behavior

google-beta.go starts with

```
package google-beta
```

which is invalid go

### Steps to Reproduce
Run `cdktf init --template="go" --local`

Add the following to cdktf.json
```json
  "terraformProviders": [
    "hashicorp/google@~> 3.90",
    "hashicorp/google-beta@~> 3.90",
  ],
```

Run `cdktf get`

Run `cdktf synth`

**Comment by ansgarm** [comment]
Hi @figadore! Thank you for reporting the bug 👍 I created a PR and with the next release of cdktf-cli this will work.
Until we release a new version `cdktf-cli@next` should work (as soon as the build finishes after merging the PR).
