### ISSUE TITLE
Add pre-built provider for Helm

### ISSUE THREAD

**Issue by chiayuan** [hashicorp/terraform-cdk#1251]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Helm provider is one of most used providers in Terraform.  
Also, I find it very convenient to install some infra-wise helm charts using CDKTF when provisioning infrastructure,  
such as [AWS VPC CNI](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-vpc-cni) for custom CNI networking [1].

And thanks to Terraform CDK team,   
now we are using CDKTF 0.7 with pre-built AWS Provider, it is such a pleasure when developing!

### References

[1] https://github.com/terraform-aws-modules/terraform-aws-eks/issues/519

**Comment by ansgarm** [comment]
Thank you, @chiayuan!
Great idea, I added a [PR](https://github.com/hashicorp/cdktf-repository-manager/pull/29) to add `helm` to the pre-built providers.

**Comment by ansgarm** [comment]
There you go: https://github.com/hashicorp/cdktf-provider-helm/releases 🎉
