### ISSUE TITLE
AWS Terraform provider `> 3.64.0` cannot be built for Java

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1260]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.7

### Affected Resource(s)

```/__w/terraform-cdk/terraform-cdk/examples/java/aws/src/main/java/imports/aws/AwsProviderEndpoints.java:[6234,19] too many parameters```

### Debug Output

> Error: ROR] COMPILATION ERROR : 
> Error: ROR] /__w/terraform-cdk/terraform-cdk/examples/java/aws/src/main/java/imports/aws/AwsProviderEndpoints.java:[6234,19] too many parameters
> Error: ROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project aws: Compilation failure
> Error: ROR] /__w/terraform-cdk/terraform-cdk/examples/java/aws/src/main/java/imports/aws/AwsProviderEndpoints.java:[6234,19] too many parameters
> Error: ROR] 
> Error: ROR] -> [Help 1]
([source](https://github.com/hashicorp/terraform-cdk/runs/4114745215?check_suite_focus=true))

### Expected Behavior

should compile

### Actual Behavior

does not compile

### Steps to Reproduce

try `cdktf get` in a Java project for specified AWS provider version. Fails when compiling the generated Java code.

### References

Similar problem as https://github.com/hashicorp/terraform-cdk/issues/365 but this time for the provider and not a module.

**Comment by skorfmann** [comment]
While this waits for https://github.com/aws/jsii/pull/3133 would there be a potential workaround?

**Comment by maksymgendin** [comment]
@skorfmann A downgrade to previous version worked for me:

`"terraformProviders": ["aws@= 3.63.0"]`

**Comment by skorfmann** [comment]
> A downgrade to previous version worked for me:

Yes, thanks - Was more thinking about something which we could do on our end to support the latest AWS provider without being blocked by the upstream dependency to jsii. With re:invent around the corner, I can imagine frequent updates which people probably wanna try :)

**Comment by ansgarm** [comment]
> While this waits for [aws/jsii#3133](https://github.com/aws/jsii/pull/3133) would there be a potential workaround?

Not shipping updates for the Java AWS pre-built provider until the upstream issue is resolved, would technically work.
Or using a fork of JSII with the PR in it.

**Comment by skorfmann** [comment]
> > While this waits for [aws/jsii#3133](https://github.com/aws/jsii/pull/3133) would there be a potential workaround?
> 
> Not shipping updates for the Java AWS pre-built provider until the upstream issue is resolved, would technically work. Or using a fork of JSII with the PR in it.

But a Java user wouldn't be able to build it locally either. Depending on which direction the upstream issue takes, I'm wondering if special casing could be an option here.

**Comment by ansgarm** [comment]
(this is fixed upstream, but we cannot upgrade jsii due to https://github.com/hashicorp/terraform-cdk/issues/1152)
