### ISSUE TITLE
AssumeRole not working with Multi-Accounts

### ISSUE THREAD

**Issue by gayanhewa** [hashicorp/terraform-cdk#1267]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

<img width="231" alt="Screen Shot 2021-11-08 at 5 14 12 pm" src="https://user-images.githubusercontent.com/1681406/140692940-4b3b2afa-106c-4bf5-b5dc-18498971e87f.png">

<img width="198" alt="Screen Shot 2021-11-08 at 5 14 27 pm" src="https://user-images.githubusercontent.com/1681406/140692968-208a7a20-7b00-43ff-9253-7a0db5d5798f.png">

<img width="435" alt="Screen Shot 2021-11-08 at 5 15 54 pm" src="https://user-images.githubusercontent.com/1681406/140693160-3912b7b2-97de-4623-92b9-ed91727c5123.png">

### Affected Resource(s)

`AwsProvider` doesn't seem to assume the role.

```
export default class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string, config: Config) {
    super(scope, id);

    const { region, allowedAccountIds, roleArn, env } = config;

    new AwsProvider(this, "aws", {
      region,
      allowedAccountIds,
      assumeRole: {
        roleArn,
        sessionName: env,
      },
    });

    new S3Backend(this, {
      bucket: "terraform-state-management-mystack",
      key: "${env}-my-stack-service/tf.state",
      region,
    });
  }
}
```

### Expected Behavior

Terrform to initialize with the remote backend

### Actual Behavior

<img width="896" alt="Screen Shot 2021-11-08 at 5 17 13 pm" src="https://user-images.githubusercontent.com/1681406/140693239-e6a0c16f-8244-44f2-980f-25e972503bcd.png">

### Steps to Reproduce

1. Multiple account setup with an IAM role to assume on a sub-account
2. S3Backend is configured to point to a s3 bucket on the sub-account

- #0000

**Comment by ansgarm** [comment]
Hi @gayanhewa!
Thank you for reporting. The AWS Provider config for `assumeRole` only affects the resources Terraform manages, not your state bucket. From your error message it appears that your Terraform state in AWS S3 is not accessible without a role.
The role for Terraform backends can be [set separately](https://www.terraform.io/docs/language/settings/backends/s3.html#assume-role-configuration). Supplying `assumeRole` to your `S3Backend` might resolve your issue.

**Comment by gayanhewa** [comment]
> Hi @gayanhewa! Thank you for reporting. The AWS Provider config for `assumeRole` only affects the resources Terraform manages, not your state bucket. From your error message it appears that your Terraform state in AWS S3 is not accessible without a role. The role for Terraform backends can be [set separately](https://www.terraform.io/docs/language/settings/backends/s3.html#assume-role-configuration). Supplying `assumeRole` to your `S3Backend` might resolve your issue.
> 
> https://github.com/hashicorp/terraform-cdk/blob/12bdf63493b2fd6182aae63d60d864c79e2e444f/packages/cdktf/lib/backends/s3-backend.ts#L43
> 
> 
> https://github.com/hashicorp/terraform-cdk/blob/12bdf63493b2fd6182aae63d60d864c79e2e444f/packages/cdktf/lib/backends/s3-backend.ts#L46

Setting the role and session on the S3Backend solved the problem.

**Comment by ansgarm** [comment]
Great!
