### ISSUE TITLE
Deploy summary is inconsistent

### ISSUE THREAD

**Issue by waxb** [hashicorp/terraform-cdk#1269]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
waxb@mbp:cdktf-azure-go$ cdktf --version
0.7.0
waxb@mbp:cdktf-azure-go$ cat cdktf.json 
{
    "language": "go",
    "app": "go run main.go",
    "codeMakerOutput": "generated",
    "terraformProviders": ["hashicorp/azurerm@~> 2.74"],
    "terraformModules": [],
    "context": {
        "excludeStackIdFromLogicalIds": "true",
	"allowSepCharsInLogicalIds": "true"
    }
}
waxb@mbp:cdktf-azure-go$ go version
go version go1.17.2 darwin/amd64
```

### Affected Resource(s)

Resource existing between keyboard and chair

### Debug Output

I create a resource[group] at first then update it the `Summary` field is inconsistent with what a terraform plan would spit out:

```
waxb@mbp:cdktf-azure-go$ cdktf apply
Deploying Stack: cdktf-azure-go
Resources
 ✔ AZURERM_RESOURCE_GRO test_rg             azurerm_resource_group.test_rg
   UP

**Summary: 1 created, 0 updated, 0 destroyed.**

Output: name = original_rg
waxb@mbp:cdktf-azure-go$ sed -i 's/original_rg/updated_rg/' main.go
waxb@mbp:cdktf-azure-go$ cdktf apply
Deploying Stack: cdktf-azure-go
Resources
 ✔ AZURERM_RESOURCE_GRO test_rg             azurerm_resource_group.test_rg
   UP

**Summary: 1 created, 0 updated, 0 destroyed.**

Output: name = updated_rg
waxb@mbp:cdktf-azure-go$ 
```

1st plan:
```
waxb@mbp:cdktf-azure-go$ cdktf apply
Stack: cdktf-azure-go
Resources
 + AZURERM_RESOURCE_GRO test_rg             azurerm_resource_group.test_rg
   UP

**Diff: 1 to create, 0 to update, 0 to delete.**

Do you want to perform these actions?
 CDK for Terraform will perform the actions described above.
 Only 'yes' will be accepted to approve.
```
2nd plan after modification:
```
waxb@mbp:cdktf-azure-go$ cdktf apply
Stack: cdktf-azure-go
Resources
 - AZURERM_RESOURCE_GRO test_rg             azurerm_resource_group.test_rg
   UP

**Diff: 0 to create, 0 to update, 1 to delete.**

Do you want to perform these actions?
 CDK for Terraform will perform the actions described above.
 Only 'yes' will be accepted to approve.
```

### Expected Behavior
Terraform plan should look like this (maybe the `update` value is never updated?)
on the first run:
**Diff: 1 to create, 0 to update, 0 to delete.**
on the second run:
either
 **Diff: 0 to create, 1 to update, 0 to delete.** 
or 
**Diff: 1 to create, 0 to update, 1 to delete.**

**Comment by DanielMSchmidt** [comment]
#114 Could solve this as well

**Comment by DanielMSchmidt** [comment]
We removed this view in favour of the terraform logs, so we can close this thanks to #1596
