### ISSUE TITLE
Unable to set provisioner for remote-exec

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1271]
Trying to use the remote-exec provisioner in cdktf but it seems the @cdktf/provider-aws does not have it? 
This is what I am referring to https://www.terraform.io/docs/language/resources/provisioners/remote-exec.html

**Comment by skorfmann** [comment]
Thanks for creating this issue. While there's no explicit support for this for now, an [escape hatch](https://www.terraform.io/docs/cdktf/concepts/providers-and-resources.html#escape-hatch) could be used to add it anyway.

**Comment by jin-ahn** [comment]
Got it.  Thank you.

**Comment by EdDanileyko** [comment]
Hello @jin-ahn , I'm wondering if you ever got this to work?

I'm attempting the following for each EC2 instance i want to install nginx on:
`webservers.forEach(instance => (
      instance.addOverride("provisioner", [
        {
          "remote-exec": {
            inline: [
              "sudo apt upgrade -y && sudo apt install nginx -y"
            ]
          }
        }
      ])
    ));`

The output however contains the following error:
`$ cdktf deploy --auto-approve
⠹ planning CMS...
[2022-02-13T21:47:55.705] [ERROR] default - ╷
│ Error: Extraneous JSON object property
│ 
│   on cdk.tf.json line 187, in module.webserver-us-east-1a:
│  187:       "provisioner": [
│ 
│ No argument or block type is named "provisioner".
╵
non-zero exit code 1`

Have you dealt with this?

**Comment by ansgarm** [comment]
Hi @EdDanileyko,

could you paste the generated `cdk.tf.json` contents for those webserver resources?

I just tried the following successfully:
```ts
const test = new NullResource(this, "test", {});
test.addOverride("provisioner", [
  {
    "local-exec": { command: "echo 'Hello World!'" },
  },
]);
```
which generated the following json
```jsonc
"resource": {
    "null_resource": {
      "test": {
        "provisioner": [
          {
            "local-exec": {
              "command": "echo 'Hello World!'"
            }
          }
        ]
        // ... (excluded metadata)
      }
    }
  },
```

**Comment by EdDanileyko** [comment]
of course:

```
"webserver-us-east-1a": {
      "//": {
        "metadata": {
          "path": "CMS/webserver-us-east-1a",
          "uniqueId": "webserver-us-east-1a"
        }
      },
      "ami": "${data.aws_ami.ubuntu-ami.image_id}",
      "instance_type": "t2.micro",
      "key_name": "octaviius-web-master-keypair",
      "name": "octaviius-web-uat-${aws_subnet.private-subnet-us-east-1a.availability_zone}-webserver",
      "provisioner": [
        {
          "remote-exec": {
            "inline": [
              "sudo apt upgrade -y && sudo apt install nginx -y"
            ]
          }
        }
      ],
      "source": "terraform-aws-modules/ec2-instance/aws",
      "subnet_id": "${aws_subnet.private-subnet-us-east-1a.id}",
      "tags": {
        "application_env": "uat",
        "application_name": "octaviius-web",
        "project_id": "1201634690686223",
        "project_name": "infrastructure",
        "project_owner": "Ed Danileyko",
        "resource_role": "webserver"
      },
      "version": "~> 3.4.0",
      "volume_tags": {
        "application_env": "uat",
        "application_name": "octaviius-web",
        "project_id": "1201634690686223",
        "project_name": "infrastructure",
        "project_owner": "Ed Danileyko",
        "resource_role": "webserver"
      },
      "vpc_security_group_ids": [
        "${aws_security_group.private-sg.id}"
      ]
    },
    ```

**Comment by EdDanileyko** [comment]
I should add that the EC2 instance is of this type:
https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/latest

**Comment by EdDanileyko** [comment]
> I should add that the EC2 instance is of this type: https://registry.terraform.io/modules/terraform-aws-modules/ec2-instance/aws/latest

This may be the problem. You can ignore this for now but i appreciate the super quick response.

**Comment by ansgarm** [comment]
Ah! Didn't know you were using a module @EdDanileyko. It is not possible to set a provisioner on the module. However, as [this issue comment](https://github.com/terraform-aws-modules/terraform-aws-ec2-instance/issues/48#issuecomment-767766578) in the module repo suggests, you can add a null resource containing that provisioner.
I'm happy to help you with doing that in CDKTF, if you have further questions (as the linked comment describes the solution in HCL).

**Comment by EdDanileyko** [comment]
This looks very promising. I appreciate the tip. I will likely be reaching out about cdktf implementation :) thanks again!

**Comment by jin-ahn** [comment]
sorry for late reply but yes using the null-provider with remote-exec worked for me.
