### ISSUE TITLE
chore(lib): Deprecate Resource in favour of Construct

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#1273]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are practically 2 ways to create abstractions within cdktf right now:

1. [Resource](https://github.com/hashicorp/terraform-cdk/blob/f4dc243658f181aea92aed7519ef63a0f4f778ff/packages/cdktf/lib/resource.ts)
1. [Construct](https://github.com/aws/constructs/blob/cd5aadbaa45cece2697d4f284fee6b885401aecd/src/construct.ts)

`Resource` is just a very thin layer on top fo `Construct` and is not doing anything particularly useful and I don't recall why it got introduced in the first place. Since it's regularily causing confusion, we should deprecated and eventually remove `Resource` in favour of `Construct`.

### Example

The following example shows that both versions are possible and there's no practical difference.

```ts
import { Construct } from "constructs";
import { App, Resource, TerraformStack } from "cdktf";
import { AwsProvider, S3 } from './.gen/providers/aws'

class MyResourceConstruct extends Resource {
  public readonly foo: string;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.foo = "bar";

    new S3.S3Bucket(this, "MyBucket");
  }
}

class MyConstruct extends Construct {
  public readonly foo: string;

  constructor(scope: Construct, id: string) {
    super(scope, id);

    this.foo = "bar";

    new S3.S3Bucket(this, "MyBucket");
  }
}


class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    // define resources here

    new AwsProvider(this, "aws", {
      region: "us-east-1"
    });

    new MyResourceConstruct(this, "my-resource");
    new MyConstruct(this, "my-construct");
  }
}

const app = new App();
new MyStack(app, "foobar");
app.synth();
```

**Comment by jsteinich** [comment]
It's slightly more effort to get a `TerraformStack`, but that doesn't really seem like enough of a reason to keep it around.
