### ISSUE TITLE
Fn.Element to go over a list of elements

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1280]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf & Language Versions

cdktf - 0.7.0
node - 16.2.0
typescript

### Affected Resource(s)

Essentially trying to recreate this feature of kubectl (https://registry.terraform.io/providers/gavinbunney/kubectl/latest/docs/data-sources/kubectl_filename_list) to go through a list of yamls passed in as datasources.

I have the following 
```
   new kubectl.KubectlProvider(this, "kubectl", {
      configPath: this.kubeConfig,
      loadConfigFile: true
    })

    const kubeyaml = new kubectl.DataKubectlFilenameList(this, "kubeyaml", {
      pattern: "${path.module}/../../../src/manifests/*.yaml"
      //path for file is based on cdktf.out/stacks/stackname
    })

    const kubeapply = new kubectl.Manifest(this, "kubeapply", {
      yamlBody: Fn.file(Fn.element("${kubeyaml.matches}", "${count.index}"))
    })
    kubeapply.addOverride(
      "count",
      kubeyaml.matches.length
    );
```

### Expected Behavior
Issue is with this line specifically `yamlBody: Fn.file(Fn.element("${kubeyaml.matches}", "${count.index}"))`
I should have a way to refer to `count` since I have the addOverride. Typically this is done by "${count.index}"
However, when trying to pass that into `Fn.element` it throws an errow because it is reading that as a string, when it is expecting a number. 

### Important Factoids

I tried replacing the line with `yamlBody: `\${file(element(${kubeyaml.matches}, count.index))}`,`
but that throws an error telling me to use Fn.element

**Comment by jsteinich** [comment]
Have you tried using `Token.asNumber("count.index")` as input to `Fen.element`?
I also think you'll want `Fn.length(kubeyaml.matches)` as the length of the matches array isn't known at synth time.

Another alternative is to simply list files in typescript and then loop through them to create manifests.

**Comment by jin-ahn** [comment]
thanks for the feedback, will have to go back and try it

**Comment by DanielMSchmidt** [comment]
#430 is the issue tracking this, will close this one as duplicate :)

**Comment by DanielMSchmidt** [comment]
We have the concept of iterators now that solve the iterating over something portion: https://www.terraform.io/cdktf/concepts/iterators
