### ISSUE TITLE
Nested Responses from Remote State

### ISSUE THREAD

**Issue by gayanhewa** [hashicorp/terraform-cdk#1286]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf - 0.7.0

### Affected Resource(s)
```
    const internalLBConfiguration = new DataTerraformRemoteStateS3(this, "internal", {
      bucket: s3BackendBucket,
      key: 'loadbalancers/internal/terraform.tfstate',
      region
    });
    
   const lbConfig = internalLBConfiguration.get("lb");

```

### Expected Behavior
Ability to access the values in the object returned by the terraform output. In this case the details related to 

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elb#attributes-reference

```
  lbConfig.arn
  lbConfig.dnsName
```
### Actual Behavior
```
internalLBConfiguration.get("lb");
```

Returns undefined

### Steps to Reproduce

Import the remote state from any terraform resource, that returns a nested output.

**Comment by ansgarm** [comment]
Hi @gayanhewa
I had a look at the Terraform Docs on remote state datasources and it appears that [only root outputs can be accessed](https://www.terraform.io/docs/language/state/remote-state-data.html#root-outputs-only).

What kinds of outputs does the `loadbalancers/internal` Terraform module have? You might either need to add some or use the ones that contain the `arn` and the `dnsName` attributes.

**Comment by gayanhewa** [comment]
> Hi @gayanhewa I had a look at the Terraform Docs on remote state datasources and it appears that [only root outputs can be accessed](https://www.terraform.io/docs/language/state/remote-state-data.html#root-outputs-only).
> 
> What kinds of outputs does the `loadbalancers/internal` Terraform module have? You might either need to add some or use the ones that contain the `arn` and the `dnsName` attributes.

We nest the output from the elb respirce in another name. So it makes perfect sense then, But that does mean, I need to flatten out the outputs if I want to access them on CDK

**Comment by ansgarm** [comment]
> We nest the output from the elb resource in another key.

Could you explain what you mean by that? Maybe with an example?

> That means, I need to flatten out the outputs if I want to access them on CDK.

You need explicit outputs, yes. But they don't have to be flat (they could also be maps or arrays for example). But this is not only true for CDKTF but also for Terraform.

**Comment by gayanhewa** [comment]
For an instance, one of my Terraform modules have this in the output

```
output "lb" {
  value = aws_lb.this
}
```

Basically it wraps the output from the aws_lb resource in a key `lb`

<img width="98" alt="Screen Shot 2021-11-11 at 9 28 59 pm" src="https://user-images.githubusercontent.com/1681406/141282528-bb539b6d-e00a-434d-86c4-c17a216dabd5.png">

In this case I can access the dns_name from the remote state `internalLBConfiguration.get("dns_name")` but not `internalLBConfiguration.get("lb.arn")`

**Comment by jsteinich** [comment]
I would expect `internalLBConfiguration.get("lb")` to have a value, but it is just a reference, so you won't be able to directly access anything from it. You could pass it to a function i.e. `Fn.element` and that would likely get you a reference to the nested property.

If `internalLBConfiguration.get("lb.arn")` isn't working, you may be able to do `internalLBConfiguration.get('lb["arn"]')`
