### ISSUE TITLE
Can't destroy Batch Compute Environment with custom IAM role with attached policy

### ISSUE THREAD

**Issue by janschloss** [hashicorp/terraform-cdk#1297]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

    "cdktf": "^0.7.0",
    "cdktf-cli": "^0.7.0",

### Affected Resource(s)

IamRole
IamPolicyAttachment
BatchComputeEnvironment

### Expected Behavior

When usind cdktf destroy BatchComputeEnvironment should be destroyed.

### Actual Behavior

BatchComputeEnvironment is not being destroyed. The reason is probably that the IamPolicyAttachment is removed from the IamRole first which then removes the necessary permissions to delete the BatchComputeEnvironment.

### Steps to Reproduce

``` 
    const batchServiceRole = new IAM.IamRole(this, `${this.prefix}-batch-service-role`, {
      name: `${this.prefix}-batch-service-role`,
      assumeRolePolicy: JSON.stringify({
        Version: "2012-10-17",
        Statement: [
          {
            Action: "sts:AssumeRole",
            Effect: "Allow",
            Principal: {
              Service: "batch.amazonaws.com",
            },
          },
        ],
      }),
    });

    new IAM.IamPolicyAttachment(this, `${this.prefix}-batch-service-role-policy-attachment`, {
      name: `${this.prefix}-batch-policy-statement`,
      roles: [batchServiceRole.name],
      policyArn: "arn:aws:iam::aws:policy/service-role/AWSBatchServiceRole",
    });

    const batchComputeEnvironment = new Batch.BatchComputeEnvironment(this, `${this.prefix}-compute-environment`, {
      computeEnvironmentName: `${this.prefix}-compute-environment`,
      type: "MANAGED",
      serviceRole: batchServiceRole.arn,
      computeResources: {
        maxVcpus: 10,
        subnets: remoteState.getList("123"),
        securityGroupIds: ["123"],
        type: "FARGATE",
      },
    });
``` 

Deploy and destroy.

### References

- #0000

**Comment by skorfmann** [comment]
I'm not familiar with `BatchComputeEnvironment`. However, you could define an explicit dependency between `IamPolicyAttachment` and `BatchComputeEnvironment` to see if the dependency is really the underlying issue. 

Each resource takes a `dependsOn` property in the constructor.

**Comment by janschloss** [comment]
@skorfmann I found out that AWS does not recommend to use a custom IAM role for this resource anymore so I just deleted it and AWS assigns a fitting role themselves, so I guess this issue is not really relevant, feel free to close.
