### ISSUE TITLE
Add pre-built provider for Open Telekom Cloud

### ISSUE THREAD

**Issue by mmarko08154711** [hashicorp/terraform-cdk#1304]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please consider adding the Open Telekom Provider (opentelekomcloud) to the list of pre-built providers - it would be great to be able to use the awesomeness of the cdktf also with this provider.

Thanks!

**Comment by ansgarm** [comment]
Hi @mmarko08154711!
Thank you for the suggestion.
I added it: https://github.com/hashicorp/cdktf-provider-opentelekomcloud
The initial build might take a bit, but it should be up in an hour or two (if nothing goes wrong 😄).

**Comment by mmarko08154711** [comment]
Hi @ansgarm!
That was fast :1st_place_medal:
Great work, have a lovely day and thanks a lot!
