### ISSUE TITLE
First class error support for cdktf

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/terraform-cdk#131]

**Comment by DanielMSchmidt** [comment]
Closing this as aws/jsii#1840 is closed now 👍

**Comment by ansgarm** [comment]
@DanielMSchmidt Hm.. the issue you linked was closed as a duplicate of https://github.com/aws/jsii/issues/47 😅

**Comment by schersh** [comment]
Related to https://github.com/hashicorp/terraform-cdk/issues/1103

**Comment by xiehan** [comment]
Some aspects of this issue have been resolved over the years. There might still be areas we can improve but if so, let's file new, separate and more specific issues; this issue itself is too broad and vague.
