### ISSUE TITLE
Rename synth to either compile/transpile/generate

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-cdk#1312]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It was a little bit hard to understand why synth was used as a command in `cdktf`. 
As I understand it, `cdktf` compiles from different languages to a single target artifact: JSON that terraform can understand.
It is not very much different from a compiler such as LLVM or GCC that takes code (potentially from different languages) and produces for all those languages a target artifact such as an executable.

Maybe this comparison could help people and in particular, developers understand better the goal of cdktf and how it looks like the compiler they use when they work with a given language.

**Comment by skorfmann** [comment]
> It was a little bit hard to understand why synth was used as a command in `cdktf`.

The `synth` naming is common in the CDK ecosystem, see [aws cdk](https://docs.aws.amazon.com/cdk/latest/guide/cli.html) and [cdk8s](https://cdk8s.io/docs/latest/cli/synth/). 

We're currently in the process of moving existing docs over to terraform.io. Looks like https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/synthesizing-config.md hasn't been fully migrated yet. Is there anything you'd add to these docs to make it easier to understand what it's doing?

**Comment by remyleone** [comment]
I would add to the documentation that those are standard across the community. I came to CDK by your project and not by `aws cdk` nor `cdk8s`. 
Regarding the documentation you mention I would add that you need to do a cdktf get to ensure that the proper files are generated in the gen folder.

**Comment by mxplusb** [comment]
I can agree that `synth` isn't very understandable. This is also my first intro to a CDK, and I would agree that `compile` or `generate` would be better than `synth`.

**Comment by ansgarm** [comment]
Hi 👋
We discussed this and decided against renaming `synth`, mainly because it is already the common naming in the CDK ecosystem (as Sebastian already mentioned).
However, we want to make this more clear and are happy to improve our docs to make this more clear.
