### ISSUE TITLE
Add tutorial about how to use CDK with a developer version of a terraform provider

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-cdk#1314]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As a Terraform provider implementer, I work with uncommitted versions of a given terraform provider. I would like to be able to test those unreleased versions of my terraform provider with CDK. 
In terraform, I can use [Developpement Override](https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers) to test. Could you add documentation about how to do it with CDK?

### References

- https://www.terraform.io/docs/cli/config/config-file.html#development-overrides-for-provider-developers

**Comment by jsteinich** [comment]
There is a small section in the docs about this: https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers.md#using-a-local-provider

**Comment by remyleone** [comment]
Is there a way to find this content on <https://www.terraform.io/docs/cdktf/index.html> ?

**Comment by DanielMSchmidt** [comment]
This information is here: https://www.terraform.io/docs/cdktf/concepts/providers-and-resources.html#use-a-local-provider

**Comment by remyleone** [comment]
Perfect :)
