### ISSUE TITLE
Add option to override nodejs version warnings

### ISSUE THREAD

**Issue by remyleone** [hashicorp/terraform-cdk#1316]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have the latest version of node.js installed with homebrew:

```
$ node --version
v17.0.1
```

When I run `cdktf synth` in the boilerplate project, I get:

```
[2021-11-17T16:50:56.708] [ERROR] default - !!                                                                                  !!
!!  This software has not been tested with node v17.0.1.                            !!
!!  You may to encounter runtime issues, and should switch to a supported release.  !!
!!                                                                                  !!
!!  As of the current release, supported versions of node are:                      !!
!!  - ^12.7.0                                                                       !!
!!  - ^14.5.0                                                                       !!
!!  - ^16.3.0                                                                       !!
!!                                                                                  !!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Generated Terraform code for the stacks: cdk-go
```

It is confusing because I get a message labeled as an ERROR and my code is generated anyway. 
Could you:
- Add an option to mute this warning
- Rename ERROR to warning as it does not prevent the compilation to happen.

**Comment by skorfmann** [comment]
That's coming from [jsii](https://github.com/aws/jsii/blob/f0a9ec6d9275be5126bcb2a455d43df2107a9262/packages/%40jsii/check-node/src/index.ts#L56) and would have to be addressed over there. At a first glance, I don't see an option to disable it. 

Could you please open this as an issue in jsii itself?

**Comment by remyleone** [comment]
https://github.com/aws/jsii/issues/1073

**Comment by skorfmann** [comment]
> aws/jsii#1073

I think that's a different scope which is described there. But perhaps it could be added there as well. 

Either way, I'm going to close this issue here since that's something which would have to be tackled upstream.
