### ISSUE TITLE
CLI unusable since updating (React error)

### ISSUE THREAD

**Issue by janschloss** [hashicorp/terraform-cdk#1319]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

current

### Affected Resource(s)

cli 

### Debug Output

https://gist.github.com/janschloss/f1b1a12e3f249812bfb283b764430959

### Expected Behavior

Deploy infrastructure

### Actual Behavior

Error

### Steps to Reproduce

cdktf deploy with freshly installed version

### Important Factoids

CLI installed locally as devDependency.
Deploying worked well until I hard reset my dependencies by rm -rf node_modules && npm i. I guess it might be a problem in your peer packages.

### References

- #0000

**Comment by skorfmann** [comment]
Things like this should be addressed by #881 

In this particular case, do you see the same error when you install the cli globally? How does the cdktf application look like, is it plain cdktf or is there frontend code (i.e. react) embedded as well?

**Comment by janschloss** [comment]
@skorfmann it is a plain cdktf project, backend only, using TypeScript & Node. In regards to the global cli I will get back to you. FYI The prerelease of v0.8 works, I use that as a workaround right now.

**Comment by janschloss** [comment]
@skorfmann it seems like it works with either the ^0.8.0-pre.3 version as a project dependency or with the regular version as a global dependency. However it is a requirement for us to have it as a project dependency.

By the way: Why is cdktf-cli giving back a react error? What is it used for if I may ask?

**Comment by ansgarm** [comment]
Hi @janschloss! We use [ink](https://github.com/vadimdemedes/ink) for the CLI output rendering (which uses React)

**Comment by DanielMSchmidt** [comment]
This should be solved by #913 If not please let us know and we'll reopen the issue :)
