### ISSUE TITLE
API Gateway v2 Domain Name Resource: Missing Computed Attributes

### ISSUE THREAD

**Issue by charles-salmon** [hashicorp/terraform-cdk#1332]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

**`cdktf` and `cdktf-cli`:** 0.7.0
**Node.js version:** 16.9.0

### Affected Resource(s)

`APIGatewayV2.Apigatewayv2DomainName`

### Debug Output

Varies depending on access pattern. If you're unable to get a reproduction, please leave a comment with the intended access pattern, and I'll happily attach this in a Gist.

### Expected Behavior

Target domain name / hosted zone ID is accessible from the `domainNameConfiguration` output.

### Actual Behavior

Target domain name / hosted zone ID is not accessible from the `domainNameConfiguration` attribute.

With an access pattern of `(apiGatewayDomainName.domainNameConfiguration as any)[0].targetDomainName`, the following error is produced:

```
    TypeError: Cannot read properties of undefined (reading
'targetDomainName')
        at new ApiStack (C:\path\to\repo\packages\infrastructure\dist\src\stacks\api-stack.js:138:26)
        at Object.<anonymous> (C:\path\to\repo\packages\infrastructure\dist\src\index.js:18:1)
        at Module._compile (node:internal/modules/cjs/loader:1101:14)
        at Object.Module._extensions..js
(node:internal/modules/cjs/loader:1153:10)
        at Module.load (node:internal/modules/cjs/loader:981:32)
        at Function.Module._load (node:internal/modules/cjs/loader:822:12)   
        at Function.executeUserEntryPoint [as runMain]
(node:internal/modules/run_main:79:12)
        at node:internal/main/run_main_module:17:47
```

### Steps to Reproduce

```typescript
...

const apiGatewayDomainName = new APIGatewayV2.Apigatewayv2DomainName(
  this,
  "api_gateway_domain_name",
  {
    domainName: apiDomain,
    domainNameConfiguration: {
      certificateArn: certificate.acmCertificateArnOutput,
      endpointType: "REGIONAL",
      securityPolicy: "TLS_1_2",
    },
  }
);

new Route53.Route53Record(this, "api_dns_record", {
  name: apiGatewayDomainName.domainName,
  zoneId: hostedZone.zoneId!,
  type: "A",
  alias: [
    {
      name: ???, // have tried (apiGatewayDomainName.domainNameConfiguration as any).targetDomainName
                 // and (apiGatewayDomainName.domainNameConfiguration as any)[0].targetDomainName
      zoneId: ???,
      evaluateTargetHealth: false,
    },
  ],
});
```

### Important Factoids

Nothing to note.

### References

Nothing to note.

**Comment by skorfmann** [comment]
Looks like `computed` [attributes](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_domain_name#argument-reference) are missing:

> hosted_zone_id - (Computed) The Amazon Route 53 Hosted Zone ID of the endpoint.
> target_domain_name - (Computed) The target domain name.

Confirmed that it's still an issue with the latest pre release.

**Comment by DanielMSchmidt** [comment]
This is a new feature, we did not implement this when exposing the single item lists as objects because we allow mutation of resources via setters and getters and setters need to have the same type. So if we'd add the computed attributes on the domainNameConfiguration object they would also need to part of the configuration, but you can not set them since they are computed. @skorfmann will verify that this restriction is still in place.

If it is this is a bigger change, we need to make these types of objects read-only and probably add another mechanism to mutate the (e.g. exposing a `putDomainNameConfiguration(domainConfig)` function). 

A workaround for this is to use a Terraform function: `Fn.lookup(apiGatewayDomainName.domainNameConfiguration, "target_domain_name", "default_value")`.

Since it's more work than expected I'm pushing this to the next release (this one ends tomorrow already)

**Comment by jsteinich** [comment]
There are a handful of similar issues (for example #25). We've slowly chipped away at some missing pieces, but I'd classify the current state as 3 remaining pieces missing:

1. Computed only values on already generated computed types. This is when we are already generating a `ComplexComputedList` or a `ComplexObject` but not including computed only (not optional or required) attributes. That's what's happening in this ticket.
2. Computed only values on interface only types. This is when we aren't generating a complex class (arrays or maps that can be specified) and there are some computed only properties. This is where what @DanielMSchmidt was describing comes into play. Also brings the general problem of even being able to access anything within the array or map.
3. Objects (structs) that would need to be referenced in the above two cases. We are currently only able to generate complex classes that are directly attached to the resource, but these would need to attach to the already generated computed classes (or missing computed interfaces).

We could technically solve for just the first case, but the code isn't really setup for it and changes to make it work shouldn't be needed once the other parts are added.
