### ISSUE TITLE
checkForEmptyDirectory check conflicts with --from-terraform-project

### ISSUE THREAD

**Issue by salzig** [hashicorp/terraform-cdk#1337]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- cdktf: 0.7.0
- node: v16.13.0

### Affected Resource(s)

`cdktf init`

### Debug Output

```
# within existing terraform project folder
$ cdktf init --local --from-terraform-project --template=typescript
ERROR: Cannot initialize a project in a non-empty directory
```

### Expected Behavior

i expected a new project to be initialised 

### Actual Behavior

Init fails. 

### Steps to Reproduce

see Debug Output

### References

https://github.com/hashicorp/terraform-cdk/blob/039a3a326b606cbf3d450e700d2148ee827ab54b/packages/cdktf-cli/bin/cmds/init.ts#L55

**Comment by ansgarm** [comment]
Hi @salzig!

Thank you for reporting, we should definitely improve this 👍
Currently we expect `--from-terraform-project` to be a relative path to the directory containing the Terraform code, so we should at least show an error message if nothing (or an empty string) was passed.
If you create a new directory adjacent to the one containing the Terraform code, you should be able to invoke `init` inside that directory with `--from-terraform-project "../your-terraform-dir"`.

**Comment by salzig** [comment]
ah, ok. Maybe the Help output for `--from-terraform-project` needs a hint that you should pass in a path then. As with the current version, i didn't expect to pass in a path, but rather that it will use the current path. 
```
      --from-terraform-project    Use a terraform project as the basis, CDK constructs will be generated based on the .tf files in the path 
```

But maybe that's a general problem with the help page right, as you have to guess witch options expect a value.

**Comment by DanielMSchmidt** [comment]
In the end of the line is a `[string]` but that's hard to see with long output 🤔  We should definitely improve the UX here by throwing a proper error
