### ISSUE TITLE
Type definition generation error for Terraform module in Typescript

### ISSUE THREAD

**Issue by McPatate** [hashicorp/terraform-cdk#1340]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

`0.7.0`

### Affected Resource(s)

Terraform Module

### Debug Output

https://gist.github.com/McPatate/d15e29ad887c0cba3fbc6026bb97bb7b

### Expected Behavior

It should apply / deploy with no error.

### Actual Behavior

I'm getting an error when deploying my terraform.

### Steps to Reproduce

`cdktf.json`

```json
...
  "terraformModules": [
    {
      "name": "security-group",
      "source": "terraform-aws-modules/security-group/aws",
      "version": "4.5.0"
    },
...
```
`main.ts`

```ts
    const sg = new SecurityGroup(this, 'my_sg', {
      name: 'my-sg',
      vpcId: '####',
      ingressCidrBlocks: ['10.42.0.0/16'],
      ingressWithCidrBlocks: [
        {
          // @ts-ignore
          fromPort: 3456,
          // @ts-ignore
          toPort: 3456, // or toPort: "3456"
          protocol: 'tcp',
          cidrBlock: '10.42.0.0/16'
        }
      ],
    });
```

**Comment by jsteinich** [comment]
The type of `ingress_with_cidr_blocks` in the source module is `list(map(string))`, so the ports do need to be passed as strings.
You could [file an issue with the module](https://github.com/terraform-aws-modules/terraform-aws-security-group/issues/new/choose) to provide more specific variable types.

**Comment by McPatate** [comment]
The result is the same when I pass them as strings.

So you are saying the issue is actually a wrong type definition from the module ?

**Comment by jsteinich** [comment]
> So you are saying the issue is actually a wrong type definition from the module ?

That would only be for the ability to pass as numbers rather than strings.

I took another look and I think I've found the issue. The casing of the argument needs to match what the module is using, so `toPort` -> `to_port`. Same idea for the other non-top level parameters.

**Comment by McPatate** [comment]
Oh that's odd.

I've changed to using [aws_security_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group) because the behavior of the module was weird. I won't test it, but thank you for looking into it !

I'll let you close the issue if you consider it solved :)

**Comment by jsteinich** [comment]
This is something to keep in mind if we implement #231, but even then, altering variable types based on the module code may be a bit out of reach.

**Comment by McPatate** [comment]
FYI, I've used another module for ALB creation and I've used your tip.

It works as you said, the casing matters and I pass values as strings.

**Comment by DanielMSchmidt** [comment]
I guess this is something we should improve our docs on. When working with map-type inputs one needs to resort to snake cased keys, even though all block keys have been converted for you. Maybe we can add a comment to the generated codes JS doc on the map property.
