### ISSUE TITLE
Unknown function parseInt

### ISSUE THREAD

**Issue by re-thc** [hashicorp/terraform-cdk#1358]
### cdktf & Language Versions

0.7.0, Typescript

### Affected Resource(s)

Terraform Function

### Expected Behavior

No errors

### Actual Behavior

`There is no function named "parseInt". Did you mean "parseint"?`
`Error: Call to unknown function`

### Steps to Reproduce

Use `Fn.parseInt`

**Comment by ansgarm** [comment]
Thanks for reporting @re-thc! The fix will be available with the next release (which will be 0.8 and will be released this week).
