### ISSUE TITLE
Error specifying custom modules stored in Terraform Cloud in cdktf.json.

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#1360]
> > Does cdktf support specifying custom modules stored in Terraform Cloud in cdktf.json. If so how would I go about it?
> > Right now the only workaround seems to be pointing to the git repository.
> 
> You should be able to specify using the same format as supported by the source parameter in hcl. See https://www.terraform.io/docs/cloud/registry/using.html#using-modules-in-configurations for more information.

I did as you said and ended up with the following error when running `cdktf get`
```
⠇ downloading and generating modules and providers...
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid module instance name
│ 
│   on main.tf.json line 1, in module:
│    1: {"terraform":{},"module":{"app.terraform.io_<REDACTED>_application-load-balancer_aws":{"source":"app.terraform.io/REDACTED/application-load-balancer/aws"}}}
│ 
│ A name must start with a letter or underscore and may contain only letters,
│ digits, underscores, and dashes.
╵
Error: non-zero exit code 1
```
Any help is appreciated.

Cheers.

_Originally posted by @nandac in https://github.com/hashicorp/terraform-cdk/issues/522#issuecomment-978151333_

**Comment by jsteinich** [comment]
There is indeed an issue here. You should be able to workaround it by specifying more information in your `cdktf.json` file.
For example:
```json
terraformModules: [
  {
    "source": "app.terraform.io/REDACTED/application-load-balancer/aws",
    "name": "application-load-balancer",
    "fqn": "app-terraform-io/REDACTED/application-load-balancer/aws",
    "namespace": "REDACTED/aws"
  }
]
```

**Comment by nandac** [comment]
@jsteinich Thanks that works for me.
