### ISSUE TITLE
[typescript] ALB -> listener -> targetGroup -> lambda function

### ISSUE THREAD

**Issue by PookMook** [hashicorp/terraform-cdk#1362]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey everyone, awesome project you have there, we stood up most AWS (formerly manually stood up) stack using cdktf/@cdktf/provider-aws to make sure all our environment matched and would survive catastrophic failures.
I'm hitting a block that forces me to go to the AWS cli/console for enabling lambda triggered via an ELB listener rule. Everything works flawlessly, but I can't register my lambda function to the target group.
Could we add the `loadBalancer` property on the `LambdaFunction`, so that it can get registered just like `EcsService` has. Or just allow to registering a lambda arn to the `LbTargetGroup` ?

Here's our code for the lambda/ALB/listener/permission/listener rules, maybe I'm missing something, but I have to go to the AWS console to register the lambda on the target group. Our ECS services are registered via their `loadBalancer` property, nothing similar seems to exist for lambdas.

```
  // create our lambda function
  const lambda = new LambdaFunction(context.stack, `${context.cid.name}`, {
    functionName: `${context.cid.name}`,
    role: role.arn,
    imageUri: `${build.awsId}.${build.ecrRepo}/${props.containerImageTag}`,
    packageType: 'Image',
    timeout: 300,
    environment: [
      {
        variables: {
          ENV: 'blabla',
        },
      },
    ],
    vpcConfig: [
      {
        subnetIds: [privateSubnet_id_0, privateSubnet_id_1],
        securityGroupIds: [sgDefaultSecurityGroup.id],
      },
    ],
  });

  // create ALB permission
  new LambdaPermission(context.stack, `${context.cid.name}-alb-permission`, {
    action: 'lambda:InvokeFunction',
    principal: 'elasticloadbalancing.amazonaws.com',
    functionName: lambda.functionName,
  });

  const listener = remoteStateServices.get(`alb-listener-arn`);

  // Create target group
  const targetGroup = new LbTargetGroup(
    context.stack,
    `${context.cid.name}-long-route-tg`,
    {
      vpcId: vpcId,
      targetType: 'lambda',
      name: `${lambda.functionName}-tg`,
    },
  );

  // Create ALB rule
  new AlbListenerRule(context.stack, `${context.cid.name}-alb-rule`, {
    action: [{ type: 'forward', targetGroupArn: targetGroup.arn }],
    condition: [
      {
        pathPattern: [{ values: ['/lambda/*', '/lambda'] }],
      },
    ],
    listenerArn: listener,
    priority: 7,
  });
```

### References

Couldn't find docs/issues related to this, so here I am!

**Comment by jsteinich** [comment]
I think you want to be using a `LbTargetGroupAttachment`. Take a look [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb_target_group_attachment#usage-with-lambda) for some more information.

**Comment by PookMook** [comment]
That's a very good pointer, I don't know how I missed this one! 
Thank you very much!
