### ISSUE TITLE
Go: Referencing boolean attributes in boolean arguments does not work

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1363]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* 0.7

### Affected Resource(s)

any

### Debug Output

See https://github.com/ansgarm/test-cdktf-go-bool-refs

### Expected Behavior

Should synthesize to a valid reference (works in e.g. TypeScript)

### Actual Behavior

Fails with 
```
panic: unable to make an instance of unregistered interface interface {}
```
(full error in reproduction example)

### Steps to Reproduce
https://github.com/ansgarm/test-cdktf-go-bool-refs

### Important Factoids

* also fails in Java, works in TS, Python & C#

**Comment by jsteinich** [comment]
I think the work I've done in #1299 will fix this.
