### ISSUE TITLE
Trying to use DependsOn

### ISSUE THREAD

**Issue by dniasoff** [hashicorp/terraform-cdk#1367]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

version 0.7.0
.Net

### Output

│ Error: Invalid expression
│
│   on cdk.tf.json line 276, in resource.openstack_networking_router_route_v2.PublicRouterPrivateRoute_0.depends_on:
│  276:           "${openstack_networking_router_interface_v2.InternalNetworkInterface.id}"
│
│ A single static variable reference is required: only attribute access and indexing with constant keys. No calculations, function calls, template expressions, etc are allowed here.

### Steps to Reproduce

Create a NetworkingRouterInterfaceV2
Create a route that depends on the above interface

```csharp
NetworkingRouterInterfaceV2 publicNetworkRouterInternalNetworkInterface = new NetworkingRouterInterfaceV2(this, "InternalNetworkInterface", new NetworkingRouterInterfaceV2Config
{
    RouterId = publicNetworkRouter.Id,
    PortId = publicNetworkRouterInternalPort.Id

});

  
var route = new NetworkingRouterRouteV2(this, "PublicRouterPrivateRoute", new NetworkingRouterRouteV2Config
{
    RouterId = publicNetworkRouter.Id,
    DestinationCidr = r,
    NextHop = privateNetworkRange.FirstUsable.ToString()
    
});

route.DependsOn = new string[1]
{
    publicNetworkRouterInternalNetworkInterface.Id
};
```

- #0000

**Comment by jsteinich** [comment]
You have 2 options:

1. Pass the dependency in the `NetworkingRouterRouteV2Config` initializer along the lines of `DependsOn = new ITerraformDependable[] {publicNetworkRouterInternalNetworkInterface}`
2. Slightly modify what you have so far: `publicNetworkRouterInternalNetworkInterface.Id` -> `publicNetworkRouterInternalNetworkInterface.Fqn`

**Comment by dniasoff** [comment]
Thanks  for your response

I get the same error on both

[2021-11-30T20:30:40.958] [ERROR] default - ╷
│ Error: Error reading openstack_networking_router_route_v2 ID : invalid ID
format:
│
│   with openstack_networking_router_route_v2.PublicRouterPrivateRoute_0,
│   on cdk.tf.json line 334, in
resource.openstack_networking_router_route_v2.PublicRouterPrivateRoute_0:
│  334:       },
│

This is the resource I am depending on

 "InternalNetworkInterface": {
        "port_id": "${
openstack_networking_port_v2.PublicNetworkRouterInternalPort.id}",
        "router_id": "${
openstack_networking_router_v2.PublicNetworkRouter.id}",
        "//": {
          "metadata": {
            "path": "DevToolStackProd/InternalNetworkInterface",
            "uniqueId": "InternalNetworkInterface"
          }
        }
      },

and this is the depends on code
      "PublicRouterPrivateRoute_0": {
        "destination_cidr": "192.168.100.0/24",
        "next_hop": "192.168.104.1",
        "router_id": "${
openstack_networking_router_v2.PrivateNetworkRouter.id}",
        "depends_on": [

"openstack_networking_router_interface_v2.InternalNetworkInterface"
        ],
        "//": {
          "metadata": {
            "path": "DevToolStackProd/PublicRouterPrivateRoute_0",
            "uniqueId": "PublicRouterPrivateRoute_0"
          }
        }
      },

**Comment by dniasoff** [comment]
and this is the typescript code (moved from .net to typescript)
const publicNetworkRouterStaticRoutes: os.NetworkingRouterRouteV2[] = new
Array();
    {
        const privateNetworkRange = subnetToRange( CIDRBlock.fromString(
globalProps.openStackPrivateNetworkRange))
        let routeCounter = 0;
        for (let r of globalProps.openStackInternalRoutes) {
          const route = new os.NetworkingRouterRouteV2(this,
"PublicRouterPrivateRoute_" + routeCounter, {
             routerId: privateNetworkRouter.id,
             destinationCidr: r,
             nextHop: privateNetworkRange.first,
          })

          route.dependsOn = [
            publicNetworkRouterInternalNetworkInterface.fqn
          ]
          routeCounter++
        }
    }

**Comment by jsteinich** [comment]
Looks like the error you got changed to `Error: Error reading openstack_networking_router_route_v2 ID : invalid ID
format`. I'm not really familiar with the openstack provider, but it may be a configuration issue: https://github.com/terraform-provider-openstack/terraform-provider-openstack/blob/80b253a65d4c5bae2ba8b9c83cf783d504a375b0/openstack/networking_router_route_v2.go#L15

**Comment by DanielMSchmidt** [comment]
No answer for two months, closing for now 👍
