### ISSUE TITLE
Go: Referencing list attributes does not work

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1371]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* 0.7

### Affected Resource(s)

any

### Debug Output

https://github.com/ansgarm/test-cdktf-go-list-refs-k8s

### Expected Behavior

Should synthesize to a valid reference (works in e.g. TypeScript)

### Actual Behavior

Fails with 
```
panic: unable to make an instance of unregistered interface interface {}
```
(full error in reproduction example)

### Steps to Reproduce
https://github.com/ansgarm/test-cdktf-go-list-refs-k8s

**Comment by jsteinich** [comment]
```typescript
  // labels - computed: false, optional: true, required: false
  private _labels?: { [key: string]: string } | cdktf.IResolvable;
  public get labels() {
    // Getting the computed value is not yet implemented
    return this.interpolationForAttribute('labels') as any;
  }
```

**Comment by jsteinich** [comment]
See #25

**Comment by ansgarm** [comment]
Thanks for the context @jsteinich! I originally created this issue to link to from the [new edge provider tests](https://github.com/hashicorp/terraform-cdk/pull/1311).
