### ISSUE TITLE
CDKTF generates empty blocks for optional resource arguments, even when provider expects content

### ISSUE THREAD

**Issue by robin-norwood** [hashicorp/terraform-cdk#1382]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
$ cdktf --version
0.8.1
$ npm list @cdktf/provider-aws
cdktf-s3-bucket@1.0.0 /Users/rnorwood/code/cdktf-s3-bucket
└── @cdktf/provider-aws@3.0.0 
```

### Affected Resource(s)

`aws.s3.S3Bucket`, probably others.

### Debug Output

[GH repo w/code, steps, and error](https://github.com/robin-norwood/cdktf-s3-bucket)

(Probably should have been a gist :))

### Expected Behavior

CDKTF deploys an S3 bucket

### Actual Behavior

`Error: Insufficient default_retention blocks` and similar for other attributes.

### Steps to Reproduce

[Steps in READM.md](https://github.com/robin-norwood/cdktf-s3-bucket/blob/main/README.md)

### Important Factoids

N/A

### References

- #1329

**Comment by robin-norwood** [comment]
Also, I retested with CDKTF `0.8.0`, and it works fine:

**Comment by jsteinich** [comment]
Looks like providers generated with 0.8.0 aren't fully compatible with 0.8.1 library. We'll hopefully have an updated pre-built provider soon, but in the meantime you can either downgrade to 0.8.0 (as you've done) or build the provider yourself by adding to `cdktf.json` and running `cdktf get`.

**Comment by jsteinich** [comment]
@skorfmann https://github.com/hashicorp/cdktf-provider-aws/pull/475 seems to be failing to automerge.
