### ISSUE TITLE
Addition of multiple providers of the same type using addProvider

### ISSUE THREAD

**Issue by nandac** [hashicorp/terraform-cdk#1383]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be good to have the ability to add multiple providers of the same type with different aliases with addProvider. Escape hatches do not seem to work for me.

For example, if I have two AWS providers targeting two different AWS accounts I would like to send them both in when calling a Terraform module in CDK.

The code I would use in Terraform would be something like:

```
provider "aws" {
  alias  = <alias-1>
  profile = "<profile-1>"
  region  = "<aws-region>"
}

provider "aws" {
  alias   = "<alias-2>"
  profile = "<profile-2>"
  region  = "<aws-region>"
```

I would then send both of them in a providers block in a module call something like:

```
providers = {
  aws.<alias-1> = aws.<alias-1>
  aws.<alias-2> = aws.<alias-2>
}
```

Is the above possible or is this a new feature that has to be implemented?

Please forgive me if this is the wrong forum to ask this question but I did try StackOverflow and scoured the web to find an example to do the above but could not find any.

My StackOverflow post is [here](https://stackoverflow.com/questions/70209843/multiple-aws-providers-using-cdktf).

**Comment by DanielMSchmidt** [comment]
Hey there, I answered your StackOverflow post, TL;DR it's possible, https://github.com/hashicorp/terraform-cdk/blob/main/examples/typescript/aws-cloudfront-proxy/main.ts shows an example of it 👍

**Comment by nandac** [comment]
@DanielMSchmidt Thank you for your reply. However, I think the solution will not work for my case because I do not set a default provider.

All of my providers are aliased and I am able to get the following structure with my module call as shown below using an escape hatch:

```
"providers": {
  "aws": "aws.account-one",
  "aws.alternate": "aws.account-2"
}
```
Now when I run `cdktf get` I end up with the following error:
 ```
Error: No configuration for provider aws.alternate
│ 
│   on main.tf.json line 1, in module:
│    1: {"terraform":{},"module":{"REDACTED"}}}
│ 
│ Configuration required for
│ module.REDACTED.provider["registry.terraform.io/hashicorp/aws"].alternate.
│ Add a provider named aws.alternate to the providers map for
│ module.REDACTED
│ in the root module.
╵
Error: non-zero exit code 1
```

How do It keep the structure I want and get around this issue in cdktf get. I do define aws.alternate.

**Comment by jsteinich** [comment]
You should be able to create two aliased providers by simply providing aliases to both.

To pass to a module you can do roughly:
```ts
new MyModule(this, "module", {
  providers: [
    provider1,
    {provider: provider2, moduleAlias: "alternate"}
  ]
});
```

**Comment by nandac** [comment]
> You should be able to create two aliased providers by simply providing aliases to both.
> 
> To pass to a module you can do roughly:
> 
> ```ts
> new MyModule(this, "module", {
>   providers: [
>     provider1,
>     {provider: provider2, moduleAlias: "alternate"}
>   ]
> });
> ```

@jsteinich Thank you for your reply.

I am doing this in Python 3 and I have my module call something like this:
```
stack = MyStack(
            self,
            "my_stack",
            var1="xyz"
            var2="abc",
            var3="def",
        )

Are you saying that I could add a providers block to the above definition? 

Something like:

providers = [provider1 , provider2]

Is there an example or better still a Python example of this somewhere. I am still very new to CDKTF and need some hand-holding.

**Comment by jsteinich** [comment]
> ```
> Are you saying that I could add a providers block to the above definition? 
> 
> Something like:
> 
> providers = [provider1 , provider2]
> 
> Is there an example or better still a Python example of this somewhere. I am still very new to CDKTF and need some hand-holding.
> ```

Yep. The module alias requires a bit more. Take a look at https://github.com/hashicorp/terraform-cdk/issues/1199#issuecomment-952484783 for a quick example.

**Comment by nandac** [comment]
@jsteinich Thank you for pointing me to the other post.

I think my issue is with `cdktf.json` file which expects me to list the provider for `aws.alternate`.

I am using the pre-built provider for AWS and therefore do not list any providers in the `cdktf.json`. I only specify the modules that I am using which are privately hosted. Here is my cdktf.json:

```json
{
  "language": "python",
  "app": "python ./main.py",
  "output": "cdktf.out",
  "terraformModules": [
    "git::<git-repo>"
  ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  },
  "projectId": "REDACTED"
}
```

So I keep getting the error below when running `cdktf get`:There are some problems with the configuration, described below.
```
The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: No configuration for provider aws.alternate
│ 
│   on main.tf.json line 1, in module:
│    1: {"terraform":{},"module":{"<my_module>":{"source":"git::<git-repo>}}}
│ 
│ Configuration required for
│ module.<my_module>.provider["registry.terraform.io/hashicorp/aws"].alternate.
│ Add a provider named aws.alternate to the providers map for
│ module.<my_module>
│ in the root module.
╵
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/provider-generator/lib/util.js:82:31)
    at Object.onceWrapper (node:events:510:26)
    at ChildProcess.emit (node:events:390:28)
    at maybeClose (node:internal/child_process:1064:16)
    at Socket.<anonymous> (node:internal/child_process:450:11)
    at Socket.emit (node:events:390:28)
    at Pipe.<anonymous> (node:net:687:12) {
  stderr: '\x1B[31m\x1B[0mThere are some problems with the configuration, described below.\n' +
    '\n' +
    'The Terraform configuration must be valid before initialization so that\n' +
    'Terraform can determine which modules and providers need to be installed.\x1B[0m\x1B[0m\n' +
    '\x1B[31m\x1B[31m╷\x1B[0m\x1B[0m\n' +
    '\x1B[31m│\x1B[0m \x1B[0m\x1B[1m\x1B[31mError: \x1B[0m\x1B[0m\x1B[1mNo configuration for provider aws.alternate\x1B[0m\n' +
    '\x1B[31m│\x1B[0m \x1B[0m\n' +
    '\x1B[31m│\x1B[0m \x1B[0m\x1B[0m  on main.tf.json line 1, in module:\n' +
    '\x1B[31m│\x1B[0m \x1B[0m   1: {"terraform":{},"module":{"<my_module>":\x1B[4m{\x1B[0m"source":"git::<git-repo>"}}}\x1B[0m\n' +
    '\x1B[31m│\x1B[0m \x1B[0m\n' +
    '\x1B[31m│\x1B[0m \x1B[0mConfiguration required for\n' +
    '\x1B[31m│\x1B[0m \x1B[0mmodule.<my_module>.provider["registry.terraform.io/hashicorp/aws"].alternate.\n' +
    '\x1B[31m│\x1B[0m \x1B[0mAdd a provider named aws.alternate to the providers map for\n' +
    '\x1B[31m│\x1B[0m \x1B[0mmodule.<my_module>\n' +
    '\x1B[31m│\x1B[0m \x1B[0min the root module.\n' +
    '\x1B[31m╵\x1B[0m\x1B[0m\n' +
    '\x1B[0m\x1B[0m\n'
}
⠼ downloading and generating modules and providers...
non-zero exit code 1
```

So my question now is is it possible to use the pre-built AWS provider and get my configuration working with two AWS providers or must I download the AWS provider which takes a long time and make `aws` and `aws.alternate` reference it.

I am afraid I am still stuck.

**Comment by jsteinich** [comment]
@nandac I've created a separate issue since the behavior that you've encountered is a bug.
