### ISSUE TITLE
synth json with sorted keys

### ISSUE THREAD

**Issue by marengaz** [hashicorp/terraform-cdk#1384]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

we use the tf cdk to generate terraform modules. we commit these modules, as json, to git and use a git tag them for versioning. every commit looks like a large because the json keys are not ordered.

i propose we add a option to the App for sorted output of keys

### References

equivalent to python 

```python 
>>> json.dumps(dict(c=1,b=2,a=dict(c=1,b=2,a=3)), sort_keys=True)
>>> '{"a": {"a": 3, "b": 2, "c": 1}, "b": 2, "c": 1}'
```

**Comment by ansgarm** [comment]
I like the idea! Switching to something like [`json-stable-stringify`](https://www.npmjs.com/package/json-stable-stringify) could possibly solve this 👍
