### ISSUE TITLE
How to define Terraform modules using cdk

### ISSUE THREAD

**Issue by romainPrignon** [hashicorp/terraform-cdk#1385]
hi :)

I'm currently moving our hcl files into ts file using cdktf.
I struggle to find a way to convert hcl module into cdk. 

Given this module
```
module "buckets" {
  source = "./modules/buckets"
  bucket1 = "foo"
  bucket2 = "bar"
}
```

I can easily convert it using HclModule in cdktf
```
terraformModules: [
{
      "name": "buckets",
      "source": "./modules/buckets"
}
]
```
it generates something like this:
```ts
export class Buckets extends TerraformModule {...}
```
When I do a synth, I get the following cdk.tf.json
```
{
  "...",
  "module": {
    "buckets": {...}
  }
}
```

but, If I try to build a construct myself, Il only get ressources in my `cdk.tf.json`
Is there any documentation around building modules directly using cdktf ?

Thanks for your help :)

**Comment by ansgarm** [comment]
Hi @romainPrignon,

as far as I know there is no such documentation yet. However, a Terraform module mainly consists of `variables`, `outputs` and `resources / datasources` – so you could try to use the synthesized output of a CDK for Terraform stack as the code for a Terraform module. If you use local state, it should not contain state handling related code. However, it will contain provider configuration which you probably have to remove from the resulting `cdk.tf.json` via some custom shell script or similar.

I just saw that @marengaz mentioned in #1384 that they use the CDKTF to generate modules – maybe he could share how they are using the CDKTF to generate modules?

**Comment by romainPrignon** [comment]
oh sorry, my issue isn't clear enough.

I try to reconciliate my remote hcl state with the cdktf output.
cdktf seems to only generates ressources, not modules.
the only solution I see right know is to edit my remote state to match the cdktf output

**Comment by jsteinich** [comment]
It's definitely a bit outdated, but you could take a look at https://dev.to/skorfmann/a-terraform-cdk-construct-which-doubles-as-native-terraform-module-447k.

**Comment by romainPrignon** [comment]
Thanks @jsteinich ! That's what I'm looking for !
I'll try to iterate on that

**Comment by DanielMSchmidt** [comment]
Seems like an answer is found, closing this :)
