### ISSUE TITLE
tidy the azure-app-service example

### ISSUE THREAD

**Issue by rgl** [hashicorp/terraform-cdk#1386]
The code at https://github.com/hashicorp/terraform-cdk/blob/main/examples/typescript/azure-app-service/main.ts could be tidier.

If you agree, I can submit a PR with the following changes:

* Remove the use of `dependsOn` as all its not really needed.
* Replace `appsvc.addOverride("site_config", [` with `siteConfig`, e.g.:
```typescript
    const appsvc = new AppService(this, "docker-cdktf", {
      ...
      siteConfig: {
        linuxFxVersion: `DOCKER|${imagename}`,
        use32BitWorkerProcess: true, // NB MUST be true for Free/Shared App Service Plans.
      },
    });
```

What do you think?

**Comment by rgl** [comment]
Oh... even though I can use `siteConfig` it ends up not working with an odd error:

```
[ERROR] default - ╷
│ Error: creating App Service "rgl-cdktf-app-service-example" (Resource Group "rgl-cdktf-app-service-example"): web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>
│
│   with azurerm_app_service.appService,
│   on cdk.tf.json line 72, in resource.azurerm_app_service.appService:
│   72:       }
│
╵
```

Do you known what is going on?

**Comment by DanielMSchmidt** [comment]
Sounds good, looking forward to reviewing your PR 👍
