### ISSUE TITLE
Acm certificate validation not handled properly

### ISSUE THREAD

**Issue by Blakeinstein** [hashicorp/terraform-cdk#1393]
https://github.com/hashicorp/terraform-cdk/blob/158d8575f520f17a5adf76d46ad9840e5888cca8/examples/typescript/aws-cloudfront-proxy/main.ts#L84

I referenced the code above, and produce something like the following.

```ts
const certificateResource = new ACM.AcmCertificate(this, props.domainName + '_certificate', {
  domainName: props.domainName,
  validationMethod: 'DNS',
  tags: {
    environment: props.environment,
  },
  lifecycle: {
    createBeforeDestroy: true,
  },
});
certificate = certificateResource.arn;
const validationRecord = new Route53.Route53Record(this, props.domainName + '_certificate_record', {
  zoneId: hostedZone.zoneId,
  name: certificateResource.domainValidationOptions('0').resourceRecordName,
  type: certificateResource.domainValidationOptions('0').resourceRecordType,
  records: [
    certificateResource.domainValidationOptions('0').resourceRecordValue,
  ],
  ttl: 60,
});

certificateDependable = new ACM.AcmCertificateValidation(this, props.domainName + '_certificate_validation', {
  certificateArn: certificateResource.arn,
  validationRecordFqdns: [
    validationRecord.fqdn,
  ],
});
```

Raises the following error
```
 on cdk.tf.json line 65, in resource.aws_route53_record.typescript-aws_examplecom_certificate_record_67B1E051:
│   65:         "type": "${aws_acm_certificate.typescript-aws_examplecom_certificate_A8CEFE35.domain_validation_options.0.resource_record_type}",
Elements of a set are identified only by their value and don't have any
separate index or key to select with, so it's only possible to perform
operations across all elements of the set.
```

Futhermore I would like add a few alternative names as discussed [here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/version-3-upgrade#resource-aws_acm_certificate) and would like to know the syntax for the same.

**Comment by jsteinich** [comment]
I'm sure there's an example somewhere for this, but the closet I could find was https://github.com/hashicorp/terraform-cdk/issues/42#issuecomment-950333267

**Comment by Blakeinstein** [comment]
> I'm sure there's an example somewhere for this

I don't think that will work since as suggested by the comment, `domainValidationOptions` is now a function

**Comment by Blakeinstein** [comment]
A solution that could work is printing the appropriate hcl code via override.

I am unsure how you can refer to a resource's id at compile time however. since cdk generates tokens that a replaced later
