### ISSUE TITLE
Running the python aws-eks example fails

### ISSUE THREAD

**Issue by al1p-R** [hashicorp/terraform-cdk#1396]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.8.1
python: 3.9.7

### Affected Resource(s)

```
        my_eks= Eks(self, 'MyEks',
            cluster_name='my-eks',
            subnets=Token().as_list(my_vpc.private_subnets_output),
            vpc_id=Token().as_string(my_vpc.vpc_id_output),
            manage_aws_auth=False,
            cluster_version='1.17'
        )
```
### Debug Output
```
cdktf deploy 
...
│ Error: Error in function call
│ 
│   on .terraform/modules/MyEks/outputs.tf line 3, in output "cluster_id":
│    3:   value       = element(concat(aws_eks_cluster.this.*.id, list("")), 0)
│ 
│ Call to function "list" failed: the "list" function was deprecated in
│ Terraform v0.12 and is no longer available; use tolist([ ... ]) syntax to
│ write a literal list.
```

[Full  output gist](https://gist.github.com/al1p-R/c64cd4ff4fbf2b64e6b18aaae7acfd85)

### Steps to Reproduce

Running the example in https://github.com/hashicorp/terraform-cdk/blob/main/examples/python/aws-eks/main.py

### Note
Only difference from original install steps is that I am running with poetry rather than pipenv...
```
{
  "language": "python",
  "app": "poetry run python main.py",
  "projectId": "b45de818-5fa7-410c-9d08-baac7b981a21",
  "terraformProviders": ["hashicorp/aws@~> 3.42"],
  "terraformModules": [
    {
      "name": "vpc",
      "source": "terraform-aws-modules/vpc/aws",
      "version": "2.77.0"
    },
    {
      "name": "eks",
      "source": "terraform-aws-modules/eks/aws",
      "version": "~> 14.0"
    }
  ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

**Comment by ansgarm** [comment]
Thank you for reporting @al1p-R!

It seems that the `terraform-aws-modules/eks/aws` module version 14 [contains that `list()` call](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/v14.0.0/outputs.tf#L3).

Upgrading that one to v15 (or newer) might already be enough (v15 did not contain the `list()` call in the outputs anymore).

Could you try changing the version in the `cdktf.json` config file?

**Comment by al1p-R** [comment]
Thanks ! it worked fine. I just had to bump the cluster_version to 1.21 
If you want, https://github.com/hashicorp/terraform-cdk/pull/1400  has the 2 version bumps.

**Comment by ansgarm** [comment]
Nice, thank you @al1p-R!
