### ISSUE TITLE
Edge provider test constructs version mismatch

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#1410]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Any version with c#

### Affected Resource(s)

c# edge provider test

### Debug Output

Version conflict detected for Constructs. Install/reference Constructs 10.0.12 directly to project MyTerraformStack to resolve this issue. 

### Expected Behavior

Test passes

### Actual Behavior

Test fails because the null and edge providers have different construct versions

### Steps to Reproduce

Build edge provider with one constructs version and null provider with a different one

### References

https://github.com/cdklabs/jsii-srcmak/issues/271

Ideally https://github.com/cdklabs/jsii-srcmak/issues/271 would be fixed since then the version would need to match exactly.
We could probably directly reference a version of constructs either in the test or always in the c# template. This will still generate warnings, but shouldn't be an error.

**Comment by DanielMSchmidt** [comment]
This should be slved by https://github.com/hashicorp/terraform-cdk/pull/1414

**Comment by jsteinich** [comment]
> This should be slved by #1414

That fixes this for now, but it will break again the next time a new constructs version is released.

**Comment by DanielMSchmidt** [comment]
#1444 is fixing this again 🙈
