### ISSUE TITLE
Support `"all"` for ignoreChanges in lifecycle

### ISSUE THREAD

**Issue by aaronfeng** [hashicorp/terraform-cdk#1425]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to ignore all attributes on a resource using cdktf?  I tried to pass in `["all"]` and it doesn't work.
Is there a workaround without defining every attribute in the list?

### References

https://www.terraform.io/docs/language/meta-arguments/lifecycle.html

**Comment by ansgarm** [comment]
Hi @aaronfeng

Currently the type only allows specifying an array. But you can use [an override](https://www.terraform.io/cdktf/concepts/providers-and-resources#escape-hatch) to set `"all"`:
```ts
yourResource.addOverride("lifecycle.ignore_changes", "all");
```

We should support `all` however, so let's keep this issue open to track this improvement 👍

**Comment by ansgarm** [comment]
> Is `all` a keyword which works in other contexts as well?

None that I know of – I've also checked the other properties of `lifecycle` and none share that `all`.

**Comment by sebbel** [comment]
Is the scope of this ticket simply adjusting the TerraformResourceLifecycle Type to include a string of `all` ?
I quickly grepped for lifecycle and I wonder if I am missing a cdktf2hcl logic.

**Comment by jsteinich** [comment]
> Is the scope of this ticket simply adjusting the TerraformResourceLifecycle Type to include a string of `all` ? I quickly grepped for lifecycle and I wonder if I am missing a cdktf2hcl logic.

That won't quite work since it won't translate to other supported languages.
One is idea is to add another property (say `ignoreAllChanges?: boolean`) to `TerraformResourceLifecycle`.
Could also have altered synth logic if `ignoreChanges` is a single element list of value "all".
Or other possible ways to implement.

**Comment by ryuheechul** [comment]
I accidentally discovered a workaround for this.

```typescript
// by using the wrapper function like this
function createVariable(scope: Construct, workspaceId: string, key: string, value: string, sensitive = false, lifecycle = {}) {
  new Variable(scope, key, {
    category: 'terraform',
    sensitive,
    value,
    key,
    workspaceId,
    lifecycle
  })
}

// and calling this
createVariable(this, workspace.id, 'key', 'value', true, {
  ignoreChanges: 'all',
})
```

Somehow Typescript doesn't complain and `cdktf synth` worked as well.
It might be a temporary bug from Typescript side though.
