### ISSUE TITLE
Error: Saved plan does not match the given state

### ISSUE THREAD

**Issue by jwhy89** [hashicorp/terraform-cdk#1428]
### cdktf & Language Versions

Terraform v1.1.0 on darwin_amd64
"@cdktf/provider-docker": "^0.5.12",
"cdktf": "^0.8.3",

### Expected Behavior

```sh
cdktf destroy typescript-docker
Destroying Stack: typescript-docker
Resources
 ✔ DOCKER_CONTAINER     nginxContainer      docker_container.nginxContainer
 ✔ DOCKER_IMAGE         nginxImage          docker_image.nginxImage

Summary: 2 destroyed.
```

### Actual Behavior

```sh
cdktf destroy typescript-docker
⠦ planning typescript-docker...
[2021-12-16T00:55:05.684] [ERROR] default - ╷
│ Error: Saved plan does not match the given state
│ 
│ The given plan file can not be applied because it was created from a
│ different state lineage.
```

### Steps to Reproduce

Follow the steps from https://learn.hashicorp.com/tutorials/terraform/cdktf-install?in=terraform/cdktf

Once you get to the https://learn.hashicorp.com/tutorials/terraform/cdktf-install?in=terraform/cdktf#destroy-the-container step,
you'll get the Actual Behavior above.

### Important Factoids

Ended up just using tfswitch to go back to v1.0.11. This worked fine.

### References

https://www.terraform.io/enterprise/release/v202111-1

- #0000

**Comment by ansgarm** [comment]
Hi @jwhy89 👋
I transferred this issue to the CDK for Terraform repo. I could reproduce it locally and got the same error. I tried using `terraform plan / apply` in the output directory which worked. So it probably has something to do with how we invoke Terraform and/or pass the state file and/or the plan file. I will debug further and will report back 🔎🐛

**Comment by ansgarm** [comment]
I built a [reproduction case](https://github.com/ansgarm/reproduction-cdktf-tf-1.1-issue) using Terraform which works with `1.0.7` but fails with `1.1.1`. I will create an issue over at the Terraform repo for that bug and keep this one here as it is still unclear whether the Terraform commands from the reproduction case are wrong or whether there was a regression in Terraform `1.1.1`.

**Comment by iainlbc** [comment]
I just ran into this as well, my first day exploring cdktf using go

Terraform v1.1.2, darwin_amd64, cdktf 0.8.3

**Comment by iainlbc** [comment]
@ansgarm Does [terraform/#30195](https://github.com/hashicorp/terraform/issues/30195) fix the `destroy` use case or only `show`? Thank you

**Comment by jdigory** [comment]
Seems that #30205 only fixed this for `show`, but there's still a problem with `plan` & `apply` -- trying to upgrade Terraform from 1.0.11 to 1.2.2:
```
$ terraform -chdir=development init -upgrade

$ terraform -chdir=development plan -state=development.tfstate -out=development.plan

$ terraform -chdir=development apply -state-out=development.tfstate development.plan

│ Error: Saved plan does not match the given state
│
│ The given plan file can not be applied because it was created from a different state lineage.

```

**Comment by IamRFC1918** [comment]
Hi @jdigory,

do you find a solution for that? I'm running in the same error, using Gitlab as http Backend and apply a plan if a state from a previous run exists.

**Comment by jdigory** [comment]
> Hi @jdigory,
> 
> do you find a solution for that? I'm running in the same error, using Gitlab as http Backend and apply a plan if a state from a previous run exists.
> 
> I tested Version 1.0.11: Its working.. It seams like a bug in newer Versions

Yes, I had to stop using the `-state` parameters everywhere...
