### ISSUE TITLE
Add pre-built provider for ACME

### ISSUE THREAD

**Issue by sorenhansendk** [hashicorp/terraform-cdk#1429]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be very handy to have the ACME provider created as an pre-built TFCDK provider.

You can find the source for the module here: https://github.com/vancluever/terraform-provider-acme

**Comment by sorenhansendk** [comment]
@vancluever: Can you please help here? That would be so nice, if we get the provider as an TFCDK provider.

**Comment by ansgarm** [comment]
Hi @sorenhansendk!
The pre-built providers are configured [here](https://github.com/hashicorp/cdktf-repository-manager/blob/main/provider.json). I will add `acme` to that list 👍

**Comment by ansgarm** [comment]
Done ✅ First release is available here: https://github.com/hashicorp/cdktf-provider-acme/releases

**Comment by vancluever** [comment]
Hey yall, looks like this got merged but happy to help if need be still! Feel free to reach out if further help is needed 🙂 

Cheers!
