### ISSUE TITLE
Release Workflow

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#143]
Current workflow:

- `@pre` is released from master with whatever version is defined in `package.json` 
- With each push on master, GH actions will try to publish. It'll error out when version exists 

This sort of works at the moment, but it would be nice to have a more explicit workflow for this. Ideas?

**Comment by anubhavmishra** [comment]
I think we ignore the errors right?

**Comment by skorfmann** [comment]
> I think we ignore the errors right?

Yes, we do. 

There's a related issue around Python. There's no pre-release version published at the moment.

**Comment by skorfmann** [comment]
Hasn't been an issue so far, closing it
