### ISSUE TITLE
Unrecognized key: `nullable` in variable

### ISSUE THREAD

**Issue by Xavientois** [hashicorp/terraform-cdk#1432]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF Version: 0.8.3
Node.js Version: v17.3.0
Terraform Version: 1.1.2

### Affected Resource(s)

Variables

### Debug Output

https://gist.github.com/Xavientois/0153c97ea55ac1087013e1fb2a54cf91

### Expected Behavior
It should expect the optional `nullable` field in terraform variables ([source](https://www.terraform.io/language/values/variables#disallowing-null-input-values))

### Actual Behavior

It gets an `Internal Error`

### Steps to Reproduce

- Include the following in your source .tf file:
```tf
variable "gcp_project" {
  type  = string
  description = "Project id for GCP project to which the dployment will be made"
  nullable = false
}
```
- Run `cdktf convert`

**Comment by jsteinich** [comment]
Looks like that was just added in Terraform 1.1, so support will need to be added.

Tangentially, looks like [validation rules](https://www.terraform.io/language/values/variables#custom-validation-rules) are also unsupported.

**Comment by Xavientois** [comment]
I might take a crack at fixing this then!
