### ISSUE TITLE
AWS examples in docs/readme are wrong/dont work

### ISSUE THREAD

**Issue by richstokes** [hashicorp/terraform-cdk#1464]
If you use [this guide](https://learn.hashicorp.com/tutorials/terraform/cdktf-build?in=terraform/cdktf), you get:
```
 ⨯ Unable to compile TypeScript:
    main.ts(3,23): error TS2305: Module '"./.gen/providers/aws"' has no exported member 'Instance'.
```

And if you use the example in the [typescript readme](https://github.com/hashicorp/terraform-cdk/blob/main/docs/getting-started/typescript.md) of this repo, you get the same but with 
```
'"./.gen/providers/aws"' has no exported member named 'EC2'. Did you mean 'ec2'
```

Thats after adding the AWS `terraformProviders` and running `cdktf get`, and then `cdktf deploy`.

**Comment by richstokes** [comment]
If you change the code in the typescript example to this, it works:

```
import { Construct } from "constructs";
import { App, TerraformStack } from "cdktf";
import { AwsProvider, ec2 } from "./.gen/providers/aws";

class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new AwsProvider(this, "aws", {
      region: "us-east-1",
    });

    new ec2.Instance(this, "Hello", {
      ami: "ami-2757f631",
      instanceType: "t2.micro",
    });
  }
}

const app = new App();
new MyStack(app, "hello-terraform");
app.synth();

```

**Comment by ansgarm** [comment]
Hi @richstokes 👋
Thank you for reporting this! I just created an internal PR to get this fixed in the tutorial.
Regarding the TypeScript Readme you found: Those docs are outdated and will be removed in the midterm.

**Comment by jritsema** [comment]
> If you change the code in the typescript example to this (e.g. use a lowercase `ec2`), it works:

Thanks, this worked for me!

**Comment by robin-norwood** [comment]
We've updated the [Learn tutorial](https://learn.hashicorp.com/tutorials/terraform/cdktf-build?in=terraform/cdktf), thanks for reporting this, @richstokes !

**Comment by richstokes** [comment]
Thanks for taking care of it! 🙇🏼

**Comment by DanielMSchmidt** [comment]
Looks like we can close this 👍
