### ISSUE TITLE
Make cdktf.log output file configurable via env or CLI flag

### ISSUE THREAD

**Issue by fmmoret** [hashicorp/terraform-cdk#1465]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When env CDKTF_DISABLE_LOGGING is disabled, the logs get appending to a file at `cdktf.log`; defined in here: https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf-cli/lib/logging.ts

I'd like to be able to write the logs to different files/paths.

**Comment by ansgarm** [comment]
Hi @fmmoret!

That's a great idea. We'd be open to a PR which adds support for an optional environment variable to set the file name / path!
