### ISSUE TITLE
Problem running cdktf-cli

### ISSUE THREAD

**Issue by successx** [hashicorp/terraform-cdk#1472]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

Happy new year everyone. I've just needed to update some aws resources in new year and got this problem running cdktf-cli. Looks like there is problem with jsii that has dependency on latest version of colors (1.4.2) that cause the issue. **Please be careful with this!**

### cdktf & Language Versions

cdktf: 0.6.4 & 0.8.6
terraform: v1.0.7, v1.1.3
node: v14 & v16
platform: linux, macos

### Affected Resource(s)

cdktf-cli

### Expected Behavior

Command line should work normally when fresh install node_modules.

### Actual Behavior

When fresh install node_modules, cdktf-cli stop working and throw dangerous logs:
`* * * * |---------------------|             H|§|§|§|H           H|* * * * * *|---------------------|             H|H|H|H|H           H| * * * * * |---------------------|             H|H|H|H|H           H|---------------------------------|          ===============        H|---------------------------------|            /| _   _ |          H|---------------------------------|            (| O   O |)          H|---------------------------------|            /|   U   |          H-----------------------------------             |  =/  |           H              _..._/            H              _|I/|_            H      _______/| H |/_______    H     /           / /          H    |          | | /         |  H    |          ||o||          |  H    |    |     ||o||     |    |  H    |    |     ||o||     |    |  H   Carl Pilcher  
t͌͂͒eͪ͆ͦ̄šͬt̐̓i̾͆n͐̋g̿̎ ҉̠̰͎ ̓ͪtͤ̊eͭ̓̍s͐̈̅t̑͐i͌̎n̈͌̎g̀ͫ ͊t̿͋eͧ̋ṡͪ ҉ ҉̥̤t̓̐ ҉͉̭͠i͊̂nͤ̔g̉̒ ͯ̂͛t̏͛e̎̚s͒̔t̍͒ ҉̳̟̦͉i͑̔n̑ͧg͛ͬ ͮ̀ṫ̎eͫ͆͐ ҉ ҉̸̢ ҉̰͎̞ŝ̍ͬ̓tͮ̑iͪ̋n͋͌gͧ̚ ̏͆̚t̂̏e̿͂s̏ͧ̀t̓ͥͧȉ̀n͒̃̓̀g̓̓ ̽̔ ҉͝ ҉̦̖tͧ̂ëͨs̆̉t̾̔i͌ͥn̎̎ ҉̨̀g̈̂`

### Steps to Reproduce

1. Fresh install node_modules inside repository. Run `cdktf help` throws above logs. (any other cli commands have the same problem)
2. Install cdktf global, same problem
3. Upgrade node, same problem
4. Try on different machine (kbuntu 20.04, macos), same problem

### Linked issues
https://github.com/Marak/colors.js/issues/285

**Comment by ansgarm** [comment]
Hi @successx 👋
Thank you for bringing this to our attention. It seems that this has been [fixed in JSII](https://github.com/aws/jsii/pull/3328).
I couldn't reproduce it anymore. Can you confirm that it was fixed?

**Comment by ansgarm** [comment]
Sidenote: JSII is one of the dependencies that we don't bundle (else the [bundling](https://github.com/hashicorp/terraform-cdk/issues/881) would have prevented this issue).

**Comment by successx** [comment]
Thanks. Confirmed the issue is resolved with latest jsii version.
