### ISSUE TITLE
azurerm.ApplicationGatewayTrustedRootCertificate is not up to date

### ISSUE THREAD

**Issue by Lars-Nielsen-Forter** [hashicorp/terraform-cdk#1483]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

version: 0.8.6

### Affected Resource(s)

azurerm.ApplicationGatewayTrustedRootCertificate

### Expected Behavior

As shown here: https://github.com/hashicorp/terraform-provider-azurerm/blob/4d43e01fac3d94a88d27e91ddd6fae5d100a6409/internal/services/network/application_gateway_resource.go#L879 the resource should have attributes: `name`, `data`, `key_vault_secret_id`.

### Actual Behavior

It has data and name. Missing `key_vault_secret_id`

```
@jsii.data_type(
    jsii_type="azurerm.ApplicationGatewayTrustedRootCertificate",
    jsii_struct_bases=[],
    name_mapping={"data": "data", "name": "name"},
)
class ApplicationGatewayTrustedRootCertificate:
    def __init__(self, *, data: builtins.str, name: builtins.str) -> None:
        '''
        :param data: Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#data ApplicationGateway#data}.
        :param name: Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#name ApplicationGateway#name}.
        '''
        self._values: typing.Dict[str, typing.Any] = {
            "data": data,
            "name": name,
        }
```

### Steps to Reproduce

See link and the `azurerm/__init__.py` file

**Comment by DanielMSchmidt** [comment]
Well, we have a new azurerm release now 🎉 https://github.com/hashicorp/cdktf-provider-azurerm/releases/tag/v0.4.128

But unfortunately it exceeds 10 GB in size, created https://github.com/hashicorp/terraform-cdk/issues/1486 to track this

**Comment by DanielMSchmidt** [comment]
In the mean time you can build the provider on your own: https://www.terraform.io/cdktf/concepts/providers-and-resources#add-provider-to-cdktf-json A bit inconvenient, but should unblock you for now.

**Comment by DanielMSchmidt** [comment]
The azure provider should be able to release, closing this since #1486  tracks the outstanding cleanup work
