### ISSUE TITLE
Improve cdktf diff output for changes

### ISSUE THREAD

**Issue by anubhavmishra** [hashicorp/terraform-cdk#152]
We want to parse the `terraform plan` output for changes and attributes that are forcing the change and display them when running `cdktf diff`.

Related https://github.com/hashicorp/terraform-cdk/issues/114.

**Comment by njsnx** [comment]
any updates on this - came across this today when showing "cdktf diff vs terraform plan" - it would be nice to see a similar view to vanilla cdk

**Comment by skorfmann** [comment]
There's no immediate update on this. However, as part of the ongoing multiple stacks initiative we'll have to address various UI / UX aspects and rethink the way we present the data. I expect that this will be changed along the way as well.

**Comment by awworrell** [comment]
Are there any updates on this?

**Comment by ansgarm** [comment]
Hi @awworrell!

Yes indeed – we are planning to pipe a slightly altered version of the Terraform plan output as a first increment and in a later version offer a more rich (and interactive) interface. I'm going to put these ideas into writing this week and will then backlink them here.
The initial simple version is planned to ship with the next release (`0.7`).

**Comment by DanielMSchmidt** [comment]
Closing this in favour of #1097 that now tracks the issue 👍
