### ISSUE TITLE
Documentation: Cross Stack References in Go

### ISSUE THREAD

**Issue by eahrend** [hashicorp/terraform-cdk#1526]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the release of 0.9.0 it looks like cross stack referencing is now a thing, however there doesn't seem to be much documentation for how to do it in golang, and the godocs on the CDKTF aren't very helpful.

For example, I have a setup where I'm trying to create a shared vpc in GCP, and I want the host project and each service project to be their own stack.

The host project and related infrastructure is created in this function and the stack is returned.
```GO
func CreateHostProject(scope constructs.Construct, hostProjectConfig models.HostProjectConfig) cdktf.TerraformStack {
	stack := cdktf.NewTerraformStack(scope, &hostProjectConfig.ProjectID)
	project := projectFactory.NewProjectFactory(stack, &hostProjectConfig.ProjectID, &projectFactory.ProjectFactoryOptions{
		BillingAccount:  &hostProjectConfig.BillingAccountID,
		Name:            &hostProjectConfig.ProjectName,
		ActivateApis:    jsii.Strings(hostProjectConfig.EnabledServices...),
		OrgId:           &hostProjectConfig.OrgID,
		FolderId:        &hostProjectConfig.ParentFolder,
		RandomProjectId: jsii.Bool(true),
	})
	return stack
}
```

Ideally, the service Project creation function should look like:

```GO
func CreateServiceProject(scope constructs.Construct, serviceProjectConfig models.ServiceProjectConfig, hostProjectStack cdktf.TerraformStack) error {
	stack := cdktf.NewTerraformStack(scope, &serviceProjectConfig.ProjectID)
	project := projectFactory.NewProjectFactory(stack, &hostProjectConfig.ProjectID, &projectFactory.ProjectFactoryOptions{
		BillingAccount:  hostProjectStack.Project.BillingAccountID,
		Name:            &serviceProjectConfig.ProjectName,
		ActivateApis:    jsii.Strings(serviceProjectConfig.EnabledServices...),
		OrgId:           hostProjectStack.Project.OrgID,
		FolderId:        &serviceProjectConfig.ParentFolder,
		RandomProjectId: jsii.Bool(true),
	})
	return nil
}

```

The cdktf.json file:
```JSON
{
    "language": "go",
    "app": "go run .",
    "codeMakerOutput": "generated",
    "projectId": "#####",
    "terraformProviders": [
        "hashicorp/google@>= 4.8.0"
    ],
    "terraformModules": [
        {
            "name": "projectFactory",
            "source": "terraform-google-modules/project-factory/google",
            "version": "~> 11.3.0"
        },
        {
            "name":"cloudRouter",
            "source": "terraform-google-modules/cloud-router/google",
            "version": "~> 0.4"
        }
    ],
    "context": {
        "excludeStackIdFromLogicalIds": "true",
        "allowSepCharsInLogicalIds": "true"
    }
}
```

### References

Current documentation I was able to find about cross stack referencing in golang:
https://github.com/hashicorp/terraform-cdk-go/blob/main/cdktf/cdktf.go#L17331-L17356

Cross stack referencing in typescript:
https://www.terraform.io/cdktf/concepts/stacks#cross-stack-references

**Comment by DanielMSchmidt** [comment]
Hey there, yeah the documentation on the topic is a bit sparse. I am not too familiar with our go implementation, but from a cross stack reference perspective I think you'd want to put the project you created into the function that creates the service and access the property there. Both will have their own stacks therefore a cross stack reference should be created.

**Comment by eahrend** [comment]
@DanielMSchmidt that's what I'm doing currently as a workaround, however it's a bit ugly and doesn't seem to be the paradigm set by the typescript example, where resources created in a stack are accessible by that stack itself. The terraformstack interface does have some functions that are named `RegisterIncomingCrossStackReference` and `RegisterOutgoingCrossStackReference` but there isn't any documentation on what they do or how they can be implemented.

**Comment by DanielMSchmidt** [comment]
They are implicitly used when a cross stack reference is detected, they are not meant to be used by hand. 

The typescript example is different since the patterns are different, afaik you can't really extend classes in Go so that's why you have to pass the stack down instead of using this like in the other languages. To keep it together you could create a struct that holds both the stack and your  outputs.

**Comment by eahrend** [comment]
@DanielMSchmidt gotcha, tested it out and it works.
