### ISSUE TITLE
"terraform show" errors out when stale plan is present in same directory

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#153]
Given the following scenario:

```bash
drwxr-xr-x   4 sebastian  staff    128 Jun 11 11:49 .terraform
-rw-r--r--   1 sebastian  staff  85923 Jul 10 21:08 helloterra.tf.json
-rw-r--r--   1 sebastian  staff   6500 Jul 10 21:08 plan
-rw-r--r--   1 sebastian  staff   3868 Jun 26 19:07 terraform.tfstate
```
Assuming the `plan` was just written, and `terraform.tfstate` is stale for some reason. When running `terraform show -json plan` it errors out with `Error: Saved plan is stale`. 

My expectation would be: Since an explicit path to the plan file is specified, the stale state should be ignored (not even be parsed). 

It's probably rather an edge case, since users would have to perform a manual `apply` in `cdktf.out`. However, if this occurs it's quite annoying. 

Possible solutions:

- Look for state files in the `cdktf.out` directory and print a warning / clean up
- File a bug in the Terraform CLI 
- ?

**Comment by anubhavmishra** [comment]
Isn't this fixed as we moved the state file to the root directory of the project?

**Comment by skorfmann** [comment]
Yes, let's close it.
