### ISSUE TITLE
AttributeError: module 'cdktf' has no attribute 'IInterpolatingParent'

### ISSUE THREAD

**Issue by asokolsky4clari** [hashicorp/terraform-cdk#1532]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
> cdktf --version                                 
0.9.0
> cat ./cdktf.json 
{
  "language": "python",
  "app": "env arquiteto cdksynth",
  "projectId": "1234567890",
  "output": "cdkoutput",
  "terraformProviders": [
    "aws@~> 3.74.0"
  ],
  "terraformModules": [
    {
      "name": "vpc",
      "source": "terraform-aws-modules/vpc/aws",
      "version": "~> 3.11.5"
    },
    {
      "name": "eks",
      "source": "terraform-aws-modules/eks/aws",
      "version": "~> 18.2.6"
    }
  ],
  "codeMakerOutput": "arquiteto/stacks/imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
> tfenv list    
* 1.1.3 (set by ~/Projects/arquiteto/.terraform-version)
> pyenv versions
  system
  3.10.1
  3.10.1/envs/arquiteto
* arquiteto (set by PYENV_VERSION environment variable)
```

### Debug Output

An attempt to import aws in python file `from arquiteto.stacks.imports import aws`
results in exception:

```
   from arquiteto.stacks.imports import aws
  File "~/arquiteto/arquiteto/stacks/imports/aws/__init__.py", line 6098, in <module>
    class CloudcontrolapiResourceTimeoutsOutputReference(
  File "~/arquiteto/arquiteto/stacks/imports/aws/__init__.py", line 6105, in CloudcontrolapiResourceTimeoutsOutputReference
    terraform_resource: cdktf.IInterpolatingParent,
AttributeError: module 'cdktf' has no attribute 'IInterpolatingParent'
```

### Expected Behavior

import should succeed as it was in cdktf 0.8.6

### Actual Behavior

The above exception is raised.

### Steps to Reproduce

```
cdktf get
```

Then import created aws module in python.

- #0000

**Comment by asokolsky4clari** [comment]
Root cause:
```
> pip list |grep cdktf                                                                              
cdktf             0.8.6
```

Resolution:
```
> pip install cdktf --upgrade                                                                       
Requirement already satisfied: cdktf in ~/.pyenv/versions/3.10.1/envs/arquiteto/lib/python3.10/site-packages (0.8.6)
Collecting cdktf
  Downloading cdktf-0.9.0-py3-none-any.whl (803 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 803.6/803.6 KB 10.4 MB/s eta 0:00:00
```

Things work after that.

**Comment by DanielMSchmidt** [comment]
Yeah, we introduced this in 0.9 and your CLI was already updated to 0.9, as a result get produced 0.9 bindings but you had cdktf in 0.8. Glad you could figure it out 👍

**Comment by ansgarm** [comment]
#298 probably would've helped here
