### ISSUE TITLE
Submodules are not generated

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1536]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

all languages, tested in cdktf 0.9

### Expected Behavior

When a terraform module has submodules I expect them to be generated when I put the module in the cdktf.json and run `cdktf get`

### Actual Behavior

Only the main module is generated

### Steps to Reproduce

- Example: https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest/submodules/eks-managed-node-group

### References

- This method only supports one module / class per module source, but it needs to create more than one module in cases of submodules

**Comment by jsteinich** [comment]
I believe this was actually intentional since:

1. The code generation is slow
2. Users likely wouldn't be using more than 1-2 submodules from a given module

Could certainly revisit the topic.

**Comment by DanielMSchmidt** [comment]
Can one specify a submodule by hand? Is there a way for me to specify this submodule somehow?

**Comment by jsteinich** [comment]
> Can one specify a submodule by hand? Is there a way for me to specify this submodule somehow?

Yep. You can specify it the same way as you would in Terraform. Take a look at https://github.com/hashicorp/terraform-cdk/blob/b4bab56f671c395ea932bcb8222a485229444521/packages/%40cdktf/provider-generator/lib/config.test.ts#L141

**Comment by DanielMSchmidt** [comment]
Created a PR to improve the docs here: https://github.com/hashicorp/terraform-cdk/pull/1537
