### ISSUE TITLE
SyntaxError Unexpected Token ? following install

### ISSUE THREAD

**Issue by blade2005** [hashicorp/terraform-cdk#1538]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
I installed cdktf-cli using `sudo npm install --global cdktf-cli@next`. I ran help as part of the tutorial https://learn.hashicorp.com/tutorials/terraform/cdktf-install
It errored out.

### Debug Output
https://gist.github.com/blade2005/c6569e956880cdf5f62c165345557b42

### Expected Behavior
Help to be shown.

### Actual Behavior
SyntaxError

### Steps to Reproduce
1. WSL2 Debian
2. install npm from apt
3. install using `sudo npm install --global cdktf-cli@next`
4. `cdktf --help`

### References

- #0000

**Comment by jsteinich** [comment]
What version of node do you have installed?
I got this error when using 12.x, but it went away after installing 16.x.

**Comment by blade2005** [comment]
Will check monday. It's almost certainly 12.x as it's ubuntu and it looks like even in latest release it's still 12.x https://packages.ubuntu.com/impish/nodejs

**Comment by jsteinich** [comment]
Looks like node 14.x is the minimum supported. I believe this happened as a result of https://github.com/hashicorp/terraform-cdk/commit/c0f9a834602e39748d724646bfbc1cbba0f932cb. There's a check in code for at least 10.12, but that doesn't seem to even hit anymore. Perhaps the same change broke that or maybe the cli bundling.
