### ISSUE TITLE
cdktf get failing when using asdf version manager

### ISSUE THREAD

**Issue by damianoneill** [hashicorp/terraform-cdk#1559]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf --version 
0.9.0

golang 1.16
terraform 1.1.5
nodejs 14.18.3

### Affected Resource(s)

N/A

### Debug Output

```sh
cdktf get
⠧ downloading and generating modules and providers...
No version is set for command terraform
Consider adding one of the following versions in your config file at
Error: non-zero exit code 126
    at ChildProcess.<anonymous> (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:43:1685)
    at Object.onceWrapper (events.js:520:26)
    at ChildProcess.emit (events.js:400:28)
    at maybeClose (internal/child_process.js:1058:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:400:28)
    at Pipe.<anonymous> (net.js:686:12) {
  stderr: 'No version is set for command terraform\n' +
    'Consider adding one of the following versions in your config file at \n' +
    'terraform 1.1.5\n'
}
```

### Expected Behavior

cdktf get should succeed

### Actual Behavior

cdktf get fails

### Steps to Reproduce

See above

### Important Factoids

Using asdf for managing go, terraform and node.

### References

Following this example - https://github.com/hashicorp/terraform-cdk/blob/main/docs/getting-started/go.md

**Comment by ansgarm** [comment]
Hi @damianoneill 👋
Thank you for reporting this issue.

It seems that the error message "No version is set for command terraform[…]" comes from `asdf`.
Does running e.g. `terraform --version` work or does this produce the same error?

**Comment by damianoneill** [comment]
@ansgarm thanks for the quick response.  Running the version command in the repo directory results in no issues. 

```sh
terraform --version
Terraform v1.1.5
on darwin_amd64
```

**Comment by ansgarm** [comment]
@damianoneill
Is there a way to tell `asdf` which version to use via an environment variable?
For `cdktf get` we run the `terraform` command in a temporary directory which might not have the required config file located inside it (hence it might be complaining that it has no config).

**Comment by damianoneill** [comment]
Hi @ansgarm, I'm not sure what you mean by the first statement.  Do you mean a specific version of terraform (1.1.3, 1.1.4, 1.1.5, etc.) or do you mean a specific binary (location)/non-asdf version of terraform?

On the second statement in the /tmp directory. 

```sh
➜  /tmp which terraform && cdktf get
/Users/doneill/.asdf/shims/terraform
(node:4076) UnhandledPromiseRejectionWarning: Error: Usage Error: /private/tmp is not a cdktf project directory, no cdktf.json found or cdktf.json is missing language / app keys
    at Object.Usage (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:593:596)
    at b4 (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:593:894)
    at Object.HWr (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:662:3794)
    at Object.handler (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:52:10850)
    at /Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9052
    at j (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:4931)
    at M.applyMiddlewareAndGetResult (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:9021)
    at M.runCommand (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:7206)
    at Jt.[runYargsParserAndExecuteCommands] (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:55997)
    at Jt.parse (/Users/doneill/.asdf/installs/nodejs/14.18.3/.npm/lib/node_modules/cdktf-cli/node_modules/yargs/build/index.cjs:1:38250)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4076) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4076) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[2022-02-11T12:53:20.868] [ERROR] default - No version is set for command terraform
Consider adding one of the following versions in your config file at
terraform 1.1.5

No version is set for command terraform
Consider adding one of the following versions in your config file at
terraform 1.1.5

Debug Information:
    Terraform CDK version: 0.9.0
    Terraform version: Unknown: Error loading terraform version Error: non-zero exit code 126
[2022-02-11T12:53:21.094] [ERROR] default - No version is set for command terraform

No version is set for command terraform
[2022-02-11T12:53:21.094] [ERROR] default - Consider adding one of the following versions in your config file at

Consider adding one of the following versions in your config file at
[2022-02-11T12:53:21.102] [ERROR] default - terraform 1.1.5

terraform 1.1.5
➜  /tmp
```

**Comment by ansgarm** [comment]
Are you able to run `terraform --version` in `/tmp` without error?

**Comment by damianoneill** [comment]
It generates a similar issue as above.  

To clarify I have it working now, through you forcing me to explain it :-) 

asdf seems to work (I'm not an expert):

- by requesting that in a directory (or parent directory) 
- if a plugin is installed and you invoke it
-  that a .tool-versions file exists with an entry for the tool (and the version) that you're calling.

So I did two things, 

1. I downloaded terraform separately and updated my path, this worked fine.
2. I created a .tool-versions in my home directory and added terraform as a plugin, and that worked fine.

So I'm speculating that the cdktf get is invoking terraform outside of the current directory (maybe /tmp?), or the current filesystem isn't available, is this correct?  

Thanks for your help.  
Damian.

**Comment by ansgarm** [comment]
Glad that it works now!

>So I'm speculating that the cdktf get is invoking terraform outside of the current directory (maybe /tmp?), or the current filesystem isn't available, is this correct?

Yes, that is exactly what is happening. We are invoking `terraform` in a temporary directory.

Another thing that could work (and would ensure that it is using the locally specified Terraform version from `.tool-versions`) would be to pass the `TERRAFORM_BINARY_NAME` environment variable. It could look like this (untested):
```
TERRAFORM_BINARY_NAME="asdf which terraform" cdktf get
```

**Comment by ansgarm** [comment]
@damianoneill can this issue be closed?

**Comment by damianoneill** [comment]
@ansgarm just noticed your docs comment (separate issue), there is an example here https://github.com/damianoneill/cdk if it helps.

**Comment by ansgarm** [comment]
Linked it in the issue! Thanks @damianoneill!

**Comment by matschaffer-roblox** [comment]
Thanks for filing this. I ran into the same issue. As a workaround I added an `.envrc` like this:

```
export TERRAFORM_BINARY_NAME="$(asdf which terraform)"
```

I also opened https://github.com/asdf-community/asdf-hashicorp/issues/64 for consideration in the asdf plugin.
