### ISSUE TITLE
Add docs for `TERRAFORM_BINARY_NAME` environment variable

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1562]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We don't have docs on the `TERRAFORM_BINARY_NAME` environment variable yet.
We could use `asdf` as an example in the new docs, like done [here](https://github.com/hashicorp/terraform-cdk/issues/1559#issuecomment-1036221905) (untested, should be tried first 😅).

### References

* https://github.com/hashicorp/terraform-cdk/issues/1559#issuecomment-1036221905
* https://github.com/damianoneill/cdk (Example using `asdf`)

**Comment by DanielMSchmidt** [comment]
This is done already: https://www.terraform.io/cdktf/create-and-deploy/environment-variables
