### ISSUE TITLE
AWS Adapter: Default example not working. Invalid generated cdk.tf.json

### ISSUE THREAD

**Issue by Yoshyn** [hashicorp/terraform-cdk#1577]
### Affected Resource(s)

* Terraform v1.1.6
* cdktf 0.8.6
* @cdktf/aws-cdk 0.2.29
* aws-cdk-lib 2.12.0

Implemented this exact example : https://www.terraform.io/cdktf/create-and-deploy/aws-adapter

### Debug Output

`cdktf deploy`

```
Fail with errors :
⠹ planning cdktf-javascript...
[2022-02-18T16:05:07.482] [ERROR] default - ╷
│ Error: Missing required argument
│
│   on cdk.tf.json line 107, in resource.aws_cloudwatch_event_target.adapter_ruleF2C1DCDC_target0_82E1D1E6.ecs_target:
│  107:         "ecs_target": {},
│
│ The argument "task_definition_arn" is required, but no definition was
│ found.
╵

╷
│ Error: Missing required argument
│
│   on cdk.tf.json line 107, in resource.aws_cloudwatch_event_target.adapter_ruleF2C1DCDC_target0_82E1D1E6.ecs_target:
│  107:         "ecs_target": {},
│
│ The argument "task_definition_arn" is required, but no definition was
│ found.
╵
non-zero exit code 1
```

### Terraform generated file (truncated) :

```json
// cdktf.out/stacks/cdktf-javascript/cdk.tf.json
"aws_cloudwatch_event_target": {
  "adapter_ruleF2C1DCDC_target0_82E1D1E6": {
    "arn": "${jsondecode(aws_cloudcontrolapi_resource.adapter_lambda8B5974B5_06304D76.properties)[\"Arn\"]}",
    "rule": "${aws_cloudwatch_event_rule.adapter_ruleF2C1DCDC_10BF962A.id}",
    "ecs_target": {},
    "//": {
      "metadata": {
        "path": "cdktf-javascript/adapter/ruleF2C1DCDC_target0",
        "uniqueId": "adapter_ruleF2C1DCDC_target0_82E1D1E6"
      }
    }
  }
}
```

### Expected Behavior

Resources should be deployed. The terraform generated file should not include `"ecs_target": {},`.

Removing `"ecs_target": {},` by hand and run `terraform apply` inside `cdktf.out/stacks/cdktf-javascript/` works.

**Comment by ansgarm** [comment]
@Yoshyn fyi: I transferred the issue to our main repository 🙂

**Comment by skorfmann** [comment]
@ansgarm mights this be fixed by the recent changes?

**Comment by ansgarm** [comment]
@skorfmann maybe – although it should not have been broken in the first place. There is even a test for exactly this example which was correct on v0.2.29:
https://github.com/hashicorp/cdktf-aws-cdk/blob/v0.2.29/examples/typescript-cron-lambda/main.test.ts#L43-L44

@Yoshyn Could you try to reproduce this with the latest version of the AWS adapter and the CDK for Terraform?
