### ISSUE TITLE
Convert fails with provider option passed

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1582]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Actual Behavior

See https://github.com/hashicorp/learn-terraform-cdktf-applications/issues/5 for a reproduction case

### References

- #0000

**Comment by ansgarm** [comment]
@DanielMSchmidt shouldn't the issue be "convert fails with**out** provider option passed"?

**Comment by DanielMSchmidt** [comment]
No, that issue got fixed. In this case it fails when passed a single provider
