### ISSUE TITLE
Use tfe_outputs for cross stack references when using tf cloud

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#1584]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The Terraform documentation recommends using `tfe_outputs` rather than `terraform_remote_state` when accessing outputs from TF Cloud workspaces.

### References

- https://www.terraform.io/language/state/remote-state-data
- https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/outputs

**Comment by DanielMSchmidt** [comment]
I think this could be solved in a construct that extends the remote backend and overwrites the `getRemoteStateDataSource` function.

**Comment by xiehan** [comment]
We talked about this while we were working on the 0.15 release and the challenge is that we're not sure whether baking in a dependency on the TFE provider is the right solution either. I'm going to close this for now but we can always revisit later this year when we do some more work related to TFC.
