### ISSUE TITLE
Deploy all stack in project...or not? 

### ISSUE THREAD

**Issue by Ciruxx** [hashicorp/terraform-cdk#1587]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Classic CDK I can execute this command: 

`cdk deploy \*`
That deploy all stacks in the project.

So I try the same with cdktf: 
`cdktf deploy \*` and `cdktf deploy *` but maybe is not intended to work in this way.

So my question, and my feature request: 
 - With this deploy function I understand that cdktf standard is have one stack with all the resources inside that, is correct? If not, how is intended to work? What would be the standard for organizing the project? Because usually I divide my project in different stacks that rapresent different part of project and the stacks can be many and linked together by refs! So deploy only single stacks becomes a problem with this method.
 - Is a planned functionality or cdktf have made a different choice?   

### References

No references.

Thanks!

**Comment by DanielMSchmidt** [comment]
You can have more than one stack, each of them are separate terraform workspaces. It's encouraged to split your project into multiple stacks. These docs explain stacks from our point of view: https://www.terraform.io/cdktf/concepts/stacks

We are working for 0.10 on adding functionality around deploying multiple stacks at once: https://github.com/hashicorp/terraform-cdk/issues/650 Right now you have to deploy one after another by specifying their name, e.g. `cdktf deploy my-stack-1`

**Comment by Ciruxx** [comment]
Ok, thank you for your response! 

So the release of this functionality will be, as planned, for the 30th March?

**Comment by DanielMSchmidt** [comment]
Yeah exactly

**Comment by disposedtrolley** [comment]
Thanks for the updates! We've implemented a bit of a hacky way to deploy multiple stacks, so this will be a welcome change when it drops!
