### ISSUE TITLE
Extend Support of Module Sources beyond Terraform Registry

### ISSUE THREAD

**Issue by joatmon08** [hashicorp/terraform-cdk#16]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The CDK for Terraform only supports generation of publicly available modules hosted in [registry.terraform.io](https://registry.terraform.io/v1/modules). In order to support private Terraform registries and other module sources, we will need to extend the CDK for Terraform to obtain module metadata to private or version-controlled sources.

### References

N/A

**Comment by tovbinm** [comment]
Adding local / custom modules (e.g. using Git submodules) would also be great.

**Comment by skorfmann** [comment]
This will be relatively easy when we have #232 

> Adding local / custom modules (e.g. using Git submodules) would also be great.

You mean local, as in not available on Github / Gitlab / etc?

**Comment by tovbinm** [comment]
Yeah, unpublished, say from an internal repo or a subfolder.

**Comment by skorfmann** [comment]
> Yeah, unpublished, say from an internal repo or a subfolder.

That makes sense, yes. I think that's not much different from a git remote. If one works, the other one will be easy to do as well.

**Comment by jsteinich** [comment]
Would something like `TerraformHclModule` used similar to https://github.com/jsteinich/terrastack/pull/5/files#diff-1526cfd8651d8210fb4a0decf140147aR70 be useful to anyone else while waiting for generation to be supported?

**Comment by skorfmann** [comment]
> Would something like `TerraformHclModule` used similar to https://github.com/jsteinich/terrastack/pull/5/files#diff-1526cfd8651d8210fb4a0decf140147aR70 be useful to anyone else while waiting for generation to be supported?

It's also possible to go with [escape hatches](https://cdk.tf/escape-hatch). Not quite as comfortable, but still possible :)

**Comment by cmclaughlin** [comment]
@jsteinich @skorfmann 

Does PR # 375 fix this?

No detailed explanation needed - I was just looking through issues and PRs and thought we might be able to close this one.

**Comment by skorfmann** [comment]
> Does PR #375 fix this?

Thanks for checking. That PR is the actual representation for a module in terms of HCL. This issue is about the code generation for modules, which only works for modules present in the Terraform Registry so far. We'd like to extend this to all regular sources of modules.

**Comment by skorfmann** [comment]
At the moment we're using a dedicated [Terraform Registry client](https://github.com/hashicorp/terraform-cdk/blob/8ec3840c631b648d68f7103b35a710a249feacd8/packages/cdktf-cli/lib/get/registry-client.ts) to fetch the required meta information about a module to generate the code.

When looking at the [various ways](https://www.terraform.io/docs/language/modules/sources.html) of consuming Terraform modules, I think it would be better to delegate the work of fetching the modules to Terraform Core directly. This could be done via defining a module block in a temporary working directory, running `terraform init` and use something like [hcl2json](https://github.com/tmccombs/hcl2json) to get all variables and outputs. Later on, this would be useful in the context of #231 as well.

Compared to the direct Terraform Registry API call, this will certainly a bit slower and use more resources, e.g. the `terraform init` call will download all required module dependencies as well. On the upside, we don't have to reimplement functionality which already exists and we'll always support what Terraform Core is going to support in the future.

**Comment by jsteinich** [comment]
@skorfmann do you know how the metadata in the terraform registry is generated? I'm curious if there is some tool that already exists internally that could be made more external.

**Comment by skorfmann** [comment]
> @skorfmann do you know how the metadata in the terraform registry is generated? I'm curious if there is some tool that already exists internally that could be made more external.

This seems to be the tool which is used to generate the module metadata   https://github.com/hashicorp/terraform-config-inspect

**Comment by skorfmann** [comment]
That's resolved with #522

**Comment by javiortizmol** [comment]
Do you have an example using the terraform hcl modules?, I would like to test it, because I created some modules in a private repo, so I would like to have them into the cdktf code.

**Comment by jsteinich** [comment]
Some light examples [here](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-modules.md#terraformhclmodule)
