### ISSUE TITLE
Consistent Warning when Provider Constructs were not generated

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#160]
It'd be good to have a consistent warning for the case where no provider constructs were generated in `.gen`

Example: 
![Screenshot 2020-07-14 at 15 58 01](https://user-images.githubusercontent.com/136789/87434588-f57f4800-c5ea-11ea-8b65-b3d94f8afd8e.png)

**Comment by skorfmann** [comment]
Just checked and confirmed it's still an issue 👍

**Comment by ansgarm** [comment]
We should check whether this is still an issue after the recent CLI refactor :)

**Comment by xiehan** [comment]
We're 99% confident this has been fixed after the last couple of refactors. If there are still problems, please file a new issue.
