### ISSUE TITLE
NODE_ENV mismatch config files

### ISSUE THREAD

**Issue by thegiantbeast** [hashicorp/terraform-cdk#1604]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CLI version `0.9.4`
Typescript

### Debug Output

I have a `config/default.json` file and whenever I try to interact with `cdktf` cli there's always this error that is shown up.
If I set `NODE_ENV=default` it complains is ambiguous and it only disappears when I set `NODE_ENV=development`, or when I rename the file to `config/production.json`.
Maybe this isn't a direct with with cdktf but if its not, whats the best practice to have a config that is not directly attached with the environments?

### Expected Behavior

No error output

### Actual Behavior

```
[2022-03-01T14:34:17.278] [ERROR] default - WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
[2022-03-01T14:34:17.278] [ERROR] default - WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
```

### Steps to Reproduce

Any `cdktf` command like `cdktf synth`.

**Comment by ansgarm** [comment]
Hi @thegiantbeast 👋

Have you installed and are you using the `node-config` npm package in your project?
It seems like that package requires a config file matching the `NODE_ENV`, if set to strict mode.

What kinds of values to you need to configure? You could use `TerraformVariable`s and supply them via e.g. `TF_VAR_some_variable="test" cdktf synth`. Using environment variables directly (e.g. `someAttribute: process.env.SOME_ENV_VARIABLE`) will cause the value at synth time to be included in the generated `cdk.tf.json` config. The same also applies to config passed using `node-config`.

**Comment by thegiantbeast** [comment]
@ansgarm really sorry for wasting your time 🤦 
After posting this issue, I realised that we use `node-config` and has nothing to do with `cdktf`. And already read their docs and fixed the issue.

Thanks a lot for your help in such a short time and sorry again for opening an issue that doesn't have anything to do with this. 👍
