### ISSUE TITLE
Use `ComplexList` classes for references to list attributes of resources

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1610]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

[#1499 Model complex lists as arrays](https://github.com/hashicorp/terraform-cdk/pull/1499) introduces the `ComplexList` class which allows users to call `.get(index)` on computed lists (computed = you can't pass an input value for this attribute). This allows users to write e.g.
```ts
cert.domainValidationOptions.get(0).resourceRecordName
```

By using the same mechanism for the getter values of other list attributes, we can use the same `.get(index).someAttribute` instead of requiring the use of Terraform functions. See the following example for how complicated that currently is:
https://github.com/hashicorp/terraform-cdk/blob/d48ab89125165ed1c7079773c69a5f7fd7ac3118/test/typescript/edge/main.ts#L55-L62

This would require asymmetric getters and setters which is not directly supported by TypeScript, but can be worked around by replacing the setter with a `putSomeAttribute` method. We currently already do this for lists with single items:
https://github.com/hashicorp/terraform-cdk/blob/d48ab89125165ed1c7079773c69a5f7fd7ac3118/test/typescript/providers/main.ts#L186-L187

There might be other downsides to this proposal, so please feel free to comment and link other related issues.

### References

- https://github.com/hashicorp/terraform-cdk/pull/1499
- https://github.com/hashicorp/terraform-cdk/issues/25 (could actually be a duplicate, but I wasn't sure)

**Comment by jsteinich** [comment]
This sounds good to me. Make sure to keep in mind point 2 from https://github.com/hashicorp/terraform-cdk/issues/1332#issuecomment-977475370.
Also should do something similar for maps.

Yeah, I think this would fully address #25, but many issues have been linked back to that one, so we should test them all out.
