### ISSUE TITLE
Unknown type tuple

### ISSUE THREAD

**Issue by benfortuna** [hashicorp/terraform-cdk#1618]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript

![image](https://user-images.githubusercontent.com/984966/157566434-2a404a35-c752-4437-9d97-2a31e6fa7615.png)

### Affected Resource(s)

* cdktf.json

![image](https://user-images.githubusercontent.com/984966/157566027-2a826c59-7b5b-4e1a-869e-bfb50e793b68.png)

* module "environment" variables.tf

![image](https://user-images.githubusercontent.com/984966/157566139-0ac7ef9f-5614-4eff-a304-aa6eea4486df.png)

### Debug Output

![image](https://user-images.githubusercontent.com/984966/157566231-efbce84f-15ae-4131-9ea9-a74be5cbcf16.png)

### Expected Behavior

When using modules we should be able to use "typle" type for input variables.

### Actual Behavior

Module generation fails when tuple type is used.

### References

- #0000

**Comment by jsteinich** [comment]
Need to update https://github.com/hashicorp/terraform-cdk/blob/8263964d3535c913ddab2770d3a7ecc61f53fa1e/packages/%40cdktf/provider-generator/lib/get/generator/module-generator.ts#L133 to have support for tuples.

**Comment by aayushharwani-aidash** [comment]
@jsteinich I want to solve this issue. I am new to community. Can you please help me ?

**Comment by jsteinich** [comment]
@aayushharwani-aidash Happy to have your help.
My previous comment links to the section of code that needs to be modified. Need to make sure `tuple` is included in the check and that a case is created to handle it.

https://github.com/hashicorp/terraform-cdk/blob/main/packages/@cdktf/provider-generator/lib/get/__tests__/generator/module-generator.test.ts would be a good place to add some test cases for the new type. You can basically just make a regular hcl file that contains variables of different tuple types and confirm that they work with test cases.

**Comment by kination** [comment]
@jsteinich @xiehan  depend on code, seems `object`, `list`, `set`, `map` is being handled inside. So for this update, is it mean that type `tuple` also needs to be handled. Is my understanding correct?

**Comment by kination** [comment]
@jsteinich could you check the following? https://github.com/hashicorp/terraform-cdk/pull/2964

Seems it changes as
```
list(tuple([string, string, number])) => tuple[string,string,number][]
```

If it seems okay, I'll include several test cases 👍
