### ISSUE TITLE
Can cdktf commands be executed inside python code?

### ISSUE THREAD

**Issue by Subhashini2610** [hashicorp/terraform-cdk#1624]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.9.4

### Affected Resource(s)

All azure resources in stack

### Debug Output

I am using cdktf for provisioning my resources using Python and Terraform. I want to automate this entire process and hence, asking for the "cdktf deploy" to be part of the python code, as below:
```
from constructs import Construct
from cdktf import App, TerraformStack
from imports.azurerm import AzurermProvider, ResourceGroup
import subprocess


class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)

        # define resources here
        loca="West Europe"
        rg_name="example-rg1"
        tag = {
            "ENV": "Dev",
            "PROJECT": "AZ_TF"
        }
        AzurermProvider(self, "Azurerm", \
                        features={}
                        )

        example_rg = ResourceGroup(self, 'example-rg1', \
                                   name=rg_name,
                                   location = loca,
                                   tags = tag
                                   )

app = App()
name = "cdktf5"
MyStack(app, name)
app.synth()
subprocess.run(["cdktf", "deploy"])
```

### Expected Behavior

The deploy command should run as it does from CLI

### Actual Behavior

However, this does not work as expected, with the following output:
```

⠼ synthesizing...

⠙ synthesizing...

⠇ synthesizing...

⠸ synthesizing...

⠇ synthesizing...

⠦ synthesizing...
```

Needless to say, the resources are not created.

**Comment by DanielMSchmidt** [comment]
No, this is currently not supported, we track the work to support this in #1104 

Please leave a comment there on your use-case, so we can make sure we design a solution that also works for you :)

**Comment by Subhashini2610** [comment]
Thanks @DanielMSchmidt . I have upvoted there. One more question though. Is there a way to know when the app.synth() operation is completed?

**Comment by DanielMSchmidt** [comment]
Yeah, it's complete wenn the CLI finishes. If you have a `subprocess.run(["cdktf", "deploy"])` in the code you effectively created an endless loop and it never finishes

**Comment by DanielMSchmidt** [comment]
For clarity, this should be working

```python
from constructs import Construct
from cdktf import App, TerraformStack
from imports.azurerm import AzurermProvider, ResourceGroup
import subprocess


class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)

        # define resources here
        loca="West Europe"
        rg_name="example-rg1"
        tag = {
            "ENV": "Dev",
            "PROJECT": "AZ_TF"
        }
        AzurermProvider(self, "Azurerm", \
                        features={}
                        )

        example_rg = ResourceGroup(self, 'example-rg1', \
                                   name=rg_name,
                                   location = loca,
                                   tags = tag
                                   )

app = App()
name = "cdktf5"
MyStack(app, name)
app.synth()
```

**Comment by DanielMSchmidt** [comment]
What you wanted to build also relates to  #237

**Comment by rahulgoud19** [comment]
@Subhashini2610  there is one way I tried it for my setup and it worked. You can try and deploy it in the following way 
```
command = f"cdktf deploy {stack_name} --auto-approve"
call(command,cwd=terraform_templates_dir,shell=True)
  ```
  here basically your terraform_templates_dir would be the one where you have initialized cdktf and u can run this pretty much from the dir/path where you are running your script.

**Comment by Subhashini2610** [comment]
@rahulgoud19 I have already implemented such a thing, except it is a primitive way to define this. For example, if I want to get the stack outputs and store it to a variable, it would not be so easy.
But definitely, this helps!

**Comment by skorfmann** [comment]
> @rahulgoud19 I have already implemented such a thing, except it is a primitive way to define this. For example, if I want to get the stack outputs and store it to a variable, it would not be so easy.
> But definitely, this helps!

You could write an output file with `--outputs-file` and read that file. That's what I've done when driving integration tests via the `cdktf` cli. Either way, agree there would be a lot of value in having https://github.com/hashicorp/terraform-cdk/issues/237

Gonna close this as another reference for https://github.com/hashicorp/terraform-cdk/issues/237 - Please feel free to add any additional context to that issue.
