### ISSUE TITLE
EACCES when generating Python bindings with cdktf get

### ISSUE THREAD

**Issue by pecigonzalo** [hashicorp/terraform-cdk#1629]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDK: `0.9.4`
Python: `v3.9.10`
OS: OSX `12.3` (On Apple M1)

### Affected Resource(s)

- Getting modules

### Expected Behavior

We are able to generate the bindings for the module

### Actual Behavior

```
❯ cdktf get
NOTE: Temp directory retained due to an error: /var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO
[Error: EACCES: permission denied, unlink '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/.eslintignore'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/.eslintignore'
}
⠦ downloading and generating modules and providers...
EACCES: permission denied, unlink '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/.eslintignore'
```

### Steps to Reproduce

- Create an App with `cdktf init --template=python --local`
- Add a local module reference to `cdktf.json`
```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "projectId": "18f2994c-d514-44d3-b42d-61685ae709b3",
  "terraformProviders": [],
  "terraformModules": [
    "/Users/pecigonzalo/src/modules/my-super-module"
  ],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```
- Run `cdktf get`

### Important Factoids

- Node, Python and the CDKTF have been installed with Nix
- When checking the file and folder permissions of the temp directory that gets created, they are missing `w` permissions so this is expected given that problem, but I believe they should not be created without `w`.
```
❯ la /var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/.eslintignore
.r--r--r-- 28 pecigonzalo 19 Mar 11:37  /var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/.eslintignore
```
- I've tested with the `typescript` CDK and that works without issues, I believe because it does not require the temp directory for generating bindings

**Comment by pecigonzalo** [comment]
I've done some further testing, and if I initialize a "local" node and `cdktf-cli` for the repo/folder, it works.

NOTE: I continue to use the python CDK, just use yarn/node to install the CLI locally

- `yarn init`
- `yarn add cdktf-cli`
- Add `./node_modules/.bin` to `PATH`
- `cdktf get`

**Comment by ansgarm** [comment]
Thank you for raising this @pecigonzalo!

As someone who has never used nix: Could you assist me with reproducing the issue? Besides installing Nix, how does your setup look like / what configuration did you specify to install node, CDKTF, Terraform etc ?

I guess this has to do with the permission system Nix uses, right?
I found this [comment on Reddit](https://www.reddit.com/r/NixOS/comments/8cnm50/cannot_install_package_globally_with_npm/dxgkwfn/) but they also seem to recommend to install such dependencies locally (as you did, if I understood that correctly).

**Comment by pecigonzalo** [comment]
Hey @ansgarm to clarify, Im using Nix but not NixOS. I've tried with the prefix, but it did not seem to do the trick.

Whats odd is that CDK does not seem to be installing a global dep, as you can see its installing to `/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-h6GmsO/node_modules/cdktf/`. That is not the path from which Im running the project/test.

For reference:
- Im using macOS
- Im using Nix + Home-Manager + Nix-Darwin
- Im using Nix Flakes

Ill try and produce a small flake so you can easily reproduce (unless it work with a local flake) without needing all of that. Besides that, could check/verify this works in vanilla macOS with a globally installed `cdktf`?

**Comment by ansgarm** [comment]
Ah, thanks!

Did you only install `cdktf-cli` globally or also `cdktf`? There should be no need to install `cdktf` globally, as the `cdktf-cli` includes it as its dependencies. The `cdktf` package is installed locally if you use TypeScript but as you are using Python it is part of the Pypi package there.

**Comment by pecigonzalo** [comment]
I've installed the `cdktf-cli`, sorry about the confusion. Package: https://search.nixos.org/packages?channel=unstable&show=nodePackages.cdktf-cli&from=0&size=50&sort=relevance&type=packages&query=cdktf

**Comment by ansgarm** [comment]
Ah, I see. Did your testing succeed?
I did a bit of research as well and found out what is happening while running `cdktf get` that writes to this temporary directory. We are using [jsii-srcmak](https://github.com/cdklabs/jsii-srcmak) to create the bindings for Python which under the hood creates a new JSII project in a temporary directory to invoke `jsii-pacmak` on, which in turn creates translated bindings for Python. This also explains why there is something like an `.eslintignore` file present even.
Maybe it might make sense to ask for support on some Nix related forums to find out why the spawned pacmak process ends up creating files with missing write permissions.

Which NodeJS version are you (or is Nix) using by the way?

**Comment by pecigonzalo** [comment]
I used `npx` from Nix to test if it was related to the `cdktf-cli` installed by Nix and yeah, it seems like the Nix version is likely wrapped or something and causing some issues.

```
❯ cdktf get
NOTE: Temp directory retained due to an error: /var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-nD5NBU
[Error: EACCES: permission denied, unlink '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-nD5NBU/node_modules/cdktf/.eslintignore'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'unlink',
  path: '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-nD5NBU/node_modules/cdktf/.eslintignore'
}
EACCES: permission denied, unlink '/var/folders/8d/rj_0svpd1pj8l8wk1w9wbkk00000gp/T/temp-nD5NBU/node_modules/cdktf/.eslintignore'

❯ ~/.nix-profile/bin/npx cdktf-cli get
Generated python constructs in the output directory: imports
```

NPM Version: `8.3.1`

Seems like we can close this, I hope at least its existence helps the next one looking to solve this. Ill re-open this in the Nix community and backlink.

**Comment by ansgarm** [comment]
Alright, will close it then!

> I hope at least its existence helps the next one looking to solve this.

👍
