### ISSUE TITLE
CDKTF documentation has broken URLs

### ISSUE THREAD

**Issue by chefgs** [hashicorp/terraform-cdk#1651]
As part of learning CDK for Terraform, I was going through the [cdktf examples](https://www.terraform.io/cdktf/examples) documentation page. 
I found that below two hyperlinks are broken and showing `Page Not Found` error,
- [Build AWS Infrastructure with Python](https://learn.hashicorp.com/tutorials/terraform/cdktf-build-python?in=terraform/cdktf)
- [Build AWS Infrastructure with Go](https://learn.hashicorp.com/tutorials/terraform/cdktf-build-go?in=terraform/cdktf)

So it would be good to update the docs with correct links.
Thanks in advance.

**Comment by ansgarm** [comment]
Hi @chefgs,
those tutorials were combined into a [new one](https://learn.hashicorp.com/tutorials/terraform/cdktf-build?in=terraform/cdktf) which also supports TypeScript, C# and Java.
But yeah, we need to update the links 👍 Thanks for raising this.

**Comment by sxt90128** [comment]
I will work on this, thanks
