### ISSUE TITLE
tagging not working correclty 

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1654]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf - 0.9.4
node - 16.2.0
typescript

### Affected Resource(s)
I am creating a nodegroup for EKS with various tags. Certain tags do not show up in AWS at all. I have tried changing around the order and stuff but it will only show the same 5 tags and nothing more, nothing less
```
  customtag: {
    "Name": "eks-node",
    "kubernetes.io/role/internal-elb": '1',
    "kubernetes.io/role/elb": '1',
    "kubernetes.io/cluster/cluster-name": 'shared',
    "kubernetes.io/cluster/****-eks": 'owned',
    "k8s.io/cluster-autoscaler/****-eks": 'owned',
    "k8s.io/cluster-autoscaler/enabled": 'true',
    "environment": 'production',
    "k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage": "80G"
  },
```

### Debug Output
There is no error output that I could find

### Expected Behavior
All the listed tags would be added to the ASG that is created by terraform. 

### Actual Behavior
Tags are missing
![image](https://user-images.githubusercontent.com/66384196/160016461-401f9837-1989-4c89-aab0-6a7c2541e7d6.png)

### References

- #0000

**Comment by jsteinich** [comment]
How are you setting the tags in your cdktf code?

**Comment by jin-ahn** [comment]
> How are you setting the tags in your cdktf code?
I add them as part of the config in the constructor. 
```
    const nodegroup = new EKS.EksNodeGroup(this, this.nodeGroupName, {
      clusterName: this.clusterName,
      instanceTypes: this.instanceTypes,
      nodeRoleArn: this.nodeGroupRoleArn,
      nodeGroupNamePrefix: this.nodeGroupName,
      subnetIds: this.subnetIds,
      amiType: this.amiType ?? "AL2_x86_64",
      lifecycle: {
        createBeforeDestroy: true,
      },
      scalingConfig: {
        desiredSize: config.desiredSize ?? 1,
        maxSize: config.maxSize ?? 2,
        minSize: config.minSize ?? 1
      },
      dependsOn: config.dependsOn,
      diskSize: config.diskSize ?? 20,
      labels: config.labels,
      tags: {
        "Name": "eks-node",
        "kubernetes.io/role/internal-elb": '1',
        "kubernetes.io/role/elb": '1',
        "kubernetes.io/cluster/cluster-name": 'shared',
        "kubernetes.io/cluster/****-eks": 'owned',
        "k8s.io/cluster-autoscaler/****-eks": 'owned',
        "k8s.io/cluster-autoscaler/enabled": 'true',
        "environment": 'production',
        "k8s.io/cluster-autoscaler/node-template/resources/ephemeral-storage": "80G"
      },
    })
```

**Comment by jin-ahn** [comment]
I guess this is a known issue with terraform/aws https://github.com/terraform-aws-modules/terraform-aws-eks/issues/860

**Comment by ansgarm** [comment]
Yeah, it seems like that is an upstream issue. Should we close this here?
