### ISSUE TITLE
`aws_ami.ebs_block_device` block doesn't support `kms_key_id` attribute

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#1655]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Using `cdktf` v.0.9.4 and latest `cdktf_cdktf_provider_aws` Python package.

### Affected Resource(s)

The `ebs_block_device` block of the `aws_ami` is missing the `kms_key_id` attribute. Passing this parameter into the `AmiEbsBlockDevice` class throws an error.

### Debug Output
```
 TypeError: AmiEbsBlockDevice.__init__() got an unexpected keyword argument 'kms_key_id'
```

### Steps to Reproduce

```python
            AmiEbsBlockDevice(
                device_name='/dev/sda1',
                delete_on_termination=False,
                encrypted=True,
                kms_key_id='some-long-key-id',
                volume_size=10,
                volume_type='gp2',
            )
```

### References
Terraform documentation showing this key should exist: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami#ebs_block_device

**Comment by jsteinich** [comment]
You could try using an escape hatch (`ami.add_override('ebs_block_device[0].kms_key_id', 'key')`), but it looks like this could be a bug with the provider itself. I don't actually see `kms_key_id` as [part of the schema](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ami.go#L80).

**Comment by ansgarm** [comment]
Hi @rirze,
the pre-built AWS provider is currently [still on v3](https://github.com/hashicorp/cdktf-provider-aws/blob/main/cdktf.json#L5) which [doesn't support](https://registry.terraform.io/providers/hashicorp/aws/3.75.1/docs/resources/ami#ebs_block_device) `kms_key_id`.

You could try switching to [building the AWS provider locally](https://www.terraform.io/cdktf/concepts/providers-and-resources#add-provider-to-cdktf-json) to use v4 until it is updated.

**Comment by ansgarm** [comment]
Related to https://github.com/hashicorp/cdktf-provider-aws/issues/529 (where I saw you comment already).

**Comment by rirze** [comment]
Thanks guys, I should've checked if the AWS Provider V3.X supported it. I'll go ahead and close it since it's not an issue with cdktf-core.
