### ISSUE TITLE
cdktf --output isnt working as expected 

### ISSUE THREAD

**Issue by rahulgoud19** [hashicorp/terraform-cdk#1662]
Hi, I am trying to deploy a couple of resources on AWS using the cdktf tool, however whenever I run  ```cdktf deploy --auto-approve``` all the terraform templates are being automatically created in the current working directory. When I try the same command with --output option the command fails with the following error. 

```
cdktf deploy stack_1648329685 --output /Users/rahul/setup/terraform_templates/terraform_outputs --auto-approve
ERROR: synthesis failed, app expected to create "/Users/rahul/setup/terraform_templates/terraform_outputs/manifest.json"

**Comment by skorfmann** [comment]
Was just trying to replicate this issue with the latest `cdktf-cli@next` and it seems to be working as expected.

Which version of the `cdktf-cli`/ `cdktf` are you using? Also which language are you targeting and I'm assuming you have multiple stacks in your application?

**Comment by rahulgoud19** [comment]
@skorfmann I am currently using 0.10.0-pre.38 and Python for configuring, synthesizing and deploying the stacks. And yeah i have multiple stacks which I am deploying sequentially.

**Comment by ansgarm** [comment]
Hi @rahulgoud19,
when you run cdktf with the `--output` option, does it still output to the current directory? Or can you find the output elsewhere?

Which OS are you on and how did you install the cdktf-cli?
