### ISSUE TITLE
Support for providers attribute when using Terraform modules

### ISSUE THREAD

**Issue by javierlga** [hashicorp/terraform-cdk#1666]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support for `providers` attribute when using Terraform modules.  

Define multiple providers within a class, e.g.:

```
import { AwsProvider } from './.gen/providers/aws/aws-provider';
import { AwsProvider } from './.gen/providers/aws/aws-provider 2';

    new AwsProvider(this, 'aws', {
      region: 'us-west-1',
      accessKey: process.env.AWS_ACCESS_KEY_ID,
      secretKey: process.env.AWS_SECRET_ACCESS_KEY,
      alias: 'us-west-1'
    });
    
    new AwsProvider2(this, 'aws-old-version', {
      region: 'us-west-2',
      accessKey: process.env.AWS_ACCESS_KEY_ID,
      secretKey: process.env.AWS_SECRET_ACCESS_KEY,
      alias: 'us-west-2'
    });
```

So we can have the flexibility of defining and using more than one provider on `cdktf.json` config file.  
`"terraformProviders": ["hashicorp/aws@~> 4.0.0", "hashicorp/aws@~> 3.5"],`

This is useful when importing/migrating a module to CDKTF that was built using an older provider version but the operator wants to build the rest of the resources using a newer provider version.

 ```
    const s3 = new S3(this, "s3", {
      providers: {
       aws: AwsProvider2.us-west-2
      }
      ...
    })
```

### References

https://www.terraform.io/language/modules/develop/providers#passing-providers-explicitly

**Comment by jsteinich** [comment]
Is this actually possible to do in Terraform? Anything I've found seems to indicate that you can't do that without effectively creating a "new" provider.

**Comment by javierlga** [comment]
> Is this actually possible to do in Terraform? Anything I've found seems to indicate that you can't do that without effectively creating a "new" provider.

Yes, you can https://www.terraform.io/language/modules/develop/providers#passing-providers-explicitly

**Comment by jsteinich** [comment]
> > Is this actually possible to do in Terraform? Anything I've found seems to indicate that you can't do that without effectively creating a "new" provider.
> 
> Yes, you can https://www.terraform.io/language/modules/develop/providers#passing-providers-explicitly

Apologizes for the misunderstanding. I know that providing providers to modules is possible in Terraform (it's also possible in cdktf). The part that I haven't seen done is having those providers actually be different versions. The closest I've found is https://stackoverflow.com/a/66430076.

**Comment by skorfmann** [comment]
Both, the generated module bindings and the `TerraformHclModule` class are accepting `providers` already (see https://www.terraform.io/cdktf/concepts/modules as well). 

> Apologizes for the misunderstanding. I know that providing providers to modules is possible in Terraform (it's also possible in cdktf). The part that I haven't seen done is having those providers actually be different versions. The closest I've found is https://stackoverflow.com/a/66430076.

Doesn't seem like there's an easy way (except for compiling your own customized provider) to run two separate versions of the same provider.

@javierlga have you tried the code sample which you provided above?

**Comment by skorfmann** [comment]
So, I just tried it with this `cdktf.json` config:

```
  "terraformProviders": [
    {
      "name": "aws",
      "source": "hashicorp/aws",
      "version": "~> 3.5"
    },
    {
      "name": "aws-4",
      "source": "hashicorp/aws",
      "version": "~> 4.0"
    }],
```

And got the following error message 

```
 cdktf get
⠴ downloading and generating modules and providers...
╷
│ Error: Failed to query available provider packages
│
│ Could not retrieve the list of available versions for provider
│ hashicorp/aws: no available releases match the given constraints ~> 3.5, ~>
│ 4.0
╵
Error: non-zero exit code
```

So, I don't think there's a way how this could work out of the box. As the `modules` itself are taking provider arguments already, I'm gonna close this issue.

**Comment by javierlga** [comment]
@jsteinich makes sense about different provider versions. 
@skorfmann Thanks for pointing out to use `TerraformHclModule` ,  I was trying to use `providers` directly.
