### ISSUE TITLE
Adding Tags via aspects (following example in the docs) is not working

### ISSUE THREAD

**Issue by luca-nardelli** [hashicorp/terraform-cdk#1685]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- Typescript: 4.6.2
- cdktf: 0.10.1
- cdktf-cli: 0.10.1
- @cdktf/provider-aws: 7.0.6

### Description

I'm working on deploying a stack using @cdktf/aws-provider, and, while I am setting some tags using defaultTags of the aws provider, I also wanted to add some custom tags to specific resources that depended on the resource type (i.e. I cannot use `defaultTags` of the aws provider).

Following the example here (https://www.terraform.io/cdktf/concepts/aspects#define-aspects) no tags are added to any resource (verified by looking at the synthesized cdk.tf.json). Upon further inspection, it looks like `node.hasOwnProperty('tags')` does not fire for any of the stack nodes.

I tried changing that line to `'tags' in node` and that check started passing, however if I tried adding the new tags like in the example I got a `Cannot add elements to map token, got: [object Object]` error and synthesis failed.

### Affected Resource(s)

Aspects?

### Debug Output

https://gist.github.com/luca-nardelli/cd420c4700a37988e7a68e7f8b8b74e5 (this is for the `'tags' in node` scenario, since in the first one no tags were added but synthesis completed succesfully).

### Expected Behavior

Tags should have been added.

### Actual Behavior

Error in the synthesis (see description above)

### Steps to Reproduce

- Create a sample stack with aws provider (a simple lambda function should suffice)
- Define an aspect following this example https://www.terraform.io/cdktf/concepts/aspects#define-aspects
- Add the aspect to the stack and verify that no tags are added because `node.hasOwnProperty('tags')` never fires.
- Change the `hasOwnProperty` check to `'tags' in node`
- Verify that synthesis now returns an error

### Important Factoids

If I try to `console.log(node.tags)` I get this output:

`{ '&{TfToken[TOKEN.39]}': 'String Map Token Value' }`

**Comment by DanielMSchmidt** [comment]
Hey, thanks for filing this very detailed issue 👍 I could reproduce the problem and have an update for our documentation up as a PR: https://github.com/hashicorp/terraform-cdk/pull/1690
