### ISSUE TITLE
cdktf maven-metadata.xml file is not up to date

### ISSUE THREAD

**Issue by mirsilstan** [hashicorp/terraform-cdk#1689]
Hi,

The maven-metadata.xml file on Maven Central seems not to be up to date.
https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/maven-metadata.xml
The latest version is specified as 0.9.0-pre.7, although the latest version is 0.10.1

Consequently, when I updated the cdktf-provider-aws to 7.0.6, my build started failing, as this version depends on  the range [0.10.0, 0.11.0) of the cdktf library.

Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:7.0.6 -> com.hashicorp:cdktf:jar:[0.10.0,0.11.0)

I downgraded the provider to 6.0.6 and the build is successful again.

**Comment by ansgarm** [comment]
Hi @mirsilstan 👋
We have been migrated to a different server by Sonatype. I expected that to happen behind the scenes as our releases can still be found on [Maven Central](https://search.maven.org/artifact/com.hashicorp/cdktf).
Our releases can now be found here: https://hashicorp.oss.sonatype.org/content/repositories/releases/com/hashicorp/cdktf/maven-metadata.xml
Did you explicitly specify `repo.maven.apache.org` somewhere in your configuration? How did you setup your build?

**Comment by mirsilstan** [comment]
Hi @ansgarm,

Actually I am using a BitBucket Cloud pipeline with no additional configuration, a pure Maven installation.
I believe that by default Maven will download dependencies only from the central repository, at least that's what their documentation states. 
The link to the central repository points to **repo.maven.apache.org**
https://maven.apache.org/guides/introduction/introduction-to-repositories.html

_Downloading in Maven is triggered by a project declaring a dependency that is not present in the local repository (or for a SNAPSHOT, when the remote repository contains one that is newer). By default, Maven will download from the [central](https://repo.maven.apache.org/maven2/) repository._

I can try overriding the default repository and configuring the repository that you sent.

**Comment by meioli** [comment]
Hi @ansgarm,

we have the same issue as mirsilstan and I agree with him.

It would be nice if that could be fixed in maven central.

**Comment by ansgarm** [comment]
Hi @meioli,
thanks for confirming. I just reached out to our contact at Sonatype and will report back as soon as I get a reply.

**Comment by jorlina** [comment]
Is this still a problem?  I rebuilt the maven-metadata.xml file just in case, but I also just looked at:

https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/maven-metadata.xml

and I'm able to see a full complement of 0.10.* and 0.11.* versions, with 0.11.0-pre.54 being listed as the latest.

**Comment by DanielMSchmidt** [comment]
Seems to be solved 👍
