### ISSUE TITLE
NewDataGoogleComputeSubnetworkSecondaryIpRangeList does not implement any of the actual SecondaryIpRange structs

### ISSUE THREAD

**Issue by fxdgear** [hashicorp/terraform-cdk#1692]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```bash
❯ cdktf --version
0.10.1
```
language version: Go Lang

### Affected Resource(s)

* `google`

### Expected Behavior
To be able to assign subnet cider ranges to a subnet list

### Actual Behavior

```
cannot use service_range (type google.ComputeSubnetworkSecondaryIpRange) as type 
google.DataGoogleComputeSubnetworkSecondaryIpRangeList in slice literal: 
google.ComputeSubnetworkSecondaryIpRange does not implement 
google.DataGoogleComputeSubnetworkSecondaryIpRangeList (missing Fqn method)
```

### Steps to Reproduce

```go
network := google.NewComputeNetwork(stack, jsii.String("gke-cluster-network"), &google.ComputeNetworkConfig{
		Name:                  jsii.String("gke-cluster-network"),
		AutoCreateSubnetworks: jsii.Bool(false),
		Lifecycle: &cdktf.TerraformResourceLifecycle{
			PreventDestroy: jsii.Bool(true),
		},
	})

service_range := google.ComputeSubnetworkSecondaryIpRange{RangeName: jsii.String("cluster-subnet-services"), IpCidrRange: jsii.String("10.130.0.0/20")}
pod_range := google.ComputeSubnetworkSecondaryIpRange{RangeName: jsii.String("cluster-subnet-pods"), IpCidrRange: jsii.String("10.61.0.0/14")}

subnet := google.NewComputeSubnetwork(stack, jsii.String("gke-cluster-subnetwork"), &google.ComputeSubnetworkConfig{
		Name:             jsii.String("gke-cluster-subnet"),
		IpCidrRange:      jsii.String("10.129.0.0/20"),
		Network:          network.Name(),
		SecondaryIpRange: []google.DataGoogleComputeSubnetworkSecondaryIpRangeList{service_range, pod_range},
	})

```

### Important Factoids

If this is the wrong way to create the secondaryIpRangeList please let me know. 

When I look at the method for creating a new secondary IpRangeList `NewDataGoogleComputeSubnetworkSecondaryIpRangeList` it takes as parameters a: 
* `terraformResource` - cdktf.IInterpolatingParent
* `terraformAttribute` - *string
* `wrapsSet` - bool

So I tried creating the subnet first, then calling the `NewDataGoogleComputeSubnetworkSecondaryIpRangeList` function and passing in the `subnet` but there's no way to "add" ipRanges to this list.

I get the feeling that something is missing... or maybe I'm just not following how to do this correctly :disappointed:

**Comment by jsteinich** [comment]
You should be able to just create an array directly from `service_range` and `pod_range`. It should be of type `ComputeSubnetworkSecondaryIpRange`.

`DataGoogleComputeSubnetworkSecondaryIpRangeList` is part of the `DataGoogleComputeSubnetwork` data source.
