### ISSUE TITLE
Gap analysis of onboarding UX

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#1704]
Design & research task to evaluate user experience of creating a new CDKTF application via the `cdktf init` workflow. 

Areas to explore: 
- Developer UX of creating a new application from available language templates
- TF token response & lack of error handling 
- TFC signup flow for new user (evaluate current state vs. ideal) 

Related issues (not complete list)
- https://github.com/hashicorp/terraform-cdk/issues/1284
- https://github.com/hashicorp/terraform-cdk/issues/694
- https://github.com/hashicorp/terraform-cdk/issues/805 
- https://github.com/hashicorp/terraform-cdk/issues/840

**Comment by jsteinich** [comment]
Another area of consideration is how empty a directory needs to be. See #1697.

**Comment by xiehan** [comment]
We did some work on this last summer before Sarah left. While it wasn't complete, we have no immediate plans to pick this work back up again, so I'm going to close this issue for now. We can always open a new issue when/if we plan a new initiative in this area.
