### ISSUE TITLE
Split Azure and Google provider resources into namespaces

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1711]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To better support these big providers in languages where they are generated into a file and IDEs break with it. This issue is about splitting their generated codebase into submodules and building an alerting system for when we have resources not matching any submodule.

**Comment by schersh** [comment]
Related to https://github.com/hashicorp/terraform-cdk/issues/1606

**Comment by jsteinich** [comment]
I think it would be better to focus effort on fixing https://github.com/aws/jsii/issues/2436. See the discussion on #1606 for more context.

**Comment by ansgarm** [comment]
This issue is obsolete now as of CDKTF v0.13. Each resource now has its own namespace. Read more about the performance improvements and the background story: https://cdk.tf/0.13
