### ISSUE TITLE
Unable to find Digital Ocean provider in npm

### ISSUE THREAD

**Issue by didip** [hashicorp/terraform-cdk#1712]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

latest version

### Expected Behavior

The module used to be located here: `./.gen/providers/digitalocean`

### References

- #0000

**Comment by jsteinich** [comment]
It's not currently in the [list of pre-built providers ](https://github.com/hashicorp/cdktf-repository-manager/blob/main/provider.json). Perhaps it could be added, but until then, you can add it to your `cdktf.json` file and run `cdktf get` to generate bindings locally.

**Comment by ansgarm** [comment]
A pre-built provider for Digital Ocean is available now 🎉
https://github.com/hashicorp/cdktf-provider-digitalocean/releases/tag/v0.0.0
https://www.npmjs.com/package/@cdktf/provider-digitalocean
