### ISSUE TITLE
Issue with @cdktf/provider-postgresql Grant (Add terraform-parallelism flag)

### ISSUE THREAD

**Issue by Joe-Kollin** [hashicorp/terraform-cdk#1715]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
"@cdktf/provider-aws": "^7.0.13"
"@cdktf/provider-postgresql": "^0.4.12"
"@cdktf/provider-random": "^0.2.12"
"cdktf": "^0.10"

"ts-node": "^10.7.0",
"typescript": "^4.6.2"

### Affected Resource(s)

PostgresqlProvider Grant Resource

### Debug Output

`Error: could not execute revoke query: pq: tuple concurrently updated`

### Expected Behavior

Successfully created each role grant for each role.

### Actual Behavior

Concurrency error in spite of trying both the `--parallelism=0` and `--parallelism=1` flags

### Steps to Reproduce

```
roles.forEach((role) => {

     ...doStuff

      role.grants.forEach((grant) => {
        new Grant(this, `${this.deploymentPrefix}-${role.name}-${grant.objectType}-grant`, {
          role: role.name,
          database: role.database,
          objectType: grant.objectType,
          privileges: grant.privileges,
        });
      });

})
```

### Important Factoids

I've done some research and tried the concurrency flag which doesn't seem to be fixing anything. My assumption is that either something is wrong with the flag implementation in CDKTF or the Grant object itself.

**Comment by jsteinich** [comment]
You could try setting an environment variable as described [here](https://github.com/cyrilgdn/terraform-provider-postgresql/issues/178#issuecomment-1076494259).
cdktf doesn't currently support passing flags to Terraform, but you can also run Terraform directly from the stack output directory.

**Comment by ansgarm** [comment]
[This PR](https://github.com/hashicorp/terraform-cdk/pull/1625) added a `parallelism` flag to the cdktf-cli, however that one addresses deploying multiple stacks in parallel and does not show the same behaviour as the `parallelism` flag of the Terraform CLI. To me it would make sense to e.g. expose a `--terraform-parallelism` flag or similar to allow setting this flag, when required as a workaround for underlying provider issues.

**Comment by Joe-Kollin** [comment]
Thanks @jsteinich that worked for me. For anyone referencing this do:

`TF_CLI_ARGS_apply="-parallelism=1" cdktf deploy <stack name>`

@ansgarm  having a direct flag like that would definitely be nice though

**Comment by jsteinich** [comment]
#734 is asking for the same flag.

**Comment by ansgarm** [comment]
Hi @jaty613,
could you explain a bit more what you did that did not work? Which command did you try? What operating system are you using?

**Comment by jaty613** [comment]
> Hi @jaty613, could you explain a bit more what you did that did not work? Which command did you try? What operating system are you using?

env:
Terraform v1.1.7 on windows_386


terraform apply --auto-approve  (parallelism  parameters to take effect)

cdktf deploy  <stack name>  (Don't take effect)

![image](https://user-images.githubusercontent.com/3693273/164580708-75b271cf-9d52-4092-beeb-1606ce65ef3f.png)

**Comment by ansgarm** [comment]
Hi @jaty613, where do you set those environment variables? Are you using an IDE, a terminal (which one?) or something else?
What do you do to confirm that `parallelism` does not take effect? Terraform will only run things in parallel that have no dependencies onto each other – maybe that's what you are experiencing? Could you share your CLI output in a [Github Gist](https://gist.github.com/) or send us an reproduction case?

**Comment by jaty613** [comment]
> Hi @jaty613, where do you set those environment variables? Are you using an IDE, a terminal (which one?) or something else? What do you do to confirm that `parallelism` does not take effect? Terraform will only run things in parallel that have no dependencies onto each other – maybe that's what you are experiencing? Could you share your CLI output in a [Github Gist](https://gist.github.com/) or send us an reproduction case?

In the Windows operating system, set the environment variables as system environment variables and ensure that the environment variables take effect。

**Comment by ansgarm** [comment]
@jaty613
What terminal application are you using on windows?

**Comment by jaty613** [comment]
C:\Users\root>echo %TF_CLI_ARGS_apply%
-parallelism=800

**Comment by ansgarm** [comment]
You mentioned Powershell. Is it correctly returning the `-parallelism=800` in the Powershell as well?
How many resources do you apply (of which only 10 apply in parallel)?

**Comment by jaty613** [comment]
The terraform apply command parallelizes the maximum number of resources, but the CDKTF deploy command does not

**Comment by ansgarm** [comment]
Could you try setting the [`CDKTF_LOG_LEVEL`](https://www.terraform.io/cdktf/create-and-deploy/environment-variables#cdktf_log_level) environment variable and see if that has an effect (it should create more output logging while running e.g. deploy or diff).
