### ISSUE TITLE
Enable Attribute References for Nested Types

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#172]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Some providers (at least the Kubernetes provider) allow attribute references on anonymous interfaces (see #170). It would be good to support this.

That would be something like this:

```ts
const namespace = new Namespace(this, 'foo', {})
namespace.inputs.generation
```

### References

https://github.com/hashicorp/terraform-cdk/issues/170

**Comment by juliankrispel** [comment]
This issue blocked me from migrating this bit of terraform the other day:

```
resource "aws_route53_record" "example" {
  name    = aws_apigatewayv2_domain_name.example.domain_name
  type    = "A"
  zone_id = aws_route53_zone.example.zone_id

  alias {
    name                   = aws_apigatewayv2_domain_name.example.domain_name_configuration[0].target_domain_name
    zone_id                = aws_apigatewayv2_domain_name.example.domain_name_configuration[0].hosted_zone_id
    evaluate_target_health = false
  }
}
```

`domain_name_configuration[0]` doesn't currently contain either `target_domain_name` or `hosted_zone_id`

Until this is fixed, a suitable workaround would be to use the escape hatch:

```
yourRoute53Record.addOverride(‘alias.name’, `${yourGateway.fqn}.domain_name_configuration[0].target_domain_name`)
```

**Comment by skorfmann** [comment]
@juliankrispel thanks for the the additional input. I believe we could leverage the mapping which got introduced by https://github.com/hashicorp/terraform-cdk/pull/395 to create a custom mapping similar [to this](https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/fa44feb1ae4ff2c68def18990f30de442090b37c/src/apigatewayv2-domain-name.ts#L36-L41).

**Comment by jsteinich** [comment]
> @skorfmann I think this is supported now in 0.7.0, wdyt?

I don't think this is fully covered yet. The initial description got picked up, but some of the comments and linked issues I believe to still be missing.

**Comment by DanielMSchmidt** [comment]
I looked into @juliankrispel example, the only thing missing to make this happen is including computed types on the complex objects. So not closed, but close to being closed

**Comment by DanielMSchmidt** [comment]
Tracking this in #1332 which is a dedicated issue for the use case mentioned in the comments 👍
