### ISSUE TITLE
cdktf deploy does not respect `--output` directory for `.terraform/terraform.tfstate`

### ISSUE THREAD

**Issue by gc-ss** [hashicorp/terraform-cdk#1723]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf v0.10.1
Python 3.9.12

### Affected Resource(s)

When running `cdktf deploy --output=/deployed/deployed_cdktf_state` from `/tmp`

The synthesized `cdk.tf.json` ends up containing:

```
"backend": {
      "local": {
        "path": "/tmp/terraform.stack-name.tfstate"
      }
    },
```

…and saves the tfstate there (`/tmp/terraform.stack-name.tfstate`) on deployment - *which is surprising*.

### Expected Behavior

Expected `/tmp/terraform.stack-name.tfstate` to be at `/deployed/deployed_cdktf_state/terraform.stack-name.tfstate` instead.

Surprisingly `/deployed/deployed_cdktf_state/stacks/stack-name/.terraform/terraform.tfstate` is created under the stated `--output` directory (`/deployed/deployed_cdktf_state`) but it too contains:

```
"backend": {
    "type": "local",
    "config": {
        "path": "/tmp/terraform.stack-name.tfstate",
        "workspace_dir": null
    },
},
```

1. Is there a way to explicitly use a different directory for `terraform.stack-name.tfstate`?
2. Is this a bug or expected?

**Comment by jsteinich** [comment]
Looks like this is a bug with the implicit local backend handling.

You should be able to workaround by creating a `LocalBackend` instance in your stack and setting the path to `/deployed/deployed_cdktf_state/stacks/stack-name/.terraform/terraform.tfstate`

**Comment by DanielMSchmidt** [comment]
My understanding of the output directory is that the synthesized code should be put there, not necessarily the local state, but I might be lacking some context on that option 🤔

**Comment by gc-ss** [comment]
> , not necessarily the local state

Is there a commandline argument that would allow me to choose/change the location of the local state (with the implicit local backend, short of using another backend provider)?

The usecase is to run `cdktf` in a container with attached volumes.

If the local state is persisted where the code is, due to the way attached volumes behaves, there are issues (happy to delve deeper into it) - it would just be very clean to have a way to explicitly set/choose/change the location of the local state

**Comment by ansgarm** [comment]
Hi @gc-ss,
you don't have to use another backend provider, you could also explictly add a `LocalBackend` yourself. However, it is currently not possible to pass any configuration to the `LocalBackend` that is [automatically added](https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/terraform-stack.ts#L215) in case no backend was defined explicitly.

If you don't want to configure the backend explicitly in every stack, you could subclass the `TerraformStack` class and use that new stack class for all your stacks. That stack could then add a correctly configured `LocalBackend` for example in its constructor.
Another option would be to use an [Aspect](https://www.terraform.io/cdktf/concepts/aspects) that adds the required `LocalBackend`.

**Comment by gc-ss** [comment]
> > If you don't want to configure the backend explicitly in every stack, you could subclass the `TerraformStack` class and use that new stack class for all your stacks. That stack could then add a correctly configured `LocalBackend` for example in its constructor
> 
> Ah! Fair - the `LocalBackendTerraformStack` ! (maybe with a better name :D)

For anyone curious, here's how the `LocalBackendTerraformStack` would look like in Python:

```Python
class LocalBackendTerraformStack(
    TerraformStack,
):
    def __init__(
        self, scope: Construct, stack_name: str, *, tfstate_file_name="deployed_cdktf_state.tfstate"
    ):
        super().__init__(scope, stack_name)

        # Don't seem to need to override ensure_backend_exists to change the default LocalBackend? (https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/terraform-stack.ts#L215)
        self.local_backend_override = LocalBackend(
            scope=self,
            # Path where the state file is stored. defaults to terraform.${stackId}.tfstate
            path=pathlib.Path(scope.outdir).joinpath(tfstate_file_name).absolute().as_posix(),
            # workspace_dir="/usr/src/generic/deployed/",
        )
```

Summary:

While there's workarounds, this behavior _is surprising_ and it's better to be explicit than implicit.

The fix is to update either of these invocations so that the `process.cwd(),` takes the `outdir` into consideration:

- https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/terraform-stack.ts#L215
-  https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/backends/local-backend.ts#L20

**Comment by DanielMSchmidt** [comment]
You would do 

```py
class LocalBackendTerraformStack(
    TerraformStack,
):
   def __init__(
        self, scope: Construct, stack_name: str, *, tfstate_file_name="deployed_cdktf_state.tfstate"
    ):
        super().__init__(scope, stack_name)
       LocalBackend(scope=self,
            # Path where the state file is stored. defaults to terraform.${stackId}.tfstate
            path=pathlib.Path(scope.outdir).joinpath(tfstate_file_name).absolute().as_posix(),
            # workspace_dir="/usr/src/generic/deployed/",
        )
```

We don't need to override the local backend, it's only added if you don't have one configured for your stack.
As for the output directory, I disagree with the notion that it should be taken into consideration. More often than not the output directory is in the gitignore (like in all our templates), because if you don't have a strong reason you don't want to commit the HCL JSON files. If we change it like you propose this would mean we ignore the state file. Plus this folder gets cleaned by us, e.g. if you delete a stack, again making you loose your state.

**Comment by gc-ss** [comment]
> If we change it like you propose this would mean we ignore the state file. Plus this folder gets cleaned by us, e.g. if you delete a stack, again making you loose your state.

Al I am asking for is for the user allowed to be override where the `tfstate` would be stored. That is, update either of these invocations so that the `process.cwd(),` takes the `outdir` into consideration:

- https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/terraform-stack.ts#L215
-  https://github.com/hashicorp/terraform-cdk/blob/cbd52156e1e407e59d2462433f21f9dae2863056/packages/cdktf/lib/backends/local-backend.ts#L20

You can take a `context` variable into consideration as well. For those who don't want to override where the `tfstate` would be stored, the existing behavior remains.

For people like me, who have a strong reason to decouple the code from the state, we now have an easy option without needing to create a new `LocalBackend` (as we do is pass in a prop by some means - say, a `context` variable)

**Comment by skorfmann** [comment]
> The usecase is to run `cdktf` in a container with attached volumes.
> 
> If the local state is persisted where the code is, due to the way attached volumes behaves, there are issues (happy to delve deeper into it) - it would just be very clean to have a way to explicitly set/choose/change the location of the local state

Out of curiosity: Could you elaborate on the specific use-case and the issues you're seeing with volumes?

**Comment by DanielMSchmidt** [comment]
I don't think we are going to do this, it does not seem to be a standard use-case and can be solved by a combination of environment variable and local backend construct with no downsides.
