### ISSUE TITLE
Digital Ocean Kubernetes Cluster Not creating. Giving Error : The argument "size" is required, but no definition was found. 

### ISSUE THREAD

**Issue by Jahadul-Rakib** [hashicorp/terraform-cdk#1724]
Hello sir,
I am going to create a kubernetes cluster using cdktf and cdktf-provider-digitalocean...but i am stucking in a place .... i can not understand how can i overcome this issue. please help me....

### cdktf & Language Versions

Java and library cdktf-provider-digitalocean(0.0.6/0.0.5)

### Expected Behavior

**create kubernetes cluster**

### Actual Behavior
_Error: Missing required argument_
_The argument "size" is required, but no definition was found._

### Steps to Reproduce

        KubernetesCluster kubernetesCluster = KubernetesCluster.Builder.create (this, dto.getClusterName ())
                .name (dto.getClusterName ())
                .vpcUuid (vpc.getId ())
                .version (dto.getK8sVersion ())
                .region (dto.getRegion ())
                .autoUpgrade (true)
                .surgeUpgrade (true)
                .ha (dto.getHighAvailability ())
                .nodePool (KubernetesClusterNodePool.builder ()
                        .name ("default-node-group")
                        .nodeCount (dto.getDefaultNodeTotal ())
                        .size (dto.getDefaultNodeType ())
                        .build ())
                .dependsOn (List.of (vpc))
                .build ();

**Comment by jsteinich** [comment]
What is `dto`? Could `dto.getDefaultNodeType()` return `null`?

**Comment by Jahadul-Rakib** [comment]
dto is transfer object .... and dto.getDefaultNodeType() its return actual value...may be problem in libriry

**Comment by DanielMSchmidt** [comment]
I could reproduce the issue with static values: https://github.com/DanielMSchmidt/cdktf-issue-1724 Synthesizes without an error or warning, but it misses the size parameter in the node pool in the synthesised code

**Comment by jsteinich** [comment]
I'm pretty sure this will be fixed with #1725.

**Comment by DanielMSchmidt** [comment]
Should be fixed by #1725
