### ISSUE TITLE
cdktf deploy fails with "Unexpected token c in JSON at position 1"

### ISSUE THREAD

**Issue by mbaranovski** [hashicorp/terraform-cdk#1729]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
"@cdktf/provider-aws": "^7.0.20",
"cdktf": "^0.10.1",
"cdktf-cli": "^0.10.1",

Terraform v1.1.8
```

### Debug Output
Before `cdktf` plan is executed:
```
Debug Information:
    Terraform CDK version: 0.10.1
    Terraform version: Unknown: Error loading terraform version SyntaxError: Unexpected token c in JSON at position 1
```
After the plan JSON is generated:
```
[2022-04-19T14:44:36.026] [DEBUG] default - ::debug::Terraform exited with code 0.

Unexpected token c in JSON at position 1
[2022-04-19T14:44:36.029] [DEBUG] default - [my-stack]: errored
```

### Expected Behavior

Stack deploys

### Actual Behavior

The `cdktf` plan generates the JSON correctly and exists with exit code 0. However after that whatever comes next after plan (I assume it's `apply`) fails with error: `Unexpected token c in JSON at position 1` with no stack trace.

### Important Factoids
Fails on GH Actions, works locally.

**Comment by DanielMSchmidt** [comment]
It looks to me like `terraform version -json` did not run successfully in CI, could you try to add a CI step before cdktf synth that runs this command to see if the command itself works?

**Comment by mbaranovski** [comment]
Hi @DanielMSchmidt, the step you requested executes correctly:
<img width="1271" alt="image" src="https://user-images.githubusercontent.com/29602306/164052385-4732e424-7425-4771-8fc3-5b26235870d1.png">

**Comment by ansgarm** [comment]
Hi @mbaranovski,

are you using the `setup-terraform` Github Action?
If yes, maybe you're running into this issue: https://github.com/hashicorp/terraform-cdk/issues/1020

**Comment by mbaranovski** [comment]
That was the case! Thanks @ansgarm & @DanielMSchmidt
