### ISSUE TITLE
cdktf deploy support terraform  apply parallelism args

### ISSUE THREAD

**Issue by jaty613** [hashicorp/terraform-cdk#1736]
await exec(
      terraformBinaryName,
      [
        "apply",
        "-auto-approve",
        "-input=false",

        ...extraOptions,
        // only appends planFile if not empty
        // this allows deploying without a plan (as used in watch)
        ...(planFile ? [planFile] : []),
      ],
      { cwd: this.workdir, env: process.env, signal: this.abortSignal },
      this.onStdout("deploy"),
      this.onStderr("deploy")
    );

**Comment by DanielMSchmidt** [comment]
Closing this as duplicate, if I'm missing something let me know and I'll reopen :)
