### ISSUE TITLE
Design: Improved TFC integration for multi-stack projects

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1737]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we only create the first stack for users using TFC when running init, all other stacks need to be created manually.
The goal of this issue is to find a nicer way to manage multiple workspaces (and their secrets / run triggers / ...?) and propose a solution / vision for how we want to tackle this problem.

### References

- https://github.com/DanielMSchmidt/cdktf-multi-stack-tfe is a user-land approach to this

**Comment by DanielMSchmidt** [comment]
Yeah, though I'd like to include more day2 things here in addition to "just" auto creating like managing secrets etc.

**Comment by nikolay** [comment]
@DanielMSchmidt The following [dependency](https://github.com/hashicorp/terraform-cdk/issues/1583) for supporting TFC! I am not sure why this hasn't been available since day 1 - don't you guys use Terraform v1.1+ and TFC at HashiCorp?!

**Comment by DanielMSchmidt** [comment]
Sorry there is some misunderstanding happening here, we support TFC. The issue you are referencing is about a the current way of using terraform cloud (through the remote backend) is being deprecated by Terraform, so we should start supporting the new (through the cloud backend).

**Comment by nikolay** [comment]
@DanielMSchmidt It behaves differently, it's not just deprecation. By using "remote", you can't override sensitive remote variable - you can only do this with cloud backend. The "remote" backend comes with a bug, which, for some strange reason, was only fix in cloud.
