### ISSUE TITLE
Compile error with cdktf npm version> 0.8.0 

### ISSUE THREAD

**Issue by richa-misra** [hashicorp/terraform-cdk#1760]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf npm version:` 0.10.3`
aws provider version: `aws@~> 3.0`

### Debug Output
When running `cdktf get` with cdktf version >0.8.0, the generated aws provider typescript files fail to compile with the following error:
```
.gen/providers/aws/vpc/data-aws-vpc-peering-connection.ts(145,5): error TS2322: Type 'IResolvable' is not assignable to type 'boolean'.
.gen/providers/aws/vpc/data-aws-vpc-peering-connection.ts(277,5): error TS2322: Type 'IResolvable' is not assignable to type 'boolean'
```

### Expected Behavior

No errors should have been thrown

### Actual Behavior

Unable to upgrade to latest cdktf npm version

**Comment by jsteinich** [comment]
What's the output from running `cdktf debug`? I suspect a version mismatch between cli and what's referenced by your project.

**Comment by richa-misra** [comment]
Thanks for the quick reply Jon! When I tried setting both cdktf and cdktf-cli to version 0.10.3, I get this error on running `cdktf debug`

```
cdktf debug
/usr/local/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:42
`))};a.once("error",l=>{throw c(`jsii compilation failed. error: ${l.message}`)}),a.once("exit",l=>l===0?n():i(c(`jsii compilation failed with non-zero exit code: ${l}`)))})}Je.exec=mz;function dz(t){var e,r,n,i;if((e=t.python)===null||e===void 0?void 0:e.moduleName.includes("-"))throw new Error(`Python moduleName [${t.python.moduleName}] may not contain "-"`);if((r=t.java)===null||r===void 0?void 0:r.package.includes("-"))throw new Error(`Java package [${t.java.package}] may not contain "-"`);if((n=t.csharp)===null||n===void 0?void 0:n.namespace.includes("-"))throw new Error(`C# namespace [${t.csharp.namespace}] may not contain "-"`);if((i=t.golang)===null||i===void 0?void 0:i.moduleName.includes("_"))throw new Error(`Go module name [${t.golang.moduleName}] may not contain "_"`)}Je.validateOptions=dz});var Px=m(Ft=>{"use strict";var pz=Ft&&Ft.__createBinding||(Object.create?function(t,e,r,n){n===void 0&&(n=r),Object.defineProperty(t,n,{enumerable:!0,get:function(){return e[r]}})}:function(t,e,r,n){n===void 0&&(n=r),t[n]=e[r]}),hz=Ft&&Ft.__setModuleDefault||(Object.create?function(t,e){Object.defineProperty(t,"default",{enumerable:!0,value:e})}:function(t,e){t.default=e}),Bc=Ft&&Ft.__importStar||function(t){if(t&&t.__esModule)return t;var e={};if(t!=null)for(var r in t)r!=="default"&&Object.prototype.hasOwnProperty.call(t,r)&&pz(e,t,r);return hz(e,t),e};Object.defineProperty(Ft,"__esModule",{value:!0});Ft.compile=void 0;var yz=Bc(require("crypto")),Et=Bc(require("path")),Xi=Bc(Vs()),$x=zc(),gz=require.resolve("jsii/bin/jsii");async function vz(t,e){var r,n,i,o;(0,$x.validateOptions)(e);let s=["--silence-warnings","reserved-word"],u=(r=e.entrypoint)!==null&&r!==void 0?r:"index.ts";if(Et.extname(u)!==".ts")throw new Error(`jsii entrypoint must be a .ts file: ${u}`);if(!await Xi.pathExists(Et.join(t,u)))throw new Error(`unable to find typescript entrypoint: ${Et.join(t,u)}`);
```
Many thanks

**Comment by jsteinich** [comment]
@richa-misra I'm not sure why the debug command is failing, but to help diagnose that (and the original issue), I have a few questions about your environment.

- What node version are you using?
- Do you have cdktf-cli and/or cdktf installed globally? If so, what versions?

**Comment by richa-misra** [comment]
hi @jsteinich  yes issue was indeed due to the node version I was using. It gives the error above on node version `12.22.10` but when I tried building against node version `14.19.0`, it works well!

Thanks so much!

**Comment by DanielMSchmidt** [comment]
Nice, this seems to be fixed, I'll close the issue. @richa-misra Could you do me a favor and take a look if `cdktf debug` is still broken under the new node version?
