### ISSUE TITLE
Refactor Github Actions using reusable workflows

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1784]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we have a lot of repetition (e.g. for integration tests) in our Github action workflows. We should refactor them using [reusable workflows](https://docs.github.com/en/actions/using-workflows/reusing-workflows#creating-a-reusable-workflow) to avoid duplicated code.

**Comment by DanielMSchmidt** [comment]
Did this already for the integration tests etc that run after a release, is that enough for you @ansgarm ?

**Comment by ansgarm** [comment]
Yeah, that was my main thought here 👍
