### ISSUE TITLE
accessing gcp images cross project

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-cdk#1785]
I have a GCP `Project A` trying to access an Image on `Project B` and seems that it cannot find it.

```python
...
 GoogleProvider(self,id=GCP_PROJECT_NAME, region="us-east1", project=GCP_PROJECT_NAME, credentials = creds)

        gcp_image = DataGoogleComputeImage(self, id = "windows_image", project = "<PROJECTB-ID>" , name= "IMAGE-NAME")
```

by replacing the `project` argument in the `DataGoogleComputeImage` should actually run the query on `ProjectB`?

```
  HTTP/2.0 404 Not Found
     Alt-Svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000,h3-Q050=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000,quic=":443"; ma=2592000; v="46,43"
     Cache-Control: private
     Content-Type: application/json; charset=UTF-8
     Date: Mon, 09 May 2022 19:07:00 GMT
     Server: ESF
     Vary: Origin
     Vary: X-Origin
     Vary: Referer
     X-Content-Type-Options: nosniff
     X-Frame-Options: SAMEORIGIN
     X-Xss-Protection: 0

     {
     "error": {
     "code": 404,
     "message": "The resource 'projects/<-----PROJECT-A????----->/global/images/family/<IMAGE-NAME>' was not found",
     "errors": [
     {
     "message": "The resource 'projects/<----PROJECT-A???----->/global/images/family/<IMAGE-NAME>' was not found",
     "domain": "global",
     "reason": "notFound"
     }
     ]
     }
     }
```

**Comment by jsteinich** [comment]
You'll need to create separate `GoogleProvider` instances that point to each project. You can then use the `provider` argument to pass the appropriate one to the resource / data source. Make sure to give each provider an `alias` so that Terraform can distinguish them.

**Comment by lmayorga1980** [comment]
But in real terraform code I can make a reference to an external project image without having a different provider. That is why on `project B` there is a definition of `iam.image.user` for the service account on `project A`.

**Comment by jsteinich** [comment]
You may need to use an escape hatch to set the id.
`gcp_image.add_override("id", "windows_image")`.
Possibly related to #1602.

**Comment by lmayorga1980** [comment]
> You'll need to create separate `GoogleProvider` instances that point to each project. You can then use the `provider` argument to pass the appropriate one to the resource / data source. Make sure to give each provider an `alias` so that Terraform can distinguish them.

Making this type of call does not require another `provider`. Does it? for `cdktf`?
https://registry.terraform.io/providers/hashicorp/google/latest/docs/data-sources/compute_image

**Comment by lmayorga1980** [comment]
```json
{
  "//": {
    "metadata": {
      "backend": "local",
      "stackName": "gcp",
      "version": "0.10.1"
    },
    "outputs": {
      "gcp": {
        "image-name": "image-name",
        "instance_ip": "instance_ip"
      }
    }
  },
  "data": {
    "google_compute_image": {
      "data_image": {
        "//": {
          "metadata": {
            "path": "gcp/data_image",
            "uniqueId": "data_image"
          }
        },
        "name": "<IMAGE_NAME>",
        "project": "PROJECT A"
      }
    }
  },
...
```

It's weird that is referencing the image on `Project A` where it should be `Project B`

**Comment by jsteinich** [comment]
I took a closer look at the data source and it does seem like it should work with only a single provider given that the credentials used have the correct permissions.

The output posted is missing the `id` property, hence why I think you'll need to used the escape hatch suggested earlier.

There shouldn't be anything special happening with the `project` output, so I think most likely is an accidental run with the incorrect value.

**Comment by lmayorga1980** [comment]
The following fixed my issue.

``` 
       GoogleProvider(self,id=GCP_PROJECT_NAME, region="us-east1", project=GCP_PROJECT_NAME, credentials = creds)

        gcp_image = DataGoogleComputeImage(self, id = "windows_image", project = "<PROJECTB-ID>" , name= "IMAGE-NAME")

       
        gcp_instance = ComputeInstance(self,id = "windows_vm", machine_type="e2-standard-4", name="cdktf-instance-1", 
                        boot_disk= ComputeInstanceBootDisk(initialize_params=ComputeInstanceBootDiskInitializeParams(image=gcp_image.id)),
                        network_interface=[net_int], zone= "us-east1-a"
 ```
