### ISSUE TITLE
Object keys containing a colon fail when used in expressions

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#1795]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.10.4

### Expected Behavior

should work

### Actual Behavior

`cdktf plan` fails with

```
│ Error: Missing attribute separator
│
│   on cdk.tf.json line 12, in locals:
│   12:     "fails": "${keys({test:key = \"abc\"})}"
│
│ Expected a newline or comma to mark the beginning of the next attribute.
```

### Steps to Reproduce

```ts
const keys = Fn.keys({
      "test:key": "abc",
    });
new TerraformLocal(this, "fails", keys);
```

### References

This line is probably the cause:
https://github.com/hashicorp/terraform-cdk/blob/d4bb45fe6367ceed3514e5a81aa320f74b3b1e06/packages/cdktf/lib/tfExpression.ts#L27

https://github.com/hashicorp/terraform-cdk/issues/2675 (a duplicate of this) has a better description with a proposed solution.

**Comment by Truefiber** [comment]
It makes https://www.terraform.io/cdktf/create-and-deploy/aws-adapter
`new iam.PrincipalWithConditions(new iam.AccountPrincipal(accountId), {
                    "Bool": {
                        "aws:MultiFactorAuthPresent": "true"
                    }
                })`
fails on aws:MultiFactorAuthPresent with the same error

**Comment by jlsalmon** [comment]
A nasty but effective workaround seems to be adding nested double quotes inside single quotes for the key containing the colon:

```
const keys = Fn.keys({
      '"test:key"': "abc",
    });
```

**Comment by ansgarm** [comment]
No timeline, but I just created a PR with your proposed fix – if all tests pass, this'll be done 👍
