### ISSUE TITLE
Implement block-level iterators

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1798]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To support dynamic list iterations on the block / resource level we will introduce a new API, called Iterator.

In this issue we are building the block-level Iterator API. To create dynamic blocks one can use iterator.dynamic([...]) and the block will be repeated for each item in the list.

```ts
import { TerraformStack, Iterator } from "cdktf";
import { S3Bucket, DataAwsSubnets, DataAwsAllowedOrigins } from "./.gen/providers/aws-ficticious";
import { Construct } from "constructs";

export class MyStack extends TerraformStack {
 constructor(scope: Construct, id: string) {
   super(scope, id);

  // Fictitious data source that returns [{method, origin}]
   const allowedOrigins = new DataAwsAllowedOrigins(
     this,
     "possibleOrigins",
     {}
   );
   const allowedOriginsIterator = Iterator.fromList(allowedOrigins.origins);
   new S3Bucket(this, "my-bucket", {
     corsRule: allowedOriginsIterator.dynamic(
       {
         allowedMethods: [allowedOriginsIterator.getStringProperty("method")],
         allowedOrigins: [allowedOriginsIterator.getStringProperty("origin")],
         maxAgeSeconds: 42,
       },
     ),
   });
 }
}
```

### References

- Part of #1094
- Depends on #1797

**Comment by ansgarm** [comment]
Hi @RichiCoder1,

yeah, we thought about that as well. Unfortunately that can be misunderstood quite easily as we don't know how many items are in a list while invoking `.forEach`.
For example this:
```ts
   const allowedOriginsIterator = Iterator.fromList(allowedOrigins.origins);
   let index = 0;
   new S3Bucket(this, "my-bucket", {
     corsRule: allowedOriginsIterator.forEach(it =>
       {
         allowedMethods: [it.getStringProperty("method")],
         allowedOrigins: [it.getStringProperty("origin")],
         maxAgeSeconds: 42,
         someOtherAttribute: index++
       },
     ),
   });
```
would cause every item to have `someOtherAttribute: 0` because we render just a single dynamic block for "all items" in the `cdk.tf.json` file:
```
dynamic "cors_rule" {
  each: allowedOrigins.origins
  ...
  someOtherAttribute: 0
}
```
I hope that explained the underlying issue a bit, but I'm happy to give more context if things are still unclear.
Maybe we will find a solution to cleanly infer what a user is trying to do in their code at some point, but every idea we came up with so far, had lots of drawbacks unfortunately.

**Comment by RichiCoder1** [comment]
I figured it was likely related to that 😅. Would it be possible to keep the name to prevent confusion, but still keep the callback style? E.g. `allowedOriginsIterator.dynamic(it =>`? Doesn't have the implication like `forEach` that it might run in a loop, but still simplifies things a bit (imho).

**Comment by ansgarm** [comment]
Hi @RichiCoder1,
yeah, I thought about that, too. However, as we're constrained by JSII (which translates our TypeScript bindings to the other languages we support), we can't directly use callbacks, but rather need to pass what would for example be the equivalent of an anonymous inner class in Java.
So it would need to look like this:
```ts
new S3Bucket(this, "my-bucket", {
  corsRule: allowedOriginsIterator.forEach(
    { callback: it =>
      {
        allowedMethods: [it.getStringProperty("method")],
        allowedOrigins: [it.getStringProperty("origin")],
        maxAgeSeconds: 42,
        someOtherAttribute: index++
      },
    }
  ),
});
```

I'm unsure whether this would still simplify things compared to `.dynamic({ ... })` or even `.forEach({ ... })`.

**Comment by RichiCoder1** [comment]
@ansgarm that's fair, JSII strikes again. `dynamic` seems fine then, considering constraints
