### ISSUE TITLE
No `DependsOn` generated in modules with Go

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-cdk#1805]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Go

### Affected Resource(s)

Any module.

### Expected Behavior

Each module should have a DependsOn property in the config.

### Actual Behavior

No such property exists.

### Steps to Reproduce

Import any module and try to add dependencies.

**Comment by jsteinich** [comment]
#1786 is attempting to solve this.

**Comment by nikolay** [comment]
@aadhikary It is true so I'm closing this.

**Comment by aadhikary** [comment]
@nikolay could you reopen the issue please as this should be fixed on typescript and go :-)

**Comment by jsteinich** [comment]
@nikolay @aadhikary modules do have a `dependsOn` property outside of the config. This should allow for setting the depends on information.

**Comment by aadhikary** [comment]
@jsteinich thanks for the info. Could you please provide an example.  I could not find a method similar to other terraform resources on CDK. The only dependsOn that i could see was a class variable which i could assign after the class is constructed. But that also takes string not terraform resource. Could you share an example please for terraform CDK on modules depending on another resource?

**Comment by jsteinich** [comment]
> @jsteinich thanks for the info. Could you please provide an example. I could not find a method similar to other terraform resources on CDK. The only dependsOn that i could see was a class variable which i could assign after the class is constructed. But that also takes string not terraform resource. Could you share an example please for terraform CDK on modules depending on another resource?

Yep, that's the way to set currently. You can do:
```typescript
(module.dependsOn ??= []).push(resource.fqn)
```
