### ISSUE TITLE
Pre-built provider for databricks

### ISSUE THREAD

**Issue by shazi7804** [hashicorp/terraform-cdk#1808]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add pre-built provider for [databricks](https://databricks.com/)

### References

- https://registry.terraform.io/providers/databrickslabs/databricks/latest

**Comment by DanielMSchmidt** [comment]
Created a PR: https://github.com/hashicorp/cdktf-repository-manager/pull/70

**Comment by DanielMSchmidt** [comment]
It's created now: https://github.com/hashicorp/cdktf-provider-databricks
