### ISSUE TITLE
MqBroker and MqConfiguration Issue

### ISSUE THREAD

**Issue by rodentskie** [hashicorp/terraform-cdk#1823]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

I used TypeScript
```
❯ cdktf --version
0.10.4
```
### Affected Resource(s)

These two
- MqBroker
- MqConfiguration

### Debug Output

https://gist.github.com/rodentskie/f49c55791556257173233ff77d499f5d

### Actual Behavior
The `TerraformOutput` shows the correct ID of the `MqConfiguration`, but when passed into the configuration property of `MqBroker`

```
configuration: {
   id: mqConfigurationTwo.id,
   revision: mqConfigurationTwo.latestRevision,
},

It shows the error log on the gist.
```

ID not found on `MqBroker`.

### Steps to Reproduce

The typescript file is on the gist, please use it and check the `main.ts` in the comment.

### Important Factoids

None

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/mq_broker

**Comment by rodentskie** [comment]
Today I tried ang checked the files in `cdktf.out` directory and found this in the resource

```
"aws_mq_broker": {
      "mq_broker_two": {
        "//": {
          "metadata": {
            "path": "onewallet-amqp-development/mq_broker_two",
            "uniqueId": "mq_broker_two"
          }
        },
        "auto_minor_version_upgrade": "${var.auto_minor_version_upgrade}",
        "broker_name": "onewallet-development-activemq-two",
        "configuration": {
          "revision": "${aws_mq_configuration.mq_configuration_broker_two.latest_revision}"
        },
        "deployment_mode": "${var.deployment_mode}",
        "engine_type": "ActiveMQ",
        "engine_version": "${var.engine_version}",
        "host_instance_type": "${var.host_instance_yype}",
        "logs": {
          "audit": "true",
          "general": true
        },
        "publicly_accessible": true,
        "security_groups": [
          "${aws_security_group.security_group.id}"
        ],
        "storage_type": "efs",
        "user": [
          {
            "console_access": true,
            "password": "${var.password}",
            "username": "${var.username}"
          }
        ]
      }
    },
```

The `configuration` property don't have the `id` just the revision.

**Comment by rodentskie** [comment]
Workaround for now is

Run `cdktf synth`
cd `cdktf.out/dir-to-stack`
Manually add the id like so: 

```
"configuration": {
  "revision": "${aws_mq_configuration.mq_configuration_broker_two.latest_revision}",
  "id": "${aws_mq_configuration.mq_configuration_broker_two.id}"
},
```
Then `terraform apply`

**Comment by jsteinich** [comment]
@rodentskie I just did a test using the provided gist (thanks much) against cdktf 0.11.0 and did not encounter the issue. There was a change related to the `id` property in 0.11.0, so I expect updating will also fix the issue for you.

**Comment by rodentskie** [comment]
Thank you @jsteinich , yep will try upgrading the version.
