### ISSUE TITLE
cdk.tf.json contains old resource ids in the depends_on list, when the logical id is overwriten

### ISSUE THREAD

**Issue by meioli** [hashicorp/terraform-cdk#1827]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

We use cdktf as maven dependencies:

- <cdktf.version>0.11.0-pre.49</cdktf.version>
- <cdktf-provider-google.version>0.8.44</cdktf-provider-google.version>
- <cdktf-provider-google-beta.version>0.0.44</cdktf-provider-google-beta.version>

### Affected Resource(s)

All

### Expected Behavior

When cdk.tf.json is generated, the generated identifiers are correctly replaced on resource level as well as in the depends_on lists of the resources that are dependent on the resources with overwritten logical identfier.

### Actual Behavior

When overwriting the logical ids with with `table.overrideLogicalId(t.getCustomUniqueIdentifier());` the identifiers on resource level in cdk.tf.json are correctly overwritten. But when resources with overwritten logical identifier are used in `.dependsOn(resourceWithOverwrittenId)` in the depends_on list still the cdktf generated identifiers are listed. This leads to a processing error `Error: Reference to undeclared resource`.

### Steps to Reproduce

Overwrite the identifier of a resource and use this resource in as dependency of another resource.

- #0000

**Comment by jsteinich** [comment]
@meioli can you please try again using cdktf version `0.11.0`? There were some fixes with logical id override made during the development of 0.11.0 and I'm not certain they had all been completed by that pre-release version.

I just tried a simple reproduce case using `0.11.0` and the dependency correctly matched. If you are still having issues after upgrading, please provide some snippets of the issue.

**Comment by meioli** [comment]
@jsteinich it indeed is fixed in `0.11.0`! Sorry that I didn't checked this my self. I was to much relying on the version update warning in intelliJ so I thought I was on the latest version.

Thanks a lot! I close the issue.
