### ISSUE TITLE
Cdktf and terratest

### ISSUE THREAD

**Issue by edge7** [hashicorp/terraform-cdk#1834]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jsteinich** [comment]
I believe this should work. Take a look at https://discuss.hashicorp.com/t/automated-tests-for-terraform-cdk-projects/25182 for some more details.

**Comment by skorfmann** [comment]
@edge7 were you able to get this working?

**Comment by edge7** [comment]
Yes I did. Just point terratest to the output of cdktf (after synth)
