### ISSUE TITLE
One stack failure when deploying multiple stack in parallel causes other stacks state to remain locked

### ISSUE THREAD

**Issue by aadhikary** [hashicorp/terraform-cdk#1836]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

$ cdktf --version
0.10.4

$ terraform --version
Terraform v1.2.1
on linux_amd64

Language: typescript

### Affected Resource(s)

Stack state files that did not fail but were running in parallel

### Expected Behavior
The stacks that did not fail should continue and complete. Once this is complete the error message for the stack that failed should be printed at the end. Also no other new stacks then should run. At the end of a failure the state file should not be locked for any of the stacks.

### Actual Behavior

Remote state file gets locked for the stacks that were running in parallel but did not fail

### Steps to Reproduce

1. Setup cdktf project with multiple stacks which can run in parallel
2. Make sure one of the stack fails while other stacks are not complete
3. Run the stacks in parallel
4. Look at the state file of the stacks that did not fail

**Comment by skorfmann** [comment]
Could you elaborate on the problem and its context you're experiencing - I'm not sure what you're describing here.

**Comment by aadhikary** [comment]
As example lets say we have 3 stacks which can run in parallel and the backend for the state file is on Azure storage account blob storage (could probably be any backend but I am using Azure backend):
stack1, stack2, stack3

If we run all these stacks in parallel:
$cdktf deploy 'stack*' --auto-approve

### Timeline: 
stack1 (deploying)---------------------------------------------------------------> (passed)
stack2 (deploying)---------------------------------------------------------------------------------> (failed)
stack3 (deploying)---------------------------------------------------------------------------------> **(in progress)**

**Note stack3 stops in the middle if the stack2 fails even if stack3 would have finished successfully** 
### Condition of state file:
stack1 ----> No locking on state file (In azure blob terms Available)
stack2 ----> No locking on state file (In azure blob terms Available)
stack3 ----> **State file locked** (In azure blob terms in Lease)

**Comment by aadhikary** [comment]
> That's weird, I explicitly tested this scenario and designed it to match what you said thinking How does stack3 behave? Is there no output anymore? Does the entire process end?

Yes that is what seems to be happening. The process ends at stack2 failure (with error message from stack2) which then is not locked anymore but the stack3 state file is locked.

**Comment by DanielMSchmidt** [comment]
I could recreate the issue: https://github.com/hashicorp/terraform-cdk/pull/1881

**Comment by tomw1994991** [comment]
We are also seeing this issue and it is a big blocker when using a lot of stacks. It would be somewhat mitigated if we were able to pass through -lock=false to terraform from cdktf to clean up afterwards.
