### ISSUE TITLE
Upgrading the cdktf v0.11.0 causes lot of terraform process to spin off when synthesizing or deploying

### ISSUE THREAD

**Issue by aadhikary** [hashicorp/terraform-cdk#1837]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

$ cdktf --version
0.11.0

$ terraform --version
Terraform v1.2.1
on linux_amd64

Language: typescript

### Expected Behavior

Should work as normal and should not spin off lot of terraform processes eventually cauing system to come to a hault.

### Actual Behavior
After upgrading to v0.11.0 and running cdktf deploy it started spinning off quite few terraform processes when then led for the system to come to complete hault.

### Steps to Reproduce

1. Upgrade to v0.11.0 for cdktf
2. Run cdktf deploy stack1 --auto-approve

**Comment by DanielMSchmidt** [comment]
Hey there,

I tried to reproduce this using the [serverless exampel](https://github.com/hashicorp/cdktf-integration-serverless-example) but for me there are no unexpected processes spawning. I'm running `ps aux | grep 'terraform'` and getting this:


```
danielschmidt     6827   0.0  1.2 35467292 418800   ??  S     4:02PM   1:27.81 /Users/danielschmidt/.vscode/extensions/hashicorp.terraform-2.22.0-darwin-x64/bin/terraform-ls serve
danielschmidt    25369   0.0  0.0 34253900    932 s004  R+   10:35AM   0:00.00 grep --color=auto terraform
danielschmidt    25247   0.0  0.3 35627064  90328 s003  S+   10:35AM   0:00.55 .terraform/providers/registry.terraform.io/hashicorp/aws/4.8.0/darwin_amd64/terraform-provider-aws_v4.8.0_x5
danielschmidt    25221   0.0  0.2 34928324  75908 s003  S+   10:35AM   0:01.45 terraform apply -auto-approve -input=false plan 
```

The first one is the language server in my VSCode, the next one is the grep, the one after is the aws provider and the last one is terraform itself. (same during apply phase).

Could you share a small reproduction case?

**Comment by aadhikary** [comment]
Hi @DanielMSchmidt,

Thanks for the response. I tried to reproduce it today by upgrading it but cannot seem to reproduce the bug. One difference in running today to last time was that I was using Vnet module which I am not anymore https://github.com/Azure/terraform-azurerm-vnet.

**Comment by DanielMSchmidt** [comment]
Okay, I'll close this issue then for now, if you experience it again let me know and I'll reopen the issue 👍
