### ISSUE TITLE
Multiple stacks use same remote backend configuration

### ISSUE THREAD

**Issue by thatarchguy** [hashicorp/terraform-cdk#1847]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using terraform, I can setup workspaces for each environment (production, qa, development) and they share the same backend configuration:
```hcl
terraform {
  backend "s3" {
    bucket         = "my_state_bucket"
    key            = "terraform/aws/my_project"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "terraform-locks"
  }
}
```

With cdk it seems like I have to make a new backend reference for each stack? 
```python

[...]
stack = MyStack(app, "development", StackConfig(account="0987654321"))
S3Backend(
    stack,
    bucket="my_state_bucket",
    dynamodb_table="terraform-locks",
    key="terraform/aws/my_project",
    region="us-east-2",
    encrypt=True,
)
stack = MyStack(app, "production",
                StackConfig(account="1234567890"))
S3Backend(
    stack,
    bucket="my_state_bucket",
    dynamodb_table="terraform-locks",
    key="terraform/aws/my_project",
    region="us-east-2",
    encrypt=True,
)

[...]
```

Is this correct? This is what the examples are suggesting. We should only need to specify the backend once.

**Comment by DanielMSchmidt** [comment]
This it not correct, you can make the backend configuration a part of your stack definition. We refer to the pattern you are currently using as configuration from the outside versus configuration from the inside. 

You can do it like this:

```py
class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)
        S3Backend(
          self,
          bucket="my_state_bucket",
          dynamodb_table="terraform-locks",
          key="terraform/aws/my_project",
          region="us-east-2",
          encrypt=True,
      )
```

**Comment by thatarchguy** [comment]
Ah alright! Sorry for the misunderstanding then. Thank you very much.
