### ISSUE TITLE
depends_on usage in Python version

### ISSUE THREAD

**Issue by edge7** [hashicorp/terraform-cdk#1866]
Hi,

**CDKTF version: 0.11.2**

I have got the need to specify that a resource depends_on on other. This is what I am trying to do:
```
created_schema = Schema(self,
                                    id_=schema["name"],
                                    database=schema["database"],
                                    name=schema["name"])

snowflake_table = SnowflakeTableModule(self,
                                               id_=f"{schema}_{table['name']}",
                                               columns=table_columns,
                                               database_name=database,
                                               schema_name=schema,
                                               table_name=table["name"],
                                               change_tracking=table["change_tracking"],
                                               data_retention_days=table["data_retention_days"])

 snowflake_table.add_override("depends_on", [Token.as_any(created_schema.fqn)])
```
It does not create errors during synth and indeed I see the following in the generated json:
```
"depends_on": [
        "${snowflake_schema.snowflake_schemas_DEMO2_BAZAARVOICE_STANDARD_CLIENT_FEED_07181D8A}"
      ],
```
But then, when trying to run terraform plan, I get:
```
│ Error: Invalid expression
│ 
│   on cdk.tf.json line 37, in module.snowflake_schemas_test_table_1_044C1F2F.depends_on:
│   37:         "${snowflake_schema.snowflake_schemas_test_07181D8A}"
│ 
│ A single static variable reference is required: only attribute access and
│ indexing with constant keys. No calculations, function calls, template
│ expressions, etc are allowed here.
```

Anyone knows how to fix this?

**Comment by jsteinich** [comment]
You should be able to just specify `depends_on=[created_schema]` when creating the table.

**Comment by hragarwal** [comment]
@jsteinich this is custom module but weirdly it doesn't have `depends_on` in the constructor parameters when module bindings are generated, anything specific needs to be done to add it in constructor while generation or creation of module ?

**Comment by jsteinich** [comment]
> this is custom module but weirdly it doesn't have `depends_on` in the constructor parameters when module bindings are generated

That would be a bug. We'll work on getting that added.

You can construct the equivalent of fqn manually:
`snowflake_table.add_override("depends_on", [created_schema.terraform_resource_type + "." + created_schema.friendly_unique_id])`

**Comment by hragarwal** [comment]
Tried this already, no errors but the generated plan still doesn't have this dependency 

`snowflake_table.add_override("depends_on", [depends_on.terraform_resource_type
                                                    + "." + depends_on.friendly_unique_id])`
cdk.tf.json contains
`"depends_on": [
        "snowflake_schema.snowflake_schemas_DEMO2"
      ]`

but still generated terraform plan doesn't have depends_on

`+ resource "snowflake_schema" "snowflake_schemas_DEMO2" {
      + data_retention_days = 1
      + database            = "LAND_NONLIVE"
      + id                  = (known after apply)
      + is_managed          = false
      + is_transient        = false
      + name                = "DEMO2"
    }`
    
`+ resource "snowflake_table" "table" {
      + change_tracking     = false
      + cluster_by          = []
      + data_retention_days = 1
      + database            = "LAND_NONLIVE"
      + id                  = (known after apply)
      + name                = "TABLE_2"
      + owner               = (known after apply)
      + schema              = "DEMO2"

      + column {
          + comment  = "test"
          + name     = "ID"
          + nullable = false
          + type     = "NUMBER(38,0)"
        }
    }`

**Comment by hragarwal** [comment]
Yes, this works, thanks!
