### ISSUE TITLE
Diff / Deploy / Destroy Columns Should Grow with Content

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#187]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

The resource type and name should always be readable. 

### Actual Behavior

![Screenshot 2020-07-16 at 16 14 17](https://user-images.githubusercontent.com/136789/87682070-b5050300-c77f-11ea-8c0f-154a2e9c90f2.png)

### Steps to Reproduce

Deploy the Google Example

### References

Somewhat related to #115

**Comment by DanielMSchmidt** [comment]
Closing this in favour of #1097 that now tracks the issue
