### ISSUE TITLE
Ensure Correct Dependencies between Constructs for Required Attributes

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#188]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

All 

### Example

```ts
    const network = new ComputeNetwork(this, 'Network', {
      name: 'cdktf-network'
    })

    new ComputeInstance(this, 'ComputeInstance', {
      name: 'cdktf-instance',
      machineType: 'f1-micro',
      bootDisk: [{
        initializeParams: [{
          image: 'debian-cloud/debian-9'
        }]
      }],
      networkInterface: [{
        network: network.name
      }],
      tags: ["web", "dev"]
    })
```

### Expected Behavior

Since `network.name` is referenced in the `ComputeInstance` to define the network interface, there should be a dependency between those two resources. Both resources should be created sequentially.

### Actual Behavior

Since `network.name` contains a user provided value, this value will be returned immediately. 

Here the implementation of the `name` accessor:
![Screenshot 2020-07-16 at 16 22 38](https://user-images.githubusercontent.com/136789/87682820-98b59600-c780-11ea-9f95-04af69e042b6.png)

This means, there's no relationship visible to Terraform. Hence, Terraform will try to create / destroy both resources in parallel.

![Screenshot 2020-07-16 at 16 18 21](https://user-images.githubusercontent.com/136789/87683095-ee8a3e00-c780-11ea-9166-a0cb622454f0.png)

### Steps to Reproduce

Take example an run it

**Comment by jsteinich** [comment]
One option might be to have the getters always return the Token reference and only use real values in `toTerraform`. There is already ambiguity in what gets returned, so users won't be able to consistently take action based on real values anyways.

**Comment by skorfmann** [comment]
> One option might be to have the getters always return the Token reference and only use real values in `toTerraform`. There is already ambiguity in what gets returned, so users won't be able to consistently take action based on real values anyways.

Yes, I agree. The current idea how to solve this is exactly this.

- Return tokens for all attribute readers regardless of it being `optional`, `computed` or `required`
- Use the attribute readers which contain the actual value `_abc` in `toTerraform`

What I'm not sure about is, if the currently private value attribute readers (`_abc`) should become public then.

**Comment by jsteinich** [comment]
> What I'm not sure about is, if the currently private value attribute readers (`_abc`) should become public then.

I think having them public would just cause more confusion since they would only have value when manually set.

It would be cool if accessing any value and running logic / functions in the code directly on it was supported, but that seems fundamentally different than synthesizing to Terraform.
