### ISSUE TITLE
Convert: init-from-terraform-project fails with unknown provider

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#1883]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Debug Output

When I convert a project with unknown provider versions we seem to use `"  *"` as a default

```
There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.
╷
│ Error: Invalid version constraint
│
│   on main.tf.json line 1, in terraform.required_providers.random:
│    1: {"terraform":{"required_providers":{"random":{"version":" *","source":"random"},"tls":{"version":" *","source":"tls"},"aws":{"version":" ~> 4.15.1","source":"hashicorp/aws"}}},"provider":{"random":{},"tls":{},"aws":{}}}
│
│ This string does not use correct version constraint syntax.
╵
```
### References

- #0000

**Comment by jpattersonz** [comment]
I ran into this also.

Many of the providers which I directly depended on via `required_providers`, in turn depended on `hashicorp/random`.  So I had an indirect dependency on `hashicorp/random`.

I was able to unblock myself by explicitly depending on a specific version of `hashicorp/random` by adding it to my `required_providers`.  To determine which version I should use, I looked in `./terraform/providers/registry.terraform.io/hashicorp/random` to see which version was installed.
