### ISSUE TITLE
Wrong release as the "current" version with NPM is 0.0.0

### ISSUE THREAD

**Issue by nikolay** [hashicorp/terraform-cdk#1889]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
Sorry, that was my bad, it happened when I tried to improve our CI pipeline. I retagged current as 0.11.2 for all our packages and deprecated the 0.0.0 versions
