### ISSUE TITLE
TagsAddingAspect example produces Self-referential block

### ISSUE THREAD

**Issue by danielBreitlauch** [hashicorp/terraform-cdk#1892]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.11.2
terraform: 1.2.3
typescript

### Affected Resource(s)

aws_ssm_parameter but any resource with non empty tags.

### Debug Output

The Gist contains the generated terraform json and the error.
[Gist](https://gist.github.com/danielBreitlauch/0c539ceff92721c7a65e1ffb01542459)

### Expected Behavior

Tags should have been read from the resource, merged and readied to the resource.

### Actual Behavior

Terraform considers this a self-referential block and aborts.

### Steps to Reproduce

1. Take the example from [https://www.terraform.io/cdktf/concepts/aspects](https://www.terraform.io/cdktf/concepts/aspects) 
2. add a ssm parameter

**Comment by danielBreitlauch** [comment]
Makes sense. Thx.
And keep up the good work. Cdktf is awesome.

**Comment by DanielMSchmidt** [comment]
I think since we are not dealing with tokens anymore you should be able to do `node.tags = { ...this.tagsToAdd, ...node.tagsInput,}`

**Comment by danielBreitlauch** [comment]
This overwrites the existing tags added elsewhere. Like { test: "ing"} above.

**Comment by ansgarm** [comment]
Hi @galaabattur, have you seen the [commit](https://github.com/hashicorp/terraform-cdk/commit/9ea85fbe2524660c44918b4ae3b6ecef46330a0a) from @DanielMSchmidt (back-linked above)?
It updates the docs to solve that issue by using the `tagsInput` value for the current tags:
```ts
// We need to take the input value to not create a circular reference
const currentTags = node.tagsInput || {};
node.tags = { ...this.tagsToAdd, ...currentTags };
```
Does that solve it for you as well?

**Comment by galaabattur** [comment]
Hi @ansgarm  thank you for the response. I have tried it and have following question. In this case, where would `tagsInput` be defined, is it in `TaggableConstruct` type? otherwise typescript will complain that cannot find the property in the `TaggableConstruct` type, or is it in the cdktf types?
