### ISSUE TITLE
[GCP - GCS Backend] Resolve project name when dynamically generating GSC backend prefix

### ISSUE THREAD

**Issue by kjlis** [hashicorp/terraform-cdk#1903]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
  "dependencies": {
    "@cdktf/provider-google-beta": "^0.1.41",
    "cdktf": "^0.11.2",
    "constructs": "^10.1.25"
  },
```

### Affected Resource(s)

- `DataGoogleProject`
- `GcsBackend`

### Debug Output

https://gist.github.com/kjlis/35ebbb60148c06af193818c57b994f79#file-cdktf-json

### Expected Behavior
GCS backent should [dynamically resolve](https://gist.github.com/kjlis/35ebbb60148c06af193818c57b994f79#file-stack-ts) project name and pass it to GCS backend. The GCS backend prefix should be: `some-prefix/some-project`.

### Actual Behavior

It uses `${data.google_project.SomeProject.name}` string as the project name, so the actual bucket prefix is: `some-prefix/${data.google_project.SomeProject.name}`

### Steps to Reproduce

1. Create dev project.
2. Pass project ID and synthesize example stack (you might need to add at least one resource, like Storage Bucket).
3. Deploy to your dev project.

### Important Factoids

N/A

### References

N/A

**Comment by DanielMSchmidt** [comment]
I looked into it: [Backends can not take references (named values) in their configuration](https://www.terraform.io/language/settings/backends/configuration#using-a-backend-block), Terraform does not support this.

**Comment by DanielMSchmidt** [comment]
Closing this as there is nothing we can do about this from the CDK side :)
