### ISSUE TITLE
"cdktf synth STACK" does not honour STACK

### ISSUE THREAD

**Issue by jarpy** [hashicorp/terraform-cdk#1906]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.11.2 with Python.

### Affected Resource(s)

N/A

### Debug Output

https://gist.github.com/jarpy/0bc5173c00814820b667f9e097a7e4ff

### Expected Behavior

```
$ cdktf synth

Generated Terraform code for the stacks: stack-one, stack-two

$ cdktf synth stack-one

Generated Terraform code for the stacks: stack-one

$ cdktf synth stack-two

Generated Terraform code for the stacks: stack-two
```

### Actual Behavior

```
$ cdktf synth

Generated Terraform code for the stacks: stack-one, stack-two

$ cdktf synth stack-one

Generated Terraform code for the stacks: stack-one, stack-two

$ cdktf synth stack-two

Generated Terraform code for the stacks: stack-one, stack-two
```

### Steps to Reproduce

```shell
cdktf init
```

```python
from constructs import Construct
from cdktf import App, TerraformStack


class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)


app = App()
MyStack(app, "stack-one")
MyStack(app, "stack-two")

app.synth()
```

```shell
cdktf synth stack-one
```

### Important Factoids

The help text for `cdktf synth` reads:

```
Synthesizes Terraform code for the given app in a directory.

Positionals:
  stack  Stack to output when using --json flag  
```

`stack` does not appear to be honoured (and the `--json` flag was removed in v0.10.0).

### References

None.

**Comment by DanielMSchmidt** [comment]
Oh good point, we forgot to remove the stack positional after removing the JSON flag. Synth can not be limited to a single stack.

**Comment by jarpy** [comment]
Ah cool. Thanks. I use my own technique to limit what gets synthed, but I wasn't sure if I needed to, or if that capability it was in the engine, but glitched.

Cheers.

**Comment by DanielMSchmidt** [comment]
What technique are you using?

**Comment by jarpy** [comment]
Nothing fancy. I have three stacks (`dev`, `test`, `prod`). I just set an optional environment variable, and then choose which stacks to synth based on that. My entrypoint looks like:

https://gist.github.com/jarpy/affd883ee535e16d2d9398352c97240e

I've been trying to figure how to get the "stage" by introspection. It would be cool if I could find this somewhere in memory:
```
cdktf plan my-stack-prod
                    ^^^^
```

Then, I wouldn't need the environment variable, which is pretty ugly. Now you can see how I ended up raising this issue! :) I wanted to `cdktf synth THING`, _and_ be able to introspect what `THING` is at runtime.

**Comment by ansgarm** [comment]
Hi @jarpy 👋
I saw some flag mentioning API calls, are you "manually" creating resources via api calls while synthesizing (aka while running your Python program)? What exactly are you using those API calls for?

**Comment by jarpy** [comment]
Hi @ansgarm :)

> are you "manually" creating resources via api calls while synthesizing

No way! :D I would never _create_ anything with an API call in `synth`, but I do consume all sorts of things so that I can programmatically declare the things I _do_ want to create as Terraform resources. This, for me, is the beauty of CDKTF and why I find it truly delightful. I can now declare resources programmatically, by consuming, inspecting and transforming data structures that can be any shape and come from anywhere.

As a concrete example, I can inspect the GitHub API for information about repositories, (my company has thousands, and they are not provisioned by Terraform), and then dynamically declare CI pipelines, Vault resources etc. based on the incoming data structures.

I'm anticipating traditional HCL users saying, at this point, "that's what `data` sources" are for. In some cases, they are certainly useful, but _not_ depending on them (and not spending months trying to get changes merged into them) is incredibly freeing. CDKTF unshackles us, and allows us to innovate, with Turing complete, well tested, and well documented software, right in our "configuration". It's been wonderful so far, and I like to offer my sincere thanks to the CDKTF team.

Please feel free to close this issue, since it sounds like `cdktf synth` is working as designed, and I can achieve my goals without any change to it.
