### ISSUE TITLE
Documentation improvement: Terraform Element usage

### ISSUE THREAD

**Issue by danielBreitlauch** [hashicorp/terraform-cdk#1910]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to know more best practices concerning the TerrafromElement.
Is there a difference to Null Provider Resources?

It would be nice to have more documentation about this entity.
The Concepts page would be a perfect place.
https://www.terraform.io/cdktf/concepts/constructs

**Comment by jsteinich** [comment]
`TerraformElement` is really just meant to serve as an internal base class for all other Terraform objects (Resources, Data Sources, etc.). You might be able to use it to group together related resources; however, the recommendation there is to use `Construct` as your base class instead.

The `Null` resource is more a special Terraform concept for performing arbitrary behavior as part of Terraform operations.

It is possible to extend some of these to add your own behavior. For example a [docker asset](https://github.com/cdktf-plus/cdktf-plus/blob/main/packages/%40cdktf-plus/core/lib/docker-asset/docker-asset.ts)
