### ISSUE TITLE
Add -no-color option

### ISSUE THREAD

**Issue by nekhebit** [hashicorp/terraform-cdk#1916]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Please add the option `-no-color` to cdk. 

A lot of users run cdk in a context where the output is not rendered by the system, but instead used for further computation or redirected to other sinks, that cannot interpret terminal formatting. The additional formatting strings makes log reading very difficult. 
Thank you very much for your work and for your attention. :+1: 

### References
https://www.terraform.io/cli/commands/apply#no-color

**Comment by ansgarm** [comment]
Hi @nekhebit!

Sounds like a good flag to add. In the meantime you could use the environment variable `FORCE_COLOR=0` which should disable colors ([supported](https://github.com/chalk/chalk#supportscolor) by the underlying lib we use).

Independently from adding support for the `--no-color` flag, we should at least document `FORCE_COLOR` in the [environment variables docs](https://www.terraform.io/cdktf/create-and-deploy/environment-variables).

**Comment by nekhebit** [comment]
Hi @ansgarm! :)
Thanks for the fast reply! 

I did not know about the flag, I will give it a try. Is there a way to diminish the verbosity of the output? For example, to get only the error back, or to get the responses as a json so that it is easier to filter?

**Comment by ansgarm** [comment]
Hi @nekhebit,

for which commands do you want such output? And could you explain a bit more about your underlying use case for this?

**Comment by nekhebit** [comment]
The output given by cdk is really verbose. It is good for a human to go through it and understand what is going on. It is not so good if you want to output it to a existing logging structure. 
I would like to either receive a confirmation of success  or the error that was generated, without the terraform formatted string/redundant information. 

A quick and **dirty** solution would be to parse the output and search for the `Error:` string and get the content until the next new line, but everything in me is screaming against it. Maybe there is already an option to get this information without having to resort to this terrible solution. :grin:  

About the `FORCE_COLOR=0`: Im still getting color. :sob:  Less than before, but still some color:

From pod's log:
![error_color](https://user-images.githubusercontent.com/82508366/178469950-91012e8a-e139-44b8-a322-53884cadbec0.png)

From console with `FORCE_COLOR=0`
<img width="1106" alt="force_color_zero" src="https://user-images.githubusercontent.com/82508366/178469706-dc889d49-867f-4c33-8ee4-79d55da8a7dc.png">

From console with `FORCE_COLOR=1`
<img width="937" alt="force_color_one" src="https://user-images.githubusercontent.com/82508366/178469760-f0dd93ac-dc71-4464-9ea1-e4dad02ac8b0.png">

**Comment by ansgarm** [comment]
Ah, thank you for explaining! Yeah, I'd be cautious about doing a string search for `Error:` as well. Unfortunately there is no better solution at the moment while still using the CDKTF CLI. That said, you could certainly invoke the Terraform CLI directly in the `cdktf.out/stacks/<your-stack>` directory and pass the [`-json` option](https://www.terraform.io/cli/commands/apply#json) to `terraform apply`. Depending on the system you are trying to build, this might be worth the effort.

Regarding the color: While `FORCE_COLOR` disables all the color the CDKTF CLI uses, it still invokes the Terraform CLI under the hood (and redirects its output). Until we support a proper `-no-color` option you should be able to disable the colored output for the Terraform CLI by additionally setting `TF_CLI_ARGS="-no-color"`.
