### ISSUE TITLE
Add multi-language code examples to docs 

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#1929]
Most of our docs only include TypeScript examples. We should add multi-language code blocks to examples in our documentation to highlight that there are five supported languages to use with CDKTF.

Scanning the codebase shows that there are currently 26 code blocks in our docs, so this work could be handled incrementally. 

Reference: [Guidance from the Education team on using CodeTabs to add multiple languages to code examples](https://docs.google.com/document/d/1fmpSviM2pQUWm6y3QnVQ3QAdq5i7RjeWopzNXbMH2Io/edit#heading=h.sjgr1uoclelk)

**Comment by pchaganti** [comment]
+1. Please provide examples in Python.
