### ISSUE TITLE
How to deal with Terraform module dependencies in construct libraries

### ISSUE THREAD

**Issue by danielBreitlauch** [hashicorp/terraform-cdk#1934]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Sorry to ask this way.
I know how to include/generate code from Terraform module dependencies via cdktf.json terraformModules.
Now I want to put my TS code that uses these dependencies in a library.
[https://www.terraform.io/cdktf/concepts/modules#create-modules](https://www.terraform.io/cdktf/concepts/modules#create-modules) advises to use projen and stay in TS.
How do I manage the terraform module dependency there?
Any advice how to do this?

E.g. Terraform modules from there: https://github.com/terraform-aws-modules

**Comment by xiehan** [comment]
Hi there:

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) where there are more people ready to help.

Thanks!
