### ISSUE TITLE
cdktf stuck on nodejs version

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1943]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
Typescript - 0.11.2

### Affected Resource(s)
When upgrading my nodejs version to a new version my cdktf project now fails and tells me to install the original version I had reverting to original version does make indeed make it work again. I am using asdf to manage my version of nodejs

### Debug Output
```❯ cdktf deploy anedot-eks --log-level DEBUG

⠧  Synthesizing
[2022-07-20T21:55:06.853] [ERROR] default - No preset version installed for command ts-node
Please install a version by running one of the following:

asdf install nodejs 18.6.0

or add one of the following versions in your config file at /Users/jinahn/.tool-versions

cdktf encountered an error while synthesizing

Synth command: npm run --silent compile && ts-node src/main.js
Error:         non-zero exit code 126

Command output on stderr:

    No preset version installed for command ts-node
    Please install a version by running one of the following:

    asdf install nodejs 18.6.0

    or add one of the following versions in your config file at /Users/jinahn/.tool-versions
    nodejs 16.2.0
```

### Expected Behavior
Updating nodejs version should not create a failure for cdktf

### Actual Behavior
Updating nodejs version breaks cdktf deploy

**Comment by ansgarm** [comment]
Hi @jin-ahn,

The error message `No preset version installed for command ts-node` sounds like it's coming from asdf. We had a similar issue reported in the past (but [for the Terraform CLI](https://github.com/hashicorp/terraform-cdk/issues/1559)) although this one seems to be different.

What does your `app` command in the `cdktf.json` config look like? If it starts with `npx ts-node ...` maybe there is something missing in your newer NodeJS version that was manually globally installed previously?

I'm not familiar with how asdf works unfortunately, so I can only suspect what is going on here.

**Comment by jin-ahn** [comment]
I had a version of node installed through `n` that I think cdktf would use. I remvoed it and reinstalled nodejs and it works now. Thank you @ansgarm
