### ISSUE TITLE
Support C#

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow writing Terraform CDK code in C#

- Update jsii config to add in C#
- Add example C# solution
- Add C# project template
- Add tests

### References

Similar to [Python Work](https://github.com/hashicorp/terraform-cdk/pull/51)

**Comment by skorfmann** [comment]
There's already progress on this by @pmRz00

**Comment by skorfmann** [comment]
This was done with #477
