### ISSUE TITLE
Python package requires version>=3.7, not >=3.6

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#1979]
Wanted to report that the python package `cdktf_cdktf_provider_aws` requires a minimum Python version of 3.7 due to an error:
```
SyntaxError: more than 255 arguments
```
(I don't have the original message anymore, but it should be easily replicated)

Upgrading to 3.7 negates this error since this python release removes the limit of 256 function arguments. I figured I should report this since PyPi and the package itself reports that `Python >=3.6` should be sufficient when it is no longer the case.

**Comment by DanielMSchmidt** [comment]
I think we can just increase the requirement to Python 3.7 on our side

**Comment by ansgarm** [comment]
Jup, seems that [JSII requires 3.7 now](https://github.com/aws/jsii/blob/5413720a274fbcc9d3b62823197b76589f99329c/packages/jsii-pacmak/lib/targets/python.ts#L2043)
