### ISSUE TITLE
cdktf init fails at npm install (NODE_ENV is not recognized)

### ISSUE THREAD

**Issue by rraziel** [hashicorp/terraform-cdk#198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.0.11 and the `typescript` template

### Debug Output

Figure it's short enough to be here (just few lines):

```
$ cdktf init --template="typescript" --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.tfstate' in the root of your project.

We will now setup the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'tfcdk')
Project Description: (default: 'A simple getting started project for cdktf.')
'NODE_ENV' is not recognized as an internal or external command,
operable program or batch file.

<cut command line options for cdktf displayed>

Error: Command failed: NODE_ENV=development npm install  cdktf@^0.0.11 constructs@^3.0.0
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at installDeps (path\to\npm\node_modules\cdktf-cli\templates\typescript\.hooks.sscaff.js:30:3)
```

### Expected Behavior

No error when doing an init

### Actual Behavior

Init fails at the npm install step

### Steps to Reproduce

```
npm i cdktf -g
cdktf init --template="typescript" --local
```

### Important Factoids

Running on Windows 10, Node 12.16.0

**Comment by rraziel** [comment]
Note: manually doing `npm i cdktf@^0.0.11 constructs@^3.0.0` works fine though (should probably be a --save-dev too?)

**Comment by Satak** [comment]
Same problem here

**Comment by Satak** [comment]
This line I guess: https://github.com/hashicorp/terraform-cdk/blob/8757404fa25b6e405f1a51eac11b96943ccb372e/packages/cdktf-cli/templates/typescript/.hooks.sscaff.js#L30

**Comment by skorfmann** [comment]
Thanks for reporting the bug. I'll check how to fix this for windows. 

Generally, #200 should be implemented to prevent similar platform dependent issues.

**Comment by skorfmann** [comment]
> This line I guess: https://github.com/hashicorp/terraform-cdk/blob/8757404fa25b6e405f1a51eac11b96943ccb372e/packages/cdktf-cli/templates/typescript/.hooks.sscaff.js#L30

Yes 👍 do you know how to achieve the same desired behavior on windows?

**Comment by Satak** [comment]
> Yes 👍 do you know how to achieve the same desired behavior on windows?

Maybe best would be to use https://www.npmjs.com/package/cross-env
and ` execSync(`cross-env NODE_ENV=development npm install ${devDep} ${deps.join(' ')}`, { stdio: 'inherit' }); `

**Comment by Satak** [comment]
Next problem is yarn, which I don't have:

```
'yarn' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! terraform-vm-test@1.0.0 build: `yarn get && tsc`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the terraform-vm-test@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-17T11_25_51_330Z-debug.log
cdktf init [OPTIONS]
```

**Comment by skorfmann** [comment]
> Next problem is yarn, which I don't have, is it mandatory or it should init without yarn?
> 
> 
> 
> Error:
> 
> ```
> 
> 'yarn' is not recognized as an internal or external command,
> 
> operable program or batch file.
> 
> npm ERR! code ELIFECYCLE
> 
> npm ERR! errno 1
> 
> npm ERR! terraform-vm-test@1.0.0 build: `yarn get && tsc`
> 
> npm ERR! Exit status 1
> 
> npm ERR!
> 
> npm ERR! Failed at the terraform-vm-test@1.0.0 build script.
> 
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> 
> 
> npm ERR! A complete log of this run can be found in:
> 
> npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-07-17T11_25_51_330Z-debug.log
> 
> cdktf init [OPTIONS]
> 
> ```

No, yarn isn't mandatory for normal usage. 

It's only required for contributions to this repo, since we are using yarn workspaces

**Comment by rraziel** [comment]
I'm a bit surprised the `NODE_ENV=development` is even there, that would be some kind of workaround for environments where someone would have set `NODE_ENV=production` I think?
Since the default is development, shouldn't this code simply do an `npm install`?

**Comment by skorfmann** [comment]
> I'm a bit surprised the `NODE_ENV=development` is even there, that would be some kind of workaround for environments where someone would have set `NODE_ENV=production` I think?
> 
> Since the default is development, shouldn't this code simply do an `npm install`?

It's set to production, since the cli uses https://github.com/vadimdemedes/ink and that's the recommended setting to suppress internal error messages.

**Comment by rraziel** [comment]
> > I'm a bit surprised the `NODE_ENV=development` is even there, that would be some kind of workaround for environments where someone would have set `NODE_ENV=production` I think?
> > Since the default is development, shouldn't this code simply do an `npm install`?
> 
> It's set to production, since the cli uses https://github.com/vadimdemedes/ink and that's the recommended setting to suppress internal error messages.

I'm not sure I'm following, the code that causes the error is executing `NODE_ENV=development npm install`?
Or are you saying `ink` sets it to `production` so you have to set it back to `development` when running `npm install`?

**Comment by skorfmann** [comment]
Could you give `cdktf-cli@next` a shot? (`npm install -g cdktf-cli@next`) It should fix the init issues on Windows

**Comment by skorfmann** [comment]
> Or are you saying `ink` sets it to `production` so you have to set it back to `development` when running `npm install`?

We do set it to `production` as `ink` is recommending it. And yes, you're right - for the `npm install` we do want to install dev dependencies. These are omitted when `NODE_ENV=production`.

**Comment by rraziel** [comment]
> Could you give `cdktf-cli@next` a shot? (`npm install -g cdktf-cli@next`) It should fix the init issues on Windows

Just tested now, it works.

**Comment by skorfmann** [comment]
Released in [0.0.12](https://github.com/hashicorp/terraform-cdk/releases/tag/v0.0.12)

**Comment by colvint** [comment]
Changing `yarn` to `npm` in `package.json`:

```json
{
  "scripts": {
     ...
    "build": "npm run get && tsc"
    ...
  }
}
```

Resolved the issue for me. I don't have `yarn` installed and don't plan to. So for those in the same boat... You can make that change and then run:

`npm run build`

To generate your `typescript` constructs.

**Comment by skorfmann** [comment]
@colvint that's a good point, thanks for the heads-up. I just created a PR to fix this https://github.com/hashicorp/terraform-cdk/pull/359
