### ISSUE TITLE
Cannot use typescript template literals with terraform interpolation

### ISSUE THREAD

**Issue by paymog** [hashicorp/terraform-cdk#1981]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

From my `package.json`

```
  "dependencies": {
    "@cdktf/provider-aws": "^9.0.3",
    "@cdktf/provider-kubernetes": "^2.0.3",
    "@eryldor/cidr": "^1.0.5",
    "cdktf": "^0.12.0",
    "cdktf-cli": "^0.12.0",
    "constructs": "^10.0.9",
    "ejs": "^3.1.6"
  },
```

### Affected Resource(s)

None in particular. This seems like a problem with typescript + terraform interpolation + cdktf

### Expected Behavior

I expect that I should be able to use typescript template literals

### Actual Behavior

Typescript template literals are not being evaluated (or are incorrectly evaluated). I get the following errors (note that in the terminal output the second `$` in each error is underlined):

```
[2022-07-29T10:22:38.612] [ERROR] default - ╷
│ Error: Invalid character
│
│   on cdk.tf.json line 191, in data.tls_certificate.certificate:
│  191:         "url": "${${aws_eks_cluster.eksCluster}.identity[0].oidc[0].issuer}"
│
│ This character is not used within the language.
goldsky-infra-dev  ╷
                   │ Error: Invalid character
                   │
                   │   on cdk.tf.json line 191, in data.tls_certificate.certificate (certificate):
                   │  191:         "url": "${${aws_eks_cluster.eksCluster (eksCluster)}.identity[0].oidc[0].issuer}"
                   │
                   │ This character is not used within the language.
                   ╵

⠙  Processing
[2022-07-29T10:22:38.628] [ERROR] default - ╷
│ Error: Invalid expression
│
│   on cdk.tf.json line 191, in data.tls_certificate.certificate:
│  191:         "url": "${${aws_eks_cluster.eksCluster}.identity[0].oidc[0].issuer}"
│
│ Expected the start of an expression, but found an invalid expression token.
goldsky-infra-dev  ╷
                   │ Error: Invalid expression
                   │
                   │   on cdk.tf.json line 191, in data.tls_certificate.certificate (certificate):
                   │  191:         "url": "${${aws_eks_cluster.eksCluster (eksCluster)}.identity[0].oidc[0].issuer}"
                   │
                   │ Expected the start of an expression, but found an invalid expression token.
```

### Steps to Reproduce

This is happening during an upgrade from cdktf of 0.8.6 to 0.12.0.

Here's the code which is causing the above issue:

```
    const dataTlsCertificateCertificate = new tls.DataTlsCertificate(
      this,
      "certificate",
      {
        url: `\${${eksCluster.fqn}.identity[0].oidc[0].issuer}`,
      }
    );

```

where `eksCluster` is a resource of type `aws.eks.EksCluster`.

It seems that I cannot use a javascript template literal when using terraform interpolation. Ninja edit: it seems that other uses of template literals are working well though, maybe something else is going on?

I'm using cdktf and the above issue happens when I run:

1. `npx cdktf get`
2. `tsc`
3. `npx cdktf diff`

### Important Factoids

None that I can think of

### References

* https://github.com/hashicorp/terraform-provider-template/issues/50

**Comment by ansgarm** [comment]
Hi @paymog 👋 This seems to be related to https://github.com/hashicorp/terraform-cdk/issues/1641. However, it seems to be a different result as it seems to render `aws_eks_cluster.eksCluster (eksCluster)` which probably originates from somewhere else (some `.toString()` method probably).
The workaround that Daniel Schmidt posted in that other issue should work for you as well.

**Comment by paymog** [comment]
Hi @ansgarm that seems to have solved the issue. I'm running into other similar issues which don't have a clear resolution.

Here's another use of `fqn`(the `availabilityZone` in the Subnet construction and the override below) which also uses `count.index` but I'm not sure how I can correctly use `count.index` with the `Fn.lookup` or `Fn.element` functions, any chance you have some tips you can share?

```
    const publicSubnet = new aws.vpc.Subnet(this, "pub_subnet", {
      availabilityZone: `\${${dataAwsAvailabilityZonesAll.fqn}.names[count.index]}`,
      cidrBlock: "${cidrsubnet(aws_vpc.vpc.cidr_block, 8, count.index)}",
      mapPublicIpOnLaunch: true,
      tags: {
        name: environment + "-public-subnet-${(count.index + 1)}",
        ["kubernetes.io/cluster/" + eksClusterName]: "shared",
        "kubernetes.io/role/elb": "1",
        environment: environment,
        public: "true",
      },
      vpcId: "${aws_vpc.vpc.id}",
    });
    publicSubnet.addOverride(
      "count",
      `\${length(${dataAwsAvailabilityZonesAll.fqn}.names)}`
    );
```

**Comment by jsteinich** [comment]
Many of the reasons for needing to do complex lookups have been eliminated in more recent versions of cdktf. For instance, I believe the cluster identity issuer should be directly available via the generated bindings at this point. `count.index` does still require overrides; however, iterators where just added in 0.12 as a more supported way of doing something similar.

If you do still need an escape, one workaround is to replace `resource.fqn` with `resource.terraformResourceType + "." + resource.friendlyUniqueId`.

**Comment by paymog** [comment]
I just tried using your `fqn` workaround like so:

```
    const publicSubnet = new aws.vpc.Subnet(this, "pub_subnet", {
      availabilityZone: `\${${dataAwsAvailabilityZonesAll.terraformResourceType}.${dataAwsAvailabilityZonesAll.friendlyUniqueId}.names[count.index]}`,
      cidrBlock: "${cidrsubnet(aws_vpc.vpc.cidr_block, 8, count.index)}",
      mapPublicIpOnLaunch: true,
      vpcId: "${aws_vpc.vpc.id}",
    });
    publicSubnet.addOverride(
      "count",
      `\${length(${dataAwsAvailabilityZonesAll.fqn}.names)}`
    );
```

but I get similar issues when running a diff:

```
[2022-08-02T08:35:45.244] [ERROR] default - ╷
│ Error: Reference to undeclared resource
│
│   on cdk.tf.json line 901, in resource.aws_subnet.pub_subnet:
│  901:         "availability_zone": "${aws_availability_zones.all.names[count.index]}",
│
│ A managed resource "aws_availability_zones" "all" has not been declared in
│ the root module.
│
│ Did you mean the data resource data.aws_availability_zones.all?
goldsky-infra-dev  ╷
                   │ Error: Reference to undeclared resource
                   │
                   │   on cdk.tf.json line 901, in resource.aws_subnet.pub_subnet (pub_subnet):
                   │  901:         "availability_zone": "${aws_availability_zones.all (all).names[count.index]}",
                   │
                   │ A managed resource "aws_availability_zones" "all" has not been declared in
                   │ the root module.
                   │
                   │ Did you mean the data resource data.aws_availability_zones.all (all)?
                   ╵

⠏  Processing
[2022-08-02T08:35:45.258] [ERROR] default - ╷
│ Error: Invalid character
│
│   on cdk.tf.json line 903, in resource.aws_subnet.pub_subnet:
│  903:         "count": "${length(${data.aws_availability_zones.all}.names)}",
│
│ This character is not used within the language.
goldsky-infra-dev  ╷
                   │ Error: Invalid character
                   │
                   │   on cdk.tf.json line 903, in resource.aws_subnet.pub_subnet (pub_subnet):
                   │  903:         "count": "${length(${data.aws_availability_zones.all (all)}.names)}",
                   │
                   │ This character is not used within the language.
                   ╵

⠋  Processing
[2022-08-02T08:35:45.274] [ERROR] default - ╷
│ Error: Invalid expression
│
│   on cdk.tf.json line 903, in resource.aws_subnet.pub_subnet:
│  903:         "count": "${length(${data.aws_availability_zones.all}.names)}",
│
│ Expected the start of an expression, but found an invalid expression token.
goldsky-infra-dev  ╷
                   │ Error: Invalid expression
                   │
                   │   on cdk.tf.json line 903, in resource.aws_subnet.pub_subnet (pub_subnet):
                   │  903:         "count": "${length(${data.aws_availability_zones.all (all)}.names)}",
                   │
                   │ Expected the start of an expression, but found an invalid expression token.
```

I'll take a look at iterators. Is there any chance you know how I can use `count.index` when using `Fn.element` since `Fn.element` accepts a `number` as it's second parameter?

**Comment by DanielMSchmidt** [comment]
The original issue should be solved by list accessors & I created #2021 to track work regarding count, so closing this out now

**Comment by paymog** [comment]
@DanielMSchmidt how is the original issue solved by list accessors? 

@ansgarm great catch! Even when I fix the usage of `.fqn` in the `addOverride` I'm left with an issue of how to access the `count.index` for the `availabilityZone`. Do you have any tips on how I can solve this?

**Comment by DanielMSchmidt** [comment]
You can now express  `url: \${${eksCluster.fqn}.identity[0].oidc[0].issuer},` as `url: eksCluster.identity.get(0).oidc.get(0).issuer`

**Comment by paymog** [comment]
Ah, that's great to know! What about in cases like `      availabilityZone: '\${${dataAwsAvailabilityZonesAll.fqn}.names[count.index]}\',` - how does this get translated to the latest version of cdk?

**Comment by DanielMSchmidt** [comment]
I'm not sure, but I created the count iterator issue to  track order iterator support 👍
