### ISSUE TITLE
Terraform CDK Doesnot allow to create GCP APiGateway

### ISSUE THREAD

**Issue by bmakumar** [hashicorp/terraform-cdk#1982]
Hi Team,

   Trying to create an apigateway  using terraform cdk in GCP, but while trying to import the module from @cdktf/provider-google it doesnot show any module, doesnot terraform cdk support creation on apigateway in Google Cloud.
<img width="397" alt="gcptf_apigw_error" src="https://user-images.githubusercontent.com/102816902/182099084-5ebc254a-f2ff-43bc-aa71-7fe050eee349.png">

**Comment by bmakumar** [comment]
I have imported the beta module of cdktf and was able to import apigw but not able to view the module parameters as the webpage loads page not found.

<img width="314" alt="gcptf_apigw_beta_error" src="https://user-images.githubusercontent.com/102816902/182106197-f3c920c1-74b2-4dd5-adce-9a1ac4b0b1d8.png">

<img width="844" alt="gcptf_apigw_beta_module_page_error" src="https://user-images.githubusercontent.com/102816902/182106141-2dce9bbe-900d-4d37-91dd-5c3ed43163e1.png">

**Comment by jsteinich** [comment]
Resources only being in the beta version of the provider is a general property of the Google Terraform provider. I don't know the exact details, but they have no resources incubate in the beta provider for some time before moving to the main provider.

The documentation link being wrong is something that will need to be looked into. In the meantime, here's the correct link: https://registry.terraform.io/providers/hashicorp/google-beta/latest/docs/resources/api_gateway_api

**Comment by bmakumar** [comment]
Hi Jon,

Thanks for the response i started using the shared document , but i am not able to create the configuration for the apigw,
not able to add the openapigwdocuments parameters and grpc services as it displays no value exists in scope for that property.

Attaching the screenshots below


<img width="533" alt="gcptf_apigw_beta_module1_error" src="https://user-images.githubusercontent.com/102816902/182368259-68f9cd45-2958-47fb-9ba7-e49b4d3633b4.png">

<img width="504" alt="gcptf_apigw_beta_module2_error" src="https://user-images.githubusercontent.com/102816902/182368283-85ead32c-8dea-4916-9a88-a896229967fb.png">

**Comment by jsteinich** [comment]
Looks like an unfortunate naming collision. There are both `GoogleApiGatewayApiConfigA` and `GoogleApiGatewayApiConfig`. The former is used to configure `google_api_gateway_api_config` and the later `google_api_gateway_api`.

**Comment by DanielMSchmidt** [comment]
This looks like the question is answered, closing it for now :)
