### ISSUE TITLE
worflow sourcecontent parameter is not accepting string data

### ISSUE THREAD

**Issue by bmakumar** [hashicorp/terraform-cdk#1992]
Hi Team,
 trying to create workflow for gcp using cdktf and as per the documentation it mentions all the Arguments are Optional infact couple of them are mandatory to create workflow , also source_contents accepts data of type "STRING" , first i tried using the same sample data that is present in the workflow document it throws error saying it is not acceptable, later saved  the code to a yaml file and passed as a string even then throwed error, finally just added a single line as string even then it throws the below error.

Error:

cdktf  ╷
       │ Error: Error waiting to create Workflow: Error waiting for Creating Workflow: Error code 3, message: main.yaml:1:1: parse error: expected a map of workflows or a sequence of steps; got string
       │ this is sample data
       │ ^
       │ 
       │ 
       │ 
       │   with google_workflows_workflow.workflow (workflow),
       │   on cdk.tf.json line 108, in resource.google_workflows_workflow.workflow (workflow):
       │  108:       }

The Error States that it is expecting Map but got string , but as per module documentation it expects to be of type string.

in case if we need to use map can you share a sample code on how it needs to be added.

Attaching all the screenshots and document link below for reference.

Workflow Document Link:  https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/workflows_workflow

<img width="577" alt="gcp_workflow_document_error" src="https://user-images.githubusercontent.com/102816902/182653519-f2fdc861-e9aa-4070-b2c1-2b69844e5a52.png">

<img width="457" alt="workflow_source_contents_error1" src="https://user-images.githubusercontent.com/102816902/182653443-ee2cef95-54a9-464e-86b9-0e589bfd0390.png">

<img width="671" alt="workflow_source_contents_error" src="https://user-images.githubusercontent.com/102816902/182653385-0569bead-12a6-432b-b7a9-58eb0d38a344.png">

<img width="539" alt="workflow_source_contents_error2" src="https://user-images.githubusercontent.com/102816902/182653291-f289f842-8806-44d5-8469-2f1eb9ba3fb1.png">

<img width="521" alt="workflow_source_contents_type" src="https://user-images.githubusercontent.com/102816902/182653250-c822a73d-5685-44c2-b4e4-4a53e95cba78.png">

**Comment by ansgarm** [comment]
Hi @bmakumar 👋

The error message is a bit confusing there, I agree. Passing a string as an attribute for `source_content` is right.
However, the string is expected to be valid yaml and that yaml should adhere to a specific format ("map of workflows or ...").

Your second to last screenshot (with the loads of red squiggly lines) is already pretty close. The only thing missing there is the correct way of denoting a multiline string in TypeScript.

The easiest way to write a multiline string in TypeScript would be to use backticks (`) I'd say. So you could try something like this:

```ts
new WorkflowsWorkflow(this, "workflow", {
  name: "daas-get-workflow",
  description: "Triggers the get cloudfuntions",
  sourceContents: `
# This is a sample workflow, feel free to replace it with your source code
#
# This workflow does the following:
# - reads current time and date information from an external API and stores
#   the response in CurrentDateTime variable
# - retrieves a list of Wikipedia articles related to the day of the week
#   from CurrentDateTime
# - returns the list of articles as an output of the workflow
# FYI, In terraform you need to escape the $$ or it will cause errors.

- getCurrentTime:
    call: http.get
    args:
        url: https://us-central1-workflowsample.cloudfunctions.net/datetime
    result: CurrentDateTime
- readWikipedia:
    call: http.get
    args:
        url: https://en.wikipedia.org/w/api.php
        query:
            action: opensearch
            search: $${CurrentDateTime.body.dayOfTheWeek}
    result: WikiResult
- returnOutput:
    return: $${WikiResult.body[1]}
`});
```

You could also use a JavaScript library (e.g. [yaml](https://www.npmjs.com/package/yaml)) that stringifies the an object to a yaml string for you and pass the result as `sourceContents`.

**Comment by bmakumar** [comment]
Hi Ansgar,

Thanks for the response after adding the source contents in above format , results in an error

it is not able to fetch the data present in flower brackets

Error:


[2022-08-03T17:06:34.251] [ERROR] default - TSError: ⨯ Unable to compile TypeScript:
main.ts(102,28): error TS2304: Cannot find name 'CurrentDateTime'.
main.ts(105,20): error TS2304: Cannot find name 'WikiResult'.

<img width="514" alt="error_workflows" src="https://user-images.githubusercontent.com/102816902/182668453-7ccc1515-5f11-43d4-8c32-9ca5eb15b687.png">

**Comment by ansgarm** [comment]
Oh, right. I forgot that I had to escape the `${` within template strings 😅 Please add a `\` in front of every `$` sign.
I also edited the code I posted above!

**Comment by bmakumar** [comment]
Also i am creating both cloud functions and workflow in a single .ts script , how can i refer the cloudfunctions url to workflow URL parameter ?

i tried something similar to below, but it didnot work

/// CloudFunctions Code:

    const Cloudfunctions3 = new CloudfunctionsFunction (this, "CloudFunction3",{
        name: "OutputFunction",
        runtime: "python39",
        entryPoint: "hello_gcs",  
    })

// workflow 
for workflow under sourcecontents what should the url be 
sourceContents: `
        <<-EOF
- randomgen_function:
    call: http.get
    args:
        url: Cloudfunctions3.triggerHttp

**Comment by ansgarm** [comment]
Hi @bmakumar, as this is drifting into being a question instead of a bug report, please post this to [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) instead 🙂

Thanks!

**Comment by ansgarm** [comment]
Thank you for posting [your question in the forum](https://discuss.hashicorp.com/t/need-help-with-refering-cloudfunction-http-endpoint-in-workflow-url/42770)! I'm going to close this issue now as the original problem seems to be resolved. If you encounter any other bugs feel free to open a new issue.
