### ISSUE TITLE
${path.cwd} not working as expected 

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#1997]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf & Language Versions

cdktf - 0.12.0
node - 18.6.0
typescript

### Affected Resource(s)
Trying to point the script to utilize a file through Fn.File but when doing so ${path.cwd} does not work. script reads it as literal rather than pointing to the current working directory. all ${path.} typically available in terraform dont work. Instead I have to use "~/" and put the needed file in my home directory 
```
vaultEks.addNodeGroup("graylogNG", {
  environment: "production",
  clusterName: "vault-eks",
  nodeGroupName: "graylogNG-",
  desiredSize: 3,
  maxSize: 8,
  minSize: 3,
  nodeRoleArn: "arn:aws:iam::477792159425:role/Nodegroup-Role",
  instanceTypes: ["m5.large"],
  customTemplate: {
    //ISSUE with ${path.cwd} not working in cdtkf
    userData: "${path.cwd}/userData-bckbn.tpl",
  },
  labels: {
    "appname": "graylog",
  },

```

### Expected Behavior

${path.cwd} should point to curretn working directory
### Actual Behavior
scriopt fails saying "${path.cwd}" is not a dir

### Steps to Reproduce

Use ${path.cwd} anywhere, Fn.file

**Comment by DanielMSchmidt** [comment]
In the context of CDKTF we recommend using [Assets](https://www.terraform.io/cdktf/concepts/assets) when working with files.

**Comment by jin-ahn** [comment]
if I follow the tutorial I have the following

```
 import * as path from "path";
...
    const asset = new TerraformAsset(this, "lambda-asset", {
      path: path.resolve(__dirname, "../lambda"),
      type: AssetType.ARCHIVE, // if left empty it infers directory and file
    });
```
But it complains that path is not found. 

So I tried to bypass importing path and just tried

```
    const asset = new TerraformAsset(this, "lambda-asset", {
      path: "./src/lambda",
      type: AssetType.ARCHIVE, // if left empty it infers directory and file
    });
```
But then it fails saying `Error: ENOENT: no such file or directory, stat 'assets/lambda_userDataasset_8946F5A8/E84C400832FD755575537F63C1A3D8BA/lambda`

**Comment by jin-ahn** [comment]
needed to add `"esModuleInterop": true` to my tsconfig.json for import path to work correctly. works now
