### ISSUE TITLE
`aws` provider: cannot install due to go module error

### ISSUE THREAD

**Issue by jaygorrell** [hashicorp/terraform-cdk#1998]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.12.0 / golang

### Affected Provider / Resource(s)

aws

### Debug Output

```
go get github.com/hashicorp/cdktf-provider-aws-go/aws   
go: module github.com/hashicorp/cdktf-provider-aws-go@upgrade found (v0.0.0-20220804010506-f53ab9125fed), but does not contain package github.com/hashicorp/cdktf-provider-aws-go/aws
```

### Expected Behavior

provider should be added successfully

### Actual Behavior

the package was unable to be located

### Steps to Reproduce

```
cdktf init --template=go --local 
go get github.com/hashicorp/cdktf-provider-aws-go/aws   
```
or
```
cdktf init --template=go --local 
cdktf provider add "aws@~>4.0"
```

**Comment by danfedick** [comment]
I get the same error when trying to get the go pkg

```bash
go get github.com/hashicorp/cdktf-provider-aws-go/aws


go: downloading github.com/hashicorp/cdktf-provider-aws-go v0.0.0-20220804010506-f53ab9125fed
go get: module github.com/hashicorp/cdktf-provider-aws-go@upgrade found (v0.0.0-20220804010506-f53ab9125fed), but does not contain package github.com/hashicorp/cdktf-provider-aws-go/aws
```

**Comment by ansgarm** [comment]
Hi @jaygorrell & @danfedick 👋 

Thank you for reporting this! This seems to be a bug in the `cdktf provider add` command.
I think Go requires major versions to be part of the package name, so the correct command to install the pre-built provider would be
```
go get github.com/hashicorp/cdktf-provider-aws-go/aws/v9
```

I'll make sure to update our pre-built provider readme installation instructions and fix the cdktf-cli `provider add` command!

**Comment by jaygorrell** [comment]
Thank you @ansgarm, that certainly helps!

If I'm not mistaken, the import statements in most documented examples and learn guides need updated as well. Instead of `"cdk.tf/go/stack/generated/hashicorp/aws"`` they would now be not only need to reference the new package but also include the v9: `"github.com/hashicorp/cdktf-provider-aws-go/aws/v9"`.

Does that seem right? I did just test those changes and things appear to be working.

**Comment by ansgarm** [comment]
Oh yeah, right! That is true. Go is very explicit about this which is nice and annoying at the same time 😄
I'll make sure we update this!

**Comment by jaygorrell** [comment]
Much appreciated!
