### ISSUE TITLE
Cdktf synth is very slow 😥

### ISSUE THREAD

**Issue by a0s** [hashicorp/terraform-cdk#2006]
Hi team, 

I am using cdktf last several months. This is a wonderful tool. But the speed of cdktf synth makes me cry every time. I need to restart this frequently, after about every change. This is called iteration. And it hurts me. How can this stage be accelerated? Why does it take more than a couple of minutes on Intel Core i9?

**Comment by ansgarm** [comment]
Hi @a0s 👋
Thank you for the kind words!
Which language and providers are you using? Are you using pre-built providers or locally built ones?

There is also the [`cdktf watch`](https://www.terraform.io/cdktf/cli-reference/commands#watch) command, although that one won't be faster in the synth step yet.

**Comment by a0s** [comment]
I am on TypeScript. 
I have ton of providers, and i am using only .gen versions. Because I can't and don't want to trust third party package builders.
```json
  "terraformProviders": [
    "hashicorp/aws@ ~> 4.19.0",
    "hashicorp/external@ ~> 2.2.2",
    "hashicorp/helm@ ~> 2.6.0",
    "hashicorp/kubernetes@ ~> 2.12.1",
    "hashicorp/local@ ~> 2.2.3",
    "hashicorp/random@ ~> 3.3.2",
    "integrations/github@ ~> 4.26.1"
  ],
  "terraformModules": [
    "DNXLabs/eks-lb-controller/aws@ ~> 0.6.0",
    "angelabad/msk-cluster/aws@ ~> 0.4.2",
    "justindotcloud/client-vpn-endpoint/aws@ ~> 0.1.1",
    "terraform-aws-modules/cloudfront/aws@ ~> 2.9.3",
    "terraform-aws-modules/eks/aws@ ~> 18.24.1",
    "terraform-aws-modules/iam/aws//modules/iam-role-for-service-accounts-eks@ ~> 5.2.0",
    "terraform-aws-modules/rds-aurora/aws@ ~> 7.2.2",
    "terraform-aws-modules/rds/aws@ ~> 4.4.0",
    "terraform-aws-modules/vpc/aws@ ~> 3.14.2"
  ],
```
The question is why it consume so many time? And can it be cached in much smarty way?

**Comment by ansgarm** [comment]
Ah!
Yeah, the `.gen` directory contains a lot of generated TypeScript code for all the bindings (for example the AWS provider has roughly 1.3m lines of code 😅). When you run `cdktf synth` your `cdktf.json > app` script gets executed which probably uses `ts-node` (depending on when you set up this project, but that is what we are currently using). And ts-node does an on the fly conversion of all `*.ts` files to JavaScript and then runs it.
To improve the time synth takes, you could switch to `tsc` which creates `*.js` files (and uses them as a cache on subsequent runs). There are also some settings on [`ts-node`](https://www.npmjs.com/package/ts-node) that could improve the performance, but I'm not familiar with them.

I personally would probably adjust my local workflow to run `tsc --watch` while I'm working on the code base (that will incrementally compile TypeScript to JavaScript). And run synth with a separate `app` command that uses the compilation result:
```
npx tsc --watch & # or run in a separate terminal instead of using &
cdktf synth --app "node main.js"
```

**Comment by a0s** [comment]
Thank you so much. Now it takes 5-10 seconds, a real beast!

**Comment by a0s** [comment]
Several notes that i found in last 24h:
1) Once you start using `npx tcs`, you can't stop. `cdktf synth` will use the cache even if nobody updates it. (I could be wrong but this is how it worked for me, i was suprised)
2) Don't forget to set `{"compilerOptions": {"outDir": "dist"}}` otherwise you will have to purge .js and .d.js from every folder and subfolder in order to flush compiled cache. (Or use compiler again). With `outDir` it just need to remove `dist` folder and thats all. (Yes you can write find blabla xargs rm .. but remove one folder much simpler)
