### ISSUE TITLE
Run builds for Windows as Well

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#201]
Since windows behaves slightly different, tests should be run for windows as well.

**Comment by skorfmann** [comment]
Github actions support windows in general - see https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners 

Not sure what the best way would be to run windows tests. It'd be nice to run the integration tests somehow. Alternatively, we could come up with a dedicated test scenario for windows. Thoughts?

**Comment by jsteinich** [comment]
Looks like the Windows runners have Docker, so an integration testing using the docker example might be a start.
Longer term it would probably be good have more thorough testing of the cli.

**Comment by skorfmann** [comment]
> Looks like the Windows runners have Docker, so an integration testing using the docker example might be a start.

In the existing integration we've just a `null` resource deployment. That's good enough for the cli integration for now.

What I meant: I haven't touched in Windows in ages and will have to read up on how to basic things like installing node, npm. But perhaps the Github runner supports this already, don't know.

**Comment by skorfmann** [comment]
These are the integration tests I was talking about: https://github.com/hashicorp/terraform-cdk/tree/master/test - We could try to add a dedicated windows integration build based on this https://github.com/hashicorp/terraform-cdk/tree/master/test/test-typescript-deploy

**Comment by jsteinich** [comment]
There's a pretty extensive list of things installed: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

I'm on Windows most of the time so I can do some local testing.

Do you have a preference between platform specific scripts vs writing something in JS/TS/Python that would be cross platform?

**Comment by skorfmann** [comment]
> There's a pretty extensive list of things installed: https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md

That looks sufficient, yes 👍 

> I'm on Windows most of the time so I can do some local testing.

That would be great, wanna take a stab at it?

> Do you have a preference between platform specific scripts vs writing something in JS/TS/Python that would be cross platform?

In the best case this would be delegated to JS. I messed this up already once :) see #205
