### ISSUE TITLE
`google` provider: "google_eventarc_trigger" resource created with invalid key "id" what needs to be "trigger_id"

### ISSUE THREAD

**Issue by meioli** [hashicorp/terraform-cdk#2012]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- Java Maven
- cdktf: 0.13.0-pre.6
- cdktf-provider-google: 2.0.10

### Affected Provider / Resource(s)

cdktf-provider-google
"google_eventarc_trigger" resource

### Debug Output

```
╷
│ Error: Invalid or unknown key
│ 
│   with google_eventarc_trigger.stack_name_id,
│   on cdk.tf.json line 23077, in resource.google_eventarc_trigger.stack_name_id:
│ 23077:         "id": "trigger_id",
│ 
╵
```

### Expected Behavior

Eventarc Trigger is created when running cdktf deploy

### Actual Behavior

Eventarc Trigger creation fails with error above.

### Steps to Reproduce

Create a eventarc trigger and try to deploy it.
```
EventarcTrigger.Builder.create(this, triggerName)
                  .name(triggerName)
                  .id(triggerName)
                  .project(project)
                  .location(location)
                  .matchingCriteria(
                      List.of(
                          EventarcTriggerMatchingCriteria.builder()
                              .attribute("type")
                              .value("google.cloud.pubsub.topic.v1.messagePublished")
                              .build()))
                  .destination(
                      EventarcTriggerDestination.builder()
                          .workflow(
                              String.format(
                                  "projects/%s/locations/%s/workflows/%s",
                                 project,
                                  location,
                                  workflowName))
                          .build())
                  .build();
```

### Important Factoids

None

### References

Nothing.

- #0000

**Comment by ansgarm** [comment]
Hi @meioli 👋
The `id` field does not need to be set. The inline documentation for that field should give a bit clarity to why it still exists:
> Please be aware that the id field is automatically added to all resources in Terraform providers using a Terraform provider SDK version below 2. If you experience problems setting this value it might not be settable. Please take a look at the provider documentation to ensure it should be settable.

Whereas in the provider documentation for [`google_eventarc_trigger`](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger) the [`id` field](https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/eventarc_trigger#id) is only listed as an attribute and not as an argument. So, it can't be set. You can just remove that part 👍

**Comment by meioli** [comment]
Hi @ansgarm.
thanks for clarifying. Diving into the documentation I realized what was actually going wrong.

The real problem was that I first used underscores in the trigger names, this lead to the following error message:
```
Error: Error creating Trigger: googleapi: Error 400: The request was invalid: trigger_name: must follow this regex format: "^[a-z][a-z0-9-]*[a-z0-9]$", please see the user guide for details
Step #6 - "[cdktf] deploy":                         │ Details:
Step #6 - "[cdktf] deploy":                         │ [
Step #6 - "[cdktf] deploy":                         │   {
Step #6 - "[cdktf] deploy":                         │     "@type": "type.googleapis.com/google.rpc.BadRequest",
Step #6 - "[cdktf] deploy":                         │     "fieldViolations": [
Step #6 - "[cdktf] deploy":                         │       {
Step #6 - "[cdktf] deploy":                         │         "field": "trigger_id"
Step #6 - "[cdktf] deploy":                         │       }
Step #6 - "[cdktf] deploy":                         │     ]
Step #6 - "[cdktf] deploy":                         │   },
Step #6 - "[cdktf] deploy":                         │   {
Step #6 - "[cdktf] deploy":                         │     "@type": "type.googleapis.com/google.rpc.RequestInfo",
Step #6 - "[cdktf] deploy":                         │     "requestId": "xx"
Step #6 - "[cdktf] deploy":                         │   }
Step #6 - "[cdktf] deploy":                         │ ]
```
Because the api response indicates the error in `trigger_id` I assumed it is the `id` field in the provider, so I added it what lead to the error described above. A bit confusing that the google api responds with `trigger_id` when the field everywhere else in the gcp service (and therefore also in terraform) is called `name`.

I realized my mistake when I tried to create the triggers directly via the gcloud CLI.

Thanks for pointing me into the right direction!

Best
