### ISSUE TITLE
A parallel stack `deploy` errors locks the other stacks

### ISSUE THREAD

**Issue by Zman94** [hashicorp/terraform-cdk#2030]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
❯ cdktf --version
0.12.0
```
### Affected Resource(s)

Any. For my example, I am creating `resource "azurerm_log_analytics_saved_search"` in stack 1 and networking resources (Vnet, Subnets, NSGs) in stack 2

Stack 1 and 2 are running in parallel because they are independent of each other.
In stack 1, I am forcing an error to occur while the two stacks are deploying with
```
cdktf deploy -auto-approve
```

### Debug Output

https://gist.github.com/Zman94/b98f82570f500415df5f03768d9f7dff

### Expected Behavior

The run should error out, but stack 2 should not be locked. The lock should be released before `cdktf deploy` errors out

### Actual Behavior

The lock on stack 2 remains after stack 1 errors and `cdktf deploy` returns to the user. I then need to manually unlock my stack

### Steps to Reproduce

Create 2 parallel stacks (any resource). Put an error in stack 1. Run deploy

### Important Factoids

Nothing atypical. I'm also seeing this happen on `cdktf destroy`

### References

None

**Comment by DanielMSchmidt** [comment]
Could you try version 0.12.1 we just released, it contains a fix

**Comment by Zman94** [comment]
Just ran through a full test. Looks great! Thanks for the speedy response. 0.12.1 fixed it.

**Comment by ansgarm** [comment]
(fixed by #1987)
