### ISSUE TITLE
"Found resources without a matching provider." when using auth0 provider

### ISSUE THREAD

**Issue by Aaronius** [hashicorp/terraform-cdk#2036]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf: 0.12.1
typescript: 4.7.4

### Affected Resource(s)
All Auth0 resources.

### Debug Output
https://gist.github.com/Aaronius/353a111b18922564088708596282060f

### Expected Behavior
Successful synth

### Actual Behavior
Error: `Found resources without a matching provider. Please make sure to add the following providers to your stack: auth0`

### Steps to Reproduce
Add the auth0/auth0 provider: 

```
"terraformProviders": [
  "auth0/auth0@~> 0.35"
]
```

Use it to create a Client (or any other) Auth0 resource:

```
import { Construct } from "constructs";
import {App, TerraformStack} from "cdktf";
import {Client} from "./.gen/providers/auth0";

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new Client(this, "dashboard-application", {
      name: "UMC Dashboard",
      appType: "spa",
      callbacks: ["http://localhost:3000/callback"],
      allowedLogoutUrls: ["http://localhost:3000"],
      allowedOrigins: ["http://localhost:3000"],
      oidcConformant: true
    });
  }
}

const app = new App();
new MyStack(app, "auth0-terraform");
app.synth();
```

Run `cdktf synth`.

### Important Factoids
I really have no idea, but I would guess cdktf is tripping up because the name of the provider in `terraformProviders` is `auth0/auth0` but the directory in `.gen` is `auth0`. 

### References

- #0000

**Comment by jsteinich** [comment]
You'll need to create an instance of the `Auth0Provider` in your stack. It configures the provider access to allow you to create resources. https://registry.terraform.io/providers/auth0/auth0/latest/docs has more information about what parameters are needed.

**Comment by ansgarm** [comment]
Seems like we should improve the wording of the error message to make that more clear 👍

**Comment by Aaronius** [comment]
Ah, that makes sense and it fixed the problem. Thank you.
