### ISSUE TITLE
Suggestions for improving documentation and examples

### ISSUE THREAD

**Issue by xiehan** [hashicorp/terraform-cdk#2053]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Here's some feedback and ideas for how to improve our documentation based on a conversation one of our engineers had with some folks over at AWS:

- more complex examples (the ones they found in the examples folder were to easy) -> how can we give our e2e examples more visibility here?
- there were no docs around networking -> they might contribute something here
- almost no usage of data sources in the examples, AMIs were used directly -> This is something we could and should change, it seems like a quick win
- not a lot of documentation and examples around using modules -> We should add a dedicated example for modules at least in TS

**Comment by DanielMSchmidt** [comment]
Split this in sub issues, closing this now 👍
