### ISSUE TITLE
CDKTf convert command issue with C#

### ISSUE THREAD

**Issue by vbebins** [hashicorp/terraform-cdk#2075]
I have a simple variable.tf file and I tried to convert the same to C# using the convert command, Below is command I used for the same,

`PS C:\Users\bebins.velmurugan\source\repos\TerraformInfra> cat variable.tf | cdktf  convert --language csharp > imported.cs
`undefined
Collecting Debug Information...
C:\Users\bebins.velmurugan\AppData\Roaming\npm\node_modules\cdktf-cli\node_modules\yoga-layout-prebuilt\yoga-layout\build\Release\nbind.js:53
        throw ex;
        ^

**[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "No stdin was passed, please use it like this: cat main.tf | cdktf convert > imported.ts".] {
  code: 'ERR_UNHANDLED_REJECTION'
}**
PS C:\Users\bebins.velmurugan\source\repos\TerraformInfra>

I am not sure what does this error mean?
Could anyone please help with this?

**Comment by ansgarm** [comment]
Hi @vbebins 👋

What is the output of only `cat variable.tf`? Is it printing anything? (Is your file maybe named `variables.tf`? So maybe just a typo?)
Else: Could you try `echo "should fail differently" | cdktf convert --language csharp > imported.cs`?

As you seem to be running Windows: What shell are you using? Does it have the `cat` command?
