### ISSUE TITLE
Support of `replace_triggered_by` lifecycle

### ISSUE THREAD

**Issue by iharabukhouski** [hashicorp/terraform-cdk#2082]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would you please consider adding support of `replace_triggered_by` lifecycle

### References
[Terraform Docs](https://www.terraform.io/language/meta-arguments/lifecycle#replace_triggered_by)

**Comment by DanielMSchmidt** [comment]
Yeah good point, we should add this!

**Comment by ansgarm** [comment]
Hi @manojkarthick 👋
You should be able to use an escape hatch ([docs](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch)) on the resource.

There are no concrete plans for this yet, but we're open to a PR adding support for this 👀
