### ISSUE TITLE
Add documentation for construct authoring

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2084]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have little docs to link to for folks who want to explore building constructs. We should have docs mentioning

- the projen template
- best practices for creating shared constructs
- hybrid constructs

**Comment by shinebayar-g** [comment]
I'd like to author a custom provider for my personal project. Is there ANY documentation on this?

**Comment by jsteinich** [comment]
> I'd like to author a custom provider for my personal project. Is there ANY documentation on this?

I responded to your [discuss post](https://discuss.hashicorp.com/t/how-to-develop-custom-provider-for-cdktf/47654)

**Comment by ansgarm** [comment]
Another related [Discuss topic](https://discuss.hashicorp.com/t/can-i-import-a-native-terraform-module-in-a-construct/48070) about using Terraform modules when authoring constructs. The `cdk.tf.json` file might not yet be covered / managed by the Projen template for CDKTF constructs, which is something we should check when writing these docs.

**Comment by xiehan** [comment]
This was addressed in #2287 so I'm going to close this. If there's follow-up work (e.g. additions to that document) that we want to make, please open up a new ticket to capture the desired changes.
