### ISSUE TITLE
Rename `get` to `import` and `.gen` to `imports` to align with cdk8s and AWS CDK

### ISSUE THREAD

**Issue by eladb** [hashicorp/terraform-cdk#209]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, cdktf uses the verb `get` to generate constructs for providers and modules and this generated code is written to the `.gen/` directory.

In [cdk8s], we are using the verb `import` and the directory `imports/`. We are devising a plan to introduce a similar API for the AWS CDK (`cdk import`) in order to support importing constructs from the CloudFormation Registry ([RFC](https://github.com/aws/aws-cdk-rfcs/issues/77))

I'd like to propose to align these names 

Additionally, in [cdk8s], we encourage users to commit this generated code into their source repository, which simplifies the build logic in many environments (there is no need for a custom pre-build step).

**Comment by DanielMSchmidt** [comment]
Closing this, seems like cdk and terraform lingo collides here with no better way of reconciling. (that we know of right now, if y'all have ideas let us know :) )

**Comment by jsteinich** [comment]
> We mainly closed this issue because we currently don't plan to rename it to `import` as originally suggested in this issue.

Sounds good. I put the reference in a comment in #1084. Will close this again.
