### ISSUE TITLE
Allow dot in an ID

### ISSUE THREAD

**Issue by benkeil** [hashicorp/terraform-cdk#2094]
At the moment dots `.` are replaced with an empty string in an id. But if you use e.g. modules the ID is allowed. Allow them also for constructs.

**Comment by ansgarm** [comment]
Hi @benkeil,

could you give an example?

**Comment by benkeil** [comment]
If you have something like this

```Kotlin
JwtAuthBackendRole.Builder.create(this, "foo.bar").build()
```

The resulting id is `foobar`, but in terraform `foo.bar` is also valid.

**Comment by ansgarm** [comment]
>  but in terraform foo.bar is also valid

I'm not sure whether that is correct. I just tried
```hcl
resource "random_string" "random.id" {
}
```
And `terraform validate` gives me the following error:
```
╷
│ Error: Invalid resource name
│
│   on main.tf line 1, in resource "random_string" "random.id":
│    1: resource "random_string" "random.id" {
│
│ A name must start with a letter or underscore and may contain only letters, digits, underscores, and dashes.
╵
```
(tested with Terraform 1.2.8)

Or am I misunderstanding something here? Could you give me an HCL example with a dot in an id which works?

**Comment by benkeil** [comment]
Ok initially i saw the dot in a resource with a module. So maybe terraform needs the dot to make some stuff.

**Comment by ansgarm** [comment]
Yeah, the dot could've been used to access an output of a module maybe? But thank you for raising this anyway! Could've been an inconsistency in our API as well :)
