### ISSUE TITLE
public_ip_address_id for Lb is not generated

### ISSUE THREAD

**Issue by herveleclerc** [hashicorp/terraform-cdk#2095]
cdktf-provider-azurerm python

I'm trying to generate a loadbalencer (Lb) with a reference to a previously public ip via `public_ip_address_id` attribute 

The generated tf doesn't have the `public_ip_address_id` 

```python

      public_ip = PublicIp(self, vars.public_ip_name,
                    allocation_method="Static",
                    location=vars.location,
                    name=vars.public_ip_name,
                    resource_group_name=vars.rg_name
        )

       lb = Lb(self, vars.lb_name,
            depends_on =[public_ip],
            frontend_ip_configuration=[{
                 "name": "pip",
                 "public_ip_address_id": Token().as_string(public_ip.id)
            }],
            location=vars.location,
            name= vars.lb_name,
            resource_group_name=vars.rg_name
        )
```

tf generated 

```
"azurerm_lb": {
      "herlectalos-lb": {
        "//": {
          "metadata": {
            "path": "herlectalos/herlectalos-lb",
            "uniqueId": "herlectalos-lb"
          }
        },
        "depends_on": [
          "azurerm_public_ip.herlectalos-public-ip"
        ],
        "frontend_ip_configuration": [
          {
            "name": "herlectalos-public-ip"
          }
        ],
        "location": "northeurope",
        "name": "herlectalos-lb",
        "resource_group_name": "herlectalos-rg"
      }
    },
```

Am I missing something ?

**Comment by ansgarm** [comment]
Hi @herveleclerc,

what happens if you set an arbitrary invalid id for `public_ip_address_id`, so e.g. `"public_ip_address_id": "abc"`?

Does that end up in the synthesized JSON config?

**Comment by herveleclerc** [comment]
Hello, 

I've tried , nothing happens :( , nothing is generated

**Comment by ansgarm** [comment]
Hi @herveleclerc,

found the solution: It requires wrapping in `LbFrontendIpConfiguration`:
```python
from cdktf_cdktf_provider_azurerm import LbFrontendIpConfiguration

frontend_ip_configuration=[LbFrontendIpConfiguration(
     name="pip",
     public_ip_address_id=Token().as_string(public_ip.id)
)],
```
But I don't know why it was able to pass along `name` but failed to do so for `public_ip_address_id` – and I'm sure that we've had this issue in Python before / it already exists.

Maybe @jsteinich knows a bit more about that?

**Comment by jsteinich** [comment]
This is definitely a bit strange. It appears as though it actually synthesized `name` to be `public_ip_address_id`. I know a recent JSII update made changes intended to make passing a dict better supported; perhaps there's an issue with that.

**Comment by herveleclerc** [comment]
Thank you the workaround works fine !
there are some other attributes are affected by this behavior eg: public_ip_prefix_id)
