### ISSUE TITLE
learn.hashicorp.com has incorrect/old golang modules.

### ISSUE THREAD

**Issue by cwiggs** [hashicorp/terraform-cdk#2101]
Docs are pointing to https://cdk.tf to import golang modules, but cdk.tf is deprecated?

https://learn.hashicorp.com/tutorials/terraform/cdktf-build#define-your-cdk-for-terraform-application is the link that has this code in it:

```
import (
    "github.com/aws/constructs-go/constructs/v10"
    "github.com/aws/jsii-runtime-go"
    "github.com/hashicorp/terraform-cdk-go/cdktf"

    "cdk.tf/go/stack/generated/hashicorp/aws"
    "cdk.tf/go/stack/generated/hashicorp/aws/ec2"
)
<snip>
```

If you `go get cdk.tf/go/stack/generated/hashicorp/aws` it fails.

I finally found the packages have moved.  Here is the correct code:

```
import (
    "github.com/aws/constructs-go/constructs/v10"
    "github.com/aws/jsii-runtime-go"
    "github.com/hashicorp/terraform-cdk-go/cdktf"

    "github.com/hashicorp/cdktf-provider-aws-go/aws/v9"
    "github.com/hashicorp/cdktf-provider-aws-go/aws/v9/ec2"
)
```

Also, the docs say:

```
Tip: If you would prefer to store your project's state locally, remove or comment out cdktf.NewRemoteBackend(stack, &cdktf.RemoteBackendProps{ [...] })
```

However you have to do remove or comment and change the line that says `stack := NewMyStack(app, "aws_instance")` to `NewMyStack(app, "aws_instance")`

I would create a PR to fix those issues but it seems learn.hashicorp.com isn't on github like the docs on terraform.io are?

**Comment by ansgarm** [comment]
Hi @cwiggs 👋

Thanks for reporting this! The tutorials for HashiCorp Learn are closed source, but I put in a fix PR for the Go imports 👍

To clarify the second thing you mentioned: Are you talking about the need to also remove the then unused variable `stack` so Go does not complain about it?

**Comment by cwiggs** [comment]
> Hi @cwiggs 👋
> 
> Thanks for reporting this! The tutorials for HashiCorp Learn are closed source, but I put in a fix PR for the Go imports 👍
> 
> To clarify the second thing you mentioned: Are you talking about the need to also remove the then unused variable `stack` so Go does not complain about it?

Hi @ansgarm 

Somewhat, if you remove that unused variable the program will still fail because you can't calling a stack at all now.  Instead of removing/commenting it out you need to edit the line to call the `NewMyStack()` function instead of storing it in a variable.
