### ISSUE TITLE
 Call to function "index" failed: item not found

### ISSUE THREAD

**Issue by jaty613** [hashicorp/terraform-cdk#2112]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf  0.12.1 or 0.12.2     

### Debug Output
dtci_-k).ids is list of string with 2 elements
                                                                        │ 
                                                                        │ Call to function "index" failed: item not found

### Important Factoids

  const diskAttachment = new EcsDiskAttachment(this, "mount-" + stackId, {
            instanceId: vmState.instances.get(Fn.index(vmState.ids, "${each.value}")).id,
            diskId: diskState.disks.get(Fn.index(vmState.ids,"${each.value}")).diskId
        })

        diskAttachment.addOverride("for_each",localIds.asList)

================================================
synth code

    "alicloud_ecs_disk_attachment": {
      "mount-k": {
        "disk_id": "${data.alicloud_ecs_disks.dtccss_k.disks[index(data.alicloud_instances.dtci_k.ids, \"$${each.value}\")].disk_id}",
        "for_each": "${local.instance_ids}",
        "instance_id": "${data.alicloud_instances.dtci_k.instances[index(data.alicloud_instances.dtci_k.ids, \"$${each.value}\")].id}"
      }
    }

each.value One more $ flag.

### References

- #0000

**Comment by ansgarm** [comment]
Hi @jaty613,

have you tried using an Iterator ([docs](https://www.terraform.io/cdktf/concepts/iterators)) instead of the override?

**Comment by jaty613** [comment]
Iterator is ok.
