### ISSUE TITLE
Improve error message when trying to deploy to non-existing TFC workspace

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2120]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* 0.12.2
* any language

### Affected Resource(s)

* `CloudBackend`
* `RemoteBackend`

### Debug Output

<img width="793" alt="image" src="https://user-images.githubusercontent.com/1112056/190597779-051555f5-d213-40b0-a3c4-1808aea6bdea.png">

### Expected Behavior

Should print a good error message or even ask whether the cdktf-cli should create that workspace and try again.

### Actual Behavior

Error does not help at all

### Steps to Reproduce

Try to deploy to a non-existing workspace in Terraform Cloud using the `CloudBackend` or `RemoteBackend` construct.

### References

- #0000

**Comment by mutahhir** [comment]
@ansgarm What was the code that caused this error?

**Comment by xiehan** [comment]
This has been made irrelevant by #1955 and #670 which we get for free as part of that work.
