### ISSUE TITLE
DataTerraformRemoteStateAzurermConfig does not include option for UseAzureasAuth

### ISSUE THREAD

**Issue by jleechpe** [hashicorp/terraform-cdk#2126]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF 0.12.2
Dotnet 6.0.304

### Affected Resource(s)

DataTerraformRemoteStateAzurermConfig

### Expected Behavior

Terraform Azurerm Remote State Backend allows for `use_msi`, `use_oidc` and `use_azuread_auth` in addition to SAS Token and Client/Secret.

When creating the same backend configuration in CDKTF for .NET SAS, ClientSecret and UseMSI are offered as completion candidates but `UseAzureadAuth` is not

### Actual Behavior

Completion only allows for `UseMsi` (of the `use_*` options) when defining the data source.

### Steps to Reproduce

Create a data source referencing an AzureRM remote state and try to use `UseAzureadAuth` (or use completion candidates on `Use`).  CDKTF synth will fail since it is not known to exist.

**Comment by ansgarm** [comment]
Hi @jleechpe 👋

Looks like we need to add support for those properties!

In the meantime you can use an override as a workaround, as described in this comment: https://github.com/hashicorp/terraform-cdk/issues/2049#issuecomment-1225810193
