### ISSUE TITLE
Cannot open terraform cloud screen when cdktf init is done in devcontainer

### ISSUE THREAD

**Issue by nmemoto** [hashicorp/terraform-cdk#2132]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
$ cdktf --version
0.12.2
```

### Affected Resource(s)

- nothing

### Debug Output

https://gist.github.com/nmemoto/36c0123e3011848ee9a73e070469565d

### Expected Behavior

Run cdktf init -template="typescript" in Devcontainer.
I want the following screen to appear in the host's browser.

<img src="https://user-images.githubusercontent.com/1522332/191569040-a240f30c-4d48-441c-9e3e-2af4e779d1f9.png" width="200">

### Actual Behavior

The contents of Debug output were output and timed out.

### Steps to Reproduce

1. Open the following repository in VSCode Remote Container.
    https://github.com/nmemoto/try-cdktf

2. Execute the following in devcontainer
```
mkdir learn-cdktf
cdktf init --template="typescript"
```

### Important Factoids

- nothing

### References

- nothing

**Comment by nmemoto** [comment]
I would like to work on this issue.

**Comment by DanielMSchmidt** [comment]
The issue stems from us trying to help you get a Terraform Cloud token. What would be your proposed solution?

**Comment by nmemoto** [comment]
Thanks for the quick reply.

If the environment variable BROWSER is set, I am thinking of using child_process.exec to make that string execute the OS command.

Inside devcontainer, [github-cli](https://github.com/cli/cli) can be used to open the host's browser. This is because it uses the browser execution path specified in the environment variables and configuration file.

[Here](https://github.com/cli/cli/blob/24ff8fac408cdcd212498b9dd9081d7175d2d763/internal/authflow/flow.go#L42-L48) we get the environment variables and settings, and finally execute the command [here](https://github.com/cli/go-gh/blob/802b578c27d9117fd04f2c84ceb5aebc032ea8cf/pkg/browser/browser.go#L60).

When the following is executed inside Devcontainer(with VSCode Remote Containers), the environment variable BROWSER is set, so we think we can handle the above.

```
 $ env |grep BROWSER
 BROWSER=/vscode/vscode-server/bin/linux-x64/74b1f979648cc44d385a2286793c226e611f59e7/bin/helpers/browser.sh
```

I am almost new to trying to OSS contribute and there may be many things I don't understand. Any advice would be appreciated.

**Comment by nmemoto** [comment]
I found that if I install xdg-utils on devcontainer (with `sudo apt-get install xdg-utils`), it opens in VSCode as follows.

<img src="https://user-images.githubusercontent.com/1522332/191832061-3fd86da4-daca-4cf4-845b-a5b674c44995.png" width="200">

I will try to propose a fix in [devcontainers/features](https://github.com/devcontainers/features) that will make this installation in devcontainer.

So I will close this issue.
Thank you for your confirmation.
