### ISSUE TITLE
Multiline string for helm chart not preserving spaces

### ISSUE THREAD

**Issue by paymog** [hashicorp/terraform-cdk#2141]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

typescript 0.12

### Affected Resource(s)

setting value in helm chart

### Expected Behavior

I expect multiline strings to be kept as is when setting values for helm charts

### Actual Behavior

The leading spaces for each line in a multiline string a stripped

### Steps to Reproduce

Create a datadog helm chart like the following

```
    new helm.Release(this, "datadog-agent", {
      chart: "datadog",
      name: "datadog",
      repository: "https://helm.datadoghq.com",
      version: "3.1.3",
      set: [
        {
          name: "clusterAgent.confd",
          value: `postgres.yaml: |-
cluster_check: true
init_config:
instances:
\t- dbm: true
\t  host: <redacted>
\t  port: 5432
\t  username: datadog
\t  password: <redacted>
    `
        }

      ],
    });
```

try deploying this chart and see the following diff

```
                   + set {
                   + name  = "clusterAgent.confd"
                   + value = <<-EOT
                   postgres.yaml: |-
                   cluster_check: true
                   init_config:
                   instances:
                   - dbm: true
                   host: <redacted>
                   port: 5432
                   username: datadog
                   password: <redacted>

                   EOT
```

Note that leading spaces/tabs are not preserved.

### Important Factoids

Nope

### References

I'm trying to replicate what's shown in [these datadog docs](https://docs.datadoghq.com/database_monitoring/setup_postgres/aurora/?tab=kubernetes#command-line-with-helm) with CDKTF

**Comment by mutahhir** [comment]
I believe this is related to us trimming the output from Terraform on the console, and not actually removing the leading spaces from the helm chart. 

It should be fixed when https://github.com/hashicorp/terraform-cdk/pull/2100 is released. 

Did you try deploying and did the deployed chart have the same problem?

**Comment by paymog** [comment]
Yeah, when I tried deploying this Helm errored out and said that it couldn't range over keys. I'm not sure if it's because the spacing is incorrect or if I'm not correctly reproducing the expected structure for the key.

**Comment by ansgarm** [comment]
Oh, and apparently yaml does not support tabs (if [this](https://stackoverflow.com/a/19976827/3420189) is right)

**Comment by DanielMSchmidt** [comment]
This sounds to me like it's both solved and an upstream issue in the provider (as cdktf seems to preserve the spaces). Closing this for now, feel free to reopen if I misunderstood this :)
