### ISSUE TITLE
Add Terraform Version Check

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#216]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Reduce confusion to users running an older version of Terraform by printing out a warning notice when Terraform < 0.12 

The functionality could also be useful when new versions of Terraform are being released (e.g. `0.13 ` with the changed provider naming schema).

### References

https://github.com/hashicorp/terraform-cdk/issues/208

**Comment by bverhoeve** [comment]
Hi @skorfmann I'm looking to contribute to the repository, what exactly needs to be done?

**Comment by skorfmann** [comment]
> Hi @skorfmann I'm looking to contribute to the repository, what exactly needs to be done?

For the case where a user uses something below `0.12`, it would be great to display a clear error message and exit the process. The supported Terraform versions at the moment are `0.12` and `0.13`.  I think the check should go like this:

- `< SUPPORTED => exit` with error message
- `>= SUPPORTED => continue` without further message.

We do have a [terraform check](https://github.com/hashicorp/terraform-cdk/blob/175c3872827c1325d32ecc7ea7150a2774da0121/packages/cdktf-cli/bin/cmds/terraform-check.ts#L6) already, which checks for the presence of the Terraform CLI only. This could be expanded to check against supported versions and print a helpful error message.

--- 

ps: I was thinking about if it would make sense to print a warning when a user is using `> SUPPORTED` (e.g. alpha of `0.14` at the moment). However, I think it's not important for now and I'd ignore this case until we actually run into issues with a case like that.

**Comment by bverhoeve** [comment]
Okay, thanks for the explanation! I'll check to tend to it.

**Comment by skorfmann** [comment]
This was addressed in #378
