### ISSUE TITLE
Only release new versions of the pre-built providers when there are relevant changes

### ISSUE THREAD

**Issue by xiehan** [hashicorp/terraform-cdk#2169]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Provider / Resource(s)

All of them, though it's mostly causing issues for big providers like AWS and AzureRM

### Expected Behavior

Pre-built providers should only trigger a release (and publish packages to npm, PyPI, etc.) when one of the following conditions is true:
- a new version of the underlying provider has been released (this happens on average once a week for verified providers)
- a new version of CDKTF has been released (this happens on average once a month)

### Actual Behavior

Pre-built providers trigger a release when _any_ of the underlying JavaScript dependencies are updated. Since Projen has nightly builds, this means our pre-built providers currently unnecessarily publish a new version every single day.

### Impact

Issues like #1486 and cdktf/cdktf-provider-aws#774 occur because we have are butting up against the limits of our project size in PyPI. We can ask them to increase those limits, but only once we prove that we've done due diligence to reduce the rate at which we publish new packages to only what is strictly necessary.

### References

- https://pypi.org/project/cdktf-cdktf-provider-aws/#history vs https://github.com/hashicorp/cdktf-provider-aws/releases
- https://pypi.org/project/cdktf-cdktf-provider-google/#history vs https://github.com/hashicorp/cdktf-provider-google/releases
- https://pypi.org/project/cdktf-cdktf-provider-kubernetes/#history vs https://github.com/cdktf/cdktf-provider-kubernetes/releases

An example of what triggered a patch release of the AWS provider: https://github.com/hashicorp/cdktf-provider-aws/commit/65ad21f976291fb413607a7f79c14814007073e8

### Previous Discussions

@DanielMSchmidt:
> RE PyPi & Publishing pre-built providers too much: I spiked into the topic and to me it looks like we could add a few steps to the github workflow to check if the cdktf version or the provider version changed since the last release and set an output that then can be used to skip the release steps. This is definitely doable...

@ansgarm:
> Sounds like a good approach, although skipping the release should be something that we should be able to override easily. For example there could be a certain dependency upgrade that we need to release to fix some upstream issues (thinking about TypeScript here).

@DanielMSchmidt:
> There would also be a cheap solution I should mention: releasing on a cron, that’s already built-in and even with the option to also have a manual trigger IIRC

@ansgarm:
> We could also have a manual trigger to release (in case of upstream funkery) which could override (aka ignore) the skip-if-no-new-version logic.

**Comment by ansgarm** [comment]
While we already implemented this using a hacky workaround, it is still open as I'm working on integrating this properly into Projen (https://github.com/projen/projen/issues/2179)
