### ISSUE TITLE
Make cdktf get easier to debug

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Make `cdktf get` easier to debug. Right now the code has to be changed manually in order to see what JSII produces on `stdout`.

### References

https://github.com/hashicorp/terraform-cdk/issues/217

**Comment by DanielMSchmidt** [comment]
We could use https://github.com/visionmedia/debug to add debug logging throughout the application. One can set flags that change the scope depending on what to debug.

**Comment by ansgarm** [comment]
> We could use https://github.com/visionmedia/debug 
Yup, I really like that lib, too :)
However, I found this already existed when I had that same idea: https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf-cli/lib/logging.ts 😅 
Maybe we might just need to polish up that logging code there.

**Comment by skorfmann** [comment]
Don't have strong opinions about the library we use here. We should keep a few things in mind though:

- having multiple, configurable output destinations is really useful (stdout, file, ...)
- there are multiple sources we might want to log separately (cdktf, jsii, terraform, terraform cloud client)
- on top of this, we will likely want to separate this on a per stack level as well 

As an example what I'm imagining there: Being able to print all of this to stdout while each of the individual streams gets written to a dedicated file.

**Comment by xiehan** [comment]
We don't think this is an active issue anymore / has been addressed tangentially by other work. If there's a more specific problem to tackle, please open a new issue.
