### ISSUE TITLE
Failed to update appsync-api-cache ttl

### ISSUE THREAD

**Issue by successx** [hashicorp/terraform-cdk#2187]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
"@cdktf/provider-aws": "10.0.10"
Same problem from v9

### Affected Provider / Resource(s)
@cdktf/provider-aws

### Debug Output

[Error output](https://gist.github.com/successx/2dd04f4f2504873793606dcd218447b9)

### Expected Behavior

Should be able to change appsync-api-cache ttl.

### Actual Behavior

Update ttl config throw above error

### Steps to Reproduce

- Create appsync-api-cache and specify ttl
- Update ttl and deploy again.

I think there is an issue if case-sensitive. Please check that. Thanks!

**Comment by ansgarm** [comment]
Hi @successx 👋

Which arguments are you passing to the aws_appsync_api_cache resource?
Could it maybe be related to this issue: https://github.com/hashicorp/terraform-provider-aws/issues/25599 ?

**Comment by successx** [comment]
Thanks,

The settings is similar to this in Typescript

```
resource "aws_appsync_api_cache" "example" {
  api_id               = aws_appsync_graphql_api.example.id
  api_caching_behavior = "FULL_REQUEST_CACHING"
  type                 = "LARGE"
  ttl                  = 900
}
```

It successfully create api cache when I check aws console. Only error out when change ttl to a different value.

**Comment by jsteinich** [comment]
It looks to be a bug in the underlying Terraform AWS Provider. https://github.com/hashicorp/terraform-provider-aws/blob/8f48c22f8e87774a73156e638fdfc2de2d2e8615/internal/service/appsync/api_cache.go#L125 appears to only set the parameter value if there's a change, but according to the [aws documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/appsync.html#AppSync.Client.update_api_cache), it is required.
@successx would you mind creating a bug [here](https://github.com/hashicorp/terraform-provider-aws/issues/new?assignees=&labels=bug%2Cneeds-triage&template=00_bug_report.yml&title=%5BBug%5D%3A+)?

**Comment by successx** [comment]
Thanks @jsteinich . I have created a bug in that repo. Closing this for now.
