### ISSUE TITLE
cdktf debug should list prebuilt provider versions 

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2190]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

And ideally also show the peer dependency of the provider in question so pre-built provider related dependency issues are easier to debug.

### References

- https://discuss.hashicorp.com/t/cdk-not-respecting-pom-xml/45418/7

**Comment by xiehan** [comment]
Discussed with the team today, and the suggested (easy) solution is to just have this call `cdktf provider list` under-the-hood, which does exactly this.
