### ISSUE TITLE
`aws` provider: CDKTF tutorial documentation needs updating for dependency changes

### ISSUE THREAD

**Issue by csjcode** [hashicorp/terraform-cdk#2197]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Provider / Resource(s)

@cdktf/provider-aws@10.0.10

The tutorial examples won't compile for: ec2 and AwsProvider using @cdktf/provider-aws@10.0.10

The code requested which is not working in the tutorial is:
 `import { AwsProvider, ec2 } from "@cdktf/provider-aws";`

$ cdktf deploy

### Debug Output

[2022-10-17T15:57:17.874] [ERROR] default - TSError: ⨯ Unable to compile TypeScript:
main.ts(3,10): error TS2724: '"@cdktf/provider-aws"' has no exported member named 'AwsProvider'. Did you mean 'provider'?
main.ts(3,23): error TS2305: Module '"@cdktf/provider-aws"' has no exported member 'ec2'.
### Expected Behavior

Expected it to compile and deploy 

### Actual Behavior

It does not compile and deploy, it errors out with the Typescript error above,

### Steps to Reproduce

Tutorial (Typescript): https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-build

### Important Factoids

I rolled back to provider-aws@9.0.52 and it works fine with that

npm i @cdktf/provider-aws@9.0.52

This resolves it

### References

See tutorial: 
https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-build

- #0000

**Comment by xiehan** [comment]
I forgot we had an open issue for this -- this was fixed a couple of weeks ago. Thanks for flagging!
