### ISSUE TITLE
Built-in Function Compatibility

### ISSUE THREAD

**Issue by pmartindev** [hashicorp/terraform-cdk#220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, as far as I'm aware, the terraform built-in functions are not compatible with cdktf. 

Examples below:
https://www.terraform.io/docs/configuration/functions.html
https://www.terraform.io/docs/configuration/functions/cidrsubnet.html

**Comment by skorfmann** [comment]
> Currently, as far as I'm aware, the terraform built-in functions are not compatible with cdktf.

Yes, there's no builtin support for using functions at the moment. In general, there are two ways of dealing with this:

#### 1. Use Escape Hatches 

It should be possible to use functions in overrides as described [here](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/escape-hatch.md). That's at the moment the only way when working with computed attributes.

#### 2. Use a library of the platform

For things which are known at build time, it's perfectly fine to use some library from the programming environment.
One example for Typescript I was playing around with is the [@eryldor/cidr](https://www.npmjs.com/package/@eryldor/cidr?activeTab=readme) npm package

In theory, this could also be wrapped in a `null` resource with local exec and would work then at runtime as well. But that's uncharted terrain and nothing I'd recommend ;)

<details><summary>Vpc Construct</summary><p>

```ts
import { Construct } from "constructs";
import { TerraformResource } from "cdktf";
import { Vpc, InternetGateway, Subnet } from "./.gen/providers/aws";
import { AwsRegion } from "./aws-regions";
import { CIDRBlock } from "@eryldor/cidr";

export interface AwsVpcConfig {
  readonly region: AwsRegion;
  readonly cidrBlock: string;
}

export class AwsVpc extends Construct {
  public readonly publicSubnets: Subnet[];
  public readonly privateSubnets: Subnet[];

  constructor(scope: Construct, name: string, config: AwsVpcConfig) {
    super(scope, name);

    const cidr = CIDRBlock.fromString(config.cidrBlock);
    const [publicSubnetBlock, privateSubnetBlock] = cidr.split(2);
    const publicSubnets = publicSubnetBlock.split(3);
    const privateSubnets = privateSubnetBlock.split(3);

    const vpcMain = new Vpc(this, "main", {
      cidrBlock: config.cidrBlock,
      tags: {
        Name: name,
      },
    });

    new InternetGateway(this, "igw", {
      vpcId: vpcMain.id,
    });

    this.publicSubnets = config.region.zones.map(
      (zone, index) =>
        new Subnet(this, `public-${zone}`, {
          vpcId: vpcMain.id!,
          cidrBlock: publicSubnets[index].toString(),
          availabilityZone: zone,
          tags: {
            Name: `${name}-public-${zone}`,
          },
        })
    );

    this.privateSubnets = config.region.zones.map(
      (zone, index) =>
        new Subnet(this, `private-${zone}`, {
          vpcId: vpcMain.id!,
          cidrBlock: privateSubnets[index].toString(),
          availabilityZone: zone,
          tags: {
            Name: `${name}-public-${zone}`,
          },
        })
    );
  }
}
```

</p></details>
