### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by ahmagdy** [hashicorp/terraform-cdk#221]
Hi
I noticed that all the examples are about AWS. So, I'm wondering if Azure is supported? and if so how to get started?

**Comment by anubhavmishra** [comment]
@ahmagdy thanks for your question! We have an azure example shown [here](https://github.com/hashicorp/terraform-cdk/tree/master/examples/typescript-azure). Hopefully that helps!

**Comment by ahmagdy** [comment]
@anubhavmishra Thanks for your answer. 
That's what i wanted :) .
