### ISSUE TITLE
Windows: cdktf deploy - symlink not permitted

### ISSUE THREAD

**Issue by Satak** [hashicorp/terraform-cdk#222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version : `0.0.12-pre.4c00f2bafb17b79dcf2310a2a85a4ef9ed6518a1`
TypeScript

### Affected Resource(s)

All, Docker example

### Debug Output

```
❯ cdktf deploy
⠸ synthesizing ...
internal/fs/utils.js:298
    throw err;
    ^

Error: EPERM: operation not permitted, symlink 'C:\Dev\satak\terraform-vm-test\.terraform' -> 'C:\Dev\satak\terraform-vm-test\cdktf.out\.terraform'
    at Object.symlinkSync (fs.js:1121:3)
    at MyStack.linkDotTerraform (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\terraform-stack.js:98:16)
    at MyStack.onSynthesize (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\terraform-stack.js:91:14)
    at Node.synthesize (C:\Dev\satak\terraform-vm-test\node_modules\constructs\lib\construct.js:342:27)
    at App.synth (C:\Dev\satak\terraform-vm-test\node_modules\cdktf\lib\app.js:32:36)
    at Object.<anonymous> (C:\Dev\satak\terraform-vm-test\main.js:26:5)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14) {
  errno: -4048,
  syscall: 'symlink',
  code: 'EPERM',
  path: 'C:\\Dev\\satak\\terraform-vm-test\\.terraform',
  dest: 'C:\\Dev\\satak\\terraform-vm-test\\cdktf.out\\.terraform'
⠼ synthesizing ...
```

### Expected Behavior

deploy should work without elevated (terminal opened as admin) rights

### Actual Behavior

Deploy fails on permissions while trying to create symlink

### Steps to Reproduce

Try to deploy Docker example with TypeScript on VS Code terminal (pwsh 7.0) from terminal that is not opened as admin

### Other

I can't open my terminal as admin since it's not company policy to have terminals opened as admin. Make a workaround to copy files without symlink, like:

```js
try {
  fs.symlinkSync(absoluteFilePath, outputFilePath);
} catch(e) {
  const conentStr = fs.readFileSync(absoluteFilePath);
  fs.writeFileSync(outputFilePath, conentStr);
}
```

**Comment by skorfmann** [comment]
Thanks for your bug report. 

The symlink is for the `.terraform` directory and it's purpose is to avoid re-downloading the Terraform providers. Besides from making these providers survive a removal of the `cdktf.out` directory, another intent was caching between `cdktf get` runs. I think `cdktf get` runs in a temp directory now and doesn't benefit from this anymore.

Alternatively, we should think about fully leveraging [Terraform provider caching](https://www.terraform.io/docs/configuration/providers.html#provider-plugin-cache) to have a more robust way of handling this.

This could be done by:

- Documenting how to do it (e.g. via env)
- Getting rid of the symlink logic in the code 

what do you think? /cc @anubhavmishra

**Comment by skorfmann** [comment]
Getting rid of the symlink would also fix this issue https://github.com/hashicorp/terraform-cdk/issues/189
