### ISSUE TITLE
Azurerm | AppService -> SiteConfig-> IP Restrictions not working 

### ISSUE THREAD

**Issue by nlucansk** [hashicorp/terraform-cdk#2220]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Python 3.10.8
hashicorp/azurerm v3.26.0 
Terraform v1.2.4

### Affected Resource(s)

from cdktf_cdktf_provider_azurerm.linux_web_app import **LinuxWebAppSiteConfigIpRestriction**

### Debug Output

![image](https://user-images.githubusercontent.com/51444462/197521431-db96ef6c-7234-4255-aad1-f1bc924108c3.png)

### Expected Behavior

- IP restriction should be added to AppService 

### Actual Behavior

Error (img above),  I am not able to deploy the stack.
Passing None or Empty strings ([] in case of header) will bypass the validation but deploy will crash.

### Steps to Reproduce

Create AppService with 
```
ip_restriction=[
  LinuxWebAppSiteConfigIpRestriction(
    name="randomname",
    priority=100,
    action="Allow",
    ip_address="randomIP/32"
  )
]
```

### Important Factoids

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/linux_web_app#action
![image](https://user-images.githubusercontent.com/51444462/197522178-efe0b508-3533-4a10-8776-2a6f7f3e298d.png)

### References

- #0000

**Comment by ansgarm** [comment]
Hi @nlucansk 👋
This seems to be an upstream problem in the Azure Terraform provider: https://github.com/hashicorp/terraform-provider-azurerm/issues/17189

**Comment by nlucansk** [comment]
Yes, in vanilla TF you can get around as on the example ^^.

In Python I am not able to get to that result:

![image](https://user-images.githubusercontent.com/51444462/197525290-f9f05039-7fc5-4d20-a012-50d75ebff805.png)
This will produce exactly the same error 


![image](https://user-images.githubusercontent.com/51444462/197525551-06db2f15-d35b-4b97-aba4-34f998e0f3bd.png)
This will fail during the deployment with:
```Error: expected "site_config.0.ip_restriction.0.service_tag" to not be an empty string, same for other parameters```

**Comment by nlucansk** [comment]
🤔 | Is possible to add something like
from cdktf import **TerraformEmpty**
virtual_network_subnet_id=TerraformEmpty(),

This will tell cdktf synth to produce json with null?

**Comment by ansgarm** [comment]
Yeah, that would be a possible API if we can't make passing the `null` value of each language work 👍
Let me try TypeScript real quick..

**Comment by nlucansk** [comment]
I will rather wait for a proper fix as "null" is pretty critical in certain situations.
Thank you, tracking the #2221
