### ISSUE TITLE
Skip initialization when possible

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform-cdk#2222]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During every run, I see

```txt
prod  Initializing the backend...
prod
prod  Initializing provider plugins...
prod  - Reusing previous version of hashicorp/aws from the dependency lock file
prod  - Using previously-installed hashicorp/aws v4.33.0
prod  Terraform has been successfully initialized!
      
      You may now begin working with Terraform. Try running "terraform plan" to see
      any changes that are required for your infrastructure. All Terraform commands
      should now work.

      If you ever set or change modules or backend configuration for Terraform,
      rerun this command to reinitialize your working directory. If you forget, other
      commands will detect it and remind you to do so if necessary.
```

This is noisy and the instructions ("If you forget, other commands will detect it and remind you to do so if necessary") don't really match the cdk behavior. 

I think there is also some performance cost to it, IIRC, but perhaps not.

Mostly, I would like to not keep seeing "successfully initialized!" when it has already in fact been initialized. It makes me concerned, like I'm create a new stack.

**Comment by xiehan** [comment]
This was done as part of #2572.
