### ISSUE TITLE
Terraform Cloud Bearer token plain text printed in log when cdktf command fails

### ISSUE THREAD

**Issue by daniel-laszlo** [hashicorp/terraform-cdk#2233]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Python 3.9
CDKTF 0.13.2

### Affected Resource(s)

`cdktf diff`
`cdktf deploy`

### Debug Output

```
Creating Terraform Cloud configuration version
Created Terraform Cloud configuration version cv-XXXXXXXXXXXXX
Zipping up the directory cdktf.out/stacks/STACK
Uploading the directory to Terraform Cloud
Uploaded the directory to Terraform Cloud
Waiting for configuration version to become ready...
Creating speculative Terraform Cloud run
Created speculative Terraform Cloud run: https://app.terraform.io/app/ORGANIZATION/workspaces/WORKSPACE_NAME/runs/run-XXXXXXXXXXXXXXXX
Speculative Terraform Cloud run done
Getting plan output
Deploying Terraform Cloud run


1 Stack deploying     0 Stacks done     0 Stacks waiting
[2022-10-31T14:34:34.126] [ERROR] default - Error in Deploy: {"message":"...","name":"Error","stack":"...","config":{"url":"...","method":"post","data":"{}",
"headers":{"Authorization":"Bearer TOKEN",  <--- TOKEN is in plain text!!
"Accept":"application/json","Content-Type":"application/vnd.api+json","User-Agent":"terraform-cloud/1.15.0","Content-Length":2},"baseURL":"https://app.terraform.io/api/v2","transformRequest":[null],"transformResponse":[null],"timeout":0,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"transitional":{"silentJSONParsing":true,"forcedJSONParsing":true,"clarifyTimeoutError":false}}}
```

### Expected Behavior

No token is printed when there is an error.

### Actual Behavior

Token is printed in plain text and since it needs to be an [admin token on Terraform Cloud to be able to query json-output](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/plans#retrieve-the-json-execution-plan) it is very sensitive.

**Comment by mutahhir** [comment]
Fix for this was released in cdktf version 0.13.3
