### ISSUE TITLE
CDKTF tsconfig paths not working

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#2237]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
language: typescript
cdktf-cli: 0.13.0
node: v16.17.0
cdktf: 0.13.2
constructs: 10.1.142
jsii: null
terraform: 1.3.2
arch: x64
os: linux 5.10.102.1-microsoft-standard-WSL2
```

#### CDKTF Typescript
- When using paths in `tsconfig file`, `cdktf synth` throws error. 
- the tsconfig.json file 
```
{
    "paths": {
      "@models": [
        "./lib/models/index.ts"
      ],
      "@helpers": [
        "./lib/helpers/index.ts"
      ],
    },
  },
  "include": ["./lib/**/*.ts", "./src/**/*.ts"],
  "exclude": [
    "node_modules",
    "cdktf.out"
  ]
}
```
- the cdktf.json file 
```
{
    "app": "npx ts-node -r tsconfig-paths/register --prefer-ts-exts src/main.ts",
}
```
- the TagsAspect file in /libs/helpers/tag-aspect-ts
```
import { IConstruct } from "constructs";
import { IAspect } from "cdktf";

// Not all constructs are taggable, so we need to filter it
type TaggableConstruct = IConstruct & {
  tags?: { [key: string]: string };
  tagsInput?: { [key: string]: string };
};

function isTaggableConstruct(x: IConstruct): x is TaggableConstruct {
  return "tags" in x && "tagsInput" in x;
}

export class TagsAddingAspect implements IAspect {
  constructor(private tagsToAdd: Record<string, string>) {}

  // This method is called on every Construct within the specified scope (resources, data sources, etc.).
  visit(node: IConstruct) {
    if (isTaggableConstruct(node)) {
      // We need to take the input value to not create a circular reference
      const currentTags = node.tagsInput || {};
      this.tagsToAdd["name"] = node.node.id;
      node.tags = { ...this.tagsToAdd, ...currentTags };
    }
  }
}
```
### Debug Output
```
⠋  Synthesizing
[2022-10-31T10:37:56.103] [ERROR] default - /home/projects/github/metronet-iac-core/node_modules/@cdktf/provider-aws/src/provider/index.ts:3003
export class AwsProvider extends cdktf.TerraformProvider {
                                       ^
[2022-10-31T10:37:56.104] [ERROR] default - TypeError: Class extends value undefined is not a constructor or null
    at Object.<anonymous> (/home/projects/github/metronet-iac-core/node_modules/@cdktf/provider-aws/src/provider/index.ts:3003:40)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Object.require.extensions.<computed> [as .js] (/home/projects/github/metronet-iac-core/node_modules/ts-node/src/index.ts:1608:43)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/projects/github/metronet-iac-core/tgw-stack.ts:3:1)
ERROR: cdktf encountered an error while synthesizing

Synth command: npx ts-node -r tsconfig-paths/register --prefer-ts-exts src/main.ts
Error:         non-zero exit code 1
```

### Expected Behavior
- CDKTF should be able to synthesize the stack. 

### Actual Behavior
- CDKTF throws the above error

### Steps to Reproduce
- Add paths to tsconfig.json file
- Use one of the paths in your imports. Such as `import { TagsAddingAspect } from "@helpers/tag-aspect";`
- Add some generic stack with AWS Provider.
- Add the Aspect to the stack.
```
 Aspects.of(stack).add(
    new TagsAddingAspect({ createdBy: "cdktf", environment: "global" })
  );
```
- Install tsconfig-paths and update your cdktf.json > app.
- Run CDKTF synth.

### References

- https://discuss.hashicorp.com/t/cdktf-tsconfig-paths-not-working-for-local-imports/46163
- https://github.com/aws/jsii/issues/865#issuecomment-950261852

**Comment by DanielMSchmidt** [comment]
Ah I just saw [your answer](https://discuss.hashicorp.com/t/cdktf-tsconfig-paths-not-working-for-local-imports/46163/5?u=danielmschmidt). It seems like the error stems from the app command, so there is not much cdktf itself can do here, we just execute this command you give us. The error looks like importing cdktf inside of the pre-built provider fails to resolve, in TS this can sometimes hint to a circular dependency if I recall correctly.
