### ISSUE TITLE
Mark backends that were removed in Terraform 1.3 as deprecated in the CDKTF docs

### ISSUE THREAD

**Issue by xiehan** [hashicorp/terraform-cdk#2244]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Several remote backends were removed in Terraform 1.3 but are currently still supported in CDKTF because we support Terraform 1.1+. We should at minimum mark these backends as deprecated in our own documentation and in the docblocks to discourage new use of these backends in case we require a higher version of Terraform for future releases with which these backends are no longer compatible.

The main page affected by this is: https://developer.hashicorp.com/terraform/cdktf/concepts/remote-backends#supported-backends

### References

From the Terraform core changelog for 1.3:

> The following backends, which were deprecated in v1.2.3, have now been removed: `artifactory`, `etcd`, `etcdv3`, `manta`, `swift`. The legacy backend name `azure` has also been removed, because the current Azure backend is named `azurerm`. (https://github.com/hashicorp/terraform/issues/31711)

**Comment by laurapacilio** [comment]
This will be addressed in this PR: https://github.com/hashicorp/terraform-cdk/pull/2261/files
