### ISSUE TITLE
Support `for_each` (aka TerraformIterator) on modules

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2245]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support `TerraformIterator` ([docs](https://developer.hashicorp.com/terraform/cdktf/concepts/iterators)) on modules.

**Comment by DanielMSchmidt** [comment]
Module Support for iterators was added in #1830
