### ISSUE TITLE
Not being able to increment Fn.index

### ISSUE THREAD

**Issue by sabinayakc** [hashicorp/terraform-cdk#2247]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
language: typescript
cdktf-cli: 0.13.0
node: v16.17.0
cdktf: 0.13.2
constructs: 10.1.142
jsii: null
terraform: 1.3.2
arch: x64
os: linux 5.10.102.1-microsoft-standard-WSL2
```

#### CDKTF Typescript
- When using cidrsubnet , I am trying to increase the netsum using Fn.index + 1. See code below.  Zone Iterator is a simple AWS datasource with azs. 
```
 const privateSubnet = new Subnet(this, "private-subnets", {
      forEach: zoneIterator,
      vpcId: this.vpc.id,
      cidrBlock: Fn.cidrsubnet(this.vpc.cidrBlock, 4, Fn.index(zones.names, zoneIterator.value) + 1),
      availabilityZone: zoneIterator.value,
    });
```
### Debug Output
-  CDKTF.out/stack
```
    "aws_subnet": {
      "private-subnets": {
        "//": {
          "metadata": {
            "path": "my-vpc/private-subnets",
            "uniqueId": "private-subnets"
          }
        },
        "availability_zone": "${each.value}",
        "cidr_block": "${cidrsubnet(aws_vpc.my-vpc.cidr_block, 4, index(data.aws_availability_zones.all.names, each.value))}",
        "for_each": "${toset(data.aws_availability_zones.all.names)}",
        "tags": {
          "createdBy": "cdktf",
          "environment": "core",
          "name": "firewall-subnet-${each.value}-${index(data.aws_availability_zones.all.names, each.value) + 1}"
        },
        "vpc_id": "${aws_vpc.my-vpc.id}"
      }
```

### Expected Behavior
- It should add +1 in the cidr_block. Like this
`"cidr_block": "${cidrsubnet(aws_vpc.my-vpc.cidr_block, 4, index(data.aws_availability_zones.all.names, each.value))}",`

### Actual Behavior
- The +1 is ignored. 

### Steps to Reproduce
- Created an iterated subnet using zones.
- Create cidr block using the above function
- Now synthesize.

### Information
- The workaround is using escape hatches but it's a pretty hacky one.

**Comment by ansgarm** [comment]
Hi 👋
The value of `each.value` isn't a number but rather a token that resolves to a Terraform reference, so you can't use arithmetic operators in TypeScript on that value.
Instead you could do
```ts
cidrBlock: Fn.cidrsubnet(this.vpc.cidrBlock, 4, Fn.sum([Fn.index(zones.names, zoneIterator.value), 1]))
```
