### ISSUE TITLE
`aws` provider: Launch Template associate public ip address wrong data type

### ISSUE THREAD

**Issue by riebecj** [hashicorp/terraform-cdk#2263]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.13.3
Python: 3.9.10
cdktf-provider-aws: 10.0.2

### Affected Provider / Resource(s)

[launch_template.LaunchTemplateNetworkInterfaces](https://github.com/cdktf/cdktf-provider-aws/blob/aafce3305aba097f4367ba5a00988b49571717d3/src/launch-template/index.ts#L3377)

### Debug Output

![Screen Shot 2022-11-08 at 12 43 13](https://user-images.githubusercontent.com/16140677/200649378-26862e2d-45f6-4487-bd31-2ad115537f04.png)

### Expected Behavior

To assign `associate_public_ip_address` to a boolean based on [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/launch_template#associate_public_ip_address).

### Actual Behavior

Requires a string input instead.

### Steps to Reproduce

Create a `LaunchTemplateNetworkInterfaces` object and attempt to assign `associate_public_ip_address` to a boolean value.

### Important Factoids

None.

### References

- [#819](https://github.com/cdktf/cdktf-provider-aws/pull/819) <- Pull request

**Comment by ansgarm** [comment]
Thanks for raising this!

We get the type from the schema of the Terraform provider. So this might be a bug in the AWS Terraform Provider.
Let me check the AWS Terraform provider schema real quick to confirm this.

In the meantime you might be able to work around this by passing `Token.as_string(False)`.

**Comment by xiehan** [comment]
Since this is an upstream issue in the AWS provider and there is a reasonable workaround, I'm going to go ahead and close this.
