### ISSUE TITLE
Output command

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#227]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When a stack has no changes, the `apply` is omitted  and therefore no outputs are printed.

Two things here:

- `cdktf deploy` should always print outputs regardless of changes being present 
- introduce `cdktf output` to explicitly retrieve outputs only

**Comment by ansgarm** [comment]
Seconding in on this.
For my CDK Day talk I had to build a [rather ugly workaround](https://github.com/ansgarm/talk-cdkday-2021/blob/master/test/getOutputs.js) to get outputs which I used for tests.

**Comment by matschaffer** [comment]
I solved this by putting this in my `package.json`:

```
  "scripts": {
    ...
    "outputs": "cd cdktf.out/stacks/metricbeat_monitoring_on_cloud; terraform output -json > outputs.json"
  },
```

That way I can at least just run `yarn outputs` and get a json file.

I can then read this json file from other scripts that helps complete provisioning beyond what I'm able to do with the terraform provider.

`cdk output -json` would be a welcome addition for that piece.

**Comment by ansgarm** [comment]
Ah, that's a nice workaround @matschaffer 💡  That reminds me of a [similar thing](https://github.com/hashicorp/cdktf-integration-serverless-example/blob/06bff1363504388b7b467ec23e019f498e807eca/frontend/index.ts#L77-L83) I did for the dotenv config for a React frontend, however that does not make use of outputs but uses Terraform to write that file.  
I have the feeling there might be a way to collect all outputs of a stack and write such an `outputs.json` file via Terraform 😄

**Comment by skorfmann** [comment]
> I have the feeling there might be a way to collect all outputs of a stack and write such an `outputs.json` file via Terraform 😄

You're thinking about an Aspect here?

**Comment by kc-dot-io** [comment]
How about approaching this the same way [that CDK does](https://github.com/aws/aws-cdk/commit/75d5ee9e41935a9525fa6cfe5a059398d0a799cd) using `--outputs-file`?

**Comment by jsteinich** [comment]
> How about approaching this the same way [that CDK does](https://github.com/aws/aws-cdk/commit/75d5ee9e41935a9525fa6cfe5a059398d0a799cd) using `--outputs-file`?

Having that consistency sounds like a good idea to me. Could still add the `output` command which accepts the same argument.
