### ISSUE TITLE
`aws` provider: Imports broken in v10.0.11

### ISSUE THREAD

**Issue by aa8y** [hashicorp/terraform-cdk#2279]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Provider / Resource(s)

10.0.11

### Debug Output

https://gist.github.com/aa8y/1aaec3451568cb52b0ad4de7c901dce0

### Expected Behavior

Import statements are not affected by version upgrade from v9.0.52 to v10.0.11.

#### IAM import changes

```
-import {
-  DataAwsIamPolicyDocument,
-  IamRole,
-  IamRolePolicyAttachment,
-} from '@cdktf/provider-aws/lib/iam';
+import { DataAwsIamPolicyDocument } from '@cdktf/provider-aws/lib/data-aws-iam-policy-document';
+import { IamRole } from '@cdktf/provider-aws/lib/iam-role';
+import { IamRolePolicyAttachment } from '@cdktf/provider-aws/lib/iam-role-policy-attachment';
```

#### S3 import changes

```
-import {
-  S3Bucket,
-  S3BucketNotification,
-  S3BucketServerSideEncryptionConfigurationA,
-} from '@cdktf/provider-aws/lib/s3';
+import { S3Bucket } from '@cdktf/provider-aws/lib/s3-bucket';
+import { S3BucketNotification } from '@cdktf/provider-aws/lib/s3-bucket-notification';
+import { S3BucketServerSideEncryptionConfigurationA } from '@cdktf/provider-aws/lib/s3-bucket-server-side-encryption-configuration';
```

To me it looks like v10 is missing index files which direct all imports for a service to a common namespace like  @cdktf/provider-aws/lib/iam and `@cdktf/provider-aws/lib/s3` (which is also the best practice), instead of each resource having its own personal namespace.

### Steps to Reproduce

1. Create a CDKTF project with `@cdktf/provider-aws` v9.0.52.
2. Create a stack with AWS resources. Let's take, for example, IAM and S3 and make sure they're imported.
3. Build/Synthesize the infrastructure. No need to deploy it anywhere.
4. Upgrade `@cdktf/provider-aws` to v10.0.11.
5. Rerun build/synthesize. You'll see that the imports are not the same, breaking the build.

### Important Factoids

No

### References

None

**Comment by DanielMSchmidt** [comment]
Hey, this is the expected behaviour. We did this change to [improve the synth-time performance of CDKTF](https://www.hashicorp.com/blog/cdk-for-terraform-0-13-significantly-improves-performance). By upgrading the pre-built AWS provider you upgraded from CDKTF 0.12 to 0.13, please take a look at our [upgrade guide](https://developer.hashicorp.com/terraform/cdktf/release/upgrade-guide-v0-13)
