### ISSUE TITLE
CDK init allow to choose to use Terraform cloud if detected

### ISSUE THREAD

**Issue by dre2004** [hashicorp/terraform-cdk#2280]
#### Description
When initialising a new project and if a Terraform Cloud connection is detected (I assume this is based on `~/.terraform.d/credentials.tfrc.json` existing) the `init` step does not give you the option to not use this connection.

It would be nice if we could choose if we wanted this behaviour.

**Comment by DanielMSchmidt** [comment]
Good point! There is the `--local` flag you can pass to init, but asking the user might be a better UX 👍
