### ISSUE TITLE
`newrelic` provider: `one-dashboard-json`

### ISSUE THREAD

**Issue by ps-radianbaskoro** [hashicorp/terraform-cdk#2290]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`newrelic` Terraform provider was recently updated with `newrelic_one_dashboard_json` resource to import a dashboard from JSON exported from UI.

Existing `newrelic_one_dashboard` and `newrelic_one_dashboard_raw` are planned to be deprecated with warnings now added to documentation.
https://github.com/newrelic/terraform-provider-newrelic/discussions/2044
https://github.com/newrelic/terraform-provider-newrelic/pull/2059

### References

Terraform provider resource PR: https://github.com/newrelic/terraform-provider-newrelic/pull/2026
And the release changelog: https://github.com/newrelic/terraform-provider-newrelic/blob/main/CHANGELOG.md#v340---2022-10-03

**Comment by ansgarm** [comment]
Hi @ps-radianbaskoro 👋

Thanks for reporting. It appears that we currently still are one the previous major version for the pre-built provider: https://github.com/cdktf/cdktf-repository-manager/blob/43b0f523f5be95cc0bae9736c181cafe593724d2/provider.json#L33

But that's something we can update 👍

**Comment by ps-radianbaskoro** [comment]
Thanks!  I appreciate the company and community's help with everything.  Sorry about the noob questions, I'm just barely scratching the surface on CDKTF.  After posting this, I also realized I could have gone the `cdktf get` route.
