### ISSUE TITLE
cdktf get EMFILE error

### ISSUE THREAD

**Issue by msavidg** [hashicorp/terraform-cdk#2296]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.13.3 C#

cdktf debug
language: null
cdktf-cli: 0.13.3
node: v18.12.1
terraform: 1.3.4
arch: x64
os: win32 10.0.19044

### Affected Resource(s)

cdktf get produces EMFILE: too many open files

### Debug Output

https://gist.github.com/msavidg/edfec8083f7d8fb8669d1cf08ff2cfc6#file-gistfile1-txt

### Steps to Reproduce

mkdir foo & cd foo
cdktf init
edit cdktf.json:  "terraformProviders": ["aws@~> 4.0"],

```

{
  "language": "csharp",
  "app": "dotnet run -p MyTerraformStack.csproj",
  "projectId": "082dc538-b4b0-4c72-9865-2a35f1f625db",
  "sendCrashReports": "true",
  "terraformProviders": ["aws@~> 4.0"],
  "terraformModules": [],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}

cdktf get


NOTE: Temp directory retained due to an error: C:\TEMP\temp-nngPnl
Error: jsii compilation failed with non-zero exit code: 1
  | [jsii-pacmak] [WARN] dotnet failed
  | Error: EMFILE: too many open files, open 'C:\TEMP\temp-nngPnl\dist\dotnet\aws\aws\Wafv2RuleGroup\Wafv2RuleGroupRuleStatementRateBasedStatementScopeDownStatementOrStatementStatementOrStatementStatementSizeConstraintStatementFieldToMatchHeadersMatchPatternOutputReference.cs'
  +----------------------------------------------------------------------------------
  | Command: C:\Users\xxxxxxxx\AppData\Roaming\nvm\v18.12.1\node_modules\cdktf-cli\node_modules\jsii-pacmak\bin\jsii-pacmak --code-only
  | Workdir: C:\TEMP\temp-nngPnl
  +----------------------------------------------------------------------------------
    at p (C:\Users\xxxxxxxx\AppData\Roaming\nvm\v18.12.1\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:52:1581)
    at ChildProcess.<anonymous> (C:\Users\xxxxxxxx\AppData\Roaming\nvm\v18.12.1\node_modules\cdktf-cli\bundle\bin\cmds\handlers.js:55:112)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
⠏ downloading and generating modules and providers...
jsii compilation failed with non-zero exit code: 1
  | [jsii-pacmak] [WARN] dotnet failed
  | Error: EMFILE: too many open files, open 'C:\TEMP\temp-nngPnl\dist\dotnet\aws\aws\Wafv2RuleGroup\Wafv2RuleGroupRuleStatementRateBasedStatementScopeDownStatementOrStatementStatementOrStatementStatementSizeConstraintStatementFieldToMatchHeadersMatchPatternOutputReference.cs'
  +----------------------------------------------------------------------------------
  | Command: C:\Users\xxxxxxxx\AppData\Roaming\nvm\v18.12.1\node_modules\cdktf-cli\node_modules\jsii-pacmak\bin\jsii-pacmak --code-only
  | Workdir: C:\TEMP\temp-nngPnl
  +----------------------------------------------------------------------------------


```

**Comment by msavidg** [comment]
Also tried with these versions:

cdktf debug

language: csharp
**cdktf-cli: 0.14.1**
node: v18.12.1
**cdktf: 0.14.1**
constructs: 10.0.25
**jsii: 1.71.0**
terraform: 1.3.4
arch: x64
os: win32 10.0.19044
dotnet: 7.0.100

Same error:
jsii compilation failed with non-zero exit code: 1
  | [jsii-pacmak] [WARN] dotnet failed
  | Error: EMFILE: too many open files, open 'C:\Users\xxxxxxxx\AppData\Local\Temp\temp-Y4mzFB\dist\dotnet\aws\aws\Wafv2RuleGroup\Wafv2RuleGroupRuleStatementRateBasedStatementScopeDownStatementOrStatementStatementOrStatementStatementSqliMatchStatement.cs'

**Comment by DanielMSchmidt** [comment]
Created an upstream issue for this: https://github.com/aws/jsii/issues/3843

**Comment by xiehan** [comment]
Closing as not planned because we can't address this ourselves -- this needs to be an upstream fix in JSII.
