### ISSUE TITLE
MODULE_NOT_FOUND on cdktf-cli@0.14.0

### ISSUE THREAD

**Issue by willish** [hashicorp/terraform-cdk#2300]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- node version 16.18.1
- cdktf-cli version 0.14.0  (no problem on `0.13.3`)

### Affected Resource(s)

`cdktf-cli` is unusable

### Debug Output

https://gist.github.com/willish/e661ca7eccf7ade977e1d523b0fd76de

### Expected Behavior

`cdktf` should show the help

### Actual Behavior

A stacktrace due to `MODULE_NOT_FOUND` (`Error: Cannot find module '../../../../cdktf-cli/src/lib/version'`) in `constructs-maker.js`

### Steps to Reproduce

On Amazon Linux 2:

```
sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
sudo yum -y install terraform
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
. ~/.nvm/nvm.sh
nvm install 16
npm install --global cdktf-cli@latest
cdktf help
```

**Comment by ansgarm** [comment]
Hi @willish 👋
Whoops, thanks for raising this. This line seems to be the reason:
https://github.com/hashicorp/terraform-cdk/blob/823f343aef9917fd56dc5eecc01bcaf4c43a0ed5/packages/@cdktf/provider-generator/lib/get/constructs-maker.ts#L22

I'll work on a patch version ASAP!

**Comment by ansgarm** [comment]
Unfortunately, our CI and tests didn't catch this as it only fails after the CLI was bundled. We test the bundle for the cdktf core library – something we apparently should to start doing for the cdktf-cli as well.

**Comment by ansgarm** [comment]
Hi 👋
[CDKTF 0.14.1](https://github.com/hashicorp/terraform-cdk/releases/tag/v0.14.1) has just been released with a fix 🐛
