### ISSUE TITLE
Azurerm | LinuxWebAppSiteConfigIpRestriction + `Token.null_value()` not working 

### ISSUE THREAD

**Issue by nlucansk** [hashicorp/terraform-cdk#2306]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

<img width="360" alt="image" src="https://user-images.githubusercontent.com/51444462/202291362-9f2d77a7-5db8-4b88-bbc0-0c3205b1a25d.png">

### Affected Resource(s)

LinuxWebAppSiteConfigIpRestriction

### Expected Behavior

Token.null_value should be processed to null 

### Actual Behavior

<img width="987" alt="image" src="https://user-images.githubusercontent.com/51444462/202291940-28d9a39c-8c54-4764-8fac-0d5240fb38fe.png">

### Steps to Reproduce

<img width="337" alt="image" src="https://user-images.githubusercontent.com/51444462/202291525-ec7016ea-9926-43df-ac92-f9a613c5f739.png">

### References

- #0000

**Comment by ansgarm** [comment]
Hi @nlucansk 👋

Oh, interesting – it seems that something on the Python side of things is stringifying the `IResolvable` returned by `Token.null_value()`. I suspect that `LinuxWebAppSiteConfigIpRestriction` could have something to do with that.

That said, I think we can workaround this by passing `Token.as_string(Token.null_value())` which should wrap the token in a string that won't be altered by Python in any way.

**Comment by nlucansk** [comment]
`Token.as_string(Token.null_value())` works just fine, thank you :)
