### ISSUE TITLE
Incorrect generation of datastax/astra provider

### ISSUE THREAD

**Issue by AlexStasko** [hashicorp/terraform-cdk#2310]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf: 0.14.1
nodejs: v16.18.0
typescript: 4.8.4

### Affected Resource(s)
datastax/astra provider
table resource

### Debug Output
https://gist.github.com/AlexStasko/55f94a8ec04047db3b969feae3e13825

### Expected Behavior
`columnDefinitions` attribute of `table` resource is generated with the correct type: `{ [key: string]: string }[] | cdktf.IResolvable[]`. 
The stack is deployed successfully.

### Actual Behavior
`columnDefinitions` attribute of `table` resource is generated with the type: `{ [key: string]: string } | cdktf.IResolvable`.  That is incorrect in regard to provider documentation. In this case, I can not declare multiple columns.
If I declare only one column there is the error during `cdktf diff`

### References

- #0000

**Comment by ansgarm** [comment]
Thank you for reporting @AlexStasko 👍

I was able to confirm that the following attribute definition from the Terraform provider schema is not properly handled:
```json
"column_definitions": {
  "type": [
    "list",
    [
      "map",
      "string"
    ]
  ],
  "description": "A list of table Definitions",
  "description_kind": "markdown",
  "required": true
},
```

I suspect that we don't properly parse this definition as it results in (as you reported):
```ts
readonly columnDefinitions: { [key: string]: string } | cdktf.IResolvable;
```

**Comment by ansgarm** [comment]
Until we fix this, you can work around this using:
```ts
columnDefinitions: [
  {
    Name: "a",
    Static: false,
    TypeDefinition: "text",
  },
  {
    Name: "b",
    Static: false,
    TypeDefinition: "text",
  },
] as any,
```

**Comment by AlexStasko** [comment]
Hi @ansgarm, thank you for your quick response. Workaround works for me.
