### ISSUE TITLE
HCL to CDKTF Tool

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#232]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It'd be pretty cool to have a `hcl2cdktf` tool. It would take HCL and transform it to `cdktf` Typescript Constructs. This would enable:

- Converting an existing HCL based project to Typescript 
- Transform modules (see #231) 
- Generate documentation examples 

### References

#231

**Comment by JayDoubleu** [comment]
+1 for python

**Comment by jsteinich** [comment]
Using https://github.com/tmccombs/hcl2json packaged with https://github.com/sanathkr/go-npm might provide an easier path for parsing HCL

**Comment by skorfmann** [comment]
> Using https://github.com/tmccombs/hcl2json packaged with https://github.com/sanathkr/go-npm might provide an easier path for parsing HCL

There's some early work going on [here](https://github.com/iann0036/hcl2cdktf)

**Comment by DanielMSchmidt** [comment]
I think sub-steps here could be:

- [ ] Generating TS code via `cat main.tf | cdktf tf2cdk > main.ts`
- [ ] Use [Rosetta](https://www.npmjs.com/package/jsii-rosetta) internally to allow `--language=<java,go,python,c#>`
- [ ] Create vscode "Paste as CDK" command
