### ISSUE TITLE
Provider for arbitrary programmatic resources

### ISSUE THREAD

**Issue by alethenorio** [hashicorp/terraform-cdk#2327]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When dealing with resources for which there are no providers today, the `null_resource` is quite handy but maps directly to executing a binary.

The Terraform CDK opens up possibilities for executing actual code instead of calling a binary.

A example here would be using the Google Cloud SDK for Go to create a Google Cloud resource which does not yet have support in the provider without requiring the `gcloud` cli to be installed in the host machine. Another would be using an SDK for some arbitrary service which does not have a CLI without having to need to setup and maintain a whole terraform provider for it.

Could we have a provider (or maybe a resource in the `null` provider) which allows for this possibility?

I am thinking that use of interfaces and closures could come in handy for this purpose with maybe the same setup of triggers as the null resource has?

**Comment by ansgarm** [comment]
Hi @alethenorio 👋
Thanks for raising this! Would you say your use-case is covered in https://github.com/hashicorp/terraform-cdk/issues/661?

**Comment by alethenorio** [comment]
Read the issue and I think it does very much. I'll go thumbs up that one and close this. Thanks for pointing it out. I searched the issues a bit but likely used the wrong search words :)
