### ISSUE TITLE
Support HCL null 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#233]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I read up on HCL2 and [null](https://www.terraform.io/docs/configuration/expressions.html#types-and-values) is technically something we should support. However, not sure what the impact is and if it's applicable to all attributes. There's a bit more research required. 

This would support something like this:

```ts
new FooBar(this, "baz", {
  attribute: null
})
```

At the moment it's possible like this:

```ts
const a = new FooBar(this, "baz", {})

a.addOverride('attribute', null)
```
### References

https://github.com/hashicorp/terraform-cdk/issues/223

**Comment by chuckyz** [comment]
Could TFCDK simply utilize overloading instead of using nulls?

**Comment by skorfmann** [comment]
Could you provide an example?

**Comment by DanielMSchmidt** [comment]
Hey there, this issue has been unanswered quite a while (the `waiting-on-answer` label tells me we wait for feedback here) so I will be closing this for now. If there is new information let me know and I will reopen the issue again 👍
