### ISSUE TITLE
`mvn install` invoked by `provider add` fails if Java code has errors due to being work in progress

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-cdk#2336]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf</artifactId>
      <version>0.14.1</version>
    </dependency>
```

node `v18.12.1`
npm `8.19.2`

I think all other versions are in the debug output below.

### Debug Output

```
$ JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ../node_modules/.bin/cdktf provider add hashicorp/external
Checking whether pre-built provider exists for the following constraints:
  provider: external
  version : latest
  language: java
  cdktf   : 0.14.1

Found pre-built provider.
Adding com.hashicorp.cdktf-provider-external @ 4.0.0 to pom.xml
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/home/andrew/temp/ren/bread/deploy/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:432:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5)
Collecting Debug Information...
/home/andrew/temp/ren/bread/deploy/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/home/andrew/temp/ren/bread/deploy/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:432:933)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1091:16)
    at ChildProcess._handle.onexit (node:internal/child_process:302:5) {
  stderr: ''
}

Node.js v18.12.1
```

### Expected Behavior

Provider add to complete with no errors.

### Actual Behavior

It aborted with the above error, however the dependency was added to `pom.xml` so I'm not sure where it failed.

If it's just a spurious error it's only confusing, but I'm worried I might run into other trouble down the line.

### Steps to Reproduce

Run the command in the above snippet.

**Comment by ansgarm** [comment]
Hi @andrewbaxter 👋

After adding the pre-built provider package to the `pom.xml`, the cdktf-cli tries to run a `mvn install`:
https://github.com/hashicorp/terraform-cdk/blob/217b7398fcc470d618f16f1095c3a88f69d6baeb/packages/@cdktf/cli-core/src/lib/dependencies/package-manager.ts#L543

Because I saw that you defined the `JAVA_HOME` variable as part of your command: Is `mvn` available in the shell that you invoked the `provider add` command in?

**Comment by andrewbaxter** [comment]
Yeah, `mvn` runs fine.

I just straced it to see if I could get more output:
```
[pid 3116676] write(1<UNIX-STREAM:[94882573->94882572]>, "[ERROR] /home/...mysource.../Main.java:[61,74] ';' expected", 101 <unfinished ...>
```
It looks like maven may be writing the error to stdout?

So cdktf seems to be trying to compile my java code, which isn't in a compilable state at the moment.  I think I was trying to autocomplete the provider when I realized it wasn't installed, and left the statement half completed.

**Comment by andrewbaxter** [comment]
Yeah, commenting out the partially written code allows the provider to be added.

**Comment by ansgarm** [comment]
Ah, interesting! Maybe there is some kind of flag we can pass to Maven so Maven only does the `install` but does not attempt to `compile/build`? Or maybe some other command instead of `install`? 🤔

**Comment by andrewbaxter** [comment]
I think just adding it to `pom.xml` should be enough... `mvn install` is only required for making local code available to other projects that don't include the source in their build, which isn't the case here (I think, although I don't really know what happens during provider add).

And thanks again for looking into this!

**Comment by ansgarm** [comment]
Good to know! We probably fell for the similarity to the `yarn install` command with this one 😄 It seems like `mvn dependency:resolve` could be an alternative that would only fetch the dependency without going further.

**Comment by jsteinich** [comment]
I do think that for local providers there is value in compiling them as part of running `provider add` to ensure they are generated correctly. This would then be a difference between pre-built vs local which is worth considering if that difference is acceptable. Seems fine to me.

**Comment by andrewbaxter** [comment]
That's a good point, but as long as it's part of the same maven module whether it compiles or not is a crapshoot so it would be impossible to assert on.

Maybe the local providers could be added as child maven modules (or something like that, it might require more project restructuring) rather than as part of the same module?

I'd like to see 3rd party modules get pre-built as well, either as part of the release process or something on Hashicorp's end.  That way it could be evaluated earlier and I think it would make installing and updating easier (could be done with the normal workflows of your CDK language of choice).

Re `dependency:resolve`, just in case it wasn't clear, just adding the dep to `pom.xml` will cause it to be automatically fetched the next time maven is run so the only reason to do `dependency:resolve` would be to identify issues earlier.

**Comment by DanielMSchmidt** [comment]
We are moving overall to gradle, hopefully it's not an issue there :)
