### ISSUE TITLE
Variable names clobbered, unusable

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-cdk#2341]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Variables

### Expected Behavior

I should be able to provide a variable `aws_secret_key` which will be used by my stack.

### Actual Behavior

1. The variable `aws_secret_key` is ignored (I spent a while trying to figure out why `-var` wasn't working, `-var-file`, etc)
2. The actual variable it looks for is named `localdev_awssecretkey_AFAB001C`

### Steps to Reproduce

With the variable defined as (Java):
```
    final TerraformVariable awsSecretKey =
        new TerraformVariable(
            scope,
            "aws_secret_key",
            TerraformVariableConfig.builder()
                .type("string")
                .sensitive(true)
                .nullable(false)
                .build());
```

**Comment by DanielMSchmidt** [comment]
Are these nested in constructs? [We recommend to keep you variables at the top-level of your stack](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/best-practices#read-secrets-with-terraform-variables)

**Comment by ansgarm** [comment]
Hi @andrewbaxter!

In #2341 you stated that you don't use the CDKTF CLI, which brings me to the suspicion that the feature flags from the `cdktf.json` config might not get applied. Especially the `excludeStackIdFromLogicalIds` one. Without that flag you'll end up with that hash in the construct id and respectively in the Terraform output name causing the issue you observed.

This issue comment has a workaround for this: https://github.com/hashicorp/terraform-cdk/issues/798#issuecomment-1007447363

**Comment by andrewbaxter** [comment]
Yeah, AFAIK they were top level (scope = stack here).

Ah yes, that sounds like the issue.  I ran `terraform` from within the stack directory, but the `cdktf.json` file is several levels above that.  I'll try that workaround out! And close this in favor of #798 .

Thanks!

**Comment by andrewbaxter** [comment]
FWIW I ended up doing
```
    app.getNode().setContext("excludeStackIdFromLogicalIds", "true");
    app.getNode().setContext("allowSepCharsInLogicalIds", "true");
```
after trying to figure out how that env var is passed through to the CDK code by the CLI (and failing).

This seems to have worked great.
