### ISSUE TITLE
Variables aren't supported, contradictory documentation

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-cdk#2342]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Issue

The CDK [docs on variables](https://developer.hashicorp.com/terraform/cdktf/concepts/variables-and-outputs) currently:
1. Recommend not to use variables as though it's a choice -- this is misleading, variables are not supported A. by the cli or B. if you skip the cli and use terraform directly (due to #2341).  Furthermore, this is dangerous because people are probably using them for secrets and the recommended workarounds (env vars) will embed that in the generated terraform code
2. Immediately after that, contradicts itself and recommends to use variables

I'd actually prefer to limit my usage of the cdk cli as much as possible (it's an extra language and set of dependencies I need to manage, and that get in the way of the other languages and dependencies I'm using a la #1697, and an extra layer between me and the errors generated by my cdk code), so I'd request
1. Updating the documentation to clearly state variables aren't supported, and suggest using terraform directly for plan/deploy
2. Resolving #2341

**Comment by ansgarm** [comment]
Hi @andrewbaxter 👋

Thank you for reporting that contradiction in there. We should make it more clear in which cases we recommend using Terraform variables and in which we don't. Maybe @laurapacilio has some ideas how to adjust those sections you referenced to reflect that.

We share your assessment regarding secrets, which is why we have the yellow warning section in the docs you linked, which states:
> Important: The synthesized Terraform configuration will contain any values that you pass directly to CDKTF constructs. This includes credentials and any other sensitive data provided as input for the cdktf application. If you plan to commit the generated cdk.tf.json to version control, use [input variables](https://developer.hashicorp.com/terraform/cdktf/concepts/variables-and-outputs#input-variables) for secrets instead.

Do you have a suggestion that could make the danger of using secrets more clear to readers?

The CDKTF CLI does support setting Terraform variables [by using `TF_VAR_` environment variables](https://developer.hashicorp.com/terraform/language/values/variables#environment-variables) and I do have a suspicion why you are running into #2341 – but I'll share it over there.

**Comment by andrewbaxter** [comment]
Thanks, I was unaware of the `TF_VAR_` method for setting variables!

Maybe this would be a good solution:

1. Remove the suggestion to generate variables in CDK code.  It sounds dangerous, and I think people are smart enough that if they have a real reason for needing to do it they can figure out how to do it -- that's why they're using a programming language of their choice instead of terraform syntax.
2. Change the section that says you may use environment variables to either state `with the CDK CLI the only way to pass variables is via environment variables` to clarify that the methods in the linked Terraform documentation do not work, or else repeat the information in the Terraform documentation omitting the stuff on `-var` or `-var-file` (and other irrelevant parts for CDK).

I think having an example of the CLI-side of passing variables would be immensely helpful here, right now only the code-side of things is shown.

FWIW I didn't try `terraform.tfvars` + other directory files because I didn't know which directory those should go in and if it failed it seemed like it would be difficult to debug.

**Comment by laurapacilio** [comment]
Hi @andrewbaxter Thank you so much for the docs feedback - we really appreciate it!

I'll work with @ansgarm to put up a fix so this is clearer for you and other users :)

**Comment by DanielMSchmidt** [comment]
Closed by #2468
