### ISSUE TITLE
Make Terraform CDK and Terraform interoperable (without the CDKTF CLI)

### ISSUE THREAD

**Issue by alethenorio** [hashicorp/terraform-cdk#2344]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When you write Terraform CDK code (personally only used Go), the main function runs `Synth()` at the end which generates a `cdk.tf.json`. This json can be used by both terraform to `plan` and `apply` and also by the cdktf cli to `diff` and `deploy`.

However they cannot be used independently.

#### Consider the following scenario:

1. `go run .` (Synth)
2. `terraform init` (From inside the folder which contains `cdk.tf.json`)
3. `terraform plan` (From inside the folder which contains `cdk.tf.json`)
4. `cdktf diff`
5. `terraform plan` (From inside the folder which contains `cdk.tf.json`)

Step 3 and Step 4 are going to generate completely different resource names (and therefore different diff/plan) however Step 4 and Step 5 are going to generate the same diff/plan

This makes it not possible to use the Terraform CLI without the CDKTF CLI as well.

It would be very nice to be able to write terraform CDK code and not necessarily have to rely on the cdktf cli (which came as a surprise to me as I thought they were interoperable) which would avoid dependencies in Node, possibilities to use community tooling built around Terraform, json output and a lot more.

### References

Here's a simple example that reproduces this

```go
package main

import (
	"github.com/aws/jsii-runtime-go"
	"github.com/cdktf/cdktf-provider-null-go/null/v4/provider"
	"github.com/cdktf/cdktf-provider-null-go/null/v4/resource"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)

func main() {
	app := cdktf.NewApp(nil)

	stack := cdktf.NewTerraformStack(app, jsii.String("my-stack"))

	provider.NewNullProvider(stack, jsii.String("null_provider"), &provider.NullProviderConfig{})

	resource.NewResource(stack, jsii.String("dummy"), &resource.ResourceConfig{})

	app.Synth()
}
```

On step 3 we get
![image](https://user-images.githubusercontent.com/2749771/203836671-8b40f1ca-b83b-4386-836e-9d60d5ed2317.png)

On step 4 we get
![image](https://user-images.githubusercontent.com/2749771/203836809-816dbe68-0383-4c27-aa6f-dbf7a005257d.png)

On Step 5 we get
![image](https://user-images.githubusercontent.com/2749771/203836753-1eb0bd83-3a8e-46fd-b215-1f93da8ba893.png)

**Comment by ansgarm** [comment]
Hi @alethenorio 👋
It seems like you are running into the same problem as reported in #2341

**Comment by alethenorio** [comment]
Thank for the heads up @ansgarm 

The issue is indeed solved by the following workaround

```go
package main

import (
	"github.com/aws/jsii-runtime-go"
	"github.com/cdktf/cdktf-provider-null-go/null/v4/provider"
	"github.com/cdktf/cdktf-provider-null-go/null/v4/resource"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)

func main() {
	app := cdktf.NewApp(nil)

	// Configure CDKTF through an environment variable so we don't have
	// a dependency on the CDKTF cli.
	app.Node().SetContext(jsii.String("excludeStackIdFromLogicalIds"), "true")
	app.Node().SetContext(jsii.String("allowSepCharsInLogicalIds"), "true")

	stack := cdktf.NewTerraformStack(app, jsii.String("my-stack"))

	provider.NewNullProvider(stack, jsii.String("null_provider"), &provider.NullProviderConfig{})

	resource.NewResource(stack, jsii.String("dummy"), &resource.ResourceConfig{})

	app.Synth()
}
```

More specifically I think https://github.com/hashicorp/terraform-cdk/issues/798#issuecomment-1007447363 is more relevant than this issue so I am closing it.

Thank you
