### ISSUE TITLE
Provider upgrade doesn't work on non-pre-built providers (Java)

### ISSUE THREAD

**Issue by andrewbaxter** [hashicorp/terraform-cdk#2345]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf</artifactId>
      <version>0.14.1</version>
    </dependency>
```

node `v18.12.1`
npm `8.19.2`

### Debug Output

```
$ JAVA_HOME=/usr/lib/jvm/java-11-openjdk/ ../node_modules/.bin/cdktf provider upgrade andrewbaxter/stripe
Upgrading andrewbaxter/stripe...
[2022-11-25T04:04:41.890] [INFO] default - Checking if andrewbaxter/stripe is installed...
Usage Error: Could not find pre-built provider for registry.terraform.io/andrewbaxter/stripe
```

### Expected Behavior

The version should have been increased from 0.0.11 to 0.0.12

### Actual Behavior

Nothing changed.

### Steps to Reproduce

This has happened for every version, so I imagine reproduction is straightforward:
1. Create java project
2. Add custom provider
3. Release new version of custom provider
4. Run above command

### Important Factoids

I also tried re-running `provider add` which also did nothing.

I tried running `provider add` with a version (`@~0.0.12`) which appeared to upgrade, but `terraform` continued to use version 0.0.11.

To work around this I've had to manually delete all the directories: `imports` `resources` and edit the various json files containing references to the provider, then re-install.  After that and re-synthing `teraform` prompted me to do `init -upgrade`.

FWIW a command to delete added providers would also be extremely helpful

### References

**Comment by ansgarm** [comment]
Hi 👋 Thanks for reporting this.

Specifically, it seems that `upgrade` fails for providers that are not available as pre-built providers (which is a bug!).

Minimal reproduction example:
```
cdktf init
cdktf provider add "Azure/azapi@1.0.0"
cdktf provider upgrade Azure/azapi
```
fails with
```
Usage Error: Could not find pre-built provider for registry.terraform.io/Azure/azapi
```

The error stems from this line, where we e.g. could catch the exception that is thrown:
https://github.com/hashicorp/terraform-cdk/blob/217b7398fcc470d618f16f1095c3a88f69d6baeb/packages/@cdktf/cli-core/src/lib/dependencies/dependency-manager.ts#L170
