### ISSUE TITLE
Remove feature flag support in `cdktf.json`

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2349]
Now that we announced the deprecation of the feature flags, we can invert the behavior and remove them.

Former issue content:
> Remove the feature flags in the `cdktf.json` file as they cause inconsistencies when running `cdktf synth` vs. running the CDKTF program directly.
> Related to #798

**Comment by jsteinich** [comment]
We should make the current ones default behavior.

We'll still want feature flags in the future and there are certainly good reasons to have them in `cdktf.json`. We should be able to make it work the same way regardless of how it is ran.

**Comment by ansgarm** [comment]
I agree with making the current ones default behavior 👍

Regarding keeping them in the `cdktf.json`, the only reason I can think of would be behavior changes that need to be reflected in both the cdktf-cli and the cdktf core library 🤔
On the opposite: We didn't need the feature flags since quite some time – so I'm a bit torn here.

(Personally, I'd be fine with only deprecating and removing the _current_ feature flags in 0.15 / 0.16 while keeping the feature-flags feature 😄)

**Comment by DanielMSchmidt** [comment]
I'd vote for deprecation, if we need them ever again we can re-add them, but I would propose to add them in a way that running cdktf through synth vs executing the program directly behaves the same. The way it currently is causes some confusion.

**Comment by mutahhir** [comment]
Deprecation was already announced in 0.15.

This issue will be closed when we remove support for the existing feature flags that were already announced as deprecated.
