### ISSUE TITLE
Keys of user supplied input objects should keep character casing

### ISSUE THREAD

**Issue by exocom** [hashicorp/terraform-cdk#235]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript 0.0.12

### Affected Resource(s)

ApiGatewayMethodConfig.requestParameters

### Debug Output

https://gist.github.com/exocom/611c59e13542b90fa378eccd5647b121
### Expected Behavior

The prop name should not have been modified resulting in a plan with `"method.request.header.x-api-key" = true`

```hcl
      + request_parameters   = {
          + "method.request.header.x-api-key" = true
        }
```

### Actual Behavior

The prop name is lowercase with "." & "-" replaced with "_". IE it has been normalized. `"method_request_header_x_api_key"`

```hcl
      + request_parameters   = {
          + "method_request_header_x_api_key" = true
        }
```

### Steps to Reproduce

```typescript
new ApiGatewayMethod(this, `${id}_agm`, {
  ...
  requestParameters: {'method.request.header.x-api-key': true}
});
```
### Important Factoids

Having dots/periods (.) in prop name works in plain .tf files. See example on [official docs](https://www.terraform.io/docs/providers/aws/r/api_gateway_method.html)

```hcl
 request_parameters = {
    "method.request.path.proxy" = true
  }
```

**Comment by skorfmann** [comment]
Thanks for raising this issue. We had a similar thing with #136, where we took a shortcut and did a `tags` specific quick fix. But this is actually quite a big issue, which we'll have to address now.

The problem is, that we perform `keysToSnakeCase` during `synth` on all attributes. This issue here affects all user provided dictionaries (`tags` is the majority, but there are hundreds of other occasions just in the `AWS` provider). 

I'll see if we can easily identify and skip these attributes somehow.

**Comment by skorfmann** [comment]
Looked into this, here's a quick summary:

Identifying these cases just by type information won't be working at runtime as it seems. I think we'll need an explicit mapping which we generate alongside the classes.

There are two general directions for this:

### 1. JSON Schema 

Perhaps a JSON schema could be generated which is used as guardrail during synth.

### 2. Customized Mapping

The AWS CDK is doing a [customized mapping](https://github.com/aws/aws-cdk/blob/d28752513175c94fb2bc4da43374d7f2e66d6550/tools/cfn2ts/lib/codegen.ts#L407-L506) as well. This could turn out to be useful, as it's potentially opening up other use-cases.

--- 

I'm sort of leaning towards the customized mapping. Perhaps this could be implemented in a way to address other open issues as well (#25, #172). 

Either way, that's a significant chunk of work to do. However, I feel like this shouldn't be postponed.

**Comment by skorfmann** [comment]
@exocom FYI: You can workaround this with [escape hatches](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/escape-hatch.md) for now. 

This would look like this:

```ts
const apiMethod = new ApiGatewayMethod(this, `agm`, {
      authorization: "NONE",
      httpMethod: "GET",
      resourceId: 'Foo',
      restApiId: 'bar',
    });

    apiMethod.addOverride('request_parameters', {'method.request.header.x-api-key': true})
```

and synthesizes to this:

```json
    "aws_api_gateway_method": {
      "helloterra_agm_50C0F401": {
        "authorization": "NONE",
        "http_method": "GET",
        "request_parameters": {
          "method.request.header.x-api-key": true
        },
        "resource_id": "Foo",
        "rest_api_id": "bar"        
      }
    },

```

**Comment by exocom** [comment]
@skorfmann Nice workaround. I'm back on track thank you!

**Comment by kaisellgren** [comment]
For future reference to others: if you're using something like `gcp.CloudRunService` and you need to add inside an existing array you can do this:

```
cloudRunService.addOverride('template.0.metadata', [
  { annotations: { 'run.googleapis.com/cloudsql-instances': 'project-id:europe-north1:instance-name' } },
])
```
Output:

```
    "google_cloud_run_service": {
      "***_ABA7A841": {
        ...
        "template": [
          {
            "spec": [
              {
                 ...
              }
            ],
            "metadata": [
              {
                "annotations": {
                  "run.googleapis.com/cloudsql-instances": "project-id:europe-north1:instance-name"
                }
              }
            ]
          }
        ],
```

It's not documented, but you can access array items via syntax `foo.0.bar` or `foo.2.bar`, etc.

**Comment by skorfmann** [comment]
That's being worked on by @jsteinich
