### ISSUE TITLE
Pre-built provider url in Readme not correct

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#2354]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Provider / Resource(s)

Snowflake provider is one example

### Expected Behavior

Readme correctly links to terraform provider, e.g. https://github.com/Snowflake-Labs/terraform-provider-snowflake

### Actual Behavior

Has an invalid link, e.g. https://github.com/terraform-providers/terraform-provider-snowflake

### Important Factoids

Registry metadata does appear to be fairly easily available, e.g. `curl 'https://registry.terraform.io/v1/providers/snowflake-labs/snowflake' | jq ".namespace"`.
Really an issue for https://github.com/cdktf/cdktf-provider-project, but likely to get more visibility here.

### References

- https://github.com/cdktf/cdktf-provider-snowflake/pull/242

**Comment by xiehan** [comment]
Fixed in cdktf/cdktf-provider-project#286 - hat-tip to @Maed223 for his work on this!
