### ISSUE TITLE
`vsphere` provider: Username and Password Required even when using Environment Variables.

### ISSUE THREAD

**Issue by mxrss2** [hashicorp/terraform-cdk#2374]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

TypeScript

### Affected Provider / Resource(s)

VSphere Provider {username and password are required}

### Expected Behavior

UserName and password should not be mandatory as it can be feed via the environment variables. Marking them as required or not IResolveable breaks the way that the terraform provider is expected to work. 

### Actual Behavior

Can not run a compile as the items are marked as string without the `?` denoting it be optional. You can however edit the code in the prodivder to do this. 

### Steps to Reproduce
```
new VsphereProvider(this, "test1", { allowUnverifiedSsl: true})
```

### References

- #0000

**Comment by DanielMSchmidt** [comment]
I think this is a problem upstream in the provider, they [mark these fields as required](https://github.com/hashicorp/terraform-provider-vsphere/blob/main/vsphere/provider.go#LL21) so we assume it is required and require input from you. One hack you could try is to generate a Token value that resolves to undefined, but returns a string value. The typesystem should be happy then and at runtime it's the same as not passing anything. So e.g.

```ts
new VsphereProvider(this, "vsphere", {
  user: Token.asString(undefined),
  password: Token.asString(undefined),
});
```

**Comment by mxrss2** [comment]
That works Awesome! I will close this.
