### ISSUE TITLE
`azurerm` provider: Bug in class IothubEndpoint in c#

### ISSUE THREAD

**Issue by asaf-horvitzsg** [hashicorp/terraform-cdk#2388]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

c# package - HashiCorp.Cdktf.Providers.Azurerm" Version="4.0.2"

in class IothubEndpoint there are several members that are declared as mandatory in the class although in the documentation they are optional, if using AuthenticationType = "keyBased", which is what I am using

the members are:
EndpointUri  
EntityPath
IdentityId

I cant run "cdktf deploy" since I get error that I need these params, but I cant declare them since I am not using the relevant AuthenticationType

![error5](https://user-images.githubusercontent.com/118113899/205637038-4d18635d-2444-4768-805f-dcf472b6042d.png)

Please fix it ASAP since I cant deploy to azure

**Comment by ansgarm** [comment]
Hi @asaf-horvitzsg  👋
The CDKTF provider bindings are based on the Azurerm provider schema. So we'd need a fix in the [upstream repository](https://github.com/hashicorp/terraform-provider-azurerm) to fix this inconsistency.

That said, you could try working around this problem by passing `Token.AsString(null)` to the required attributes.

**Comment by asaf-horvitzsg** [comment]
Hi @ansgarm 

I have updated the issue and add an image that shows the response from the "cdftk deploy"

I also tried your workaround and got the same response.

Note that I am using the "authentication_type": "keyBased",

I have moved from HCL to cdk, and in HCL it worked...

adding the code for the IOTHUB:

`

            Iothub iothub = new Iothub(this, "iothub", new IothubConfig {
                Name                = "solargik",
                ResourceGroupName = rg.Name,
                Location            = rg.Location,

                Sku  = new IothubSku {
                    Name     = "S1",
                    Capacity = 1
                },
                Endpoint = new IothubEndpoint[] {
                    new IothubEndpoint {
                    Type                       = "AzureIotHub.EventHub",
                    Name                       = "RulesProcessorEventHub",
                    ConnectionString = mcsmoduletwindatasendpolicy.PrimaryConnectionString,
                    AuthenticationType = "keyBased", // default
                    // EndpointUri = Token.AsString(null) , // required but not needed 
                    // EntityPath = Token.AsString(null) ,
                    // IdentityId = Token.AsString(null) ,
                    },
                },
                Route = new IothubRoute[] {new IothubRoute {
                    Name           = "mcs-site-status-messages",
                    Source         = "DeviceMessages",
                    Condition      = "$body.SourceType = SiteStatus",
                    EndpointNames = new String[] {"RulesProcessorEventHub"},
                    Enabled        = true,

                    },
                },
                Enrichment  = new IothubEnrichment[] {new IothubEnrichment{
                    Key            = "site_id",
                    Value          = "$twin.tags.site_id",
                    EndpointNames = new String[] {"RulesProcessorEventHub"}
                    },
                },
            }
        );
`

**Comment by asaf-horvitzsg** [comment]
hi @ansgarm

In the HCL the code looked like this:

`

    endpoint {
       type              = "AzureIotHub.EventHub"
       name              = "RulesProcessorEventHub"
       connection_string = azurerm_eventhub_authorization_rule.mcsmoduletwindatasendpolicy.primary_connection_string
    }
` 

got the same error when set the Token.NullValue() in c# 

Do you have another suggestion for workarounds ?

It is a bug in the cdktf that is not allowing endpoints without the optional parameters above - it doesn't come from terraform

**Comment by asaf-horvitzsg** [comment]
hi @ansgarm

can we chat by email ? it will be much easier

thanks

**Comment by asaf-horvitzsg** [comment]
> > It is a bug in the cdktf that is not allowing endpoints without the optional parameters above - it doesn't come from terraform
> 
> Could you share the error you are seeing that comes from the CDKTF? Or alternatively share a minimal reproducible example? I only know about the error from your screenshot and that is output that originates from the Terraform CLI (which is invoked by the cdktf-cli when you run `cdktf deploy`).

@ansgarm 

this is the output of cdktf deploy, for some reason cdktf expects that the mention params will be with values.

this is a cdktf bug, not terraform  

![error5](https://user-images.githubusercontent.com/118113899/205708900-7b7e5359-1c46-4159-83ef-951719b03749.png)

**Comment by jsteinich** [comment]
Likely the resource added some attributes and we just need to add them [here](https://github.com/hashicorp/terraform-cdk/blob/dab85f050d3534e1e81e1fc509b4960441c3de3b/packages/%40cdktf/provider-generator/lib/get/generator/custom-defaults.ts#L281). See https://github.com/hashicorp/terraform-cdk/issues/234 for more context.
