### ISSUE TITLE
Add more non-technical information to CONTRIBUTING.md

### ISSUE THREAD

**Issue by xiehan** [hashicorp/terraform-cdk#2416]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was chatting with one of HashiCorp's community managers last night and he pointed out that the contents of our `CONTRIBUTING.md` file are too technical, or rather, the info in there is fine, but we should also include a higher-level layer that talks more about our process of best practices for submitting issues, how we intend to work with community feature requests, where to ask questions, etc.

### References

Here are examples of a few other open source projects we can draw inspiration from:

- https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md
- https://github.com/hashicorp/vault/blob/main/CONTRIBUTING.md
- https://github.com/angular/angular/blob/main/CONTRIBUTING.md
- https://reactjs.org/docs/how-to-contribute.html
- https://github.com/php/php-src/blob/master/CONTRIBUTING.md

**Comment by kination** [comment]
Will it be okay me to take a look on this? (if there's progress already on-going, please let me know)

**Comment by ansgarm** [comment]
Hi @kination 👋
Sure! Feel free to submit a PR that improves our `CONTRIBUTING.md` 😊

**Comment by kination** [comment]
Got it. Thanks @ansgarm

**Comment by Maed223** [comment]
Hey @kination! We had a slight miscommunication on the team. I currently have a draft PR up that is providing some updates on our CONTRIBUTING doc. Even so, I'd love to hear your input. Please feel free to comment on the PR with any material you feel is missing  or various other adjustments you see fit 😁

**Comment by kination** [comment]
@Maed223 oh, there are. Thanks for quick notice 🙏 .
@xiehan @ansgarm I think you can review his PR above.
