### ISSUE TITLE
Terraform CLI waits for variable input forever if variables are missing

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2425]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

<img width="959" alt="image" src="https://user-images.githubusercontent.com/1112056/207833869-3e109dae-28f2-4297-b6d7-630316a4f87b.png">

As of #1955 we now invoke Terraform interactively for applying, which causes it to ask for input (e.g. for variables) and to wait basically forever. So the UX to users that don't know Terraform and this output will be confusing.
We have two main options here:
1. Detect when TF asks for input (which we don't support) and crash with an error message that users need to supply variables via TF_VAR_ env variables.
2. Support passing various inputs to the TF CLI (basically extending the "wait for approval" logic for different kinds of questions).

Option 1 is simpler and possibly a good first stepping stone (as detecting those questions is also required for option 2). I'd propose to start with option 1 and then create a follow-up issue to implement option 2 at some point.

**Comment by DanielMSchmidt** [comment]
Same problem with abort, if terraform is killed it sends

```
Do you want to cancel the remote operation?
  Only 'yes' will be accepted to cancel.

  Enter a value: yes
```
