### ISSUE TITLE
Aborting cdktf-cli does not stop the plan / apply currently running

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2429]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

The plan / aplpy run should be cancelled when cdktf-cli is aborted

### Actual Behavior

The plan runs to the end, but the apply does not start. If the apply has already started the apply runs until the end

### Steps to Reproduce

1. Create a cdktf program using TFC
2. Add a resource that takes some time, e.g.

```ts
import { NullProvider } from "./.gen/providers/null/provider";
import { Resource } from "./.gen/providers/null/resource";

// ...

new NullProvider(this, "null", {});

new Resource(this, "test4", {
  provisioners: [
    {
      type: "local-exec",
      command: "sleep 100 && echo 'hello world'",
    },
  ],
});
```

3. Run `cdktf deploy --auto-approve` and abort after the plan / apply has started

### References

- #0000

**Comment by jsteinich** [comment]
This should ideally forward to the terraform cli so that semantics match as much as possible. See https://discuss.hashicorp.com/t/cancel-terraform-apply-gracefully-to-immediately-do-a-terraform-destroy/45722/2 for a bit more info on how it works.

**Comment by DanielMSchmidt** [comment]
@jsteinich it does, we send the ctrl+c signal to the terraform process and wait for TF to clean up.

It seems like we solved this in the meantime, closing the issue :)
