### ISSUE TITLE
toHaveProviderWithProperties / toHaveProvider are not available when writing unit tests

### ISSUE THREAD

**Issue by kshlomi** [hashicorp/terraform-cdk#2436]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf@0.14.3 
typescript@4.9.3

### Affected Resource(s)

Unit tests

### Expected & Actual Behavior
According to documentation , the following code snippet should properly compile and run 
```
it('Terraform is generated properly', () => {
        expect(stack).toHaveProviderWithProperties(AwsProvider, {
             assume_role: "arn:aws:iam::1234:role/admin"
         })
})
```
However `toHaveProviderWithProperties` is not exposed in Jest adapters:
https://github.com/hashicorp/terraform-cdk/blob/c837a9de1306a6f3cfbd751f56a1a346386d68c5/packages/cdktf/lib/testing/adapters/jest.ts#L72

**Comment by jsteinich** [comment]
Until this gets added, you could try using the `Testing` class directly (`Testing.toHaveProviderWithProperties`).

**Comment by zmully** [comment]
I had a similar problem maybe? `TypeError: expect(...).toHaveResourceWithProperties is not a function`  and fixed it with `setup.js`:

```
const cdktf = require('cdktf');
cdktf.Testing.setupJest();
```

Then made sure that it was loaded by Jest in my `.projenrc.ts`:
```
  jestOptions: {
    jestConfig: {
      setupFilesAfterEnv: ['<rootDir>/setup.js'],
    },
  },

``

**Comment by kshlomi** [comment]
@zmully note this bug is about `toHaveProviderWithProperties` and not `toHaveResourceWithProperties`
