### ISSUE TITLE
cdktf convert not working for some gke files after export

### ISSUE THREAD

**Issue by mewc** [hashicorp/terraform-cdk#2442]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.14.3

### Affected Resource(s)

GKE hcl files exported by bulk-export

I suppose this is either a hashicorp problem with the `convert`, or a google problem with their `--resource-format=terraform` export..

not sure, i just ran this to get the hcl files:

```
gcloud beta resource-config bulk-export \
  --path=entire-tf-output \
  --project=org-123\
  --resource-format=terraform
```

and then ran a recursive cdktf convert after that (its working for hundreds of other files, just not many of these gke ones

`ComputeInstanceTemplate/australia-southeast1/gke-clus-od-pool-123` is the die the `bulk-export` put it in.

### Debug Output

this is one of the files that fail

```
resource "google_compute_firewall" "gke_cluster_123_all" {
  allow {
    protocol = "ah"
  }

  allow {
    protocol = "esp"
  }

  allow {
    protocol = "icmp"
  }

  allow {
    protocol = "sctp"
  }

  allow {
    protocol = "tcp"
  }

  allow {
    protocol = "udp"
  }

  direction     = "INGRESS"
  name          = "gke-cluster-123-all"
  network       = "https://www.googleapis.com/compute/v1/projects/.../global/networks/default"
  priority      = 1000
  project       = "org-123"
  source_ranges = ["10.0.0.0/14"]
  target_tags   = ["gke-cluster-123-node"]
}

-- terraform import google_compute_firewall.gke_cluster..._all projects/org-123/global/firewalls/...

```

and

```
Error: Internal Error: Error: Could not parse HCL, this means either that the HCL passed is invalid or that you found a bug. If the HCL seems valid, please file a bug under https://cdk.tf/bugs/new/convert
    at Object.Internal (/Users/mewc/.nvm/versions/node/v16.2.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:41856)
    at Object.MFr (/Users/mewc/.nvm/versions/node/v16.2.0/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:492:23695)
    at async mp.handleCommand (/Users/mewc/.nvm/versions/node/v16.2.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:33813)
    at async Object.B.handler (/Users/mewc/.nvm/versions/node/v16.2.0/lib/node_modules/cdktf-cli/bundle/bin/cdktf.js:53:29879) {
  language: 'typescript',
  __type: 'Internal'
}
```

### Expected Behavior

convert to .ts 

### Actual Behavior

errors

### Steps to Reproduce

copy the file above
run cdktf convert
???
done

### References

---

Hopefully this is of value 🙏🏻 The `convert` cli brought me here

**Comment by ansgarm** [comment]
Hi @mewc 👋

Did you run `cdktf convert` on that file including that last `-- terraform import ...` line? If yes, that is invalid HCL and you'd need to remove that line from the file first before `cdktf convert` can work with it.
