### ISSUE TITLE
`aws` provider: Incorrect type for `skipMetadataApiCheck` in AwsProviderConfig

### ISSUE THREAD

**Issue by micchickenburger** [hashicorp/terraform-cdk#2447]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

I'm using TypeScript.  Library versions:

```json
"@cdktf/provider-aws": "11.0.8",
"cdktf": "^0.14.3",
"cdktf-cli": "^0.14.3",
"constructs": "^10.1.196",
```

### Affected Provider / Resource(s)

`@cdktf/provider-aws/lib/provider/index.d.ts`:

```ts
import { Construct } from 'constructs';
import * as cdktf from 'cdktf';
export interface AwsProviderConfig {
    // ...
    /**
    * Skip the AWS Metadata API check. Used for AWS API implementations that do not have a metadata api endpoint.
    *
    * Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/aws#skip_metadata_api_check AwsProvider#skip_metadata_api_check}
    */
    readonly skipMetadataApiCheck?: string;
    // ...
}
```

### Expected Behavior

The type of `skipMetadataApiCheck` should be boolean.  See here:  https://registry.terraform.io/providers/hashicorp/aws/latest/docs#skip_metadata_api_check

### Actual Behavior

The type of `skipMetadataApiCheck` is string.

**Comment by ansgarm** [comment]
Hi @micchickenburger 👋

The bindings are generated based on the output from `terraform provider schema -json` which returns
```json
"skip_metadata_api_check": {
  "type": "string",
  "description": "Skip the AWS Metadata API check. Used for AWS API implementations that do not have a metadata api endpoint.",
  "description_kind": "plain",
  "optional": true
}
``` 
for the `skip_metadata_api_check` attribute. This is an upstream issue with the AWS Terraform Provider and happens for multiple attributes. One other similar issue is #2263.

You can workaround this by using `Token.asString(false)`.

**Comment by xiehan** [comment]
Since this is an upstream issue in the AWS provider and there is a reasonable workaround, I'm going to go ahead and close this.
