### ISSUE TITLE
"Using Iterators on Complex Types" documentation sample code does not work

### ISSUE THREAD

**Issue by cosminnicula** [hashicorp/terraform-cdk#2452]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version: 0.14.3
python version: 3.8.10
terraform modules: terraform-aws-modules/s3-bucket/aws@3.6.0

### Affected Resource(s)

When trying to use the Iterator on Complex Types in the example documented here https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-on-complex-types,  I get an error saying that "The given "for_each" argument value is unsuitable: "for_each" supports maps and sets of strings, but you have provided a set containing type object." - see gist below for the complete error message

### Debug Output

[https://gist.github.com/cosminnicula/e32ccabed695fb646aefa2cb6e1609c8](https://gist.github.com/cosminnicula/e32ccabed695fb646aefa2cb6e1609c8)

### Expected Behavior

The code should work as expected.

### Actual Behavior

An error pops out, saying that "The given "for_each" argument value is unsuitable: "for_each" supports maps and sets of strings, but you have provided a set containing type object."

### Steps to Reproduce

Initialize a minimal CDKTF project with Python including the "Using Iterators on Complex Types" sample code, then run `cdktf apply`.

### Important Factoids

N/A

### References

N/A

**Comment by cosminnicula** [comment]
Ok, after some heavy digging into CDKTF's source code and API Reference documentation, I finally made it work.
Just for reference, the original code looked like this (which obviously didn't work):

```
from imports.aws.s3_bucket import S3Bucket
from cdktf import TerraformIterator, TerraformVariable, TerraformLocal
        list = TerraformLocal(self, "my-list", [
            {
                "name": "website-static-files",
                "tags": {"app": "website"}
            },
            {
                "name": "images",
                "tags": {"app": "image-converter"}
            }
        ])

        iterator = TerraformIterator.from_list(
            list=list.as_list
        )

        s3Bucket = S3Bucket(self, "s3-bucket",
            for_each=iterator,
            bucket=iterator.get_string("name"),
            tags=iterator.get_map("tags")
        )
```

The first approach is to rearrange the list as a map and work with a MapTerraformIterator which extends TerraformIterator https://github.com/hashicorp/terraform-cdk/blob/20541785d05572af20974f4f19568a3540d0c220/packages/cdktf/lib/terraform-iterator.ts#L260

```
map = TerraformLocal(self, "my-map", {
    "website": {
        "name": "website-static-files",
        "tags": {"app": "website"}
    },
    "images": {
        "name": "images",
        "tags": {"app": "image-converter"}
    }
})

iterator = TerraformIterator.from_map(
    map=map.as_string_map
)

s3Bucket = S3Bucket(self, "s3-bucket",
    for_each=iterator,
    bucket=iterator.get_string("name"),
    tags=iterator.get_map("tags")
)
```

This approach is not ideal, especially if the `name` is guaranteed to be unique. For this particular case the `name` is unique, and the map could be restructured such that the `name` becomes the key of the object and can further be referenced through its getter `iterator.key`, like this:

```
map = TerraformLocal(self, "my-map", {
    "website-static-files": {
        "tags": {"app": "website"}
    },
    "images": {
        "tags": {"app": "image-converter"}
    }
})

iterator = TerraformIterator.from_map(
    map=map.as_string_map
)

s3Bucket = S3Bucket(self, "s3-bucket",
    for_each=iterator,
    bucket=iterator.key,
    tags=iterator.get_map("tags")
)
```

I have to admit that the documentation is not intuitive at all, in which case you have to jump into CDKTF's source code to better understand what's going on behind the scenes.

**Comment by mutahhir** [comment]
Thanks @cosminnicula for the issue and the explanation about a potential solution ❤️ . 

I apologise, I should've commented on the issue earlier, but I was digging into the codebase to see if there's an alternative solution to using maps. There can be, but it is non-trivial and would require more work on our part to support. 

For now, I've made a PR to update the example snippets, and it's the same approach you mentioned in the above comment.
