### ISSUE TITLE
No versions available for com.hashicorp:cdktf:jar:[0.12.2,0.14.0) within specified range

### ISSUE THREAD

**Issue by Jahadul-Rakib** [hashicorp/terraform-cdk#2458]
Language: Java 17 and Maven.

My running project giving issue from today unexpectedly whithout any change in may project. **CDKTF libriry version is 0.13.3 from Maven repository**.

**ERROR:** _**No versions available for com.hashicorp:cdktf:jar:[0.12.2,0.14.0) within specified range**_

when i try to build using maven then system tell me no version available. Here i giving my pom file,

```
   <dependencies>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf</artifactId>
            <version>0.13.3</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-local</artifactId>
            <version>3.0.11</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-null</artifactId>
            <version>3.0.11</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-tls</artifactId>
            <version>3.0.12</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-time</artifactId>
            <version>2.0.85</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-aws</artifactId>
            <version>10.0.10</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-digitalocean</artifactId>
            <version>3.0.12</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-google</artifactId>
            <version>3.0.16</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-azurerm</artifactId>
            <version>3.0.15</version>
        </dependency>
    </dependencies>
```
 
**I do not get any solution what is happened within 24 hours that my running project stop working.  please help me and giving me information whats the problem and how can i solve this....**

**Comment by DanielMSchmidt** [comment]
My first guess would be that you have a dependency on a pre-built provider that is not using the 0.13 version of CDKTF, did you add a new one lately? If you don't care too much about the specific provider versions being used you could remove all dependencies related to cdktf besides cdktf itself and run `cdktf provider add local null tls time aws digitalocean google azurerm`. This should give you the latest versions supported by your cdktf version.

**Comment by Jahadul-Rakib** [comment]
> My first guess would be that you have a dependency on a pre-built provider that is not using the 0.13 version of CDKTF, did you add a new one lately? If you don't care too much about the specific provider versions being used you could remove all dependencies related to cdktf besides cdktf itself and run `cdktf provider add local null tls time aws digitalocean google azurerm`. This should give you the latest versions supported by your cdktf version.

can you give me a sample, what you instruct me plz ?

**Comment by mutahhir** [comment]
I can see the same problem with other Java CDKTF projects on different versions. I'm trying to confirm it, but this is smelling like a maven issue.

**Comment by andreas-heatly** [comment]
@mu

> I can see the same problem with other Java CDKTF projects on different versions. I'm trying to confirm it, but this is smelling like a maven issue.

Yes - as I wrote above I believe that the maven-metadata.xml (https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/maven-metadata.xml) accidentally has been replaced by an old version, as it does not contain any release more recent than 0.9.0-pre.7 and that maven therefore cannot resolve version ranges properly.

**Comment by mutahhir** [comment]
Ahh, thanks for the explanation.

**Comment by dmb23** [comment]
Hi,

same issue here. I wonder what is the way forward? In the referenced issue some contact was made behind the scenes to Sonatype, then suddenly the issue was solved, but I don't know how or by whom?

- should this be somehow escalated to maven / sonatype ?
- should all users update the maven configuration to include the releases at https://hashicorp.oss.sonatype.org/content/repositories/releases/com/hashicorp/cdktf/maven-metadata.xml ?
- should we downgrade all our requirements to cdktf <= 0.9.0?

All of those do not sound great to me, and our production pipelines are down.

**Comment by andreas-heatly** [comment]
Another temporary workaround would be to exclude the dependency and explicitly pin a version yourself:
```xml
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf</artifactId>
            <version>0.14.3</version>
        </dependency>
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf-provider-aws</artifactId>
            <version>11.0.8</version>
            <exclusions>
                <exclusion>
                    <groupId>com.hashicorp</groupId>
                    <artifactId>cdktf</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
But it seems like a major issue, so *hopefully* someone in the project is working on it as we speak.

**Comment by mutahhir** [comment]
We're working on it. reached out on a couple of channels to the maven team, so hopefully we have a resolution soon.

**Comment by mutahhir** [comment]
The metadata file has been updated 🎉

**Comment by Jahadul-Rakib** [comment]
> The metadata file has been updated tada

Thank you so much sir
