### ISSUE TITLE
[ctrl] + [c] should work during Terraform Cloud init

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#246]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- all

### Affected Resource(s)

- CLI

### Expected Behavior

When trying to abort the init dialog for the Terraform Cloud with [ctrl] + [c] it should exit the program

### Actual Behavior

It's not exiting 

### Steps to Reproduce

Run `cdktf init --template typescript`

### Important Factoids

![Screenshot 2020-07-25 at 21 52 01](https://user-images.githubusercontent.com/136789/88465175-2ac84780-cec1-11ea-88fc-7ab159f100a1.png)

**Comment by DanielMSchmidt** [comment]
This works now 👍
