### ISSUE TITLE
'cdktf get' Cannot Import Local Modules Which Reference Other Modules That Use `../`

### ISSUE THREAD

**Issue by jhwbarlow** [hashicorp/terraform-cdk#2460]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
- cdktf 0.14.3
- Terraform v1.3.7
- Python 3.10.8

### Expected Behavior

Should be able to import modules which are outside the App directory in the file tree which themselves reference modules.

### Actual Behavior

Attempting to import such a module causes and error such as the following:
```
downloading and generating modules and providers...
╷
│ Error: Local module path escapes module package
│ 
│ The given source directory for module.register.module.constants would be
│ outside of its containing package
│ "file:///Users/jamesbarlow/repo/tf.modules/modules/register/v0".
│ Local source addresses starting with "../" must stay within the same
│ package that the calling module belongs to.
╵

╷
│ Error: Local module path escapes module package
│ 
│ The given source directory for module.register.module.constants would be
│ outside of its containing package
│ "file:///Users/jamesbarlow/repo/tf.modules/modules/register/v0".
│ Local source addresses starting with "../" must stay within the same
│ package that the calling module belongs to.
╵
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/Users/jamesbarlow/homebrew/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:45:2064)
    at Object.onceWrapper (node:events:628:26)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess.emit (node:domain:489:12)
    at maybeClose (node:internal/child_process:1098:16)
    at Socket.<anonymous> (node:internal/child_process:456:11)
    at Socket.emit (node:events:513:28)
    at Socket.emit (node:domain:489:12)
    at Pipe.<anonymous> (node:net:305:12)
```

This error appears to be coming from the Terraform CLI itself rather than cdktf, but this pattern works fine when using HCL-based Terraform.

### Steps to Reproduce

- Create a module in a directory such as `/Users/jamesbarlow/repo/tf.modules/modules/register/v0` and have this module itself reference another module with a relative path:
```
module "constants" {
  source = "../../constants"
}
```
So, in this example the `constants` module is located at `/Users/jamesbarlow/repo/tf.modules/modules/constants`

- Create a cdktf App directory at `/Users/jamesbarlow/repo/learn-cdktf-docker`
- Setup the `cdktf.json` to reference the `register` module that we want to generate the code bindings for, and include the `constants` module that is referenced by that module for good measure:

```json
"terraformModules": [
    {
      "name": "constants",
      "source": "../tf.modules/modules/constants"
    },
    {
      "name": "register",
      "source": "../tf.modules/modules/register/v0"
    }
  ]
```
- Run `cdktf get`. The error is emitted.

### Important Factoids

If a module which itself does not reference another module is imported, this works fine. For example, the `constants` module imports fine when specified in isolation in the `terraformModules` as this does not use another module.

### References

According to [here](https://github.com/hashicorp/terraform/issues/23333#issuecomment-1261531854) there is special treatment for relative paths and this error will occur for absolute paths.

I would guess that cdktf is "incorrectly" pre-converting the relative path to an absolute path before passing the path to Terraform, hence causing this error.

**Comment by jhwbarlow** [comment]
I experimented with various workarounds such as having a symlink in the App directory to the modules, such that there was a symlink `./tf.modules` -> `../tf.modules` but this did not change anything. I also used symlinks within the modules themselves to remove the `../` from within the modules but this again did not change anything.

Even copying the modules to a directory within the App directory causes the same error for those modules that use `../` internally:

```
│ Error: Local module path escapes module package
│ 
│ The given source directory for module.register.module.constants would be
│ outside of its containing package
│ "file:///Users/jamesbarlow/repo/learn-cdktf-docker/tf.modules/modules/register/v0".
│ Local source addresses starting with "../" must stay within the same
│ package that the calling module belongs to.
```

**Comment by jsteinich** [comment]
Your suspicion is correct; cdktf does convert relative module paths to absolute when running `cdktf get`. This conversion is done because the `get` operation is actually creating a temporary terraform hcl json file in a different directory and then invoking the terraform cli.

One option is to convert it back to a relative path at the time we know where it is being executed from.
