### ISSUE TITLE
Windows: Stuck after approval in interactive mode

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2476]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- Node on windows

### Expected Behavior

cdktf deploy should deploy after approval

### Actual Behavior

The confirming 'yes' is printed, the stack is showing as deploying but nothing happens

### References

- #0000

**Comment by ansgarm** [comment]
Maybe windows needs a `\r\n` after `yes` instead of just `\n` which we currently send?

**Comment by DanielMSchmidt** [comment]
This was it @ansgarm 👍
