### ISSUE TITLE
Windows: cdktf cli stuck after successful run

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2477]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

The process should exit and the powershell should be interactive again

### Actual Behavior

The process halts, canceling does not work anymore (it does if you cancel while work is happening)

### References

- #0000

**Comment by ansgarm** [comment]
Possibly related to https://github.com/microsoft/node-pty/issues/437 ?

**Comment by DanielMSchmidt** [comment]
Not so sure, this is after approving so there should be no process kill involved
