### ISSUE TITLE
Force stack to use construct ids for names.

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#248]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Something along the lines of `stack.useConstructIdsAsNames()` This would disable the generation of resource and other names and instead just use the construct ids passed in.

The main use case I'm looking for is being able to rebuild an existing Terraform stack using cdktf without having to destroy it beforehand.

### References
Takes #247 farther.

**Comment by skorfmann** [comment]
I think this was reasonably addressed with https://github.com/hashicorp/terraform-cdk/pull/329 - Don't think we're going to take it further than that.
