### ISSUE TITLE
cdktf throws errors when packages are installed system wide

### ISSUE THREAD

**Issue by sbkg0002** [hashicorp/terraform-cdk#2507]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
Python 3.11.1
cdktf==0.14.3

### Affected Resource(s)
NA
### Debug Output

```
# cdktf get
[2023-01-17T16:10:19.426] [DEBUG] default - Unable to run 'pipenv run pip show cdktf': Error: non-zero exit code 1
[2023-01-17T16:10:21.126] [DEBUG] default - Name: cdktf
```
```
# pip freeze | grep cdktf==
cdktf==0.14.3
# pipenv run pip freeze | grep cdktf==
#
```
### Expected Behavior

I expect -when cdktf is run outside of venv- to use the global/system packages.

### Actual Behavior

`cdktf get` is always run in a virtual environment.

### Steps to Reproduce

1. Install packages with `--global` (pip) or `--system` (pipenv)
2. run `cdktf get`

### Important Factoids

NA

### References

- #0000

**Comment by sbkg0002** [comment]
> > I expect -when cdktf is run outside of venv- to use the global/system packages.
> 
> The expectation is incorrect (depending on the template you used). To synthesise CDKTF looks into the `cdktf.json`'s app command and executes it. You can change the command to whatever you like, so also directly invoking your local python installation.
> 
> We should probably have some sort of info in the documentation for this, do you have an idea where we can add it so you would have found it?

Thanks for you reply. Still not completely clear since my app only states `python3 ./main.py`; there is no pip(env) mentioned anywhere in the project.
I guess [this would](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/project-setup) be the best spot.

**Comment by ansgarm** [comment]
My suspicion is that `collectDebugInformation` is the culprit here. Especially this line:
https://github.com/hashicorp/terraform-cdk/blob/44cf75daab5e89bdfe89887d24bcb283287e5564/packages/%40cdktf/commons/src/debug.ts#L115

Maybe we should change the log level of that line to debug – especially since we already expect that this might not work.
