### ISSUE TITLE
Add option to omit stack trace metadata

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#251]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When distributing the contents of `cdktf.out`, it's likely not desirable to have stack trace metadata alongside the resources, since that will change depending on where it's generated.

A workaround for now is using [jq](https://stedolan.github.io/jq/) to clean it up. This for example:

```
cat ./cdktf.out/cdk.tf.json | jq 'walk(if type == "object" then with_entries(select(.key | test("\/\/") | not)) else . end)'
```

**Comment by skorfmann** [comment]
I've just realised that this is possible already: `const app = new App({stackTraces: false});`

**Comment by miyurusankalpa** [comment]
I think this should set to false by default.

**Comment by skorfmann** [comment]
> I think this should set to false by default.

Could you explain why?
