### ISSUE TITLE
Golang: installing pre-built aws provider results in "file name too long" error

### ISSUE THREAD

**Issue by justabaka** [hashicorp/terraform-cdk#2510]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

language: go
cdktf-cli: 0.15.0
node: v18.12.1
cdktf: 0.15.0
constructs: 10.1.167
jsii: 1.73.0
terraform: 1.3.7
arch: x64
os: linux 5.15.0-58-generic
go: go version go1.19.5 linux/amd64

### Affected Provider / Resource(s)
cdktf-provider-aws-go/aws @ 12.0.0

### Debug Output
https://gist.github.com/justabaka/82f3f595ffe7c9660d64adc515827e63

### Expected Behavior
`cdktf init --template="go" --providers="aws@~>4.0"` or `cdktf provider add "aws@~>4.0"` work, pre-built provider is installed.

### Actual Behavior
Provider is not installed due to the 'file name too long' error.

### Steps to Reproduce
* install golang (any version, issue reproduces on 1.19, 1.18 and 1.16)
* install cdktf v0.15.0 as per [guide](https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install)
* initialize an empty project and install the aws provider: `cdktf init --template="go" --providers="aws@~>4.0"`

### Important Factoids
* `go get github.com/cdktf/cdktf-provider-aws-go/aws/v12@v12.0.0` also produces the same error
* my username consists of 9 characters
* filenames in cdktf-provider-aws-go really are absurdly enormous: e.g., aws/appautoscalingpolicy/appautoscalingpolicy_AppautoscalingPolicyTargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationDimensionsList__no_runtime_type_checking.go consists of 154 characters itself, even if you ignore all the path parts
* node.js is installed via nvm in case it matters

### References

- #0000

**Comment by DanielMSchmidt** [comment]
This is something we will need to fix in jsii-pacmac, removing some of the duplication in the filename

**Comment by DanielMSchmidt** [comment]
https://github.com/aws/jsii/pull/3927
