### ISSUE TITLE
`spotinst` provider: Update version constraint to use version 1.95.0

### ISSUE THREAD

**Issue by nandac** [hashicorp/terraform-cdk#2517]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

hashicorp/terraform-cdk => v0.15.0
cdktf-provider-spotinst => v5.0.0

### Affected Provider / Resource(s)

The cdktf-provider-spotinst has a version constraint for the ocean-ecs resource that has been set to v1.92.0 and as a result, does not pick up the latest version v1.95.0 which has a critical fix for our clusters.

I hope this can be updated soon. I am also happy to make a PR if someone could guide me on the process.

https://github.com/cdktf/cdktf-provider-spotinst/blob/47d51f860424ba0c70347287e9b37b17b60cb500/src/ocean-ecs/index.ts#L2400

### Debug Output

N/A

### Expected Behavior

The provider should get the latest version of the spotinst provider v1.95.0.

### Actual Behavior

The provider installed is v1.92.0 because of the version constraint.

### References

- #0000

**Comment by ansgarm** [comment]
Hi @nandac 👋

The constraint that defines the allowed version range is defined [here](https://github.com/cdktf/cdktf-repository-manager/blob/55c5aeb1fd33b802a11f84265680167ec5f30a8d/provider.json#L45) and should allow for an update.

Usually CI auto updates the provider but that seemed to have failed: https://github.com/cdktf/cdktf-provider-spotinst/pull/302

Also, I can't seem to see version `1.95.0` in the Terraform Registry: https://registry.terraform.io/providers/spotinst/spotinst/latest
I can see it on Github, though: https://github.com/spotinst/terraform-provider-spotinst/releases/tag/v1.95.0

I'll have a look at the pre-built provider upgrade that failed 👀

**Comment by nandac** [comment]
Thanks @ansgarm for looking into this.

Perhaps it takes 24 hours for the newest version to propagate and appear on the registry.

Let us see if the newest version is available tomorrow and go from there.

**Comment by ansgarm** [comment]
So, there's a new release that upgrades to `v1.94.0` out now: https://github.com/cdktf/cdktf-provider-spotinst/releases/tag/v5.0.1

**Comment by ansgarm** [comment]
I checked with the Registry team and `v1.95.0` is now available (they resynced it, there were some issues with the ingestion apparently).
I just triggered an [update](https://github.com/cdktf/cdktf-provider-spotinst/pull/305) and the new version should be available in a few minutes 👍

**Comment by nandac** [comment]
Thank you so much @ansgarm. :-)
