### ISSUE TITLE
Release new version of the databricks provider compatible with v0.15

### ISSUE THREAD

**Issue by manojkarthick** [hashicorp/terraform-cdk#2528]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.15.0
cdktf-cli: 0.15.0
databricks-provider: 4.0.1

### Affected Provider / Resource(s)

The prebuilt cdktf provider for databricks compatible with cdktf v0.15.0 hasn't been released. The other providers I use (aws, snowflake, newrelic, etc) have already been updated. 

The Github action for upgrading the provider seems to be failing for ~2 weeks from what I see: https://github.com/cdktf/cdktf-provider-databricks/actions - this is possibly why it hasn't been released? 

### References

* Databricks provider versions: https://www.npmjs.com/package/@cdktf/provider-databricks?activeTab=versions
* Most recent failed provider-upgrade action: https://github.com/cdktf/cdktf-provider-databricks/actions/runs/3982963814

**Comment by DanielMSchmidt** [comment]
A new version for this provider has been release: https://github.com/cdktf/cdktf-provider-databricks/releases/tag/v5.0.0
