### ISSUE TITLE
TFCDK- Python: Find the value From JSON Object

### ISSUE THREAD

**Issue by sdubey472** [hashicorp/terraform-cdk#2545]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Steps to Reproduce
I have created an Subnet using terraform CDK by using below COde

        subnetData = {
                "availability_zone": "ap-south-1a",
                "vpc_id": data['vpcData']['resourceAttrs'].id,
                "cidr_block": "10.10.10.0/24",
                "map_public_ip_on_launch": True,
                "tags": {
                    "Name": "Subnet 1"
                }
        }
        subnet = vpc.Subnet(self, "testSubnet", 
            **subnetData)
        subnetTags = subnet.tags
        
        TerraformOutput(self, "SubnetTags",
                    value = subnetTags 
            )

    Output on Terminal:
    SubnetTags = {
            "Name": "Subnet 1"
     }
    
     For some Business logic I have to get value of  "Name key" from the Subnet Tags that is not working. I tried multiple way but getting possible in CDKTF python.

### References

- #0000

**Comment by sdubey472** [comment]
Subnet created successfully and I am facing the problem to get subnet ids basis on which tags i have used to create subnet.

**Comment by ansgarm** [comment]
Hi there 👋

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) where there are more people ready to help.

Thanks!
