### ISSUE TITLE
IamInstanceProfile is not being created even though the code has successfully finished!

### ISSUE THREAD

**Issue by fdervisi** [hashicorp/terraform-cdk#2551]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions 

cdktf 0.15.2
typescript
npm 9.3.1
@cdktf/provider-aws  4.50.0  

### Debug Output

No error message, it just not create a IamInstanceProfile in AWS

### Expected Behavior

IamInstanceProfile should be created

### Actual Behavior

code finished successful and the state is also captured, however the IamInstanceProfile can't be found in IAM

### Steps to Reproduce

just create a IamInstanceProfile with a test role, then you will see the issue:

Here you can see the state in cdk.tf.json:
```
 "resource": {
    "aws_iam_instance_profile": {
      "yourUserId-role1-iam-instance-profile": {
        "//": {
          "metadata": {
            "path": "iamstack/yourUserId-role1-iam-instance-profile",
            "uniqueId": "yourUserId-role1-iam-instance-profile"
          }
        },
        "name": "yourUserId-role1-iam-instance-profile",
        "role": "${aws_iam_role.yourUserId-role1.name}"
      },
      "yourUserId-role2-iam-instance-profile": {
        "//": {
          "metadata": {
            "path": "iamstack/yourUserId-role2-iam-instance-profile",
            "uniqueId": "yourUserId-role2-iam-instance-profile"
          }
        },
        "name": "yourUserId-role2-iam-instance-profile",
        "role": "${aws_iam_role.yourUserId-role2.name}"
      }
    },
```

however you can't find the yourUserId-role1-iam-instance-profile in AWS! Eveything else, works:

IamPolicyAttachment
IamRole
IamPolicy

### References

- #0000

**Comment by DanielMSchmidt** [comment]
Did the `cdktf plan` show the `IamInstanceProfile` resource?
