### ISSUE TITLE
Typescript template local backend not generating lock files

### ISSUE THREAD

**Issue by acdoussan** [hashicorp/terraform-cdk#2552]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

"cdktf": "^0.14.3"

### Affected Resource(s)

cdktf-cli

### Debug Output

N/A

### Expected Behavior

In the past, I created a cdktf project by running `cdktf init --template=typescript --local`

I then made some changes and deployed them with `cdktf deploy`

~~I moved my parent directory (aka `mv directory-containing-project ../somewhere-else`), and now when I try to deploy, `cdktf` thinks all of my resources need to be created again, when they already exist. It appears [lock files](https://developer.hashicorp.com/terraform/language/settings/backends/local) are not being generated, or if they are, are being put somewhere outside of the project.~~

~~How am I supposed to use this if everywhere I pull the repo down will not recognize that resources have already been created? I do not want to create an account or upload stuff anywhere, I just want local files generated that can be tracked with source control.~~

I take this back, it looks like `.tfstate` files are being generated, but they are part of the gitignore by default. Shouldn't this not be in there if the user has defined local only? 

Should the example project also have a [LocalBackend](https://developer.hashicorp.com/terraform/cdktf/api-reference/typescript#localbackend) rather than no backend at all when using `--local`?

### Actual Behavior

No lock files generated.

### Steps to Reproduce

- create a project
- update the project and deploy it
- try to use the project elsewhere
- terraform thinks nothing has been created already

### Important Factoids

N/A

### References

- Did a search but could not find anything relevant
- Repo that I am having this problem with https://github.com/acdoussan/homelab-terraform

**Comment by jsteinich** [comment]
The Terraform state file can contain sensitive information and as such it is not recommended to place in source control.
If you are working with other developers (or even on different machines), it is recommended to use a different backend so that state is stored securely and is shareable.

**Comment by ansgarm** [comment]
> Should the example project also have a [LocalBackend](https://developer.hashicorp.com/terraform/cdktf/api-reference/typescript#localbackend) rather than no backend at all when using --local?

If you have no backend at all, we will infer a local backend (Terraform does this too, if I remember correctly).
