### ISSUE TITLE
Token asAny / Intrinsic value doesn't work as expected

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#256]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
0.0.12

### Affected Resource(s)
Referenced remote state

### Debug Output
https://github.com/hashicorp/terraform-cdk/pull/241/checks?sha=46584d718d9a955732949782d0638e2dd5c8c1c7

### Expected Behavior
The `creation_stack` property should probably just be removed in tests since it is very sensitive to unrelated changes

### Actual Behavior
Despite removing hard paths, the `creation_stack` was different with both local and runner using the docker image.

### Steps to Reproduce
Run yarn test with https://github.com/hashicorp/terraform-cdk/pull/241

### References

* #241

**Comment by skorfmann** [comment]
`creation_stack` shouldn't be synthesized at all.

**Comment by skorfmann** [comment]
`creation_stack` gets synthesized when `Token.asAny` returns an `Intrinsic` value.
