### ISSUE TITLE
Documentation: Migrate state instructions in `remote-backends.mdx` don't match with examples

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2577]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The steps are worded for a stack called `hello-terraform`
https://github.com/hashicorp/terraform-cdk/blob/b3c34a80e75a167b758807bcebfebd06d360c168/website/docs/cdktf/concepts/remote-backends.mdx?plain=1#L299

But the examples use `local-to-cloud-backend`, and `hi-terraform`

https://github.com/hashicorp/terraform-cdk/blob/b3c34a80e75a167b758807bcebfebd06d360c168/website/docs/cdktf/concepts/remote-backends.mdx?plain=1#L216
https://github.com/hashicorp/terraform-cdk/blob/b3c34a80e75a167b758807bcebfebd06d360c168/website/docs/cdktf/concepts/remote-backends.mdx?plain=1#L251

**Comment by DanielMSchmidt** [comment]
The outdated instructions have been replaced in the mean time, nothing to do here anymore :)
