### ISSUE TITLE
Github provider is ignoring owner field

### ISSUE THREAD

**Issue by gkaskonas** [hashicorp/terraform-cdk#2594]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.15.2

### Affected Resource(s)

GithubProvider

### Expected Behavior

Repository should be created under owner organisation

### Actual Behavior

It gets created under user repository

### Steps to Reproduce

```
  private provider = new GithubProvider(this, "github", {
    alias: "github",
    owner: "myorg
  });

new Repository(this, "repository", {
    name: "test-repo-v2",
    visibility: GithubRepoVisibility.public});
```

### Important Factoids

It works fine if I set GITHUB_OWNER env variable
### References

- #0000

**Comment by gkaskonas** [comment]
It's similar to this problem https://github.com/integrations/terraform-provider-github/issues/876

But how do I configure required_providers in cdk?

**Comment by ansgarm** [comment]
Hi @gkaskonas 👋

As CDKTF is using Terraform providers underneath, the issue you linked is probably the reason.

You can use [overrides](https://developer.hashicorp.com/terraform/cdktf/concepts/stacks#escape-hatch) to set the right Github provider in `required_providers`.

**Comment by ansgarm** [comment]
Let me re-open this, as provider bindings generated by CDKTF do set `required_providers` but could do better.
So, while you can workaround this, we could also fix this on our end 👍

**Comment by ansgarm** [comment]
In theory we should already set the right source – so we'd need to confirm that, too.

**Comment by ansgarm** [comment]
I just checked and we're indeed using `integrations/github` from here:
https://github.com/cdktf/cdktf-provider-github/blob/fe1b953f77ca3dd516a1a7af4e8d118c8af88af6/src/provider/index.ts#L131
to set in the provider source:
https://github.com/hashicorp/terraform-cdk/blob/c3896e2768b1e7250b39f98d5c52e0e65fbbe9d8/packages/cdktf/lib/terraform-provider.ts#L73

So, sorry for the noise – I thought we're setting only `github` there which would cause that problem. Let me close this again :)
