### ISSUE TITLE
cdktf get - '"cdktf"' has no exported member named 'TerraformModuleUserConfig'

### ISSUE THREAD

**Issue by shira-lev** [hashicorp/terraform-cdk#2599]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli version - 0.15.2
node version - v18.14.0
terraform version - 1.3.7

### Expected Behavior

When running `cdktf get` the given modules in `cdktf.json` are generated as typescript files. the generated files should import the correct names from cdktf

### Actual Behavior

The generated file is using this import - 
`import { TerraformModule, TerraformModuleUserConfig } from 'cdktf';`

I see this error - 
`'"cdktf"' has no exported member named 'TerraformModuleUserConfig'. Did you mean 'TerraformModuleUserOptions'?ts(2724)`

### Steps to Reproduce

created a new cdktf project and added a private module to the modules list in the `cdktf.json` file, then run `cdktf get`

### Important Factoids

After changing to `TerraformModuleUserOptions` it works but it should be importing it from the start.
It didn't happened 2 weeks ago, then It imported `TerraformModuleUserOptions` as it should

**Comment by ansgarm** [comment]
Hi @shira-lev 👋

Which version of the `cdktf` library are you using? (You can run `cdktf debug` to get a list of all versions)

**Comment by shira-lev** [comment]
Hi, I found the problem, the `cdktf` in the package.json was the old version... its ok now. 
Thank you!
