### ISSUE TITLE
`aws` provider: broken for cdktf 0.15.3

### ISSUE THREAD

**Issue by jonatanzafar59** [hashicorp/terraform-cdk#2602]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

`cdktf 0.15.3`
`awsProvider 0.12.2`

### Affected Provider / Resource(s)

AWS

### Debug Output

`.gen/modules/acm.ts(3,27): error TS2724: '"cdktf"' has no exported member named 'TerraformModuleUserConfig'. Did you mean 'TerraformModuleUserOptions'?`

### Expected Behavior

to run as usual.

### Actual Behavior

borken because of the `TerraformModuleUserConfig` change.
### Steps to Reproduce

upgrade `cdktf` to `0.15.3`

**Comment by ansgarm** [comment]
Which `cdktf` version are you using? You can run `cdktf debug` to print all versions.

**Comment by ansgarm** [comment]
Seems to be similar to #2599

**Comment by jonatanzafar59** [comment]
@ansgarm 
```
cdktf debug
language: typescript
cdktf-cli: 0.15.3
node: v18.12.1
cdktf: 0.15.3
constructs: 10.1.242
jsii: null
terraform: 1.3.7
arch: arm64
os: darwin 21.3.0
```

**Comment by ansgarm** [comment]
(for visibility)

As posted in the [thread](https://cdk-dev.slack.com/archives/C017XMM5L7N/p1675693753299249) on the CDK Dev Slack, I was not able to reproduce this – Here's an example that worked for me: https://github.com/ansgarm/test-cdktf-0.15.3-modules

There might be something else in the way your project is set-up that might cause this. Could you try cloning my reproduction example and check whether that works? If it does work, we need to dig deeper to figure out what's going on in your project.

**Comment by jonatanzafar59** [comment]
@ansgarm the test repo is working for me. the one that fails is an a public terraform module. this is the part of it in my `cdktf.json`

```        {
            "name": "acm",
            "source": "terraform-aws-modules/acm/aws",
            "version": "~> 3.4.1"
        }
```
something with the linking is broken, I guess there are more modules broken.

**Comment by ansgarm** [comment]
Hm, the test repo [contains](https://github.com/ansgarm/test-cdktf-0.15.3-modules/blob/main/cdktf.json#L8-L12) that exact same module.

**Comment by jonatanzafar59** [comment]
problem resolved after deleting the `package-lock.json` and re-installing from a fresh `package.lock` `cdktf` version change.
thanks @ansgarm for the help!
