### ISSUE TITLE
Terraform CDK CLI - Error when running destroy for multiple stacks

### ISSUE THREAD

**Issue by getsec** [hashicorp/terraform-cdk#2615]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I have encountered the following error whenever I seem to run `destroy` for multiple stacks. I can destroy each stack by referencing it by name, but when I use `cdktf destroy xxx yyy --auto-approve`, I receive the following Javascript Trace

```sh
❯ cdktf destroy aesir_redis aesir_rabbitmq --ignore-missing-stack-dependencies --auto-approve


1 Stack destroying     0 Stacks done     1 Stack waiting

<--- Last few GCs --->

[364092:0x5f5c380]   319314 ms: Mark-sweep 4044.1 (4130.1) -> 4028.6 (4130.6) MB, 1078.0 / 0.0 ms  (average mu = 0.103, current mu = 0.024) allocation failure; scavenge might not succeed
[364092:0x5f5c380]   320427 ms: Mark-sweep 4044.5 (4130.6) -> 4029.0 (4130.8) MB, 1087.2 / 0.0 ms  (average mu = 0.064, current mu = 0.023) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xbbf330 node::Abort() [node]
 2: 0xad464e  [node]
 3: 0xda4320 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0xda46d6 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 5: 0xfa1b65  [node]
 6: 0xfa2116 v8::internal::Heap::RecomputeLimits(v8::internal::GarbageCollector) [node]
 7: 0xfb371d  [node]
 8: 0xfb4235 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 9: 0xf8eaa7 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
10: 0xf8faa7 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
11: 0xf6e820 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
12: 0xf611fc v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
13: 0xf61375 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
14: 0x11b8055 v8::internal::FastGetOwnValuesOrEntries(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, bool, v8::internal::Handle<v8::internal::FixedArray>*) [node]
15: 0x11b8318 v8::internal::GetOwnValuesOrEntries(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::PropertyFilter, bool, bool) [node]
16: 0x137f6b7 v8::internal::Runtime_ObjectEntries(int, unsigned long*, v8::internal::Isolate*) [node]
17: 0x17fb2f9  [node]
fish: Job 1, 'cdktf destroy aesir-redis aesir…' terminated by signal SIGABRT (Abort)
```

I don't have much experience with node, and I am unsure on the possible solutions / further troubleshooting information for this issue. Thanks for taking the time to take a look at this. It's quite possible that I made a mistake somewhere too, and that this isn't related to cdktf-cli

#### Providers
```json
{
  "local": [
    {
      "providerName": "aws",
      "providerConstraint": "4.53",
      "providerVersion": "4.53.0"
    },
    {
      "providerName": "integrations/github",
      "providerConstraint": "5.17.0",
      "providerVersion": "5.17.0"
    }
  ],
  "prebuilt": [
    {
      "packageName": "cdktf-cdktf-provider-aws",
      "packageVersion": "12.0.2",
      "providerName": "aws",
      "providerVersion": "4.52.0",
      "cdktfVersion": "^0.15.0"
    }
  ]
}
```

#### CLI Version
```sh
❯ cdktf provider --version
0.15.2
```

#### Node Version
Tried with both v19, and v18, the examples listed here used this version
```
❯ node --version
v19.0.0
```

### Expected Behavior
I would expect the CLI to destroy each template.

### Actual Behavior
The application crashes.

### Important Factoids
This seems to happen when I reference multiple stacks as well as `"*"`

### References
https://stackoverflow.com/questions/53230823/fatal-error-ineffective-mark-compacts-near-heap-limit-allocation-failed-javas
https://support.snyk.io/hc/en-us/articles/360002046418-JavaScript-heap-out-of-memory

- #0000

**Comment by ansgarm** [comment]
Hi @getsec 👋

In the past we've only seen out of memory issues with `cdktf get` but not when running `destroy` or other commands. Does running `cdktf diff` or `cdktf deploy` work?

Is there any chance that anything is running `cdktf get`? Especially with the AWS provider the 4 GB of memory probably wouldn't suffice.

Oh, almost forgot: Does it work when targeting only a single stack for the `destroy`?
