### ISSUE TITLE
CLI doesn't run `terraform init` if new module is used

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2616]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

`0.15.3`

### Affected Resource(s)

Modules

### Debug Output

```
[2023-02-08T17:22:54.713] [ERROR] default - ╷
│ Error: Module not installed
│
│   on cdk.tf.json line 12, in module:
│   12:     "label": {
│
│ This module is not yet installed. Run "terraform init" to install all
│ modules required by this configuration.
test-cdktf-module-init  ╷
                        │ Error: Module not installed
                        │
                        │   on cdk.tf.json line 12, in module:
                        │   12:     "label": {
                        │
                        │ This module is not yet installed. Run "terraform init" to install all
                        │ modules required by this configuration.
                        ╵

⠏  Processing
Error: External Error: Stack failed to plan: test-cdktf-module-init. Please check the logs for more information.
```

### Expected Behavior

CLI should run `terraform init`

### Actual Behavior

Does not run `terraform init` which fails

### Steps to Reproduce

1. Create a new CDKTF project
2. Run `cdktf plan` on the empty project
3. Add a module to `cdktf.json` (e.g. `"cloudposse/label/null@~> 0.25.0"`)
4. Run `cdktf get`
5. Use the module
```ts
import { Label } from './.gen/modules/cloudposse/null/label';
// ...
new Label(this, "label", {});
```
6. Run `cdktf plan`
7. ~Profit~ Error

### Important Factoids

Probably introduced by #2572 – We can refactor that fix to still run `init` on every `plan`/`apply` but only run `providers lock` selectively (the latter downloads the re-providers every time which was the real time consuming culprit that we intended to fix in that PR).

**Comment by giner** [comment]
> A workaround for this is deleting the cdktf.out directory before running plan/apply

Deleting `cdktf.out` means deleting `.terraform.lock.hcl` which makes pinning versions of the providers impossible.

**Comment by kamiluo** [comment]
Hi, exists another 2 workarounds:

1. Go to the cdktf.out/stacks/yourstack folder and execute `terraform init` directly.
2. Change the name of your stack in your code and execute `cdktf synth` that will refresh everything in your stack folder.
