### ISSUE TITLE
Issue when getting output from tf remote state

### ISSUE THREAD

**Issue by ansraliant** [hashicorp/terraform-cdk#2620]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### description

While getting an output from the terraform state, `cdktf synth` fails to synthesize.

### cdktf & Language Versions

cdktf: `0.15.3`
python: `3.11.1`

### Affected Resource(s)

`DataTerraformRemoteStateS3` (possibly other resource, as early debugging seems to indicate this component is working correctly)

### Debug Output

https://gist.github.com/ansraliant/404f7f86f048cdff57a506d7ee064a39

### Expected Behavior

Define Terraform Output:
```python
TerraformOutput(self, "repository_arns", value=["some_important_string"])
```

This array is saved in the terraform state.
```json
"outputs": {
    "repository_arns": {
      "value": [
        "some_important_string",
      ],
      "type": [
        "tuple",
        [
          "string",
        ]
      ]
    }
```

Define Terraform Remote State
```python
DataTerraformRemoteStateS3(
            self,
            id="remote_state",
            bucket=config.ecr_config.bucket,
            key=config.ecr_config.key,
        )
```

Debugging `DataTerraformRemoteStateS3`, it would seem it returns correctly the output
```python
> ecr_remote_state.get_list('repository_arns')
> ['#{TfToken[TOKEN.3]}']
```

When running `cdktf synth` it should synthesize correctly.

### Actual Behavior

When running `cdktf synth` it fails with the message `RuntimeError: Error: Found an encoded list token string in a scalar string context. Use 'Fn.element(list, 0)' (not 'list[0]') to extract elements from token lists`. 

More info on the attached full stack trace log.

Note that I am using `get_list()` to get the array from the terraform state, using `get_string()` will result in `cdktf synth` working correctly, but the result being a single element from the array.

### Steps to Reproduce

1. Define string list as terraform output
2. Save result in remote state
3. Get list from remote state with `get_list()`
4. Run `cdktf synth`

### Important Factoids

There is nothing abnormal in the accounts we are using, we just use S3, and ECR, and should be considered a normal case use.

### References

Could not find any other reference to this issue in this repository.

That's all I know at the moment. Please let me know if there is any other information you would need.

**Comment by ansgarm** [comment]
Hi @ansraliant 👋

Thank you for the detailed explanation! Much appreciated 👍

How are you using the result returned from `ecr_remote_state.get_list('repository_arns')` in the rest of your code? I suspect the error may lie there.

**Comment by ansraliant** [comment]
Hi @ansgarm 
Thanks for the quick reply.

Regarding your question. The result of `ecr_remote_state.get_list('repository_arns')` is being put into a dataclass used to generate a iam policy json.
The dataclass definition is something like this:
```python
@dataclass
class Statement:
    action: Union[list[str], str]
    effect: str
    resource: list[str]

@dataclass
class Policy
statement: list[Statement]
```

The calling part is:
```python
Policy([Statement(
    action = ["list of ecr api actions"]
    resource = repository_arns => this is the output of the external remote state
)])
```

The dataclass is converted to json using python `JSONEncoder()` combined with [asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict)


The generated json is used in `IamRolePolicy` on the `policy` field.

**Comment by ansraliant** [comment]
Hi @ansgarm 

> special token that will be resolved to a Terraform address to the output of your Terraform remote state

I see. I thought that token was being used later on for something.

If I have something like this 
```
{
  "statement": [{
    "action":"something",
    "effect":"Allow",
    "resource": "${jsonencode([\"#{TfToken[TOKEN.3]}\"])}"
  }]
}
```

It complains with:

```
Error: "policy" contains an invalid JSON: invalid character 'a' after object key:value pair
```

But, If instead I do
```
{
  "statement": [{
    "action":"something",
    "effect":"Allow",
    "resource": ${jsonencode([\"#{TfToken[TOKEN.3]}\"])}
  }]
}
```
It works.

Now, I suspect this has to do with the fact that jsonencode returns a string with double quotes and they are not escaped. 

Maybe I can put the jsonencode into a var and then use it somehow, at least, I would do that in HCL haha. 

I'm still seeing ways of solving it, will update with more once I find a solution to it.

**Comment by ansraliant** [comment]
Hi @ansgarm 

Sorry for the delay. I continued working on this one, and found something interesting.

First of all, `jsonencode` kinda works.

Using my previous example of the policy dataclass, if I have a `as_json` method as this

```python
    def as_json(self) -> str:
        return Fn.jsonencode(self.as_dict())
```

Then, the output of the remote state is parsed correctly, and cdk is happy.

Now to the interesting part.

With those policy dataclasses I generate multiple policies, one of those uses conditions. Conditions are 
just a normal dict, which then gets converted into json.

For example, I have this condition dict
```python
{"StringEquals": {"token.actions.githubusercontent.com:aud": "sts.amazonaws.com"}}
```

Python JSONEncoder converts such dictionary to json, and the result is

```json
'{"StringEquals": {"token.actions.githubusercontent.com:aud": "sts.amazonaws.com"}}'
```

Now with jsonencode I cannot see the result on the console because calling jsonencode returns a token, but after I synth I get something like
```json
"${jsonencode({condition = {StringEquals = {token.actions.githubusercontent.com:aud = \"sts.amazonaws.com\"}}})}"
```

Notice the keys are not escaped. 

Luckily I can run a terraform console and experiment a bit more:

```
(cdk) raul.verdi@I-M-A-000017 /t/c/c/s/cdk> terraform console
> jsonencode({hello: "there"})
"{\"hello\":\"there\"}"
> jsonencode({condition = {StringEquals = {token.actions.githubusercontent.com:aud = \"sts.amazonaws.com\"}}})
╷
│ Error: Missing attribute separator
│
│   on <console-input> line 1:
│   (source code not available)
│
│ Expected a newline or comma to mark the beginning of the next attribute.
╵

╷
│ Error: Invalid character
│
│   on <console-input> line 1:
│   (source code not available)
│
│ This character is not used within the language.
╵
> jsonencode({"condition" = {"StringEquals" = {"token.actions.githubusercontent.com:aud" = "sts.amazonaws.com"}}})
"{\"condition\":{\"StringEquals\":{\"token.actions.githubusercontent.com:aud\":\"sts.amazonaws.com\"}}}"
>
```

From that output we can see that if I treat keys as strings, then jsonencode is happy.

I put this as an example into a gist if you want to try the example, it uses the AWS provider, but you don't need an account or anything to be able to synth it.

https://gist.github.com/ansraliant/c0a57145cc6e70ef8446ae332a9316d9

Let me know what you think.
Thanks.

**Comment by ansraliant** [comment]
This issues are related:
 * https://github.com/hashicorp/terraform-cdk/issues/2675
 * https://github.com/hashicorp/terraform-cdk/issues/1795

**Comment by ansraliant** [comment]
For the time being we ended up using a combination of `jsonencode` and pythons `jsonencoder`, until the issue on jsonencode is resolved. I believe we can close this now. Mentioned tickets should provide a follow up to this issue.
