### ISSUE TITLE
Consul pre-built provider fails pull on case-insensitive filesystem

### ISSUE THREAD

**Issue by krarey** [hashicorp/terraform-cdk#2627]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF: 0.15.4
Provider: cdktf-provider-consul-go @ 3.0.0

### Debug Output

https://gist.github.com/krarey/7c3008454c57ad806d622d3ac017f3a5

### Expected Behavior

When attempting to pull the Consul pre-built provider for CDKTF on a MacOS host, the provider fails to pull due to case-insensitivity conflicts between the `LICENSE` file and `license` directory. MacOS formats its root volume with APFS in case-insensitive mode by default, so this incompatibility would impact most developers working from MacOS.

### Actual Behavior

Provider fails to pull from github. See linked gist for raw output.

**Comment by ansgarm** [comment]
Hi @krarey! Thanks for reporting this! I created a fix that probably will go out with the next major release.
