### ISSUE TITLE
Lazy value that is referencing a remote state is resolved to local state

### ISSUE THREAD

**Issue by asafcyclops** [hashicorp/terraform-cdk#2629]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CdkTf Version - 0.15.4
Language - C#

### Affected Resource(s)

every resource

### Debug Output

https://gist.github.com/asafcyclops/137c5e078e21b27f12d86a79c8103bc5

### Expected Behavior

When using a lazy value
On Synthesis token should be resolved to reference the remote state where the MongoDbAtlas data is located

### Actual Behavior

When using a lazy value
On Synthesis token is resolved as if the MongoDbAtlas data is located in the same stack

### Steps to Reproduce

1. Create 2 stacks
2. Create a Lazy value in Stack A referencing a resource in Stack B
3. Try to deploy and face the issue
run deploy

### Important Factoids

not sure if its atypical but I am using lazy values

**Comment by DanielMSchmidt** [comment]
Can you share a minimal example of your code so that we can reproduce this?
