### ISSUE TITLE
Yarn workspaces TS compile error

### ISSUE THREAD

**Issue by tiagob** [hashicorp/terraform-cdk#263]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
% cdktf --version
0.0.12
```

### Debug Output

```
% yarn compile
yarn run v1.22.4
$ tsc --pretty
../../node_modules/@testing-library/dom/types/events.d.ts:87:42 - error TS2304: Cannot find name 'Node'.
```

### Expected Behavior

```
% yarn compile
yarn run v1.22.4
$ tsc --pretty
✨  Done in 9.09s.
```

### Steps to Reproduce

I have yarn workspaces setup. One of the packages is an expo react-native app. Setup via https://github.com/expo/expo/tree/master/packages/expo-yarn-workspaces

I believe this is causing the issue.

### Solution

I added this line to the `tsconfig.json` which fixed it

```
    "skipLibCheck": true
```

**Comment by skorfmann** [comment]
Hey @tiagob, thanks for taking the time to report this issue. 

Is your suggestion to add this config to the Typescript [template](https://github.com/hashicorp/terraform-cdk/blob/d785af4bf2dad8f1a30b34b8e751ece967c7680d/packages/cdktf-cli/templates/typescript/tsconfig.json)?

**Comment by tiagob** [comment]
Yes!

**Comment by skorfmann** [comment]
Ok, thanks for confirming.

I read up on `skipLibCheck` [a bit](https://stackoverflow.com/questions/52311779/usage-of-the-typescript-compiler-argument-skiplibcheck), and I'm not sure it makes sense to enable this by default. 

According to [the docs](https://www.typescriptlang.org/docs/handbook/compiler-options.html), it'd disable all checks for `*.d.ts` files, even if you would have manually created these yourself. Plus, wouldn't you want the types of your dependencies to be correct in general? 

From that regard, it looks more like an option which would be enabled in case there are issues with 3rd party dependencies. It doesn't look like the offending dependency comes from `cdktf` - and even if it was coming form this project, I'd be more inclined to try to fix it. 

Did I miss anything or are there other reasons to add this option?
