### ISSUE TITLE
Move "app" config from "cdktf.json" to "package.json"

### ISSUE THREAD

**Issue by tiagob** [hashicorp/terraform-cdk#264]
I have cdktf setup in a yarn workspaces monorepo. I want my build settings to match across packages. I think cdktf could support this by looking at `package.json` `"main"`

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
% cdktf --version
0.0.12
```

### Expected Behavior

Deploy works

### Actual Behavior

```
% cdktf deploy
⠹ synthesizing ...
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'packages/aws/main.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
non-zero exit code 1
```

### Steps to Reproduce

Change tsconfig.json

```
  "compilerOptions": {
    ...
    "outDir": "build"
  },
  ...
  "exclude": ["node_modules", "build"]
```

Change package.json

```
  "main": "build/index.js",
```

Rename `main.ts` to `index.ts`

**Comment by skorfmann** [comment]
Thanks for the bug report @tiagob. I'm not sure if this is an actual bug or more like a feature request to move the config from `cdktf.json` to `package.json`. 

Wouldn't this `cdktf.json` config work in your case?

```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node build/index.js",
  "terraformProviders": [
    "aws@~> 2.0"
  ]
}
```

**Comment by tiagob** [comment]
@skorfmann that works! Thank you.

Yes, moving this from cdktf.json to package.json would be clearer

**Comment by skorfmann** [comment]
> Yes, moving this from cdktf.json to package.json would be clearer

It's maintained as part of `cdktf.json`, since we support not only Typescript / Node, but also Python. There will be .NET, Java and at some point Go support as well. Hence, I think a special case for Typescript / Node would be more confusing and would make maintaining docs more complex.

**Comment by anubhavmishra** [comment]
As @skorfmann mentioned this won't be possible as the `cdktf.json` file is meant to provide a common way to integrate with different languages that CDK for Terraform supports.

**Comment by anubhavmishra** [comment]
Created a new [issue](https://github.com/hashicorp/terraform-cdk/issues/275) to document the `cdktf.json` file/
