### ISSUE TITLE
Use specific imports for used resources when converting

### ISSUE THREAD

**Issue by mutahhir** [hashicorp/terraform-cdk#2647]
Currently convert generates a single import line per provider for typescript, something like so:

```ts
import * as aws from "../../.gen/providers/aws";
```

and then uses the following syntax for referencing resources / data sources:

```ts
    new aws.provider.AwsProvider(this, "aws", {
```

While this works fine for Typescript, it doesn't work for languages that don't allow * imports, like C#.

That import becomes:

```cs
using Gen.Providers.Aws;
```

and declaring the resource becomes:

```cs
            new aws.Provider.AwsProvider(this, "aws", new Struct
```

which does not work.

Apart from it being broken on C#, there are performance implications for doing a * import for large providers. Thus, this is a performance improvement as well.

```cs
            new aws.Provider.AwsProvider(this, "aws", new Struct
            {
// ...
            });
```

**Comment by ansgarm** [comment]
I just wanted to quickly note that the import seems to be still wrong (even after JSII resolves to the right structs) – I don't know how related that is exactly (i.e. whether the structs fix was supposed to fix the imports too) which is why I'm posting this message 😄

I just got the following code produced (with `^0.16.0-pre.89`)
```csharp
using Constructs;
using HashiCorp.Cdktf;
/*Provider bindings are generated by running cdktf get.
See https://cdk.tf/provider-generation for more details.*/
using Gen.Providers.Aws;
class MyConvertedCode : TerraformStack
{
    public MyConvertedCode(Construct scope, string name) : base(scope, name)
    {
        var awsS3BucketB = new S3Bucket.S3Bucket(this, "b", new S3BucketConfig {
            Bucket = "my-tf-test-bucket",
            Tags = new Dictionary<string, string> {
                { "Environment", "Dev" },
                { "Name", "My bucket" }
            }
        });
        new S3BucketAcl.S3BucketAcl(this, "example", new S3BucketAclConfig {
            Acl = "private",
            Bucket = awsS3BucketB.Id
        });
    }
}
```

which seems to have a wrong import (`Gen.Providers.Aws`).
