### ISSUE TITLE
Build watching for changes

### ISSUE THREAD

**Issue by cmclaughlin** [hashicorp/terraform-cdk#265]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not very familiar with TypeScript, Yarn, etc, so I'm not sure about this... but just getting started making some changes it would be nice to "compile" one file at a time and not the entire project. `yarn build` takes a while and drains my laptop battery 😄 

I see there's a watch option in`packages/cdktf-cli/package.json` -- could we have something like that in the root of the repo? In other words, could we run `yarn watch` in the root of the repo and have it watch/compile changes to `packages/cdktf*`?

Also, expanding the docs on environment setup would good too... I'm not sure if this is the right way to get started, but I edited `packages/cdktf/package.json` and specified a version there (.e.g. 0.0.1). And then used `--cdktf-version=0.0.1` with my copy of `cdktf` - without that I was getting this error:

    cannot use version 0.0.0, use --cdktf-version, --dist or CDKTF_DIST to install from a "dist" directory

**Comment by skorfmann** [comment]
Thanks for raising this issue @cmclaughlin - I just created #266 to improve the guide and added a `yarn watch` command. Would be great if you could provide feedback on this.

**Comment by skorfmann** [comment]
Fixed in https://github.com/hashicorp/terraform-cdk/pull/266
