### ISSUE TITLE
AssumeRole on the AwsProvider interface is supposed to be an array now

### ISSUE THREAD

**Issue by kevanslumin** [hashicorp/terraform-cdk#2651]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

I think AssumeRole on line 24 here: https://github.com/cdktf/cdktf-provider-aws-go/blob/main/aws/provider/provider_AwsProvider.go is supposed to be an array now.

This was changed upstream here: https://github.com/cdktf/cdktf-provider-aws/commit/bc10d04d63405770a9478b546b79dd427e5d112f#diff-509e5a7e694ada9ee232d998a18480cb322eecec8351eb36cd68633af5ef0970R187 where the AwsProviderAssumeRole is an array now.

Looks like a bunch of other items are supposed to be arrays now too.

It causes this error:

```
panic: Passed to parameter config of new @cdktf/provider-aws.provider.AwsProvider: Unable to deserialize value as @cdktf/provider-aws.provider.AwsProviderConfig | undefined
├── 🛑 Failing value is an object
│      { '$jsii.struct': [Object] }
╰── 🔍 Failure reason(s):
    ╰─ Key 'assumeRole': Unable to deserialize value as cdktf.IResolvable | array<@cdktf/provider-aws.provider.AwsProviderAssumeRole> | undefined
        ├── 🛑 Failing value is an object
        │      { '$jsii.struct': [Object] }
        ╰── 🔍 Failure reason(s):
            ├─ [as array<@cdktf/provider-aws.provider.AwsProviderAssumeRole>] Value is not an array
            ╰─ [as cdktf.IResolvable] Value does not have the "$jsii.byref" key
```

This issue is just a courtesy; feel free to close it if you don't think it is important.  I got this to work by passing in a slice and it works because the actual parameter is just the empty interface.  It would be clearer if it was at least a slice of empty interface though.

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-cdk/issues/2565.

**Comment by DanielMSchmidt** [comment]
This looks like the AWS provider changing it's schema and the pre-built provider reacting. Quite annoying that it leads to breaking changes for you, but from our perspective it works like expected. Unfortunately unions are not well handled in JSII in general, that's why you see the `interface{}` as an equivalent of `any` in TS. 

Closing this since there is little we can do against provider updates 🙈
