### ISSUE TITLE
[devops-cdktf]: errored in logs instead of any clear error message

### ISSUE THREAD

**Issue by Mithgroth** [hashicorp/terraform-cdk#2664]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.15.5
.net: 7.0

### Debug Output

https://gist.github.com/Mithgroth/7ed3daca7f9597d5abc207d2c374a1db

### Expected Behavior

Get an actual error message

### Actual Behavior

`[devops-cdktf]: errored` in logs
`Error: External Error: Stack failed to plan: devops-cdktf. Please check the logs for more information.` in CLI after `cdktf diff`

### Steps to Reproduce

Upgrade a C# CDKTF with microsoft/azuredevops, azuread, azurerm providers from 0.14.3 to 0.15.5.

### Important Factoids

microsoft/azuredevops (v.0.3.0) provider hasn't been updated since Nov '22, might be causing errors.

**Comment by DanielMSchmidt** [comment]
> microsoft/azuredevops (v.0.3.0) provider hasn't been updated since Nov '22, might be causing errors.

Just to make sure, you mean [this one](https://registry.terraform.io/providers/microsoft/azuredevops/latest) and no pre-built provider, right?

In this case it seems like we start `terraform plan` but get no logs back from it, what operating system were you running on?
