### ISSUE TITLE
`Fn.mergeList` should not exist (`Fn.concat` is the right one)

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2665]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

`Fn.mergeList`

### Debug Output

> Call to function "merge" failed: arguments must be maps or objects, got
                    │ "tuple".

### Expected Behavior

Function shouldn't exist

As per TF docs:
> merge takes an arbitrary number of maps or objects, and returns a single map or object that contains a merged set of elements from all arguments.

### References

- #0000

**Comment by mutahhir** [comment]
This is resolved, but we reference it in one of our docs: https://github.com/hashicorp/terraform-cdk/blob/main/website/docs/cdktf/concepts/stacks.mdx#stack-dependencies
