### ISSUE TITLE
cdktf should escape keys in maps/objects if they require quoting

### ISSUE THREAD

**Issue by nikowatari** [hashicorp/terraform-cdk#2675]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.15.5 (Python)

### Debug Output

Produced `cdk.tf.json`: https://gist.github.com/nikowatari/caf8f0bad424e0199dcd4df0d552113b

### Expected Behavior

Terraform docs says the following about keys in maps/objects:
> The keys in a map must be strings; they can be left unquoted if they are a valid identifier, but must be quoted otherwise.

Reference: https://developer.hashicorp.com/terraform/language/expressions/types#maps-objects
More info about identifiers: https://developer.hashicorp.com/terraform/language/syntax/configuration#identifiers

For this piece of the cdktf code in Python:
```python
TerraformOutput(self, "fail", value=Fn.lookup({
    "ke:y": "value"
}, "key", default_value="default"))
```
I expect cdktf to produce the following output:
```json
"output": {
  "fail": {
    "value": "${lookup({\"ke:y\" = \"value\"}, \"key\", \"default\")}"
  }
}
```

### Actual Behavior

cdktf produces the following output, which is incorrect (note `ke:y` that should be quoted according to the docs above):
```json
"output": {
  "fail": {
    "value": "${lookup({ke:y = \"value\"}, \"key\", \"default\")}"
  }
}
```

### Steps to Reproduce

This is a complete source code in Python: https://gist.github.com/nikowatari/d133596068923cb6f7d45e50e5c78979

The issue lies here: https://github.com/hashicorp/terraform-cdk/blob/5cec0935c05da5e8a1fd3a01392709453215a13e/packages/cdktf/lib/tfExpression.ts#L30
cdktf should check if the key identifier needs escaping and escape if so. Or just escape all the time w/o checking (the only downside I see here is the slightly increased size of `cdk.tf.json`)
So the simplest form of the fix would be to change the above line to:
```ts
.map((key) => `"${key}" = ${this.resolveArg(context, arg[key])}`) 
```

**Comment by ansgarm** [comment]
Hi @nikowatari 👋 Thank you for reporting this!
This seems to be the same as #1795 (which took me a while to find, but I knew it existed, because I created it some long time ago 😅).
So, I'm closing this as a duplicate (even though this issue is written way better than mine was) as the other one already has some upvotes on it.
