### ISSUE TITLE
vars are not passed through to destroy properly

### ISSUE THREAD

**Issue by doowb** [hashicorp/terraform-cdk#2684]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
cdktf: v0.15.5
@cdktf/cli-core: v0.15.5
```

I'm using the above libraries and TypeScript

### Affected Resource(s)

Using `TerraformVariable` and passing in `vars` array to `project.destroy` (instance of `CdktfProject` from `@cdktf/cli-core`)

### Expected Behavior

The `vars` should be used (this works correctly with `project.deploy`)

### Actual Behavior

Terraform is prompting to enter a value for the "missing" variables.

### Steps to Reproduce

Create a stack file making use of `TerraformVariable`.
Create an instance of `CdktfProject` that runs the stack file via the `synthCommand`.
Invoke `project.destroy({ vars: ['myVariable=myValue'] /*, additional options */ })`

### Important Factoids

The code [here](https://github.com/hashicorp/terraform-cdk/blob/aeda96bd633b9b2bdcf7894582345eb1ca69b00b/packages/%40cdktf/cli-core/src/lib/models/deploy-machine.ts#L383-L385) is wrapping the vars elements with `'`.

This is not being done for `deploy` [here](https://github.com/hashicorp/terraform-cdk/blob/aeda96bd633b9b2bdcf7894582345eb1ca69b00b/packages/%40cdktf/cli-core/src/lib/models/deploy-machine.ts#L335-L337).

I updated the JavaScript code in my node_modules to remove the `'` and `destroy` was able to run successfully.

//edit
I thought I might be able to use [extraOptions](https://github.com/hashicorp/terraform-cdk/blob/aeda96bd633b9b2bdcf7894582345eb1ca69b00b/packages/%40cdktf/cli-core/src/lib/models/deploy-machine.ts#L323) but those are not being passed through [here](https://github.com/hashicorp/terraform-cdk/blob/aeda96bd633b9b2bdcf7894582345eb1ca69b00b/packages/%40cdktf/cli-core/src/lib/cdktf-stack.ts#L469-L475)

### References

- #0000

**Comment by DanielMSchmidt** [comment]
Seems like we forgot to wrap the vars for destroy
