### ISSUE TITLE
NamedCloudWorkspace to Accept Parameters Similar to tfe_workspace

### ISSUE THREAD

**Issue by ZacharyATanenbaum** [hashicorp/terraform-cdk#2690]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently NamedCloudWorkspaces [only accept a name argument](https://github.com/hashicorp/terraform-cdk/blob/9e641f69ce8943c3737ab43cdd74a5306c41d485/packages/cdktf/lib/backends/cloud-backend.ts#L134). This means the workspace will have sensible defaults on creation but must be changed manually, after creation, for some use cases.

There doesn't seem to be a "NamedCloudWorkspace" Terraform Resource. Does the NamedCloudWorkspace transpile to the [tfe_workspace](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace) Terraform resource? If so, would it be possible to pass the configuration parameters of the "NamedCloudWorkspace" to that one?

### References

[NamedCloudWorkspaces Definition](https://github.com/hashicorp/terraform-cdk/blob/9e641f69ce8943c3737ab43cdd74a5306c41d485/packages/cdktf/lib/backends/cloud-backend.ts#L134)

[tfe_workspace Documentation](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/workspace)

**Comment by ansgarm** [comment]
Hi @ZacharyATanenbaum 👋

The `NamedCloudWorkspace` class that `cdktf` exposes, is only used to configure the `cloud` backend in Terraform ([related docs](https://developer.hashicorp.com/terraform/cli/cloud/settings#workspaces)).

The tfe_workspace resource is not included in the `cdktf` core library but rather is its own Terraform provider which can be used through either pre-built provider bindings or locally generated bindings (via `cdktf get`).
You can run `cdktf provider add tfe` to add it to your project (will prefer the pre-built package).
