### ISSUE TITLE
aws provider npm version uploaded as 0.0.0

### ISSUE THREAD

**Issue by x3cion** [hashicorp/terraform-cdk#2691]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Provider / Resource(s)

provider-aws (https://www.npmjs.com/package/@cdktf/provider-aws, https://github.com/cdktf/cdktf-provider-aws)

### Expected Behavior

Version in npm reflects version from version bump

### Actual Behavior

For npm, the release got uploaded as version "0.0.0".

### References
https://www.npmjs.com/package/@cdktf/provider-aws
https://github.com/cdktf/cdktf-provider-aws

- #0000

It doesn't look like this was on purpose?

**Comment by mutahhir** [comment]
Thank you for reporting! We're working on a fix.

**Comment by xiehan** [comment]
This was resolved.
