### ISSUE TITLE
Support `assume_role` and `security_token` in CosBackend (added in TF 1.4)

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#2703]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform 1.4 added these two properties to the `cos` backend – we should update our interface for that backend.

### References

Mentioned in the [changelog](https://github.com/hashicorp/terraform/blob/v1.4/CHANGELOG.md), but no PR is linked unfortunately, so a bit of search or visiting the docs for more info is necessary.

**Comment by ansgarm** [comment]
In the meantime this can be achieved by using an [override](https://developer.hashicorp.com/terraform/cdktf/concepts/remote-backends#escape-hatches).

**Comment by dbanck** [comment]
* https://github.com/hashicorp/terraform/pull/32631 :)
