### ISSUE TITLE
Convert: Use local bindings when running JSII-Rosetta

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#2708]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

We have incorrect convert results for JSII languages (#2646), these are partially fixed in #2706.
The fix only works in very specific scenarios where the user has the correct local bindings in Typescript in the folder where they run convert (to a non-TS language). This makes it very impractical, thus our process needs to also generate typescript bindings in a temporary folder during convert

**Comment by mutahhir** [comment]
I think we should definitely have a plan for solving this, but we might not be able to get to it within this release.
