### ISSUE TITLE
allow to use 3rd party terraform provider

### ISSUE THREAD

**Issue by vmarchaud** [hashicorp/terraform-cdk#271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the cdk only support official provider which is limiting, for example i use https://github.com/gavinbunney/terraform-provider-kubectl to apply directly manifests in Terraform. The behavior of the terraform binary is to look for custom provider in `terraform.d` directory, which the cdk does not.

**Comment by skorfmann** [comment]
Would the new [provider requirements](https://github.com/hashicorp/terraform/blob/guide-v0.13-beta/draft-upgrade-guide.md#in-house-providers) of Terraform 0.13 be sufficient?

**Comment by vmarchaud** [comment]
@skorfmann I think so yeah

**Comment by skorfmann** [comment]
> @skorfmann I think so yeah

Cool, that's ongoing (#118) and should be shipped soon. Let's check again once that's released.

**Comment by danieldreier** [comment]
The linked linked PR (#118) has been merged for a while, so I'm going to close this issue and consider it resolved. Please say something if the scope of your request is beyond that PR!
