### ISSUE TITLE
`mongodbatlas` provider: Python CFNTF package name for mongodbatlas

### ISSUE THREAD

**Issue by andreaangiolillo** [hashicorp/terraform-cdk#2718]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
Python

### References

Hello 👋 ,
is there any reason why the python package name is `cdktf-cdktf-provider-mongodbatlas` instead of `cdktf-provider-mongodbatlas`? 
Thanks

**Comment by nbaju1** [comment]
All of the Python packages are named like this: https://pypi.org/search/?q=cdktf-cdktf . Not that this directly answers your question, just stating that this is the standard.

**Comment by andreaangiolillo** [comment]
Thank you!
