### ISSUE TITLE
Use jsii-srcmak

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As suggested by @eladb we should transition to https://github.com/aws/jsii-srcmak for the code generator process in the cli. This will likely help with #270 and paves the way for #197 

It's used in [cdk8s](https://github.com/awslabs/cdk8s/blob/f0ef3b467969a90efcbfc663353565c8639bb5bd/packages/cdk8s-cli/lib/import/base.ts) already. It can be implemented in a similar way.

### References

- #270 
- #197

**Comment by jsteinich** [comment]
Can probably use https://github.com/awslabs/cdk8s/pull/205 to help guide the process.

**Comment by skorfmann** [comment]
Implemented in #276
