### ISSUE TITLE
🚀 Support for Ruby language

### ISSUE THREAD

**Issue by palladius** [hashicorp/terraform-cdk#2726]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, Terraform CDK supports TypeScript, Python, Java, C#, and Go.
Please add Ruby to the list of supported language.

**Comment by ansgarm** [comment]
Hi @palladius 👋

CDK for Terraform uses JSII as the underlying technology to support multiple languages.
As soon as JSII adds support for Ruby, we can add support for it, too.

Here's the upstream issue related to Ruby support: https://github.com/aws/jsii/issues/144
