### ISSUE TITLE
CDKTF Custom Constructs not respecting DependsOn

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [hashicorp/terraform-cdk#2727]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript, 15.5

### Affected Resource(s)

Any Custom Construct. Example:

```typescript
interface LambdaPretrafficPassedParams {
  preTrafficInvocation: LambdaInvocation;
}
class LambdaPretrafficPassed extends Construct {
  public preTrafficFunctionInvocation: LambdaInvocation;
  constructor(scope: Construct, id: string, { preTrafficInvocation }: LambdaPretrafficPassedParams) {
    super(scope, id);
    this.preTrafficFunctionInvocation = preTrafficInvocation;
    console.log('PretrafficPassed init complete');
  }
}

export const createLambdaPretrafficPassed = (scope: Construct, id: string, preTrafficInvocation: LambdaInvocation) => {
  const PassedInstance = new LambdaPretrafficPassed(scope, id, {
    preTrafficInvocation,
  });
  PassedInstance.node.addDependency([preTrafficInvocation]);
  PassedInstance.node.addValidation({
    validate: () => {
      if (preTrafficInvocation.result !== 'SUCCESS') {
        return [`Invocation of ${preTrafficInvocation.functionName} failed`];
      }
      return [];
    },
  });
  return PassedInstance;
};
```

### Debug Output

```bash
[2023-03-15T17:00:15.328] [ERROR] default - Error: Validation failed with the following errors:
  [DEVMS_OwlStacksInternalStack/OwlStacksInternalLogging/logToS3PretrafficPassed] Invocation of ${TfToken[TOKEN.66]} failed
    at InternalStack.runAllValidations (/home/michaelsila/Documents/owl-stacks-repositories/owl-stacks-internal/deploy/node_modules/cdktf/lib/terraform-stack.ts:342:13)
    at StackSynthesizer.synthesize (/home/michaelsila/Documents/owl-stacks-repositories/owl-stacks-internal/deploy/node_modules/cdktf/lib/synthesize/synthesizer.ts:30:18)
    at /home/michaelsila/Documents/owl-stacks-repositories/owl-stacks-internal/deploy/node_modules/cdktf/lib/app.ts:129:49
    at Array.forEach (<anonymous>)
    at App.synth (/home/michaelsila/Documents/owl-stacks-repositories/owl-stacks-internal/deploy/node_modules/cdktf/lib/app.ts:129:12)
    at /home/michaelsila/Documents/owl-stacks-repositories/owl-stacks-internal/deploy/main.ts:32:9
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERROR [DEVMS_OwlStacksInternalStack/OwlStacksInternalLogging/logToS3PretrafficPassed]: PretrafficValidationFailed
```

### Expected Behavior

If I add DependsOn,  Terraform should not attempt to validate the resource using TF Tokens that are not yet resolved. Note this is also true if I set the type to terraform resource

### Actual Behavior

Terraform tries to immediately run validation despite the fact that the specified values are not resolved. 

### Steps to Reproduce

1. Create a test project with the aws provider
2. create a test lambda
3. create a test lambda invocation
4. use my code

Watch it fail in the plan stages

### References

- #0000

**Comment by DanielMSchmidt** [comment]
The [`addDependency`](https://docs.aws.amazon.com/cdk/api/v2/docs/constructs.Node.html#addwbrdependencydeps) method you are calling is part of the Construct library and is used for ordering the constructs resolution. It has nothing to do with terraform dependencies. That being said, I am sure one could write an [Aspect](https://developer.hashicorp.com/terraform/cdktf/concepts/aspects) that adds the Construct level `cdktfConstruct.node.dependencies` to the CDKTF level `cdktfConstruct.dependsOn` array.

One question, you mention

> TF Tokens that are not yet resolved

And I'd like to make sure to clear out misunderstandings about [Tokens](https://developer.hashicorp.com/terraform/cdktf/concepts/tokens): They are never going to contain real data, their purpose is to synthesise into terraform references for the underlying data, but there is nothing to inspect at runtime.

I'm closing this issue for now; it seems to be more of an usage problem and I'd be unsure on how to improve the documentation in this case. If you have ideas or if I misjudged this please re-open :)
