### ISSUE TITLE
CDFTK has incorrect Terraform lifecycle configuration for resources

### ISSUE THREAD

**Issue by JustAnotherSoftwareDeveloper** [hashicorp/terraform-cdk#2728]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.15.5

### Affected Resource(s)

All

### Expected Behavior

[
](https://developer.hashicorp.com/terraform/language/v1.2.x/expressions/custom-conditions)

This is present in all versions of terraform. You can set pre and postconditions on the resource 
### Actual Behavior

This just doesn't exist. 

### Steps to Reproduce

Go to the lifecycle documentation in cdktf and look for preconditions or postconditions

### References

[]()

- #0000

**Comment by DanielMSchmidt** [comment]
Yes, good point, we are missing pre and post conditions in our library right now. We are open for Pull Requests and it's definitely on our list, but I'm unsure on the timing. In the mean time #2472 shows how one can use [the escape hatch](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch) to synthesise these conditions
