### ISSUE TITLE
Generated bindings for `elastic/elasticstack` ommit provider configuration

### ISSUE THREAD

**Issue by ignaloidas** [hashicorp/terraform-cdk#2735]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.15.5
Seems to happen with all languages

### Affected Resource(s)

Provider configuration of `elastic/elasticstack`

### Expected Behavior

Generated bindings code for provider configuration should include `elasticsearch` and `kibana` blocks.

### Actual Behavior

Generated bindings code for provider configuration does not have any parameters besides alias.

### Steps to Reproduce

`cdktf provider add "elastic/elasticstack@=0.5.0"` and `cdktf get`

### Important Factoids

From a quick look seems like their schema for provider configuration is [a bit weird](https://github.com/elastic/terraform-provider-elasticstack/blob/main/internal/schema/connection.go#L34), with it being a list with maximum number of elements of 1, but I don't know if that's what's causing an issue

**Comment by ansgarm** [comment]
Hi @ignaloidas 👋

Thank you for raising this! It seems like this provider is running into a bug as it has no `attributes` but only `block_types` defined 😅
The offending line is this one: https://github.com/hashicorp/terraform-cdk/blob/506cd10ab0bcc373a74a60c43411c8c1a10b0444/packages/%40cdktf/provider-generator/lib/get/generator/resource-parser.ts#L95-L97

I'll get a PR ready to fix this 👍

**Comment by ansgarm** [comment]
In the meantime (and until the fix is released) you can use an override to set these properties: https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch (this also works on providers)
