### ISSUE TITLE
cdktf typescript aws cloudformation argument naming conventions

### ISSUE THREAD

**Issue by animaala** [hashicorp/terraform-cdk#2748]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf v0.15.5
tsc v4.9.5
aws v4.60.0

### Affected Provider / Resource(s)

aws cloudformation

CloudfrontDistributionDefaultCacheBehaviorLambdaFunctionAssociation

### Debug Output

Error: Extraneous JSON object property
     │ 
     │   on cdk.tf.json line 268, in resource.aws_cloudfront_distribution.abc123.default_cache_behavior.lambda_function_association:
     │  268:             "eventType": "origin-response",
     │ 
     │ No argument or block type is named "eventType". Did you mean "event_type"?
     ╵
tms  ╷
     │ Error: Extraneous JSON object property
     │ 
     │   on cdk.tf.json line 269, in resource.aws_cloudfront_distribution.abc123.default_cache_behavior.lambda_function_association:
     │  269:             "lambdaArn": "arn:aws:lambda:us-east-1:123456789:function:hsts:8"
     │ 
     │ No argument or block type is named "lambdaArn". Did you mean "lambda_arn"?
     ╵
tms  ╷
     │ Error: Missing required argument
     │ 
     │   on cdk.tf.json line 270, in resource.aws_cloudfront_distribution.abc123.default_cache_behavior.lambda_function_association:
     │  270:           },
     │ 
     │ The argument "lambda_arn" is required, but no definition was found.
     ╵
     ╷
     │ Error: Missing required argument
     │ 
     │   on cdk.tf.json line 270, in resource.aws_cloudfront_distribution.abc123.default_cache_behavior.lambda_function_association:
     │  270:           },
     │ 
     │ The argument "event_type" is required, but no definition was found.

### Expected Behavior

The typescript argument format naming conventions would be followed e.g. eventType

### Actual Behavior

The OG terraform argument naming conventions are being used. e.g. event_type

### Steps to Reproduce

Create a cloudfront distribution with default cache behaviour with lambda function associations

### References

- #0000

**Comment by ansgarm** [comment]
Hi @animaala 👋

Could you share some code that produces this error? I looked at the code of the AWS prebuilt provider and it seems to have the [proper mapping method](https://github.com/cdktf/cdktf-provider-aws/blob/e500787fee482602b99d856913d97bd113c8ae4f/src/cloudfront-distribution/index.ts#L931-L941) that does this conversion - so nothing odd there.
