### ISSUE TITLE
cdktf apply output gets cut off by approve dialog

### ISSUE THREAD

**Issue by maybedino** [hashicorp/terraform-cdk#2749]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf v0.15.5
tsc v4.9.5
azurerm v5.0.9

### Affected Resource(s)

cdktf-cli

### Expected Behavior

When deploying a stack to Azure, `cdktf apply` shows the diff that you have to approve.

### Actual Behavior

The diff outout gets cut off by the the approve/dismiss/stop dialog:

![image](https://user-images.githubusercontent.com/108456389/228842272-6f5a2bc6-9cea-4bd0-8427-307d007e9e44.png)
(Blur was added by me)

You can't see what will actually be applied until you select something. This does not happen with `cdktf plan` because there is no dialog in the end.

### Steps to Reproduce

Create a stack, run `cdktf apply`. I'm not sure if this is related to any provider etc. we use, but so far this happens with all our stacks.

### Important Factoids

The above image uses Fish and Gnome-Terminal on Linux, but the same happens on other systems, like MacOS.

This did not happen in cdtkf 0.13, only after upgrading to 0.15 this bug appeared.

**Comment by DanielMSchmidt** [comment]
Is the missing diff from the same stack that is about to be approved? We normally stop all further output so that one can read the diff that should have been printed beforehand. Maybe we should stop all but the one for the stack we want to diff so that in case of this race condition we don't hold off too early.

**Comment by maybedino** [comment]
Yes, this is all just 1 stack.

**Comment by maybedino** [comment]
The approval dialog is send _before_ the terraform output, which includes the diff, so the output is halted until then: https://github.com/hashicorp/terraform-cdk/blob/main/packages/%40cdktf/cli-core/src/lib/models/deploy-machine.ts#L112

Here is a simple fix: https://github.com/hashicorp/terraform-cdk/pull/2790
