### ISSUE TITLE
cdktf convert reports python errors when using the kubernetes provider

### ISSUE THREAD

**Issue by robin-norwood** [hashicorp/terraform-cdk#2786]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
$ cdktf --version                                                
0.15.5
```

```
$ python3 --version
Python 3.7.9
```

### Affected Resource(s)

Kubernetes provider with the `cdktf convert` command.

### Debug Output

Here's a [gist reproducing the issue](https://gist.github.com/robin-norwood/2c8ae3cf88ac028e59897f898e2975f2), and showing that omitting `--provider=kubernetes` does not show the error.

### Expected Behavior

Python code without scary error messages.

### Actual Behavior

CDKTF appears to generate the correct python code, but includes a bunch of scary error messages.

### Steps to Reproduce

In the [gist](https://gist.github.com/robin-norwood/2c8ae3cf88ac028e59897f898e2975f2):

1. Clone example repo
2. Create and go to `app` directory.
3. Run `cdktf init`, specifying python and the kubernetes provider.
4. Run `cat ../k8s_deployment.tf | cdktf convert  --provider=kubernetes`

### Important Factoids

- MacOS Ventura 13.2.1
- Python 3 installed via brew
- CDKTF installed via NPM

**Comment by mutahhir** [comment]
This should be fixed now on latest main. Output from following repro steps: 

```py
from constructs import Construct
#
# Provider bindings are generated by running `cdktf get`.
# See https://cdk.tf/provider-generation for more details.
#
from imports.kubernetes.deployment import Deployment
class MyConvertedCode(Construct):
    def __init__(self, scope, name):
        super().__init__(scope, name)
        Deployment(self, "myapp",
            metadata=DeploymentMetadata(
                labels={
                    "app": "myapp",
                    "component": "frontend",
                    "environment": "dev"
                },
                name="myapp-frontend-dev"
            ),
            spec=DeploymentSpec(
                replicas="1",
                selector=DeploymentSpecSelector(
                    match_labels={
                        "app": "myapp",
                        "component": "frontend",
                        "environment": "dev"
                    }
                ),
                template=DeploymentSpecTemplate(
                    metadata=DeploymentSpecTemplateMetadata(
                        labels={
                            "app": "myapp",
                            "component": "frontend",
                            "environment": "dev"
                        }
                    ),
                    spec=DeploymentSpecTemplateSpec(
                        container=[DeploymentSpecTemplateSpecContainer(
                            image="nginx:latest",
                            name="myapp-frontend-dev"
                        )
                        ]
                    )
                )
            )
        )
```
