### ISSUE TITLE
Expose `conditional()` and other expression helpers through JSII

### ISSUE THREAD

**Issue by ramzi-afli** [hashicorp/terraform-cdk#2818]
### Description

I want to use conditions  when trying to assign values  inside locals.
example : 
locals {
driver_node_type       = var.driver_node_type != null ? var.driver_node_type : var.instance_type
maybe_driver_node_type = var.driver_instance_pool_id != null ? null : local.driver_node_type
} 
and i didn't  find any documentation about this  topic, it is implemented or not  yet ? 

### Links

https://developer.hashicorp.com/terraform/cdktf/concepts/variables-and-outputs#local-values

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @ramzi-afli 👋

We don't have docs on that yet, but there is `conditional()` which you can import from the `cdktf` package.

Does that help?

**Comment by ramzi-afli** [comment]
@ansgarm  Thank you ,  Could you provide me with the name of the class, as I haven't found it yet ?

**Comment by ansgarm** [comment]
That is no class but rather a function. Something along these lines should work:

```ts
import { conditional, TerraformLocal, Op } from 'cdktf'

new TerraformLocal(this, 'local', conditional(
      Op.neq(varDriverNodeType.value, null),
      varDriverNodeType.value,
      instanceType.value
));
```

**Comment by ramzi-afli** [comment]
@ansgarm  it is exposed only for typescript  or even for python is exposed also because i'm trying to import  the  function and  it seems  nothing  with that name is found   (cdk  version 0.16.0)

**Comment by AmineChikhaoui** [comment]
Hi @ansgarm , I'm @ramzi-afli 's colleague and also interested to get to know about the languages feature parity situation for Terraform CDK in general.

While going through the published python lib for `cdktf` I noticed that it doesn't export a `conditional` symbol and that wasn't actually the only case. There is several symbols that are not exported from the jsii mapping for python, but I could be missing something as I don't know exactly how the jsii runtime execution handles things.
Is there a difference between the features supported between typescript and the rest of the languages ? or is it guaranteed that all symbols exported from Typescript are also available to the python (other langs) bindings through some automatic jsii runtime mapping ?

**Comment by ansgarm** [comment]
Hi @AmineChikhaoui @ramzi-afli 👋

Unfortunately, the way JSII works, only certain exports will be made available to other languages automatically. So there's no guarantee. That said, we intend to make everything available to all languages, so not exposing `conditional()` for Python and other languages was an oversight on our end here.

**Comment by xiehan** [comment]
I think there's two things going on here: one is that the conditionals feature isn't documented, the other is that it's currently unavailable in languages other than TypeScript.

I've gone ahead and created #2915 to track the documentation issue, so that this issue can be about adding multi-language support.
