### ISSUE TITLE
cdktf doesnt show Approve/Dismiss/Stop prompt when items to change

### ISSUE THREAD

**Issue by prowlaiii** [hashicorp/terraform-cdk#2827]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
node --version
v20.0.0
npm --version
9.6.5
terraform --version
Terraform v1.4.5
on darwin_amd64
+ provider registry.terraform.io/hashicorp/archive v2.3.0
+ provider registry.terraform.io/hashicorp/aws v4.63.0
+ provider registry.terraform.io/hashicorp/null v3.2.1
+ provider registry.terraform.io/hashicorp/random v3.5.1
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/sumologic/sumologic v2.22.0
+ provider registry.terraform.io/terraform-providers/acme v2.12.0
cdktf --version
0.16.0
```

### Affected Resource(s)

`cdktf apply `

1. Displays and responds to the Approve/Dismiss/Stop prompt on a new stack creation.
2. Displays and responds to the Approve/Dismiss/Stop prompt on stack deletion (`cdktf destroy`).
3. Never displays prompt if changes are required.

### Debug Output

n/a

### Expected Behavior

Expecting the Approve/Dismiss/Stop prompt in order to proceed with the apply.

### Actual Behavior

There is no prompt, so the stack update cannot be actioned.

It also hangs on `cdktf apply --require-approval never`, so it seems like it may be impossible to manage the stack.

### Steps to Reproduce

It happens every time I do "cdktf apply" with the changes.
I have to do Ctrl-C and then unlock the TF Cloud Workspace.

### Important Factoids

Trial and error:

- This is on an Intel Mac running Ventura 13.3.1 and occurs in iTerm2 and Mac Terminal.
- I've tried different versions of NPM & Terraform, but the same outcome.
- It doesn't occur on a Linux system (Mint).
- The state is in TF Cloud, but execution is local.
- I tried setting `TERM=dumb`, but it didn't seem to believe me and still output colour and the smart terminal output.
- I tried adding `-no-colour` to the output and it displayed the Approve/Dismiss/Stop prompt and let me choose the option.
- So, "cdktf apply" works to created a stack, "cdktf destroy" works to tear down the stack, but "cdktf apply" hangs if there are changes.

Screendump showing the terminal as it's been for 15 min.
![image](https://user-images.githubusercontent.com/95285953/233426543-94f94806-6d39-49a3-85e9-116ddba977a0.png)

### Suggestion

It might be good to be able to disable the clever prompt and revert to the underlying Terraform text "Yes" prompt.

### Workaround

Add `--no-colour` to the command.

### References

It might relate to the screen handling as per https://github.com/hashicorp/terraform-cdk/issues/2749 but can't be sure.

- #0000

**Comment by ansgarm** [comment]
A possible approach to fix this could be to take the incoming output from the `terraform` process and buffer it and release new input on a line by line basis (so whenever a `\n` is received, we'd forward that).

**Comment by prowlaiii** [comment]
A further update - I think it may be related to the sceen width, as it happened with a change even with the "--no-color" workaround.
I then noticed the formatting issue mentioned by @ansgarm ...
So I made my window wider and it succeeded.

**Comment by prowlaiii** [comment]
And another small update; it does look like the screen size/wrap is out of kilter; I'm seeing this sort of thing...

![image](https://user-images.githubusercontent.com/95285953/234007630-3d20ad91-47d7-4b22-9ffd-b55319feaa2f.png)
![image](https://user-images.githubusercontent.com/95285953/234007743-dadcbf17-858a-4493-a7bb-6658eca9c20e.png)

But in this case I am getting the Approve/Dismiss/Stop options.
![image](https://user-images.githubusercontent.com/95285953/234007964-bf281036-0c64-4fa8-8929-a8cd667d0bce.png)

I'm wondering if there's a screen/line buffer issue?
