### ISSUE TITLE
Assertions are not found

### ISSUE THREAD

**Issue by mazzy89** [hashicorp/terraform-cdk#2828]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.16.0
Go 1.20

### Affected Resource(s)

<img width="1037" alt="Screenshot 2023-04-20 at 22 04 05" src="https://user-images.githubusercontent.com/5463218/233475814-fcd91748-ef93-4cbd-b50f-b968fa7fda07.png">

Assertions are not found

### Expected Behavior

under the cdktf package I could have `Testing` package with the Assertions.

### Actual Behavior

Assertions are not found and no unit tests could be written

### References

- #0000

**Comment by ansgarm** [comment]
Hi @mazzy89 👋 

thank you for reporting this! This seems to be wrong in our template for new Go projects.

Instead of `Assertions_` it should be `Testing_` as e.g. here in our integration test:
https://github.com/hashicorp/terraform-cdk/blob/705cdc5bc10b5f1fc88923887ebf0c4a076dee52/test/go/testing-matchers/main_test.go#L26

**Comment by mazzy89** [comment]
Right. so there is a problem in the test generation because I have found that already created during the template. template then must be changed.

**Comment by mazzy89** [comment]
Also please check out documentation. documentation is wrong too.
