### ISSUE TITLE
No versions available for com.hashicorp:cdktf-provider-null:jar:[4.0.1,4.0.1] within specified range 

### ISSUE THREAD

**Issue by anthonybennett-RL** [hashicorp/terraform-cdk#2851]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf version - 0.14.3
Java version - 17
cdktf-provider-null version - 4.0.1

### Affected Resource(s)

Calling `jsii-pacmak --target java` will fail due it not being to resolve version 4.0.1 of `cdktf-provider-null`

Maven repository's `maven-metadata.xml` does not correctly list `cdktf-provider-null` version 4.0.1 which is causing failures in resolving dependencies even though it exists in the repository. The last updated date of `maven-metadata.xml` is from 2021.

https://repo.maven.apache.org/maven2/com/hashicorp/cdktf-provider-null/maven-metadata.xml

### References

- #2458

**Comment by ansgarm** [comment]
The versions are available now – if this happens again, please file a new issue and we'll get in contact with Maven to ensure the sync happens correctly.
