### ISSUE TITLE
Encounter segmentation fault issue when running cdktf get under version v0.16.1

### ISSUE THREAD

**Issue by HaoyunJi** [hashicorp/terraform-cdk#2868]
**ENVIRONMENT: WSL2 Ubuntu 22.04.1 LTS**

☁  cdktf-flux-stack [main] (⎈|omt-cluster:default) **cat /etc/os-release**
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

☁  cdktf-flux-stack [main] (⎈|omt-cluster:default) cdktf get
**[1]    970 segmentation fault  cdktf get**

☁  cdktf-flux-stack [main] (⎈|omt-cluster:default) cdktf get --version
0.16.1

**Comment by DanielMSchmidt** [comment]
Can you share the content of your `cdktf.json` file?

**Comment by HaoyunJi** [comment]
I think it is not related to the cdktf.json.
I will also meet error during cdftf init:
☁  temp  (⎈|omt-cluster:default) cdktf init --template=typescript --providers=kreuzwerker/docker --local
[1]    4804 segmentation fault  cdktf init --template=typescript --providers=kreuzwerker/docker --local

Not sure if it is related to the WSL env..

**Comment by HaoyunJi** [comment]
It is **fine** to run cdktf **v0.15.5** for me..

**Comment by ansgarm** [comment]
Hi @HaoyunJi 👋

Are you still experiencing this on the latest release?
