### ISSUE TITLE
SecuirtyGroupIngress creation in AWS requires to provide optional parameters as well and even after that it fails

### ISSUE THREAD

**Issue by igw2014** [hashicorp/terraform-cdk#2878]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

using cdktf version 0.16.0 with python
aws provider version 3.67.0

### Affected Resource(s)

SecurityGroupIngress while trying to create SecurityGroup fro AWS RDS Cluster/Cluster Instance

### Debug Output

 148:             ],
                   │  149:             "prefix_list_ids": [
                   │  150:               "pl-073555187c4e6ccf2",
                   │  151:               "pl-07cbd8b5e26960eac"
aws-cdktf-example  │  152:             ],
                   │  153:             "protocol": "tcp",
                   │  154:             "security_groups": [
                   │  155:               "launch-wizard-1"
                   │  156:             ],
                   │  157:             "self": null,
                   │  158:             "to_port": 5432
                   │  159:           }
                   │  160:         ],
                   │ 
                   │ Null values are not allowed for this attribute value.

### Expected Behavior

Security Group creation should work even if prefix_list_id,security group and self are not provided as they are optional as per the documentation here : https://registry.terraform.io/providers/hashicorp/aws/3.67.0/docs/resources/security_group

### Actual Behavior

Tried creating AWS security group using cdktf/python. When I run cdktf deploy without providing value for optional parameters it throws error saying that Null values are not allowed for this attribute. It does not even hint which attribute! at least you should consider the developer experience here.In the absense of any API documentation for CDKTF packages its already a tough job to come up with the constructs and this adds to the painful debugging experience.

When I tried to pass some values it went through fine but then I am stuck at "self". Even after providing the value as "false" or False it still fails giving error message "  TypeError: SecurityGroupIngress.__init__() got multiple values for argument 'self'". NO matter what i pass it always throws this message!

### Steps to Reproduce

1. write cdktf python code for creating security group
2. run cdktf deploy

### Important Factoids

There is nothing particular about my steps.Its a very normal stuff I am doing. I have already wasted a day because if this,with no clue about what is wrong here.

**Comment by DanielMSchmidt** [comment]
Can you share your program so we can better understand the issue?
