### ISSUE TITLE
Add Computed List Accessor

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#288]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While we have a wrapper for computed maps (e.g. `StringMap`), we don't have similar wrappers for computed lists. 

This popped up when working with a AWS VPC module which has string lists outputs, but there are certainly more occurrences.

**Comment by DanielMSchmidt** [comment]
Closed as we plan to migrate over to normal lists (#993 is the issue). All lists right now can be accessed via Terraform Functions, e.g. `Fn.element(list, 0)`.
