### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by axecopfire** [hashicorp/terraform-cdk#2882]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Debug Information:
language: python
cdktf-cli: 0.16.1
node: v18.16.0
cdktf: 0.16.1
constructs: 10.2.31
jsii: 1.82.0
terraform: 1.4.6
arch: arm64
os: darwin 22.4.0
python: Python 3.9.6
pip: null
pipenv: pipenv, version 2023.4.29

### Debug Output
https://gist.github.com/axecopfire/83c79ee2b0280190075b33411976411a

### Expected Behavior

Should be able to cdktf convert

### Actual Behavior

Above error

### Steps to Reproduce

download cdktf and run `cdktf convert` on a tf file

### References

- #0000

**Comment by justquick** [comment]
ditto. my setup:

```
language: python
cdktf-cli: 0.16.1
node: v18.14.0
cdktf: 0.16.1
constructs: 10.2.35
jsii: 1.82.0
terraform: 1.2.9
arch: x64
os: darwin 21.6.0
python: Python 3.10.8
pip: pip 23.1.2 from /Users/jquick/.asdf/installs/python/3.10.8/lib/python3.10/site-packages/pip (python 3.10)
pipenv: pipenv, version 2023.5.19
```

**Comment by mutahhir** [comment]
This should be resolved in the latest main and will be included in the next release. 

```python
from constructs import Construct
#
# Provider bindings are generated by running `cdktf get`.
# See https://cdk.tf/provider-generation for more details.
#
from imports.docker.container import Container
from imports.docker.image import Image
from imports.docker.provider import DockerProvider
class MyConvertedCode(Construct):
    def __init__(self, scope, name):
        super().__init__(scope, name)
        DockerProvider(self, "docker",
            host="unix:///var/run/docker.sock"
        )
        nginx = Image(self, "nginx",
            keep_locally=False,
            name="nginx:latest"
        )
        docker_container_nginx = Container(self, "nginx_2",
            image=nginx.name,
            name="tutorial",
            ports=[ContainerPorts(
                external=8000,
                internal=80
            )
            ]
        )
        # This allows the Terraform resource name to match the original name. You can remove the call if you don't need them to match.
        docker_container_nginx.override_logical_id("nginx")
```
