### ISSUE TITLE
`cloudflare` provider: 

### ISSUE THREAD

**Issue by mauricevancooten** [hashicorp/terraform-cdk#2884]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

CDKTF v0.14.3 TypeScript

### Affected Provider / Resource(s)

CloudFlare > WorkerScript

I'm wondering how to add the value for content, because it requires the script contents as a string. I tried putting the file name of the script but this doesn't work. 

This is how it should be for using Terraform without CDKTF, so how do I create the: file("script.js") in CDKTF?

```
resource "cloudflare_worker_script" "my_script" {
  account_id = "f037e56e89293a057740de681ac9abbe"
  name       = "script_1"
  content    = file("script.js")
```

**Comment by mauricevancooten** [comment]
Ok, I think I got it.
At the top import `fs`
```
import * as fs from 'fs'
```
In the worker script:
```
 new cloudflare.workerScript.WorkerScript(this, 'my-script', {
      accountId: 'f037e56e89293a057740de681ac9abbe',
      name: 'mauricevancooten-api',
      content: fs.readFileSync('script.js').toString(),
    })
```
Unless there's a better way to do it?

**Comment by xiehan** [comment]
Hi there:

We use GitHub issues for tracking bugs and enhancements, rather than for questions. While we can sometimes help with certain simple problems here, it's better to use [the community forum](https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47) where there are more people ready to help.

Thanks!
