### ISSUE TITLE
Escape hatch for filebase64sha256 can't find paths

### ISSUE THREAD

**Issue by Tirke** [hashicorp/terraform-cdk#292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
cdktf --version
0.0.13-pre.2f0b966cb25b6dc5066ee1551fdb32ff47a9c0fd
```

### Affected Resource(s)

Escape hatch

### Expected Behavior

Using an escape hatch for utility functions like `filebase64sha256` doesn't work as the function doesn't seem to be able to find paths, even when trying with absolute paths and also checking that all paths resolve to an actual file.

### Actual Behavior

```
Error: Unable to load "filebase64sha256(\"./lambda/lambda.zip\")": open filebase64sha256("./lambda/lambda.zip"): no such file or directory
```

### Steps to Reproduce

```typescript
 const lambda = new LambdaFunction(this, "cdk-tf-lambda", {
            filename: '../lambda/lambda.zip',
            functionName: 'cdk-tf',
            handler: 'index.handler',
            role: lambdaRole.arn,
            runtime: 'nodejs12.x'
        });
        lambda.addOverride('filename', 'filebase64sha256("./lambda/lambda.zip")')
```
I tried many paths including `./lambda/lambda.zip`, `../lambda/lambda.zip`, `${path.module}/lambda.zip`, `${path.cwd}/../lambda/lambda.zip`, nothing works.

**Comment by skorfmann** [comment]
> I tried many paths including `./lambda/lambda.zip`, `../lambda/lambda.zip`, `${path.module}/lambda.zip`, `${path.cwd}/../lambda/lambda.zip`, nothing works.

In this case, I'd use native JS tooling to get the correct path. Something like:

```ts
import * as path from 'path';

// ....

filename: path.join(__dirname, '../lambda/lambda.zip')
```

However, according to your description doesn't seem to be the issue here. Could you push a repo which demonstrates the issue? That'd make it much easier to debug.

**Comment by Tirke** [comment]
Yeah, as I said I tried many things, including using raw string paths, using node `path` module, etc with all formats relative / absolute, all actually resolving to an actual file and it doesn't work.
Repro : 
https://github.com/Tirke/tf-cdk-escape-path-bug

**Comment by skorfmann** [comment]
Thanks, I'll have a look later today.

**Comment by skorfmann** [comment]
This works for me:

```ts
        const lambda = new LambdaFunction(this, "cdk-tf-lambda", {
            filename: `${path.join(__dirname, 'lambda/lambda.zip')}`,
            functionName: 'cdk-tf',
            handler: 'index.handler',
            role: lambdaRole.arn,
            runtime: 'nodejs12.x'
        });
```

What I'm wondering is, what you're trying to achieve with this line:

```ts
lambda.addOverride('filename', `filebase64sha256(${path.join(__dirname, 'lambda/lambda.zip')})`)
```

The error suggests, that it's just interpreted as plain string. Then it makes total sense, that it can't be found:

```
Error: Unable to load "filebase64sha256(/Users/sebastian/projects/cdk/debug/tf-cdk-escape-path-bug/lambda/lambda.zip)": open filebase64sha256(/Users/sebastian/projects/cdk/debug/tf-cdk-escape-path-bug/lambda/lambda.zip): no such file or directory

  on cdk.tf.json line 72, in resource.aws_lambda_function.decimpmainstack_cdktflambda_491DE064:
  72:       }
```

Could you elaborate on what you're trying to do?

**Comment by Tirke** [comment]
I'm exploring cdk-tf capabilities for an article.

By the way, my example is wrong as I mentally switched `filename` with `sourceCodeHash`, this is why this issue makes no sense and I apologize for that.
I had no particular issue making the filename work without overriding the prop I'm just testing the override feature.
The override does work when using it with the intended prop `source_code_hash` and everything is cool.

If I can only suggest one thing, tf-cdk should warn users about the camelCase to snake_case thingy in the tool if it is possible, CLI UX is a bit rough ATM.

Thanks for you patience and apologies for wasting your time.

**Comment by skorfmann** [comment]
> Thanks for you patience and apologies for wasting your time.

No worries, glad it works as expected.

> If I can only suggest one thing, tf-cdk should warn users about the camelCase to snake_case thingy in the tool if it is possible

I think you're talking about this issue here? https://github.com/hashicorp/terraform-cdk/issues/235 That'll be worked on soonish. 

>, CLI UX is a bit rough ATM.

I absolutely agree, there's lots of room for improvement around the UX. We'll iterate on that based on a few ideas we still have in our backlog, but also based on community feedback. After all, community feedback is the main purpose of the current alpha release. 

We'd love to get more feedback, so please don't hesitate to create more issues :)
