### ISSUE TITLE
google: Adding labels via Aspects isn't working

### ISSUE THREAD

**Issue by strongishllama** [hashicorp/terraform-cdk#2928]
### Expected Behavior

With the following code, I'd expect the labels to be applied to the child constructs similar to AWS tags documented [here](https://developer.hashicorp.com/terraform/cdktf/concepts/aspects#define-aspects).

```ts
import { Construct } from "constructs";
import { TerraformStack } from "cdktf";
import { dnsManagedZone } from "@cdktf/provider-google";
import { GoogleProvider } from "@cdktf/provider-google/lib/provider";
import { ProjectService } from "@cdktf/provider-google/lib/project-service";

export class BootstrapStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new GoogleProvider(this, "google", {
      region: "PROJECT_REGION",
      project: "PROJECT_NAME",
    });
    new ProjectService(this, "project-service", {
      project: "PROJECT_NAME",
      service: "dns.googleapis.com",
    });

    new dnsManagedZone.DnsManagedZone(this, "zone", {
      dnsName: "DNS_NAME",
      name: "NAME",
    });

    Labels.add(this, {
      foo: "bar",
    });
  }
}

import { IConstruct } from "constructs";
import { Aspects, IAspect } from "cdktf";

type LabelableConstruct = IConstruct & {
  labels?: {
    [key: string]: string;
  };
};

function isLabelableConstruct(node: IConstruct): node is LabelableConstruct {
  return "labels" in node;
}

export class Labels implements IAspect {
  constructor(private readonly labels: Record<string, string>) {}

  visit(node: IConstruct): void {
    if (isLabelableConstruct(node)) {
      node.labels = { ...node.labels, ...this.labels };
    }
  }

  public static add(scope: IConstruct, labels: Record<string, string>) {
    Aspects.of(scope).add(new Labels(labels));
  }
}
```

### Actual Behavior

No tags are applied to the `DnsManagedZone` construct.

### Steps to Reproduce

1. Create a new CDKTF project from the Typescript template.
2. Add the Google provider.
3. Add the code from the "Expected Behaviour" section.
4. Run `cdktf diff` and see the tags are not added.

### Versions

language: typescript
cdktf-cli: 0.16.3
node: v18.12.1
cdktf: 0.16.3
constructs: 10.2.50
jsii: null
terraform: 1.4.5
arch: x64
os: darwin 22.5.0

### Providers

```
┌───────────────┬──────────────────┬─────────┬────────────┬────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name           │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼────────────────────────┼─────────────────┤
│ google        │ 4.68.0           │ ^0.16.3 │            │ @cdktf/provider-google │ 7.0.10          │
└───────────────┴──────────────────┴─────────┴────────────┴────────────────────────┴─────────────────┘
```

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @strongishllama 👋

Our Aspect docs use `node.tagsInput` to reference the current tags.

So in your case this line:
```
node.labels = { ...node.labels, ...this.labels };
```
would need to become
```
node.labels = { ...node.labelsInput, ...this.labels };
```

`.labels` always returns a Token to the labels at apply time whereas `.labelsInput` returns the value that was passed to the resource (if any)

**Comment by strongishllama** [comment]
Hey @ansgarm, thanks for the reply. Ah, I see where I went wrong there! I've implemented those changes (see below) but it's still not working. It's a bit hard to tell, but I think the `visit` method isn't being called?

```ts
import { IConstruct } from "constructs";
import { Aspects, IAspect } from "cdktf";

type LabelableConstruct = IConstruct & {
  labels?: {
    [key: string]: string;
  };
  labelsInput?: {
    [key: string]: string;
  };
};

function isLabelableConstruct(node: IConstruct): node is LabelableConstruct {
  return "labels" in node && "labelsInput" in node;
}

export class Labels implements IAspect {
  constructor(private readonly labels: Record<string, string>) {}

  public visit(node: IConstruct): void {
    if (isLabelableConstruct(node)) {
      node.labels = { ...this.labels, ...(node.labelsInput || {}) };
    }
  }

  public static add(scope: IConstruct, labels: Record<string, string>) {
    Aspects.of(scope).add(new Labels(labels));
  }
}
```

**Comment by ansgarm** [comment]
Hi @strongishllama 👋

Sorry for the late reply! If it's still a problem: Have you tried a `console.log` in the `visit` method to check whether it is in fact not called?
