### ISSUE TITLE
ckdtf-cli@next with python is broken

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- `cdktf-cli@next` (pre release) 
- Python

### Affected Resource(s)

- `init`

### Debug Output

![Screenshot 2020-08-07 at 16 36 27](https://user-images.githubusercontent.com/136789/89656847-766cef00-d8cc-11ea-8d72-948982664c6d.png)

### Expected Behavior

An `cdktf init --template python` should work when using a pre release of the cli

### Actual Behavior

it's exiting with an error, since we don't publish pre releases for python 

### Steps to Reproduce

- install `npm install -g cdktf-cli@next`
- run `cdktf init --template python --local`

**Comment by anubhavmishra** [comment]
We discussed this and we want to publish the next verbose version to PyPi for the users using the next version of the CLI.
