### ISSUE TITLE
DmsEndpointS3Settings: Empty value being sent for optional field timestamp_column_name

### ISSUE THREAD

**Issue by divakarpatil51** [hashicorp/terraform-cdk#2930]
### Expected Behavior

cdktf should send a null value or remove the key for optional field timestamp_column_name in s3_settings (Removed other keys for brevity purpose):

Expected Synth Output
```
"s3_settings": [
        {
                ...
                "timestamp_column_name": null
                ...
       }
 ]
```

### Actual Behavior

cdktf sends an empty string for optional field timestamp_column_name in s3_settings:

cmd:
`cdktf deploy "*" `

Error Output:
```
Error: creating DMS Replication Task : InvalidParameterValueException: TimestampColumnName cannot be an empty string.
status code: 400,
```

Synth Output:
```
"s3_settings": [
              {
                ...
                "timestamp_column_name": "",
               ...
              }
            ]
```

### Steps to Reproduce

Run following command to deploy the stack
cdktf deploy "*"

### Versions

language: python
cdktf-cli: 0.16.3
node: v18.14.0
cdktf: 0.16.3
constructs: 10.2.46
jsii: 1.83.0
terraform: 1.4.4
arch: x64
os: darwin 22.4.0
python: Python 3.11.3

### References

Same issue was filed on terraform-provider-aws:
https://github.com/hashicorp/terraform-provider-aws/issues/27283

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jsteinich** [comment]
cdktf shouldn't be applying an values for that attribute unless explicitly specified; however, the underlying AWS provider will apply defaults. You could try using `Token.null_value()` to explicitly produce `null` in the synthed output.

**Comment by jsteinich** [comment]
> @jsteinich Token.null_value() generates a null value that is not supported as argument for timestamp column.
> 
> ```
> TypeError: type of argument timestamp_column_name must be one of (str, NoneType); got jsii._reference_map.InterfaceDynamicProxy instead
> ```

Try `Token.as_string(Token.null_value())` which effectively casts the null token to a string.
