### ISSUE TITLE
cdktf-cli: Interactive prompt throws exception in devcontainer

### ISSUE THREAD

**Issue by lohrm-stabl** [hashicorp/terraform-cdk#2936]
### Expected Behavior

No exception

### Actual Behavior

After executing `cdktf init --template="typescript" --providers="aws@~>4.0"` I get asked whether I want to use Terraform Cloud remote state management. If I reply with Yes, the application crashes, probably because I am running this in a devcontainer.

AWS also uses sth similar with SSO (automatically open a browser window), but there it works fine. I would also be happy to click the link manually if the app would not crash immediately afterwards.

```bash
? Do you want to continue with Terraform Cloud remote state management? Yes

opening webpage using your browser.....

If the web browser didn't open the window automatically, you can go to the following url:
        https://app.terraform.io/app/settings/tokens?source=terraform-login

? Token for app.terraform.io 🔑 [input is hidden] /usr/local/share/npm-global/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [
    'https://app.terraform.io/app/settings/tokens?source=terraform-login'
  ]
}

```

### Steps to Reproduce

1. Create an empty vscode devcontainer project and install cdktf
2. Execute `cdktf init --template="typescript" --providers="aws@~>4.0"`

### Versions

Node.js v20.2.0
cdftf: 0.16.3

### Workarounds

Replying 'n' in when asked whether one want to use TF Cloud state management

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @lohrm-stabl 👋

I suspect crashes because it tries to open an interactive CLI to get ask for the token which somehow fails in the devcontainer and would need some investigation.

**Comment by lohrm-stabl** [comment]
A hot fix would be to just handle the error and don't crash the app, because the link is already provided. I can just click that myself.

**Comment by ansgarm** [comment]
Oh, yeah, you're right! I misinterpreted the error message, I'll create a PR with the fix you proposed 👍
