### ISSUE TITLE
Terraform produces missing Azure resource errors on synthesized TypeScript

### ISSUE THREAD

**Issue by bcline760** [hashicorp/terraform-cdk#295]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.0.13 - CDKTF
3.9.7 - Typescript

### Affected Resource(s)

Azure Provider

### Expected Behavior

No errors produced on apply

### Actual Behavior

I have to continually run `cdktf deploy` to deploy a simple resource group, virtual network, and subnet. Each time they fail with an error similar to this.
```
Error: Error Creating/Updating Subnet "default" (Virtual Network "cdk-test-vnet" / Resource Group "cdk-test"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Network/virtualNetworks/cdk-test-vnet' under resource group 'cdk-test' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"

  on cdk.tf.json line 102, in resource.azurerm_subnet.azure_subnet_ADA8A08A:
 102:       }
```

### Steps to Reproduce

Run `cdktf deploy` with this simple code block

```typescript
import { Construct } from 'constructs';
import { App, TerraformStack } from 'cdktf';
import { AzurermProvider, VirtualNetwork, SubnetA, ResourceGroup } from './.gen/providers/azurerm';

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new AzurermProvider(this, 'AzureRm', {
      features: [{}]
    });

    new ResourceGroup(this, 'rg', {
      location: 'westus',
      name: 'cdk-test'
    });

    new VirtualNetwork(this, 'vnet', {
      name: 'cdk-test-vnet',
      location: 'westus',
      addressSpace: ['10.4.0.0/24'],
      resourceGroupName: 'cdk-test'
    });

    new SubnetA(this, 'subnet', {
      addressPrefix: '10.4.0.0/27',
      name: 'default',
      resourceGroupName: 'cdk-test',
      virtualNetworkName: 'cdk-test-vnet'
    });
  }
}

const app = new App();
new MyStack(app, 'azure');
app.synth();
```

**Comment by skorfmann** [comment]
Hey @bcline760 - thanks for creating this issue. At a first glance, I'd guess that's due to the missing dependencies between the resources.

```ts
    const resourceGroup = new ResourceGroup(this, 'rg', {
      location: 'westus',
      name: 'cdk-test'
    });

    const network = new VirtualNetwork(this, 'vnet', {
      name: 'cdk-test-vnet',
      location: 'westus',
      addressSpace: ['10.4.0.0/24'],
      resourceGroupName: resourceGroup.name, // there's a bug which doesn't build the dependency here correctly, that's why we need an explict dependsOn
      dependsOn: [resourceGroup]
    });

    new SubnetA(this, 'subnet', {
      addressPrefix: '10.4.0.0/27',
      name: 'default',
      resourceGroupName: resourceGroup.name, // same issue as described above
      virtualNetworkName: network.name, // same issue as described above
      dependsOn: [resourceGroup, network]
    });
```
The bug mentioned in the code snippet is this one: #188

**Comment by bcline760** [comment]
Ah OK so the work around is to put the "dependsOn"?

**Comment by skorfmann** [comment]
> Ah OK so the work around is to put the "dependsOn"?

Yes, that should work.

**Comment by skorfmann** [comment]
Gonna close as duplicated of #188 - Please reopen if the workaround doesn't work.
