### ISSUE TITLE
Interactive prompt for state management on init wont let you select no for TF cloud

### ISSUE THREAD

**Issue by LiamLeane** [hashicorp/terraform-cdk#2952]
### Expected Behavior

When performing an init the question

`? Do you want to continue with Terraform Cloud remote state management? (Y/n)`

Is asked. Entering n should not use TF Cloud

### Actual Behavior

Any value entered at all (even invalid) results in yes being selected

`? Do you want to continue with Terraform Cloud remote state management? yes`

### Steps to Reproduce

1. cdktf init
2. Enter `n` for TF cloud question

### Versions

cdktf-cli: 0.17.0
node: v18.12.1
terraform: 1.3.6
arch: x64
os: win32 10.0.22621

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by matttylr** [comment]
Have just upgraded to 0.17.0 on my m1 macbook via brew. cdktf always chooses the positive answer regardless of what is entered:

```
mattt@xepi scratch % mkdir cdktfbug
mattt@xepi scratch % cd cdktfbug
mattt@xepi cdktfbug % cdktf init --template="typescript" --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
? Project Name cdktfbug
? Project Description A simple getting started project for cdktf.
? Do you want to start from an existing Terraform project? yes.   <--- I entered 'n' here
? Please enter the path to the Terraform project
? Do you want to send crash reports to the CDKTF team? Refer to https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/configuration-file#enable-crash-reporting-for-the-cli for more information yes.    <--- Also entered 'n' here
```

**Comment by andrewinci** [comment]
Same for me

**Comment by ozyman42** [comment]
Is there an older version of cdktf I can use when I don't want to be forced to select yes for everything?

**Comment by mutahhir** [comment]
Sorry for the delay on this. #2977 should solve the problem. We'll try to get a patch release out with the fix soon.
