### ISSUE TITLE
`cdktf init` failure with local version

### ISSUE THREAD

**Issue by kination** [hashicorp/terraform-cdk#2955]
### Expected Behavior

After install package from source in local, `cdktf xxx` should work correctly.

```
$ cd /path/to/source
$ yarn install
...
[4/4] 🔨  Building fresh packages...
$ husky install
husky - Git hooks installed

$ yarn build
...
 >  Lerna (powered by Nx)   Successfully ran target build for 7 projects (21s)

$ yarn link-packages
```

### Actual Behavior

Command failed as following

```
$ cdktf init
Error: Cannot find module 'node:util'
Require stack:
...
Collecting Debug Information...
node:internal/modules/cjs/loader:925
  const err = new Error(message);
              ^

Error: Cannot find module 'performance'
...
```

### Steps to Reproduce

1. yarn install
2. yarn build
3. cdktf init

### Versions

language: typescript
OS: MacOS (M1)
Golang: 1.20
Node: 16.14
cdktf version: master branch

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by kination** [comment]
I've checked contributing doc, and seems it needs `yarn package`.
But it failed with following
```
$ go version
go version go1.20.5 darwin/arm64

$ yarn package
yarn run v1.22.10
$ lerna run package && tools/collect-dist.sh
lerna notice cli v6.6.1

    ✔  cdktf:build  [existing outputs match the cache, left as is]
    ✔  @cdktf/commons:build  [existing outputs match the cache, left as is]
    ✔  @cdktf/commons:package (973ms)

    ✖  cdktf:package
$ jsii-pacmak && bash ./go-copyright-header.sh
       [xmldom warning]	attribute "NAME" missed value!! "NAME" instead!!
       @#[line:1,col:1]
       [xmldom warning]	attribute "NAME" missed value!! "NAME" instead!!
       @#[line:1,col:1]
       [xmldom warning]	attribute "NAME" missed value!! "NAME" instead!!
       @#[line:1,col:1]
       [jsii-pacmak] [WARN] Failed building go
       [jsii-pacmak] [WARN] go failed
       Error: Command (go build -modfile local.go.mod ./...) failed with status 1:
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR> go: module github.com/hashicorp/terraform-cdk-go/cdktf appears multiple times in workspace
       #STDERR>
       #STDOUT>
           at ChildProcess.<anonymous> (/Users/kination/workspace/oss/terraform-cdk/node_modules/jsii-pacmak/lib/util.js:175:27)
           at Object.onceWrapper (node:events:646:26)
           at ChildProcess.emit (node:events:526:28)
           at maybeClose (node:internal/child_process:1092:16)
           at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
error Command failed with exit code 1.
```

**Comment by mutahhir** [comment]
This is a known problem right now when using Go 1.20 because of go workspaces. If you would downgrade go to 1.18.10, this should work. As far as us supporting 1.20 is concerned, this is definitely something we'd like to do, but I'm not sure when we get to it.

**Comment by kination** [comment]
@mutahhir thanks for guide! This make it works.
But still I'm facing the same issue...

@xiehan sorry for confusing, but it looks not golang-related issue. Could you remove `language/golang` tag if okay?

**Comment by kination** [comment]
I've tried using Node 14, but it failed on install, because example packages require `node>=16`
https://github.com/hashicorp/terraform-cdk/blob/main/examples/typescript/aws-kubernetes/package.json#L18-L20

So I think it should
- Update pre-requisite: But maybe the reason of this failure can be node-16, so it should be proved first
- Allow examples to use node 14: Example can have dependency to node-16
- Ignore installing examples on `yarn build`

How do you think?

**Comment by mutahhir** [comment]
@kination can you provide a bit more information about what's failing? I wouldn't switch to Node 14 since that's no longer LTS.

**Comment by kination** [comment]
@mutahhir okay, for now...
- Build base on Node 14v is failing, due to requirements of example packages. As you've commented, seems it will be better to fix in "pre-requisite".
- After link local build packages with `yarn link-packages`, following command fails as:
```
cdktf init --template typescript --local
Error: Cannot find module 'node:util'
Require stack:
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2cdk/node_modules/jsii-rosetta/lib/translate.js
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2cdk/node_modules/jsii-rosetta/lib/index.js
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2cdk/lib/index.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2cdk/node_modules/jsii-rosetta/lib/translate.js:10:21)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19)
Collecting Debug Information...
node:internal/modules/cjs/loader:925
  const err = new Error(message);
              ^

Error: Cannot find module 'performance'
Require stack:
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2json/wasm/bridge_wasm_exec.js
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2json/lib/bridge.js
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2json/lib/index.js
- /Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2cdk/lib/index.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cmds/handlers.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf.js
- /Users/kination/workspace/oss/terraform-cdk/packages/cdktf-cli/bundle/bin/cdktf
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/kination/workspace/oss/terraform-cdk/packages/@cdktf/hcl2json/wasm/bridge_wasm_exec.js:14:28)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
```

**Comment by kination** [comment]
@mutahhir sorry for confusion. Seems there were some problem on my local node version. Now issue above is not happening.
But there are new problem as:
- In question `Do you want to start from an existing Terraform project? ` below, it is being setup as `yes` whether I select 'y' or 'N':
```
$ cdktf init --template typescript --local --dist
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.<STACK NAME>.tfstate' in the root of your project.
? Project Name cdktf-sample
? Project Description A simple getting started project for cdktf.
? Do you want to start from an existing Terraform project? (y/N)
...
```
- I've setup `CDKTF_DIST`, but it shows error messages at the end as following (but it creates templates well):
$ echo $CDKTF_DIST
/Users/kination/workspace/oss/terraform-cdk/dist

$ cdktf init --template typescript --local --dist
...
? Project Name cdktf-sample
? Project Description A simple getting started project for cdktf.
? Do you want to start from an existing Terraform project? yes
? Please enter the path to the Terraform project
? Do you want to send crash reports to the CDKTF team? Refer to https://developer.hashicorp.com/
terraform/cdktf/create-and-deploy/configuration-file#enable-crash-reporting-for-the-cli for more
 information yes
...
...
Usage Error: cannot use version 0.0.0, use --cdktf-version, --dist or CDKTF_DIST to install from a "dist" directory
```

Both looks like not critical issues, but for notice 🙏

**Comment by mutahhir** [comment]
Thanks for replying. The first issue with y/n should be resolved now. The latter issue seems to be a problem indeed. Can you create a new issue for this so we can track it better? Until then, please use `--dist` flag until we fix the environment variable.

I'm going to close this issue right now because the original problem was resolved.
