### ISSUE TITLE
Add 'iam' prefix to 'serviceAccount' export

### ISSUE THREAD

**Issue by strongishllama** [hashicorp/terraform-cdk#2965]
### Description
Hi there 👋

Currently, as the `serviceAccount` [export](https://github.com/cdktf/cdktf-provider-google/blob/920b417a41ac550b5789a0f5df414f42e2acb13f/src/index.ts#L587) doesn't have the service prefix like all the other exports, the following construct cannot be built by `jsii` and fails with following error.

I've tried several workarounds, such as:

- Using an `as` import like so:  `import { serviceAccount as iamServiceAccount } from "@cdktf/provider-google";`
- Creating a `BaseServiceAccount` class that creates the `serviceAccount` resource, and then extending it with a `ServiceAccount` subclass.

None of the above have worked.

I understand that the provider resources are generated, but would there be a way to add an override for the `serviceAccount` export, so it becomes `iamServiceAccount`? This would have two main benefits:

- Keeping a consistent naming conversion of `ServiceName-ResourceName`
- Allow for a cleaner looking interface when being able to use `ServiceAccount` as a class/construct name.

```ts
import { Construct } from "constructs";
import { serviceAccount } from "@cdktf/provider-google";

export interface ServiceAccountConfig {
  readonly accountId: string;
}

export class ServiceAccount extends Construct {
  public readonly grantMember: string;

  private readonly resource: serviceAccount.ServiceAccount;

  constructor(scope: Construct, id: string, config: ServiceAccountConfig) {
    super(scope, id);

    this.resource = new serviceAccount.ServiceAccount(this, "resource", {
      accountId: config.accountId,
    });

    this.grantMember = this.resource.member;
  }
}
```

```
service-account/service-account.ts:6:14 - error JSII5011: Submodule "serviceAccount" conflicts with "ServiceAccount, as different languages could represent it as: "serviceAccount", "ServiceAccount", "service_account""

6 export class ServiceAccount extends BaseServiceAccount {
               ~~~~~~~~~~~~~~

  ../../../node_modules/@cdktf/provider-google/lib/index.d.ts:584:13
    584 export * as serviceAccount from './service-account';
                    ~~~~~~~~~~~~~~
    This is the conflicting submodule declaration
```

Thanks in advance! 🙏

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
We follow the Terraform resource schema very closely to be predictable and avoid confusion. I am afraid you will need to find another name for the ServiceAccount in your local construct or do some workaround yourself (you could probably use a locally built provider and have a bash script replace the `export * as ...` statement if it's that important to you).
