### ISSUE TITLE
CDTKTF Python support for Poetry by default!

### ISSUE THREAD

**Issue by AaronSaikovski** [hashicorp/terraform-cdk#2967]
### Description

When creating a CDKTF project in Python. can you change the default package manager to use poetry instead of pipenv?
thanks

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @AaronSaikovski 👋

thank you for raising this! There's already https://github.com/hashicorp/terraform-cdk/issues/2838 that tracks this request.
I'll close this one as it is a duplicate – please ensure to upvote the other issue!
