### ISSUE TITLE
AWS: lambdaAuthorizerConfig setting in AppsyncGraphqlApi

### ISSUE THREAD

**Issue by bmilesp** [hashicorp/terraform-cdk#2971]
### Expected Behavior

lambdaAuthorizerConfig would not error and be present as expeted.

### Actual Behavior

Error: updating AppSync GraphQL API: BadRequestException: Lambda Authorizer Config missing

### Steps to Reproduce

1) Create the stack graphqlAPI necessary stack code:
```js
this.graphqlApi = new AppsyncGraphqlApi(this, config.name+'_graphql_api', {
            name: config.name+'_graphql_api', 
            authenticationType: config.appsync.authenticationType,
            additionalAuthenticationProvider: [
                {authenticationType: config.appsync.additionalAuthenticationType},
                {authenticationType: "AWS_LAMBDA"}
            ],
            lambdaAuthorizerConfig: {
                authorizerUri: lambdaArnForAuthorizer
            },
            userPoolConfig : {
                awsRegion : config.region,
                defaultAction : config.appsync.defaultAction,
                userPoolId : cognitoUserPoolId
            },
            schema: schemaFile.toString(),
            logConfig: {
                cloudwatchLogsRoleArn: iamResource.roles['appsyncServiceRole'].arn,
                fieldLogLevel: "ERROR"
            },
            tags: {
                name: config.name
            },
            xrayEnabled : true,
})
new LambdaPermission(this, stackName+"-lambdaAuthorizer", {
            statementId: stackName+"-lambdaAuthorizer",
            action: "lambda:InvokeFunction",
            principal: "appsync.amazonaws.com",
            sourceArn: lambdaArnForAuthorizer,
            functionName: lambdaFunctionNameForAuthorizer
 })
```
2)  deploy the stack

3) get error when deploying

### Versions

language: typescript
cdktf-cli: 0.16.1
node: v18.12.1
cdktf: 0.16.1
constructs: null
jsii: null
terraform: 1.5.0
arch: x64
os: linux 6.2.6-76060206-generic

### Providers
```
┌─────────────────────┬──────────────────┬─────────┬────────────┬─────────────────────────┬─────────────────┐
│ Provider Name       │ Provider Version │ CDKTF   │ Constraint │ Package Name            │ Package Version │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ franckverrot/stripe │ 1.9.0            │         │ ~>1.9.0    │                         │                 │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ aws                 │ 4.14.0           │         │ 4.14.0     │                         │                 │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ archive             │ 2.3.0            │ ^0.16.0 │            │ @cdktf/provider-archive │ 6.0.0           │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ aws                 │ 4.66.1           │ ^0.16.0 │            │ @cdktf/provider-aws     │ 14.0.4          │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ kreuzwerker/docker  │ 3.0.2            │ ^0.16.0 │            │ @cdktf/provider-docker  │ 7.0.0           │
├─────────────────────┼──────────────────┼─────────┼────────────┼─────────────────────────┼─────────────────┤
│ null                │ 3.2.1            │ ^0.16.0 │            │ @cdktf/provider-null    │ 6.0.0           │
└─────────────────────┴──────────────────┴─────────┴────────────┴─────────────────────────┴─────────────────┘
```

### Possible Solutions

None, I see the correct code in the cdktf.out/cdk.tf.json file:
```json
"lambda_authorizer_config": {
          "authorizer_uri": "${aws_lambda_function.devStack-appsyncStepFunction_LambdaStepFunctions_queryAppsync_ED414792.arn}"
},
```
### Workarounds

none. Everything seems to be present so i'm not sure where to start.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @bmilesp 👋

Are you still experiencing this? If yes, could you set the `TF_LOG` env var to `trace` and look for the HTTP 400 response that should be included in the log? Be careful when sharing it though, as these logs can contain API keys or other secrets.

**Comment by bmilesp** [comment]
> Hi @bmilesp 👋
> 
> Are you still experiencing this? If yes, could you set the `TF_LOG` env var to `trace` and look for the HTTP 400 response that should be included in the log? Be careful when sharing it though, as these logs can contain API keys or other secrets.

Hello @ansgarm,

I was able to change strategies and use IAM authorizers instead so I went that route to move forward, which I think logically is a better approach.

Thanks for getting back to me, and I will mark this as resolved.
