### ISSUE TITLE
No versions available for com.hashicorp:cdktf:jar when running jsii-pacmak

### ISSUE THREAD

**Issue by hansbarnard** [hashicorp/terraform-cdk#2996]
### Expected Behavior

When running jsii-pacmak including java as a target, a java jar package should be successfully generated for my constructs.

### Actual Behavior

When running jsii-pacmak I get the following error:
[ERROR] Failed to execute goal on project ipidp: Could not resolve dependencies for project com.clarivate:ipidp:jar:0.1.44: Failed to collect dependencies at com.hashicorp:cdktf-provider-aws:jar:15.0.0 -> com.hashicorp:cdktf:jar:[0.17.0,0.18.0): No versions available for com.hashicorp:cdktf:jar:[0.17.0,0.18.0) within specified range -> [Help 1]

The packaging tool downloads the metadata file from maven central:
[INFO] Downloaded from central: https://repo.maven.apache.org/maven2/com/hashicorp/cdktf/maven-metadata.xml (19 kB at 326 kB/s)

However, the file maven-metadata.xml does not contain any version of this jar for 0.17.0 or above. Instead it contains:
 <latest>0.15.0-pre.41</latest>

### Steps to Reproduce

1. run jsii-pacmak with java as a target.

### Versions

jsii: 1.84.0
cdktf: 0.17.0

### Possible Solutions

This used to work fine until yesterday. I suspect the metadata file was incorrectly updated.

### Workarounds

None

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by xiehan** [comment]
We're aware of the issue and this has happened a few times before in the past, most recently in January 2023; for some reason the `maven-metadata.xml` was reverted to an old cached version and as far as we know we didn't do anything to trigger that -- it seems to have happened on Maven's side. Unfortunately that means we're also dependent on them to fix it. We've opened a high-priority ticket with them so hopefully this will be addressed soon.

**Comment by Zman94** [comment]
Hello. Have there been any updates to this? Is the Maven ticket publicly available?

**Comment by hansbarnard** [comment]
I have not tested but I believe it has been fixed. At  least I saw the maven-metadata.xml file now contains all the versions.

**Comment by hansbarnard** [comment]
I've tested and for me it is working now.
