### ISSUE TITLE
API Reference Docs: How to get detail definitions of python APIs

### ISSUE THREAD

**Issue by kination** [hashicorp/terraform-cdk#2997]
### Description

Hello
I'm trying to make IaC logic with python, with similar architecture described in following typescript example https://github.com/cdktf/docker-on-aws-ecs-with-terraform-cdk-using-typescript

But to define `EcsCluster`, `SecurityGroup`, (or maybe more), I couldn't find out how to define key value for these classes.
```
...
def __cluster(self, scope, name):
        my_ecs_cluster = EcsCluster(
            self, 
            "my_ecs_cluster", 
            name = "My_Cluster",
            <???> = {
                name = name,
                capacityProviders: ["FARGATE"],
                tags = tags,
            }
            )
...
def __security(self, scope, name):
      lbSecurityGroup = new SecurityGroup(
      scope,
      `${name}-lb-security-group`,
      <???> = {
        vpcId = vpc.vpcIdOutput,
        tags,
```

In this case, what should be the key value of `<???>`

Are there some references I could check for these?

### Links

- https://github.com/cdktf/docker-on-aws-ecs-with-terraform-cdk-using-typescript

### Help Wanted

- [x] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
You can find some information in the documentation generated for the pre-built providers: https://github.com/cdktf/cdktf-provider-aws/blob/main/docs/API.python.md 


While this is not ideal, I still hope this helps :)

**Comment by kination** [comment]
@DanielMSchmidt thanks.
But when checking `ecsCluster` API, 
- typescript: https://github.com/cdktf/cdktf-provider-aws/blob/main/docs/ecsCluster.typescript.md
- python: https://github.com/cdktf/cdktf-provider-aws/blob/main/docs/ecsCluster.python.md

seems both shows pretty big difference.

AFAIK, terraform-cdk loads hcl from provider, and re-format to code. If it is, API should be pretty similar.
Could you confirm?

**Comment by DanielMSchmidt** [comment]
I don't really see much of a difference between these except for camelcase vs snake case, what are you referring to?
The API in Python is generated from the Typescript implementation, so yes they are similar

**Comment by kination** [comment]
@DanielMSchmidt 
Okay these are the issue I've found:
- Initializer API in ts has 3 params, while python has 16.
- And this looks like because `config(type -> EcsClusterConfig)` inside ts API has been flattened on python
- Because of this, in python API there are 2 params name as `id`
- Which one is correct?

**Comment by kination** [comment]
I've just checked imported python provider, and it seems:
```
def __init__(
        self,
        scope: _constructs_77d1e7e8.Construct,
        id_: builtins.str,
        *,
        name: builtins.str,
        configuration: typing.Optional[typing.Union["EcsClusterConfiguration", typing.Dict[builtins.str, typing.Any]]] = None,
        id: typing.Optional[builtins.str] = None,
        service_connect_defaults: typing.Optional[typing.Union["EcsClusterServiceConnectDefaults", typing.Dict[builtins.str, typing.Any]]] = None,
        setting: typing.Optional[typing.Union[_cdktf_9a9027ec.IResolvable, typing.Sequence[typing.Union["EcsClusterSetting", typing.Dict[builtins.str, typing.Any]]]]] = None,
        tags: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
        tags_all: typing.Optional[typing.Mapping[builtins.str, builtins.str]] = None,
        connection: typing.Optional[typing.Union[typing.Union[_cdktf_9a9027ec.SSHProvisionerConnection, typing.Dict[builtins.str, typing.Any]], typing.Union[_cdktf_9a9027ec.WinrmProvisionerConnection, typing.Dict[builtins.str, typing.Any]]]] = None,
        count: typing.Optional[typing.Union[jsii.Number, _cdktf_9a9027ec.TerraformCount]] = None,
        depends_on: typing.Optional[typing.Sequence[_cdktf_9a9027ec.ITerraformDependable]] = None,
        for_each: typing.Optional[_cdktf_9a9027ec.ITerraformIterator] = None,
        lifecycle: typing.Optional[typing.Union[_cdktf_9a9027ec.TerraformResourceLifecycle, typing.Dict[builtins.str, typing.Any]]] = None,
        provider: typing.Optional[_cdktf_9a9027ec.TerraformProvider] = None,
        provisioners: typing.Optional[typing.Sequence[typing.Union[typing.Union[_cdktf_9a9027ec.FileProvisioner, typing.Dict[builtins.str, typing.Any]], typing.Union[_cdktf_9a9027ec.LocalExecProvisioner, typing.Dict[builtins.str, typing.Any]], typing.Union[_cdktf_9a9027ec.RemoteExecProvisioner, typing.Dict[builtins.str, typing.Any]]]]] = None,
    ) -> None:
        '''Create a new {@link https://registry.terraform.io/providers/hashicorp/aws/5.8.0/docs/resources/ecs_cluster aws_ecs_cluster} Resource.
...
    config = EcsClusterConfig(
            name=name,
            configuration=configuration,
            id=id,
            service_connect_defaults=service_connect_defaults,
            setting=setting,
            tags=tags,
            tags_all=tags_all,
            connection=connection,
            count=count,
            depends_on=depends_on,
            for_each=for_each,
            lifecycle=lifecycle,
            provider=provider,
            provisioners=provisioners,
        )
```
looks like it makes `config` internally, with given resource. So document seems correct anyway.
Just a question, is there a reason that API of python has different param input with python?

And for `ModuleNotFoundError: No module named 'cdktf_cdktf_provider_aws'`, seems following works:
```
from imports.aws.ecs_cluster import EcsCluster
```

**Comment by jsteinich** [comment]
You can create an instance of the config type and pass that as a parameter, but generally the parameters are flattened in attempt to provide a more idiomatic experience.

The import used depends on if you are using a pre-built provider vs a locally generated provider.

**Comment by kination** [comment]
@jsteinich 
> You can create an instance of the config type and pass that as a parameter, but generally the parameters are flattened in attempt to provide a more idiomatic experience.

=> Thanks for notice

> The import used depends on if you are using a pre-built provider vs a locally generated provider.

=> Okay, when I've used option as --template="python", and install provider with `pipenv install cdktf-cdktf-provider-aws`, import can be called from `from cdktf_cdktf_provider_aws`. But when I use `cdktf init --template="python-pip" --local` template, and setup provider inside cdktf.json as
```
"terraformProviders": [
    "hashicorp/aws@~> 5.0"
],
```
and get packages with `cdktf get`, it should import by using `from imports.aws`.

- Is this expected result?
- It may confused to some users. Are there some plan to make unified rule?
- This is bit out of scope, but when I use `cdktf get` to install aws provider, it takes pretty much time to install packages... maybe it can be better to split providers, to install only required data (for example, getting only ecs related packages), if possible...

**Comment by jsteinich** [comment]
- It is expected that the import paths are different
- I don't believe there is any plan to change it; however, I certainly understand the confusion
- At the moment splitting packages isn't possible, though that idea has been proposed: https://github.com/hashicorp/terraform-cdk/issues/2892

**Comment by kination** [comment]
@jsteinich thanks for clarify.
> I don't believe there is any plan to change it; however, I certainly understand the confusion

=> Okay if there's no specific plan for this, I think it will be okay to close this ticket 🙏 but it will be better to add comment in document about this difference.

**Comment by jsteinich** [comment]
> => Okay if there's no specific plan for this, I think it will be okay to close this ticket 🙏 but it will be better to add comment in document about this difference.

Going to link to #831 and close this out then.
