### ISSUE TITLE
COMPONENT: Expose container timeouts on ecs task definitions

### ISSUE THREAD

**Issue by jsonmorris** [hashicorp/terraform-cdk#3009]
### Description

I would like to specify a `stopTimeout` on the container definition of an `ecsTaskDefinition`. There are currently no types exposed for that in cdktf, so I get this error.

```
... Argument of type '{ provider: AwsProvider; family: string; containerDefinitions: string; requiresCompatibilities: string[]; taskRoleArn: string; executionRoleArn: string; cpu: string; memory: string; networkMode: string; stopTimeout: number; }' is not assignable to parameter of type 'EcsTaskDefinitionConfig'.

  Object literal may only specify known properties, and 'stopTimeout' does not exist in type 'EcsTaskDefinitionConfig'.
  ```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @jsonmorris 👋

You should be able to use an [override / escape hatch](https://developer.hashicorp.com/terraform/cdktf/concepts/resources#escape-hatch) for this.

**Comment by jsonmorris** [comment]
Awesome, thank you!
