### ISSUE TITLE
missing dependency in `@cdktf/hcl2json`: `performance` package isn't installed but is required

### ISSUE THREAD

**Issue by sagilaufer1992** [hashicorp/terraform-cdk#3036]
### Expected Behavior

using version v0.17.3 should work smoothly without any other dependencies installed

### Actual Behavior

got the following error:
```
ERROR in ../../node_modules/.pnpm/@cdktf+hcl2json@0.17.3/node_modules/@cdktf/hcl2json/wasm/bridge_wasm_exec.js 14:27-49
Module not found: Error: Can't resolve 'performance' in '/tmp/seed/source/node_modules/.pnpm/@cdktf+hcl2json@0.17.3/node_modules/@cdktf/hcl2json/wasm'
resolve 'performance' in '/tmp/seed/source/node_modules/.pnpm/@cdktf+hcl2json@0.17.3/node_modules/@cdktf/hcl2json/wasm'
```

### Steps to Reproduce

- add version v0.17.3
- compile with webpack
- fail

### Versions

 "@cdktf/hcl2json": "0.17.3"

### Possible Solutions

add `performance` to the package's `package.json` file as a dependency

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @sagilaufer1992 👋

The `performance` package is [built into Node.js](https://nodejs.org/api/globals.html#performance) and requires Node.js 16 or later. It seems that Webpack might need an update ([similar to this one](https://github.com/webpack/webpack/pull/16841)) to add `performance` as it's currently [not in the list](https://github.com/webpack/webpack/blob/main/lib/node/NodeTargetPlugin.js#L13-L71) for the node target – but that's just a guess.

Depending on your Webpack config and version you might also be running into this: https://github.com/webpack/webpack/issues/11282

**Comment by sagilaufer1992** [comment]
we use an up-to-date version of webpack, and Node v16.x.x. so from your comment the issue is with my webpack configuration, and probably will require mending in it or in webpack itself (inserting it to the list above)?
