### ISSUE TITLE
Lambda: Add Python 3.11 to supported runtimes check

### ISSUE THREAD

**Issue by mgb-mat** [hashicorp/terraform-cdk#3044]
### Description

AWS now supports Python 3.11 for Lambda managed runtimes.
Current cdktf gives an error on "python3.11" value.

### References

- https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#SSS-CreateFunction-request-Runtime

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @mgb-mat 👋

Support for this runtime needs to be added to the AWS Terraform provider. There is an issue for this over there: https://github.com/hashicorp/terraform-provider-aws/issues/32817

I'd recommend to give that issue a thumbs-up to help that team prioritize it higher 👍

**Comment by mgb-mat** [comment]
Ohh lovely! Thanks for the info ^^
