### ISSUE TITLE
cdktf-cli: Output stack deploy order for segregated environment deployments

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#3054]
### Description

Hi,

It's been a short while since the cdktf-cli supports deploying multiple stacks within the same App, which is great. I was wondering if there was an easy solution to the problem I'm currently facing:

I can't have cdktf-cli/Terraform deploy from a role that has access to all of my accounts/environments. My security mandates won't allow it unfortunately. Alternatively, is there a way I can get what order my stacks should deploy, in order to ensure dependencies are handled properly? I could take this list and forward the deployments to the appropriate runners. 

I could imagine this list being generated at diff time? 

If this list already exists in the code, and just needs to be exported to the user, then I could potentially open a PR. 

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @rirze 👋

This exists in a quite raw form already and is part of the `synth` output: `cdktf.out/manifest.json` contains all stacks and their dependencies. It's not a sorted list though, so you'd still need a small script to parse that file and convert it into a list. You might need something similar already for the locations of each stack (also included in that file).

Let me know if that helps!

**Comment by rirze** [comment]
Gotcha, each stack's dependencies are shown in the manifest.json. So essentially, I would need to construct a DAG and use that to deploy, correct?

Thanks for the quick response btw!

**Comment by DanielMSchmidt** [comment]
Yes, that is also what we do internally. Whenever a dependency is done we walk the DAG to get the next stacks to run. I'm closing this since it seems to be answered 👍 If not feel free to reopen :)
