### ISSUE TITLE
Debug Command

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#306]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

For bug reports it would be good to have a dedicated command to get all relevant information we need:

- CLI version
- core package version
- constructs version
- jsii version 
- Terraform version
- node / Typescript version (and Python if relevant)
- provider version (or prebuilt package version)
- OS

**Comment by DanielMSchmidt** [comment]
I tried to solve the same problem with #693 do you think we can extend it to make it even more useful?

**Comment by skorfmann** [comment]
I think it would be useful to have a dedicated command along the lines of `cdktf debug-info` which allows people to collect more context for bugs or support requests. Wouldn't hurt to put these infos in the error handler built in #693 as well

**Comment by schersh** [comment]
could also address https://github.com/hashicorp/terraform-cdk/issues/1703
