### ISSUE TITLE
Examples:  the java project as example with maven does not compile.

### ISSUE THREAD

**Issue by ttais2017** [hashicorp/terraform-cdk#3067]
### Expected Behavior

The basic project with Java& Maven should compile and be able to be deployed 

This is the url of the project
https://github.com/hashicorp
/
[terraform-cdk](https://github.com/hashicorp/terraform-cdk) 

### Actual Behavior

the project does not compile.

### Steps to Reproduce

mvn compile

### Versions

Terraform v1.5.5
on windows_amd64

cdktf 0.17.3

### Possible Solutions

here the pom.xml fixed:
```

<!--
 Copyright (c) HashiCorp, Inc.
 SPDX-License-Identifier: MPL-2.0
-->

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.mycompany.app</groupId>
  <artifactId>aws</artifactId>
  <name>aws</name>
  <version>0.1</version>

  <properties>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf</artifactId>
      <version>0.17.3</version>
    </dependency>
    <dependency>
      <groupId>software.constructs</groupId>
      <artifactId>constructs</artifactId>
      <version>10.0.5</version>
    </dependency>
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf-provider-aws</artifactId>
      <version>6.0.5</version>
    </dependency>
  </dependencies>

  <build>
    <sourceDirectory>src/main/java</sourceDirectory>
    <testSourceDirectory>src/test/java</testSourceDirectory>

    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>

      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>1.6.0</version>
        <configuration>
          <mainClass>com.mycompany.app.Main</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

Here the java class also fixed:
```

/*
 * Copyright (c) HashiCorp, Inc.
 * SPDX-License-Identifier: MPL-2.0
 */

package com.mycompany.app;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import com.hashicorp.cdktf.App;
import com.hashicorp.cdktf.TerraformOutput;
import com.hashicorp.cdktf.TerraformStack;

import com.hashicorp.cdktf.providers.aws.AwsProvider;
import com.hashicorp.cdktf.providers.aws.datasources.DataAwsRegion;
import com.hashicorp.cdktf.providers.aws.dynamodb.DynamodbTable;
import com.hashicorp.cdktf.providers.aws.dynamodb.DynamodbTableAttribute;
import com.hashicorp.cdktf.providers.aws.sns.SnsTopic;
import software.constructs.Construct;

public class Main extends TerraformStack {
    public Main(final Construct scope, final String id) {
        super(scope, id);

        AwsProvider.Builder.create(this, "aws").region("eu-central-1").build();

        DataAwsRegion region = new DataAwsRegion(this, "region");

        DynamodbTable table = DynamodbTable.Builder.create(this, "Hello").name("my-first-table-" + region.getName())
                .hashKey("temp").attribute(Arrays.asList(DynamodbTableAttribute.builder().name("id").type("S").build()))
                .billingMode("PAY_PER_REQUEST").build();

        table.addOverride("hash_key", "id");
        table.addOverride("lifecycle", Collections.singletonMap("create_before_destroy", true));

        final int topicCount = 1;
        List<SnsTopic> topics = IntStream.range(0, topicCount)
                .<SnsTopic>mapToObj(
                        i -> SnsTopic.Builder.create(this, "Topic" + i).displayName("my-first-sns-topic" + i).build())
                .collect(Collectors.toList());

        TerraformOutput.Builder.create(this, "table_name").value(table.getName()).build();

        for (int i = 0; i < topics.size(); i++) {
            TerraformOutput.Builder.create(this, "sns_topic" + i).value(topics.get(i).getName()).build();
        }
    }

    public static void main(String[] args) {
        final App app = new App();
        new Main(app, "aws");
        app.synth();
    }
}
```

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by karlbennett** [comment]
To be more specific, all of the `*Config` interfaces are generated with compilation errors. This is even present in the [com.hashicorp:cdktf-provider-aws](https://central.sonatype.com/artifact/com.hashicorp/cdktf-provider-aws/16.0.9) library that is currently deployed to maven central.

The bellow image shows one of the compilation errors in the `AccessanalyzerAnalyzerConfig` class from the source downloaded from the `cdktf-provider-aws` maven library.
![image](https://github.com/hashicorp/terraform-cdk/assets/135296/1090464e-20ec-4131-b604-c16594d7dff5)

Here is the compiled class file, you can see that the IDE cannot figure out which type the `Builder` class is.
![image](https://github.com/hashicorp/terraform-cdk/assets/135296/455c89a7-3119-4f30-af3c-88f9688ffe32)
![image](https://github.com/hashicorp/terraform-cdk/assets/135296/5f2c4c0f-e5ef-43c9-9bcf-a26524d50766)

It is a mystery how this code could have ever been successfully compiled and then deployed to maven central.

To help people at least get something working, could we maybe please be shown the steps used to compile the `cdktf-provider-aws` library?

**Comment by ansgarm** [comment]
Hi @ttais2017 👋

Thank you for raising this and thank you for the fixed files. While reading them I noticed that the following dependency seems outdated:
```
<dependency>
  <groupId>com.hashicorp</groupId>
  <artifactId>cdktf-provider-aws</artifactId>
  <version>6.0.5</version>
</dependency>
```
which is probably why you had to change the imports in the other files.

The [current](https://github.com/cdktf/cdktf-provider-aws/releases) major version of the pre-built provider for AWS is `19` and there have been changes since `6.0.5` that affected the names of packages and thus imports.

The example you linked uses locally build provider bindings to allow us to run the examples in CI and confirm they work. You can generate the code for them by running `cdktf get`.

I just tried this with the latest version of CDKTF and the code compiled successfully.

As this issue might be outdated by now, I'm going to close it. But feel free to create a new one, if you're still running into issues.
