### ISSUE TITLE
Upgrade to 17.3.1 Typescript CDKTF fails to synth

### ISSUE THREAD

**Issue by jin-ahn** [hashicorp/terraform-cdk#3094]
### Expected Behavior
    new AwsProvider(this, "aws", {
      region: this.region,
      profile: this.profile,
      assumeRole: {
        roleArn: config.cdktfrole ?? "",
      },
    });

cdktf synth should complete successfully

### Actual Behavior

Run ckdtf synth returns following error

`TypeError: Cannot read properties of undefined (reading 'required_providers')`

### Steps to Reproduce

1. Run cdktf synth

### Versions

cdktf debug
language: typescript
cdktf-cli: 0.17.3
node: v20.5.1
cdktf: null
constructs: 10.2.69
jsii: null
terraform: 1.5.5
arch: arm64
os: darwin 22.5.0

### Providers

 ┌───────────────┬──────────────────┬─────────┬────────────┬────────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name               │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼────────────────────────────┼─────────────────┤
│ aws           │ 5.12.0           │ ^0.17.0 │            │ @cdktf/provider-aws        │ 16.0.7          │
├───────────────┼──────────────────┼─────────┼────────────┼────────────────────────────┼─────────────────┤
│ kubernetes    │ 2.23.0           │ ^0.17.0 │            │ @cdktf/provider-kubernetes │ 8.0.1           │
└───────────────┴──────────────────┴─────────┴────────────┴────────────────────────────┴─────────────────┘

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jin-ahn** [comment]
@DanielMSchmidt Actually I found out the cause of the issue is related to this https://github.com/hashicorp/terraform-cdk/issues/1739

To summarize 
```
const app = new App()
const stack = new TerraformStack(app, 'stack');
const eks1 = new EKSCluster(stack, 'eks1', {
...
}
const eks2 = new EKSCluster(stack, 'eks2', {
...
}
app.synth();
```
I originally made app to make a stack, and I added multiple eks clusters to that one stack. The problem is now that I have a stack called "stack" in cdktf.out that does not have "required_providers" since it's not actual a terraform_stack

the cdk.tf.out of "stack" is this
```
  "//": {
    "metadata": {
      "backend": "local",
      "stackName": "anedot",
      "version": "0.17.3"
    },
    "outputs": {
    }
  }
}

```

Is there a way to force add a required_provider? that would be the only work around at this point i believe.

**Comment by DanielMSchmidt** [comment]
To get required_providers you need to have a provider on that stack, e.g. aws:

```ts
const app = new App()
const stack = new TerraformStack(app, 'stack');
new AwsProvider(stack, "aws", {
  region: "us-west-2"
});
const eks1 = new EKSCluster(stack, 'eks1', {
...
}
const eks2 = new EKSCluster(stack, 'eks2', {
...
}
app.synth();
```

**Comment by jin-ahn** [comment]
Doing this will change the state of the ekscluster completely so it would destroy and recreate them. is there around this?

**Comment by DanielMSchmidt** [comment]
Yes, this guide on refactoring state from one stack to another talks about it: https://developer.hashicorp.com/terraform/cdktf/examples-and-guides/refactoring#moving-resources-from-one-stack-to-another

Closing this for now, there seems to be no open problems left, please post on Discuss for usage questions: https://discuss.hashicorp.com/c/terraform-core/cdk-for-terraform/47

**Comment by jin-ahn** [comment]
@DanielMSchmidt the linked resources does not apply to the current situation.
I am not trying to move resources from one stack to another, i am trying to move entire stacks to another stack. 

The structure is currently
app -> stack (no provider) -> stack-eks1(with provider),stack-eks2(with provider)

But I need to go to either one of the following
1. app -> stack (with provider) -> stack-eks1(with provider),stack-eks2(with provider)
2. app -> stack-eks1(with provider),stack-eks2(with provider)

The issue is doing either will make cdktf think stack-eks1 needs to be destroyed and rebuilt entirely. I need to be able to update the higher level stack/app while making stack-eks1,stack-eks2 remain the same.
