### ISSUE TITLE
Convert: Convert error using Nutanix provider and Golang

### ISSUE THREAD

**Issue by abstractalchemist** [hashicorp/terraform-cdk#3111]
### Expected Behavior

Generate cdk code for nutanix provider.

### Actual Behavior

Errors out.  See attached Gist down belowcd

### Steps to Reproduce

1.  get-content main.tf | cdktf convert --language go --provider nutanix/nutanix@1.9.0

### Versions

cdktf debug
language: go
cdktf-cli: 0.18.0
node: v18.16.1
cdktf: 0.18.0
constructs: 10.1.167
jsii: 1.87.0
terraform: 1.5.4
arch: x64
os: win32 10.0.19044
go: go version go1.21.0 windows/amd64

### Providers

┌─────────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name   │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├─────────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ nutanix/nutanix │ 1.9.0            │       │ 1.9.0      │              │                 │
└─────────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Gist

https://gist.github.com/abstractalchemist/95527a754e9a9a54488534f6f95f1cc1

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mutahhir** [comment]
Can you provide us a redacted version of your main.tf file that we can use to reproduce this issue? Thanks!
