### ISSUE TITLE
azurerm.virtual_network: when the dns_servers attribute changes to 'None' it doesn't detect/remove the previous specified dns server list attributes

### ISSUE THREAD

**Issue by Mejato** [hashicorp/terraform-cdk#3113]
### Expected Behavior

When you construct a VirtualNetwork and specify the dns_servers list attributes it deploys as expected.

```
azure_virtual_network = VirtualNetwork(self._resource_parent_object,
                                                       id_=v.name.format(self._resource_prefix),
                                                       name=v.name.format(self._resource_prefix),
                                                       address_space=[v.cidr],
                                                       location=self._location,
                                                       resource_group_name=self._resource_group_lookup[v.resource_group_link].name,
                                                       dns_servers=[10.0.1.10],
                                                       provider=self._azurerm_provider)
```
After initial deployment, if the dns_servers attribute is changed to None, it doesn't detect/remove the virtual network DNS configuration change. I.e., default back to (Azure-provided) configuration.

```
azure_virtual_network = VirtualNetwork(self._resource_parent_object,
                                                       id_=v.name.format(self._resource_prefix),
                                                       name=v.name.format(self._resource_prefix),
                                                       address_space=[v.cidr],
                                                       location=self._location,
                                                       resource_group_name=self._resource_group_lookup[v.resource_group_link].name,
                                                       dns_servers=None,
                                                       provider=self._azurerm_provider)
```

### Actual Behavior

After initial deployment, if the dns_servers attribute is changed to None, it doesn't detect/remove the virtual network DNS configuration change. I.e., default back to (Azure-provided) configuration.

### Steps to Reproduce

See steps in expected behaviour.

### Versions

language: python
cdktf-cli: 0.17.0
node: v18.17.1
cdktf: 0.17.0
constructs: 10.2.63
jsii: 1.86.1
terraform: 1.5.6
arch: x64
os: linux 6.2.0-31-generic
python: Python 3.10.12
pip: pip 22.3.1 /lib/python3.10/site-packages/pip (python 3.10)
pipenv: pipenv, version 2023.6.26

### Providers

┌───────────────┬──────────────────┬─────────┬────────────┬──────────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name                 │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼──────────────────────────────┼─────────────────┤
│ azure/azapi   │ 1.8.0            │         │ ~> 1.8     │                              │                 │
├───────────────┼──────────────────┼─────────┼────────────┼──────────────────────────────┼─────────────────┤
│ azurerm       │ 3.67.0           │ ^0.17.0 │            │ cdktf-cdktf-provider-azurerm │ 9.0.5           │
└───────────────┴──────────────────┴─────────┴────────────┴──────────────────────────────┴─────────────────┘

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by mutahhir** [comment]
The Azure provider with CDKTF seems to be a bit picky about passing `None`. Can you instead try to pass `Token.null_value()` and see if you get the desired result?

**Comment by Mejato** [comment]
Thanks @mutahhir , I'll give it a try and will let you know.
