### ISSUE TITLE
firestore-document: Error creating Document: googleapi: Error 400: Missing routing header

### ISSUE THREAD

**Issue by garysassano** [hashicorp/terraform-cdk#3117]
### Expected Behavior

```py
class FirestoreDatabaseStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)

        GCP_PROJECT_ID = os.environ.get("GCP_PROJECT_ID")
        GCP_REGION = os.environ.get("GCP_REGION")

        GoogleProvider(
            self,
            "GoogleProvider",
            project=GCP_PROJECT_ID,
            region=GCP_REGION,
            credentials=os.path.abspath("credentials.json"),
        )

        # Enable Cloud Firestore API for the project
        cloud_firestore_api = ProjectService(
            self,
            "CloudFirestoreAPI",
            service="firestore.googleapis.com",
            disable_on_destroy=True,
        )

        firestore_database = FirestoreDatabase(
            self,
            "FirestoreDatabase",
            name="database2",
            location_id=GCP_REGION,
            type="FIRESTORE_NATIVE",
            concurrency_mode="OPTIMISTIC",
            app_engine_integration_mode="DISABLED",
            depends_on=[cloud_firestore_api],
        )

        document = FirestoreDocument(
            self,
            "FirestoreDocument_document",
            database=firestore_database.name,
            document_id="document",
            collection="collection",
            fields=json.dumps({"key-1": {"stringValue": "value-1"}}),
            depends_on=[cloud_firestore_api],
        )
```

### Actual Behavior

```sh
│ Error: Error creating Document: googleapi: Error 400: Missing routing header. Please fill in the request header with format x-goog-request-params:project_id=foobar-df2d4&database_id=database2. Please refer to https://firebase.google.com/docs/firestore/manage-databases#access_a_named_database_with_a_client_library for more details.
│ 
│   with google_firestore_document.FirestoreDocument_document (FirestoreDocument_document),
│   on cdk.tf.json line 54, in resource.google_firestore_document.FirestoreDocument_document (FirestoreDocument_document):
│   54:       }
```

### Steps to Reproduce

1. cdktf deploy
2. Enjoy error from missing header

### Versions

language: python
cdktf-cli: 0.18.0

### Providers

┌───────────────┬──────────────────┬─────────┬────────────┬─────────────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name                │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼─────────────────────────────┼─────────────────┤
│ google        │ 4.80.0           │ ^0.18.0 │            │ cdktf-cdktf-provider-google │ 9.0.1           │
└───────────────┴──────────────────┴─────────┴────────────┴─────────────────────────────┴─────────────────┘

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi 👋

This error is an upstream problem happening in the Terraform Google Provider. Here's the related issue: https://github.com/hashicorp/terraform-provider-google/issues/15550
