### ISSUE TITLE
Availability Zones in AWS cannot be queried

### ISSUE THREAD

**Issue by ttais2017** [hashicorp/terraform-cdk#3123]
### Expected Behavior

The list of Availability Zones within a Region in AWS can be queried, in order to create subnetworks inside a VPC

### Actual Behavior

using this code:

![image](https://github.com/hashicorp/terraform-cdk/assets/26426283/badae405-b1e0-4965-a95c-4a58fe366c86)

the stack cannot be deployed, due to this internal error:

![image](https://github.com/hashicorp/terraform-cdk/assets/26426283/4bf64ede-0583-47ff-9631-8570fdfd9cc2)

### Steps to Reproduce

use the provided code

### Versions

cdktf debug
language: java
cdktf-cli: 0.18.0
node: v18.17.1
cdktf: null
constructs: null
jsii: null
terraform: 1.5.5
arch: x64
os: win32 10.0.22621
java:
maven: Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)Maven home: C:\Dev\Software\apache-maven-3.9.3Java version: 17.0.8, vendor: Eclipse Adoptium, runtime: C:\Dev\Software\java\jdk-17.0.8+7Default locale: de_DE, platform encoding: Cp1252OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"
gradle: ------------------------------------------------------------Gradle 8.3------------------------------------------------------------Build time:   2023-08-17 07:06:47 UTCRevision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5Kotlin:
    1.9.0Groovy:       3.0.17Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023JVM:          17.0.8 (Eclipse Adoptium 17.0.8+7)OS:           Windows 11 10.0 amd64

### Providers

AWS, local

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
You can not use native-language loops like a for loop on a list returned from a construct. These lists are only available at runtime, whereas the for loop runs at compile time, so you only get a [token](https://developer.hashicorp.com/terraform/cdktf/concepts/tokens) back. Instead you should use [iterators](https://developer.hashicorp.com/terraform/cdktf/concepts/iterators), they are built for this purpose. Hope this helps 👍
