### ISSUE TITLE
COMPONENT: Eks module does not support tagsInput attribute

### ISSUE THREAD

**Issue by airlangga-gunawan-faculty** [hashicorp/terraform-cdk#3132]
### Expected Behavior

I am using the [Aspect resource](https://developer.hashicorp.com/terraform/cdktf/concepts/aspects) in order to define a single place in the code when tags are added to (what I thought would be) all resources in a stack.

What we're finding out is that tags are not applied to EKS resources, and in turn, the EC2 resources within an EKS cluster. 

### Actual Behavior

Tags are not applied to EKS cluster, and EC2 resources underpinning the EKS cluster.

### Steps to Reproduce

1. Create EKS resource using `cdktf_modules.eks.Eks` resource in a stack
2. Add Aspect to add tags in the same stack
3. Notice that no tags are applied to the EKS cluster, or the EC2 resources.

### Versions

language: python
cdktf-cli: 0.16.3
node: v18.16.0
cdktf: 0.16.3
constructs: 10.2.70
jsii: 1.88.0
terraform: 1.4.6
arch: arm64
os: darwin 22.6.0
python: Python 3.11.3
pip: pip 23.1.2 from /Users/airlanggagunawan/Documents/git/infrastructure-cdktf/.venv/lib/python3.11/site-packages/pip (python 3.11)
pipenv: null

### Possible Solutions

The reason for this is that the EKS resource from `cdktf_modules.eks.Eks` has a `tags` attribute but not a `tags_input` attribute. By Terraform's own examples, the Aspect requires both of these attributes to exist in order to apply the tag.

### Anything Else?

Can we please add the `tags_input` attribute to the EKS module (and more widely, to more modules?) 

### References

https://developer.hashicorp.com/terraform/cdktf/concepts/aspects

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @airlangga-gunawan-faculty 👋

Where does `cdktf_modules` come from? Aspects can't access resources in Terraform modules unfortunately as these resources are not CDKTF constructs, maybe that's the case here?

**Comment by airlangga-gunawan-faculty** [comment]
Yes, I think you are right. In any case, we found a workaround which may help others who want to propagate tags through to Terraform modules (and the resources they provision). 
Modify the Aspect from [the tutorial](https://developer.hashicorp.com/terraform/cdktf/concepts/aspects) to add the new block:
```
    # This method is called on every Construct within the specified scope
    # (resources, data sources, etc.).
    def visit(self, node: IConstruct):

        # Handle cdktf modules
        if isinstance(node, TerraformModule) and hasattr(node, "tags"):
            # Update existing dict in place if not empty, else pass in entire dict
            if node.tags is not None:
                node.tags |= self.tags_to_add
                return
            node.tags = self.tags_to_add
            return

        # Handle normal cdktf resources
        if (
            hasattr(node, "tags")
            and hasattr(node, "tags_input")  # noqa: W503
            and getattr(node, "terraform_resource_type")  # noqa: W503
        ):
            # We need to take the input value to not create a circular reference
            current_tags = node.tags_input if node.tags_input is not None else {}
            node.tags = {**self.tags_to_add, **current_tags}
            return
```
