### ISSUE TITLE
AWS provider: appsync datasource deltasyncconfig and resolver templates

### ISSUE THREAD

**Issue by xxjt123xx** [hashicorp/terraform-cdk#3140]
### Description

I need the delasync config and maybe you can also include some resolver templates that AWS CDK includes

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource?lang=typescript#deltaSyncConfig

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @xxjt123xx 👋 

Could you explain a bit more what you are missing? Is this a request for documentation?

**Comment by xxjt123xx** [comment]
I see in the docs that the delta sync config exists but in the code it says that it does not exist

**Comment by xxjt123xx** [comment]
maybe this needs to live in typescript provider. https://github.com/hashicorp/terraform-cdk/issues/3141

**Comment by ansgarm** [comment]
Can you share the error message and the versions you are using? The property exists in the generated code for the AWS Terraform Provider:
https://github.com/cdktf/cdktf-provider-aws/blob/782239c1d0bb37e5ba6073755729cfedcb08d218/src/appsync-datasource/index.ts#L223

**Comment by xxjt123xx** [comment]
this is working now in typescript for me.
