### ISSUE TITLE
AWS provider: missing attributes from cognito and appsync

### ISSUE THREAD

**Issue by xxjt123xx** [hashicorp/terraform-cdk#3141]
### Expected Behavior

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool_client?lang=typescript#explicitAuthFlows

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_datasource?lang=typescript#deltaSyncConfig

### Actual Behavior

attributes don't exist

### Steps to Reproduce

leverage typescript cdktf and try adding these attributes 

### Versions

"@cdktf/provider-aws": "^17.0.6",
"cdktf": "^0.18.0",

### Providers

AWS

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @xxjt123xx 👋

Could you share a bit more about the error you are getting? I just tried to reproduce this with the versions you specified and it worked. You can find the code here: https://github.com/ansgarm/cdktf-aws-missing-attrs

**Comment by xxjt123xx** [comment]
These are working now in typescript. thanks
