### ISSUE TITLE
lib: Support `terraform_data` built-in resource

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#3142]
### Description

Terraform 1.4 added support for a built-in `terraform_data` resource which can be used instead of the `null` resource. We should support it, too!

Note: We should ensure `convert` supports this as well!

### References

Terraform PR: https://github.com/hashicorp/terraform/pull/31757
Terraform Docs: https://developer.hashicorp.com/terraform/language/resources/terraform-data
Discuss thread asking for CDKTF support: https://discuss.hashicorp.com/t/how-to-use-terraform-data-in-cdk-tf/58390

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by pauldraper** [comment]
Including @ansgarm's workaround here:

```tf
stack.addOverride("resource.terraform_data.replacement", {
  input: revision
})
```
