### ISSUE TITLE
Error: unknown type {"nesting_mode":"single"}

### ISSUE THREAD

**Issue by patrickcping** [hashicorp/terraform-cdk#3144]
### Expected Behavior

Running [CDKTF Getting Started](https://developer.hashicorp.com/terraform/tutorials/cdktf/cdktf-install) but instead replacing the docker provider with the `pingidentity/pingone` provider, expecting project to initialise successfully.

### Actual Behavior

Error returned:

```
[2023-09-25T09:57:54.000] [INFO] default - Adding local provider registry.terraform.io/pingidentity/pingone with version constraint undefined to cdktf.json
Local providers have been updated. Running cdktf get to update...
Error: unknown type {"nesting_mode":"single"}
    at w$.renderAttributeType (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:70757)
    at w$.renderAttributesForBlock (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:71060)
    at w$.resourceFrom (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:68376)
    at iS.parse (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:94:74117)
    at /usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12793
    at Array.map (<anonymous>)
    at aS.buildResourceModels (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12760)
    at aS.emitProvider (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:13308)
    at aS.generate (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:95:12338)
    at X$.generateTypescriptProvider (/usr/local/Cellar/cdktf/0.18.0/libexec/lib/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:101:17429)
⠏ downloading and generating modules and providers...
Error: unknown type {"nesting_mode":"single"}
```

### Steps to Reproduce

1. `cdktf init --template=java --providers=pingidentity/pingone --local`

### Versions

language: java
cdktf-cli: 0.18.0
node: v20.6.1
cdktf: 0.18.0
constructs: 10.0.25
jsii: null
terraform: 1.5.7
arch: x64
os: darwin 22.6.0
java: 
maven: null
gradle: ------------------------------------------------------------Gradle 8.3------------------------------------------------------------Build time:   2023-08-17 07:06:47 UTCRevision:     8afbf24b469158b714b36e84c6f4d4976c86fcd5Kotlin:       1.9.0Groovy:       3.0.17Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023JVM:          20.0.2.1 (Amazon.com Inc. 20.0.2.1+10-FR)OS:           Mac OS X 13.5.2 x86_64

### Providers

┌──────────────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name        │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├──────────────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ pingidentity/pingone │                  │       │ ~> 0.21    │              │                 │
└──────────────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Anything Else?

- Provider muxes v5 and v6 TF protocol resources/data sources

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @patrickcping 👋

Thank you for raising this. I just fetched the schema for the latest (`=0.21.0`) `pingidentity/pingone` provider. There seems to be this attribute in the `pingone_risk_predictor` resource:
```json
"predictor_bot_detection": {
                "nested_type": {
                  "nesting_mode": "single"
                },
                "description": "A single nested object that specifies options for the Bot Detection predictor.  At least one of the following must be defined: `predictor_anonymous_network`, `predictor_bot_detection`, `predictor_composite`, `predictor_custom_map`, `predictor_device`, `predictor_geovelocity`, `predictor_ip_reputation`, `predictor_user_location_anomaly`, `predictor_user_risk_behavior`, `predictor_velocity`.",
                "description_kind": "markdown",
                "optional": true
              },
```

CDKTF currently expects `nested_type` to have `attributes` defined but it seems that this property is missing a them here. From the description it seems like there are supposed to be attributes that can be set on that object.

We'd need to have a look at the underlying Terraform provider to figure out why there's no schema for any attributes here.

From your Github profile it seems like you are working the Terraform provider as well, right?

**Comment by patrickcping** [comment]
Hi @ansgarm 👋 

Yes I'm the primary maintainer for the PingOne provider project!  You're correct, `predictor_bot_detection` doesn't have any child attributes defined today, but there may be in the future.  Currently, just the presence of `predictor_bot_detection = {}` in the HCL is enough to define this predictor type.

It was a design choice to use this syntax in place of the API's `type` = `BOT_DETECTION` value because we can better control required/optional/computed schema validation this way, and makes for a better user experience when developing HCL through the registry documentation.

Since the plugin framework allows this configuration in the provider, is this something the CDK could also allow?

**Comment by ansgarm** [comment]
Hi @patrickcping 👋

Thanks for explaining this! Makes sense!

Yes, that's definitely something we should support then. I'll bring this up for prioritization internally. We're of course open to contributions here, if you're keen to override the timeline of this getting implemented 😉 However, the provider-generator isn't the simplest part of our code base to be fair.
