### ISSUE TITLE
Include homebrew support for using tfenv as an optional dependency instead of terraform

### ISSUE THREAD

**Issue by schematis** [hashicorp/terraform-cdk#3148]
### Description

We have to support multiple versions of terraform on our macs depending on our terraform cloud provider (scalr) as they're usually a minor version or two behind the current release. As a software architect I'm almost never running Node for projects and would prefer to keep my tools in homebrew for convenience.

I am aware of [the prior issue that looked at this](https://github.com/hashicorp/terraform-cdk/issues/475), but that issue has been closed. In that issue it was commented that there was no way to do either/or dependencies of terraform vs tfenv., but it has since been added in.

[According to the docs](https://docs.brew.sh/Formula-Cookbook#adding-optional-steps), you can add a flag for `--with-tfenv` that would use tfenv as the dependency and then have it install terraform as the dependency if no flag is provided. This would cover most use cases with smart defaults. 

### References

- #475

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @schematis 👋

Thank you for bringing this up!

Unfortunately the docs state:
> Note: [option](https://rubydoc.brew.sh/Formula#option-class_method)s are not allowed in Homebrew/homebrew-core as they are not tested by CI.

And our formula is currently specified in `Homebrew/homebrew-core`: https://github.com/Homebrew/homebrew-core/blob/master/Formula/c/cdktf.rb
