### ISSUE TITLE
Duplicate AWS Resource Generated During Synth

### ISSUE THREAD

**Issue by jmurillo9** [hashicorp/terraform-cdk#3153]
### Expected Behavior

1. `[jon@laptop]$ cdktf synth`
2. `[jon@laptop]$ cdktf deploy`
3. I approve the changes
4. A new DynamoDB table gets created.

### Actual Behavior

1. `[jon@laptop]$ cdktf synth`
2. `[jon@laptop]$ cdktf deploy`
3. The previous command fails saying:
```bash
Error: Missing required argument

on cdk.tf.json line 116, in resource.aws_dynamodb_table.remote-state-dynamodb (remote-state-dynamodb):
116:       },

The argument "name" is required, but no definition was found.
```

When I look at the generated `cdk.tf.json` file, I see that there was 2 instances of DynamoDB created. The first one is incomplete _(which is causing the error)_ and the other has the code exactly how I want it. 

```json
"resource": {
  "aws_dynamodb_table": {
    "my-awesome-dynamodb": {
      "//": {
          "metadata": {
            "path": "MY_MODULE/my-awesome-dynamodb",
            "uniqueId": "my-awesome-dynamodb"
          }
      }
    },
  "my-awesome-dynamodb_dynamodb_table_084AA624": {
    << insert generated code that is correct >>
```

For me to get past this, I have to delete the first instance of `my-awesom-dynamodb` in `cdk.tf.json`. Then, I have to actually run `terraform plan`. If I try to run `cdktf deploy` again, it will re-generate the bad JSON. 

-------------

It's worth noting that:

- I'm using TypeScript

- I am currently using a local backend. This module is specifically for new accounts getting bootstrapped so the module will eventually create the s3 bucket but I'm not writing to it just yet.

- I am also running the following. Ultimately, I have an entrypoint in my code that runs `TerraformStack` but not with this piece that's broken.

```typescript
import { Construct } from "constructs"; 
import { TerraformResource, TerraformOutput, TerraformResourceConfig } from "cdktf";
```

- I tried to copy/paste the generated code on HashiCorp's documentation repo and I still get the same error. Again, I only copied the middle portion of the code (not instantiating a `TerraformStack`).
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table?lang=typescript

### Steps to Reproduce

1. cdktf synth
2. cdktf deploy

### Versions

cdktf debug
language: null
cdktf-cli: 0.16.3
node: v16.20.1
terraform: 1.2.2
arch: x64
os: darwin 22.6.0

### Providers

┌───────────────┬──────────────────┬─────────┬────────────┬─────────────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF   │ Constraint │ Package Name        │ Package Version │
├───────────────┼──────────────────┼─────────┼────────────┼─────────────────────┼─────────────────┤
│ aws           │ 4.66.1           │ ^0.16.0 │            │ @cdktf/provider-aws │ 14.0.4          │
└───────────────┴──────────────────┴─────────┴────────────┴─────────────────────┴─────────────────┘

### Workarounds

- delete the stanza and manually run `terraform plan` but that's not ideal.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @jmurillo9 👋

Thank you for raising this! Could you share the code that creates the DynamoDB bucket? Maybe even an example that reproduces this?

From the output it seems that there are two constructs (with the ids `my-awesome-dynamodb` and `my-awesome-dynamodb_dynamodb_table_084AA624`). It seems that the latter is defined inside a construct whereas the first is defined directly on the stack level.
Did you maybe extend from `DynamodbTable` instead of `Construct` for your own abstraction?

**Comment by jmurillo9** [comment]
@ansgarm  - Please note, that I took all of this complexity out and replaced the `new DynamoDB` chunk of code out and copied/pasted what the HashiCorp documentation had (no variables or anything, all hard-coded) and I ran into the same error. 

---

# Stack

```typescript
import { App, TerraformStack, TerraformResourceConfig } from "cdktf";
import { provider } from "@cdktf/provider-aws";

import { DynamoDB } from '../index';

export myStackProps extends TerraformResourceConfig {
   region: string;
   environment: string
   app: string
   
   tableName: string
};

export class myStack extends TerraformStack {
   constructor(scope: App, id: string, props: myStackProps) {
      super(scope, id);
      
      new provider.AwsProvider(this, 'provider') {
         region: props.region
      };
      
      new DynamoDB(this, "myDynamoDB", {
         terraformResourceType: 'aws_dynamodb_table',
         app: props.app,
         region: props.region,
         environment: props.environment,
         tableName: props.tableName
      });
   }
}

const app = new App();
new myStack(app, "myapp", {
   terraformResourceType: 'myapp_stack',
   region: 'us-east-1',
   environment: 'nonprod',
   app: 'my-awesome-app',
   tableName: 'my-awesome-dynamodb-table',
   billingMode: 'PAY_PER_REQUEST';
   hashKey: 'LockID';
   attributeType: 'S'
   encryptionEnabled: true;
});
```

# Resource:
```typescript
import { Construct } from "constructs"; 
import { TerraformResource, TerraformOutput, TerraformResourceConfig } from "cdktf";
import { dynamodbTable } from "@cdktf/provider-aws";


export interface dynamoDBProps extends TerraformResourceConfig {
   platform: string;
   region: string;
   environment: string;

   tableName: string;
   billingMode: string;
   hashKey: string;
   attributeType: string;
   encryptionEnabled: boolean;
};

export class DynamoDB extends TerraformResource {
   constructor(scope: Construct, id: string, resourceProps: dynamoDBProps) {
      super(scope, id, resourceProps);

      const dynamoTable = new dynamodbTable.DynamodbTable(this, "dynamodb_table", {
         name: resourceProps.tableName,
         billingMode: resourceProps.billingMode,
         hashKey: resourceProps.hashKey,
         attribute: [{ name: resourceProps.hashKey, type: resourceProps.attributeType }],
         serverSideEncryption: {
            enabled: resourceProps.encryptionEnabled
         },

         // tag our dynamoDB table with the custom `Name` tag but also include provider tags
         tags: Object.assign(
            {
               Name: resourceProps.tableName,
            },
         ) 
      });

      const outputs = {
         tableName: dynamoTable.name,
         tableARN: dynamoTable.arn,
         tableBillingMode: dynamoTable.billingMode,
      };

      new TerraformOutput(this, "dynamoProperties", {
         description: "DynamoDB class outputs that make up Terraform's remote state backend. This table is used for statefile locking mechanism.",
         value: outputs
      });
   }
}
```

# Index

```typescript
export * from 'dynamodb';
```

**Comment by ansgarm** [comment]
Hi @jmurillo9 👋

Thank you for taking the time to share the example!

Your `DynamoDB` class extends from `TerraformResource` which causes CDKTF to try to create a resource out of this construct (that's the one with no properties in your result). `TerraformResource` is not really intended to be used directly other than for provider bindings (like the `dynamodbTable.DynamodbTable` for example).

You can fix your problem by extending from `Construct` (from the `construct` package) instead and by removing `terraformResourceType`. Your `dynamoDBProps` interface could then also just be standalone and not extend anything.

Old tutorials and examples we had extended from `TerraformResource` in case you stumbled upon one of these?
That said, we could try to build some safeguards to warn in cases like these (i.e. we could detect resource constructs within resources).

**Comment by sebs** [comment]
funny. I have the same problem with Azure Resources. 

1. I only have a stack, referencing a bunch of resources
2. i get a name collision and no second resource with a random string 
3. some resources are being created (AppConfig, KeyVault, StorageAccount) and then the error hits and tells me 2 of already created resources (AppConfig, StorageAccount) do exist already. 

Things I checked: 

1. The name choose is globally available (the first deploy of resource works) 
2. The cdk.tf.json does only include one of those 
3.  Deleting the created resources and trying again 
4. local backend deploy

**Comment by ansgarm** [comment]
Hi @sebs 👋 Could you create a separate issue for your problem and share e.g. the exact error message you are getting? Furthermore, I'd also be interested in the code that causes this – if that would be possible that is.

**Comment by jmurillo9** [comment]
@ansgarm - thank you so much. That 100% solved my problem. 

Yes, I must have seen some legacy documentation a little while back whenever I first upgraded to cdktf 0.16 _(or something)_ then never went back. I was scratching my head for a while now why I kept having to reference the `terraformResourceType` too. Once I used `Construct` instead, it all magically started working.

**Comment by jmurillo9** [comment]
Closing ticket as this is now resolved.
