### ISSUE TITLE
cdktf_provider_aws: No clear way to access `ref()` from Python

### ISSUE THREAD

**Issue by rirze** [hashicorp/terraform-cdk#3169]
### Expected Behavior

`from cdktf import ref` 

The above should work... but I'm unable to find any way to include `ref` as an import. It doesn't exist in the Python package as far as I've searched.

How do I enable this to exist?

### Actual Behavior

ImportError

### Steps to Reproduce

`from cdktf import ref`

### Versions

language: python

### Providers

aws

### Anything Else?

Could be JSII related? 

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @rirze 👋

Yeah, this is probably JSII related, as JSII only exports classes and not individual functions as some of the target languages don't support standalone functions (as far as I know).

What's your underlying problem that you are trying to solve? If it's not covered differently already, we will probably be able to expose the `ref` function through some utility class for these cases.
