### ISSUE TITLE
🚀 Feature Request :  Docker local build image .

### ISSUE THREAD

**Issue by neilkuan** [hashicorp/terraform-cdk#317]
### Description
Hi all 
I see aws cdk have this https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecr-assets-readme.html
DockerImageAsset
I can use `new DockerImageAsset ` help me build my local Dockerfile to image and push to AWS ECR 
```typescript
import { DockerImageAsset } from '@aws-cdk/aws-ecr-assets';

const asset = new DockerImageAsset(this, 'MyBuildImage', {
  directory: path.join(__dirname, 'my-image')
});
```

Is it possible to have a similar method to help us build image via  local Dockerfile  and then push it to GCP Container Registry or Azure Container Registry... ??
like
```typescript
import {DockerImageAsset} from '@cdk-terraform/docker-assets';

const asset = new DockerImageAsset(this,'MyBuildImage', {
   directory: path.join(__dirname,'my-image')
});
```

I just do something test like that ... 🙂🙂🙂🙂🙂🙂🙂🙂
`docker-assert.ts`
```typescript
import { exec } from 'child_process';
export function dockerAsserts(
  imagename: string,
  cwpath: string,
  credentialsName: string
) {
  exec(
    `docker build -t ${imagename} ${cwpath}/images && cat ${cwpath}/${credentialsName} | docker login -u _json_key --password-stdin asia.gcr.io && docker push ${imagename}`
  );
}
```

`main.ts`
```typescript
import { Construct } from 'constructs';
import { App, TerraformStack, TerraformOutput } from 'cdktf';
import {
  CloudRunService,
  GoogleProvider,
  DataGoogleIamPolicy,
  CloudRunServiceIamPolicy,
} from './.gen/providers/google';
import * as path from 'path';
import * as fs from 'fs';
import { dockerAsserts } from './src/index';
class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    // define resources here
    const imagename = 'asia.gcr.io/${project-id}/nginx:v4';
    dockerAsserts(imagename, `${process.cwd()}`, 'google.json');
...
```

**Comment by skorfmann** [comment]
That's essentially a Level 2 construct which you're talking about. To make this possible, we need #98 - Which are currently being implemented - e.g. see https://cdk.tf/provider/aws 

However, I do have an example of an `EcrAsset` Level 2 construct for the Terraform CDK AWS Provider. Let me polish it a bit and then I'll publish and ping you.

> Is it possible to have a similar method to help us build image via local Dockerfile and then push it to GCP Container Registry or Azure Container Registry... ??
> like

For GCP or Azure, do you have to create the Docker repository as well? Or is it just building and pushing the image? Where are the credentials coming from?

**Comment by guan840912** [comment]
GCP we can import something like `google.json` service account credentials , I think Azure have something like that ~~~ 😊😊😊😊

**Comment by skorfmann** [comment]
> GCP we can import something like `google.json` service account credentials , I think Azure have something like that ~~~ 😊😊😊😊

Ah - yes. What I meant was credentials for `docker push` :)

**Comment by guan840912** [comment]
GCP can get `docker push` credentials like that 😁😁😊
```bash
cat ${cwpath}/google.json | docker login -u _json_key --password-stdin asia.gcr.io && docker push ${imagename}
```

**Comment by skorfmann** [comment]
@guan840912  here's [an example](https://github.com/skorfmann/cdktf-aws-ecr-asset/blob/4232e5341888848e04f72554ae66a78fe13a233b/src/index.ts) for AWS ECR. 

It could be an interesting experiment, to build something like a generic Docker asset, which works with AWS / Google & Azure.

**Comment by guan840912** [comment]
Thank you for the information  😊 😊 😊

**Comment by skorfmann** [comment]
This is something to consider when working on #648

**Comment by skorfmann** [comment]
While it's not polished and not well documented, there's a version in [cdk.tf/plus](https://github.com/cdktf-plus/cdktf-plus/tree/481d27a9ce1bac9dcacba0156d5aabcb32d7e868/packages/%40cdktf-plus/core/lib/docker-asset).

Not sure if this will get into core at some point or not. Closing this one here
