### ISSUE TITLE
TypeError: t.update is not a function

### ISSUE THREAD

**Issue by xxjt123xx** [hashicorp/terraform-cdk#3171]
### Expected Behavior

for the code deploy

### Actual Behavior

deployment finishes and then at the end I get the error

```
/iac/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

TypeError: t.update is not a function
    at e.captureSession (/iac/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:210:25239)
    at ha._sendSessionUpdate (/iac/node_modules/cdktf-cli/bundle/bin/cdktf.js:52:867)
    at ha.endSession (/iac/node_modules/cdktf-cli/bundle/bin/cdktf.js:52:235)
    at process.<anonymous> (/iac/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:215:6296)
    at process.emit (node:events:514:28)
    at process.emit (node:domain:488:12)
    at process.dtt [as emit] (/iac/node_modules/cdktf-cli/bundle/bin/cmds/handlers.js:262:14915)

Node.js v20.8.0
```

### Steps to Reproduce

1. deploy
2. wait for error

### Versions

```
  "dependencies": {
    "@cdktf/provider-aws": "^17.0.8",
    "cdktf": "^0.18.1",
    "constructs": "^10.2.70"
  },
  "devDependencies": {
    "@types/jest": "^29.5.4",
    "@types/node": "^20.5.7",
    "@typescript-eslint/eslint-plugin": "^6.5.0",
    "@typescript-eslint/parser": "^6.5.0",
    "cdktf-cli": "^0.18.1",
    "dotenv-flow": "^4.0.0",
    "eslint": "^8.48.0",
    "jest": "^29.6.4",
    "terraform": "^1.23.0",
    "ts-jest": "^29.1.1",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  }
```

### Providers

AWS

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
A patch (0.18.2) is out with this fix now as well 🙂
