### ISSUE TITLE
AWS provider: remove content handling for lambda as its not supported

### ISSUE THREAD

**Issue by xxjt123xx** [hashicorp/terraform-cdk#3175]
### Description

remove content handling for lambda as its not supported

### Links

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/apigatewayv2_integration?lang=typescript#lambda-integration

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
This should be fixed with the next release of the AWS provider
