### ISSUE TITLE
TerraformAsset fails to find zipSync.js when used in library

### ISSUE THREAD

**Issue by OlivierPT** [hashicorp/terraform-cdk#3176]
### Expected Behavior

Using TerraformAsset from a L2Construct library works properly inside an application project using the library.

### Actual Behavior

If `TerraformAsset` is used to create a L2Construct packaged in a library, it fails to find zipSync.js when the L2Construct is invoked in an application project with the message:

Error: Cannot find module '$PATH_TO_APP/node_modules/$L2CONSTRUCT_LIBRARY/bin/zipSync.js'

### Steps to Reproduce

1. Create package with L2Construct which use TerraformAsset (for example an LambdaFunction) and publish this package with `yalc`
2. Create a project that use the L2Construct from the lib
3. Synth the project

### Versions

language: typescript
cdktf-cli: 0.18.2
node: v18.9.1
cdktf: null
constructs: null
jsii: null
terraform: 1.5.7
arch: arm64
os: darwin 22.6.0

### Providers

The command did not work.

Provider are:
- aws-provider
- kubernetes-provider
- vault-rpoviderr

### Possible Solutions

Include zipSync as a function part of CDKTF instead of having in `bin` ?

### Workarounds

Use the FILE AssetType of TerraformAsset

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Adding the entire stack trace as posted on the CDK Dev Slack:
```
Error: Cannot find module '/Users/path_to_my_l2contruct_library/bin/zipSync.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:955:15)
    at Module._load (node:internal/modules/cjs/loader:803:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:18:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [] 
```

**Comment by OlivierPT** [comment]
Is there any news about this issue?

I tried a work around by copying the "bin" directory which contains "zipSync.js" file inside my L2 contruct library but since the library is scoped, there is an additional directory level and CDK-TF is not able to point to the right place... 
I think this comes from this line: https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf/lib/private/fs.ts#L50
