### ISSUE TITLE
cdktf npm package bundles dozens of additional packages

### ISSUE THREAD

**Issue by pauldraper** [hashicorp/terraform-cdk#3177]
### Expected Behavior

The cdftf npm package does not have a `node_modules` directory.

### Actual Behavior

The cdftf npm package does not has a `node_modules` directory with dozens packages.

### Steps to Reproduce

```
curl https://registry.npmjs.org/cdktf/-/cdktf-0.18.2.tgz | tar t | grep node_modules
```

### Versions

cdktf 0.18.2

### Anything Else?

This happens because cdktf bundles dependencies with `bundledDependencies`. There isn't a good reason to do this.

Including dozen of other packages bloats the download and install size. Rather, these should be normal dependencies in package.json and allow the package manager to resolve+download+install them.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @pauldraper 👋

This is due to how JSII works currently: https://github.com/hashicorp/terraform-cdk/issues/2819#issuecomment-1517560604

**Comment by pauldraper** [comment]
Okay I see that now. https://aws.github.io/jsii/user-guides/lib-author/configuration/#dependencies-that-are-not-jsii-modules

It seems that JSII is trying to use **npm packages** for **non-npm environments**.

It's a pseudo-package npm manager that consumes npm packages, but doesn't implement everything npm does.

Kinda weird, but I can complain to JSII.
