### ISSUE TITLE
CDKTF-CLI: Hangs on synth/plan

### ISSUE THREAD

**Issue by eahrend** [hashicorp/terraform-cdk#3198]
### Expected Behavior

1. Run cdktf synth
2. It shows a list of stacks
3. Gives me control of the terminal

### Actual Behavior

Just hangs after showing all the stacks for about 30 minutes.

### Steps to Reproduce

Haven't been able to cleanly reproduce, adding a 26th stack seems to my app will cause it, even if the 26th stack is empty, but if all stacks are empty it works.

### Versions

cdktf debug
language: go
cdktf-cli: 0.18.0
node: v20.4.0
cdktf: 0.18.0
constructs: 10.2.70
jsii: 1.88.0
terraform: 1.5.3
arch: arm64
os: darwin 23.0.0
go: go version go1.20.3 darwin/arm64

### Providers

erik@Erik-Ahrends-MacBook-Pro cloud-infrastructure % cdktf provider list
Pre-built provider information not found
Error: Pre-built provider information not found

### Gist

https://gist.github.com/eahrend/410069fa4059823813cc1ab36c1c365f

### Possible Solutions

No clue, going through the CDKTF CLI code doesn't show any references to an http 413 error, nor do I see any obvious place where it would even be making an HTTP call, let alone where the request entity would be too large during the synth process.

I tried setting sendCrashReports to false in cdktf.json as well, in the hopes that maybe there was some http call that cdktf was doing and this didn't work either.

Tried doing `export NODE_OPTIONS=--max-old-space-size=8192` in the hopes that maybe it was some memory issue, but doubling and even tripling the available memory to node didn't resolve this either.
https://github.com/hashicorp/terraform-cdk/blob/v0.18.0/packages/%40cdktf/cli-core/src/lib/synth-stack.ts#L98-L100

### Workarounds

Comment out a stack, then rerun. 

### Anything Else?

Nothing out of the ordinary.

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @eahrend 👋

Is this error also happening when you directly invoke your program (the `app` command specified in your `cdktf.json` config e.g. `go run ...`)?

If that works: Could you try to disable all telemetry by setting `CHECKPOINT_DISABLE=1`? (This is different from the crash reporting setting)

Thanks in advance! And weird issue indeed 🕵️

**Comment by eahrend** [comment]
Running `go run main.go` works fine, generates all the TF code in `cdktf.out` like intended. Running `env CHECKPOINT_DISABLE=1 cdktf synth` also works, same with `env CHECKPOINT_DISABLE=1 cdktf plan $stackName` also works. What would cause this?

**Comment by eahrend** [comment]
@ansgarm is there anything we can do to prevent this from happening while still using checkpoint?

**Comment by ansgarm** [comment]
Hi @eahrend 👋

CDKTF uses Checkpoint for its own [telemetry](https://developer.hashicorp.com/terraform/cdktf/telemetry) events (e.g. reporting which CDKTF version is used). As part of the telemetry payload we send metadata about the stacks (e.g. when overrides are used, to help us know when an escape hatch is used). Your configuration seems to be quite elaborate which causes the payload to grow above the 8KB limit.

https://github.com/hashicorp/terraform-cdk/pull/3255 is a fix for this, that skips sending such events if they are too large.
