### ISSUE TITLE
ElasticacheReplicationGroup: Transit encryption mode

### ISSUE THREAD

**Issue by dtsabii** [hashicorp/terraform-cdk#3259]
### Description

I need to set transit encryption mode to preferred or required. For now, I can set only the `transit_encryption_enabled` attribute.
If I set only `transit_encryption_enabled=True` and deploy the redis stack it sets transit encryption mode to required. I need to set it to preferred.

### References

https://github.com/hashicorp/terraform-provider-aws/issues/29403

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @dtsabii 👋

Which version of the AWS Terraform provider are you using?

It seems that support has been [added in v5.16.0](https://github.com/hashicorp/terraform-provider-aws/issues/29403#issuecomment-1710971639). The [latest pre-built](https://github.com/cdktf/cdktf-provider-aws/releases/tag/v18.0.5) provider for AWS is based on v5.25.0, so it includes that fix as well.

**Comment by dtsabii** [comment]
Hi, @ansgarm !
It was fixed in v18.0.5, I used lower version without this attribute.
Thanks.
