### ISSUE TITLE
pipenv required even if developing/running in a container?

### ISSUE THREAD

**Issue by dss010101** [hashicorp/terraform-cdk#3262]
### Expected Behavior

My dev env is a container - where i have all and only necessary components installed (python, terraform and azure cli, npm, node, cdktf, )

I have been using terraform sucessfully in this environment for some time.  I am looking however to see experiment with python + cdktf.  I am walking through the tutorial on how to set up.  however when i get to selection of provider, i select 'azurerm', but right after that i get "Unable to find 'pipenv'.    
![image](https://github.com/hashicorp/terraform-cdk/assets/855627/ae2242e1-7b93-463b-b2b8-29f2d19b1bd2)

Is cdktf attempting to create a virtual environment? why if i am already working in a docker container? 
Or is there another issue/setp im missing here?

### Actual Behavior

I shouldnt need pipenv if my dev env is a containerized.

### Steps to Reproduce

1. create a dev container with python, terraform, npm, node, cdktf and azure cli installed
2. enter the container and do: "cdktf init --template=python --local"

### Versions

language: python 3.12
cdktf: 0.19.1
npm: 10.2.3
node: v20.9.0
azure-cli: 2.53.1

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @dss010101 👋

CDKTF has two Python templates: `python` (which uses pipenv) and `python-pip`, which might solve your problem.

**Comment by dss010101** [comment]
> -

thanks will try this and report back.

**Comment by dss010101** [comment]
> Hi @dss010101 👋
> 
> CDKTF has two Python templates: `python` (which uses pipenv) and `python-pip`, which might solve your problem.

i have some time to try this. do you have documentation on how to use python-pip instead of pipenv?

Thanks much
