### ISSUE TITLE
Support for Synthesizing Terraform Remote State Backends

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#33]
I think that remote state functionality should be supported as well. That would enable the usage in more complex environments (e.g. thinking of centrally managed VPCs)

**Comment by jsteinich** [comment]
I worked on this a bit for [Terrastack](https://github.com/jsteinich/terrastack/tree/backends). Also included typed backend support

**Comment by jsteinich** [comment]
I started some early work on this: https://github.com/hashicorp/terraform-cdk/pull/241

**Comment by skorfmann** [comment]
This will be fully available with https://github.com/hashicorp/terraform-cdk/pull/241
