### ISSUE TITLE
PR build integration tests aren't consistent in which build artifacts they use.

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#334]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
* all

### Affected Resource(s)
* integration tests

### Expected Behavior
Should always use the artifact of one specified build from the matrix

### Actual Behavior
I believe which ever build finishes last is used

### Steps to Reproduce
Submit a PR and let the build run

### Important Factoids

In theory the artifacts are identical, so this doesn't completely matter, but having complete consistency in tests is nice.

### References

* #332 
* #333

**Comment by skorfmann** [comment]
Resolved by limiting the upload to only one build job via #270
