### ISSUE TITLE
CDKTF login / get: cannot authenticate to Terraform via env variable

### ISSUE THREAD

**Issue by kneekeel** [hashicorp/terraform-cdk#3342]
### Expected Behavior

According to the [Deployment Patterns](https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/deployment-patterns#github-actions-ci-and-terraform-cloud) documentation, you can specify an env variable `TERRAFORM_CLOUD_TOKEN` to execute `cdktf diff & deploy` commands. We feel as though this behavior should be replicated across other `cdktf cmds` i.e., `login & get`. 

In our CI pipeline, our CDKTF projects utilize HCL private modules. When we specify the required (API Token) env variable, we should be able to authenticate against our private registry.

### Actual Behavior

The `cdktf-cli` package does not support Terraform authentication through env variables. We receive a 401 error: 
<img width="1007" alt="image" src="https://github.com/hashicorp/terraform-cdk/assets/52008136/06852cc3-c750-4787-ada1-ec7f5563bad7">

The [login](https://developer.hashicorp.com/terraform/cdktf/cli-reference/commands#login) command currently supports 3 ways to authenticate, 2 of which being an interactive process further complicating the CI flow. Optionally, you can create / modify the [.terraform.d/credentials.tfrc.json](https://github.com/hashicorp/terraform-cdk/blob/60851b5022bc7d83f4f8641de1e7a77750517f9e/packages/cdktf-cli/src/bin/cmds/helper/terraform-login.ts#L12) file.

### Steps to Reproduce

1. Create CDKTF (Typescript) project that uses a HCL module stored in a private registry
2. Create a GitHub workflow (CLI driven diff) to get the provider & module bindings of the project
    - try without `<token-file-name>.txt` or `.terraform.d/credentials.tfrc.json` files

### Versions

language: typescript
cdktf-cli: 0.19.2
node: v20.10.0
cdktf: 0.19.2
constructs: 10.3.0
jsii: null
terraform: 1.5.5
arch: arm64
os: darwin 21.6.0
providers
aws@~> 4.30 (LOCAL)
        terraform provider version: 4.67.0
http@~> 3.4 (LOCAL)
        terraform provider version: 3.4.0

### Providers

┌───────────────┬──────────────────┬───────┬────────────┬──────────────┬─────────────────┐
│ Provider Name │ Provider Version │ CDKTF │ Constraint │ Package Name │ Package Version │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ aws           │ 4.67.0           │       │ ~> 4.30    │              │                 │
├───────────────┼──────────────────┼───────┼────────────┼──────────────┼─────────────────┤
│ http          │ 3.4.0            │       │ ~> 3.4     │              │                 │
└───────────────┴──────────────────┴───────┴────────────┴──────────────┴─────────────────┘

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
It seems like we have the wrong information in our docs, I think the right key for the environment variable would be `TF_TOKEN_app_terraform_io`
