### ISSUE TITLE
cdktf init: Unable to find "go" installation

### ISSUE THREAD

**Issue by Gre8t** [hashicorp/terraform-cdk#3350]
### Expected Behavior

`cdktf init --template=go` should find Go and generate a template.

### Actual Behavior

It outputs an error saying "Go version can't be found".

### Steps to Reproduce

1. Use a Linux operating system
2. Install Golang in a folder other than /usr/local/go/bin
3. Run this command: sudo cdktf init --template=go --provider=aws --local. 
4. When you hit this error, use `strace` command to figure out how Go is being searched for.

### Versions

cdktf-cli: 0.20.0-pre.58
node: 18.7.0
terraform: 1.3.7
arch: amd64

### Possible Solutions

Modify CLI to use system path instead of a specific directory. That way it becomes directory agnostic

### Workarounds

Create a softlink to "/usr/local/go" directory. Or perhaps reinstall your Go CLI into "/usr/local/go" directory

### Help Wanted

- [X] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
We rely on running go version to get the installed version of go. Could it be that go is not in your path or not under the name go?

In either way I could see that having a separate check if the binary exists and a different error being thrown in that case might help understand this problem better.
