### ISSUE TITLE
[init] Graceful Error Handling for Terraform Cloud Init

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#337]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- 0.0.16 and likely all other versions 

### Affected Resource(s)

- Terraform Cloud init

### Debug Output

![Screenshot 2020-08-22 at 15 31 56](https://user-images.githubusercontent.com/136789/90957257-b87d5f80-e48c-11ea-9901-379fa93d2423.png)

### Expected Behavior

The Terraform Cloud token seems to be valid for the first organization only (`cdk-dev`). When choosing the other organization, the error should be handled gracefully.

### Actual Behavior

An error is thrown and the process is exiting.

### Steps to Reproduce

A Terraform Cloud token valid for one org only, use it to init a project in a different org.

**Comment by ansgarm** [comment]
@skorfmann I cannot seem to reproduce this because with a "Team token" as it will only show the one TFC org that token has access to. With a "user token" I can see the two TFC orgs I have access to but it'll also work with both those orgs.

I tried reusing an existing workspace but that printed a nicely formatted error message
> ERROR: Could not create Terraform Cloud Workspace: Name has already been taken

Do you know how I can create a token which causes this issue?

**Comment by DanielMSchmidt** [comment]
It could be that I fixed that error while working on the streaming logs from TF Cloud PR 🤔

**Comment by ansgarm** [comment]
Could also be the case that something changed upstream in the Terraform Cloud API.

I'd just close this, as we cannot reproduce it (anymore). Fine with you, @skorfmann ?

**Comment by skorfmann** [comment]
Yep, let's just close it
