### ISSUE TITLE
Resource ID Mismatch between 0.15.5 and 0.17.0 and higher whilst using feature flags

### ISSUE THREAD

**Issue by OLingard** [hashicorp/terraform-cdk#3378]
### Expected Behavior

When upgrading from 0.15.5, the resource IDs should stay the same. Unlike #2954, the feature flags have always been enabled.

### Actual Behavior

The Resource IDs change from, for example, `stack_cloudflareCDNRecord_B16C1A90` to `cloudflareCDNRecord`.

### Steps to Reproduce

cdktf.json:
```json
{
  "language": "typescript",
  "app": "npx ts-node main.ts",
  "projectId": "bfeb3a70-002e-487f-a528-8621d18b42ad",
  "sendCrashReports": "false",
  "terraformProviders": [
    "aws@=5.31.0",
    "cloudflare/cloudflare@=4.21.0",
    "hashicorp/random@=3.6.0",
    "fastly/fastly@=5.6.0",
    "signalsciences/sigsci@~> 2.1.4"
  ],
  "terraformModules": [],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

1. Create a stack using 0.15.5
2. Bump your package.json to the latest version
3. Rerun and notice the discrepancies

### Versions

cdktf: 0.15.5 -> 0.17.0 or higher

### Possible Solutions

Looking through the code, I have noticed the difference within `allocateLogicalId`. It looks like the stackIndex has moved from being 0 to 1 in this change. Unfortunately I don't know the code base well enough to understand where this would have happened.

### References

#2954

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by Maed223** [comment]
Hey @OLingard 👋

To help users migrate from versions previous to 0.17 we added an id migration tool that avoids any destructive behavior you'd otherwise see. You can take a look at the [0.17 upgrade guide](https://github.com/hashicorp/terraform-cdk/blob/main/website/docs/cdktf/release/upgrade-guide-v0-17.mdx) that calls out the `Aspect` `MigrateIds`. Additionally if you are unfamiliar with  the `Aspect` in CDKTF [here is the related documentation](https://developer.hashicorp.com/terraform/cdktf/concepts/aspects) to get you on your way 😁

**Comment by OLingard** [comment]
Hi Maed, thanks for the reply! That's handy information, for anyone else's benefit who sees this thread, the simple fix is as follows:
```ts
import { TerraformStack, Aspects, MigrateIds } from "cdktf";
import { Construct } from "constructs";

export class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);
    // Add the following
    Aspects.of(this).add(new MigrateIds());
  };
};
```

**Comment by DanielMSchmidt** [comment]
Closing this since it seems solved :)
