### ISSUE TITLE
Test all Templates Explicitly

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#338]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As we add more templates, it'd be good to add an explicit test which tests all present templates in some kind of integration test. It could:

- iterate over all templates
- init a new project for each of these templates
- `build` / `compile` and expect a `0` exit code

**Comment by ansgarm** [comment]
This probably could've caught https://github.com/hashicorp/terraform-cdk/issues/1505.

**Comment by xiehan** [comment]
We want to tackle making these less brittle as part of #1734 so we don't think there needs to be a separate issue about this anymore. Also, nearly all our templates are used in integration tests by this point.
