### ISSUE TITLE
Hashmap values like "_FOO" are converted incorrectly to "foo" in cdk.tf.json file

### ISSUE THREAD

**Issue by kaisellgren** [hashicorp/terraform-cdk#340]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.0.12
provider.google v3.30.0

### Affected Resource(s)

https://www.terraform.io/docs/providers/google/r/cloudbuild_trigger.html

Specifying a `substitutions` hashmap in TypeScript:

```
  new gcp.CloudbuildTrigger(scope, `${config.prefix}-backend-trigger`, {
    ...
    substitutions: {
      '_IMAGE_URL': config.imageUrl,
      '_BACKEND_NAME': backend.name,
      '_REGION': config.region,
      '_DOCKER': docker,
    },
    ...
  })
```

Is for some reason converted to incorrect format in the cdk.tf.json file:

```
    "google_cloudbuild_trigger": {
      "***_devbackendtrigger_91F68B7B": {
        ...
        "substitutions": {
          "image_url": "gcr.io/***/app-dev",
          "backend_name": "dev-backend",
          "region": "europe-north1",
          "docker": "gcr.io/cloud-builders/docker"
        },
```

### Debug Output

Here's the relevant debug output:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT"
  }
}
```

The [documentation states ](https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values#using_user-defined_substitutions)that it has to be in format _XXX (start with an underscore and be all-caps). 

### Expected Behavior

When I manually modify the produced cdk.tf.json file to have the same _XXX format, then running `terraform apply` works.

Keep the underscore and uppercase format or provide a way to override this behavior when you need it.

### Actual Behavior

The hashmap keys are converted from _BACKEND_NAME format to "backend_name" format.

### References

* #0000

**Comment by jsteinich** [comment]
Sounds like #235 
Take a look at [this comment](https://github.com/hashicorp/terraform-cdk/issues/235#issuecomment-662942782) for some possible workarounds.

**Comment by skorfmann** [comment]
Yes - looks like the same issue. Please watch the ticket #235 for changes, going to close this one here as duplicate.
