### ISSUE TITLE
Complex list iterator: incorrect example in docs

### ISSUE THREAD

**Issue by gabegorelick** [hashicorp/terraform-cdk#3409]
### Description

The example code given in https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-on-complex-lists is incorrect. When run, it generates errors (`This object does not have an attribute named "record"`, `This object does not have an attribute named "name"`, etc). 

Relevant code from the docs, which was also included with the same error in was included in [the release post for v0.2.0](https://www.hashicorp.com/blog/cdktf-0-20-improves-implementation-of-iterators-and-enables-hcl-output):
```ts
const cert = new AcmCertificate(this, "cert", {
  domainName: "example.com",
  validationMethod: "DNS",
});
const dataAwsRoute53ZoneExample = new DataAwsRoute53Zone(this, "dns_zone", {
  name: "example.com",
  privateZone: false,
});

const exampleForEachIterator = TerraformIterator.fromComplexList(
  cert.domainValidationOptions,
  "domain_name"
);

const records = new Route53Record(this, "record", {
  forEach: exampleForEachIterator,
  allowOverwrite: true,
  name: exampleForEachIterator.getString("name"),
  records: [exampleForEachIterator.getString("record")],
  ttl: 60,
  type: exampleForEachIterator.getString("type"),
  zoneId: dataAwsRoute53ZoneExample.zoneId,
});
```

In the above code, `exampleForEachIterator.getString("name")` should be `exampleForEachIterator.getString("resource_record_name")`, `exampleForEachIterator.getString("record")` should be `exampleForEachIterator.getString("resource_record_value")`, and `exampleForEachIterator.getString("type")` should be `exampleForEachIterator.getString("resource_record_type")`.

https://github.com/hashicorp/terraform-cdk/pull/3273 has more context as to how this error may have arisen. Before the introduction of complex list iterators, the boilerplate solution was:
```hcl
resource "aws_route53_record" "example" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.example.zone_id
}
``` 

Note the use of `name`, `record`, and `type`. But these are not valid given the HCL that `fromComplexList` generates:
```json
"for_each": "${{ for key, val in tolist(aws_acm_certificate.example.domain_validation_options): val.domain_name => val }}
```

### Links

- https://github.com/hashicorp/terraform-cdk/pull/3273
- https://www.hashicorp.com/blog/cdktf-0-20-improves-implementation-of-iterators-and-enables-hcl-output
- https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-on-complex-lists

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @gabegorelick 👋

You're 100% right! Will create a fix for this 👍

**Comment by gabegorelick** [comment]
Thanks for the quick fix! Will https://www.hashicorp.com/blog/cdktf-0-20-improves-implementation-of-iterators-and-enables-hcl-output be updated too?
