### ISSUE TITLE
feature: Static ressource ID in terraform output

### ISSUE THREAD

**Issue by rhoriguchi** [hashicorp/terraform-cdk#3433]
### Description

A global setting to enable static terraform resource IDs for all constructs and sub constructs in a stack, using the explicitly set ID in the constructor with no hash and not prefixing it with the parrent constructs ID.

Without this feature it's practically impossible to refactor CDK code down the road specialy when adding nested constructs.

In contrast to #329 a feature that does this for all sub constructs and not only on stack level and for direct subconstructs would be usefull.

### References

- #329

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
We have the prefix and hash to avoid ID conflicts within a cdktf stack. Within a construct scope all IDs need to unique (a construct requirement), even if the type differs. For terraform there can not be the same resource name for the same resource type in the entire stack (they would just overwrite one another). This means the requirement for cdktf is to have these both combined, leading to the hashing and prefixing we do. With the current solution there are no ways to mess up, the default is easy.

I can see this being a problem with refactoring constructs into stacks, for this we propose using [move blocks](https://developer.hashicorp.com/terraform/cdktf/examples-and-guides/refactoring#moving-renaming-resources-within-a-stack) to change the resource addresses within terraform to the new name.

Another alternative would be to use `overrideLogicalId` to set the name on the resources manually, this could even be done by extending the class, e.g.

```ts
class FixedNameS3Bucket extends S3Bucket {
  constructor(scope: Construct, name: string, options: S3BucketOptions) {
    super(scope, name, options);
    this.overrideLogicalId(name);
  }
}
```

Yet another alternative if you want to go all in with this would be to extend `TerraformStack` [and provide your own `allocateLogicalId` function](https://github.com/hashicorp/terraform-cdk/blob/a0974087b87f21ce5d21c1655a06393afe469bde/packages/cdktf/lib/terraform-stack.ts#L198). It should work if you are in Typescript, but you are definitely leaving the supported area of use.

I think adding this override will make it more likely for users to run into issues that the current solution solves quite nicely. It is unlikely we will support the option out of the box.

**Comment by ansgarm** [comment]
I was nerd-sniped by Daniels answer and initially wanted to try whether an Aspect could also be used here (tl;dr: it can't be used).

However, overriding `Stack#getLogicalId` seemed to be the simplest solution:
```ts
class MyStack extends TerraformStack {
  
  getLogicalId(tfElement: TerraformElement): string {
    return tfElement.node.id;
  }
  
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new RandomProvider(this, "random", {});

    new TerraformOutput(this, "global-output", {
      value: "global-output",
    });
    new Pet(this, "global-pet", {});
    new NestedConstruct(this, "nested-construct");
  }
}
```
Note: As Daniel alluded to, constructs need unique ids, so this requires globally unique names for the Terraform resources and does not support having two resources with a different type share the same name (which Terraform supports).

<details>
  <summary>Entire example code</summary>

```ts
import { Construct } from "constructs";
import {
  App,
  TerraformElement,
  TerraformOutput,
  TerraformStack,
} from "cdktf";
import { RandomProvider } from "./.gen/providers/random/provider";
import { Pet } from "./.gen/providers/random/pet";

class NestedConstruct extends Construct {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new TerraformOutput(this, "nested-output", {
      value: "nested-output",
    });
    new Pet(this, "nested-pet", {});
  }
}

class MyStack extends TerraformStack {
  
  getLogicalId(tfElement: TerraformElement): string {
    return tfElement.node.id;
  }
  
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new RandomProvider(this, "random", {});

    new TerraformOutput(this, "global-output", {
      value: "global-output",
    });
    new Pet(this, "global-pet", {});
    new NestedConstruct(this, "nested-construct");
  }
}

const app = new App();
new MyStack(app, "cdktf-aspect-global-ids");
app.synth();

```

</details>

**Comment by rhoriguchi** [comment]
Thank you for the solutions. I've also tried to solve it with aspects but that sadly does not work. The solution from @ansgarm works greate in our use case. This issue can be closed, if this is not planed to be implemented. But maybe document it somewhere, so users know this is a possible solution to get "raw" ids.
