### ISSUE TITLE
Wafv2WebAcl: Extraneous JSON object property "managedRuleGroupStatement"

### ISSUE THREAD

**Issue by xxjt123xx** [hashicorp/terraform-cdk#3458]
### Expected Behavior

This was working a few weeks ago and now is giving a build error with no code changes.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/wafv2_web_acl?lang=typescript#managedRuleGroupStatement

### Actual Behavior

Build should be working

### Steps to Reproduce

1. Add Wafv2WebAcl
2. Add a rule with managedRuleGroupStatement

### Versions

language = typescript
cdktf = ^0.20.1
cdktf-cli = ^0.20.1
@cdktf/provider-aws = 19.2.0

### Providers

AWS

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @xxjt123xx 👋

There has been a small performance related change to that resource in CDKTF 0.20.1 ([changelog](https://github.com/hashicorp/terraform-cdk/blob/main/CHANGELOG.md#0201), [PR](https://github.com/hashicorp/terraform-cdk/pull/3414)) which removes generated types for some attributes of this resource.

To fix the error you are encountering, change the casing of all keys in the `rule > statement` block to snake case. It should then look like this:
https://github.com/hashicorp/terraform-cdk/blob/c60b321b6bc832eb21c23f5b895f78def7d55f19/examples/typescript/aws-cloudfront-proxy/main.ts#L52-L68

Sorry for the trouble this change caused! We'd have liked to solve it in another way but there sadly was no sensible alternative.
