### ISSUE TITLE
Add feature flags for enabling breaking changes

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#346]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While working on #329 it was realized that it would cause a breaking change. While currently that may be acceptable, as the project grows, we'll want to introduce more potentially breaking changes and won't want to be forced to wait for a new major version.

Feature flags serve as a way to conditionally enable breaking behavior. Following CDK [feature flags](https://docs.aws.amazon.com/cdk/latest/guide/featureflags.html) makes a lot of sense...
* Easy central definition
* Automatic use in new projects

The naming convention can probably be loosened since this project isn't made up of 100s of modules.
We also need to decide where to put them. Some options:
1. cdktf.json - this is a close equivalent of cdk.json so would match well
2. Directly in code - already possible to set via `node.setContext`. Could be added to template projects

I'm in favor of the first option since it keeps the code cleaner and has a cleaner boundary of effect.

### References

#329 
[CDK feature flags](https://docs.aws.amazon.com/cdk/latest/guide/featureflags.html)

**Comment by skorfmann** [comment]
> I'm in favor of the first option since it keeps the code cleaner and has a cleaner boundary of effect.

Yes, I'd prefer `cdktf.json` as well 👍

**Comment by cmclaughlin** [comment]
I think this can be closed since PR #329 was merged - excited to try that!

**Comment by jsteinich** [comment]
Resolved with #329
