### ISSUE TITLE
Support configurable runtime context

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#347]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is currently the concept of a runtime context available to construct nodes. It is possible to use `node.setContext` to pass runtime configuration data. The idea is to expand the ability to set to other sources. The AWS CDK actually supports [6 sources](https://docs.aws.amazon.com/cdk/latest/guide/context.html): a few different files, cli command line, AWS, and the programmatic setting.

Having this is automatically applied configuration is helpful for #346 since it could be placed into `cdktf.json` automatically.

The AWS CDK takes things a bit farther and also has context providers that cache history of context lookups. These seem similar to Terraform data sources, so might not add as much value here. There is also a cli command for working with context, but it seems most relevant to working with provider cached data.

### References

#346 
#329 
[CDK context](https://docs.aws.amazon.com/cdk/latest/guide/context.html)

**Comment by skorfmann** [comment]
> The AWS CDK takes things a bit farther and also has context providers that cache history of context lookups. These seem similar to Terraform data sources, so might not add as much value here.

Yes, agreed - we don't need context lookups in that sense.

> e. There is also a cli command for working with context, but it seems most relevant to working with provider cached data.

It could make sense to use context as way to provide configuration via the cli - see #348

**Comment by jsteinich** [comment]
> It could make sense to use context as way to provide configuration via the cli - see #348

I'd be curious if @eladb or anyone else that has worked more extensively with the AWS CDK has opinions on this, but I'm personally in favor of keeping `cdktf.json` to be limited to just configuration values for the cdktf cli/runtime.

I don't really see app configuration as something that cdktf should be trying to solve; however, it is important that users are able to easily do what they need. This might be as simple as providing good documentation and examples for of a real world multi-environment scenario, but perhaps something like [environments](https://docs.aws.amazon.com/cdk/latest/guide/environments.html) is a core enough concept to warrant inclusion.

If we limit the use, there is still a question of how rigidly the file is loaded. We could limit to explicitly defined keys (truly limited use), or we could allow a bag of key value pairs (possibly less code maintenance, but leaves the door open for other uses).

**Comment by skorfmann** [comment]
@jsteinich I think that was implemented already?

**Comment by jsteinich** [comment]
We only support a subset of the ways that the AWS CDK does to provide context, but that seems fine.

I see value in being able to pass additional flags to Terraform (or run arbitrary terraform commands), but I think that is covered by #348.

One thing I would like to address is the discrepancy between `cdktf synth` and running the app directly. Specifically, the context is only applied when ran from the cli. I'm pretty sure AWS CDK had the same behavior, but it has proven to be an annoyance in practice.

**Comment by skorfmann** [comment]
> One thing I would like to address is the discrepancy between `cdktf synth` and running the app directly. Specifically, the context is only applied when ran from the cli. I'm pretty sure AWS CDK had the same behavior, but it has proven to be an annoyance in practice.

Oh, wasn't aware of this. That's certainly something to address 👍

**Comment by skorfmann** [comment]
> One thing I would like to address is the discrepancy between `cdktf synth` and running the app directly. Specifically, the context is only applied when ran from the cli. I'm pretty sure AWS CDK had the same behavior, but it has proven to be an annoyance in practice.

That's tracked in https://github.com/hashicorp/terraform-cdk/issues/798

Closing this one in favour of #798
