### ISSUE TITLE
Optional terraform binaries

### ISSUE THREAD

**Issue by soulman-is-good** [hashicorp/terraform-cdk#349]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Our setup:
- We work with `typescript` template
- We use Azure
- We use ts-node to run the code w/o compiling to a files
- We use generated terraform json to run in Azure DevOps release pipelines

Would be great to have an option not to make symbolic link to `.terraform` when doing synth

**Comment by skorfmann** [comment]
That's already being worked on in #344

**Comment by skorfmann** [comment]
@soulman-is-good I'm curious about the azure devops pipeline you mentioned. Is it a public one or something you built yourself? In particular since you mentioned that there are no terraform binaries involved - could you elaborate on that?

**Comment by soulman-is-good** [comment]
@skorfmann I would like to express my excitement regarding this project and really want it to evolve.
The way how we use it right now is we write infra in typescript then we run main.tf with ts-node which creates cdktf.json file to run with terraform. This is perfect for us to use as deployment artifact in our flow.

Regarding ADO, not sure if I understand what did you mean by "built yourself".
https://azure.microsoft.com/en-us/services/devops/?nav=min
We are using this platform to run our terraform code. Corporate project is not public so unfortunately I won't be able to provide a link.

Regarding terraform binaries. When I run `cdktf get` it creates `.terraform` folder under the root of project.<br>
When I run `synth` it builds json file and puts `.terraform` into `cdktf.out`. I had to add `unlink` to main.tf file to mitigate this, as we want to pack and deploy this json file as an artifact to be used in ADO pipelines after.

**Comment by skorfmann** [comment]
Yes, I was curious how you use Azure Devops for deployment. Looked into it again, and it looks very similar to Github Actions.

> When I run `synth` it builds json file and puts `.terraform` into `cdktf.out`. I had to add `unlink` to main.tf file to mitigate this, as we want to pack and deploy this json file as an artifact to be used in ADO pipelines after.

Right, that makes sense. Thanks for the info 👍
