### ISSUE TITLE
Running under the proxy

### ISSUE THREAD

**Issue by soulman-is-good** [hashicorp/terraform-cdk#351]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In our organisation we use proxy to get to internet.

When run `cdktf get` exception is thrown:
```
Error: getaddrinfo ENOTFOUND checkpoint-api.hashicorp.com
```
So I have to go to sources and add proxy to checkpoint.js request to get typescript files for azure provider.

If would be great if cli would respect HTTPS_PROXY environment variable

### References

https://github.com/hashicorp/terraform-cdk/blob/master/packages/cdktf-cli/lib/checkpoint.ts#L25

**Comment by skorfmann** [comment]
Thanks for reporting this issue, I believe that's a regression of #326 - Networking issues shouldn't interrupt the workflow here.

**Comment by skorfmann** [comment]
In the meantime, you can disable the metrics via the `CHECKPOINT_DISABLE` env.

**Comment by soulman-is-good** [comment]
Thanks @skorfmann that works for me

**Comment by sonfrau** [comment]
> 
> 
> In the meantime, you can disable the metrics via the `CHECKPOINT_DISABLE` env.

The command "CHECKPOINT_DISABLE=true cdktf get" worked for me.

Thanks!

**Comment by timpur** [comment]
i just ran into this problem also, wondering if we can add the env to `cdktf.json` as context or something so that we can consistently disable it for the project ?

**Comment by jsteinich** [comment]
> wondering if we can add the env to `cdktf.json` as context or something

Not currently, but that sounds like a reasonable request.

**Comment by skorfmann** [comment]
As mentioned in https://github.com/hashicorp/terraform-cdk/issues/545 we should just catch the error and ignore it.
