### ISSUE TITLE
GCP & AZURE Python Support

### ISSUE THREAD

**Issue by AmrMKayid** [hashicorp/terraform-cdk#355]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Does the current version of the CDK support GCP & AZURE for python deployment? Are there any available examples for these cloud providers?

**Comment by skorfmann** [comment]
There's one [pull request](https://github.com/hashicorp/terraform-cdk/pull/350) for a Python Azure example. Other than that, it's pretty similar to the [Typescript examples](https://github.com/hashicorp/terraform-cdk/tree/master/examples/typescript), and should be transferable to Python.

In general, Terraform CDK isn't limited to particular providers. All available providers for Terraform should work with Terraform CDK in all supported languages - JS / Typescript and Python at the moment.

**Comment by skorfmann** [comment]
I think we can close this, I'm sure more examples will be added in the future. Please reopen, if something hasn't been answered from your point of view.
