### ISSUE TITLE
CDKTF: Fn.Secret returns string when inputting an array for on C#

### ISSUE THREAD

**Issue by klemmchr** [hashicorp/terraform-cdk#3560]
### Expected Behavior

`Fn.Secret` should return an array of the input element type when inputting an array.

### Actual Behavior

`Fn.Secret` returns a string

### Steps to Reproduce

1. Create a `TerraformLocal` with a string array as a value
2. Use Fn.Secret on it

### Versions

language: csharp
cdktf-cli: 0.20.1
node: v20.9.0
cdktf: 0.20.4
constructs: 10.3.0
jsii: 1.95.0
terraform: 1.3.1
arch: x64
os: win32 10.0.22631
dotnet: 8.0.202
providers
HashiCorp.Cdktf.Providers.Azuread (PREBUILT)
        terraform provider version: 2.47.0
        prebuilt provider version: 12.0.0
        cdktf version: ^0.20.0
HashiCorp.Cdktf.Providers.Azurerm (PREBUILT)
        terraform provider version: 3.96.0
        prebuilt provider version: 12.10.0
        cdktf version: ^0.20.0
HashiCorp.Cdktf.Providers.Local (PREBUILT)
        terraform provider version: 2.5.1
        prebuilt provider version: 10.1.0
        cdktf version: ^0.20.0
HashiCorp.Cdktf.Providers.Null (PREBUILT)
        terraform provider version: 3.2.2
        prebuilt provider version: 10.0.0
        cdktf version: ^0.20.0
HashiCorp.Cdktf.Providers.Random (PREBUILT)
        terraform provider version: 3.6.0
        prebuilt provider version: 11.0.0
        cdktf version: ^0.20.0

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
> should return an array of the input element type when inputting an array

This is impossible to do since JSII (the tool we use to get from TS to any other language) does [not support generics](https://aws.github.io/jsii/user-guides/lib-author/typescript-restrictions/#typescript-mapped-types). You need to use [Token](https://developer.hashicorp.com/terraform/cdktf/concepts/tokens) type casts, e.g. `Token.asList`

**Comment by klemmchr** [comment]
Does that mean that this is already supported when wrapping the returned token with `Token.asList`?;

**Comment by DanielMSchmidt** [comment]
Yes
