### ISSUE TITLE
Build and Push Docker Image Automatically 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#36]
Follow up for #23

**Comment by anubhavmishra** [comment]
I just pushed a new version of the docker image: https://hub.docker.com/r/hashicorp/jsii-terraform

**Comment by skorfmann** [comment]
@anubhavmishra let's just move our docker image to the Github Registry https://github.blog/2020-09-01-introducing-github-container-registry/ - I think this might solve our issues.

**Comment by skorfmann** [comment]
Create a pr to build the docker image only if the dockerfile has changed and publish to docker hub

**Comment by skorfmann** [comment]
That was done a while ago
