### ISSUE TITLE
GOOGLE_COMPUTE_REGION_BACKEND_SERVICE doesn't have security policy field

### ISSUE THREAD

**Issue by cyber-francis** [hashicorp/terraform-cdk#3611]
### Description

This feature is available on GCP console, but is not available in TF. Also, it is available on the google_compute_backend_service

### References

N/A

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by ansgarm** [comment]
Hi @cyber-francis 👋

Could you share which version of CDKTF, the google (pre-built?) provider you use and on which language?

If it is available in Terraform, it should be available in CDKTF as well, so you might be on an outdated version somehow 🙂
