### ISSUE TITLE
terraform-aws-modules/vpc module fails to compile with Java

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Branch for #360

### Affected Resource(s)

`VpcOptions`

### Expected Behavior

Generated modules classes compile and module is usable.

### Actual Behavior

Failed to compile, too many parameters in `VpcOptions` constructor

### Steps to Reproduce

Add terraform-aws-modules/vpc to the terraform modules of a java project, run `cdktf get`, then `mvn compile`

### Important Factoids

Java has a limit of 255 parameters for a method. The module currently has 375 inputs.

### References

* #360

### Possible Solutions

1. Modify the jsii java code generator to split the construction into pieces when above the parameter limit (or always)
2. Write a special case into cdktf code generation to split `VpcOptions` into multiple chunks, i.e. `VpcOptions` and `ExtendedVpcOptions`, or more logical groupings
3. Write a logical replacement for the module using constructs.

- I haven't looked into the feasibility of the first option, but that would be the most seamless user experience.
- If we can come up with a division that works for common use cases, the second option could be a smooth user experience.
- The third option makes a lot of sense long term, but given that the vpc module has almost 5 million downloads, would likely be rough for adoption.

### Other Affected Modules

I wrote a script to scan the terraform module registry for other modules that would fail. They all appear to be forks of the vpc module...

- lablabs/vpc/aws/2.18.0 282
- mishra-demos/vpc/aws/2.18.0 282
- cncoder/vpc/aws/2.22.0 292
- swapnamareddy/vpc/aws/2.39.0 366
- HDE/vpc/aws/2.47.0 375
- hhmmll/vpc/aws/2.44.0 375
- ntmsvicky1/vpc/aws/2.48.0 375
- terraform-aws-modules/vpc/aws/2.48.0 375
- yojota/vpc-aper/aws/1.2.0 375
- yojota/vpc/aws/2.44.0 375

*the second value is the number of inputs the module has

**Comment by skorfmann** [comment]
> The module currently has 375 inputs.

😱

> Java has a limit of 255 parameters for a method.

Heh, that's interesting 😄 

> 1. Modify the jsii java code generator to split the construction into pieces when above the parameter limit (or always)

Not sure what you mean by that, could you explain a bit more?

> 2\. Write a special case into cdktf code generation to split `VpcOptions` into multiple chunks, i.e. `VpcOptions` and `ExtendedVpcOptions`, or more logical groupings

Hmmmm, that sounds like it would cause lots of longterm maintenance issues

> 3\. Write a logical replacement for the module using constructs.

I'm sure someone will do it at some point, but I don't think that's the right approach here. I was thinking that it might be a workaround if we would be able to transform the entire module automatically, but we'd still end up having a huge interface of options, wouldn't we?

I know it's probably one of the most popular modules, nevertheless I'm leaning towards ignoring this issue for now. It seems to be limited to the AWS VPC module only.

**Comment by jsteinich** [comment]
> Not sure what you mean by that, could you explain a bit more?

There is currently a class named `Jsii$Proxy` that is generated for `VpcOptions`. That class has two constructors. The problematic one, which is used by the builder class, takes each input as a parameter. The proxy fields could be set via setters/direct field access instead (or some more complicated additional method(s) for parameters above the limit). This would force the proxy fields to be non-final, so definitely some other implications there.

> I was thinking that it might be a workaround if we would be able to transform the entire module automatically, but we'd still end up having a huge interface of options, wouldn't we?

Yeah, unless we didn't create the option struct and only exposed setters.


> I know it's probably one of the most popular modules

Currently the 2nd most downloaded module on the registry.

We can certainly wait and see if it becomes a frequent issue.

**Comment by digitalsanctum** [comment]
I was pointed here from #470 not realizing this was the same issue.

My 2 cents: The best solution to me is to break up the constructor to use configuration objects that make sense from a functional point of view. Looking at the args there seem to be a ton of toggles/booleans for enabling endpoints so perhaps that could be a candidate for a object to encapsulate specific functionality? There are other groupings such as args for "Code Build" and "Code Deploy", and various database specific args.

It may also make sense to provide a default constructor with minimal args to just define CIDR/subnets which I suspect would take care of 80% of use cases? For example, https://github.com/digitalsanctum/cdktf-kotlin-demo/blob/master/src/main/kotlin/io/futz/cdktf/Main.kt#L19.

**Comment by digitalsanctum** [comment]
Looking at the docs for the aws cli (`create-vpc`) and the API call ('CreateVpc`) most of the args defined in the cdktf VpcOptions are not there which leads me to question why many of the args are part of VpcOptions in the first place.

**Comment by jsteinich** [comment]
I'm not sure that modifying the module generation code makes a lot of sense. Instead, this seems like a great area for a higher level construct similar to https://docs.aws.amazon.com/cdk/api/latest/docs/@aws-cdk_aws-ec2.Vpc.html

**Comment by digitalsanctum** [comment]
Even if a new construct is added won't we still need a workaround for the 255 parameter limit being exceeded? It seems the module generation code needs to be changed if folks opt *not* to use whatever higher level construct is added.

**Comment by skorfmann** [comment]
While the AWS VPC module is certainly one of the more popular ones, I think it's an edge case and I wouldn't spend a lot of time to implement a workaround at this time. As far as I see it: 

- 375 inputs is just incredibly high 
- It seems to be an issue for Java only
- It seems to affect only one module 
- There are a bunch of other module related improvements we could do with a much higher impact 

Perhaps this could be part of https://github.com/hashicorp/terraform-cdk/issues/231 - since this will have to have some knowledge about transforming modules anyway.

**Comment by skorfmann** [comment]
> I'm surprised and disappointed by that response. I don't consider creating a VPC an edge case.

Sorry, I phrased this in the wrong way and could have been more detailed in my reply. What I meant to say: I think the issue of having more than 255 arguments for the constructor is an edge case, which only affects one - very popular - module. As stated above, I think it could make sense to tackle this issue as part of #231. However, it's likely not the very next issue we'll be working on.

What @jsteinich [suggested](https://github.com/hashicorp/terraform-cdk/issues/365#issuecomment-751527405) could be a good alternative.

Another workaround might be a [stack escape hatch](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/escape-hatch.md#stack-escape-hatch). The corresponding syntax for modules can be found [over here](https://www.terraform.io/docs/configuration/syntax-json.html#module-blocks). This won't give you abstracted outputs of the module, but you could still reference them manually. Would this help in your case?

**Comment by digitalsanctum** [comment]
@skorfmann Thanks for the kind reply. Yes, I think a stack escape hatch will suffice for my use case and I look forward to a more idiomatic solution.

**Comment by skorfmann** [comment]
Cool, thanks for the feedback 👍

**Comment by jsteinich** [comment]
An alternative to using an escape hatch is the [TerraformHclModule](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#using-modules). While it can be used directly, you can also extend it to provide typed inputs and outputs (could just add the values from the vpc module that you are actually using).

**Comment by skorfmann** [comment]
> An alternative to using an escape hatch is the [TerraformHclModule](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#using-modules). While it can be used directly, you can also extend it to provide typed inputs and outputs (could just add the values from the vpc module that you are actually using).

That's even better than the escape hatch, of course 👍
