### ISSUE TITLE
Go language support

### ISSUE THREAD

**Issue by philiphorrocks** [hashicorp/terraform-cdk#368]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Go language support for  CDK TF

**Comment by anubhavmishra** [comment]
Hey @philiphorrocks, thanks for opening this issue. Golang support for any CDK ecosystem project depends on [jsii](https://github.com/aws/jsii) to enable us to generate CDK constructs. Currently, jsii doesn't have support for Golang but from what we know, it is being worked on by the team. GH issue: https://github.com/aws/jsii/issues/83

**Comment by skorfmann** [comment]
The overall progress of GoLang support for jsii can be tracked here https://github.com/aws/jsii/projects/2

**Comment by nikolaishields** [comment]
Here to upvote this issue!

**Comment by icereed** [comment]
Golang JSII support is in developer preview now. Any chance this can be tried out for terraform-cdk?

**Comment by jsteinich** [comment]
Initial support will probably wait for jsii-srcmak to support go. See https://github.com/aws/jsii-srcmak/pull/342

**Comment by danieldreier** [comment]
AWS CDK now has Go support as a developer preview feature, so we should work to also provide a developer-preview version of Go support.

**Comment by weberc2-tempus** [comment]
@jsteinich I see that https://github.com/cdklabs/jsii-srcmak/pull/476 has been merged (which supersedes https://github.com/cdklabs/jsii-srcmak/pull/342), so I'm curious what are next steps?

**Comment by jsteinich** [comment]
@weberc2-tempus Work has been in-progress for awhile now. I expect that a preview release will be available soon. Take a look [here](https://github.com/hashicorp/terraform-cdk/pull/686) for more detailed progress.

**Comment by weberc2-tempus** [comment]
Oh, awesome, thanks a lot!

**Comment by ansgarm** [comment]
Just a heads up for everyone subscribed: We [released 0.4](https://www.hashicorp.com/blog/announcing-cdk-for-terraform-0-4) today. Please check out the experimental Go support 🚀 We're looking forward for feedback on this!
