### ISSUE TITLE
Feature Request: Enable Vector Search Functionality for AWS MemoryDB Cluster

### ISSUE THREAD

**Issue by trend-ted-rong-r** [hashicorp/terraform-cdk#3721]
## Summary
Enable the ability to configure the Vector Search functionality for AWS MemoryDB Clusters through the Terraform CDK. Currently, this feature is available in the AWS console but is not accessible via the CDK.

## Background
AWS MemoryDB recently introduced a Vector Search capability that can be enabled at the time of cluster creation. This feature is crucial for applications requiring advanced search capabilities. However, there is no current way to enable this feature using the Terraform CDK, limiting automation and infrastructure as code practices.

## Proposed Solution
Introduce support for configuring the Vector Search functionality in the aws_memorydb_cluster resource within the Terraform CDK. This will allow users to specify the Vector Search option during the creation of MemoryDB clusters.

## Benefits
Automate the deployment of MemoryDB clusters with Vector Search enabled.
Enhance the Terraform CDK's capability to match AWS console features.
Streamline workflows for developers and operations teams utilizing MemoryDB for search-intensive applications.

Please consider adding this feature to align with the latest AWS offerings and improve the Terraform CDK's functionality.

### References

[AWS Documentation](https://docs.aws.amazon.com/memorydb/latest/devguide/vector-search-console.html)
[Terraform CDK Documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_cluster)

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by jsteinich** [comment]
Vector search can be enabled by creating a parameter group with a parameter named `search-enabled` set to `yes`.

* https://docs.aws.amazon.com/memorydb/latest/devguide/vector-search-cli.html
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/memorydb_parameter_group

**Comment by trend-ted-rong-r** [comment]
Thanks, @jsteinich. That worked for me.
