### ISSUE TITLE
How to get the list of AZ's of a specific region

### ISSUE THREAD

**Issue by ryands17** [hashicorp/terraform-cdk#374]
I have created code like this:

```ts
    const provider = new aws.AwsProvider(this, 'aws', {
      region: REGION,
    })
    const azs = new aws.DataAwsAvailabilityZones(this, 'region-azs', {
      provider,
      state: 'available',
    })
```

and when I log `azs.names` I get a weird token type string. Something like `'#{Token[TOKEN.0]}'`.

Is there any configuration that I am missing?

**Comment by skorfmann** [comment]
> and when I log `azs.names` I get a weird token type string. Something like `'#{Token[TOKEN.0]}'`.
> Is there any configuration that I am missing?

The behaviour is broken and you're not missing anything. We'll look into that.

Meanwhile, could you elaborate on what you're going to do with the `azs.names` so that we can better understand your use-case? Perhaps there's a workaround to address this.

**Comment by ryands17** [comment]
My use-case was fetching the AZ's dynamically so that I don't need to hardcode them when I switch regions. I wanted to perform something like this: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones#by-state

Deploying 2 subnets in different AZ's by fetching the list automatically and assign each subnet to an AZ.

**Comment by skorfmann** [comment]
Off the top of my head, you could probably do something like this:

```ts

    const provider = new aws.AwsProvider(this, 'aws', {
      region: REGION,
    })
    const azs = new aws.DataAwsAvailabilityZones(this, 'region-azs', {
      provider,
      state: 'available',
    })

    new aws.Subnet(this, 'subnet', { availability_zone: `\${${azs.fqn}.names[0]}` })
```

It's not pretty, but it should work. The entire topic of referencing complex types will get reworked and should address issues like this as well.

**Comment by ryands17** [comment]
That works like a charm! Thank you :)

**Comment by skorfmann** [comment]
Probably related to https://github.com/hashicorp/terraform-cdk/issues/256

**Comment by karthikns16** [comment]
@skorfmann , This workaround doesn't to help if the attribute is a set() and I am coding cdk-terraform in python. 

my understanding you can access a set with index and that you have use [ for i in set() : set.<attribute> ]. any suggestions will be much appreciated.

**Comment by skorfmann** [comment]
> @skorfmann , This workaround doesn't to help if the attribute is a set() and I am coding cdk-terraform in python.
> 
> my understanding you can access a set with index and that you have use [ for i in set() : i.attribute ]. any suggestions will be much appreciated.

@karthikns16 do you have an example of what you want to do? 

I recently did something like this in a Typescript project, but I'm not sure if that's what you're looking for.

```ts
    const record = new aws.Route53Record(this, 'validation-record', {
      name: "${each.value.name}",
      type: "${each.value.type}",
      records: [
        "${each.value.record}"
      ],
      zoneId: zone.zoneId,
      ttl: 60,
      allowOverwrite:  true
    })

    record.addOverride('for_each', `\${{
       for dvo in ${cert.fqn}.domain_validation_options : dvo.domain_name => {
          name   = dvo.resource_record_name
          record = dvo.resource_record_value
          type   = dvo.resource_record_type
        }
      }
    }`)
```

**Comment by karthikns16** [comment]
@skorfmann thanks for the tip, the syntax is pretty tricky. I got it to work in python. It was missing a ${ in front and } at the end

```python
audience = TerraformOutput(
            self,
            "OktaAppAuthServerAudience",
            value="empty"
        )

audience.add_override(
    "value",
    "${[ for audience in "+auth_server.fqn+".audiences : audience ][0]}"
)
```

hcl syntax does not need the ${ and }

```hcl
output "okta_auth_server_audiences" {
  value = [for i in  okta_auth_server.outh_app_server.audiences : i][0]
}
```

btw, finding the meaning of .fqn function was not straight forward either. Is there api reference guide of the cdktf functions?

**Comment by kevishaholli** [comment]
Any update on this?  The workaround seems like a hack.

**Comment by jsteinich** [comment]
> btw, finding the meaning of .fqn function was not straight forward either. Is there api reference guide of the cdktf functions?

Not at this time. The Terraform provider documentation is generally your best place to look; however, I realize that doesn't cover the few built in pieces like `fqn`. It's been brought up a couple times now, so I'll make a separate issue to track.

**Comment by jsteinich** [comment]
> Any update on this? The workaround seems like a hack.

We are working on some changes which are a perquisite to making this work better (this issue has ballooned some, so some pieces will be covered directly), but it will take some time before we have a better solution for working with for loops.

**Comment by jsteinich** [comment]
The original request of accessing an az can now be accomplished through `Fn.element(azs.names, 0)` to get the first availability zone.
Accessing sets is something that is still in-progress.
Looping has definitely been talked about, but will probably be awhile before anything is put in place there.

**Comment by DanielMSchmidt** [comment]
It's now nested, in the datasources object I believe

**Comment by richmeij** [comment]
@DanielMSchmidt yes! Thank you! Can you give me any pointers as to where I could have found this myself? Its a bit unclear to me which part in the documentation to turn to.

**Comment by DanielMSchmidt** [comment]
The Terraform provider docs (https://registry.terraform.io/providers/hashicorp/aws/latest/docs) have a side bar, the namespaces for the provider are in those. It's just the AWS provider right now, due to the size (it lead to code generation issues with JSII)

**Comment by richmeij** [comment]
@DanielMSchmidt Thank you! 🙏
