### ISSUE TITLE
cdktf deploy for typescript-docker failed to output docker providers in cdk.tf.json

### ISSUE THREAD

**Issue by ming0601** [hashicorp/terraform-cdk#377]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Terraform V0.13.2
cdktf-cli 0.0.17-pre.175c3872827c1325d32ecc7ea7150a2774da0121
cdktf package version 0.0.17-pre.175c3872827c1325d32ecc7ea7150a2774da0121
### Affected Resource(s)

docker-provider

### Debug Output

⠧ initializing typescript-docker...

Error: Failed to install providers

Could not find required providers, but found possible alternatives:

  hashicorp/docker -> terraform-providers/docker

If these suggestions look correct, upgrade your configuration with the
following command:
    terraform 0.13upgrade .

non-zero exit code 1

### Expected Behavior

The expected Terraform JSON (cdk.tf.json) that is valid is as follows:

{
  "//": {
    "metadata": {
      "version": "0.0.17-pre.175c3872827c1325d32ecc7ea7150a2774da0121",
      "stackName": "typescript-docker"
    }
  },
  "terraform": {
    "required_providers": {
      "docker": {
        "source": "terraform-providers/docker"
      }
    }
  },
### Actual Behavior

The expected Terraform JSON (cdk.tf.json) that is valid is as follows:

{
  "//": {
    "metadata": {
      "version": "0.0.17-pre.175c3872827c1325d32ecc7ea7150a2774da0121",
      "stackName": "typescript-docker"
    }
  },
"resource": {...}
### Steps to Reproduce

Follow the tutorial from Terraform : https://learn.hashicorp.com/tutorials/terraform/cdktf-install
### Important Factoids
When running
Run cdktf deploy
the output file doesn't contain any data for provider docker.

### References

* #303 
My case is quite similar to the Issue #303 but this time there isn't any output data for the Docker Provider in the cdk.tf.json file. Tried on Linux Mint 19.3 and MacOS 10.15.6 : same result.

**Comment by jsteinich** [comment]
What does your `cdktf.json` file contain?

Also take a look at the [docker example](https://github.com/hashicorp/terraform-cdk/tree/master/examples/typescript/docker).

**Comment by ming0601** [comment]
Here is my cdktf.json content 

{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "terraform-providers/docker@~> 2.0"
  ]
}

same as the docker example file.

Tested also with aws (aws@~>2.0) and google (google@~>2.5.0) providers, they work well. I have the right output.

**Comment by jsteinich** [comment]
I'm able to reproduce this by omitting `new DockerProvider(this, 'provider', {})` from the sample. After adding it back in, things work as expected.

**Comment by ming0601** [comment]
Hurrah, it's working. I've cleaned all installations of Terraform and cdktf-cli. Then I pulled the project on GitHub, it's working! Thank you for your support @jsteinich !
