### ISSUE TITLE
Prebuilt Snowflake provider didn't generate for v1.0.0

### ISSUE THREAD

**Issue by iveselin-glooko** [hashicorp/terraform-cdk#3791]
### Expected Behavior

Generated versions for both v0.100.0 and v1.0.0 for https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases

### Actual Behavior

Generated version for v0.100.0 but not for v1.0.0

### Steps to Reproduce

1. Open https://github.com/Snowflake-Labs/terraform-provider-snowflake/releases and review the list of releases
2. Open https://github.com/cdktf/cdktf-provider-snowflake/releases and review the list of releases
3. compare the two

### Versions

-

### Providers

-

### Help Wanted

- [ ] I'm interested in contributing a fix myself

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by DanielMSchmidt** [comment]
Hey, there is a PR open for this major upgrade to happen, once it's merged there should be a new pre-built provider release. It should be merged & released over the next days: https://github.com/cdktf/cdktf-repository-manager/pull/341
