### ISSUE TITLE
Configure Github Codespaces

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#381]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

![Screenshot 2020-09-23 at 20 13 39](https://user-images.githubusercontent.com/136789/94053182-475a0080-fdda-11ea-8129-7cf78059170c.png)

To enable PR reviews directly in Github [Codespaces](https://github.com/codespaces) it would be quite nice to configure  with a Docker image that supports all target languages, terraform and the requirements of Codespaces itself. See here https://docs.github.com/en/github/developing-online-with-codespaces/configuring-codespaces-for-your-project

**Comment by jsteinich** [comment]
Might be pretty simple: https://github.com/aws/aws-cdk/pull/10470
