### ISSUE TITLE
Failed to load config file error?

### ISSUE THREAD

**Issue by justindra** [hashicorp/terraform-cdk#383]
I am just trying to run the following example:
https://github.com/hashicorp/terraform-cdk/blob/master/examples/typescript/aws-cloudfront-proxy/main.ts

But running into an error when doing a deploy

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* cdktf - 0.0.17
* typescript 4.0.3

### Debug Output

```
Error: error creating EC2 Metadata session: SharedConfigLoadError: failed to load config file, /home/justin/.aws/credentials
caused by: INIParseError: invalid state with ASTKind { {4 NONE 0 [61]} true [{expr {1 STRING 0 [97 119 115 95 115 101 99 114 101 116 95 97 99 99 101 115 115 95 107 101 121]} true []}]} and TokenType op

  on cdk.tf.json line 20, in provider.aws[0]:
  20:       },
non-zero exit code 1
```

the given lines in `cdk.tf.json` are as follows (expanded to show others):
```jsonc
{
...
  "provider": {
    "aws": [
      {
        "region": "us-west-2"
      }, // line 20
      {
        "region": "us-east-1",
        "alias": "route53"
      }
    ]
  },
}
```

### Expected Behavior

Should deploy properly

### Actual Behavior

Produces the error above, and the error doesn't seem to make too much sense.

### Steps to Reproduce

1. Copy the example and replace contents of `main.ts`
2. `cdktf synth`
3. `cdltf deploy`

### Important Factoids

I have multiple AWS Profiles setup in the credentials file, but this should be using the default profile (I assume).
### References

* #0000

**Comment by skorfmann** [comment]
This looks very similar to this https://github.com/terraform-providers/terraform-provider-aws/issues/14450  and might be either an actual aws-sdk upstream bug, or a format / config error. Is this issue only occurring when using `cdktf` or shows using `terraform` cli directly the same issues?

**Comment by skorfmann** [comment]
It's likely a configuration error / or an upstream bug. In any case, nothing we can tackle without more context. Please reopen with more information.
