### ISSUE TITLE
Parametrizing with different remote states causes unexpected issues

### ISSUE THREAD

**Issue by kaisellgren** [hashicorp/terraform-cdk#384]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Terraform v0.12.29
+ provider.google v3.30.0

"cdktf": "0.0.17",
"constructs": "^3.0.4"
"cdktf-cli": "0.0.17",

### Expected Behavior

diff & deploy should work normally.

### Actual Behavior

Sometimes cdktf hangs forever at `initializing <name>...` and sometimes I get:

```
⠹ initializing builds...
⠙ initializing builds...

2020/09/26 18:34:39 [TRACE] backendMigrateState: both source and destination workspaces have states, so might overwrite destination with source

Error: error asking for state migration action: input disabled

non-zero exit code 1
```
And sometimes different states get entangled so that diffing a dev environment will want to destroy staging and prod resources.

### Steps to Reproduce

I am using env variables to parametrize cdktf. I have ENV set to dev/staging/prod. Each env specifies a diff remote state:

```typescript
    new GcsBackend(this, {
      bucket: 'terraform-state',
      prefix: `app-${process.env.ENV}`,
    })
```

I also have two stacks: `app` and `builds` stacks. They both have the same env specific parameters, and `builds` stack has this:

```typescript
    new GcsBackend(this, {
      bucket: 'terraform-state',
      prefix: `builds-${process.env.ENV}`,
    })
```

If I run cdktf diff or cdktf deploy, it either hangs forever, produces the error shown earlier or shows wrong diff results (wanting to delete resources of other environments).

The only way to make it work is to do `rm -rf cdktf.out`. If I always delete the `out` folder then it works so it has to do with its existence. This also seems to be universal across every type of resource. Right now my script just runs `rm -rf cdktf.out` and it works well that way.

### References

* #0000

**Comment by skorfmann** [comment]
Sounds similar to what's described in this comment https://github.com/hashicorp/terraform-cdk/issues/376#issuecomment-694956456

**Comment by DanielMSchmidt** [comment]
I think this is the same as #398; I could not reproduce that one, if it's fundamentally different please let me know and I'll see if this is still an issue 👍
