### ISSUE TITLE
Terraform errors should be shown when running cdktf commands

### ISSUE THREAD

**Issue by kaisellgren** [hashicorp/terraform-cdk#385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

"cdktf": "0.0.17",
"cdktf-cli": "0.0.17",

### Debug Output
```
Error: Error, failed to create instance master-instance: googleapi: Error 409: The Cloud SQL instance already exists. When you delete an instance, you cannot reuse the name of the deleted instance until one week from the deletion date., instanceAlreadyExists
⠧ Deploying Stack: xxx
Resources
 ⠼ GOOGLE_SQL_DATABASE_ dbmaster            google_sql_database_instance.xxx_dbmaster_39528157
```

### Expected Behavior

When running cdktf deploy it fails without showing any reason as to _why_ it failed. I had to run `export TF_LOG=debug` in order to see the error produced by Terraform. The above error should be displayed without needing to set TF_LOG=debug or something similar like that.

### Actual Behavior

Terraform's errors should be passed down through cdktf so that we can see them without having to modify TF_LOG level.

I only got a generic error exit:

```
non-zero exit code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
Terraform's error wasn't displayed.
### References

* #0000

**Comment by paulvonallwoerden** [comment]
As a interim solution you may execute cdktf in the following way:

```bash
    CDKTF_DISABLE_LOGGING=false cdktf --log-level DEBUG deploy
```

## Explanation

* The env `CDKTF_DISABLE_LOGGING` is set as cdktf-cli will only write a log file if it is explicitly set to `false`. https://github.com/hashicorp/terraform-cdk/blob/e39f5e5847b9eb928f17be51d5f8f42ea5ab3112/packages/cdktf-cli/lib/logging.ts#L7-L12 

* The log level has to be set to `DEBUG` as the `stderr` from terraform will  be piped to a `processLogger` function https://github.com/hashicorp/terraform-cdk/blob/e39f5e5847b9eb928f17be51d5f8f42ea5ab3112/packages/cdktf-cli/lib/util.ts#L62-L64 
that will log the **error** with severity **debug**.
https://github.com/hashicorp/terraform-cdk/blob/e39f5e5847b9eb928f17be51d5f8f42ea5ab3112/packages/cdktf-cli/lib/logging.ts#L14-L16

**Comment by paulvonallwoerden** [comment]
Also, in your special case of using the google cloud provider, there is a very helpful page that shows all activities made by terraform (and everyone else on the GCP project).
> https://console.cloud.google.com/home/activity

Failed api request (e.g., with http status code 400 because of an incorrect configuration) made by terraform will be shown there with a detailed error message of what went wrong.

I know thats more of a terraform specific solution but until cdktf has basic logging functionality thats very helpful for debugging.

**Comment by skorfmann** [comment]
Related to https://github.com/hashicorp/terraform-cdk/issues/218

**Comment by adamdry** [comment]
Thanks, this helps although the format of the log file isn't the best - is there a reader/parser for it so I didn't get loads of unknown chars when I'm trying to read it?

**Comment by DanielMSchmidt** [comment]
I tried to reproduce this, but it seems to be solved: I ran with the smallest amount of logging (`CDKTF_DISABLE_LOGGING=true cdktf --log-level=error apply --auto-approve`) and still got the errors from terraform printed both in watch and apply. 

If anyone still runs into this issue with a newer version than 0.8.5 that I tested it with, please let me know and we can reopen the issue 👍
