### ISSUE TITLE
Usng pypi pip for installing cdktf-cli

### ISSUE THREAD

**Issue by yrsurya** [hashicorp/terraform-cdk#386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
So far to install cdktf-cli we need to use npm , $ npm install -g cdktf-cli
Instead it would be nice if we can get pypi pip package to install

**Comment by skorfmann** [comment]
> Instead it would be nice if we can get pypi pip package to install

Could you elaborate on the motivation behind it?

**Comment by yrsurya** [comment]
As cdktf-cli also supports python along with javascript and all python packages are available in https://pypi.org/ . It will be convenience to install cli tool directly from there so no need to have npm/nodejs.

 @snimark can provide more info

**Comment by covracer** [comment]
In case folks searching around find this issue, https://pypi.org/project/cdktf/ and some pre-built provider packages such as https://pypi.org/project/cdktf-cdktf-provider-aws/ are available.
