### ISSUE TITLE
ERROR: Invalid requirement: 'cdktf~=0.0.17-pre.66613656b954d42a7aeaf40bd351f741fbda4e11'

### ISSUE THREAD

**Issue by wonboyn** [hashicorp/terraform-cdk#387]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli@0.0.17-pre.66613656b954d42a7aeaf40bd351f741fbda4e11

python v3.8

### Affected Resource(s)

cdktf init failing

### Debug Output

See error message from issue title

### Expected Behavior

cdktf init --template="python" --local  should not throw an error

### Actual Behavior

Running the init throws the error & leaves the requirements.txt file behind.

### Steps to Reproduce

- install cdktf v0.0.17
- run cdktf init --template="python" --local

**Comment by jsteinich** [comment]
Likely the same as https://github.com/hashicorp/terraform-cdk/issues/293.
I think for now you'll need to rollback to 0.0.17

**Comment by skorfmann** [comment]
> I think for now you'll need to rollback to 0.0.17

Yes, as @jstein said - please downgrade your `cdktf-cli` to `0.0.17`
