### ISSUE TITLE
Handle jsii incompatible names

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#39]
![Screenshot 2020-04-30 at 21 26 12](https://user-images.githubusercontent.com/136789/80750982-48d41500-8b29-11ea-9400-a2dcc4c63231.png)

Follow up for #31

**Comment by jsteinich** [comment]
For the most part jsii-pacmak (which jsii-srcmak uses) will handle renaming reserved names. It's a potentially breaking change, but it would be nice if this either wasn't used (relying on jsii replacement) or was also used in the module generator so that names were consistent.

**Comment by DanielMSchmidt** [comment]
JSII handles renaming by now I think, can we close this @skorfmann?

**Comment by jsteinich** [comment]
> JSII handles renaming by now I think, can we close this @skorfmann?

It actually isn't that great at it. See https://github.com/aws/jsii/issues/2155

**Comment by skorfmann** [comment]
> JSII handles renaming by now I think, can we close this @skorfmann?

I think we still have custom logic, and not sure if that's spread around the code. For example, how does handle `convert` the special casing?

**Comment by DanielMSchmidt** [comment]
Convert does not handle the special casing, it would make sense to refactor this so that convert uses the renamings as well

**Comment by DanielMSchmidt** [comment]
I created issues for convert for the renaming: https://github.com/hashicorp/terraform-cdk/issues/1552 and https://github.com/hashicorp/terraform-cdk/issues/1708

Closing this issue as everything is covered in the follow ups
