### ISSUE TITLE
equivalent of aws cdk patterns

### ISSUE THREAD

**Issue by saxenark** [hashicorp/terraform-cdk#390]
Hi,

I am having difficulty in understanding whether to use aws cdk or terraform cdktf. From my work so far, it appears to me that aws cdk has more robust patterns and constructs which will comply with the well architected framework, all available out of the box. Terraform cdktf will require hand crafting many of such constructs and patterns.

An example in point is the construct [ecs_patterns.ApplicationLoadBalancedEc2Service](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-ecs-patterns-readme.html) which does a lot of heavy lifting in spinning up a industrial strength infrastructure for EC2 based ECS service. I can't find the equivalent of that in Terraform cdktf and it appears I will have to manually assemble and connect all the infra elements.

However, Terraform apparently has the advantage of working with several different cloud vendors, and therefore I want to do due diligence before choosing one of the other. Is such a feature planned for cdktf?

Thanks

**Comment by skorfmann** [comment]
The Terraform CDK generates a 1:1 mapping for the Terraform provider schema. Some of the Terraform providers provide a few abstractions over the raw SDKs / APIs already which you therefore can use with the Terraform CDK as well. However, in CDK terms we're generating [Level 1](https://docs.aws.amazon.com/cdk/latest/guide/constructs.html) constructs. Compared to the AWS CDK we don't provide further abstractions (Level 2 / 3) at the moment. There are plenty of community driven [Terraform modules](https://registry.terraform.io/browse/modules) which you could use, though. 

Perhaps there will be a few community driven abstractions for parts of certain providers, but building fully featured abstractions for a provider is significant effort. When looking at the AWS CDK, they're almost 3 years into the project and still haven't covered 100% of the Cloudformation resources when it comes to Level 2 / 3 constructs.

There are vague plans to build a bridge between AWS CDK and Terraform CDK, which would enable the usage of the handcrafted abstractions from each other. However, that's nothing which I'd expect to be fully working anytime soon.

**Comment by skorfmann** [comment]
We do have various [examples](https://github.com/hashicorp/terraform-cdk/tree/main/examples) and will work on having more documentation in the future. There are no immediate plans for anything beyond that, but welcome contributions :)
