### ISSUE TITLE
Switch new project templates to pre-built providers

### ISSUE THREAD

**Issue by cmclaughlin** [hashicorp/terraform-cdk#391]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Pre-built providers are pretty awesome - much faster than running `cdktf get`.
Should we switch all the templates to use them? 
Seems like for new users getting started, faster experience is better. However, I could also see it's also good to introduce the concept of building modules that aren't available.

**Comment by jsteinich** [comment]
I agree and I think @skorfmann is on board as well (https://github.com/hashicorp/terraform-cdk/pull/360#discussion_r491155670)

**Comment by skorfmann** [comment]
> I agree and I think @skorfmann is on board as well ([#360 (comment)](https://github.com/hashicorp/terraform-cdk/pull/360#discussion_r491155670))

Yes, the templates should be reworked to be provider independent, and then promote the usage of the prebuilt providers.

**Comment by skorfmann** [comment]
The templates are independent from any providers for a while already and are promoting the use prebuilt providers. Furthermore, we have remote templates now #645 which enable the usage of custom templates.
