### ISSUE TITLE
Helm Support for Kubernetes CDK

### ISSUE THREAD

**Issue by dirien** [hashicorp/terraform-cdk#392]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Any plans for Helm support for the Kubernetes provider like the helm provider 

(https://registry.terraform.io/providers/hashicorp/helm/latest)

**Comment by skorfmann** [comment]
> Any plans for Helm support for the Kubernetes provider like the helm provider

This should just work - Is there something which isn't working with this provider?

**Comment by wuqunfei** [comment]
+1

**Comment by dirien** [comment]
@skorfmann i need to try it.

**Comment by wuqunfei** [comment]
Looking forward to testing it @skorfmann

**Comment by dirien** [comment]
@skorfmann: Works like a charm!

**Comment by mayasnayak** [comment]
@dirien Can you please share one example. Thanks.

**Comment by dirien** [comment]
@mayasnayak 


       new HelmProvider(this, 'do-helm', {
            kubernetes: [{
                configPath: "do_kube_config_cluster.yml"
            }]
        })

        new Release(this, "ingress", {
            name: "ingress-nginx",
            chart: "ingress-nginx",
            version: "2.15.0",
            repository: "https://kubernetes.github.io/ingress-nginx"
        })
