### ISSUE TITLE
Google provider 3 incompatible with Python

### ISSUE THREAD

**Issue by lightningboltemoji** [hashicorp/terraform-cdk#394]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.0.17
Python 3.8.5
google@~> 3 in cdktf.json 
* at the time of writing, resolves to `v3.41.0` with `cdktf get`

### Affected Resource(s)

Google provider? cdktf generating bindings? (not sure)

### Debug Output

https://gist.github.com/lightningboltemoji/f777938e43cab9dbfc61f913bf3f03de

### Expected Behavior

Latest version of Google provider can be imported in Python

### Actual Behavior

Import fails, because generated Python docstrings contain invalid escape sequences (`\N`)

```
$ echo "import imports.google" > main.py           
$ pipenv run python main.py
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    import imports.google
  File "/Users/x/hello-terraform/imports/google/__init__.py", line 14418
    """
    ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 3494-3495: malformed \N character escape
```

### Steps to Reproduce

Much of this is borrowed from the Getting started instructions here: https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/python.md

Output from running these is included above under 'Debug Output'

```
$ brew install cdktf
### ... installs python 3.8 + cdktf 0.0.17 on macOS
$ mkdir hello-terraform && cd hello-terraform
$ cdktf init --template="python" --local

### [optional] demonstrate the AWS provider is working
$ echo "import imports.aws" > main.py
$ pipenv run python main.py

### swap out the AWS provider for the Google provider
$ sed -i.bak 's/aws@~> 2.0/google@~> 3/' cdktf.json
$ CDKTF_LOG_LEVEL=debug cdktf get

### this where issues arise, Google provider will fail to import
$ echo "import imports.google" > main.py
$ pipenv run python main.py
```

**Comment by jsteinich** [comment]
I was able to reproduce this. As a workaround, you can edit `imports/google/__init__.py` and remove all occurrences of `"\N"`

**Comment by skorfmann** [comment]
> I was able to reproduce this. As a workaround, you can edit `imports/google/__init__.py` and remove all occurrences of `"\N"`

So that should be fixed in the code generator, right?

**Comment by jsteinich** [comment]
> So that should be fixed in the code generator, right?

It would be nice if jsii handled it, but it should be fixable in cdktf as well.
