### ISSUE TITLE
Test Run Times

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#405]
With the merged Java support (#360), the examples integration test runtime increased by ~ 30% from 14 to 18 minutes. I'm wondering if we can do something to make this faster (except for disabling the java tests)

![Screenshot 2020-10-05 at 21 57 45](https://user-images.githubusercontent.com/136789/95125907-eb866480-0755-11eb-88d6-b801e534deb6.png)

**Comment by jsteinich** [comment]
I think for examples integration we could switch to using pre-built providers.
For the regular integration tests, parallelizing them would probably make a big difference. Some of them could probably start without providers and then add in what makes sense for the test.

**Comment by skorfmann** [comment]
> test runtime increased by ~ 30% from 14 to 18 minutes.

This gets more pressing. We're now at ~ 35 minutes.
 
![Screenshot 2021-01-14 at 23 42 58](https://user-images.githubusercontent.com/136789/104658083-639fe700-56c2-11eb-85cc-aa71f8b77f48.png)

**Comment by skorfmann** [comment]
> I think for examples integration we could switch to using pre-built providers.

Yes, that could be an option. Examples might end up in a dedicated repository anyway.

> For the regular integration tests, parallelizing them would probably make a big difference. Some of them could probably start without providers and then add in what makes sense for the test.

Yes, the integration tests are running sequentially. One potential optimization could be to run them in parallel. However, the [runners](https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources) have 2 cores and 7 GB of memory, so there are tight limits on that.

One thing we can certainly do would be to merge a few of the integration tests, or even refactor one or two of them into a functional / unit test. Other than that, I've been wondering if there's an easy way to automatically split the integration tests and run each of them on its own, either in Github Actions or somewhere else. 

Personally, I'd want to see the total test run times at significantly less than 10 minutes.

**Comment by jsteinich** [comment]
Just some notes:

- We should add timing to each test so that we can narrow down what is taking the most time
- Many of the tests effectively generate providers twice. Can definitely cut it down to once
- I know I came across inefficiencies in jsii in some early testing. Could make contributions there to speed things up
- There certainly are a handful of tests that could be combined
- It is very important to have at least one integration test for each language that does provider generation
- There is a lot of value in validating additional providers generate correctly as well

**Comment by skorfmann** [comment]
We're at 25 minutes for a full CI run again. That's not bearable  from my point of view


```
[  569.000s ] ├───────────────────────────┤                                                    * build (0.15.4, typescript)-2914036934
[ 1533.161s ] ├──────────────────────────────────────────────────────────────────────────────┤ * checkrun-timechart-2914036932
[ 1502.000s ] ├───────────────────────────────────────────────────────────────────────────┤    * build (0.15.4, go)-2914036934
[  295.000s ] ├─────────────┤                                                                  * build (0.15.4)-2914036935
[  309.000s ] ├─────────────┤                                                                  * build (0.14.11)-2914036935
[  932.000s ] ├──────────────────────────────────────────────┤                                 * build (0.15.4, java)-2914036934
[  419.000s ] ├───────────────────┤                                                            * build (0.15.4, csharp)-2914036934
[    4.000s ] .                                                                                * main-2914036869
[  454.000s ] ├─────────────────────┤                                                          * build (0.15.4, python)-2914036934
[  124.000s ]                  ├────┤                                                          * linux_integration (0.14.11, go)-2914036935
[  450.000s ]                  ├─────────────────────┤                                         * linux_integration (0.14.11, java)-2914036935
[  446.000s ]                  ├─────────────────────┤                                         * linux_integration (0.14.11, csharp)-2914036935
[  891.000s ]                  ├────────────────────────────────────────────┤                  * linux_integration (0.14.11, python)-2914036935
[  462.000s ]                  ├─────────────────────┤                                         * linux_integration (0.15.4, csharp)-2914036935
[  141.000s ]                  ├─────┤                                                         * linux_integration (0.15.4, go)-2914036935
[  533.000s ]                  ├─────────────────────────┤                                     * linux_integration (0.14.11, typescript)-2914036935
[  916.000s ]                  ├─────────────────────────────────────────────┤                 * linux_integration (0.15.4, python)-2914036935
[  453.000s ]                  ├─────────────────────┤                                         * linux_integration (0.15.4, java)-2914036935
[  605.000s ]                  ├─────────────────────────────┤                                 * linux_integration (0.15.4, typescript)-2914036935
[  665.000s ]                  ├────────────────────────────────┤                              * windows_integration (0.14.11, java)-2914036935
[  704.000s ]                  ├──────────────────────────────────┤                            * windows_integration (0.14.11, csharp)-2914036935
[  913.000s ]                  ├─────────────────────────────────────────────┤                 * windows_integration (0.15.4, typescript)-2914036935
[ 1133.000s ]                  ├────────────────────────────────────────────────────────┤      * windows_integration (0.15.4, python)-2914036935
[  312.000s ]                  ├──────────────┤                                                * windows_integration (0.14.11, go)-2914036935
[ 1190.000s ]                  ├───────────────────────────────────────────────────────────┤   * windows_integration (0.14.11, python)-2914036935
[  673.000s ]                  ├────────────────────────────────┤                              * windows_integration (0.15.4, csharp)-2914036935
[  279.000s ]                  ├────────────┤                                                  * windows_integration (0.15.4, go)-2914036935
[ 1029.000s ]                  ├───────────────────────────────────────────────────┤           * windows_integration (0.14.11, typescript)-2914036935
[  726.000s ]                  ├───────────────────────────────────┤                           * windows_integration (0.15.4, java)-2914036935

     one '.' unit is less than:   19.320s
                    total time: 1545.619s
```

Besides from the Go build which takes ages, it looks like some of the integration examples increased their runtimes as well. Yesterday, the CI pipeline started to fail for non obvious reasons. With this commit (https://github.com/hashicorp/terraform-cdk/pull/761/commits/03f78a1a8041f6d3db4b6f0c9b41bab5abb7f41d) the pipeline started to work again (thanks for the hint @ansgarm).

Anyway, let's think about options how to make this faster. I think the goal should still be < 10 minutes. The faster the better :)

**Comment by ansgarm** [comment]
I just had a short look into the run times and I think there might be two things that we could address that could have a big impact:
1. Integration tests run in band and take a lot of time
Idea: Look into some kind of caching mechanism that could reuse the providers that are generated there (so that the same providers are not built twice or more times – e.g. the aws provider seems to appear in 3 typescript integration tests)
2. Examples take a lot of time to build (especially for Go)
Idea: Possibly generate provider bindings first and reuse them in all examples (this could e.g. help with multiple examples that make use of the AWS provider). However this probably does not help that much with Go unfortunately (there is only one AWS provider example and one for Google – both taking quite some time and memory, which blocks us from running them in parallel).

Another option could be to pull all provider "get-ting" into a separate step which runs once before all builds.

I don't know how feasible this is (if at all). But I think that's where could improve (besides improving the JSII performance upstream).

**Comment by skorfmann** [comment]
One other idea: Perhaps this could be solved by throwing more compute power at the problem. I vaguely remember that there's a significant difference in test run times between the Github Action runner and my local machine. However, I wouldn't really want to move away from Github Actions to achieve this.

**Comment by ansgarm** [comment]
> … I wouldn't really want to move away from Github Actions to achieve this.
There is the option for [self-hosted runners for Github Actions](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

**Comment by skorfmann** [comment]
> > … I wouldn't really want to move away from Github Actions to achieve this.
> 
> There is the option for [self-hosted runners for Github Actions](https://docs.github.com/en/actions/hosting-your-own-runners/about-self-hosted-runners).

This wouldn't be something I'd wanna manage, so it would have to happen on org level. Not sure if that's something we can expect to happen anytime soon.

Another thing I just thought about - How about a generated [actions matrix](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix)?

> Job matrix - A job matrix can generate a maximum of 256 jobs per workflow run. This limit also applies to self-hosted runners.

So, effectively generate one job per example / integration test / terraform version. There seems to be an [account limit](https://docs.github.com/en/actions/reference/usage-limits-billing-and-administration#usage-limits) of parallel jobs, but not sure if this applies to private projects only.

**Comment by jsteinich** [comment]
I think there are likely to be large gains to be has within jsii. Improving that would also help end users when generating providers/modules.

**Comment by skorfmann** [comment]
Highly parallelized the builds (essentially one job per example / integration test). The windows based tests are still a bit slow, but on average a full pipeline succeeds at around 15 minutes. I'd want to make sure, that the test run times are not growing again. So, I'm considering these 15 minutes as the absolute maximum which we should tolerate.

As @jsteinich said, there are likely improvements possible in jsii itself. But for now, I'm closing this issue here.
