### ISSUE TITLE
ETIMEDOUT errors during synth for cdktf >= 0.0.16 behind proxy

### ISSUE THREAD

**Issue by mstair** [hashicorp/terraform-cdk#407]
Error: connect ETIMEDOUT errors from .../yoga-layout/build/Release/nbind.js in cdktf-cli >= 0.0.16 from behind corporate proxy.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

versions: 0.0.16, 0.0.17
0.0.15 is last known good

language bindings: Python

### Affected Resource(s)

All

### Debug Output

https://gist.github.com/mstair/4bc9ee07f15266c87e1c76b561da5285

### Expected Behavior

`cdktf synth` completes

### Actual Behavior

`cdktf synth` fails

### Steps to Reproduce

`cdktf synth`

### Important Factoids

Executing behind a corporate proxy which is likely blocking direct IP address access.

IP address in error (204.236.226.251) resolves to AWS EC2

### References

* #0000

**Comment by jsteinich** [comment]
Maybe take a look at #351. I'm thinking this is the same issue.

**Comment by mstair** [comment]
Thanks @jsteinich that worked, sorry for the duplicate.
