### ISSUE TITLE
App.synth output - returning as JSON/String in code

### ISSUE THREAD

**Issue by lukepopp** [hashicorp/terraform-cdk#408]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi

I'm trying to trap the output of App.synth() in Java.  Unfortunately the synth method returns void so I can't get this easily in code.  I can use the Builder to specify an output directory and read the output from that but was looking for a better way .  The AWS CDK has options to get the JSON Tree in code.  Thanks.

**Comment by jsteinich** [comment]
I'm curious how you plan on using the synthesized output. Are you looking for something like #237 ?

**Comment by lukepopp** [comment]
I'm looking to be able to do things like Unit testing and potentially doc generation automation.

**Comment by martimconstantino** [comment]
I'm also looking for a good way of unit testing the CDK in Java.
So far, the best I managed to do is:
`
App app = new App();
Stack stack = new Stack(app, 'test-stack');
// Add other CDK constructs

CloudAssembly assembly = app.synth();
String treePath = assembly.getDirectory() + "/" + assembly.tree().getFile();
JsonNode tree = objectMapper.readTree(new File(treePath));
`

Now, I have a tree.json file to check. But it doesn't seem to be the right way, though

**Comment by jsteinich** [comment]
It does look like AWS CDK has a couple pieces that don't exist in cdktf. Seems reasonable to explore similar patterns.
See https://docs.aws.amazon.com/cdk/latest/guide/testing.html

**Comment by skorfmann** [comment]
There are some basic testing capabilities - see here for an example: https://github.com/hashicorp/terraform-cdk/blob/fc3363e575f14d43aacd5512b608105e4216536c/packages/cdktf/test/provider.test.ts 

@lukepopp what are you looking for beyond that? Some helpers around matching particular parts of resources / attributes?

**Comment by DanielMSchmidt** [comment]
We added unit testing capabilities, the other parts overlap with #237 and #682, closing this in favor of the tickets referencing it
