### ISSUE TITLE
aws eks NodeCreationFailure: Instances failed to join the kubernetes cluster.

### ISSUE THREAD

**Issue by bitgandtter** [hashicorp/terraform-cdk#409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

cdktf~> 0.0.17-pre.cbf526c954ba97438241933a69ff04b0031ea3d3
aws@~> 2.0
google@~> 3.0
azurerm@~> 2.0

### Debug Output

https://gist.github.com/bitgandtter/fb1aed5a4a8728b9c2c0b36b99e6c5e4

### Expected Behavior

Successfully created an EKS Cluster

### Actual Behavior

EKS Cluster and Nodes created but nodes didn't join the cluster

### Steps to Reproduce

https://gist.github.com/bitgandtter/fb1aed5a4a8728b9c2c0b36b99e6c5e4

### Important Factoids

no

**Comment by jsteinich** [comment]
I believe there are just a few missing pieces. Potentially an internet gateway, security groups, or iam roles.
https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest may be a good resource to either import directly or reference for needed resources.

**Comment by schollii** [comment]
1. looks like the gists are no longer available, which kind of makes this ticket useless

2. some might be interested in https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1111

**Comment by deval-graymatics** [comment]
I was facing the similar issue. I tried even basic example from EKS module and that was also giving Node joining issue. 
I would suggest to verify the terraform version and follow this [blog](https://learnk8s.io/terraform-eks). This code is working well when I downgraded terraform version to exactly same.

**Comment by DanielMSchmidt** [comment]
The gist seems to be unavailable, could you post a new one so I can check the issue?

**Comment by DanielMSchmidt** [comment]
No reaction for almost two months, closing this out for now 👍
