### ISSUE TITLE
Support for Provisioners

### ISSUE THREAD

**Issue by lukepopp** [hashicorp/terraform-cdk#411]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, does TF CDK support [Provisioners](https://www.terraform.io/docs/provisioners/index.html)?  I couldn't find anything in the libs.  Whilst I realise there's better ways to do this with cloud-init or packer,  Provisioner support would help with backwards compatibility and prototyping.

**Comment by jsteinich** [comment]
They aren't directly supported, but it is possible to use them via [escape hatches](https://github.com/hashicorp/terraform-cdk/blob/8757404fa25b6e405f1a51eac11b96943ccb372e/docs/working-with-cdk-for-terraform/escape-hatch.md#resource-escape-hatch).

**Comment by ansgarm** [comment]
When we add support for provisioners we should also add support for dynamic block iteration to them. I'm currently implementing this for #1798 and provisioners can also be dynamically created ([docs](https://www.terraform.io/language/expressions/dynamic-blocks#dynamic-blocks)).
