### ISSUE TITLE
CamelCase keys/properties get changed into Snake case when creating AWS CloudwatchMetricAlarm resources

### ISSUE THREAD

**Issue by gvasquez95** [hashicorp/terraform-cdk#412]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
cdktf --version
0.0.17-pre.06e13a2348f6cefd0b65c65fc99c081e108e6878

npx tsc -v
Version 4.0.3
```
### Affected Resource(s)

CloudwatchMetricAlarm

### Expected Behavior

Alarm Dimensions are case sensitive and Dimensions names (keys) are getting changed from Camel case into Snake case.

In the code example below Metric's dimensions are `ClusterName` and `ServiceName`.

### Actual Behavior

Both `ClusterName` and `ServiceName` get changed into `cluster_name` and `service_name`, as in the following state snippet:

```
"dimensions": {
              "cluster_name": "utilities",
              "service_name": "gateway-api"
            }
```

This creates alarms with wrong dimensions references, thus yields the alarms not useful.

### Steps to Reproduce

Consider the following code:

```
import { Construct } from 'constructs'
import { App, TerraformStack } from 'cdktf'
import { AwsProvider, CloudwatchMetricAlarm, CloudwatchMetricAlarmConfig } from './.gen/providers/aws'

class MyStack extends TerraformStack {
  constructor (scope: Construct, name: string) {
    super(scope, name)
    new AwsProvider(this, 'aws', {
      region: 'us-east-1'
    })
    const services : {ClusterName: string, ServiceName: string }[] = [{ ClusterName: 'utilities', ServiceName: 'gateway-api' }, { ClusterName: 'utilities', ServiceName: 'geotimezones' }]
    const metrics = ['CPUUtilization', 'MemoryUtilization']
    for (const service of services) {
      for (const metric of metrics) {
        const name = `${metric}-${service.ClusterName}-${service.ServiceName}`
        const config : CloudwatchMetricAlarmConfig = { dimensions: { ClusterName: service.ClusterName, ServiceName: service.ServiceName }, threshold: 90, namespace: 'ECS', period: 300, metricName: metric, statistic: 'Average', alarmName: name, comparisonOperator: 'GreaterThanThreshold', evaluationPeriods: 1 }
        new CloudwatchMetricAlarm(this, name, config)
      }
    }
  }
}

const app = new App()
new MyStack(app, 'cw-ecs-alarms')
app.synth()

```

**Comment by jsteinich** [comment]
This should be fixed with #395. We can hopefully get that merged soon.

**Comment by cmclaughlin** [comment]
I think this can be closed now.

**Comment by jsteinich** [comment]
#395 has been merged for quite awhile.
