### ISSUE TITLE
no template 'java' available

### ISSUE THREAD

**Issue by waffel** [hashicorp/terraform-cdk#413]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.0.17

### Affected Resource(s)

Java

### Expected Behavior

When running `cdktf init --template="java" --local` is should initialize the java project for me.

### Actual Behavior

Following output / error:

`
cdktf init --template="java" --local
cdktf init [OPTIONS]
Create a new cdktf project from a template.

Options:
  --version                   Show version number                                                                                                                   [boolean]
  --disable-logging           Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.                                                  [boolean] [default: true]
  --disable-plugin-cache-env  Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured differently. Supported using the env
                              CDKTF_DISABLE_PLUGIN_CACHE_ENV.                                                                                      [boolean] [default: false]
  --log-level                 Which log level should be written. Only supported via setting the env CDKTF_LOG_LEVEL                                                  [string]
  --template                  The template name to be used to create a new project.            [string] [choices: "python", "python-pip", "typescript", "typescript-minimal"]
  --project-name              The name of the project.                                                                                                               [string]
  --project-description       The description of the project.                                                                                                        [string]
  --dist                      Install dependencies from a "dist" directory (for development)                                                                         [string]
  --local                     Use local state storage for generated Terraform.                                                                     [boolean] [default: false]
  --cdktf-version             The cdktf version to use while creating a new project.                                                             [string] [default: "0.0.17"]
  -h, --help                  Show help                                                                                                                             [boolean]

Invalid values:
  Argument: template, Given: "java", Choices: "python", "python-pip", "typescript", "typescript-minimal"
`

### Steps to Reproduce

Install the latest version as described on the documentation and try to follow the instructions given for java.

* #0000

**Comment by jsteinich** [comment]
Similar to python (see #293), Java isn't yet supported for pre-release versions. I'm not sure the timeline for having release version with Java, but hopefully soon.

**Comment by waffel** [comment]
Ah ... good to now. Maybe an update on the docs would be nice. I thought (from documentation reading and the examples) it must work :-)

So I will wait for the release with Java. I really would like to try it out.

Thanks for the fast response!

**Comment by mvillafuertem** [comment]
Very cool! Looking forward to trying it
