### ISSUE TITLE
AWS EBS Volume Tag Keys automatically set to lower case incorrectly

### ISSUE THREAD

**Issue by choweiyuan** [hashicorp/terraform-cdk#414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.0.17
### Affected Resource(s)

AWS EBS Volume Tags

### Expected Behavior

AWS Volume tag keys should not be lower case by terraform synth, it should obey whatever I've defined in the map as its case sensitive

```
    const volumeTags: { [key: string]: string } = {};
    volumeTags["Application"] = "${var.application}" 

    const instance = new Instance(this, `${name}-instance`, {
      volumeTags
    })
```

Desired output:
```
    "aws_instance": {
      "terraforminstance_39B0EEB0": {
        "volume_tags": {
          "Application": "${var.application}"
        },
    }
```
### Actual Behavior

Tag Key "Application" became "application", was lower case
```
    "aws_instance": {
      "terraforminstance_39B0EEB0": {
        "volume_tags": {
          "application": "${var.application}"
        },
    }
```
### Important Factoids
My current workaround is to use escape hatch:

`  instance.addOverride("volume_tags",  volumeTags)
`
### References

Seems related:
https://github.com/hashicorp/terraform-cdk/issues/235

**Comment by skorfmann** [comment]
Since #235 got merged, could you verify this works now with the latest pre release @choweiyuan ? Thanks!

**Comment by choweiyuan** [comment]
Hi sorry for the delay, yes I can confirm this works now
