### ISSUE TITLE
openXJsonSerDe property should output open_x_json_ser_de for KinesisFirehoseDeliveryStream

### ISSUE THREAD

**Issue by thepont** [hashicorp/terraform-cdk#415]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request

### cdktf & Language Versions

Typescript, cdktf version 0.0.17

### Affected Resource(s)

 * KinesisFirehoseDeliveryStream

### Debug Output

https://gist.github.com/thepont/3d1e6c7c12ee8703a8f8e72b10546af6

### Expected Behavior

Should have outputted `open_x_json_ser_de` into the terraform json as pe r[kinesis_firehose_delivery_stream](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#open_x_json_ser_de)

### Actual Behavior

```
Error: Extraneous JSON object property

  on cdk.tf.json line 820, in resource.aws_kinesis_firehose_delivery_stream.possumreports_datadeliverystream_0002D58D.extended_s3_configuration[0].data_format_conversion_configuration[0].input_format_configuration[0].deserializer[0]:
 820:                         "open_xjson_ser_de": [

No argument or block type is named "open_xjson_ser_de". Did you mean
"open_x_json_ser_de"?
```
### Steps to Reproduce

Create a  `KinesisFirehoseDeliveryStream` using the `openXJsonSerDe` deserializer 

```
new KinesisFirehoseDeliveryStream(this, 'data-delivery-stream', {
      name: 'data-delivery-stream',
      destination: 'extended_s3',
      extendedS3Configuration: [{
        bucketArn: bkt.arn,
        prefix: "TEST_PREFIX",
        roleArn: kinesisRole.arn,
        bufferSize: 128,
        dataFormatConversionConfiguration: [{
          inputFormatConfiguration:[{
            deserializer: [{
              openXJsonSerDe: [{}]
            }]
          }],
          outputFormatConfiguration: [{
            serializer: [{
              parquetSerDe: [{}]
            }]
          }]
        }]
      }]
    });
```

### Important Factoids

None

**Comment by jsteinich** [comment]
Related to #235

**Comment by skorfmann** [comment]
Since #235 got merge, could you verify this works with the latest pre release @thepont?

**Comment by thepont** [comment]
@skorfmann unless I am missing something that seems to have made matters worse, It doesn't seem to be converting any of the extendedS3Configuration to snake case any more.

This is a different bug to https://github.com/hashicorp/terraform-cdk/issues/235, although I have seen #235 on environment vars passed to lambda functions ( and this appears to be fixed by this change).

my issue is simply that when we change to snake case `openXJsonSerDe` should be converted to `open_x_json_ser_de` not `open_xjson_ser_de`. The code that is responsible for converting to snake case doesn't seem to like a single char then the separator. 

To be fair I don't know what other resource has this pattern.

**Comment by jsteinich** [comment]
@thepont are you using the pre-built provider or generating one (in cdktf.json terraformProviders)? If the pre-built provider is out of date, it would probably cause nothing to be snake cased.

The generated typescript does have the correct casing. I'll try running an example when I can to see if some runtime check is failing.

**Comment by jsteinich** [comment]
When using generated providers with both cdktf and cdtf-cli at version `0.0.18-pre.134` I'm seeing the correct output.

**Comment by thepont** [comment]
Ok, sorry, I am probably using the incorrect provider.
```
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "aws@~> 2.0"
  ]
}
```

**Comment by jsteinich** [comment]
> Just for clarification, the upgrade path is to upgrade the packages then run a `cdktf get`

Yep.

Your configuration looks fine.

**Comment by thepont** [comment]
@jsimone @skorfmann, thanks heaps for your help, confirmed working on my end.

**Comment by skorfmann** [comment]
Cool, thanks for confirming @thepont
