### ISSUE TITLE
S3Bucket creates random generated names

### ISSUE THREAD

**Issue by jritsema** [hashicorp/terraform-cdk#416]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
cdktf --version
0.0.17
```
```
python --version
Python 3.8.6
```

### Affected Resource(s)

```python
S3Bucket(self, id="tf-state-my-app")
```

### Expected Behavior

create a bucket with the name `tf-state-my-app`

### Actual Behavior

got a bucket with the name `terraform-20201030204203141300000001`

### References

* #0000

**Comment by cmclaughlin** [comment]
id is used as identifiuer/key in the JSON output - try adding a bucket argument. Such as:


    S3Bucket(self, id="tf-state-my-app", bucket="bucket-name")

**Comment by jritsema** [comment]
Ah, ok, thank you!  I'm brand new to this project.  That worked, however, it seems odd that the `id` appears to have no bearing on the output, however, if I remove it I get 
```
TypeError: __init__() missing 1 required positional argument: 'id'
```

**Comment by cmclaughlin** [comment]
That confused me at first too... the ID is used in the generated output - see cdktf.out/cdk.tf.json.
