### ISSUE TITLE
aws lambda environment variables is force lowercase

### ISSUE THREAD

**Issue by YouDonggeun** [hashicorp/terraform-cdk#419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

typescript@4.0.5
cdktf@0.0.17

### Affected Resource(s)

LambdaFunction

### Expected Behavior

```json
"environment": [
    {
        "variables": {
            "foo": "bar"
        }
    }
],
```
### Actual Behavior
```json
"environment": [
    {
        "variables": {
            "FOO": "bar"
        }
    }
],
```

**Comment by jsteinich** [comment]
Related to #235

**Comment by YouDonggeun** [comment]
#235 FIXED
