### ISSUE TITLE
Stack Trace when running basic build

### ISSUE THREAD

**Issue by philhorrocks** [hashicorp/terraform-cdk#420]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Language: Typescript
version: 0.0.17

### Debug Output

 "//": {
          "metadata": {
            "path": "hello-terraform/Hello",
            "uniqueId": "helloterraform_Hello_19940A68",
            "stackTrace": [
              "new TerraformElement (/home/user01/projects/cdktf/test/node_modules/cdktf/lib/terraform-element.js:11:28)",
              "new TerraformResource (/home/user01/projects/cdktf/test/node_modules/cdktf/lib/terraform-resource.js:9:9)",
              "new Instance (/home/user01/projects/cdktf/test/.gen/providers/aws/instance.js:13:9)",
              "new MyStack (/home/user01/projects/cdktf/test/main.js:11:9)",
              "Object.<anonymous> (/home/user01/projects/cdktf/test/main.js:18:1)",
              "Module._compile (internal/modules/cjs/loader.js:1138:30)",
              "Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)",
              "Module.load (internal/modules/cjs/loader.js:986:32)",
              "Function.Module._load (internal/modules/cjs/loader.js:879:14)",
              "Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)",
              "internal/main/run_main_module.js:17:47"
            ]
          }

### Expected Behavior

Im running this example from your instructions 

import { Construct } from "constructs";
import { App, TerraformStack } from "cdktf";
import { AwsProvider, Instance } from "./.gen/providers/aws";

class MyStack extends TerraformStack {
  constructor(scope: Construct, id: string) {
    super(scope, id);

    new AwsProvider(this, "aws", {
      region: "us-east-1",
    });

    new Instance(this, "Hello", {
      ami: "ami-2757f631",
      instanceType: "t2.micro",
    });
  }
}

const app = new App();
new MyStack(app, "hello-terraform");
app.synth();

### References

* #0000

**Comment by jsteinich** [comment]
@philhorrocks could you please elaborate on the problem you are experiencing? Does running `cdktf synth` produce an error?

**Comment by choweiyuan** [comment]
I can't speak for @philhorrocks  but I have a similar query.

After running cdktf synth, each of my resources have a huge block of stackTrace under metadata. Is that by design? it makes my cdktf.tf.json unnecessarily huge for that reason, I personally would rather not have the stackTrace block at all. 

AWS CDK only outputs the metadata/path, not metadata/stackTrace

**Comment by choweiyuan** [comment]
Never mind, I found this issue shortly after I hit enter https://github.com/hashicorp/terraform-cdk/issues/251

**Comment by DanielMSchmidt** [comment]
Closed since `new App({stackTraces: false})` can be used to disable the stack trace metadata
