### ISSUE TITLE
Retrieve Resolved Properties During Synthesis

### ISSUE THREAD

**Issue by kstewart83** [hashicorp/terraform-cdk#423]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm trying to figure out how to get resolved properties during synthesis so I can further process them in Typescript. I cannot find anything in the documentation, prior issues, or on the web.

For example, I have an existing VPC where I can create a data source:

```typescript
const vpc = new DataAwsVpc(this, "data-awsvpc", {
  tags: {
    // ... filter criteria here
  }
});
```

This part works, and I can use the VPC ID and other properties elsewhere. I'm particularly interested in the CIDR block so I can statically assign IP addresses within the range to instances I am creating in this VPC. All the examples I can find use an output:

```typescript
const cidrOutput = new TerraformOutput(this, 'vpc-cidrblock', {
  description: "CIDR block for VPC",
  value: vpc.cidrBlock
})
```

This will print out the CIDR block to the console when using the CLI. The problem is that I want to use the CIDR block during synthesis programmatically, and not just handing the ID around. I want to be able to generate IP ranges from this CIDR. So instead of an opaque handle, I really I want this CIDR block information as a string like `10.X.X.X/24` so I can process it in Typescript and use as an input to a future construct. In other words, I want the CLI output of a `TerraformOutput` during synthesis time. I've tried every rendition of creating strings with no success: 

```typescript
console.log(Token.asString(vpc.cidrBlock));
console.log(Token.asString(cidrOutput.value));
console.log(vpc.cidrBlock);
console.log(cidrOutput);
console.log(cidrOutput.toString());
console.log(cidrOutput.toTerraform());
```

### References

https://github.com/hashicorp/terraform-cdk/tree/master/docs/working-with-cdk-for-terraform

**Comment by jsteinich** [comment]
Having the ability to actually access the value at synth time would be a major shift in how cdktf functions since it simply renders Terraform compliant JSON and then runs the Terraform binary.

It is possible to use Terraform functions, though they aren't natively supported at this time so it will be a bit clunky.
You might also consider giving up the lookup and just providing as configuration input to allow for full Typescript processing.

**Comment by kstewart83** [comment]
That's what I've done for the time being, using environment variables that are hard coded to the appropriate values.

**Comment by skorfmann** [comment]
@kstewart83 When you want to use the data at build time (synth), you could use the Nodejs SDK to fetch these values. The issue which will likely come up is, that the synth process itself is synchronous. There are two ways to workaround this:

1. Fetch the data and pass it as props into your stack
2. Build a [custom data source](https://gist.github.com/skorfmann/e399bbd85be6e5a8a5a021adcb570dd4) to do the calculations you want to do, and pass the VPC data source as arguments.

**Comment by kstewart83** [comment]
I think that's a pretty reasonable next step that avoids the hard coding in environment variables. As you all are pondering future design decisions like what is outlined in #435, I'm curious if there is a way to leverage what cdktf already has built in to avoid shifting paradigms if data constructs in cdktf already fit the bill. One thought that comes to mind is if each stack synth is synchronous, is there a clever way when implementing multiple stacks (I haven't checked on the progress on that item for awhile), where the outputs of one stack deploy can be passed into another stack? I don't know enough about Terraform under the hood or other CDK internals to know if that is feasible.

**Comment by skorfmann** [comment]
Doing this at synth time might lead to unexpected results. However, I've extracted an issue to create [custom data sources](https://github.com/hashicorp/terraform-cdk/issues/660] which achieves the desired outcome of the original issue in a slightly different way.
