### ISSUE TITLE
aws_acm_certificate.*.domain_validation_options throws Invalid index

### ISSUE THREAD

**Issue by YouDonggeun** [hashicorp/terraform-cdk#424]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
> ctktf : 0.0.17-pre.131/typescript
> ts: 4.0.5
> aws-providers: 3.14.1

### Expected Behavior
```bash
Error: Invalid index

  on cdk.tf.json line 7420, in resource.aws_route53_record.cdktf_notificationcertvalidationrecord_16141CAD:
7420:         "name": "${aws_acm_certificate.cdktf_notificationappcertificate_680C64C0.domain_validation_options.0.resource_record_name}",

This value does not have any indices.
```
### Actual Behavior

```json
"${tolist(aws_acm_certificate.cdktf_notificationappcertificate_680C64C0.domain_validation_options).0.resource_record_name}"
        
```
when added "tolist" into cdk.tf.json it works completed 

### References

ref: https://github.com/hashicorp/terraform/issues/26043

### bug fix Implement
> ComplexComputedToList
```typescript
import { ITerraformResource, Token } from "cdktf";

export class ComplexComputedToList {
    terraformResource: ITerraformResource;
    terraformAttribute: string;
    index: string;
    /**
     * @experimental
     */
    constructor(
        terraformResource: ITerraformResource,
        terraformAttribute: string,
        index: string
    ) {
        this.terraformResource = terraformResource;
        this.terraformAttribute = terraformAttribute;
        this.index = index;
    }
    /**
     * @experimental
     */
    getStringAttribute(terraformAttribute: string) {
        return Token.asString(
            this.interpolationForAttribute(terraformAttribute)
        );
    }
    /**
     * @experimental
     */
    getNumberAttribute(terraformAttribute: string) {
        return Token.asNumber(
            this.interpolationForAttribute(terraformAttribute)
        );
    }
    /**
     * @experimental
     */
    getListAttribute(terraformAttribute: string) {
        return Token.asList(this.interpolationForAttribute(terraformAttribute));
    }
    /**
     * @experimental
     */
    getBooleanAttribute(terraformAttribute: string) {
        return Token.asString(
            this.interpolationForAttribute(terraformAttribute)
        );
    }
    /**
     * @experimental
     */
    interpolationForAttribute(property: string) {
        const {
            terraformResourceType,
            friendlyUniqueId,
        } = this.terraformResource;
        return `\${tolist(${terraformResourceType}.${friendlyUniqueId}.${this.terraformAttribute})[${this.index}].${property}}`;
    }
}

```
> someConvertTest.ts
```typescript
class CustomAcmCertificateDomainValidationOptions extends ComplexComputedToList {
    // domain_name - computed: true, optional: false, required: true
    public get domainName() {
        return this.getStringAttribute("domain_name");
    }

    // resource_record_name - computed: true, optional: false, required: true
    public get resourceRecordName() {
        return this.getStringAttribute("resource_record_name");
    }

    // resource_record_type - computed: true, optional: false, required: true
    public get resourceRecordType() {
        return this.getStringAttribute("resource_record_type");
    }

    // resource_record_value - computed: true, optional: false, required: true
    public get resourceRecordValue() {
        return this.getStringAttribute("resource_record_value");
    }
}
const convertDomainValidationOptions = (cert: AcmCertificate, index: string) =>
    new CustomAcmCertificateDomainValidationOptions(
        cert,
        "domain_validation_options",
        index
    );
```

**Comment by jsteinich** [comment]
This may require a bit of discussion. Currently lists and sets are treated the same in cdktf; however, they aren't the same in Terraform. The workaround proposed here would allow accessing by index; however, I believe converting a set to a list doesn't guarantee ordering which could result in differences between plans. Actually generating a set type is possible, but a lack of generic support would make it a fairly large task.

**Comment by skorfmann** [comment]
@jsteinich do you have something in mind how to tackle this?

**Comment by jsteinich** [comment]
> @jsteinich do you have something in mind how to tackle this?

Ideally jsii would support `Set<T>` just like they support `Array<T>`. I'd be willing to work on that; however, I think we have bigger issues to figure out with referencing computed collections. https://github.com/aws/jsii/issues/1841 would go a long way, but even that may not be enough. I also came across https://github.com/aws/jsii/issues/1302. I'll try to write up some more thoughts when I have a bit more time.

**Comment by DanielMSchmidt** [comment]
#992 tracks this issue, Closing this one so we only have one issue that tracks the effort
