### ISSUE TITLE
Create flag for simple output type to prevent mass logging in automation systems

### ISSUE THREAD

**Issue by bikescholl** [hashicorp/terraform-cdk#426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

During runs in automation systems because of the changing character in bash the logs can get quite unwieldy. My workaround has been simply to output to `/dev/null` as an intermediary but is a bit hacky.

I'm proposing a flag that can be used across all commands to disable this feature and create a simple static output.

```
⠋ starting ...
�[2K�[1A�[2K�[G⠋ synthesizing ...
�[2K�[1A�[2K�[G⠙ synthesizing ...
�[2K�[1A�[2K�[G⠹ synthesizing ...
�[2K�[1A�[2K�[G⠸ synthesizing ...
�[2K�[1A�[2K�[G⠼ synthesizing ...
�[2K�[1A�[2K�[G⠴ synthesizing ...
�[2K�[1A�[2K�[G⠦ synthesizing ...
�[2K�[1A�[2K�[G⠧ synthesizing ...
�[2K�[1A�[2K�[G⠇ synthesizing ...
�[2K�[1A�[2K�[G⠏ synthesizing ...
�[2K�[1A�[2K�[G⠋ synthesizing ...
�[2K�[1A�[2K�[G⠙ synthesizing ...
�[2K�[1A�[2K�[G⠹ synthesizing ...
�[2K�[1A�[2K�[G⠸ synthesizing ...
�[2K�[1A�[2K�[G⠼ synthesizing ...
�[2K�[1A�[2K�[G⠴ synthesizing ...
�[2K�[1A�[2K�[G⠦ synthesizing ...
�[2K�[1A�[2K�[G⠧ synthesizing ...
�[2K�[1A�[2K�[G⠇ synthesizing ...
�[2K�[1A�[2K�[G⠏ synthesizing ...
�[2K�[1A�[2K�[G⠋ synthesizing ...
�[2K�[1A�[2K�[G⠙ synthesizing ...
�[2K�[1A�[2K�[GGenerated Terraform code in the output directory: cdktf.out
```
 VS.

```
synthesizing...
Generated Terraform code in the output directory: cdktf.out
```

**Comment by jsteinich** [comment]
@bikescholl try setting the `CI` environment variable.

**Comment by bikescholl** [comment]
@jsteinich that seems to work! Thank you! Are there docs available for the supported environment variables at this time? Maybe this can be changed to get documentation created around those.

**Comment by jsteinich** [comment]
> Are there docs available for the supported environment variables at this time? Maybe this can be changed to get documentation created around those.

I thought there was something, but a quick search didn't turn up anything, so adding documentation sounds like a good idea.
