### ISSUE TITLE
providers/helm/release.ts failing cdktf get with missing README.md in Python

### ISSUE THREAD

**Issue by bikescholl** [hashicorp/terraform-cdk#427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf-cli@0.0.18
cdktf@0.0.18
python@3.8.5

### Affected Resource(s)

- providers/helm/release.ts

### Debug Output

https://gist.github.com/bikescholl/e53f5baae2bebe946897e7e724bbc4de

### Expected Behavior

When running cdktf get the providers should download as expected

### Actual Behavior

The providers fail to download correctly.

### Steps to Reproduce

- Install latest cdktf @ 0.0.18
- Specify the helm provider in your cdktf.json
- Run cdktf get

### Important Factoids

This appears to work with cdktf @ 0.0.17

**Comment by jsteinich** [comment]
Looks like it is hitting a naming conflict since it has both `values` and `reset_values`. We'll try to get a fix soon.
