### ISSUE TITLE
Provider Metadata for Resources

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#43]
We can't tell at runtime from which provider version the resources were generated. I think it would be good for compatibility checking and version locking to have this knowledge in the generated resource classes. Something like this perhaps:

```typescript
export class TestResource extends TerraformResource {
  constructor(scope: Construct, id: string, config: TestResourceConfig) {
    super(scope, id, {
      terraformResourceType: 'test_resource',
      terraformGeneratorMetadata: {
        providerName: 'aws',
        providerVersion: '2.59.0'
      }
    });
  }
}
```

The `providerName` is straightforward. The `providerVersion` is not easily available at the moment. The only idea I have right now: Parse the provider file names in `.terraform`. There are likely better approaches - anyone?

**Comment by anubhavmishra** [comment]
This might be needed for metrics for the project.

**Comment by skorfmann** [comment]
With Terraform `>= 0.13` there's a `.terraform/plugins/selections.json` file after doing the `init`:

```
{
  "registry.terraform.io/hashicorp/aws": {
    "hash": "h1:b1qNzEzDHZpnHSOW4fRo1PFC0U2Ft25PKKs9NSDGe3U=",
    "version": "3.26.0"
  }
}
```

We could use this information and pass it through to the code generator, as long as this file is present.
