### ISSUE TITLE
Iterating computed values

### ISSUE THREAD

**Issue by hampus77** [hashicorp/terraform-cdk#430]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli@0.0.18
cdktf@0.0.18
typescript@4.0.5

### Description
I´m trying to figure out how to do work with computed values and loops with the kbst/kustomize provider where they provide an ids list which contain computed values which in turn will be used to get the kustomized manifests.

data "kustomization" "test" {
  provider = kustomization
  path = "test_kustomizations/basic/initial"
}

resource "kustomization_resource" "test" {
  provider = kustomization
  for_each = data.kustomization.test.ids
  manifest = data.kustomization.test.manifests[each.value]
}

How would I go about and do this in the cdk?

Regards,
Hampus

**Comment by skorfmann** [comment]
There's no abstraction over loops yet. However, you can achieve this by using [escape hatches](https://cdk.tf/escape-hatch) for now

**Comment by skorfmann** [comment]
In the context of a cert validation in AWS (see [Terraform docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acm_certificate_validation)) here's a working example for using `for_each`:

Given this HCL 

```hcl
resource "aws_route53_record" "example" {
  for_each = {
    for dvo in aws_acm_certificate.example.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }

  allow_overwrite = true
  name            = each.value.name
  records         = [each.value.record]
  ttl             = 60
  type            = each.value.type
  zone_id         = aws_route53_zone.example.zone_id
}

resource "aws_acm_certificate_validation" "example" {
  certificate_arn         = aws_acm_certificate.example.arn
  validation_record_fqdns = [for record in aws_route53_record.example : record.fqdn]
}
```

We can use escape hatches to make JSON understand the `for_each` concept:

```typescript
const record = new aws.Route53Record(this, 'validation-record', {
  name: "${each.value.name}",
  type: "${each.value.type}",
  records: [
    "${each.value.record}"
  ],
  zoneId: zone.zoneId,
  ttl: 60,
  allowOverwrite:  true
})

record.addOverride('for_each', `\${{
    for dvo in ${cert.fqn}.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
}`)

const certValidation = new aws.AcmCertificateValidation(this, 'certvalidation', {
  certificateArn: cert.arn
})
certValidation.addOverride('validation_record_fqdns', `\${[for record in ${record.fqn} : record.fqdn]}`)
```

While that works, it's really not intuitive and should be abstracted somehow. Don't know a good way to model it right now, that's something to think about.

**Comment by DanielMSchmidt** [comment]
Closing this, we are tracking the work in #994

**Comment by mbazalik** [comment]
In the #994 I am not able to find an example of how to further use the result from iterated resources (In this example how to use multiple `Route53Record`s to generate `AcmCertificateValidation`

```typescript
const validationRecords = new Route53Record(scope, "certificate_validation", {
      forEach: certValidationOptionsIterator,
      allowOverwrite: true,
      records: [certValidationOptionsIterator.getString("resourceRecordValue")],
      ttl: 60,
      type: certValidationOptionsIterator.getString("resourceRecordType"),
      zoneId: local.zoneId,
      name: certValidationOptionsIterator.getString("resourceRecordName"),
    });

    new AcmCertificateValidation(scope, "main", {
      certificateArn: acmCertificate.arn,
      validationRecordFqdns: [validationRecords.fqdn]
    });
```

above results in error:

```
Because aws_route53_record.validation-record has "for_each" set, its
│ attributes must be accessed on specific instances.
```

**Comment by ansgarm** [comment]
Hi @mbazalik,
you could try to put `validationRecords` into a new `Iterator.fromList()` but that said, this is currently a gap in the Iterator API which might need an escape hook until we fix it (if using another iterator does not work).

**Comment by mbazalik** [comment]
Hi @ansgarm.
Thanks for your quick reply, I was trying both:

```typescript
const certificateValidationRecordIterator = TerraformIterator.fromList(
    certificateValidationRecord
);
```
resulting in Error: Argument of type 'RouteS3Record' is not assignable to parameter of type 'ListType' ...

```typescript
const certificateValidationRecordIterator = TerraformIterator.fromList(
    certificateValidationRecord.fqdn
);
```
resulting in Error: Argument of type 'string' is not assignable to parameter of type 'ListType' ...

:(

I was even trying different escape approaches, again without any luck :(

```typescript
const certValidation = new AcmCertificateValidation(scope, "main", {
    certificateArn: acmCertificate.arn,
  });

  certValidation.addOverride(
    "validation_record_fqdns",
    `[for record in ${certificateValidationRecord} : record.fqdn]`
  );
```

with error:
 on cdk.tf.json line 105, in resource.aws_acm_certificate_validation.main:
│  105:         "validation_record_fqdns": "[for record in service/certificate_validation : record.fqdn]"
│
│ Inappropriate value for attribute "validation_record_fqdns": set of string
│ required.

resp.

```typescript
const certValidation = new AcmCertificateValidation(scope, "main", {
    certificateArn: acmCertificate.arn,
  });

  certValidation.addOverride(
    "validation_record_fqdns",
    `[for record in ${certificateValidationRecord.fqdn} : record.fqdn]`
  );
```

with error:
 on cdk.tf.json line 105, in resource.aws_acm_certificate_validation.main:
│  105:         "validation_record_fqdns": "[for record in ${aws_route53_record.certificate_validation.fqdn} : record.fqdn]"
│
│ Because aws_route53_record.certificate_validation has "for_each" set, its
│ attributes must be accessed on specific instances.

**Comment by ansgarm** [comment]
Thank you @mbazalik 👍
fyi: We're working on implementing accessing resources created via an iterator in #2027.

**Comment by adamdry** [comment]
@ansgarm thanks for the update on the PR.

Is there a workaround to this atm? I used to use escape hatches in the previous version but that method doesn't seem to work anymore in the new version. So I started porting to iterators but hit this issue. Thanks!

**Comment by ansgarm** [comment]
Hi @adamdry 👋

I just found a weird but working workaround:

```ts
const cert = new AcmCertificate(this, "cert", {
      domainName: "example.com",
    });
    // Iterators currently fail for sets: https://github.com/hashicorp/terraform-cdk/issues/2001
    // This is a weird workaround for that, heavily relying on internals
    // using fromMap() instead of fromList() to circumvent wrapping in toset()
    const certValidationOptionsIterator = TerraformIterator.fromMap(
      // to circumvent wrapping a set in tolist() as for_each requires a set
      cert.interpolationForAttribute("domain_validation_options")
    );

    const validationRecords = new Route53Record(
      this,
      "certificate_validation",
      {
        forEach: certValidationOptionsIterator,
        allowOverwrite: true,
        records: [
          certValidationOptionsIterator.getString("resourceRecordValue"),
        ], // TODO: fix these (use underscores)?
        ttl: 60,
        type: certValidationOptionsIterator.getString("resourceRecordType"),
        zoneId: "123456",
        name: certValidationOptionsIterator.getString("resourceRecordName"),
      }
    );
    
    new AcmCertificateValidation(this, "main", {
      certificateArn: cert.arn,
      validationRecordFqdns: Token.asList(
        ref(
          `${validationRecords.terraformResourceType}.${validationRecords.friendlyUniqueId}.*.fqdn`
        )
      ),
    });
```

However, you still need to make sure the ACM cert is provisioned first (e.g. by using `-target` via the Terraform CLI in the outputs directory, as proposed by the error message). That is the same issue in HCL unfortunately.
But in regards to producing valid Terraform config, the workaround above should help. It works around this issue and #2001.

**Comment by pauldraper** [comment]
@skorfmann 's suggestion almost worked, but I found I had to tweak it a bit because `cert.fqn` didn't work.

```
const record = new aws.Route53Record(this, 'validation-record', {
  name: "${each.value.name}",
  type: "${each.value.type}",
  records: [
    "${each.value.record}"
  ],
  zoneId: zone.zoneId,
  ttl: 60,
  allowOverwrite:  true
})

record.addOverride('for_each', `\${{
    for dvo in aws_acm_certificate.${cert.friendlyUniqueId}.domain_validation_options : dvo.domain_name => {
      name   = dvo.resource_record_name
      record = dvo.resource_record_value
      type   = dvo.resource_record_type
    }
  }
}`)

const certValidation = new aws.AcmCertificateValidation(this, 'certvalidation', {
  certificateArn: cert.arn
})
certValidation.addOverride('validation_record_fqdns', `\${[for record in ${record.fqn} : record.fqdn]}`)
```
