### ISSUE TITLE
Ability to use Random Provider - random_password

### ISSUE THREAD

**Issue by choweiyuan** [hashicorp/terraform-cdk#431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like the ability to use https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/password with Terraform CDK.

Use Case - I'm trying to store randomly generated password to AWS Secrets Manager via Terraform, but can't achieve it without the above resource

**Comment by jsteinich** [comment]
It should be possible to use the `random` provider. Just add `random` to the list of terraform providers in `cdktf.json` and run `cdktf get`. That should generate a `Password` type that you can use.

**Comment by choweiyuan** [comment]
Thanks for the swift reply, this works for me. I'll close this issue, thanks for your help!
