### ISSUE TITLE
creationStack gets generated for certain scenarios

### ISSUE THREAD

**Issue by choweiyuan** [hashicorp/terraform-cdk#433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.0.18, TypeScript

### Affected Resource(s)

I've seen this happening on Tags so far.

### Expected Behavior

creationStack should be omitted as it makes the terraform stack too verbose.

### Actual Behavior

creationStack gets printed for certain resources, sample: https://gist.github.com/choweiyuan/66b82ddcbda96b6d51f71d1e77fa4ed2

### Steps to Reproduce

```
class DBOptionGroup extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    const tags: { [key: string]: string } = {};
    const sampleTagKey = new TerraformVariable(this, "sampleTagKey", {
      type: "string",
      description: "Sample tag key",
    })
    const sampleTagValue = new TerraformVariable(this, "sampleTagValue", {
      type: "string",
      description: "Sample tag value"
    })
    tags[sampleTagKey.value] = sampleTagValue.value
    const majorEngineVersion = "12.1";
    const engine = "oracle-se2";

    new DbOptionGroup(this, "dbOptionGroup2", {
      engineName: engine,
      majorEngineVersion,
      tags
    })
  }
}

const app = new App({
  stackTraces: false
});
new DBOptionGroup(app, 'sampleStack');

app.synth();
```

### Important Factoids

If I hardcode the tag key/value pair, then creationStack wouldn't appear. If I use variable then the problem occurs.

### References

* #0000

**Comment by skorfmann** [comment]
> If I hardcode the tag key/value pair, then creationStack wouldn't appear. If I use variable then the problem occurs.

Yes, looks like the Token reference of the variable is causing this. That's certainly a bug and should be addressed soonish.
