### ISSUE TITLE
AWS provider can't create an EKS cluster

### ISSUE THREAD

**Issue by cesarpball** [hashicorp/terraform-cdk#436]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "terraformProviders": ["aws@~> 2.0"],
  "codeMakerOutput": "imports"
}
```
cdktf --version 0.0.18-pre.134

### Affected Resource(s)

https://gist.github.com/cesarpball/5180bfadd8e1fb16116b810cb97b4530

### Expected Behavior

EKS created successfully

### Actual Behavior

```
  File "main.py", line 51, in __init__
    "subnet_ids": mylist
  File "/Users/test/.local/share/virtualenvs/aws-eks-infra-9UoNTo0O/lib/python3.7/site-packages/jsii/_runtime.py", line 69, in __call__
    inst = super().__call__(*args, **kwargs)
⠸ synthesizing ...
non-zero exit code 1
```

### Steps to Reproduce

cdktf diff

### Important Factoids

**subnet_ids** is a valid input for Terraform on the EKS cluster creation. This value is receiving a list of subnets-ids: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster

### References

None

**Comment by skorfmann** [comment]
well, that looks like a bug. We'll look into that

**Comment by jsteinich** [comment]
In `EksCluster`, need to use `role_arn` rather than `role`.

There are a couple bugs as well, but they can be worked around.
First, you'll need to wrap the vpc config in a list due to #258.
Second, you'll need to use the Typescript casing for the keys in the vpc config, i.e. `subnetIds`. I don't think there is an issue for that.

**Comment by cesarpball** [comment]
> In `EksCluster`, need to use `role_arn` rather than `role`.
> 
> There are a couple bugs as well, but they can be worked around.
> First, you'll need to wrap the vpc config in a list due to #258.
> Second, you'll need to use the Typescript casing for the keys in the vpc config, i.e. `subnetIds`. I don't think there is an issue for that.
> 
> ```python
>         EksCluster(self, "eks-cluster",
>             name = cluster_name,
>             role_arn = eksRole.arn,
>             vpc_config = [{
>                 "endpointPublicAccess": True,
>                 "subnetIds": mylist
>             }]
> 
>         )
> ```

This is working with this approach. Thanks for the clarification about the Typescript casing.

Regards
