### ISSUE TITLE
Gitlab provider generation broken by 0.0.18

### ISSUE THREAD

**Issue by ndarwincorn** [hashicorp/terraform-cdk#438]
Looks like a naming collision by adding the `reset[Attribute]()` method to generated attributes.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.0.18
TypeScript: ^4.0.5

### Affected Resource(s)

GitlabUser

### Debug Output

https://gist.github.com/ndarwincorn/9dd82281a1893e71fb74a05975743c1c

### Expected Behavior

`cdktf get` produces a usable provider

### Actual Behavior

The addition of [`getResetName()`](https://github.com/hashicorp/terraform-cdk/blob/bf4bcfd6113732228ccd9f225bb06291e0440497/packages/cdktf-cli/lib/get/generator/emitter/attributes-emitter.ts#L154-L157) results in the creation of a reset method that collides with another attribute, producing a compile time error in the typescript, regardless of whether the resource is used or not.

### Steps to Reproduce

[See gist.](https://gist.github.com/ndarwincorn/9dd82281a1893e71fb74a05975743c1c)

### Important Factoids

The `gitlab_user` resource [includes both `password` and `reset_password` attributes](https://github.com/gitlabhq/terraform-provider-gitlab/blob/v3.1.0/gitlab/resource_gitlab_user.go#L38-L85). With the addition of a reset method to the generated resource, the generated `_password` attribute gets a method (`resetPassword()`) that conflicts with the generated get/set `resetPassword()` methods for the `_resetPassword` attribute.

We don't use this resource yet, so our workaround is to just comment out the import line in the generated `index.ts` and delete the offending file.

Seems like this bug will happen when attempting to generate a resource with two attributes named *attribute* and reset_*attribute*.

### References

* #310

**Comment by jsteinich** [comment]
This should be fixed with #429

**Comment by skorfmann** [comment]
@ndarwincorn can you confirm it has been fixed with #429 merged?

**Comment by skorfmann** [comment]
@ndarwincorn thanks again for raising this issue. I just tried it locally with `0.0.19` and the issue seems to be fixed.
