### ISSUE TITLE
KeyVaultAccessPolicy - Inappropriate value for attribute "access_policy": element 0: attributes "application_id"

### ISSUE THREAD

**Issue by Mejato** [hashicorp/terraform-cdk#443]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

cdktf => v 0.0.18
terraform => v 0.13.5
azurerm => 2.37.0
python => 3.8.6

### Affected Resource(s)

KeyVaultAccessPolicy

### Debug Output

https://gist.github.com/Mejato/11d8814f61bb7dc3237e1224fb388fd9

### Expected Behavior

cdktf should have constructed the appropriate policy based on the documentation.

imports.azurerm.KeyVaultAccessPolicy def __init__(self,
             *,
             application_id: **Optional**[str] = None,
             certificate_permissions: **Optional**[List[str]] = None,
             key_permissions: Optional[List[str]] = None,
             object_id: Optional[str] = None,
             secret_permissions: **Optional**[List[str]] = None,
             storage_permissions: **Optional**[List[str]] = None,
             tenant_id: Optional[str] = None) -> None

### Actual Behavior

Terraform planning stage fails - see debug output gist.

### Steps to Reproduce
azure_key_vault_access_policy = KeyVaultAccessPolicy(tenant_id=azure_ad_tenant_id, secret_permissions=['get', 'set'], object_id=azure_principle)

### Important Factoids

N/A

**Comment by jsteinich** [comment]
I think this is the same underlying issue as #223. I believe you'll need to set the optional attributes as `None` or possibly `null` as a workaround.
