### ISSUE TITLE
Template java project does not compile

### ISSUE THREAD

**Issue by miguelaferreira** [hashicorp/terraform-cdk#444]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
$ cdktf --version
0.0.18
$ mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 1.8.0_275, vendor: Eclipse OpenJ9
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"
```

### Affected Resource(s)

Not applicable since the project itself is not compiling.

### Debug Output

I'm not sure if I could provide this since the only `cdktf` command I run is `init` and that fails on `mvn install` for an expected reason (missing mvn packages repo)

### Expected Behavior

The project would compile in such a way that I could follow the [getting started instructions](https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/java.md).

### Actual Behavior

What happens is that both a freshly created Java project and the AWS example provided in this repo do not compile.

### Steps to Reproduce

I've done two things:
1. start a new project following [these instructions](https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/java.md)
  * `cdktf init --template="java" --local` command fails on `mvn install` due to missing `com.hashicorp:cdktf` dependency
  * then I configure the repository with the required credentials
  * `mvn install` still fails due to missing package ` com.hashicorp.cdktf` (required for `com.hashicorp.cdktf.App` and `com.hashicorp.cdktf.TerraformStack`)
2. clone this repository and navigate to the [java aws example](https://github.com/hashicorp/terraform-cdk/tree/master/examples/java/aws)
  * configure the repository with the required credentials
  * update `com.hashicorp:cdktf:0.0.0` to `com.hashicorp:cdktf:0.0.18` in pom.xml
  * `mvn install` fails due to missing package ` com.hashicorp.cdktf`

### Important Factoids

This project looks awesome to me and I really hope I can do some serious terraforming from the comfort of my Java IDE! 

### References

Did not find anything,

**Comment by jsteinich** [comment]
I'm glad you're excited to try it out. I'll work on fixing asap. Sorry about that. I'm not sure how I missed that the jar generated was empty for releases. If you want, building from source does produce a working jar file.

**Comment by miguelaferreira** [comment]
Thanks for getting back to me! I've looked for the sources but I couldn't find them. Could you point me to it?

**Comment by jsteinich** [comment]
For full instructions, the [contributing guide](https://github.com/hashicorp/terraform-cdk/blob/master/CONTRIBUTING.md) has more information.
The high level is:

1. clone
2. yarn install
3. yarn build
4. yarn package

Once those are done, there will be a jar file in the `dist` folder.
