### ISSUE TITLE
Python CDK for Google

### ISSUE THREAD

**Issue by keunsooptmp** [hashicorp/terraform-cdk#446]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to use this CDK for Python to configure Google could resources.
Could you share your plan/roadmap for when it will be released?

**Comment by jsteinich** [comment]
It is already possible to use the Google provider for Terraform. There isn't a python example currently, but you can take a look at the [typescript example](https://github.com/hashicorp/terraform-cdk/tree/master/examples/typescript/google) or [other python examples](https://github.com/hashicorp/terraform-cdk/tree/master/examples/python).

**Comment by keunsooptmp** [comment]
@jshoffstall Thanks! It would be great if there is Python example available one day!
