### ISSUE TITLE
Generate terraform code from CDK, rather than terraform JSON configurations

### ISSUE THREAD

**Issue by keunsooptmp** [hashicorp/terraform-cdk#447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I understand that CDK generates Terraform JSON configurations files, and we can deploy these files as the same ways of deploying the terraform code files (`.tf`).
But our team has been using Terraform code files with typing them manually, and now we are supposed to use this CDK to generate them. To make our team members feel more comfortable, we prefer to have terraform code files as a result, rather than Terraform JSON configurations.
Is there such functionality in this CDK? Otherwise, developing such module is a part of the roadmap? When can it be released then?

**Comment by jsteinich** [comment]
It has been requested before (#225), so there may be some interest in adding it; however, I'm not aware of any current plans.

**Comment by skorfmann** [comment]
Thanks for opening this issue @keunsooptmp - Please consider to add to the discussion in #225. Closing this as duplicate.
