### ISSUE TITLE
Compile-error "Jsii$Proxy cannot implement getDependsOn()"

### ISSUE THREAD

**Issue by chburmeister** [hashicorp/terraform-cdk#453]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-version: 0.0.18 
language: java
terraform-providers: "aws@~> 2.0"
maven: 3.6.3
java: adoptopenjdk 15.0.1

### Affected Resource(s)

generated provider-source-files

### Expected Behavior

After running "cdktf get" I expect the generation of compilable java-source-files in package "imports.aws"

### Actual Behavior

Compile-Errors by running "mvn clean compile" for generated classes.
e.g.
`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project terraform-with-java: Compilation failure: Compilation failure: 
[ERROR] /Users/christoph/projects/terraform-with-java/src/main/java/imports/aws/S3BucketAnalyticsConfigurationConfig.java:[215,76] getDependsOn() in imports.aws.S3BucketAnalyticsConfigurationConfig.Jsii$Proxy cannot implement getDependsOn() in com.hashicorp.cdktf.TerraformMetaArguments
[ERROR]   return type java.util.List<com.hashicorp.cdktf.TerraformResource> is not compatible with java.util.List<com.hashicorp.cdktf.ITerraformDependable>
`

**Comment by jsteinich** [comment]
@chburmeister did you build the cdktf jar yourself? I ask because the currently published one is broken.
It also looks you are using a pre-release version since `ITerraformDependable` isn't in a release version yet.

**Comment by chburmeister** [comment]
Hi @jsteinich : Yes, you are absolutely right. I stumbled upon bug [444](https://github.com/hashicorp/terraform-cdk/issues/444#issue-750818931) and had to build the jar via yarn. I must have mixed up the tag with master/main-branch. Trying again with the v0.0.18-tag results in compilable java-sources  :-) 

Thanks for your fast reaction and help 👍
