### ISSUE TITLE
AttributeError: module 'cdktf' has no attribute 'ITerraformDependable'

### ISSUE THREAD

**Issue by sonfrau** [hashicorp/terraform-cdk#463]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I was using cdktf 0.0.17 as usual until now. Today I have upgraded to 0.0.19 and since then I've got a new error when I try to use cdktf synth.

I suspect it could be related to this commit: https://github.com/hashicorp/terraform-cdk/commit/4c2bd1af58823b264db3d0112fb25824f5b99ed9 but I don't have any idea how fix it.

Any clue would be pretty appreciated.

Thanks and kind regards

### cdktf & Language Versions

# cdktf --version
0.0.19

### Debug Output

+ cdktf synth

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from imports.aws import AwsProvider, DbInstance
  File "/mnt/efs/aplicaciones/orquestador01/jenkins/workspace/aws-rds-infra_mqbr/imports/aws/__init__.py", line 20, in <module>
    jsii_type="aws.AccessanalyzerAnalyzer",
  File "/mnt/efs/aplicaciones/orquestador01/jenkins/workspace/aws-rds-infra_mqbr/imports/aws/__init__.py", line 33, in AccessanalyzerAnalyzer
    provider: typing.Optional[cdktf.TerraformProvider] = None,
**AttributeError: module 'cdktf' has no attribute 'ITerraformDependable'**
⠹ synthesizing ...
non-zero exit code 1

### Expected Behavior

Success synthesizing 

### Actual Behavior

AttributeError: module 'cdktf' has no attribute 'ITerraformDependable'

### Steps to Reproduce

cdktf synth

### References

May be it's related to this commit: https://github.com/hashicorp/terraform-cdk/commit/4c2bd1af58823b264db3d0112fb25824f5b99ed9

**Comment by jsteinich** [comment]
Try running `cdktf get` again.

**Comment by sonfrau** [comment]
Thanks a lot for your support @jsteinich .

I have to say we have launched several `cdktf get` but the behaviour is the same.

We can add we are able to deploy that infrastructure from two sources: my laptop and a Jenkins servers which shows this issue.

Both were running cdktf 0.0.17.

First I upgraded my laptop to 0.0.18 and later to 0.0.19. I was able to deploy infrastructure without any issue.

Later, I upgraded our Jenkins server and was then when we realized about this problem. If I downgrade to 0.0.17 back, the issue disappears and Jenkins server goes fine.

Thanks and kind regards,

**Comment by sonfrau** [comment]
I share more previous output on Jenkins server by if it could be valious:

> + pipenv install
> Installing dependencies from Pipfile.lock (361bcb)…
> To activate this project's virtualenv, run pipenv shell.
> Alternatively, run a command inside the virtualenv with pipenv run.
> 
> + CHECKPOINT_DISABLE=true
> + cdktf get
> Generated python constructs in the output directory: imports
> 
> + CHECKPOINT_DISABLE=true
> + cdktf synth
> Traceback (most recent call last):
>   File "main.py", line 7, in <module>
>     from imports.aws import AwsProvider, DbInstance
>   File "/mnt/efs/aplicaciones/orquestador01/jenkins/workspace/aws-rds-infra_mqbr/imports/aws/__init__.py", line 20, in <module>
>     jsii_type="aws.AccessanalyzerAnalyzer",
>   File "/mnt/efs/aplicaciones/orquestador01/jenkins/workspace/aws-rds-infra_mqbr/imports/aws/__init__.py", line 33, in AccessanalyzerAnalyzer
>     provider: typing.Optional[cdktf.TerraformProvider] = None,
> AttributeError: module 'cdktf' has no attribute 'ITerraformDependable'
> ⠼ synthesizing ...
> non-zero exit code 1

**Comment by jsteinich** [comment]
@sonfrau my suspicion is that something is using an older version of cdktf.
Can you confirm which version is used in your `Pipfile` and `Pipfile.lock`?

**Comment by sonfrau** [comment]
Thanks again @jsteinich.

May be I'm doing something wrong. In theory, my laptop is using 0.0.19
```
$ cdktf --version
0.0.19
```
but I'm seeing next:
```
$ cat Pipfile
[[source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true

[requires]
python_version = "3"

[packages]
cdktf = "~=0.0.17"

$ cat Pipfile.lock
{
    "_meta": {
        "hash": {
            "sha256": "03b1f2d0a8fe3f38502fb46a2c795d211cde8005a6d5f1fa6634dc935f361bcb"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "attrs": {
            "hashes": [
                "sha256:31b2eced602aa8423c2aea9c76a724617ed67cf9513173fd3a4f03e3a929c7e6",
                "sha256:832aa3cde19744e49938b91fea06d69ecb9e649c93ba974535d08ad92164f700"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2, 3.3'",
            "version": "==20.3.0"
        },
        "cattrs": {
            "hashes": [
                "sha256:41398d3cbdda64707a9947c3ffac35116dc8ab5307c2962c02cdd01c96097149",
                "sha256:cd7579ef6ed80993bdd0e24a806493c48576caebd47b7b6ec2cd3cfd0b9a5f72"
            ],
            "markers": "python_version >= '3.7'",
            "version": "==1.1.1"
        },
        "cdktf": {
            "hashes": [
                "sha256:1b6cbb5325011b9bc75b0e57231ef2e3a3bf36460120bc57efe5489bef873ef6",
                "sha256:5d411b4a3742ce1afb0ab9607886a0a34226e14be3dbcc3f6676f897b15ffa89"
            ],
            "index": "pypi",
            "version": "==0.0.18"
        },
        "constructs": {
            "hashes": [
                "sha256:16b872d145461a6dca7ffe9c67ba42ac4bba332a8afbd604d5ae352054dee86a",
                "sha256:e068805ba9b6366b191d26112db67f81ab52e4b4e89ffad75217ead40957a664"
            ],
            "markers": "python_version >= '3.6'",
            "version": "==3.2.30"
        },
        "jsii": {
            "hashes": [
                "sha256:580e4fd38740b8a0c520db46f60c3e78aef6a6d01687c7ab8c28bfb74992310a",
                "sha256:f69086667a8b4fff586d9c0f26870260bf0f5a6ffcd379c7beb435c61a96a02e"
            ],
            "markers": "python_version ~= '3.6'",
            "version": "==1.14.1"
        },
        "publication": {
            "hashes": [
                "sha256:0248885351febc11d8a1098d5c8e3ab2dabcf3e8c0c96db1e17ecd12b53afbe6",
                "sha256:68416a0de76dddcdd2930d1c8ef853a743cc96c82416c4e4d3b5d901c6276dc4"
            ],
            "version": "==0.0.3"
        },
        "python-dateutil": {
            "hashes": [
                "sha256:73ebfe9dbf22e832286dafa60473e4cd239f8592f699aa5adaf10050e6e1823c",
                "sha256:75bb3f31ea686f1197762692a9ee6a7550b59fc6ca3a1f4b5d7e32fb98e2da2a"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==2.8.1"
        },
        "six": {
            "hashes": [
                "sha256:30639c035cdb23534cd4aa2dd52c3bf48f06e5f4a941509c8bafd8ce11080259",
                "sha256:8b74bedcbbbaca38ff6d7491d76f2b06b3592611af620f8426e82dddb04a5ced"
            ],
            "markers": "python_version >= '2.7' and python_version not in '3.0, 3.1, 3.2'",
            "version": "==1.15.0"
        },
        "typing-extensions": {
            "hashes": [
                "sha256:7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918",
                "sha256:99d4073b617d30288f569d3f13d2bd7548c3a7e4c8de87db09a9d29bb3a4a60c",
                "sha256:dafc7639cde7f1b6e1acc0f457842a83e722ccca8eef5270af2d74792619a89f"
            ],
            "version": "==3.7.4.3"
        }
    },
    "develop": {}
}

```
Jenkins server is showing the same outputs with either 0.0.17 or 0.0.19.

Kind regards and Merry Christmas!

**Comment by jsteinich** [comment]
The Pipfile is only created and isn't modified. Does seem like something that would be good to add.

**Comment by DanielMSchmidt** [comment]
Hey @sonfrau, I'm cleaning up old issues, have you seen this issue in a later release like 0.7 as well. I'd assume it's fixed by now
