### ISSUE TITLE
Unable to assign secret to kubernetes cluster

### ISSUE THREAD

**Issue by nvick** [hashicorp/terraform-cdk#466]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.0.19
Terraform: 0.14.3
Typescript/Javascript

### Affected Resource(s)

digitalocean/kubernetes_cluster
kubernetes/secret

### Debug Output

https://gist.github.com/nvick/f1b5afe4f6f5fa56f1247dc196505925

### Expected Behavior

Terraform to fetch the cluster_ca_certificate and allow secrets to be assigned to the cluster

### Actual Behavior

Errors with: certificate signed by unknown authority

### Steps to Reproduce

1. Create a Kubernetes Cluster on DigitalOcean
2. Assign attributes from the cluster to the Kubernetes Provider
3. Assign secrets to the cluster

```typescript
  const docr = new ContainerRegistry(this, 'container-registry-production', {
      name: 'example-testing',
      subscriptionTierSlug: 'professional'
  })

  const docrCredentials = new ContainerRegistryDockerCredentials(this, 'docr-credentials-production', {
      registryName: docr.name,
      dependsOn: [docr]
  })

  const kubeCluster = new KubernetesCluster(this, 'kubecluster-production', {
      name: 'kubecluster-production',
      region: 'sfo2',
      version: '1.19.3-do.2',
      tags: ['production'],
      vpcUuid: vpc.id,

      nodePool: [{
        name: 'default-autoscaling-poll',
        size: 'c-2',
        autoScale: true,
        minNodes: 3,
        maxNodes: 8
      }]
    })
  new KubernetesProvider(this, 'kubernetes', {
      loadConfigFile: false,
      host: kubeCluster.endpoint,
      token: kubeCluster.kubeConfig('0').token,
      clusterCaCertificate: kubeCluster.kubeConfig('0').clusterCaCertificate
  })

  new Secret(this, 'docr-registry-secret', {
      metadata: [{
        name: 'docr-registry-config'
      }],
      data: {
        ".dockerconfigjson": docrCredentials.dockerCredentials
      },
      type: "kubernetes.io/dockerconfigjson",
      dependsOn: [ docr, kubeCluster ]
  })
```

### Important Factoids

I'm new to cdktf and trying to translate Terraform docs so this could be an issue of my misinterpretation.

### References

https://registry.terraform.io/providers/digitalocean/digitalocean/latest/docs/resources/container_registry_docker_credentials#kubernetes-example

* #0000

**Comment by jsteinich** [comment]
I haven't used those resources, but comparing your code to the example, I see a missing `base64decode` on the certificate. There isn't currently a built in way to call that, but you can use [escape hatches](https://github.com/hashicorp/terraform-cdk/blob/master/docs/working-with-cdk-for-terraform/escape-hatch.md) to do so.

**Comment by nvick** [comment]
Thanks, @jsteinich. I will check escape hatches.

 I did not include it in my example, but I attempted to use node's base64decoding at one point.

```javascript
    const encodedCert = kubeClusterData.kubeConfig('0').clusterCaCertificate
    const buff = Buffer.from(encodedCert, 'base64')
    const decodedCert = buff.toString('utf8')

    new KubernetesProvider(this, 'kubernetes', {
      loadConfigFile: false,
      host: kubeCluster.endpoint,
      token: kubeCluster.kubeConfig('0').token,
      clusterCaCertificate: decodedCert
    })
```

**Comment by jsteinich** [comment]
> I did not include it in my example, but I attempted to use node's base64decoding at one point.

cdktf under the hood just creates terraform json and then runs terraform directly. That means in the flow of your program execution, the certificate is just a token that won't get filled in until later.

**Comment by nvick** [comment]
Yeah, I did not think about that until after I tried the above code.

**Comment by skorfmann** [comment]
@nvick not sure if I understand this correctly. Are you trying to defer this action to the apply time of Terraform? While this isn't directly supported by cdktf at this point, I was successful with using a [custom data source](https://gist.github.com/skorfmann/e399bbd85be6e5a8a5a021adcb570dd4). Would this be helpful in your case?

**Comment by nvick** [comment]
Thanks, @skorfmann. I'm not exactly sure. I'm going to close this out for now. Thanks for the help.

**Comment by sergeyzenchenko** [comment]
hi @jsteinich do you have any examples how to use base64decode using escape hatches? 
```
const kubeProvider = new KubernetesProvider(this, "k8s", {
    host: clusterConfig.endpoint,
    token: clientConfig.accessToken
});
let cert = `base64decode(${clusterConfig.masterAuth("0").clusterCaCertificate})}`;
kubeProvider.addOverride("cluster_ca_certificate", cert);
```

This way doesn't work.

**Comment by jsteinich** [comment]
I think you are pretty close. Try
```typescript
let cert = `\${base64decode(${clusterConfig.masterAuth("0").getStringAttribute("clusterCaCertificate")})}`;
```

**Comment by sergeyzenchenko** [comment]
I've tried this way too, but I am getting:
```
⠙ planning appspector-tf...

Error: Invalid character

  on cdk.tf.json line 31, in provider.kubernetes[0]:
  31:         "cluster_ca_certificate": "${base64decode(${data.google_container_cluster.cluster_config.master_auth.0.clusterCaCertificate})}",

This character is not used within the language.


Error: Invalid expression

  on cdk.tf.json line 31, in provider.kubernetes[0]:
  31:         "cluster_ca_certificate": "${base64decode(${data.google_container_cluster.cluster_config.master_auth.0.clusterCaCertificate})}",

Expected the start of an expression, but found an invalid expression token.
```

**Comment by jsteinich** [comment]
How about
```typescript
let cert = `\${base64decode(${clusterConfig.fqn}.master_auth.0.clusterCaCertificate)}`;
```

**Comment by sergeyzenchenko** [comment]
Thanks @jsteinich this one worked!
```
let cert = `\${base64decode(${clusterConfig.fqn}.master_auth.0.cluster_ca_certificate)}`;
```

**Comment by Crazybus** [comment]
For anyone else landing on this issue you can actually do this now natively in CDK: https://www.terraform.io/cdktf/concepts/functions

An example with Python looks like:

```python
from cdktf Fn

cluster = ContainerCluster(
    self,
    "cluster",
    name=name,
    location=region,
)

KubernetesProvider(
    self,
    id="kubernetes",
    host=f"https://{cluster.endpoint}",
    token=client.access_token,
    cluster_ca_certificate=Fn.base64decode(
        cluster.master_auth.cluster_ca_certificate
    ),
)
```
