### ISSUE TITLE
vpc not created  from given example

### ISSUE THREAD

**Issue by teamdts** [hashicorp/terraform-cdk#467]
### cdktf & Language Versions

cdktf --version 0.0.19
Python 3.6.9

### Affected Resource(s)
- VPC

### Debug Output

root@ubuntu:~/terraform-cdk/examples/python/aws# cdktf synth
⠋ synthesizing ...
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from imports.terraform_aws_modules.vpc.aws import Vpc
  File "/home/ubuntu/terraform-cdk/examples/python/aws/imports/terraform_aws_modules/vpc/aws/__init__.py", line 23
    self,
    ^
⠴ synthesizing ...
non-zero exit code 1
--->

### Expected Behavior

it must create VPC

### Actual Behavior

it is giving error while doing cdktf synth

### Steps to Reproduce

1. clone https://github.com/hashicorp/terraform-cdk.git repo
2. got example > python >  aws  dir
3. cdktf.json file change 'pipenv run python' to 'python3'
4.  execute `cdktf synth` command

**Comment by jsteinich** [comment]
@teamdts You'll need to run `cdktf get` before a synth will work correctly with that example.

**Comment by teamdts** [comment]
@jsteinich thanks for that.
yes it is fixed . now getting bellow error

```
(aws) root@ubuntu:~/terraform-cdk/examples/python/aws# cdktf deploy
⠋ planning python-aws...

Error: InvalidParameter: Invalid parameter: TopicArn
	status code: 400, request id: 9a1a8732-03bf-5c8d-b1b5-df68da9211c0

⠙ planning python-aws...
```

**Comment by jsteinich** [comment]
@teamdts That looks like an AWS error.
I just ran `cdktf diff` on the example without issue.
Have you made any modifications? Have you successfully deployed at any time?

**Comment by teamdts** [comment]
@jsteinich thanks for help
Have you successfully deployed at any time?  - yes some times work some time getting this error.
but now it is fixed don't know exact reason hows it is fixed.

Thanks
