### ISSUE TITLE
EksOptions.manageAwsAuth should be a boolean, not a string

### ISSUE THREAD

**Issue by digitalsanctum** [hashicorp/terraform-cdk#469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* hashicorp/terraform-cdk Version 0.0.19
* Language: Java
* Constructs Version: 5.0.0 (also tried 3.0.0)

### Affected Resource(s)

`EksOptions`

### Expected Behavior

The builder for EksOptions.manageAwsAuth should accept a boolean instead of a string

### Actual Behavior

The builder for EksOptions.manageAwsAuth accepts string

### References

* #0000

**Comment by jsteinich** [comment]
@digitalsanctum are you referring to the [eks module](https://registry.terraform.io/modules/terraform-aws-modules/eks/aws/latest?tab=inputs)?

**Comment by digitalsanctum** [comment]
@jsteinich yes. `terraform-aws-modules/eks/aws`

**Comment by jsteinich** [comment]
This seems to be a bug in the way that the module json schema is generated. The json has a type of `string` when the source `variables.tf` has an implicit type of `boolean` (has a boolean default). I'm not sure the best spot to file that; @skorfmann do you know?

**Comment by skorfmann** [comment]
> This seems to be a bug in the way that the module json schema is generated. The json has a type of `string` when the source `variables.tf` has an implicit type of `boolean` (has a boolean default). I'm not sure the best spot to file that; @skorfmann do you know?

I'll investigate.

**Comment by skorfmann** [comment]
> The builder for EksOptions.manageAwsAuth should accept a boolean instead of a string

The EKS module doesn't specify an explicit type. 

Up until Terraform 0.11 the type was [inferred from the default](https://www.terraform.io/docs/configuration-0-11/variables.html#description) or assumed to be a `string`. 

Starting with Terraform 0.12 the typing changed and it doesn't look like the type is inferred from defaults anymore. So, according to the [HCL docs](https://www.terraform.io/docs/configuration/variables.html#type-constraints) this should be `any`. This means, the  `string` type in the Terraform Registry is certainly misleading - however, it shouldn't be a boolean either. It should become `any`.

I'll try find a good solution for this. Meanwhile, the easiest fix in this particular case would be to create a PR to the [EKS repo](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/65777d0a37791dd1200d478e3bacc4c9a75f24c8/variables.tf#L47-L50
) and add an explicit type to these inputs.

**Comment by DanielMSchmidt** [comment]
We now have the correct types as inputs 👍
