### ISSUE TITLE
Integration Tests for Examples

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#47]
To ensure that our examples are always in a valid, deployable state, it'd be very helpful to have full end2end tests for our examples. 

Each example is: 

- Build 
- Synthesized
- Planned / Applied 
- Destroyed

**Comment by frezbo** [comment]
Yes, I would also like to see examples around writing Unit Tests. That seems to be missing.

**Comment by wuqunfei** [comment]
@skorfmann ,any tips and docs to use cdktf lib to build, synthesize, plan, destroy, I only saw cdktf cli to do it now, and the cdktf lib docs is almost empty.

**Comment by skorfmann** [comment]
We're building the examples as part of the Github Actions workflows. Going beyond that doesn't seem to be reasonable at this point.
