### ISSUE TITLE
Use locally-built terraform providers

### ISSUE THREAD

**Issue by mattchrist** [hashicorp/terraform-cdk#476]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like a way to use a locally built version of a terraform provider instead of always downloading providers from the internet.
This functionality would be helpful for using custom providers not published in the terraform registry, as well as when working on new features for existing terraform providers.

**Comment by skorfmann** [comment]
Skimming through this [tutorial](https://learn.hashicorp.com/tutorials/terraform/provider-setup#test-the-provider) it looks like the locally built provider are placed in the `plugins` folder in the terraform config folder. So, Terraform should automatically pick up the local provider. The command `cdktf get` should actually work with whatever the Terraform CLI works with (in the context of Providers. Modules are limited to the Terraform Registry at the moment).

Could you elaborate on the error you're experiencing when trying to use your local provider?

**Comment by mattchrist** [comment]
The schema from providers appears to be generated in a new temp folder every time, and `terraform init` is always run beforehand
https://github.com/hashicorp/terraform-cdk/blob/master/packages/cdktf-cli/lib/get/generator/provider-schema.ts#L81

It's my assumption that running `cdktf get` will always fetch the providers fresh every time since it's being launched in a freshly made temp folder... but to be honest I haven't actually tested that assumption.

You're suggesting I try creating a `.terraform.d/plugins` folder in my project and putting my locally built provider into it (in the path format specified in that tutorial)? 
I'll give that a try, but my expectation is that the schema generation function in cdktf that I linked above will need to also copy the `.terraform.d/plugins` folder into the temp folder before running `terraform init` (or something like that)

**Comment by skorfmann** [comment]
> Edit: I get it now, put the provider in my home-dir `~/.terraform.d/plugins`, I'll give that a go.

Yes - let me know if that works out for you.
