### ISSUE TITLE
Handle Variables for Terraform Cloud 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We should make the handling of Terraform Variables more streamlined for the Terraform Cloud workflow. At the moment, local variables are entirely ignored.

### References

* #449
* https://www.terraform.io/cloud-docs/workspaces/variables/managing-variables#run-specific-variables

**Comment by DanielMSchmidt** [comment]
Closed by #2468
