### ISSUE TITLE
Handle Switching Backend from Remote to Something Else

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#489]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the Remote Backend is dropped in favour of something else (e.g. Local), the Terraform CLI detects this change and asks if the existing state should be copied, see:

![Screenshot 2021-01-13 at 14 53 04](https://user-images.githubusercontent.com/136789/104461286-74136d00-55af-11eb-9309-87551c335a86.png)

The `init` command has a `force-copy` flag, which would essentially confirm this question with a yes. What do you think, is it safe to assume it's ok confirming this all the time and make it a default flag on the `init` step? 

### References

- #449

**Comment by jsteinich** [comment]
> What do you think, is it safe to assume it's ok confirming this all the time and make it a default flag on the `init` step?

In my experience, this has been true about 90% of the time. I do worry about that other 10% though.

**Comment by skorfmann** [comment]
> The `init` command has a `force-copy` flag,

Unfortunately, the `init` command doesn't have an option to specify where the local state should be written to. We use this in other commands like `plan` or `apply`.  Means, we would have to either start to move files around or perhaps define a fallback [local backend](https://www.terraform.io/docs/backends/types/local.html) explicitly with correct configuration if there's no other found.

**Comment by skorfmann** [comment]
> In my experience, this has been true about 90% of the time. I do worry about that other 10% though.
> Edit* that's for other backends, not for terraform cloud, but the messaging is the same.

Yes, this would apply to all sort of backends. And I agree, there's very likely a good reason why this step has to be confirmed in the Terraform CLI :)
