### ISSUE TITLE
azurerm Error: "features": required field is not set

### ISSUE THREAD

**Issue by prabh-62** [hashicorp/terraform-cdk#498]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```bash
❯ az version
{
  "azure-cli": "2.17.1",
  "azure-cli-core": "2.17.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```
```bash
❯ cdktf --version
0.1.0
```

### Affected Resource(s)

All Azure resources

### Debug Output

```
❯ cdktf diff
⠸ synthesizing ...
App synth complete
⠏ planning azure...

Error: "features": required field is not set
```
<img width="794" alt="azurerm_diff" src="https://user-images.githubusercontent.com/13006107/104797293-fa37db00-578a-11eb-9936-8f99d816149b.png">

### Expected Behavior
`cdktf diff` should not emit any errors

### Actual Behavior
`cdktf diff` emits non-zero exit code 1 

### Steps to Reproduce

```bash
> git clone https://github.com/hashicorp/terraform-cdk.git
> cd terraform-cdk/examples/csharp/azure (and update nuget file)
> cdktf get
> cdktf diff
```

### References

* #0000

**Comment by skorfmann** [comment]
@prabh-62 thanks for taking the time to create this issue. 

You mean this part can't be an empty array?

```csharp
 new AzurermProvider(this, "AzureRm", new AzurermProviderConfig {
                Features = Array.Empty<AzurermProviderFeatures>()
            });
```

**Comment by jsteinich** [comment]
Looks like just an error in the example (Java most likely has the same issue).

If you change
```csharp
Features = Array.Empty<AzurermProviderFeatures>()
```
to
```csharp
Features = new []{new AzurermProviderFeatures()}
```
I expect it to work (sorry, don't have an azure account to verify)

**Comment by prabh-62** [comment]
<img width="744" alt="cdktf_diff_success" src="https://user-images.githubusercontent.com/13006107/104815756-7e6a7c80-57e4-11eb-8634-1a674de56edb.png">

LGTM. Thank you for the suggestion.

**Comment by prabh-62** [comment]
@skorfmann Is the code fixed in template as well?
```bash
❯ cdktf init --template="csharp" --local
```

**Comment by skorfmann** [comment]
> @skorfmann Is the code fixed in template as well?

No, the provider isn't set [there](https://github.com/hashicorp/terraform-cdk/blob/db313032e4b9c10a9be89a862476d41946297381/packages/cdktf-cli/templates/csharp/Main.cs). I think that's intentional, since cdktf isn't bound to any specific provider. In fact, [this](https://github.com/hashicorp/terraform-cdk/blob/db313032e4b9c10a9be89a862476d41946297381/packages/cdktf-cli/templates/csharp/cdktf.json#L4) shouldn't be  there either - it should be [provider agnostic](https://github.com/hashicorp/terraform-cdk/issues/505).
