### ISSUE TITLE
C# cdktf get fails on windows, symlink

### ISSUE THREAD

**Issue by mikeparker** [hashicorp/terraform-cdk#501]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.1.0 (2 days old)

### Debug Output

https://gist.github.com/mikeparker/0a4aaa37c1d31efdf2956f40b5e1045d
In particular `Error: EPERM: operation not permitted, symlink ...`

### Expected Behavior

It completes

### Actual Behavior

It errored

### Steps to Reproduce

Run ` cdktf get` on windows

**Comment by jsteinich** [comment]
Likely caused by https://github.com/aws/jsii-srcmak/blob/32b05a562d4f90f19cedfacc301a10be051a11bb/src/compile.ts#L46
Symlinks have been getting removed in other places, so we can likely work on removing this one as well.

@mikeparker are you able to run with a user that has permissions to create symlinks (run as admin may be an option)?

**Comment by mikeparker** [comment]
@jsteinich yes, running as admin solves this. As a quick intermediate workaround it might be worth just adding a note to the readme that admin privs are needed on windows machines (not all developers have admin access).

After that it runs into whitespace directory name errors on my machine, same as with some other commands
```
C:\Git\src\github.com\mikeparker\hello-terraform2> cdktf get
⠇ downloading and generating providers...
⠏ downloading and generating providers...
Error: jsii compilation failed with non-zero exit code: 1
  | Error: Command (npm pack C:\Users\Mike Parker\AppData\Local\Temp\temp-KCq1q5) failed with status 1:
  | #STDERR> npm ERR! code ENOLOCAL
  | #STDERR> npm ERR! Could not install from "..\..\..\..\..\Mike" as it does not contain a package.json file.
```
Shall I open a separate ticket for that?

**Comment by jsteinich** [comment]
> Shall I open a separate ticket for that?

You can if you'd like to. Clearly spaces are breaking all steps, so we'll try to tackle that in one go.
