### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by SamuelMarks** [hashicorp/terraform-cdk#513]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I asked about a C API for Terraform a year and a quarter ago:
https://discuss.hashicorp.com/t/c-api-to-terraform-providers/14195

> Years ago I wrote a wrappers around Apache Libcloud in Python for my multi-cloud abstraction libraries. It’s great, and supports 50+ different public and private clouds.
>
> Now, I’m tossing up betwixt the different languages to rewrite the whole system in. Likely, I’ll write the bulk of it in C (C89, the old ANSI C); maybe with some configuration management done in Rust.
>
> Unfortunately there are no good/maintained abstracted cloud [de]provisioning/upload/configuration libraries. Cursory research shows Terraform as the only [maintained & large] library written with a non-VM language. Congrats!
>
> Are you planning to expose C-APIs; perhaps via Go’s builtin C meta-package; so this can be used from other languages?
>
> Thanks for considering this feature

PS: Happy to help out

**Comment by skorfmann** [comment]
@SamuelMarks you're essentially aiming for natively usable C libraries exported from Terraform Core? Or more like some sort of interface to drive the Terraform CLI programmatically?

**Comment by SamuelMarks** [comment]
@skorfmann The former. It would be great to have a self contained C library, that could be linked—statically or dynamically—with frontends (e.g., a CLI or RPC frontend written in C, or wrapped into a library that is statically/dynamically linked into another language, such as Rust).

This would enable unifying all the language interfaces around multicloud (Python's [libcloud](https://libcloud.apache.org/), Java's [jclouds](https://jclouds.apache.org), Ruby's [fog](https://fog.io)).

Importantly, this would enable some interesting use-cases, one could, for example:

- parse internal configuration in Crystal ([habitat](https://github.com/luckyframework/habitat));
- parse/emit server configs using official parsers (like the [official Python parser for nginx](https://github.com/nginxinc/crossplane))
- parse/emit configs using Rust (e.g., [serde](https://github.com/serde-rs/serde))
- install software calling native APIs (like `<dpkg/dpkg.h>`)
- download, archive, extract
- de/provision servers

…all with a single statically linked binary (with a link to a credential/config server, config file, and/or env vars also)

With everything unified and made trivially multilingual through FFI, the entire elastic scaling lifecycle can be managed from a single binary. Which will [I expect] lower the barrier to entry for moving between cloud providers, initial de/provisioning, scaling, and maintenance.

**Comment by skorfmann** [comment]
This sounds like a pretty interesting idea. However, I don't think that's within the scope of this particular project. I see the discuss link with the original posting goes to the Terraform Providers forum. I feel like this would be better addressed in the [Terraform](https://github.com/hashicorp/terraform) Github repo.

**Comment by SamuelMarks** [comment]
@skorfmann Thanks. Okay, opened an issue there. Closing this one.
