### ISSUE TITLE
ReadMe does not make the distinction between pip and pip even in docs/getting-started/python.md

### ISSUE THREAD

**Issue by JohnT1** [hashicorp/terraform-cdk#514]
Following these steps carefully on https://github.com/hashicorp/terraform-cdk/blob/master/docs/getting-started/python.md

After running **cdktf synth** I get 
_ERROR: synthesis failed, run "cdktf get" to generate providers in imports_

I think this may be because one of the two methods (pip not pip env) mentions that for the pip method this has to be done "with a simple requirements.txt file." but mine is blank?   How should I populate this file for this method please?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

* #0000

**Comment by cmclaughlin** [comment]
Can you provide the full output? Also, Python and cdktf versions would be helpful.

**Comment by skorfmann** [comment]
Please re-open if still relevant
