### ISSUE TITLE
Inappropriate value for attribute "ingress"

### ISSUE THREAD

**Issue by cesarpball** [hashicorp/terraform-cdk#517]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf version: 0.0.19
Language: Python

### Affected Resource(s)

SecurityGroups (Ingress resource)

### Debug Output

`Error: Incorrect attribute value type

  on cdk.tf.json line 237, in resource.aws_security_group.awsrdsinfra_securitygroup_62FC8872:
 237:         "ingress": [
 238:           {
 239:             "cidrBlocks": [
 240:               "0.0.0.0/0"
 241:             ],
 242:             "description": "Allow access to database",
 243:             "fromPort": 3306,
 244:             "ipv6CidrBlocks": [],
 245:             "prefixListIds": [],
 246:             "protocol": "tcp",
 247:             "securityGroups": [],
 248:             "selfAttribute": false,
 249:             "toPort": 3306
 250:           }
 251:         ],

Inappropriate value for attribute "ingress": element 0: attributes
"cidr_blocks", "from_port", "ipv6_cidr_blocks", "prefix_list_ids",
"security_groups", "self", and "to_port" are required.

non-zero exit code 1`
### Expected Behavior

❯ cdktf diff
Stack: aws-rds-infra
Resources

 + AWS_DB_INSTANCE      awsrdsinfra_dbinsta aws_db_instance.awsrdsinfra_dbinstancecesarpball_6817F739
 + AWS_DB_PARAMETER_GRO awsrdsinfra_paramet aws_db_parameter_group.awsrdsinfra_parametergroup_D8F91

### Actual Behavior

`Error: Incorrect attribute value type

  on cdk.tf.json line 237, in resource.aws_security_group.awsrdsinfra_securitygroup_62FC8872:
 237:         "ingress": [
 238:           {
 239:             "cidrBlocks": [
 240:               "0.0.0.0/0"
 241:             ],
 242:             "description": "Allow access to database",
 243:             "fromPort": 3306,
 244:             "ipv6CidrBlocks": [],
 245:             "prefixListIds": [],
 246:             "protocol": "tcp",
 247:             "securityGroups": [],
 248:             "selfAttribute": false,
 249:             "toPort": 3306
 250:           }
 251:         ],

Inappropriate value for attribute "ingress": element 0: attributes
"cidr_blocks", "from_port", "ipv6_cidr_blocks", "prefix_list_ids",
"security_groups", "self", and "to_port" are required.

non-zero exit code 1`

### Steps to Reproduce

cdktf diff

### References

* #282

**Comment by skorfmann** [comment]
@cesarpball thanks for raising this issue. This looks like something which will be fixed with https://github.com/hashicorp/terraform-cdk/pull/479

**Comment by skorfmann** [comment]
Closing as duplicated of #223 -  gonna be addressed in #479
