### ISSUE TITLE
AzureRM CosmosDB connection_strings[0] yields #{Token[TOKEN.0]} instead of first list item

### ISSUE THREAD

**Issue by Gerrit-K** [hashicorp/terraform-cdk#518]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

`cdktf`: `0.1.0`
`@cdktf/provider-azurerm`: `0.0.91`

### Affected Resource(s)

`CosmosdbAccount` from `@cdktf/provider-azurerm`

### Expected Behavior

Referencing `cosmosDbAccount.connectionStrings[0]`, e.g. as a terraform output, should yield the actual reference (i.e. in HCL: `"${azurerm_cosmosdb_account.cosmosdb_account.connection_strings[0]}"`).

### Actual Behavior

It actually yields `"#{Token[TOKEN.0]}"`

### Important Factoids

I'm pretty sure that this is closely related to #434 (and thus probably also #435), but I didn't want to hijack any of those for my question. I'm not very familiar with CDKTF yet, but from what I've read, I was expecting that `getListAttribute` was implemented for that exact purpose, but it doesn't seem to work here. Is this a bug or did I just miss something? And if not, is there a workaround for that?

### References

* #434

**Comment by Gerrit-K** [comment]
> is there a workaround for that?

Okay, I think I can answer this myself: all necessary parts of the connection string are provided as well, so I can construct it manually: 
```typescript
connectionString = `AccountEndpoint=${cosmosDbAccount.endpoint};AccountKey=${cosmosDbAccount.primaryKey};`;
```
Still, I would be interested in the details. Thanks!

**Comment by jsteinich** [comment]
Seems most closely related to #374.

I believe this is caused by the token resolution system seeing a string (since just accessing a single element) rather than the list and as such tries (and fails) to resolve as a string.

**Comment by DanielMSchmidt** [comment]
You can do `Fn.element(azurerm_cosmosdb_account.cosmosdb_account.connection_strings, 0)` now 👍
