### ISSUE TITLE
cdktf get for java generates empty directory

### ISSUE THREAD

**Issue by k-brooks** [hashicorp/terraform-cdk#519]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.1.0
terraform 0.14.5
openjdk 1.8.0_252

### Affected Resource(s)

cdktf / aws provider

### Debug Output

https://gist.github.com/k-brooks/abf7815491e82a91db40bb4c5cfe413a

### Expected Behavior

Generated Java classes

### Actual Behavior

Empty directory

### Steps to Reproduce

cdktf get -l "java"

### Important Factoids

I was able to successfully generate typescript and csharp

### References

* #0000

**Comment by skorfmann** [comment]
Thanks for raising this issue. 

> Empty directory

The `.gen` directory is empty?

**Comment by k-brooks** [comment]
Yes, the .gen directory is empty.
cdktf.json is as follows
```
{
  "language": "java",
  "app": "mvn -e -q compile exec:java",
  "terraformProviders": ["aws@~> 2.0"],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
}
```
Maven is configured with the cdktf github repo

**Comment by jsteinich** [comment]
Java actually generates source files within the main source tree at `src/main/java/imports`. We could clean up that empty directory though.

**Comment by k-brooks** [comment]
Thanks for the clarification.
If I may be so bold to suggest a fix; honor the output directory parameter, just change the default accordingly, depending on language (src/main/java/imports). This would be more consistent IMHO.

**Comment by skorfmann** [comment]
> If I may be so bold to suggest a fix; honor the output directory parameter, just change the default accordingly, depending on language (src/main/java/imports). This would be more consistent IMHO.

I agree, that's unexpected. We'll make this more consistent with the other languages.

**Comment by jsteinich** [comment]
I looked into this some more and it extends beyond just changing the default.
Created https://github.com/aws/jsii-srcmak/issues/366 to track some upstream changes that should make this go smoother.

**Comment by skorfmann** [comment]
> Java actually generates source files within the main source tree at `src/main/java/imports`. We could clean up that empty directory though.

Let's just clean up the empty directory for now and address further changes once aws/jsii-srcmak#366 is resolved.

**Comment by ansgarm** [comment]
Hey @k-brooks,

I started implementing the "small fix" (as I thought at first) to just skip having that `.gen` directory for Java. It turned out, there are quite a few places where I had check whether the current language was Java. For a temporary fix (while we wait for the [upstream issue](https://github.com/aws/jsii-srcmak/issues/366) to be resolved) this seemed a bit off to do it that way.

However, I found a workaround that you can use, if you want to get rid of that `.gen` directory:
By setting `"codeMakerOutput": "src/main/imports"` in your `cdktf.json` no `.gen` directory will be created.

Happy to assist if you have any questions!

**Comment by schersh** [comment]
> 

@ansgarm the upstream issue that you linked is now closed. does that mean this could be ready to be worked on, or might be resolved?

**Comment by ansgarm** [comment]
Good catch @schersh! Unfortunately the upstream issue was auto-closed due to inactivity 😞
