### ISSUE TITLE
Support for Kubernetes CRDs / `kubernetes-alpha`? 

### ISSUE THREAD

**Issue by dotansimha** [hashicorp/terraform-cdk#527]
Hi! 

I'm currently experimenting with using Terraform CDK with TypeScript, and one of my deployment plans includes a usage for a Kubernetes CRD. 
I noticed that the default K8s provider for TF (`hashicorp/kubernetes@~> 2.0.1`) doesn't support K8s CRD (or just plain manifests), and this support is only available with `kubernetes-alpha`. 

I tried to update my `cdktf.json` file to use `kubernetes-alpha`, but while running `cdktf get` I got this error: 

```
$ cdktf get
⠦ downloading and generating providers...
Error: invalid primitive type dynamic
    at Parser.renderAttributeType (cdktf-cli/lib/get/generator/resource-parser.js:62:32)
    at Parser.renderAttributesForBlock (cdktf-cli/lib/get/generator/resource-parser.js:106:31)
    at Parser.resourceFrom (cdktf-cli/lib/get/generator/resource-parser.js:36:33)
    at ResourceParser.parse (cdktf-cli/lib/get/generator/resource-parser.js:217:33)
    at TerraformGenerator.emitProvider (cdktf-cli/lib/get/generator/provider-generator.js:61:66)
    at new TerraformGenerator (cdktf-cli/lib/get/generator/provider-generator.js:48:18)
    at GetProvider.generateTypeScript (cdktf-cli/lib/get/providers.js:12:9)
    at async GetProvider.get (cdktf-cli/lib/get/base.js:44:9)
    at async ConstructsMaker.getProviders (cdktf-cli/bin/cmds/helper/constructs-maker.js:17:13)
    at async get (cdktf-cli/bin/cmds/ui/get.js:51:17)
invalid primitive type dynamic
```

Is there a way to overcome this? Or another alternative for using CDK with CRD?

Thank you!

**Comment by jsteinich** [comment]
I haven't seen `dynamic` as an attribute type before, but I don't think it would render to a very usable type.

You might have better luck using https://github.com/awslabs/cdk8s in combination with cdktf. @skorfmann do you have any samples for that?

**Comment by skorfmann** [comment]
Hm, that's interesting. In general, we do want to support all available providers and therefore the entire spectrum of the schema. For reference, here's the schema of that provider:

<details>

```json
{
	"format_version": "0.1",
	"provider_schemas": {
		"registry.terraform.io/hashicorp/kubernetes-alpha": {
			"provider": {
				"version": 0,
				"block": {
					"attributes": {
						"client_certificate": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"client_key": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"cluster_ca_certificate": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context_cluster": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context_user": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_path": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"exec": {
							"type": ["object", {
								"api_version": "string",
								"args": ["list", "string"],
								"command": "string",
								"env": ["map", "string"]
							}],
							"description_kind": "plain",
							"optional": true
						},
						"host": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"insecure": {
							"type": "bool",
							"description_kind": "plain",
							"optional": true
						},
						"password": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"server_side_planning": {
							"type": "bool",
							"description_kind": "plain",
							"optional": true
						},
						"token": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"username": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						}
					},
					"description_kind": "plain"
				}
			},
			"resource_schemas": {
				"kubernetes_manifest": {
					"version": 1,
					"block": {
						"attributes": {
							"manifest": {
								"type": "dynamic",
								"description": "A Kubernetes manifest describing the desired state of the resource in HCL format.",
								"description_kind": "plain",
								"required": true
							},
							"object": {
								"type": "dynamic",
								"description": "The resulting resource state, as returned by the API server after applying the desired state from `manifest`.",
								"description_kind": "plain",
								"optional": true,
								"computed": true
							},
							"wait_for": {
								"type": ["object", {
									"fields": ["map", "string"]
								}],
								"description": "A map of attribute paths and desired patterns to be matched. After each apply the provider will wait for all attributes listed here to reach a value that matches the desired pattern.",
								"description_kind": "plain",
								"optional": true
							}
						},
						"description_kind": "plain"
					}
				}
			}
		}
	}
}
``` 
</details>

When looking at the [provider](https://github.com/hashicorp/terraform-provider-kubernetes-alpha) and example from [tfk8s](https://github.com/jrhouston/tfk8s), it appears to be more or less just JSON - not sure to which extent this would be validated.

```hcl
resource "kubernetes_manifest_hcl" "configmap_test" {
  manifest = {
    "apiVersion" = "v1"
    "data" = {
      "TEST" = "test"
    }
    "kind" = "ConfigMap"
    "metadata" = {
      "name" = "test"
    }
  }
}
```

So, in the easiest case, dynamic attributes would just accept a JSON string? What do you think @jsteinich?

> You might have better luck using https://github.com/awslabs/cdk8s in combination with cdktf. @skorfmann do you have any samples for that?

I haven't tried this, but I think there would be a bit of work required to make this render seamlessly. However, that would be certainly an interesting use-case here.

**Comment by jsteinich** [comment]
> So, in the easiest case, dynamic attributes would just accept a JSON string? What do you think @jsteinich?

Perhaps a map of arbitrary string keys to values would be better. Something like `{ [key: string]: any }`.
Either way it's not very discoverable, but probably better than failing to generate.

**Comment by dotansimha** [comment]
> > So, in the easiest case, dynamic attributes would just accept a JSON string? What do you think @jsteinich?
> 
> Perhaps a map of arbitrary string keys to values would be better. Something like `{ [key: string]: any }`.
> Either way it's not very discoverable, but probably better than failing to generate.


Yeah, totally. In Pulumi for example, the have a special type called `CustomResource` (see https://www.pulumi.com/docs/reference/pkg/kubernetes/apiextensions/customresource/) intended for that. The API is exactly as you described it - it's just a TypeScript transformation of the YAML schema, with `Record<string, unknown>` set to allow flexibility. 

I prefer dealing with objects that has `any` / `unknown` set instead of a raw `string`, I think it would be easier to work with.

**Comment by dotansimha** [comment]
@skorfmann @jsteinich thank you for your thoughts and support :) I was looking at `cdk8s` but it seems like the eventual result of it is just a YAML of K8s which it still something I need to apply manually, right? How can this be done with `terraform-cdk`? Am I missing something here? 

Also, the suggestion to map `dynamic` into an arbitrary JSON sounds like a great idea. Do you think you can consider that as a `good-first-issue`? If so, I would love to make a PR!

**Comment by dotansimha** [comment]
If someone else is dealing with this and looking for a temporary workaround:

You can use `gavinbunney/kubectl@~> 1.9.4` provider, which allow you to use Kubernetes YAML as-is. The setup of the provider is the same as `hashicorp/kubernetes` so it doesn't really adds any complexity. 

With TS, it looks like that: 

```ts
// Create the provider
new KubectlProvider(scope, 'k8s-yaml', {
  configPath: environment.kubeConfig
});

// Define the plan
import { Manifest } from '.gen/providers/kubectl';

new Manifest(this, 'my-custom-resource', {
  yamlBody: `...`
});
```

**Comment by jsteinich** [comment]
> Also, the suggestion to map `dynamic` into an arbitrary JSON sounds like a great idea. Do you think you can consider that as a `good-first-issue`? If so, I would love to make a PR!

It's probably not the best first issue since the attribute type system is a bit complicated and messy, but you are more than welcome to take a look at it.

**Comment by skorfmann** [comment]
> Also, the suggestion to map `dynamic` into an arbitrary JSON sounds like a great idea. Do you think you can consider that as a `good-first-issue`? If so, I would love to make a PR!

As @jsteinich said, feel free to take a stab at it. Happy to help if there are questions around this.

**Comment by skorfmann** [comment]
Just checked this again - both, `cdktf get` and `cdktf synth` works as expected for this:

```ts
import { Construct } from "constructs";
import { App, TerraformStack } from "cdktf";
import * as k8s from './.gen/providers/kubernetes-alpha'

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new k8s.KubernetesAlphaProvider(this, 'kubernetes-alpha');

    new k8s.KubernetesManifest(this, 'kubernetes-manifest', {
      manifest: {
        apiVersion: 'v1',
        kind: 'Pod',
        metadata: {
          name: 'my-pod',
          labels: {
            app: 'my-app'
          }
        },
        spec: {
          containers: [
            {
              name: 'my-container',
              image: 'my-image'
            }
          ]
        }
      }
    })
    // define resources here
  }
}

const app = new App();
new MyStack(app, "foo");
app.synth();

```
