### ISSUE TITLE
provider-azurerm is not compatible with cdktf

### ISSUE THREAD

**Issue by moatazelmasry2** [hashicorp/terraform-cdk#530]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.10.0
@cdktf/provider-azurerm: 0.0.105

### Debug Output

https://gist.github.com/moatazelmasry2/94a50d631d4d19cca653a0254ff0cfb5

### Expected Behavior

@cdktf/provider-azurerm is installed successfully

### Actual Behavior

@cdktf/provider-azurerm can not be installed due to unable to resolve dependancy tree

### Steps to Reproduce

```bash
mkdir tf-example
cd tf-example
cdktf init --template=typescript --local
npm i -a @cdktf/provider-azurerm
```

### Important Factoids

No. I was able to reproduce the same behaviour on a Mac and on a docker ubuntu container

**Comment by skorfmann** [comment]
Thanks for raising this issue, I'm just in the progress of updating the dependencies - see https://github.com/terraform-cdk-providers/cdktf-provider-azurerm/pull/184

**Comment by skorfmann** [comment]
Please give this version a try https://github.com/terraform-cdk-providers/cdktf-provider-azurerm/releases/tag/v0.1.1

**Comment by moatazelmasry2** [comment]
This is probably a new record in resolving an issue on github.
Works like charm. 

Many thanks and cheers from Hessen to Hamburg :)))

**Comment by skorfmann** [comment]
Thanks 😊 and greetings to Hessen. Closing this issue. please don't hesitate to create follow up issues if there are other things popping up.
