### ISSUE TITLE
CDK provider for DigitalOcean

### ISSUE THREAD

**Issue by jubairsaidi** [hashicorp/terraform-cdk#531]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if we could get a CDK provider for DO! I was recently introduced to CDKTF and was super excited about it until I realized that there is no DigitalOcean provider for it... Any chance we can get one? and/or an expected ETA if it's currently in the works?

**Comment by skorfmann** [comment]
@jubairsaidi thanks for creating this issue. You can generate the provider bindings for every Terraform provider, see [here](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#importing-providers-and-modules). We do publish a few [pre-built providers](https://github.com/terraform-cdk-providers/), but not for DigitialOcean at this point.

I can see that this is not really clear when reading through the Readme and the first steps guide. So, I'll take this as an opportunity to improve the documentation around this.

**Comment by jubairsaidi** [comment]
nice! your team f*n ROCK! thank you :)

**Comment by jubairsaidi** [comment]
So I did use a generated provider for DO and it does need some work (like Droplet.image being a string or number, and When Droplet.count is specified it results in a list of resources rather than single instance) and am sure there are others.  If the maintainers of this project create a pre-built DO provider, I would be more than glad to submit a PR with fixes I find.

**Comment by jsteinich** [comment]
The pre-built providers are built and updated by generating providers the same way that users are able to.
The code generated is based on [terraform providers schema](https://www.terraform.io/docs/cli/commands/providers/schema.html) output.
There are occasions where the provider itself doesn't provide the correct definition of its schema. In that case filing an issue with the provider may be appropriate.
It's also possible the code generation itself has issues, in which case specifics can be reported here.

I haven't used the DO provider before, but it looks like `Droplet.image` is a string in the provider source code.
What value are you providing for `Droplet.count`? It should result in that many instances being created.

**Comment by jubairsaidi** [comment]
Updating the typescript definition for `get image(): string | number` `_image: string | number` and `set image(val: string | number)` (previously it was just `string`) fixed my issue there.

On Droplet.count, the issue is that when the count is specified, the result is a list of droplets, not a single instance.

for example terraform would look like this:
```
resource "digitalocean_droplet" "service" {
  count  = 1
  image  = var.service_instance_image
  name   = var.service_instance_name
  region = var.do_region
  size   = var.service_instance_size
  ssh_keys = [
    var.ssh_key.fingerprint
  ]
}

```
and when accessing this output later you have to do:
```
digitalocean_droplet.service[0].ipv4_address
```
instead of:
```
digitalocean_droplet.service.ipv4_address
```

When you omit the `count` you can access the droplet attributes via:
```
digitalocean_droplet.service.ipv4_address
```

**Comment by jsteinich** [comment]
> Updating the typescript definition for `get image(): string | number` `_image: string | number` and `set image(val: string | number)` (previously it was just `string`) fixed my issue there.

There aren't currently any hooks to modify the code generation, but they could potentially be useful.
Another option is to simply extend/wrap the base type to add/modify functionality.



> On Droplet.count, the issue is that when the count is specified, the result is a list of droplets, not a single instance.

I believe that's all standard behavior for terraform. It would be interesting to consider having count =1 effectively remove the argument, but we'd want to think through the implications before making such a change.

**Comment by skorfmann** [comment]
> Updating the typescript definition for `get image(): string | number` `_image: string | number` and `set image(val: string | number)` (previously it was just `string`) fixed my issue there.

Not sure how this fixed your issue. Could you elaborate on this?

> On Droplet.count, the issue is that when the count is specified, the result is a list of droplets, not a single instance.

Yes, there's pretty much no support for `count` beyond specifying it along the resource attributes right now. That's certainly something to iterate on and improve in general. 

> > On Droplet.count, the issue is that when the count is specified, the result is a list of droplets, not a single instance.
> 
> I believe that's all standard behavior for terraform. It would be interesting to consider having count =1 effectively remove the argument, but we'd want to think through the implications before making such a change.

Hm, this seems like an edge case. I think it would make more sense to improve the usability of list / count elements.

**Comment by skorfmann** [comment]
Going to close this issue, if there's still need for clarification please leave a comment.
