### ISSUE TITLE
cdktf python aws provider cannot be located.

### ISSUE THREAD

**Issue by rmmathik** [hashicorp/terraform-cdk#532]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Hi Team, Getting the following error during init and subsequent cdktf get
cdktf python

command: cdktf init --template="python-pip" --local 
output:
Collecting cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1))
cdktf init [OPTIONS]

Create a new cdktf project from a template.

Options:
  --version                   Show version number                                                                                    [boolean]
  --disable-logging           Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.                   [boolean] [default: true]
  --disable-plugin-cache-env  Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured differently.
                              Supported using the env CDKTF_DISABLE_PLUGIN_CACHE_ENV.                               [boolean] [default: false]
  --log-level                 Which log level should be written. Only supported via setting the env CDKTF_LOG_LEVEL                   [string]
  --template                  The template name to be used to create a new project.
                                              [string] [choices: "csharp", "java", "python", "python-pip", "typescript", "typescript-minimal"]
  --project-name              The name of the project.                                                                                [string]
  --project-description       The description of the project.                                                                         [string]
  --dist                      Install dependencies from a "dist" directory (for development)                                          [string]
  --local                     Use local state storage for generated Terraform.                                      [boolean] [default: false]
  --cdktf-version             The cdktf version to use while creating a new project.                       [string] [default: "0.1.0-pre.175"]
  -h, --help                  Show help                                                                                              [boolean]

{ Error: Command failed: pip install -r requirements.txt
    at checkExecSyncError (child_process.js:629:11)
    at execSync (child_process.js:666:13)
    at Object.exports.post.options [as post] (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/cdktf-cli/templates/python-pip/.hooks.sscaff.js:29:3)
    at executePostHook (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:28:15)
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 10505,
  stdout: null,
  stderr: null }

command cdktf get
Error: Invalid version constraint

  on providers.tf.json line 1, in terraform.required_providers:
   1: {"provider":{"aws":{}},"terraform":{"required_providers":{"aws":{"version":"~> 2.0","source":"aws"}}}}

A string value is required for aws.

Error: non-zero exit code 1
    at ChildProcess.child.once (/home/ec2-user/.nvm/versions/node/v10.23.0/lib/node_modules/cdktf-cli/lib/util.js:99:27)
    at Object.onceWrapper (events.js:286:20)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
non-zero exit code 1

**Comment by jsteinich** [comment]
Seems like it actually failed to install the cdktf package, although I'm not sure why. I just tried locally without issue.

**Comment by rmmathik** [comment]
How do we ensure if the package is installed correctly? Every other cdktf command works fine for me. I ran it using SUDO and here is the result.

sai-admin:~/environment/saranam $ sudo cdktf init --template="python-pip" --local                                                             
/usr/lib/node_modules/cdktf-cli/node_modules/yargs/yargs.js:4
async function requiresNode8OrGreater () {}
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/cdktf-cli/node_modules/yargs/index.js:5:15)

**Comment by rmmathik** [comment]
Between just tested a couple of other languages (TS etc) and teh result is the same.

**Comment by jsteinich** [comment]
@rmmathik which version of node do you have installed?

**Comment by rmmathik** [comment]
sai-admin:~/environment/saranam $ node --version
v10.23.0

**Comment by jsteinich** [comment]
Node 12.16+ is required. I would try installing again once you have that.

**Comment by rmmathik** [comment]
node -v
v14.15.4

sai-admin:~/environment/saranam $ sudo npm install --global cdktf-cli@next
/usr/bin/cdktf -> /usr/lib/node_modules/cdktf-cli/bin/cdktf
npm WARN eslint-plugin-react@7.22.0 requires a peer of eslint@^3 || ^4 || ^5 || ^6 || ^7 but none is installed. You must install peer dependencies yourself.

+ cdktf-cli@0.1.0-pre.175
updated 3 packages in 14.446s

sai-admin:~/environment/saranam $ cdktf init --template="python-pip" --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.tfstate' in the root of your project.

We will now set up the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'saranam') 
Project Description: (default: 'A simple getting started project for cdktf.') 
Collecting cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1))
cdktf init [OPTIONS]

Create a new cdktf project from a template.

Options:
  --version                   Show version number                                                                                                                                   [boolean]
  --disable-logging           Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.                                                                  [boolean] [default: true]
  --disable-plugin-cache-env  Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured differently. Supported using the env
                              CDKTF_DISABLE_PLUGIN_CACHE_ENV.                                                                                                      [boolean] [default: false]
  --log-level                 Which log level should be written. Only supported via setting the env CDKTF_LOG_LEVEL                                                                  [string]
  --template                  The template name to be used to create a new project.          [string] [choices: "csharp", "java", "python", "python-pip", "typescript", "typescript-minimal"]
  --project-name              The name of the project.                                                                                                                               [string]
  --project-description       The description of the project.                                                                                                                        [string]
  --dist                      Install dependencies from a "dist" directory (for development)                                                                                         [string]
  --local                     Use local state storage for generated Terraform.                                                                                     [boolean] [default: false]
  --cdktf-version             The cdktf version to use while creating a new project.                                                                      [string] [default: "0.1.0-pre.175"]
  -h, --help                  Show help                                                                                                                                             [boolean]

Error: Command failed: pip install -r requirements.txt
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.exports.post (/usr/lib/node_modules/cdktf-cli/templates/python-pip/.hooks.sscaff.js:29:3)
    at executePostHook (/usr/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/usr/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/usr/lib/node_modules/cdktf-cli/bin/cmds/init.js:92:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 19767,
  stdout: null,
  stderr: null
}

**Comment by rmmathik** [comment]
The node is latest stable version and yet it does not work.

**Comment by jsteinich** [comment]
What version of python do you have?

**Comment by rmmathik** [comment]
3.8

**Comment by jsteinich** [comment]
@rmmathik Can you try some of the steps mentioned [here](https://stackoverflow.com/a/56841001)? Something like `pip install --verbose -r requirements.txt` may give some more clues as to what is going wrong.

**Comment by rmmathik** [comment]
It looks like its searching for the cdktf package from pypi and not locally. I have installed cdktf. Here is the verbose output. 

sai-admin:~/environment/test9 $ pip install --verbose -r requirements.txt 
Collecting cdktf~=0.1.0.dev175 (from -r requirements.txt (line 1))
  1 location(s) to search for versions of cdktf:
  * https://pypi.python.org/simple/cdktf/
  Getting page https://pypi.python.org/simple/cdktf/
  Looking up "https://pypi.python.org/simple/cdktf/" in the cache
  Returning cached "301 Moved Permanently" response (ignoring date and etag information)
  Looking up "https://pypi.org/simple/cdktf/" in the cache
  Current age based on date: 17
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response

Using Pip3, the requirement seems to be OK.

sai-admin:~/environment/test9 $ pip3 install --verbose -r requirements.txt                                                                                                                   
Requirement already satisfied: cdktf~=0.1.0.dev175 in /usr/local/lib/python3.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: jsii<2.0.0,>=1.17.1 in /usr/local/lib/python3.7/site-packages (from cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: publication>=0.0.3 in /usr/local/lib/python3.7/site-packages (from cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: constructs<4.0.0,>=3.0.0 in /usr/local/lib/python3.7/site-packages (from cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: typing-extensions~=3.7 in /usr/local/lib/python3.7/site-packages (from jsii<2.0.0,>=1.17.1->cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: python-dateutil in /usr/local/lib/python3.7/site-packages (from jsii<2.0.0,>=1.17.1->cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: cattrs~=1.1.0; python_version >= "3.7" in /usr/local/lib/python3.7/site-packages (from jsii<2.0.0,>=1.17.1->cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: attrs~=20.1 in /usr/local/lib/python3.7/site-packages (from jsii<2.0.0,>=1.17.1->cdktf~=0.1.0.dev175->-r requirements.txt (line 1))
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/site-packages (from python-dateutil->jsii<2.0.0,>=1.17.1->cdktf~=0.1.0.dev175->-r requirements.txt (line 1))

**Comment by jsteinich** [comment]
@rmmathik thanks for that info. All the init command does after installing requirements is run `cdktf get` and run the app, so you should be able to get started with a project.

Perhaps we could explicitly use `pip3` rather than `pip` in the template.

**Comment by skorfmann** [comment]
@rmmathik  what are the versions of `pip` and `pip3` in your case?

**Comment by rmmathik** [comment]
@skorfmann pip is 2.7 and pip3 is 3.8 (Assuming the Python version you are referring to here)

@jsteinich -- what is the way forward here? Should I wait for a change to come through from cdktf?

**Comment by rmmathik** [comment]
pip 9.0.3 from /usr/lib/python2.7/site-packages (python 2.7)
pip 9.0.3 from /usr/lib/python3.7/site-packages (python 3.7)

**Comment by rmmathik** [comment]
tried in another machine (Windows) with only Python 3.8 and node8 etc but getting another issue

C:\Users\rmmathik\AppData\Roaming\npm\cdktf -> C:\Users\rmmathik\AppData\Roaming\npm\node_modules\cdktf-cli\bin\cdktf
npm WARN eslint-plugin-react@7.22.0 requires a peer of eslint@^3 || ^4 || ^5 || ^6 || ^7 but none is installed. You must install peer dependencies yourself.

+ cdktf-cli@0.1.0-pre.177
updated 8 packages in 17.705s

C:\summa-test-sai>pip --version
pip 20.1.1 from c:\program files\python38\lib\site-packages\pip (python 3.8)

C:\summa-test-sai>cdktf init --template="python-pip" --local
Note: By supplying '--local' option you have chosen local storage mode for storing the state of your stack.
This means that your Terraform state file will be stored locally on disk in a file 'terraform.tfstate' in the root of your project.

We will now set up the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'summa-test-sai')
Project Description: (default: 'A simple getting started project for cdktf.')
Unable to find "pip".

**Comment by skorfmann** [comment]
> Perhaps we could explicitly use `pip3` rather than `pip` in the template.

Wouldn't it make sense to check for  `pip` and  `pip3` and use what's present and has the closest desired version or throwing an error?

**Comment by rmmathik** [comment]
So what is the workaround until then @skorfmann ?
Also -- did you check the logs from Windows?

**Comment by skorfmann** [comment]
> tried in another machine (Windows) with only Python 3.8 and node8 etc but getting another issue

Is that node version 8? That wouldn't be supported.

> Unable to find "pip".

That's where the error is printed out - see [here](https://github.com/hashicorp/terraform-cdk/blob/25cc5997f550a46cb2fdfa0558c0f6c5c99c8a42/packages/cdktf-cli/templates/python-pip/.hooks.sscaff.js#L16) - I think it would make sense to try to reproduce what the template is doing by running these commands manually.

**Comment by rmmathik** [comment]
The code seems to be incorrect...

exports.pre = () => {
  try {
    if (os.platform() === 'win32') {
      execSync('where pip')
    }
    else {
      execSync('which pip')
    }
  } catch {
    console.error(`Unable to find "pip".`)
    process.exit(1);
  }
};

my os is win64 so the code goes and issues a "which pip" which is incorrect and hence the error. 

For ex, where pip is correctly resolving on the machine..
C:\summa-test-sai>**where pip**
### C:\Program Files\Python38\Scripts\pip.exe

**Comment by rmmathik** [comment]
@skorfmann the pip version is as follows.

C:\summa-test-sai>**pip -V**
**pip 20.1.1 from c:\program files\python38\lib\site-packages\pip (python 3.8)**

**Comment by jsteinich** [comment]
> my os is win64 so the code goes and issues a "which pip" which is incorrect and hence the error.

[win32 is correct](https://nodejs.org/api/process.html#process_process_platform), but I'll look into it further. I was hoping the same check as the regular python template would work, but there must be more going on.



> So what is the workaround until then

Manually running `pip3 install -r requirements.txt` has basically finished the work that the init command is doing. You should be able to start using normally afterwards (will need to `cdktf get` for any needed providers).
