### ISSUE TITLE
Support multiple output files for synth

### ISSUE THREAD

**Issue by mikeparker** [hashicorp/terraform-cdk#537]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have many terraform files I am trying to replicate with cdktf synth but there doesn't seem to be a way to specify which output files different pieces go into. I've checked most of the issues and the closest was 'multiple stacks' but I'm unsure thats the same thing. Is this simply not supported?

For example, I have an AWS lambda setup in one file, an API gateway in another, an SQS queue in the next, etc.

**Comment by jsteinich** [comment]
There are two main use cases for multiple tf files that I'm aware of.

1. Purely organizational so that you don't have one giant file. I believe that using multiple source files accomplishes this and more.
2. Different files are in different directories in order to deploy pieces on infrastructure differently. I.e. database tier, application tier, etc. That is what #35 is primarily aimed at.

Do you have a different use case?

**Comment by mikeparker** [comment]
My use case is (1) so I must have missed exactly how this works, I can't see a way to specify the file output either in the code or from the command line (synth isnt showing output _file_ options, only _directory_ -> https://github.com/hashicorp/terraform-cdk/blob/main/docs/cli-commands.md#cdktf-synth).

I've been following this -> https://github.com/hashicorp/terraform-cdk/blob/main/docs/getting-started/csharp.md but I've also read a bunch of docs - I guess from your response I've missed it somewhere?

**Comment by jsteinich** [comment]
You didn't miss anything; there isn't a way to output multiple files.

The output file (`cdk.tf.json`) is assumed to be fed directly into terraform (via cdktf or native terraform). What would you like to do with that output? Just trying to better understand the use-case.

**Comment by mikeparker** [comment]
I'm trying to generate a large quantity of well formatted .tf files to augment (and eventually replace) our existing large suite of .tf files which are checked in. I don't want to pass one massive json file directly to terraform, I want to keep using a github repo full of .tf files but move towards generating those (at least in part) from a programming language. Maybe this is not a use case the cdktf was designed for?

**Comment by jsteinich** [comment]
I wouldn't consider it the core use case, but several others have requested something similar.
See #225 and #510.

**Comment by mikeparker** [comment]
Right yes closing as a duplicate of #225
