### ISSUE TITLE
Use of CDK ICluster in CDK-TF

### ISSUE THREAD

**Issue by jvargh** [hashicorp/terraform-cdk#538]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Needed to use ICluster's add_manifest in py CDK-TF. Any thoughts how this be can be done? Prime reason being to use K8S manifests to create objects
https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_eks/ICluster.html

**Comment by skorfmann** [comment]
> Needed to use ICluster's add_manifest in py CDK-TF. Any thoughts how this be can be done? Prime reason being to use K8S manifests to create objects

At the moment, there's no compatibility between AWS-CDK and `cdktf`. See https://github.com/hashicorp/terraform-cdk/issues/244 for more context. 

For your specific use-case, do you want to provision an EKS cluster or do you want to use [cdk8s](https://cdk8s.io/) on top of `cdktf`?

**Comment by jvargh** [comment]
Does cdktf provide a way to apply a manifest to a cluster as done below below in cdk? The manifest will hold the definition to k8s resources. If not is there a sample on using cdk8s on top of cdktf somehow? 
```
from aws_cdk import aws_eks as eks
...
cluster= eks.Cluster.from_cluster_attributes(...
cluster.add_manifest(...
```

**Comment by skorfmann** [comment]
> Does cdktf provide a way to apply a manifest to a cluster as done below below in cdk? 

You mean something like in [this example](https://github.com/hashicorp/terraform-cdk/blob/714734b248b52c140d4c891bef0045d4f89a038c/examples/typescript/kubernetes/main.ts)?
 
> If not is there a sample on using cdk8s to create the manifest to be used in cdktf somehow?

I haven't tried that yet, it's likely not a drop in solution. However, that's something which we'll explore.

**Comment by jvargh** [comment]
Issue i'm having is when defining AppMesh virtual node there's no option to add metadata > namespace, as seen in below link. 
https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/master/src/appmesh-virtual-node.ts
In aws cdk i've used add_manifest to workaround, as per below manifest. Is there anything that can be done with cdktf? 
`
            "apiVersion": "appmesh.k8s.aws/v1beta2",
            "kind": "VirtualNode",
            "metadata": {
                "namespace": namespace_name,    <<<<<<<
                "name": redis_name,
            },
            "spec": {
                "podSelector": {"matchLabels": {"app": redis_name}},
                "listeners": [{
                    "portMapping": {"port": 6379, "targetPort": 6379, "protocol": "tcp" }
                }],
                "serviceDiscovery": {"awsCloudMap": {"namespaceName": domain, "serviceName": redis_name}}                
            }
`

**Comment by jsteinich** [comment]
> Is there anything that can be done with cdktf?

I have a feeling #527 will help you out, but I'm not really familiar enough with EKS to say for certain and it requires some fixes to cdktf before it can be used.

**Comment by skorfmann** [comment]
> Issue i'm having is when defining AppMesh virtual node there's no option to add metadata > namespace, as seen in below link. Without this definition it gets defined in default ns. 
> Also `podSelector `is needed to match deployment labels (when AppMesh is enabled), else the pods are not created. `PodSelector `is currently not available in `AppmeshVirtualNodeSpec`.
> https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/master/src/appmesh-virtual-node.ts

Look like we're talking about this resource here? https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appmesh_virtual_node 

> In aws cdk i've used `add_manifest` to workaround, as per below manifest to get it to work. Is there anything that can be done with cdktf?

This seems to be in the context of the EKS module? https://docs.aws.amazon.com/cdk/api/latest/docs/aws-eks-readme.html#quick-start Or is it another resource?

Do you happen to have a fully working example in AWS CDK? I think this might help to understand what you're trying to achieve.e

**Comment by jvargh** [comment]
Link provided is the same resource and its AppMesh in context of the EKS. 
AppMesh like Istio service mesh is an overlay on top of K8S. When K8S namespace has this tag `"appmesh.k8s.aws/sidecarInjectorWebhook": "enabled"` K8S deployments have to match up their labels with virtual nodes to create pods. Since in the virtual node spec there isn't a way to specify podSelector, only workaround is to inject the K8S manifest.

**Comment by jvargh** [comment]
suggestion mentioned in [#527](https://github.com/hashicorp/terraform-cdk/issues/527#issuecomment-771923857) got the needed workaround
