### ISSUE TITLE
Support "dynamic" attribute

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#539]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [Kubernetes (Alpha)](https://github.com/hashicorp/terraform-provider-kubernetes-alpha) contains attributes with the type `dynamic`, see the following provider schema:

<details>

```json
{
	"format_version": "0.1",
	"provider_schemas": {
		"registry.terraform.io/hashicorp/kubernetes-alpha": {
			"provider": {
				"version": 0,
				"block": {
					"attributes": {
						"client_certificate": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"client_key": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"cluster_ca_certificate": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context_cluster": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_context_user": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"config_path": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"exec": {
							"type": ["object", {
								"api_version": "string",
								"args": ["list", "string"],
								"command": "string",
								"env": ["map", "string"]
							}],
							"description_kind": "plain",
							"optional": true
						},
						"host": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"insecure": {
							"type": "bool",
							"description_kind": "plain",
							"optional": true
						},
						"password": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"server_side_planning": {
							"type": "bool",
							"description_kind": "plain",
							"optional": true
						},
						"token": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						},
						"username": {
							"type": "string",
							"description_kind": "plain",
							"optional": true
						}
					},
					"description_kind": "plain"
				}
			},
			"resource_schemas": {
				"kubernetes_manifest": {
					"version": 1,
					"block": {
						"attributes": {
							"manifest": {
								"type": "dynamic",
								"description": "A Kubernetes manifest describing the desired state of the resource in HCL format.",
								"description_kind": "plain",
								"required": true
							},
							"object": {
								"type": "dynamic",
								"description": "The resulting resource state, as returned by the API server after applying the desired state from `manifest`.",
								"description_kind": "plain",
								"optional": true,
								"computed": true
							},
							"wait_for": {
								"type": ["object", {
									"fields": ["map", "string"]
								}],
								"description": "A map of attribute paths and desired patterns to be matched. After each apply the provider will wait for all attributes listed here to reach a value that matches the desired pattern.",
								"description_kind": "plain",
								"optional": true
							}
						},
						"description_kind": "plain"
					}
				}
			}
		}
	}
}
``` 
</details>

At the moment, trying to generate a provider which contains a `dynamic` attribute will result in [an error](https://github.com/hashicorp/terraform-cdk/blob/ad213c1937ccb4e55deaf0b9e554fa7023f8d974/packages/cdktf-cli/lib/get/generator/resource-parser.ts#L69) since there's no proper mapping. 

### Example

When looking at the [provider](https://github.com/hashicorp/terraform-provider-kubernetes-alpha) and example from [tfk8s](https://github.com/jrhouston/tfk8s), it appears to be more or less just JSON - not sure to which extent this would be validated - that's something to verify.

```hcl
resource "kubernetes_manifest_hcl" "configmap_test" {
  manifest = {
    "apiVersion" = "v1"
    "data" = {
      "TEST" = "test"
    }
    "kind" = "ConfigMap"
    "metadata" = {
      "name" = "test"
    }
  }
}
```

We [think](https://github.com/hashicorp/terraform-cdk/issues/527#issuecomment-770878277) it would make sense to let the user supply an object with arbritary values (`{[key: string]: any}`) for now. 

The `HCL` example above would look like this:

```typescript
new KubernetesManifestHcl(this, 'configmap', {
  manifest: {
    apiVersion: "v1",
    data: {
      TEST: 'test"
    },
    kind: 'ConfigMap',
    metadata: {
      name: 'test'
    }
  }
})
```

### References

https://github.com/hashicorp/terraform-cdk/issues/527

**Comment by dotansimha** [comment]
> We [think](https://github.com/hashicorp/terraform-cdk/issues/527#issuecomment-770878277) it would make sense to let the user supply an object with arbritary values (`{[key: string]: any}`) for now.

Maybe `Record<string, unknown>` will be more TypeScript friendly than `any` :)

**Comment by skorfmann** [comment]
> > We [think](https://github.com/hashicorp/terraform-cdk/issues/527#issuecomment-770878277) it would make sense to let the user supply an object with arbritary values (`{[key: string]: any}`) for now.
> 
> Maybe `Record<string, unknown>` will be more TypeScript friendly than `any` :)

Could you elaborate on the benefits you see for Typescript?

**Comment by dotansimha** [comment]
> > > We [think](https://github.com/hashicorp/terraform-cdk/issues/527#issuecomment-770878277) it would make sense to let the user supply an object with arbritary values (`{[key: string]: any}`) for now.
> > 
> > 
> > Maybe `Record<string, unknown>` will be more TypeScript friendly than `any` :)
> 
> Could you elaborate on the benefits you see for Typescript?

Specifically for `Record`, [this might help](https://stackoverflow.com/questions/51936369/what-is-the-record-type-in-typescript). Also, most linters for TypeScript prefers `Record` over `{ [key: string]: value }` since it's more readable (for example: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/consistent-indexed-object-style.md).

For the `any` vs `unknown`, see https://mariusschulz.com/blog/the-unknown-type-in-typescript

**Comment by skorfmann** [comment]
Thanks for the links! 

> Specifically for `Record`, [this might help](https://stackoverflow.com/questions/51936369/what-is-the-record-type-in-typescript). Also, most linters for TypeScript prefers `Record` over `{ [key: string]: value }` since it's more readable

Don't have any strong opinion here. Would be fine with `Record` here. For the record, I verified that `jsii` deals with it as expected. So that would be ok as well from that regard.

>> For the `any` vs `unknown`, see https://mariusschulz.com/blog/the-unknown-type-in-typescript

>What happens though when we try to assign a value of type unknown to variables of other types?
>```ts
> let value: unknown;
> 
> let value1: unknown = value;   // OK
> let value2: any = value;       // OK
> let value3: boolean = value;   // Error
> let value4: number = value;    // Error
> let value5: string = value;    // Error
> let value6: object = value;    // Error
> let value7: any[] = value;     // Error
> let value8: Function = value;  // Error
>```
> Let's now see what happens when we try to perform operations on values of type unknown. Here are the same operations we've looked at before:
> ```ts
> let value: unknown;
>
> value.foo.bar;  // Error
> value.trim();   // Error
> value();        // Error
> new value();    // Error
> value[0][1];    // Error
>```

I'm not convinced. that the `unknown` type would be really helpful here in our case. Looks like you'd have to explicitly cast it to something when wanting to access nested attributes or assign it to other variables.
