### ISSUE TITLE
cdktf init for java fails with timeout error and .gen folder is empty

### ISSUE THREAD

**Issue by sbattagi** [hashicorp/terraform-cdk#544]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf version: 0.1.0
Terraform v0.14.5

### Affected Resource(s)
Below command is failing with timeout error, not generating the kubernetes provider files.
cdktf init --template="java" --local

### Debug Output
error:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.805 s
[INFO] Finished at: 2021-02-03T12:20:38Z
[INFO] ------------------------------------------------------------------------
⠼ downloading and generating providers...
/home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: connect ETIMEDOUT 172.64.204.26:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
Emitted 'error' event on ClientRequest instance at:
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -110,
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '172.64.204.26',
  port: 443
}
cdktf init [OPTIONS]

Create a new cdktf project from a template.

Options:
  --version                   Show version number                                                                     [boolean]
  --disable-logging           Dont write log files. Supported using the env CDKTF_DISABLE_LOGGING.    [boolean] [default: true]
  --disable-plugin-cache-env  Dont set TF_PLUGIN_CACHE_DIR automatically. This is useful when the plugin cache is configured
                              differently. Supported using the env CDKTF_DISABLE_PLUGIN_CACHE_ENV.   [boolean] [default: false]
  --log-level                 Which log level should be written. Only supported via setting the env CDKTF_LOG_LEVEL    [string]
  --template                  The template name to be used to create a new project.
                               [string] [choices: "csharp", "java", "python", "python-pip", "typescript", "typescript-minimal"]
  --project-name              The name of the project.                                                                 [string]
  --project-description       The description of the project.                                                          [string]
  --dist                      Install dependencies from a "dist" directory (for development)                           [string]
  --local                     Use local state storage for generated Terraform.                       [boolean] [default: false]
  --cdktf-version             The cdktf version to use while creating a new project.                [string] [default: "0.1.0"]
  -h, --help                  Show help                                                                               [boolean]

Error: Command failed: "/home/software/node-v14.15.4-linux-x64/bin/node" /home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/bin/cdktf get
    at checkExecSyncError (child_process.js:616:11)
    at execSync (child_process.js:652:15)
    at Object.exports.post (/home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/templates/java/.hooks.sscaff.js:41:3)
    at executePostHook (/home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:61:37)
    at Object.sscaff (/home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/node_modules/sscaff/lib/sscaff.js:28:15)
    at async Object.handler (/home/software/node-v14.15.4-linux-x64/lib/node_modules/cdktf-cli/bin/cmds/init.js:92:9) {
  status: 7,
  signal: null,
  output: [ null, null, null ],
  pid: 14348,
  stdout: null,
  stderr: null
}
$

### Expected Behavior
downloading and generating providers... step should be successful.

### Actual Behavior
downloading and generating providers...step fails with timeout error.

### Steps to Reproduce

1. Install cdftf-cli
2. mkdir hello-terraform
cd hello-terraform
cdktf init --template="java" --local

content of cdktf.json :
$ cat cdktf.json
{
  "language": "java",
  "app": "mvn -e -q compile exec:java",
  "terraformProviders": ["kubernetes@~> 1.11.3"]
}
$

### References

* #0000

**Comment by skorfmann** [comment]
> address: '172.64.204.26',

```
 dig +short checkpoint-api.hashicorp.com
172.64.205.26
172.64.204.26
```

Perhaps one of the IP addresses of the [telemetry](https://github.com/hashicorp/terraform-cdk/blob/fdd804f3194259a8dadd995fdaeedc06ed23b6c0/docs/working-with-cdk-for-terraform/telemetry.md) reporting. Could you try to disable it by setting the `CHECKPOINT_DISABLE` env variable to non-empty value and run again?

**Comment by sbattagi** [comment]
Thanks a lot @skorfmann  for the suggestion.
By setting the variable CHECKPOINT_DISABLE=false I am now able to successfully generate the providers.

However the .gen directory is empty after the run. Is that expected ?

**Comment by skorfmann** [comment]
> However the .gen directory is empty after the run. Is that expected ?

Can you check if the `src` directory contains the generated files? - see https://github.com/hashicorp/terraform-cdk/issues/519

**Comment by skorfmann** [comment]
> Thanks a lot @skorfmann for the suggestion.
> By setting the variable CHECKPOINT_DISABLE=false I am now able to successfully generate the providers.

Out of curiosity, are you behind a proxy or something like this?

**Comment by sbattagi** [comment]
Yes, src file has the generated files.
Yes, I am behind a organization proxy.

I have another question regarding cdktf:

Does the cdktf tool supports managing the on-premise kubernetes cluster ?
I see the below kubernetes provider uses the AWS cdk jsii, my doubt is does this
work for on-premise kubernetes cluster as well? or is there a separate provider for that ? 
Appreciate your inputs.

$ cat cdktf.json
{
“language”: “java”,

“app”: “mvn -e -q compile exec:java”,

“terraformProviders”: [“kubernetes@~> 1.11.3”]
}
$

**Comment by sbattagi** [comment]
My use case is to deploy using terraform in a local kubernetes cluster (using java).
Please suggest the right provider to use for this.

**Comment by skorfmann** [comment]
> Does the cdktf tool supports managing the on-premise kubernetes cluster ?
> I see the below kubernetes provider uses the AWS cdk jsii, my doubt is does this
> work for on-premise kubernetes cluster as well? or is there a separate provider for that ?
> Appreciate your inputs.

The Terraform [Kubernetes provider](https://registry.terraform.io/providers/hashicorp/kubernetes/latest/docs) isn't tied to AWS, so it should be perfectly usable for your use-case. [jsii](https://github.com/aws/jsii) is the library which make the polyglot packages work (java, python, c#)

> Yes, I am behind a organization proxy.

Ok, thanks for the feedback. We'll improve the error message for these kind of issues.

**Comment by sbattagi** [comment]
Thanks for the clarification.

I see two terraform kubernetes providers out there....what is the difference between these two and which one I should use ?

https://github.com/terraform-cdk-providers/cdktf-provider-kubernetes
https://github.com/hashicorp/terraform-provider-kubernetes

**Comment by skorfmann** [comment]
> https://github.com/hashicorp/terraform-provider-kubernetes

This is the actual Terraform Provider for Kubernetes.

> https://github.com/terraform-cdk-providers/cdktf-provider-kubernetes

This is our pre-generated cdktf provider package, which contains the type bindings for the actual Terraform Provider above. However, we're not yet publishing Java maven packages (only npm and pypi). So, you'll have to [generate it](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#importing-providers-and-modules) by yourself.

**Comment by sbattagi** [comment]
Understood. Following your suggestion, I was able to generate the JAVA provider for Kubernetes.
Then integrated them with a sample java application, however while running the sample java application, seen below error:

Exception in thread "main" software.amazon.jsii.JsiiException: Cannot find the 'jsii-runtime' executable (JSII_RUNTIME or PATH)
        at software.amazon.jsii.JsiiRuntime.startRuntimeIfNeeded(JsiiRuntime.java:260)
        at software.amazon.jsii.JsiiRuntime.getClient(JsiiRuntime.java:315)
        at software.amazon.jsii.JsiiEngine.getClient(JsiiEngine.java:150)
        at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:188)
        at software.amazon.jsii.JsiiEngine.loadModule(JsiiEngine.java:185)
        at software.amazon.jsii.JsiiEngine.createNewObject(JsiiEngine.java:597)
        at com.hashicorp.cdktf.App.<init>(App.java:36)

I have bundled "jsii-runtime-1.20.0.jar" in to the lib directory used to run this java application.
Added these dependencies to the application pom.xml file.
<dependency>
      <groupId>software.amazon.jsii</groupId>
      <artifactId>jsii-runtime</artifactId>
      <version>1.20.0</version>
    </dependency>
    <dependency>
      <groupId>com.hashicorp</groupId>
      <artifactId>cdktf</artifactId>
      <version>0.1.0</version>
    </dependency>
    <dependency>
      <groupId>software.constructs</groupId>
      <artifactId>constructs</artifactId>
      <version>3.0.0</version>
    </dependency>

**Comment by skorfmann** [comment]
Hm, not quite sure just by looking at logs. Any chance you can provide the full code as gist / github repo?

**Comment by sbattagi** [comment]
> 
> 
> Hm, not quite sure just by looking at logs. Any chance you can provide the full code as gist / github repo?

Sorry for the delay in response, I was out of work for a week.

Now I am able to resolve the above mentioned exception, by adding "node js" bin directory to the env PATH variable.

Could you please provide any Kubernetes (java) samples for reference, similar to the examples mentioned here for other providers ? 
https://github.com/hashicorp/terraform-cdk/tree/main/examples/java

**Comment by skorfmann** [comment]
> Now I am able to resolve the above mentioned exception, by adding "node js" bin directory to the env PATH variable.

Yes, nodejs is required, even when using other languages such as Java. I'll add this to the getting started [guides](https://github.com/hashicorp/terraform-cdk/blob/main/docs/getting-started/java.md).

> Could you please provide any Kubernetes (java) samples for reference, similar to the examples mentioned here for other providers ?
> https://github.com/hashicorp/terraform-cdk/tree/main/examples/java

There is a Typescript [example](https://github.com/hashicorp/terraform-cdk/tree/00af7818808bf6ecd28a8ad0b051586b6a688042/examples/typescript/kubernetes). This could be used as basis for building a Java example. I'll create an issue to track this.

**Comment by sbattagi** [comment]
Thanks for the clarifications. Closing this issue.
