### ISSUE TITLE
Improve Error Message for when Checkpoint isn't Reachable

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When the checkpoint endpoint isn't reachable due to network limitations, a user will see the raw nodejs error message (e.g. a Timeout error). We should catch this error and provide an actionable error message (e.g. suggesting to set the environment variable `CHECKPOINT_DISABLE` to a non empty value)

### References

- https://github.com/hashicorp/terraform-cdk/issues/544

**Comment by jsteinich** [comment]
Potentially a duplicate of #351.

I personally think that error should be caught and just ignored.

**Comment by skorfmann** [comment]
> Potentially a duplicate of #351.

True, thanks for the hint 👍 

> I personally think that error should be caught and just ignored.

Yeah, good point.

Closing as duplicate of #351
