### ISSUE TITLE
Generate wrong comunity provider configuration

### ISSUE THREAD

**Issue by dzirg44** [hashicorp/terraform-cdk#547]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

package.json
```
    "@types/node": "^14.14.25",
    "cdktf-cli": "0.1.0-pre.178",
    "typescript": "^4.1.3"
```
cdktf
```
0.0.19-pre.149
```
typescript
```
4.1.3
```
also tried stable version
### Affected Resource(s)
- cdktf get

### Debug Output
a lot of  errors, but just because of completely broken file.

### Expected Behavior
generate working typescript configuration or show  error\errors. 

### Actual Behavior

When I try to generate typescript provider from
```json
{
  "language": "typescript",
  "terraformProviders": ["phillbaker/elasticsearch@~> 1.5.1"],
}
```
i can see , that index file cannot be properly created. 
### Steps to Reproduce
add terraform provider as described and check `.gen/providers/elasticsearch/index.ts` file.

**Comment by jsteinich** [comment]
@dzirg44 which version of Terraform do you have installed?
I experienced errors when using 0.12.x, but 0.13.x worked fine for me.

**Comment by dzirg44** [comment]
```
Terraform v0.14.3

Your version of Terraform is out of date! The latest version
is 0.14.6. You can update by downloading from https://www.terraform.io/downloads.html
```
upgraded to the 
v0.14.5 without any effect.

generated file (index.ts) looks like
```ts
export * from './elasticsearch-provider';

blic constructor(scope: Construct, id: string, config: IndexConfig) {
    super(scope, id, {
      terraformResourceType: 'elasticsearch_index',
      terraformGeneratorMetadata: {
        providerName: 'elasticsearch'
      },
      provider: config.provider,
      dependsOn: config.dependsOn,
      count: config.count,
      lifecycle: config.lifecycle
    });
    this._aliases = config.aliases;
    this._autoExpandReplicas = config.autoExpandReplicas;
    this._codec = config.codec;
    this._forceDestroy = config.forceDestroy;
    this._loadFixedBitsetFiltersEagerly = config.loadFixedBitsetFiltersEagerly;
    this._mappings = config.mappings;
    this._name = config.name;
    this._numberOfReplicas = config.numberOfReplicas;
    this._numberOfShards = config.numberOfShards;
    this._refreshInterval = config.refreshInterval;
    this._rolloverAlias = config.rolloverAlias;
    this._routingPartitionSize = config.routingPartitionSize;
  }

  // ==========
  // ATTRIBUTES
  // ==========
```
where as you can see we don't have class name, even `constructor` cannot be properly generated
I've also tried with different version of node, and different version of cdkf. Maybe I missed something, but I don't know what.

**Comment by skorfmann** [comment]
> where as you can see we don't have class name, even `constructor` cannot be properly generated
> I've also tried with different version of node, and different version of cdkf. Maybe I missed something, but I don't know what.

The ES [index resource](https://github.com/phillbaker/terraform-provider-elasticsearch/blob/116c9ff6da0d481881aa687d3e7bb2e03fdcfcd4/es/resource_elasticsearch_index.go) overwrites the `index.ts` which usually does the export of all generated resources. See the [aws](https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/4049dda772d4ef71d950592ec39263890ef994d9/src/index.ts) example how this is supposed to look like.

In the case where a resource is called `index`, we'll have to make sure that we append something like `resource` to the file name.

**Comment by dzirg44** [comment]
Ah, got it! Thank you! Anyway it would be nice if cdktf-cli could handle with it, or just show error. Something like  'this Provider contains index resource, and cannot be properly generated'

**Comment by skorfmann** [comment]
> Ah, got it! Thank you! Anyway it would be nice if cdktf-cli could handle with it, or just show error. Something like 'this Provider contains index resource, and cannot be properly generated'

Sorry, I should have been clearer. You're absolutely right, that's something we'll fix in cdktf.
