### ISSUE TITLE
Build a Vagrant Box for Development

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#566]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great to have a [Vagrant](https://www.vagrantup.com/) setup which contains everything we need for development and testing both on Linux and Windows.

The current Docker image works, but it's not a great experience (at least on a Mac).

**Comment by skorfmann** [comment]
At least the local development workflow is probably covered by Codespaces now. Not sure about the state for windows specific issues, did we end up building a solution which works for these kind of issues? //cc @DanielMSchmidt

**Comment by DanielMSchmidt** [comment]
@skorfmann do we want to close this in favor of your dev setup using RDP?
