### ISSUE TITLE
OCI Synth issues "module has already exported a member "

### ISSUE THREAD

**Issue by vbudilov** [hashicorp/terraform-cdk#568]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf = 0.1.0
Terraform v0.14.6

### Affected Resource(s)

OCI

### Expected Behavior

It should synthesize without issues

### Actual Behavior

```
⠋ synthesizing ...
.gen/providers/oci/index.ts:84:1 - error TS2308: Module './database-autonomous-database' has already exported a member named 'DatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.

84 export * from './database-autonomous-database-backup';
   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


.gen/providers/oci/index.ts:415:1 - error TS2308: Module './data-oci-database-autonomous-database' has already exported a member named 'DataOciDatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.

415 export * from './data-oci-database-autonomous-database-backup';
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors.
```

### Steps to Reproduce

1. cdktf init --template="typescript" --local

2. Update cdktf.json by adding OCI:
```
  "terraformProviders": [
    "oci@~> 4.13.0"
  ],
```

3. Update main.ts by importing any OCI class:
```import {CoreVcn} from './.gen/providers/oci';```

4. cdktf get
5. cdktf synth

### Important Factoids

Not sure if it's a TF configuration issue or a CDK issue though

Also the same error is thrown for all of the other languages. 

### References

* #0000

**Comment by jsteinich** [comment]
This is a cdktf issue. Running into a naming conflict.

The `DatabaseAutonomousDatabase` resource has a `backupConfig` property whose type ends up being `DatabaseAutonomousDatabaseBackupConfig`. It also has a `DatabaseAutonomousDatabaseBackup` resource which generates a config interface of type `DatabaseAutonomousDatabaseBackupConfig`. Same problem with corresponding data sources.

I think the only work around would be to manually delete `database-autonomous-database-backup.ts` and `data-oci-database-autonomous-database-backup.ts` after `cdktf get`.

We'll probably want to detect the conflict and rename one of them when necessary since renaming all the type would be a breaking change. This situation could technically happen many other ways unless we did something like #464 proposed.

**Comment by vbudilov** [comment]
Yep that worked, although the additional step is to remove the export declaration from index.ts. Is there anything on the roadmap to address this issue? I usually use Java to write my declarations and this "exclusion" process might be a bit harder with Java (unless it's just a matter of excluding these files during complication in mvn or gradle, for now).

**Comment by vbudilov** [comment]
Update: Java fails at the `cdktf get` phase since it tries to compile the classes as well (while the same command works for a TypeScript project):
```

vbudilov@vbudilov-mac cdk-oci-java % cdktf get
⠸ downloading and generating providers...
⠼ downloading and generating providers...
Error: jsii compilation failed with non-zero exit code: 1
  | [2021-02-18T10:59:39.925] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/oci/index.ts:84:1 - error TS2308: Module './database-autonomous-database' has already exported a member named 'DatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.
  | 84 export * from './database-autonomous-database-backup';
  |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/oci/index.ts:415:1 - error TS2308: Module './data-oci-database-autonomous-database' has already exported a member named 'DataOciDatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.
  | 415 export * from './data-oci-database-autonomous-database-backup';
  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /Users/vbudilov/.nvm/versions/node/v14.15.5/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/bl/6t1t67v11h71mcrh1c02w3840000gn/T/temp-mc8vK9
  +----------------------------------------------------------------------------------
    at newError (/Users/vbudilov/.nvm/versions/node/v14.15.5/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:38:20)
    at ChildProcess.<anonymous> (/Users/vbudilov/.nvm/versions/node/v14.15.5/lib/node_modules/cdktf-cli/node_modules/jsii-srcmak/lib/util.js:55:29)
    at Object.onceWrapper (events.js:422:26)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
jsii compilation failed with non-zero exit code: 1
  | [2021-02-18T10:59:39.925] [ERROR] jsii/compiler - Compilation errors prevented the JSII assembly from being created
  | warning JSII3: There is no "README.md" file. It is required in order to generate valid PyPI (Python) packages.
  | providers/oci/index.ts:84:1 - error TS2308: Module './database-autonomous-database' has already exported a member named 'DatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.
  | 84 export * from './database-autonomous-database-backup';
  |    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  | providers/oci/index.ts:415:1 - error TS2308: Module './data-oci-database-autonomous-database' has already exported a member named 'DataOciDatabaseAutonomousDatabaseBackupConfig'. Consider explicitly re-exporting to resolve the ambiguity.
  | 415 export * from './data-oci-database-autonomous-database-backup';
  |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  +----------------------------------------------------------------------------------
  | Command: /Users/vbudilov/.nvm/versions/node/v14.15.5/lib/node_modules/cdktf-cli/node_modules/jsii/bin/jsii --silence-warnings reserved-word
  | Workdir: /var/folders/bl/6t1t67v11h71mcrh1c02w3840000gn/T/temp-mc8vK9
  +----------------------------------------------------------------------------------
```

**Comment by jlamillan** [comment]
Any workaround for the Java case?

**Comment by jsteinich** [comment]
Technically speaking, you could generate the Typescript bindings, manually fix or delete problem files, invoke jsii to generate java bindings.

Given that the other naming changes aren't yet in-progress we may be able to fix this specific case sooner.
