### ISSUE TITLE
Add "sensitive" argument to TerraformVariable

### ISSUE THREAD

**Issue by rrrix** [hashicorp/terraform-cdk#569]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform 0.14 added `sensitive` to `variable` input variable statements, which allows hiding sensitive data (passwords, keys, etc.) from CLI and other UI output. 

[Input Variables: Suppressing values in CLI output](https://www.terraform.io/docs/language/values/variables.html#suppressing-values-in-cli-output)

It would be great to have something like the exampe below to make sure sensitive data isn't output to a CI server logs or similar places.

```typescript
new cdktf.TerraformVariable(scope, 'dbPassword', {
  type: 'string',
  description: 'PostgreSQL Database Password',
  sensitive: true
});
```

### References

https://blog.gruntwork.io/a-comprehensive-guide-to-managing-secrets-in-your-terraform-code-1d586955ace1

**Comment by skorfmann** [comment]
@dedalusj saw that you were working on a fix for this. Are you still planning to create a PR?
