### ISSUE TITLE
Generate Providers as Submodules

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`cdktf` generates provider classes without namespaces and exports all generated classes and interfaces. Here's an example from the [AWS provider](https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/99b4f9e148cbce91076daf0ad48034971ad9fe44/src/index.ts):

```ts
// src/index.ts

export * from './accessanalyzer-analyzer';
export * from './acm-certificate';
export * from './acm-certificate-validation';
// ... a lot more exports
```
which can be used like the following in Typescript:

```ts
import { AccessanalyzerAnalyzer } from '@cdktf/aws-provider'
const new AccessanalyzerAnalyzer(this, 'foo', {})
```

One major problem with this approach are naming conflicts. If `acm-certificate` and `acm-certificate-validation` would export a type with the same name, the provider wouldn't compile anymore. (see https://github.com/hashicorp/terraform-cdk/issues/568 for a specific occurrence of this)

Another issue which popped up quite frequently recently: In particular for the AWS provider, but potentially for all providers which consist of lots data sources / resources, some intellisense like analziers are not working out of the box due to code size limitations (the AWS provider is a single file with about 20 MB in Python). (see https://github.com/hashicorp/terraform-cdk/issues/464)

#### Submodules 

jsii supports [submodules](https://github.com/aws/jsii/blob/4731aeb6ad85c04160b30232e85e3f8a43c712a6/gh-pages/content/specification/2-type-system.md#submodules), which are essentially Typescript namespaces. The example above could look like this:

```ts
export * as AccessanalyzerAnalyzer from './accessanalyzer-analyzer';
export * as AcmCertificate from './acm-certificate';
export * as AcmCertificateValidation from './acm-certificate-validation';
// ... a lot more exports
```

which can be used like the following in Typescript:

```ts
import { AccessanalyzerAnalyzer } from '@cdktf/aws-provider'

const new AccessanalyzerAnalyzer.AccessanalyzerAnalyzer(this, 'foo', {})
```

I don't particularly like the namespace / name duplication here, but I don't really have a better idea right now. 

The implementation seems to be pretty straightforward, it'll be a breaking change though.

### References

- https://github.com/hashicorp/terraform-cdk/issues/464
- https://github.com/hashicorp/terraform-cdk/issues/568

**Comment by skorfmann** [comment]
> I don't particularly like the namespace / name duplication here, but I don't really have a better idea right now.

It would be pretty cool to use the common abbreviation / service name for this (e.g. `s3` or `ec2` in AWS, not sure how this would look like for other providers)

**Comment by skorfmann** [comment]
> > I don't particularly like the namespace / name duplication here, but I don't really have a better idea right now.
> 
> It would be pretty cool to use the common abbreviation / service name for this (e.g. `s3` or `ec2` in AWS, not sure how this would look like for other providers)

Perhaps we could extract this information from the provider [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs). There is this [subcategory](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/d/acm_certificate.html.markdown) attribute for each of the resources. This would make the implementation a bit more difficult, since we'd have to process the docs and implement the namespaces directly in the generated code, where one namespace would span multiple files. That's [possible to do](https://www.typescriptlang.org/docs/handbook/namespaces.html#splitting-across-files) in Typescript and supported in jsii.

Not exactly sure how the implementation would look like. Using it, would probably look like this:

```ts
import { acm } from '@cdktf/aws-provider'

const new acm.AcmCertificate(this, 'foo', {})
```

**Comment by vbudilov** [comment]
AWS's CloudFormation-based CDK does just that so it'll be in line with that approach.

**Comment by skorfmann** [comment]
> AWS's CloudFormation-based CDK does just that so it'll be in line with that approach.

Yes! Will have a more detailed look there as well 👍 

> P.S. I'll be able to create a sample project (or projects) for OCI) once I can compile the code :))

That would be pretty neat :)

**Comment by skorfmann** [comment]
Was playing around with jsii, I had to explicitly declare the namespace

```
export declare namespace Foo {
// ...
}
```

Which resulted in separately rendered files per namespace - which I believe will be pretty good for Python and potentially other languages in terms of filesize.

**Comment by skorfmann** [comment]
Here's the [list of subcategories](https://github.com/hashicorp/terraform-provider-aws/blob/92f626a8c401d89c1fbc334f064373684c26e281/website/allowed-subcategories.txt) by the example of the AWS provider.

So let's take the ACM category as an example:

```
export namespace ACM {
  export class Certificate {
  }
  export class CertificateValidation {
  }

  export namespace Data {
    export class Certificate {}
  }
}
```
This looks like something we could generate, and it seems to be reasonable at a first sight. This would result in a dedicated `acm` file for Python when generated through jsii. So, at least in terms of file sizes, this would help certainly.

Let's look how intellisense handles this:

![Screenshot 2021-07-02 at 09 41 32](https://user-images.githubusercontent.com/136789/124239779-582e6400-db1a-11eb-9c7c-626ab4a0cfcf.png)

In contrast to the current AWS provider:

![Screenshot 2021-07-02 at 09 43 28](https://user-images.githubusercontent.com/136789/124239840-68deda00-db1a-11eb-85b8-964a0b918deb.png)

While we gain more structure, we'd loose the "full text" resource search we have right now. Probably an acceptable tradeoff -thoughts?

**Comment by ansgarm** [comment]
As the "full text" search breaks for some IDEs / languages, I think using namespaces would be an improvement 👍
Is it possible to add docstrings to namespaces that get displayed in intellisense?
E.g. `ACM` -> ` AWS Certificate Manager: Easily provision, manage, and deploy public and private SSL/TLS certificates for use with AWS services and your internal connected resources`

**Comment by skorfmann** [comment]
Good idea and seems to work 
![Screenshot 2021-07-02 at 14 14 06](https://user-images.githubusercontent.com/136789/124273070-dc471280-db3f-11eb-9522-6419f9046fd3.png)

**Comment by skorfmann** [comment]
>> Is it possible to add docstrings to namespaces that get displayed in intellisense?
>> E.g. `ACM` -> ` AWS Certificate Manager: Easily provision, manage, and deploy public and private SSL/TLS certificates for use with AWS services and your internal connected resources`

>Good idea and seems to work

Besides the fact, that there isn't any documentation on this level - and no linkable website either. Perhaps we could maintain a service description mapping for a selection of providers?

**Comment by ansgarm** [comment]
Jup, maybe that's something that could come in handy – some way to have a short description for those subcategories per terraform provider.

**Comment by jsteinich** [comment]
Managing those lists by hand is a bit unfortunate, but given that switching namespaces is a breaking change, probably best to be more controlled than some automated grouping.
