### ISSUE TITLE
Invalid cdktf-cli commands produce no output (no error or help) and exit code 0

### ISSUE THREAD

**Issue by rrrix** [hashicorp/terraform-cdk#573]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Running invalid `cdktf-cli` commands produces no output and the CLI exits with `0` (meaning, "OK" in *nix land). 

I don't think this is a _bug_ per-se because... maybe it's intentional?

```
$ cdktf read-my-mind ; echo $?
0
```

I expected:
* "Invalid command" error message (or similar)
* Print `cdktf --help` output if an invalid command is given
* Exit with a non-zero exit code

### References

The Linux Documentation Project, Advanced Bash-Scripting Guide, Appendix E: Appendix E. Exit Codes With Special Meanings: https://tldp.org/LDP/abs/html/exitcodes.html

**Comment by ansgarm** [comment]
Closed by #680
