### ISSUE TITLE
No way to utilize Terraform builtin functions?

### ISSUE THREAD

**Issue by kyleroot** [hashicorp/terraform-cdk#577]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf 0.1.0
Python bindings

### Affected Resource(s)

I don't see a way to use the Terraform builtin functions via cdktf. In particular I want to take the `substr` of the combined output of some string combined with the output of `random_string`. I can't take the substring from within Python because the value of the `random_string` result will only be know at Terraform runtime.

In my original Terraform version I used a local. However I do not see a way to represent Terraform builtin functions as constructs, so I cannot assign this value the expression parameter of TerraformLocal.

### Debug Output

```
locals {
  project_id = substr(join("-", [var.project_name, random_string.random_affix,result]), 0, 48)
}
```

^ This is an example of what I'm asking about. Since I won't know the value of random_affix, how can truncate that value after the fact without using a builtin?

### Expected Behavior

I expected there would a construct I could import to represent the builtin functions (like `substr` or `join`).

### References

* #0000

**Comment by skorfmann** [comment]
@kyleroot yes, we don't have abstracted functions yet (see https://github.com/hashicorp/terraform-cdk/issues/220). You could fallback to use [escape hatches](https://cdk.tf/escape-hatch). 

> . I can't take the substring from within Python because the value of the `random_string` result will only be know at Terraform runtime.

Couldn't you replace `random_string` by some random string generator in Python?

> This is an example of what I'm asking about. Since I won't know the value of random_affix, how can truncate that value after the fact without using a builtin?

You could use the `fqn` method of the resource object to get the name. Theres also a `TerraformLocal` class to represent locals.

**Comment by kyleroot** [comment]
@skorfmann 

Thanks so much for your fast reply! Escape hatches it is then.

> Couldn't you replace random_string by some random string generator in Python?

The `random_string` resource has the benefit of only ever generating a random string when the resource is first created and then that value is persisted into the tfstate doesn't change after. I have always used this technique to generate unique-but-persistent tags for tracking resources (using AWS ResourceGroups, Kubernetes annotations, etc)

**Comment by skorfmann** [comment]
> The `random_string` resource has the benefit of only ever generating a random string when the resource is first created and then that value is persisted into the tfstate doesn't change after. I have always used this technique to generate unique-but-persistent tags for tracking resources (using AWS ResourceGroups, Kubernetes annotations, etc)

Oh, of course - that makes a lot of sense :) Thanks for elaborating on this 👍

**Comment by johnjelinek** [comment]
@kyleroot: how did you use the escape hatch here? I have the same desire to use something like `random_string`, except it will be one time tokens generated from shelling out to a docker container. Once those get into the state, I don't want them to ever run again.

I thought maybe something like this would work:
```clojure
(let [app (App.)
      stack (TerraformStack. app "stack")
      null-resource (Resource. stack "otp-secret" (clj->js {:triggers
                                                            {"secret" (-> "docker run --rm tootsuite/mastodon:v3.3.0 rake secret"
                                                                          execSync .toString trim)}}))]
  (.-triggers null-resource))
;; => "${null_resource.stack_otpsecret_7E9329FC.triggers}"
```

but it seems like this ends up getting generated on every run. In addition, I don't know how to get the exported value from the triggers:
```
Error: Invalid template interpolation value

  on cdk.tf.json line 554, in resource.docker_container.sidekiq.env:
 554:           "OTP_SECRET=${null_resource.stack_otpsecret_7E9329FC.triggers}",
    |----------------
    | null_resource.stack_otpsecret_7E9329FC.triggers is map of string with 1 element

Cannot include the given value in a string template: string required.
```

It's not a typescript map, so I can't fetch it the normal way. How should I get the key from this map?

**Comment by johnjelinek** [comment]
At this point, I'm thinking maybe these type of generated secrets should prolly go into some secret store and then reference it that way. But, I was hoping to skip that at this point.

**Comment by jsteinich** [comment]
You'll need to construct the reference by hand. Something along the lines of:
```typescript
OTP_SECRET=`\${${stack_otpsecret.fqn}.triggers.secret}`
```

**Comment by johnjelinek** [comment]
ahhh yes, perfect! thank you @jsteinich:
```clojure
(replace (.-triggers null-resource) "}" ".secret}")
```

Now, my original need remains -- how do I get it to trigger this null-resource only once (like `random_string`) and then use the same value for subsequent `cdktf deploy`s?

**Comment by jsteinich** [comment]
@johnjelinek you might want to use a local-exec provisioner within your null resources using a fixed (or perhaps some hash of the docker image) trigger to get the one time property.

**Comment by johnjelinek** [comment]
But how would I store the value then? Maybe with something like locals?

**Comment by jsteinich** [comment]
Looks like you could use https://github.com/matti/terraform-shell-resource, but you might be better off storing the secret separately.

**Comment by johnjelinek** [comment]
Oh, I can use those with the CDK?

**Comment by jsteinich** [comment]
> Oh, I can use those with the CDK?

Yeah, registry modules have been supported from the start in [cdktf.json](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/cdktf-json.md). Non-registry module support was just added in the latest release.

**Comment by skorfmann** [comment]
Functions were introduced in `0.6` - see https://github.com/hashicorp/terraform-cdk/blob/8e83c6703ed6f5615898b1c4f6c4e5b06ee7445a/docs/working-with-cdk-for-terraform/terraform-functions.md
