### ISSUE TITLE
add "update" option to cdktf get

### ISSUE THREAD

**Issue by trondhindenes** [hashicorp/terraform-cdk#578]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently `cdktf get` wipes the "imports" directory, and re-downloads everything. It would be good if it instead would only get needed packages (and version updates). It might make sense to still allow a complete "wipe-and-download" option, for example by adding a `-force` parameter or similar.

**Comment by rrrix** [comment]
@trondhindenes I'm curious, would you mind explaining why having the `cdktf.json` terraform providers and modules  _not_ match the `imports` (for python) or `.gen` (for typescript) directory? 

For me I actually expect (and want) to make sure that if I remove a provider or a module from `cdktf.json` that the generated files reflect that change.

**Comment by trondhindenes** [comment]
Sorry, I should have explained better:
The behavoir today is: reglardless of the module versions specified in cdktf.json matching or not maching whatever's installed in the `imports` directory, the contents of `imports` gets wiped every time `cdktf get` is run. I wish cdktf was more smarter so that it only performed the "wipe/update" if needed.

use case: we have a simple test harness that (among other things) will run "cdktf synth", load the generated json and assert a bunch of attributes in it. This test script takes a lot of time to run, since it runs "cdktf get". Of course, we could "manually" check the "imports" folder, and only run "cdktf get" if that folder was empty or something, but my point is that it would be good if such functionality was covered by cdktf instead of us having to write custom scripts to do that.

The same thing with "environment setup" instructions:
Today we have to ask developers to "run cdktf get but only on the first time you're setting up the dev env or if the module versions in cdktf.json have changed". Again, my point was that it would be better if cdktf itself was smarter about this.

**Comment by abaki007** [comment]
The behaviour of `cdktf get` is compounded on a secondary language like python where the packages need to be built after the initial download.

This enhancement will bring `cdktf get` behaviour in line with `terraform get` - having that common behaviour makes sense as they fulfil the same purpose (https://www.terraform.io/docs/cli/commands/get.html).

**Comment by ansgarm** [comment]
I think this can be closed as of https://github.com/hashicorp/terraform-cdk/pull/2266

**Comment by DanielMSchmidt** [comment]
Yes, can be closed
