### ISSUE TITLE
Terraform block not generated when using callbacks

### ISSUE THREAD

**Issue by itsnagaraj** [hashicorp/terraform-cdk#579]
I am using swagger parser library to parse the swagger specification for API and would like to generate terraform code for ApiGatewayMethodSettings. The swagger parser takes in callback which is called after the file is parsed successfully. I have tried using await in the callback method but to no luck. I can see that log lines are printed but the JSON file that is generated does not have the method settings block

```
  private apiGatewayMethodSettings(restApiId: string, apiEndpoints: string[]): void {
    apiEndpoints.forEach(value => {
      console.log('id -> test-api' + value.toLowerCase().replace(/\//g, '\-'));
      console.log('method -> ' + value);
      new ApiGatewayMethodSettings(this, 'test-api-' + value.toLowerCase().replace('/', '-'), {
        restApiId: restApiId,
        stageName: 'xxxx',
        methodPath: value,
        settings: [
          {
            throttlingBurstLimit: 20,
            throttlingRateLimit: 100
          }
        ]
      });
    });
  }

// @ts-ignore
    SwaggerParser.parse('swagger.yml', async (err, spec) => {
      if (err) {
        console.log(err);
        throw err;
      }

      Object.entries(spec.paths).forEach(([pathKey, path]) => {
        // @ts-ignore
        Object.entries(path).forEach(([operationKey, operation]) => {
          apiEndpoints.push(pathKey + "/" + operationKey.toUpperCase());
          console.log(pathKey + "/" + operationKey.toUpperCase());
        });
      });

      await this.apiGatewayMethodSettings(restApi.id, apiEndpoints);
    });
```

**Comment by skorfmann** [comment]
That's a pretty interesting use-case, thanks for creating this issue.

> The swagger parser takes in callback which is called after the file is parsed successfully. I have tried using await in the callback method but to no luck. I can see that log lines are printed but the JSON file that is generated does not have the method settings block

Where / how are you calling `SwaggerParse.parse`? Is the `ApiGatewayMethodSettings` construct part of a `TerraformStack` / `App`?

**Comment by itsnagaraj** [comment]
@skorfmann SwaggerParser.parse is called in the constructor and yes the ApiGatewayMethodSettings construct part of a TerraformStack / App.

Full code below for reference

`class ApiGatewayStack extends TerraformStack {

  constructor(scope: Construct, name: string) {
    super(scope, name);

    new AwsProvider(this, 'aws', {
      region: 'ap-southeast-2',
    });

    this.synthesizeApiGateway().then(() => console.log('Completed'));
  }

  async synthesizeApiGateway(): Promise<void> {

    let apiSpec = readFileSync('swagger.yml', {encoding: 'utf8'});
    let restApiPolicy = readFileSync('api-resource-policy-nonprod.json', {encoding: 'utf8'});

    const restApi = new ApiGatewayRestApi(this, "rest-api", {
      name: 'api',
      body: apiSpec,
      policy: JSON.stringify(restApiPolicy)
    });

    const apiDeployment = new ApiGatewayDeployment(this, 'rest-api-deployment', {
      restApiId: restApi.id,
      triggers: {
        redeployment: createHash('sha256').update(JSON.stringify(apiSpec)).digest('hex')
      },
      dependsOn: [restApi]
    });

    new ApiGatewayStage(this, 'api-deployment-stage', {
      restApiId: restApi.id,
      deploymentId: apiDeployment.id,
      stageName: 'test'
    });

    let api = await SwaggerParser.parse('swagger.yml');
    Object.entries(api.paths).forEach(([pathKey, path]) => {
      // @ts-ignore
      Object.entries(path).forEach(([operationKey, operation]) => {
        let methodPath = pathKey + "/" + operationKey.toUpperCase();
        let id = 'api' + methodPath.toLowerCase().replace(/\//g, '\-');
        console.log("method path -> " + methodPath + " id -> " + id);

        new ApiGatewayMethodSettings(this, id, {
          restApiId: restApi.id,
          stageName: 'DEV02',
          methodPath: methodPath,
          count: 1,
          settings: [
            {
              throttlingBurstLimit: 500,
              throttlingRateLimit: 1000
            }
          ]
        })
      });
    });
  }
}

const app = new App();
new ApiGatewayStack(app, 'apigateway');
app.synth();
`

**Comment by adriano-kaiser** [comment]
I also ran into this issue. Basically you are trying to use async in a constructor, which is not allowed.
Its a bit unfortunate everything is being configured in a "giant" constructor. 

The way I circumvented the issue was: I extracted my async calls prior to the CDK Constructor and passed the async results as constructor arguments:

```
class MyStack extends TerraformStack {
  constructor(scope: Construct, name, config) {
    super(scope, name);


    const restApi = new ApiGatewayRestApi(this, 'rest-ap', {
      name: 'api',
      policy: config.restApiPolicy
    });

  }
}

(async () => {
  try {
    let config = await GetStuff();
    const cdktf = new MyStack(app, 'typescript-az', config);
  } catch (error) {
    console.log(error);
  }
  app.synth();
})();

```

**Comment by itsnagaraj** [comment]
@adriano-kaiser the seems to have done the trick. thank you very much for your help.
