### ISSUE TITLE
AzureRM Provider Issue

### ISSUE THREAD

**Issue by rahejaps** [hashicorp/terraform-cdk#581]
I have terraform provider in the `cdk.tf.json` as` "terraformProviders": ["azurerm@~> 2.0"]`, running the `cdktf synth` generates the `cdk.tf.out` file with the provider version as `undefined`
```
"terraform": {
    "required_providers": {
      "azurerm": {
        "version": "undefined",
        "source": "azurerm"
      }
    }
  },
```

**Comment by jsteinich** [comment]
I just tried with both Typescript and Python and the version was populated correctly.
Do you have any other references to `azurerm` in your `cdktf.json`?

**Comment by rahejaps** [comment]
This is complete cdktf.json
```
{
  "language": "python",
  "app": "python3 ./main.py",
  "terraformProviders": ["azurerm@~> 2.0"],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
  
}
```

**Comment by jsteinich** [comment]
Maybe try running `cdktf get` again. If that doesn't work trying enabling debug logging ( `$Env:CDKTF_LOG_LEVEL='DEBUG'` in PS) so we can look for more information.

**Comment by rahejaps** [comment]
cdktf get did the trick.
