### ISSUE TITLE
cdktf errors when module generates warnings

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-cdk#582]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.10
python: 3.7.3
terraform: 0.14.7

### Affected Resource(s)

terraform-google-modules/network/google@3.1.1

### Debug Output

https://gist.github.com/alexjmoore/45bc000eb62a1add1b5214247704e843

### Expected Behavior

When the referenced module generates warnings it should surface these to the user, although I see other issues for better error surfacing, but in this case specifically it shouldn't hard fail at a minimum.

### Actual Behavior

It seems like the warning being generated is causing it to fail - but this is my assumption - see gist referenced above.

### Steps to Reproduce

Use the terraform-google-modules/network/google@3.1.1 - there is a bug in this specific version (latest at the time of writing, but worth pinning to reproduce as there is a pending fix incoming) that generates this warning in typical terraform use:

```
Warning: Interpolation-only expressions are deprecated

  on .terraform/modules/vpc/modules/firewall-rules/main.tf line 18, in resource "google_compute_firewall" "rules":
  18:   for_each                = { for r in var.rules : "${r.name}" => r }
```

If you pin an earlier version of the module like terraform-google-modules/network/google@3.0.0 which doesn't exhibit the warning, then the issue does not occur.

Example python snippet to test:
```
        Network(self, "vpc-test",\
            network_name="vpc-test",
            project_id="<project_id>",
            auto_create_subnetworks=False,
            subnets=[{
                "subnet_name":"sn-test",
                "subnet_ip":"10.0.0.0/24",
                "subnet_region":"europe-west2",
            }]
        )
```

* #0000

**Comment by jsteinich** [comment]
@alexjmoore would you be able to provide the output from running `terraform plan` directly? I'm thinking it's getting tripped up some resource within the module rather than the warning, but I don't currently have access to a GCP account to test.

**Comment by alexjmoore** [comment]
Sure, here is the plan I'm testing with:

https://gist.github.com/alexjmoore/ceb26f76f52653a17b520000f050f563

However, re-running I notice it does actually deploy all the resources, it seems to error at the very end of the deployment, if I manually run the terraform apply it works without anything that looks unusual, this is the output post the plan output from a manual `terraform apply`:

```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.vpc-testa.module.vpc.google_compute_network.network: Creating...
module.vpc-testb.module.vpc.google_compute_network.network: Creating...
module.vpc-testa.module.vpc.google_compute_network.network: Still creating... [10s elapsed]
module.vpc-testb.module.vpc.google_compute_network.network: Still creating... [10s elapsed]
module.vpc-testb.module.vpc.google_compute_network.network: Creation complete after 12s [id=projects/testproject/global/networks/vpc-testb]
google_compute_ha_vpn_gateway.vgw-testb: Creating...
module.vpc-testb.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testb"]: Creating...
google_compute_firewall.fw-testb-allow-all-from-testa: Creating...
module.vpc-testa.module.vpc.google_compute_network.network: Creation complete after 12s [id=projects/testproject/global/networks/vpc-testa]
google_compute_ha_vpn_gateway.vgw-testa: Creating...
module.vpc-testa.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testa"]: Creating...
google_compute_firewall.fw-testa-allow-iap: Creating...
google_compute_firewall.fw-testa-allow-all-internal: Creating...
google_compute_ha_vpn_gateway.vgw-testb: Still creating... [10s elapsed]
module.vpc-testb.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testb"]: Still creating... [10s elapsed]
google_compute_firewall.fw-testb-allow-all-from-testa: Still creating... [10s elapsed]
google_compute_ha_vpn_gateway.vgw-testa: Still creating... [10s elapsed]
module.vpc-testa.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testa"]: Still creating... [10s elapsed]
google_compute_firewall.fw-testa-allow-iap: Still creating... [10s elapsed]
google_compute_firewall.fw-testa-allow-all-internal: Still creating... [10s elapsed]
google_compute_firewall.fw-testa-allow-iap: Creation complete after 11s [id=projects/testproject/global/firewalls/fw-testa-allow-iap]
google_compute_firewall.fw-testa-allow-all-internal: Creation complete after 11s [id=projects/testproject/global/firewalls/fw-testa-allow-all-internal]
google_compute_firewall.fw-testb-allow-all-from-testa: Creation complete after 11s [id=projects/testproject/global/firewalls/fw-testb-allow-all-from-testa]
google_compute_ha_vpn_gateway.vgw-testb: Creation complete after 11s [id=projects/testproject/regions/europe-west2/vpnGateways/vgw-testb]
google_compute_ha_vpn_gateway.vgw-testa: Creation complete after 11s [id=projects/testproject/regions/europe-west2/vpnGateways/vgw-testa]
module.vpc-testb.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testb"]: Creation complete after 12s [id=projects/testproject/regions/europe-west2/subnetworks/sn-testb]
module.vpc-testa.module.subnets.google_compute_subnetwork.subnetwork["europe-west2/sn-testa"]: Creation complete after 12s [id=projects/testproject/regions/europe-west2/subnetworks/sn-testa]

Apply complete! Resources: 9 added, 0 changed, 0 destroyed.
```

**Comment by alexjmoore** [comment]
If it helps, I also see a similar error on destroy - again the destroy completes prior to it posting the same `[2021-03-01T21:50:59.284] [ERROR] default - TypeError: Cannot read property 'startsWith' of undefined`

**Comment by jsteinich** [comment]
@alexjmoore thanks for the additional info.
Does `cdktf diff` also give you the same error?

**Comment by alexjmoore** [comment]
No, runs clean, both with no changes and a change:
```
alexmoore@penguin ~/src/cdktf-playpen (master) > cdktf diff
Stack: cdktf-playpen

Diff: 0 to create, 0 to update, 0 to delete.
alexmoore@penguin ~/src/cdktf-playpen (master) > cdktf diff
Stack: cdktf-playpen
Resources
 - GOOGLE_COMPUTE_HA_VP vgw-testb           google_compute_ha_vpn_gateway.vgw-testb

Diff: 0 to create, 0 to update, 1 to delete.
alexmoore@penguin ~/src/cdktf-playpen (master) > 
```

**Comment by jsteinich** [comment]
I was able to get access to a test account and it turns out the warning is the cause; I had just missed that code path when looking before.
