### ISSUE TITLE
Clarify correct use of module outputs in documentation

### ISSUE THREAD

**Issue by alexjmoore** [hashicorp/terraform-cdk#583]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I might have missed it, but I can't find any clear docs around how to reference module outputs, to the point where I almost submitted a bug as I was simply referencing parameters set in a module and I could see it was synthing a string rather than a reference (and so causing me dependency issues - or lack of). 

However, now my understanding is that you would do something like (in python):

`modulevarname.paramname_output`

i.e. add `_output` to the parameter name that the module is outputting?  a) is that correct? (as I think it is from testing and digging around the generated module python code) and b) could some guidance on this point be added to the `[using-providers-and-modules.md](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md)`

If I am completely doing it wrong, it would be also good to know :-)

Thanks!

**Comment by jsteinich** [comment]
> i.e. add `_output` to the parameter name that the module is outputting?

This is correct for python. For other languages it is
```typescript
`${toCamelCase(output.name)}Output`
```
