### ISSUE TITLE
Documentation on how CDK would work with Terraform Enterprise Cloud.

### ISSUE THREAD

**Issue by mikhail-khodorovskiy** [hashicorp/terraform-cdk#586]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there a recommendation on how to use terraform CDK with Terraform Enterprise cloud?

**Comment by skorfmann** [comment]
@mikhail-khodorovskiy that's a great question and you're absolutely right, that this area isn't documented well yet. 

When you're aiming for a direct VCS triggered execution of your, there isn't a direct for support for this. You'd need some sort of pre processing step somewhere else, which turns your cdktf app into JSON. This direct integration is something which is on our radar, though. 

We do support deploying directly via Terraform Cloud using the `cdktf` cli. It's essentially a similar configuration as described [here](https://github.com/hashicorp/terraform-cdk/blob/ad213c1937ccb4e55deaf0b9e554fa7023f8d974/docs/working-with-cdk-for-terraform/remote-backend.md#terraform-remote-backend), with the only difference that the cloud workspace has to be marked for `remote` execution.
