### ISSUE TITLE
cdktf unable to parse modules without newlines at EOF

### ISSUE THREAD

**Issue by celliott** [hashicorp/terraform-cdk#595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

using `typescript@4.2.3` and `cdktf 0.2.0`

### Affected Resource(s)

cdktf importing of custom modules

### Debug Output

i'm using the new module improvements from #584 to source modules locally and from github. It is works as expected unless a module's variables and/or outputs tf files do not have a newline at EOF. cdktf fails to parse those modules. Add a newline to EOF for suspect files and then cdktf will successful parse and import the module.

[error gist](https://gist.github.com/celliott/9be823e114e6ab9a32c7de91102b0f8d)

**example terraformModules**

```
"terraformModules": [
  {
    "name": "s3",
    "source": "git@github.com:mycompany/terraform-aws-s3.git"
  }
],
```

### Expected Behavior

I would expect to be able to import a module that works without error when using tarraform directly. It's easy to fix but it wasn't clear at first what the issue was. If there is no fix, then better documentation and error messaging would help.

### Actual Behavior

A source a custom tf module with the improved module importing and any module that doesn;t have new lines at EOF fail to parse. I have tested with both local or github sourced modules and as expected, the behavior is the same.

### Steps to Reproduce

Source a module from local or github using `terraformModules` in `cdktf.sjon`. Make sure that the file containing either `outputs` or `variables` does NOT have a newline at EOF. Run `cdktf get` and the module with fail to import. Add a newline to the end of the file(s), reimport and it will work as expected.

**Comment by jsteinich** [comment]
I'm having some trouble reproducing this issue. @celliott are you able to provide a simple module which reproduces this? Also what version of terraform are you using?

**Comment by jsteinich** [comment]
I have a thought as to what is causing this. Likely same issue as https://github.com/xchapter7x/clarity/issues/23#ref-commit-4676776 since file contents are also concatenated here.

**Comment by celliott** [comment]
@jsteinich I am using `Terraform v0.14.6`. I don't have an example that I can share but I can create one if you need. I can show you the fix that resolved my issue. No newline after a variable or output causes the issue. I haven't rechecked with `cdktf 0.2.1`. 

<img width="694" alt="Screen Shot 2021-04-14 at 6 25 52 PM" src="https://user-images.githubusercontent.com/1156432/114800746-20035a80-9d4f-11eb-9625-68491ced7e8e.png">

**Comment by celliott** [comment]
@jsteinich I updated repo with an example and added a cdktf.json. I am using `cdktf 0.2.1`. I hope this helps.

```
$ git clone git@github.com:celliott/tf-example.git
$ cd tf-example
$ cdktf get
Error: parse config: [hcl2json.tf:93,2-11: Missing newline after block definition; A block definition must end with a newline.]
    at cb (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/index.js:48:63)
    at syscall/js.valueInvoke (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/wasm_exec.js:190:48)
    at wasm-function[1489]:0x1517da
    at wasm-function[1472]:0x14fa33
    at wasm-function[3109]:0x3f0f9a
    at wasm-function[977]:0xd73a3
    at wasm-function[976]:0xd7384
    at Go._resume (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/wasm_exec.js:276:36)
    at /usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/wasm_exec.js:447:18
    at run (/usr/local/lib/node_modules/cdktf-cli/node_modules/@cdktf/hcl2json/lib/index.js:50:37)
⠙ downloading and generating modules and providers...
parse config: [hcl2json.tf:93,2-11: Missing newline after block definition; A block definition must end with a newline.]
```

**Comment by jsteinich** [comment]
Thanks for the update. I believe that I've found the root cause and have a PR open to address.
