### ISSUE TITLE
Python template is broken out of the box

### ISSUE THREAD

**Issue by lightningboltemoji** [hashicorp/terraform-cdk#603]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

* cdktf-cli@0.2.0
* cdktf@0.2.0 (Python)
* Python 3.9.1

### Affected Resource(s)

cdktf-cli's `python`  template

### Expected Behavior

After creating a new Python CDK project, user is prompted on next steps (as with other templates)
```
$ cdktf get
ERROR: Please specify providers or modules in "cdktf.json" config file
```

### Actual Behavior

```
$ cdktf get
⠋ downloading and generating modules and providers...

Error: Module not found

The module address "app" could not be resolved.

If you intended this as a path relative to the current module, use "./app"
instead. The "./" prefix indicates that the address is a relative filesystem
path.


Error: Module not found

The module address "app" could not be resolved.

If you intended this as a path relative to the current module, use "./app"
instead. The "./" prefix indicates that the address is a relative filesystem
path.
Error: non-zero exit code 1
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cdktf-cli/lib/util.js:74:27)
    at Object.onceWrapper (node:events:434:26)
    at ChildProcess.emit (node:events:327:20)
    at maybeClose (node:internal/child_process:1055:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
⠋ downloading and generating modules and providers...
non-zero exit code 1
```

### Steps to Reproduce

```bash
$ cdktf --version
0.2.0
$ mkdir tmp && cd tmp
$ cdktf init --template python --project-name gh-report --project-description=. --local
$ cdktf get
<output above>
```

### Important Factoids

Using the typescript provider as a reference for intended behavior:

```bash
$ cdktf --version
0.2.0
$ mkdir tmp && cd tmp
$ cdktf init --template typescript --project-name gh-report --project-description=. --local
$ cdktf get
ERROR: Please specify providers or modules in "cdktf.json" config file
```

**Comment by lightningboltemoji** [comment]
I'll open a PR for this

**Comment by skorfmann** [comment]
Thanks for the issue and the fix 👍  Just merged https://github.com/hashicorp/terraform-cdk/pull/604
