### ISSUE TITLE
Options generated as required even when they have a default function

### ISSUE THREAD

**Issue by ghost** [hashicorp/terraform-cdk#609]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

I'm running `next` with the TypeScript bindings.

### Affected Resource(s)

Any resources with `Required` attributes that also provide a `DefaultFunc` option.

### Debug Output

https://gist.github.com/calavera-twilio/b2bd7b4bc34e419e8ca5cc38f8dd39a0

### Expected Behavior

Configuration attributes might be required but provide a default function that gets evaluated to fetch the value if the user doesn't provide one. Terraform allows you to not set the attribute in those cases, which makes them basically optional. In my case, I'm using the PagerDuty definitions, and the provider's token is one of those attributes. See [the code in their repository](https://github.com/PagerDuty/terraform-provider-pagerduty/blob/master/pagerduty/provider.go#L23-L27)

I can declare that provider without specifying the attribute in an HCL definition like this:

```
provider "pagerduty" {
}
```

Terraform will use the default function to fetch the value for the token attribute, and will fail only, and only if, the result of the function is null.

I would expect that any bindings provided by the CDK act in the same way. 

### Actual Behavior

When the CDK generates the bindings for the provider, the configuration option is required, forcing you to set some value. Otherwise `cdkft synth` fails with an error.

In my case, I'm forced to write the provider definition this way:

```ts
new PagerdutyProvider(this, "infra-containers", {
      token: process.env.PAGERDUTY_TOKEN || ""
    });
```

Otherwise, I get this error:

```
main.ts:61:53 - error TS2345: Argument of type '{}' is not assignable to parameter of type 'PagerdutyProviderConfig'.
  Property 'token' is missing in type '{}' but required in type 'PagerdutyProviderConfig'.

61     new PagerdutyProvider(this, "infra-containers", {});
                                                       ~~

  .gen/providers/pagerduty/pagerduty-provider.ts:11:12
    11   readonly token: string;
                  ~~~~~
    'token' is declared here.
```

### Steps to Reproduce

1. add the `PagerDuty/pagerduty@1.9.5` provider to cdktf.json
2. add `new PagerdutyProvider(this, "infra-containers", {})` to your task.
3. run `cdktf synth`

**Comment by jsteinich** [comment]
The json schema for the provider output from terraform has `token` listed as a required property with no mention of the default function which will make this trickier to solve. Maybe Terraform core could be modified to output that information, but likely will need to resort to modifying the code generation with custom exceptions.

**Comment by DanielMSchmidt** [comment]
This seems like a problem in the upstream provider schema, would close it here and if it is still the case we should create an upstream issue in the pagerduty provider

**Comment by jsteinich** [comment]
@DanielMSchmidt I found a couple upstream issues related to this: https://github.com/hashicorp/terraform/issues/28657 and https://github.com/hashicorp/terraform/issues/28735. Are you able to check with the SDK team to see if any better integration may be possible in the future?

**Comment by vincentbernat** [comment]
This also happens with this provider: https://github.com/hetznercloud/terraform-provider-hcloud/blob/main/hcloud/provider.go#L46-L59. There is a default function and despite that, the generated interface makes it mandatory:

```typescript
export interface HcloudProviderConfig {
    /**
    * Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/hcloud#endpoint HcloudProvider#endpoint}
    */
    readonly endpoint?: string;
    /**
    * Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/hcloud#poll_interval HcloudProvider#poll_interval}
    */
    readonly pollInterval?: string;
    /**
    * The API token to access the Hetzner cloud.
    *
    * Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/hcloud#token HcloudProvider#token}
    */
    readonly token: string;
    /**
    * Alias name
    *
    * Docs at Terraform Registry: {@link https://www.terraform.io/docs/providers/hcloud#alias HcloudProvider#alias}
    */
    readonly alias?: string;
}
```
