### ISSUE TITLE
from imports.aws import Instance, AwsProvider

### ISSUE THREAD

**Issue by evanerwee** [hashicorp/terraform-cdk#612]
I always get:

File "main.py", line 4, in <module>
    from imports.aws import Instance, AwsProvider

non of the examples work

What step am I missing?

#!/usr/bin/env python
from constructs import Construct
from cdktf import App, TerraformStack
from imports.aws import Instance, AwsProvider

class MyStack(TerraformStack):
  def __init__(self, scope: Construct, ns: str):
    super().__init__(scope, ns)

    AwsProvider(self, 'Aws', region='us-east-1')
    Instance(self, "hello", ami="ami-2757f631", instance_type="t2.micro")

app = App()
MyStack(app, "hello-terraform")

app.synth()

**Comment by jsteinich** [comment]
Have you ran `cdktf get`? Most of the examples are relying on provider bindings being generated locally.

**Comment by ab015zt** [comment]
As @jsteinich mentioned you need to run `cdktf get` inside the working directory to install all the provider modules (aws in your case). A folder called `imports` will then be added which will contain the modules needed.

**Comment by drewmullen** [comment]
I had to manually add "aws" to the `terraformProviders` list in cdktf.json before `cdktf get` would work. works as expected after that. Unless I'm missing something, IMO the docs should be update to reflect this nuance

here is my cdktf.json in case it helps anyone:
```
{
  "language": "python",
  "app": "pipenv run python main.py",
  "terraformProviders": ["aws"],
  "terraformModules": [],
  "codeMakerOutput": "imports",
  "context": {
    "excludeStackIdFromLogicalIds": "true",
"allowSepCharsInLogicalIds": "true"
  }
}
```

**Comment by ab015zt** [comment]
You bring up a good point in that the basic python example [here](https://github.com/hashicorp/terraform-cdk/blob/main/docs/getting-started/python.md) does not have a provider specified in the config by default. 

I used the example [here](https://github.com/hashicorp/terraform-cdk/tree/main/examples/python/aws) instead and it worked great.

**Comment by drewmullen** [comment]
looks like theyre basically doing the same thing:
https://github.com/hashicorp/terraform-cdk/blob/bb9357e12c9ec6a76e2d1c1329441f19d47f6a8d/examples/python/aws/cdktf.json#L4

nice to at least see syntax for version locking :)Though this is a documentation issue, not a bug @skorfmann

**Comment by jsteinich** [comment]
Good catch @drewmullen. The default templates were changed recently to not have any default providers generated, but not all documentation was updated to reflect that.

We could add information about editing `cdktf.json`, but the more common path going forward will be to add a reference to the pre-built provider. For python this would be along the lines of `pip install cdktf-cdktf-provider-aws`

**Comment by miyurusankalpa** [comment]
I just stumbled across this after getting the same error and have already wasted a day to trying to fix it. Also this was [not the first time](https://github.com/hashicorp/consul/issues/7137) that I wasted days trying to fix a issue on a hashicorp product, where the error was in the documentation.

Please update the documentation on time. Thanks.

**Comment by DanielMSchmidt** [comment]
@jsteinich I [created a PR](https://github.com/hashicorp/terraform-cdk/pull/784) with the documentation updates you were looking for. I showcased `cdktf get` way as the default way, because only a small subset of providers are pre-built (plus it's more of an optimisation from my point of view). I made sure to link to the guide that explains pre-built providers and `cdktf get` in depth, so that people find it easily if they have further questions 👍 

@miyurusankalpa Sorry for your bad experience! If you have a few minutes I'd greatly appreciate your review on the PR 😇

**Comment by JQUINONES82** [comment]
Why is this still closed if the issue exists

**Comment by DanielMSchmidt** [comment]
The original issue does not happen anymore, but the the [API changes we introduced in 0.13](https://cdk.tf/0.13) can lead to the same error being thrown. The python import changed to  

```py
from imports.aws.provider import AwsProvider
from imports.aws.instance import Instance
```
