### ISSUE TITLE
Custom Module variable description and default value with special characters will break ts constructs

### ISSUE THREAD

**Issue by celliott** [hashicorp/terraform-cdk#615]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

typescript@4.2.3 and cdktf@0.2.0

### Affected Resource(s)

Custom modules

### Debug Output

```
variable "api_gateway_method_path" {
  type        = string
  default     = "*/*"
  description = "Method path is defined as {resource_path}/{http_method} for single method override, or */* for overriding all methods in the stage."
}
```

converts into broken ts

```ts
  /**
   * Method path is defined as {resource_path}/{http_method} for single method override, or */* for overriding all methods in the stage.
   * @default */*
   */
  readonly apiGatewayMethodPath?: string;
```

### Expected Behavior

I would expect cdktf to escape or replace special characters in variables descriptions or default values that break comments

### Actual Behavior

the comment and default value contain characters that break the ts comments. The special characters in question here are `{resource_path}/{http_method}` and `*/*`

### Steps to Reproduce

Add a variable like above to a tf module, define that module in `cdktf.json` and run `cdktf get` to generate the ts construct for the module.

### Important Factoids

I can simply update the variable description as a workaround but I would like the leave the default value as `*/*` and that is currently breaking the generated construct.

**Comment by xiehan** [comment]
Closed by #2986
