### ISSUE TITLE
cdktf init throws `items` must be Array error

### ISSUE THREAD

**Issue by huberemanuel** [hashicorp/terraform-cdk#616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf: 0.2.1
python: 3.8.3
terraform: 0.14.9
node: 15.13.0

### Debug Output

https://gist.github.com/huberemanuel/35f8aadb077519b9b2283bc6c8e7ac82

### Expected Behavior

Project being initialized

### Actual Behavior

Zero files were created.

### Steps to Reproduce

Install cdktf-cli with npm and run `cdktf init --template=python-pip`

**Comment by skorfmann** [comment]
At which point is this error occurring? Just tried to reproduce with the `cdktf-cli@0.2.1` and the template `python-pip` works as expected.

**Comment by huberemanuel** [comment]
This error occurred after trying to run `cdktf init`. I tried on a different environment and it worked well. This is an issue with my environment, maybe because I updated my node version after installing the cdktf package.
I think we can close this issue, hope this helps others with the same issue.
