### ISSUE TITLE
Add Prettier

### ISSUE THREAD

**Issue by sergeyzenchenko** [hashicorp/terraform-cdk#620]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

What do you think about adding https://prettier.io ? It will help with code contribution. My WebStrom keeps reformatting existing code :D With prettier formatting will be automatic. I can setup it.

**Comment by skorfmann** [comment]
Right now we're using `eslint`, where the config could be improved (and PRs would be more than welcome). Adding yet another tool to the mix doesn't seem to be worthwhile at this point.

> My WebStrom keeps reformatting existing code :D 

I believe this behaviour could just be disabled on a per project basis. Alternatively, WebStorm should be able to use the `eslint` config as well.
