### ISSUE TITLE
Pylance Detecting Python Imports in VSCode

### ISSUE THREAD

**Issue by pmartindev** [hashicorp/terraform-cdk#621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
Python v3.9.2
CDKTF v0.2.1

### Affected Resource(s)
Any app importing the aws resources in VSCode. 

### Debug Output
No debug output

### Expected Behavior

After creating a cdktf (python) app, and running `cdktf get` to install provider dependencies, intellisense (Pylance) in VSCode should automatically detect the generated aws provider resources.

### Actual Behavior

![image](https://user-images.githubusercontent.com/7564144/113453476-a9b83d00-93cb-11eb-86e0-1c20e4016d8d.png)

### Steps to Reproduce
1. Download Pylance in VSCode
2. Configure the settings.json
3. Download the aws provider resources with `cdktf get`
4. Attempt to import a resource from the aws provider in a cdktf app

### Important Factoids

My VSCode settings are configured as such:

![image](https://user-images.githubusercontent.com/7564144/113453923-a8d3db00-93cc-11eb-9c95-f09d8ecc836e.png)

Could this possibly be caused by the large __init__.py file in the aws module?

### References

**Comment by jsteinich** [comment]
Possibly related to #504. Dose pylance have any settings for changing size of files scanned?
Alternatively, are you using a virtual environment and is VSCode configured to use the same one?

**Comment by pmartindev** [comment]
It could definitely be related. I have tried both options, but I'm currently not using a virtual environment.

**Comment by pmartindev** [comment]
Solved the issue! Enabling verbose debugging showed that the auto generated init file wasn't being detected. Explicitly declaring the relative directory of the cdk project in my VSCode settings.json file solved the issue. 

```
{
  "python.languageServer": "Pylance",
  "python.analysis.logLevel": "Trace",
  "python.analysis.extraPaths": [
    "cdk/terraform/my-cdk-project"
  ]
}
```
