### ISSUE TITLE
unable to use @cdktf/provider-aws package with cdktf 0.2

### ISSUE THREAD

**Issue by 3p3r** [hashicorp/terraform-cdk#627]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

NodeJS: v15.11.0
NPM: 7.6.3
CDKTF: 0.2.1

### Affected Resource(s)

`@cdktf/provider-aws` npm package and `cdktf` version 0.2

### Expected Behavior

I should be able to npm install `@cdktf/provider-aws` alongside `cdktf` 0.2

### Actual Behavior

npm install fails when using the AWS prebuilt constructs alongside `cdktf` 0.2

### Steps to Reproduce

```
mkdir test && cd test
npm init
npm i --save cdktf
npm i --save @cdktf/provider-aws
```

### Important Factoids

I am unable to use `cdktf get` to download these packages as the domain it uses to download providers is blocked by our corporate proxy. Only npm is allowed to be used.

### Debug Output

npm install fails with this message:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cdktf-test@1.0.0
npm ERR! Found: cdktf@0.2.1
npm ERR! node_modules/cdktf
npm ERR!   cdktf@"^0.2.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer cdktf@"^0.1" from @cdktf/provider-aws@1.0.40
npm ERR! node_modules/@cdktf/provider-aws
npm ERR!   @cdktf/provider-aws@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See ~/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2021-04-12T19_06_29_678Z-debug.log
```

**Comment by skorfmann** [comment]
Thanks for raising this issue - it's been resolved now and you should be able to install as expected.
