### ISSUE TITLE
Property name and type conflict between generated code and cdktf.ComplexComputedList

### ISSUE THREAD

**Issue by yamamoto-febc** [hashicorp/terraform-cdk#634]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- cdktf: 0.2.1
- typescript: 4.2.4

### Debug Output

https://gist.github.com/yamamoto-febc/2a29df295eee3a768d8f1259747473bd

### Expected Behavior

It should compile.

### Actual Behavior

Unable to compile with TS2416 and TS2411 errors.

### Steps to Reproduce

Generate `sacloud/sakuracloud` provider bindings and compile - See here for a ready to go example: https://github.com/yamamoto-febc/cdktf-sakuracloud-example

---

In the community provider [sacloud/sakuracloud](https://registry.terraform.io/providers/sacloud/sakuracloud/latest), there is a field with the key name `index`, `computed:true` and `TypeInt`.  
ref: https://github.com/sacloud/terraform-provider-sakuracloud/blob/4063b51a35a88163163b0c70cafd86702543863d/sakuracloud/data_source_sakuracloud_vpc_router.go#L101-L105

Here is the code generated using it: https://github.com/yamamoto-febc/cdktf-sakuracloud-example/blob/987794ad53d57fb596a15181d5809f06976fd4b9/.gen/providers/sakuracloud/data-sakuracloud-vpc-router.ts#L166-L169

The Class which extended `cdktf.ComplexComputedList` was generated, and a getter named `index` was generated.
In the original provider, it is defined as TypeInt, so it returns a number.

However, in cdktf.ComplexComputedList, `index` is defined as a string, which causes an error.

**Comment by ansgarm** [comment]
Hey @yamamoto-febc! Thank you for providing this well described bug report containing an example which easily let me reproduce the error 👍

It is caused by a collision of the `index` property in the mentioned Terraform resource of the `sakuracloud` provider and the internal `index` which is used by the CDK for Terraform internally to be able to render references to its value.

I just added a pull request (https://github.com/hashicorp/terraform-cdk/pull/640) which renames the latter to something more specific to fix the collision.

**Comment by ansgarm** [comment]
Hi @yamamoto-febc,
just a heads-up: We released [v0.3](https://github.com/hashicorp/terraform-cdk/blob/main/CHANGELOG.md#030-april-21-2021) yesterday which includes the fix for this bug 🙂
