### ISSUE TITLE
Keep user supplied data format

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#646]
This does not work:
```typescript
new CloudRunService(s, 'a', {
  template: [
    {
      metadata: [
        {
          annotations: {
            'autoscaling.knative.dev/maxScale': '1000',
            'run.googleapis.com/cloudsql-instances': 'name',
            'run.googleapis.com/sandbox': 'gvisor',
          }
        }
      ]
    },
  ],
})
```

Those annotations will be converted to:

```json
{
  "metadata": [
    {
      "annotations": {
        "autoscaling_knative_dev_max_scale": "1000",
        "run_googleapis_com_cloudsql_instances": "name",
        "run_googleapis_com_sandbox": "gvisor"
      }
    }
  ]
}

```

How do I prevent it from converting dots to underscores? The only way I can seem to do it is by using the escape hatch:

```typescript
gcr.addOverride("template.0.metadata", [
  {
    annotations: {
      "autoscaling.knative.dev/maxScale": "1000",
      "run.googleapis.com/cloudsql-instances": 'name',
      "run.googleapis.com/sandbox": "gvisor",
    },
  },
])
```

It would be great if this worked without the escape hatch, but I can live with this for now.

_Originally posted by @kaisellgren in https://github.com/hashicorp/terraform-cdk/issues/395#issuecomment-822786292_

**Comment by jsteinich** [comment]
@kaisellgren I'm not seeing that behavior when I run your example. Which version of cdktf are you using? If you originally generated your provider bindings before #395 was released, you'll need to rerun `cdktf get`.

**Comment by kaisellgren** [comment]
Sorry for the delayed reply.

It now seems to work after doing `npm i` and `cdktf get`. This issue can be closed!
