### ISSUE TITLE
Github Action for GitOps Workflow 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Provide a Github Action for cdktf GitOps workflows

- PR with diff as comment (and optionally deploy a test stage)
- Deploy for configurable main branch 
- Pre / Post PR hooks (e.g. to setup / teardown Terraform Cloud workspaces and similar resources) 
- Supported workflows should be local and Terraform Cloud exec 

Here's an example [build workflow](https://github.com/cdk-dev/repository-manager/blob/69161c1bf21dec6246e0cdfc71e3075c4e655766/.github/workflows/build.yml) which generates PR comments like this 

![Screenshot 2021-04-20 at 15 51 36](https://user-images.githubusercontent.com/136789/115407487-5aa64080-a1f0-11eb-9334-3cbc33b7f344.png)

**Comment by jsteinich** [comment]
Can probably be built using concepts from https://learn.hashicorp.com/tutorials/terraform/github-actions. The example may already be based on that.

GitHub Actions might lack some functionality to prevent some potential issues (see https://github.com/runatlantis/atlantis/issues/384); although, newer features may alleviate some of those concerns.

**Comment by skorfmann** [comment]
> GitHub Actions might lack some functionality to prevent some potential issues (see [runatlantis/atlantis#384](https://github.com/runatlantis/atlantis/issues/384)); although, newer features may alleviate some of those concerns.

It's now possible to limit concurrency per job and seems to have been built with this exact use case in mind. Seems worthwhile exploring https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/

**Comment by RichiCoder1** [comment]
We ended up building upon the example terraform action, might help ya'll out for building this: https://github.com/uShip/actions/tree/main/terraform-output

(Utilizes the terraform installer action's stdout/err wrapping)

**Comment by DanielMSchmidt** [comment]
We published the github action in https://github.com/marketplace/actions/terraform-cdk-action
