### ISSUE TITLE
Cross Stack References

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With #636 we've introduced multiple stacks. We should enable referencing resources across stacks.

### References

- Blocked on #525

**Comment by kwalsh-tr** [comment]
Does anyone know of a temporary alternative method of passing references between stacks?

**Comment by DanielMSchmidt** [comment]
I think the nicest solution currently would be using [DataSources](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/data-sources.md) to get a reference to an object into another stack. For this you need to have the name and type of the element you want to transfer. The name can be a global constant so that it can be used by the resource and data source.


```ts
const clusterName = "my-cluster"
class InfrastructureLayer extends TerraformStack {  
  constructor(scope: Construct, name: string) {    
    super(scope, name);

    new GKECluster(this, "doesNotMatter", {
      name: clusterName,
      // ...
    })
  }
}

class ApplicationLayer extends TerraformStack {  
  constructor(scope: Construct, name: string) {    
    super(scope, name);

    // This will fail if the cluster does not exist already
    new DataGKECluster(this, "doesNotMatter", {
      name: clusterName,
      // ...
    })
  }
}

const app = new App();
new InfrastructureLayer(app, "infrastructure");
new ApplicationLayer(app, "development");
```

**Comment by ansgarm** [comment]
Another option is to write the value you want to refer to [into an output](https://github.com/hashicorp/cdktf-integration-serverless-example/blob/6b0fb158139ca50d26641cbe1cdc93c39314e77c/main.ts#L43) and read that value [from a remote state](https://github.com/hashicorp/cdktf-integration-serverless-example/blob/6b0fb158139ca50d26641cbe1cdc93c39314e77c/main.ts#L24-L25) in the other stack.

**Comment by ZacharyATanenbaum** [comment]
> I think the nicest solution currently would be using [DataSources](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/data-sources.md) to get a reference to an object into another stack. For this you need to have the name and type of the element you want to transfer. The name can be a global constant so that it can be used by the resource and data source.

Is this work-around supported within Python? I'm getting the following error when attempting to use a "Data Source" for a Python Lambda Layer Version.

```
ImportError: cannot import name 'DataLambdaLayerVersion' from 'imports.aws'
```

**Comment by jsteinich** [comment]
> Is this work-around supported within Python? I'm getting the following error when attempting to use a "Data Source" for a Python Lambda Layer Version.
> 
> ```
> ImportError: cannot import name 'DataLambdaLayerVersion' from 'imports.aws'
> ```

You want `DataAwsLambdaLayerVersion`. Data source names are currently a bit more verbose than resource names.

**Comment by phinze** [comment]
From discussion, this can be broken down into two separate issues:

 1. Getting cross-stack references working in code - this issue can continue to track that part
 2. Determining and implementing the CLI workflows associated with cross-stack references - this is captured at a high level with #650 

We plan to tackle this part first, then we'll circle around to the CLI workflows once the core functionality is in place.
