### ISSUE TITLE
Request for guidance

### ISSUE THREAD

**Issue by mimozell** [hashicorp/terraform-cdk#667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Hi,

newcomer here. I skimmed through your documentation and am looking at the codebase, but it's a bit hard for me to understand how things go from a construct to HCL to JSON. I see that under packages there's a hcl2json package, and I assume those functions are used to convert HCL to JSON, but then not sure how a Construct, let say AcmpcaCertificateAuthorityCertificate, ends up as HCL. Is this related to the naming convention that is being used or something else? Guessing that because I checked several constructs and the names seem identical to what is defined in Terraform HCL. E.g. related to the above: [aws_acmpca_certificate_authority](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority) vs AcmpcaCertificateAuthorityCertificate.

This would kinda make is so that CDK would be completely dependent on Terraform and changes will automatically be "ported" to CDK without anyone having to implement any changes to any of the cloud providers directly in CDK...

Anyways, I will stop guessing and would appreciate some explanations or references to the docs where this is explained :)

**Comment by jsteinich** [comment]
The constructs don't actually turn into hcl. They go straight to json from code.
The hcl2json package exists as a way to read in terraform modules from any source in order to generate the code construct classes.

Yes, this project is heavily dependent on Terraform itself. If a change is made in a Terraform provider or module, one simply needs to rerun `cdktf get` to generate updated code constructs. For the pre-built providers, this happens automatically on a schedule.

**Comment by skorfmann** [comment]
> I skimmed through your documentation and am looking at the codebase, but it's a bit hard for me to understand how things go from a construct to HCL to JSON.

Looks like we could improve the docs about the synthesizing process. 

Besides from what @jsteinich wrote, is there anything else we could provide you context on?

**Comment by mimozell** [comment]
Thanks for the answers! I only assumed things go from construct to hcl to json because hcl2json was the only thing I found. Thanks for clarifying and yeah, I think improving the documentation on the synth process would be great! It would also be useful to kinda know what the general areas on which people can contribute are, if that can be described. For example, I kinda expected that the majority of contributions would go into building constructs (similar to how it is in the aws cdk), but you have magically solved that my completely relying on Terraform, which is amazing, but for me it was hard to see how that happens. Just ran `yarn build` and got all the constructs magically generated 😄  so that says that I should focus my contributions in other areas.

**Comment by jsteinich** [comment]
The AWS CDK's "L1" layer is fully generated and is basically the same as what is generated from the Terraform providers. Terraform module generation is a bit of a hybrid between L1 & L2/L3. The generation is basic, but it does leverage abstracts created for Terraform. There may very well be a place for cdktf constructs, but this project hasn't quite gotten to that level.

At this point, contributions can range from just using cdktf and giving feedback / reporting issues to fixing bugs to helping to improve the code generation. There is a backlog of issues to work through and some have been [sorted into milestones](https://github.com/hashicorp/terraform-cdk/milestones). You can also look at for the [good first issue label](https://github.com/hashicorp/terraform-cdk/labels/good%20first%20issue).

**Comment by mimozell** [comment]
Okay, thank you! I see that @skorfmann has opened another issue on improving the documentation around the synth process, so I'll close this one now.
