### ISSUE TITLE
Automatically Create Terraform Cloud Workspace

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#670]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

When using multiple stacks, it'd be pretty neat if the CLI would offer to create a configured workspace if it doesn't exist.

Right now we see the following error:

```
⠙ synthesizing server...
TerraformCloud returned an HTTP 404 error. Please make sure the configured organization (some-tf-cloud-user) and workspace (foo-bar-stack) exist and you have the correct access rights.
```

**Comment by ansgarm** [comment]
Related to this / might be addressed with this:
When initializing a new project from a template that supports multiple stacks, only a single Terraform Cloud Workspace is created. In the case of my [multi stack remote template](https://github.com/ansgarm/cdktf-template-typescript-digitalocean-nodejs) the name of the project can also differ from the name of the stacks, so the TFC Workspace that gets created [in init](https://github.com/hashicorp/terraform-cdk/blob/main/packages/cdktf-cli/bin/cmds/init.ts#L80) might not even match the ones defined in the template.

**Comment by skorfmann** [comment]
Yes - I think this should be moved to the `synth` stage. Essentially collect all backend configs and check for the existence. I'm tempted to try to building this on top of #682

**Comment by matschaffer** [comment]
This is somewhat offtopic, but is there a doc for using cdktf on terraform cloud? I was unable to locate it so came here looking for a "terraform cloud support" issue to upvote. Thanks in advance!

**Comment by ansgarm** [comment]
@matschaffer: There are notes on that (somewhat hidden) in the [Project Setup Docs](https://www.terraform.io/cdktf/create-and-deploy/project-setup#use-terraform-cloud-as-a-remote-backend).
