### ISSUE TITLE
Allow to Skip Synth

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#671]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When deploying multiple stacks sequentially, every step will do another synth. Would be good if the CLI would offer the option to skip synth for the commands `deploy`, `diff` and `destroy`.

**Comment by skorfmann** [comment]
Let's wait for #650 - the workaround for now would be something like:

```
cdktf synth && cd stack-dir-a && terraform apply cd stack-dir-b && terraform apply
```

**Comment by KDanisme** [comment]
Can this be reopened now that [#650](https://github.com/hashicorp/terraform-cdk/issues/650) finished?

**Comment by ansgarm** [comment]
Hi @KDanisme 👋
What is your underlying use-case for wanting to skip synth?
The cdktf-cli now supports passing multiple stack names to deploy at the same time (doing only a single synth). So you could run a `cdktf deploy stack-a stack-b` and it will automatically deploy them (in the correct order, too). It will ask you for a confirmation of the plan after each of them.

**Comment by lcswillems** [comment]
@ansgarm If I use `cdktf output` to view the outputs, it does a `synth` before which generally takes a lot of time. Is it possible to skip it?

**Comment by DanielMSchmidt** [comment]
The deploy command also shows the outputs and allows you to create an outputs file, maybe that could help. In general we try to not skip synth to be sure the synthesized code is in sync with the actual code
