### ISSUE TITLE
cdktf plan does nothing and returns exit code 0

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#675]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.3.0

### Debug Output

```
➜  cdkday-talk git:(master) cdktf plan                                                                                                                       11:18:27
➜  cdkday-talk git:(master) echo $?                                                                                                                          11:18:29
0
➜  cdkday-talk git:(master)             
```
### Expected Behavior

I'd expect to at least see some kind of note telling me about using `diff` like it does if I try `cdktf apply` (points me to `deploy`).

### Actual Behavior

No Output, successful exit code.

### Steps to Reproduce

Run `cdktf plan`.

**Comment by DanielMSchmidt** [comment]
The output in apply comes from yargs [recommendCommands](https://github.com/yargs/yargs/blob/395bb67749787d269cabe80ffc3133c2f6958aeb/lib/validation.ts#L401) function. It seems like their algorithm doesn't catch plan, probably because no character is the same.

We should fail and show help in general if no command matches, going to PR this. We could also think about adding an alias for diff and deploy with plan and apply respectively

**Comment by skorfmann** [comment]
> We should fail and show help in general if no command matches, going to PR this. 

That's a good point 👍 

> We could also think about adding an alias for diff and deploy with plan and apply respectively

Yeah, this would also make sense I think.

**Comment by ansgarm** [comment]
+1 on adding an alias for `plan`/`apply`, as that's what we're doing anyway and to me it feels a bit like gatekeeping to force people to use `diff`/`deploy` for no good reason 😄

**Comment by danieldreier** [comment]
https://github.com/hashicorp/terraform-cdk/issues/573 ("Invalid cdktf-cli commands produce no output (no error or help) and exit code 0") can also get closed when this is resolved
