### ISSUE TITLE
bash/zsh completions for cdktf-cli commands

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#676]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Yargs [supports specifying completions](http://yargs.js.org/docs/#api-reference-completioncmd-description-fn) for commands and arguments. This would be really useful to autocomplete the stacks when doing e.g. a `cdktf deploy [stack]`.

**Comment by skorfmann** [comment]
That sounds great!

**Comment by DanielMSchmidt** [comment]
I failed getting any autocompletion output out of yargs at `cli-autocompletion` I am not super familiar with this kind of shell interaction, so I'm probably not the ideal person for this task

**Comment by ansgarm** [comment]
Support for shell completions has been introduced via #943.
Currently `yargs` does not support auto completing choices (e.g. `typescript, go, ...` for `--language`). I opened a [PR](https://github.com/yargs/yargs/pull/2018) for that and as soon as that gets merged and released we can update to that `yargs` version to improve our completion support.
