### ISSUE TITLE
No error in console when remote execution in Terraform Cloud fails

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#677]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.3.0

### Debug Output
```
➜  cdktf-bug-tfc-errors git:(master) ✗ cdktf diff                                                                                                                                                                           11:58:04
Running plan in the remote backend. To view
this run in a browser, visit: https://app.te
rraform.io/app/cdktf/workspaces/cdktf-bug-tf
c-errors/runs/run-SxLzC5z7W5Bzsmaw
Stack: cdktf-bug-tfc-errors

Diff: 0 to create, 0 to update, 0 to delete.
➜  cdktf-bug-tfc-errors git:(master) ✗ echo $?                                                                                                                                                                              11:59:13
0
```

If you follow the link for the speculative plan, that was printed, you can see the error:
<img width="876" alt="Screenshot 2021-05-03 at 12 09 46" src="https://user-images.githubusercontent.com/1112056/116864689-8bcb3b80-ac08-11eb-8745-8cae2ecb296c.png">

### Expected Behavior

An error should be printed, but exit code was 0 and output was not suspicious.

### Actual Behavior

See output above

### Steps to Reproduce

```
git clone git@github.com:ansgarm/cdktf-bug-tfc-errors.git
cd cdktf-bug-tfc-errors
cdktf diff
```
(You need to have access to the cdktf Terraform Cloud organization)

### Important Factoids

remote execution must be enabled

### References

* #0000

**Comment by ansgarm** [comment]
Note:
This also applies to `deploy`
```
➜  cdktf-bug-tfc-errors git:(master) cdktf deploy                                                                                    12:13:07
No changes for Stack: cdktf-bug-tfc-errors
➜  cdktf-bug-tfc-errors git:(master) echo $?                                                                                         12:15:46
0
```

**Comment by DanielMSchmidt** [comment]
This could possibly be solved already, I'm not sure if I got all cases though: https://github.com/hashicorp/terraform-cdk/pull/712

**Comment by ansgarm** [comment]
Just checked it. Yes, this is resolved via [this commit](https://github.com/hashicorp/terraform-cdk/pull/712/commits/9f8f27d4f09d3ab20d79a94229366ef32faf6125) of #712
