### ISSUE TITLE
getNumberAttribute() returns number instead of reference

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#679]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

0.3.0

### Affected Resource(s)

`import { DatabaseCluster } from "./.gen/providers/digitalocean";`
(generated from `"digitalocean/digitalocean@~> 2.8.0"`)

### Expected Behavior

`db.port` should synthesize to Terraform reference instead of number:

```
"output": {
    "database_host_port": {
      "value": "${digitalocean_database_cluster.db.host}:${digitalocean_database_cluster.db.port}"
    }
}
```

This workaround can achieve the above:
```
new TerraformOutput(this, 'database_host_port', { value: `${db.host}:${db.getStringAttribute('port')}` });
```

### Actual Behavior

```
new TerraformOutput(this, 'database_host_port', { value: `${db.host}:${db.port}` });
```
synthesizes to
```
"output": {
    "database_host_port": {
      "value": "${digitalocean_database_cluster.db.host}:-1.8881545897087498e+289"
    },
}
```

### Steps to Reproduce

The above code originates from my [CDK Day talk example](https://github.com/ansgarm/talk-cdkday-2021).

### References

* https://github.com/ansgarm/talk-cdkday-2021/blob/master/stack-digital-ocean.ts#L36

**Comment by jsteinich** [comment]
`getNumberAttribute` does correctly return a token; that token just isn't resolved correctly. I hadn't observed this exact case before, but this falls under #525.

**Comment by STollenaar** [comment]
I can confirm this is also happening in 0.2.2,
I'm using my own custom provider to do some math and I noticed that only the getNumberAttribute suffers from this not resolving correctly, and always synthesizing to this negative float. 
Happens with both Data and Resource source types, and not sure if there is a work around for me if I wanted to pass those references around and do some more with it

**Comment by ansgarm** [comment]
Hey @STollenaar
When I encountered the issue I used this workaround: `db.getStringAttribute('port')` which resolved to the correct reference (it seemed to not have mattered that the type was a number).
Does that workaround work for you?

**Comment by STollenaar** [comment]
@ansgarm not really, I unfortunately need a number as the output, but whenever you try to cast it to a number it will just go to that negative float. 
I was able to get a work around by just copy the bare minimum of my custom provider code into javascript/typescript. This should work until this issue gets resolved

**Comment by ansgarm** [comment]
Ah, I see. How did you try to cast it? In TS/JS or with the [tonumber](https://www.terraform.io/docs/language/functions/tonumber.html) Terraform function? I suspect using the latter could work, but I haven't tried.

**Comment by STollenaar** [comment]
I tried it with the TS/JS casting. Wasn't sure how to use the Terraform function for this, which in theory could work if we get that reference from the getStringAttribute

**Comment by STollenaar** [comment]
@jsteinich somehow I missed the notification of your comment. But I was passing it to another Data resource which is doing some operations on it (Basically convert to GiB) and I was doing some direct operations on it (Just calling Math.min). 
Currently my work around is just doing those direct operations and not taking in that extra number I would've gotten from a Data source

**Comment by jsteinich** [comment]
The actual value from a data source isn't available during synth. If the values are know at synth time, then using them directly is your best bet; otherwise, need to use Terraform functions via escape hatches.
