### ISSUE TITLE
Auto Close Stale Issues / PRs

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#683]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To reduce the amount of things that are likely not relevant anymore, let's automate closing them. I like the [config](https://github.com/aws/aws-cdk/blob/963d1c7755e23ea819481724d7e8c78e31d82294/.github/workflows/close-stale-issues.yml) of what the AWS CDK repo has. It seems to be pretty straightforward.

**Comment by jsteinich** [comment]
Might also want to consider https://github.com/actions/stale
