### ISSUE TITLE
Support JavaScript

### ISSUE THREAD

**Issue by joatmon08** [hashicorp/terraform-cdk#69]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Verify that JavaScript Language Binding works. Include documentation/getting started. Since TypeScript is supported, JavaScript should work similarly.

### References

AWS CDK Getting Started with JavaScript reference
https://docs.aws.amazon.com/cdk/latest/guide/work-with-cdk-javascript.html

**Comment by aayushharwani-aidash** [comment]
@skorfmann  @joatmon08  I want to work on this. could u plz guide me ?

**Comment by jsteinich** [comment]
@aayushharwani-aidash There are probably several levels to this. I don't think there's been much demand for this, so we'd probably just want to start with some of the basics.
Levels that I see:

1. Verify that core cdktf library can be used in JavaScript
2. Verify that pre-build cdktf providers can be used in JavaScript
3. Write some documentation for getting started with JavaScript
4. Create a project template. Typescript one is [here](https://github.com/hashicorp/terraform-cdk/tree/main/packages/cdktf-cli/templates/typescript)
5. Create and add some example projects
6. Create and add some integration tests

If for some reason JavaScript doesn't work out of the box, then figuring out why and fixing would come before other tasks.

**Comment by xiehan** [comment]
This technically probably "just works", but we don't have any docs or demos on how to work with it. After discussing with the team, we don't consider this a priority, though we'd welcome any community contributions if anyone wants to jump in and tackle this. For now, I'll close this.
