### ISSUE TITLE
Automatically run get when running deploy / destroy / plan

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#690]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When I first clone a new project and try out the examples I run into an error as I did not run get before. If I run get every time before the mentioned commands I get errors thrown if there are only prebuilt providers.

**Comment by jsteinich** [comment]
I don't think it should be ran every time. It is slow and could cause unexpected changes when there isn't an exact version pinned.

If changes were detected / generated code was missing than it could make sense. Some options in increasing complexity:

1. Only run if no code generated
2. Run if no code for any provider / module
3. Run if version changed for any provider / module

Tangential would be running incremental get operations (I thought there was an issue about that already).

**Comment by DanielMSchmidt** [comment]
Sorry for the late answer:

I agree, I think the options you outlined are a great roadmap 👍

**Comment by skorfmann** [comment]
We used to have a basic check that checks for the presence of generated code folders in case there was something specified in `cdktf.json`. Looks like we might have lost that check as part of one of the last refactorings. 

Trying to do smart guesses about which code needs to be rebuild seems like an overkill to me at this point. So, why not just re-add this little check for existence the generated output folders?

**Comment by cognitiaclaeves** [comment]
I'd like to add to this: Don't run get if using python and package for provider is installed with pip.
