### ISSUE TITLE
React Error with multi-value TerraformOutput

### ISSUE THREAD

**Issue by lamebear** [hashicorp/terraform-cdk#695]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Typescript v4.2.1
cdktf v0.3.0

### Affected Resource(s)

cdktf
TerraformOutput

### Debug Output

https://gist.github.com/lamebear/327afa47f0a4b44bb2d227ba99127a4f

### Expected Behavior

There should not be an error message when displaying terraform output with a dictionary value.

### Actual Behavior

When specifying a `TerraformOutput` resource with a dictionary as a value, the resources are successfully created, but there is an issue rendering the terraform output.

### Steps to Reproduce

A stack to reproduce can be found here: https://gist.github.com/lamebear/b4a925033e13238d6726a6fb84223c80

**Comment by ansgarm** [comment]
It seems like #687 is going to fix this.
