### ISSUE TITLE
Unable to use resources containing an argument named 'stack'

### ISSUE THREAD

**Issue by kshahar** [hashicorp/terraform-cdk#702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- cdktf 0.3.0
- Terraform v0.15.3 on windows_amd64

### Affected Resource(s)

Resources from the `heroku/heroku` provider ([link](https://registry.terraform.io/providers/heroku/heroku/latest)) containing the argument `stack`: heroku_app, heroku_build, heroku_slug, etc.

### Debug Output

https://gist.github.com/kshahar/d43287d38489d5a8bd272afb58823687

### Expected Behavior

I should be able to use any provider from the Terraform Registry.

### Actual Behavior

Errors - 
"Property 'stack' in type 'App' is not assignable to the same property in base type 'TerraformResource'. Type 'string' is not assignable to type 'TerraformStack'."

### Steps to Reproduce

cdktf.json:
```json
{
  "language": "typescript",
  "app": "npm run --silent compile && node main.js",
  "terraformProviders": [
    "heroku/heroku@~>4.3.0"
  ],
  "terraformModules": [
  ],
  "context": {
    "excludeStackIdFromLogicalIds": "true",
    "allowSepCharsInLogicalIds": "true"
  }
}
```

main.ts:
```ts
import { Construct } from 'constructs';
import { App, TerraformStack } from 'cdktf';

import { App as HerokuApp, HerokuProvider } from './.gen/providers/heroku';

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new HerokuProvider(this, 'heroku', {});

    new HerokuApp(this, 'app', {
      name: 'my-test-6841b0592ca3',
      region: 'us'
    })
  }
}

const app = new App();
new MyStack(app, 'test');
app.synth();
```

**Comment by jsteinich** [comment]
I believe this to be a regression in version 0.3.0. While we work on a fix, you may consider rolling back to the latest 0.2.x version.

**Comment by jsteinich** [comment]
The ideal solution would be to rename the `stack` property on `TerraformElement` to something like `tfStack`, but that is technically an API breaking change.
We could also rename the generated `stack` attribute to something (not sure what) to fix.
Thoughts @skorfmann?

**Comment by skorfmann** [comment]
> The ideal solution would be to rename the `stack` property on `TerraformElement` to something like `tfStack`, but that is technically an API breaking change.
> We could also rename the generated `stack` attribute to something (not sure what) to fix.
> Thoughts @skorfmann?

I'd go with renaming our property, so something like `cdktfStack`. That would be aligned with the naming schema of `constructNode`.
