### ISSUE TITLE
Publish pre-built providers for Go

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#723]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We currently publish pre-built versions of the most common Terraform providers for TypeScript / JavaScript, Python, Java and C#.  
We want to do this for Go as well.

### References

* https://github.com/terraform-cdk-providers

**Comment by ansgarm** [comment]
Note to my future self when writing docs for this soon: 
```
go get github.com/hashicorp/cdktf-provider-random-go/random
```
<details>
<summary>
main.go
</summary>

```go
package main

import (
	"github.com/aws/constructs-go/constructs/v10"
	"github.com/aws/jsii-runtime-go"
	"github.com/hashicorp/cdktf-provider-random-go/random"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)

func NewMyStack(scope constructs.Construct, id string) cdktf.TerraformStack {
	stack := cdktf.NewTerraformStack(scope, &id)

	// The code that defines your stack goes here
	random.NewRandomProvider(stack, jsii.String("random"), &random.RandomProviderConfig{})

	random.NewPassword(stack, jsii.String("password"), &random.PasswordConfig{Length: jsii.Number(10)})

	return stack
}

func main() {
	app := cdktf.NewApp(nil)

	NewMyStack(app, "test-go-prebuilt")

	app.Synth()
}
```

</details>

To subscribed readers: This already works, but 🤫

**Comment by jamiegs** [comment]
Are the https://github.com/terraform-cdk-providers repos going to be made public?

**Comment by ansgarm** [comment]
Hi @jamiegs 👋
That is an old Github org. We're currently publishing them under the HashiCorp org
See for example:
https://github.com/hashicorp/cdktf-provider-aws
https://github.com/hashicorp/cdktf-provider-aws-go

This repository manages them: https://github.com/hashicorp/cdktf-repository-manager
And this is the (self-updating) [projen](https://github.com/projen/projen) template: https://github.com/hashicorp/cdktf-provider-project

Everything is public 👍

**Comment by ansgarm** [comment]
Also: This can be closed now as we support pre-built providers for Go since 0.12 🎉
Or did I miss something, @DanielMSchmidt?

**Comment by DanielMSchmidt** [comment]
No I just forgot to close it out
