### ISSUE TITLE
Support Asset Construct with Terraform Cloud and Windows

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#726]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently Assets do not support the combination of using a Terraform Cloud Backend together with synthetisation on windows. Supporting this will need us to rewrite asset paths from windows compliant paths with `\` to linux compliant paths with `/`.

### References

Follow up for #648

**Comment by ansgarm** [comment]
Any comment why this is closed? 😅

**Comment by DanielMSchmidt** [comment]
I could solve this in #698 by exposing `TerraformAsset(...).path` as a UNIX path and use a OS related (window / linux) for copying.
