### ISSUE TITLE
Resource status parsing issues with count

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

https://github.com/hashicorp/terraform-cdk/pull/736 introduced a couple regressions in parsing of resource names:
1. Single character resource names aren't matched due to `+` vs `*`
2. Module resources aren't matched since there is more than one `.` in the name

Tangentially, I don't believe resources created with `count` will match either since they have `[x]` in the output. Likely `for_each` as well.

**Comment by skorfmann** [comment]
Thanks!

> * Single character resource names aren't matched due to `+` vs `*`
> * Module resources aren't matched since there is more than one `.` in the name

Gonna fix these

> Tangentially, I don't believe resources created with `count` will match either since they have `[x]` in the output. Likely `for_each` as well.

That was there before, correct?

**Comment by jsteinich** [comment]
> > Tangentially, I don't believe resources created with `count` will match either since they have `[x]` in the output. Likely `for_each` as well.
> 
> That was there before, correct?

I believe so. I was just looking at the output of an already executed Terraform plan to confirm the module naming and noticed this.

**Comment by skorfmann** [comment]
> > > Tangentially, I don't believe resources created with `count` will match either since they have `[x]` in the output. Likely `for_each` as well.
> > 
> > 
> > That was there before, correct?
> 
> I believe so. I was just looking at the output of an already executed Terraform plan to confirm the module naming and noticed this.

Ok, thanks for confirming.

**Comment by skorfmann** [comment]
> > * Single character resource names aren't matched due to `+` vs `*`
> > * Module resources aren't matched since there is more than one `.` in the name
> 
> Gonna fix these

That was reverted and fixed. 

Leave this issue open for 

> Tangentially, I don't believe resources created with `count` will match either since they have `[x]` in the output. Likely `for_each` as well.

**Comment by DanielMSchmidt** [comment]
We removed this view in favour of the terraform logs, so we can close this thanks to #1596
