### ISSUE TITLE
Errors when creating NetworkSecurityGroupSecurityRule

### ISSUE THREAD

**Issue by ovidiu-mihalcea** [hashicorp/terraform-cdk#750]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

terraform-cdk version 0.4.0 with C#

### Affected Resource(s)
Azure VM NetworkSecurityGroupSecurityRule

### Debug Output

https://gist.github.com/ovidiu-mihalcea/d01010a07460286436afa5ab82782b9d
### Expected Behavior

Create a NetworkSecurityGroupSecurityRule
### Actual Behavior

cdktf synth works, but cdktf deploy fails with the error above. It basically asks for all optional parameters to be present, asking for both DestinationAddressPrefix and DestinationAddressPrefixes, SourceAddressPrefix and Prefixes, SourcePortRange and Ranges, DestinationPortRange and Ranges. Forces you to add Source and DestinationApplicationSecurityGroupIds.
### Steps to Reproduce

Tried to create a NetworkSecurityGroupSecurityRule
### Important Factoids

Unless you provide for all the required parameters cdktf deploy would give you an error. If you provide for all the parameters and confirm the resource creation, Azure gives you an error saying that you have specified both source_port_range and source_port_ranges, etc. Basically there's now way to create a Network Security Rule with cdktf.
https://gist.github.com/ovidiu-mihalcea/22986d242b8b21c122696e0d6acf7f48
### References

* #0000

**Comment by skorfmann** [comment]
> 
> │ Error: Incorrect attribute value type││   on cdk.tf.json line 64, in resource.azurerm_network_security_group.myterraformnsg:│   64:         "security_rule": [│   65:           {│   66:             "access": "Allow",│   67:             "destination_address_prefix": "*",│   68:             "destination_port_range": "3389",│   69:             "direction": "Inbound",│   70:             "name": "RDP",│   71:             "priority": 100,│   72:             "protocol": "tcp",│   73:             "source_address_prefix": "*",│   74:             "source_port_range": "*"│   75:           }│   76:         ],││ Inappropriate value for attribute "security_rule": element 0: attributes│ "description", "destination_address_prefixes",│ "destination_application_security_group_ids", "destination_port_ranges",│ "source_address_prefixes", "source_application_security_group_ids", and│ "source_port_ranges" are required.

The error says that `description` should be provided. Have you tried setting it? Looks like the resource schema defines all of attributes as optional, since either the singular or the plural versions can be used - but not both versions together. Unfortunately, there's no way to detect this on our end right now.

**Comment by jsteinich** [comment]
Hm, we already have a system in place to handle via a custom mapping file. We'll have to look into why it isn't working for this case (https://github.com/hashicorp/terraform-cdk/blob/633c9136ed241db6e3aa4e8d67e178766a63032e/packages/cdktf-cli/lib/get/generator/custom-defaults.ts#L266)

**Comment by ovidiu-mihalcea** [comment]
> The error says that `description` should be provided. Have you tried setting it? Looks like the resource schema defines all of attributes as optional, since either the singular or the plural versions can be used - but not both versions together. Unfortunately, there's no way to detect this on our end right now.

Of course I did. I that excerpt I have only given the error on the first attempt.  And even so, the description is already an optional argument. Maybe it was not very clear in my initial post. While the synth command finishes successfully, "cdktf deploy" command asks for all optional parameters to be present, meaning it forces you to have both the singular and plural versions. And this, of course, doesn't sit well with Azure.

But somehow I didn't thought about sending a null array, even though I've tried sending an empty one. So after doing this simple change, it now works.
`            // Create Network Security Group with custom rule
            var networkSecurityGroup = new NetworkSecurityGroup(this, "myterraformnsg", new NetworkSecurityGroupConfig
            {
                Name = vmName + "-nsg",
                Location = location,
                ResourceGroupName = resourceGroup.Name,
                SecurityRule = new NetworkSecurityGroupSecurityRule[]
                {
                    new NetworkSecurityGroupSecurityRule
                    {
                        Description = "Allow for incoming RDP traffic",
                        Name = "RDP",
                        Priority = 100,
                        Direction = "Inbound",
                        Access = "Allow",
                        Protocol = "tcp",
                        SourcePortRanges = new string[] {},
                        SourcePortRange = "*",
                        DestinationPortRanges = new string[] {},
                        DestinationPortRange = "3389",
                        SourceAddressPrefixes = new string[] {},
                        SourceAddressPrefix = "*",
                        DestinationAddressPrefixes = new string[] {},
                        DestinationAddressPrefix = "*",
                        SourceApplicationSecurityGroupIds = new string[] {},
                        DestinationApplicationSecurityGroupIds = new string[] {}
                    }
                },

                Tags = tags
            });
`

**Comment by skorfmann** [comment]
> But somehow I didn't thought about sending a null array, even though I've tried sending an empty one. So after doing this simple change, it now works.

Ahh, now I get it

> Hm, we already have a system in place to handle via a custom mapping file. We'll have to look into why it isn't working for this case (
> 
> https://github.com/hashicorp/terraform-cdk/blob/633c9136ed241db6e3aa4e8d67e178766a63032e/packages/cdktf-cli/lib/get/generator/custom-defaults.ts#L266
> 
> )

What @jsteinich said - this seems to require some custom mapping during the generation process (see https://github.com/hashicorp/terraform-cdk/issues/234 for more context)

**Comment by jsteinich** [comment]
@ovidiu-mihalcea could you please post a snippet of the original code that wasn't working?

**Comment by DanielMSchmidt** [comment]
@skorfmann Is this resolved by #813?

**Comment by skorfmann** [comment]
> @skorfmann Is this resolved by #813?

I don't know, hard to tell without a full code snippet. I'd just close it and see if it's surfacing again.
