### ISSUE TITLE
TerraformAsset not uploading assets that has been updated

### ISSUE THREAD

**Issue by hadock** [hashicorp/terraform-cdk#762]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

I'm using CDKTF 0.4 and Typescript 3.7.5

### Affected Resource(s)

TerraformAsset

### Debug Output
> After I did some changes in the lambda configuration and also the source code of it, then I tried to deploy by executing

`cdktf deploy`

```
Do you want to perform these actions?
  CDK for Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.
Deploying Stack: PoC1
Resources
 ✔ AWS_LAMBDA_FUNCTION  Hello_lambda-hello- aws_lambda_function.Hello_lambda-hello-
                        world               world_6FB0923D

Summary: 0 created, 1 updated, 0 destroyed.
```

### Expected Behavior

What I was expecting is the lambda to become updated with the latest configuration and source code

### Actual Behavior

So far, only the configuration was updated, but the source code was not

### Steps to Reproduce

1. Create a lambda using the TerraformAsset like the following example and your source code under `lambda/hello/index.js`

```
const lambda_file = new TerraformAsset(this, "hello-source-code", {
      path: path.resolve(__dirname, "lambdas/hello"),
      type: AssetType.ARCHIVE
    });
    
    const fn = new LambdaFunction(this, "lambda-hello-world", {
      functionName: "helloWorld",
      handler: "index.Handler",
      runtime: "nodejs12.x",
      description: "This is our first lambda in myapp1",
      role: role.arn,
      timeout: 61,
      filename: lambda_file.path,
      environment: [
        { variables: {"DDB_TABLE": ddb_hello.name}}
      ]
    });
```
2. Deploy your stack with `cdktf deploy`
3. Modify the source code of your lambda
4. Deploy again and check in the AWS console 

### References

* #0000

**Comment by DanielMSchmidt** [comment]
That's a great catch, thank you for filing the issue!
The issue is that from terraforms perspective nothing changes, the path to the asset stays the same.
For this exact use-case we have a property on assets called assetHash that gives you a source code hash so that the lambda function knows it has to redeploy.

You can solve the issue by utilising the source_code_hash property in Lambda functions:


```ts
const lambda_file = new TerraformAsset(this, "hello-source-code", {
  path: path.resolve(__dirname, "lambdas/hello"),
  type: AssetType.ARCHIVE,
});

const fn = new LambdaFunction(this, "lambda-hello-world", {
  functionName: "helloWorld",
  handler: "index.Handler",
  runtime: "nodejs12.x",
  description: "This is our first lambda in myapp1",
  role: role.arn,
  timeout: 61,
  filename: lambda_file.path,
  sourceCodeHash: lambda_file.assetHash, // <-- This solves the issue
  environment: [{ variables: { DDB_TABLE: ddb_hello.name } }],
});

```

To improve the experience further in the future we could embed this hash in the path, that should give us a new input if the content changed.

**Comment by hadock** [comment]
That's awesome! thanks for the solution!! 
I'm working on a workshop from zero to hero and so far this helps a lot.

**Comment by skorfmann** [comment]
> To improve the experience further in the future we could embed this hash in the path, that should give us a new input if the content changed.

Yes, I like that idea. We should keep in mind though, that the `cdktf.out/stacks/stack-a` directory should be kept to a bare minimum in terms of folder size. I think the assets output folders are cleaned up in between synth runs, but I'm not a 100% sure right now.

**Comment by DanielMSchmidt** [comment]
Good point, we don't clean up as of right now, I'll make sure to include it in #769
