### ISSUE TITLE
Guidlines on non-prebuilt providers, like Cloudflare

### ISSUE THREAD

**Issue by emanuele-leopardi** [hashicorp/terraform-cdk#764]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
CloudFlare provider

Hello Guys, thank you for your great work.
I've seen a few Prebuilt Providers like AWS and GCP, etc., and in the documentation, they can be invoked as class objects and used or passed to modules, which is great.
The issue I'm facing is that they are limited, so I wondered what I can do to use, for example, Cloudflare as a provider, is there a way I can do so? 
Can I build it myself? Do you have guidelines or documentation on how to do so?

Thank you|

**Comment by skorfmann** [comment]
> Can I build it myself? Do you have guidelines or documentation on how to do so?

Yes, you can build any provider via the `cdktf-cli` - see here https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md#importing-providers-and-modules

**Comment by emanuele-leopardi** [comment]
Thank you @skorfmann  actually I just found out that I don't really need to do so. Apparently, when declaring my stack, for example like this :
```python

path = os.getcwd()
try:
    with open(os.path.join(path + '/vars.yaml'), 'r', encoding='utf8') as config:
        try:
            parsed_yaml = yaml.safe_load(config)
        except yaml.YAMLError as exc:
            print(exc)
except ImportError as exc:
    print(exc)

source="github.com/emanueleleopardi/my_module"

class MyStack(TerraformStack):
    def __init__(self, scope: Construct, ns: str):
        super().__init__(scope, ns)

        TerraformHclModule(self, "webapp" ,source=source,
            variables=parsed_yaml)

app = App()
MyStack(app, "my-stack")

app.synth()
```
If the module needs to use specific non-pre-build providers, like Cloudflare it is able to do so without any further action from my side, which is pretty cool 😄

**Comment by DanielMSchmidt** [comment]
@emanuele-leopardi You can also add your module into the `cdktf.json` file under `terraformModules` so that running `cdktf get` will generate you code to use the module without needing to write YAML, you can define everything directly in Python (or any other language)
