### ISSUE TITLE
Migrate pre-built providers to HashiCorp Github organization

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We currently publish a few pre-built provider bindings for common Terraform providers to NPM, PyPI, Nuget and Maven. This is currently done via the Github organization [`terraform-cdk-providers`](https://github.com/terraform-cdk-providers).  
This organization was set up in the earlier days of the CDK for Terraform and is going to be discontinued in favor of publishing the provider bindings via the HashiCorp Github organization.

As the pre-built provider bindings for Go are going to be published to a Github repo, this is blocking https://github.com/hashicorp/terraform-cdk/issues/723 because we don't want users of the CDKTF to need to adjust their imports unnecessarily.

Below is a (probably incomplete) checklist of things that need to be done / decided in order to migrate.

## Required tasks

- [x] move the [`terraform-cdk-providers/cdktf-provider-project`](https://github.com/terraform-cdk-providers/cdktf-provider-project) to the HashiCorp Github org
- [x] move (and rename) the [`terraform-cdk-providers/repository-manager`](https://github.com/terraform-cdk-providers/repository-manager) to the HashiCorp Github org
- [x] `terraform-cdk-providers` uses org-wide secrets to access NPM, etc. Configure those for the `repository-manager` repo instead and extend it to [set them](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/actions_secret) on the repos it creates. For this to work, the deployment (of repos) has to be automated an run via Github Actions
- [x] Move the existing (programmatically generated) repos for pre-built providers to the HashiCorp org and import them into the Terraform state (for proper Github redirect / "repo has moved" links to work and history to be kept)
- [ ] Get the [Mergify integration](https://github.com/terraform-cdk-providers/cdktf-provider-project/blob/master/.mergify.yml) approved or find an alternative (e.g. via Github Actions) to auto merge PRs (i.e. for provider updates).
- [x] Check that the generated repos (set-up via projen) only contain Github Actions config that is pinned and allowed to run in the HashiCorp Github org.
- [ ] ...? _remove this if the list seems complete_

### References

* blocks https://github.com/hashicorp/terraform-cdk/issues/723

**Comment by skorfmann** [comment]
If we want to keep maintaining the repos via ckdtf, we should setup a proper Github action to do this and I'll have to migrate my local state to to Terraform Cloud :D

**Comment by DanielMSchmidt** [comment]
Sounds like a good plan :) We could think about filling the generated repos content directly through CDKTF, there is a [resource for that](https://registry.terraform.io/providers/integrations/github/latest/docs/resources/repository_file) (although this blows up the TF state)

**Comment by skorfmann** [comment]
Done
