### ISSUE TITLE
Python Doc request - cdk list

### ISSUE THREAD

**Issue by pixie79** [hashicorp/terraform-cdk#780]
The following works but only gives the first subnet id from the list as requested with the "[0]"
```python
mountTargets = EfsMountTarget(
   self, ns + "_efs_mount_target", file_system_id=fileSystem.id, subnet_id="", security_groups=[securityGroupIds['efs']]
)
mountTargets.add_override(
    'subnet_id',
    "${[ for id in " + intraSubnets.fqn + ".ids: id][0]}"
)
```

I can not seem to work out the correct line for `"${[ for id in " + intraSubnets.fqn + ".ids: id][0]}"`  to give me the loop.

I have tried the following which seems close to what is needed:

```python
mountTargets = EfsMountTarget(
    self, ns + "_efs_mount_target_1", file_system_id=fileSystem.id, subnet_id="${each.value.subnet_id}", security_groups=[securityGroupIds['efs']]
)
mountTargets.add_override(
    'for_each',
    "${[ for x in " + intraSubnets.fqn + ".ids: { subnet_id = x}]}"
)
```

But that gives the error:

│     │ data.aws_subnet_ids.intraSubnets.ids is a set of string, known only after apply
│
│ The "for_each" value depends on resource attributes that cannot be
│ determined until apply, so Terraform cannot predict how many instances will
│ be created. To work around this, use the -target argument to first apply
│ only the resources that the for_each depends on.

**Comment by pixie79** [comment]
If I update the code as follows 
```python
    mountTargets = EfsMountTarget(
        self, ns + "_efs_mount_target", file_system_id=fileSystem.id, subnet_id="", security_groups=[securityGroupIds['efs']], depends_on=[vpc]
    )
    mountTargets.add_override(
        'subnet_id',
        "${[ for id in "+ vpc.fqn +".intra_subnets: id]}"
    )
```

Then I get 

│   on cdk.tf.json line 514, in resource.aws_efs_mount_target.mark-dev_efs_mount_target:
│  514:         "subnet_id": "${[ for id in module.vpc.intra_subnets: id]}",
│     ├────────────────
│     │ module.vpc.intra_subnets is tuple with 3 elements
│
│ Inappropriate value for attribute "subnet_id": string required.

**Comment by pixie79** [comment]
The following option:

```python
    mountTargets = EfsMountTarget(
        self, ns + "_efs_mount_target", file_system_id=fileSystem.id, subnet_id="${each.value.subnet_id}", security_groups=[securityGroupIds['efs']], depends_on=[vpc]
    )
    mountTargets.add_override(
        'for_each',
        "${[ for id in "+ vpc.fqn +".intra_subnets: { subnet_id = id}]}"
    )
```

Gives:
│ Error: Invalid for_each argument
│
│   on cdk.tf.json line 518, in resource.aws_efs_mount_target.mark-dev_efs_mount_target:
│  518:         "for_each": "${[ for id in module.vpc.intra_subnets: { subnet_id = id}]}",
│     ├────────────────
│     │ module.vpc.intra_subnets is tuple with 3 elements
│
│ The given "for_each" argument value is unsuitable: the "for_each" argument
│ must be a map, or set of strings, and you have provided a value of type
│ tuple.

**Comment by jsteinich** [comment]
In your original post, the 2nd example is likely what you want. It may be possible to adjust how you are accessing the subnet ids to eliminate the error. https://discuss.hashicorp.com/t/for-each-on-aws-subnet-ids/10151/2 may be helpful in what restructuring is needed.

**Comment by ansgarm** [comment]
This case should be covered by [Iterators](https://developer.hashicorp.com/terraform/cdktf/concepts/iterators#using-iterators-for-list-attributes) nowadays.

Closing this issue, please create a [new one](https://cdk.tf/bug), if you encounter any edge case 👍
