### ISSUE TITLE
Documentation on using specific provider versions

### ISSUE THREAD

**Issue by drandell** [hashicorp/terraform-cdk#800]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There should be more documentation around using a specific version of a provider. 
In terraform documentation we have the full feature list -> https://www.terraform.io/docs/language/providers/requirements.html#version-constraints

i.e. 

```
"terraformProviders": [
    "google@=3.72"
  ],
```

Works as intended, does >= work as well? A little disclaimer to say yes/no would be good :)

**Comment by skorfmann** [comment]
> Works as intended, does >= work as well? A little disclaimer to say yes/no would be good :)

All the variants to specify versions should be supported and it would be good to document either [here](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/cdktf-json.md) or [there](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers-and-modules.md).
