### ISSUE TITLE
cdktf init fails with "undefined"

### ISSUE THREAD

**Issue by andyhopp** [hashicorp/terraform-cdk#805]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
    Terraform CDK version: 0.4.1
    Terraform version: 1.0.1

### Affected Resource(s)

New CDKTF project (or lack thereof :) )

### Debug Output

No log output...

### Expected Behavior

A new CDKTF project should have been created with cdktf.json, et. Al.

### Actual Behavior

```
Detected Terraform Cloud token.

We will now set up Terraform Cloud for your project.

undefined
```

### Steps to Reproduce

Install Terraform
Install cdktf
Create project folder
Initialize using `cdktf init`

### Important Factoids
Same behavior with Typescript
Using `--local` works

### References

- #0000

**Comment by danieldreier** [comment]
@andyhopp thanks for reporting this! I've tried to reproduce this on an X86 OS X machine running OS X 11.4, but wasn't able to. I followed the steps you provided, and did not get the "undefined" error -- it completed setup as expected. I'd like to figure out how to reproduce this so that we can fix it.

Can you tell me what OS, architecture, and node version (`node -v`) you are seeing this on?

**Comment by walkerk1980** [comment]
macOS Catalina - Intel Mac

```
System Version: macOS 10.15.7 (19H1217)
Kernel Version: Darwin 19.6.0
```

```
node -v                      
v16.5.0
```

```
npm -g list
/usr/local/lib
├── aws-cdk@1.113.0
├── cdktf-cli@0.4.1
├── cdktf@0.4.1
├── constructs@3.3.98
└── npm@7.19.1
```

```
cdktf init --template python 

We will now set up the project. Please enter the details for your project.
If you want to exit, press ^C.

Project Name: (default: 'cdktf_test1') 
Project Description: (default: 'A simple getting started project for cdktf.') 

Detected Terraform Cloud token.

We will now set up Terraform Cloud for your project.

undefined

Debug Information:
    Terraform CDK version: 0.4.1
    Terraform version: 1.0.2
```

**Comment by barthuijgen** [comment]
I could reproduce this on Ubuntu (through windows WSL2) 

Ubuntu: 20.04.2 LTS
Node: 16.5
Terraform CDK version: 0.4.1
Terraform version: 1.0.3

Trying to init in a empty directory using the typescript template returns the same output and does nothing.

**Comment by justinwaite** [comment]
Can confirm this is also an issue with Node v16.4.0 and M1 MacBook Air.

**Comment by xiehan** [comment]
This issue is so old that hopefully it's been improved in the dozen releases we've done in the meantime. If folks are still encountering similar problems, please open a new issue.
