### ISSUE TITLE
Support end-to-end testing cdktf stacks with Jest

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#806]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Build a custom [TestEnvironment](https://jestjs.io/docs/configuration#testenvironment-string) and/or [setup](https://jestjs.io/docs/configuration#globalsetup-string) / [teardown](https://jestjs.io/docs/configuration#globalteardown-string) hooks for Jest that allow TypeScript users of the CDKTF to build integration / end-to-end test suites which deploy and test the (live) infrastructure via the CDKTF.  
While it is already possible to implement this, using internal APIs of the `cdktf-cli` ([example code](https://github.com/hashicorp/terraform-cdk/issues/237#issuecomment-864523914)), it makes sense to build this upon [#804 Public API for Terraform CLI / TF Cloud exec code](https://github.com/hashicorp/terraform-cdk/issues/804).  

Regarding watching tests: There seems also be support for [watch plugins](https://jestjs.io/docs/watch-plugins).  

Depending on the implemenation, this could also require #227.  

An initial version might also make use of the [cdktf watch command](https://github.com/hashicorp/terraform-cdk/issues/801) however it might be too hard to sync running Jest and running the deploy.

### References

* #804
* #227

**Comment by danieldreier** [comment]
@ansgarm I believe that this was largely addressed by https://github.com/hashicorp/terraform-cdk/pull/952, and I've created https://github.com/hashicorp/terraform-cdk/issues/1003 to track the outstanding need for `watch` integration.

**Comment by skorfmann** [comment]
> I believe that this was largely addressed by #952,

#952 seems to be about unit testing only, or am I missing something? /cc @danieldreier
