### ISSUE TITLE
Design & Plan improved diff output

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#807]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We want to improve way the cdktf-cli displays a `diff`. Currently it does not show the individual attributes that are going to be created / changed but only an info on resource level which resource is going to be created / updated / deleted.  
Furthermore it would also useful to be able to see, which attribute change causes a resource to be recreated.
As the (CLI-)UI and the state handling (via React Hooks) are currently coupled quite tightly, a refactoring which separates the state handling (i.e. synthesizing config, interfacing with Terraform CLI, etc) from the visual representation seems necessary for this.

This issue should result in:
- a design mockup for an improved diff output (text is fine, as this is about the design of the CLI interface) 
- a technical architecture + implementation sketch for how to separate the UI and the state handling

The planned work should be scoped so at least some of it can be delivered in 0.6

### References
- this issue prepares https://github.com/hashicorp/terraform-cdk/issues/114
- https://github.com/hashicorp/terraform-cdk/issues/152

**Comment by danieldreier** [comment]
@ansgarm I think this can be closed?

**Comment by phinze** [comment]
Closing in favor of #114
