### ISSUE TITLE
Design + plan token system refactor

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#808]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

@DanielMSchmidt to write this up. Outline as discussed:
Technical 
- Extract token system into separate module to establish a clear interface
- Build mock implementations of both the proposed token-as-string and token-as-object implementations
- Assess UX tradeoffs to both designs and recommend a direction

For our planning
- Architecture to be proposed, agreed on. Agree on (currently-internal) proposed architecture, publicize it here
- Circulate RFC internally at HashiCorp
- Outline implementation plan / steps in 0.6 and 0.7

User-facing
- Briefly describe + link functional improvements to expect in 0.6 and later from this work
- Also explicitly note what's out of scope

**Comment by skorfmann** [comment]
Since we committed to going forward with the existing Token system approach, I'm closing this. Ongoing work will be tracked in https://github.com/hashicorp/terraform-cdk/issues/525
