### ISSUE TITLE
Sensitive outputs are sent to stdout after cdktf deploy

### ISSUE THREAD

**Issue by matschaffer** [hashicorp/terraform-cdk#809]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

node v14.17.0

    "cdktf": "^0.4.1",
    "@types/node": "^15.12.5",
    "typescript": "^4.3.4"

### Affected Resource(s)

TerraformOutput

### Debug Output

TBD

### Expected Behavior

Sensitive outputs are masked in stdout.

### Actual Behavior

Sensitive outputs are displayed on stdout in clear text.

### Steps to Reproduce

Use a main.ts like this, using `"elastic/ec@0.2.1"`

```ts
import { Construct } from 'constructs';
import { App, TerraformOutput, TerraformStack } from 'cdktf';
import { EcProvider, Deployment } from "./.gen/providers/ec";

class MyStack extends TerraformStack {
  constructor(scope: Construct, name: string) {
    super(scope, name);

    new EcProvider(this, "ec");

    const deployment = new Deployment(this, "example_minimal", {
      version: "7.13.2",
      region: "azure-eastus2",
      deploymentTemplateId: "azure-io-optimized-v2",
      elasticsearch: [
        {
          topology: [
            {
              id: "hot_content",
              size: "4g",
              zoneCount: 2,
            },
          ],
        },
      ]
    });

    new TerraformOutput(this, "deployment_elasticsearch_password", {
      sensitive: true,
      value: deployment.elasticsearchPassword,
    });
  }
}

const app = new App();
new MyStack(app, 'outputexample');
app.synth();
```

Run `cdktf deploy`, note that password is shown in stdout

```
❯ cdktf deploy
Deploying Stack: outputexample
Resources
 ✔ EC_DEPLOYMENT        example_minimal     ec_deployment.example_minimal

Summary: 1 created, 0 updated, 0 destroyed.

Output: deployment_elasticsearch_password = jVv...REDACTED...uL
```

I'd guess this happens for any sensitive output, elastic cloud was just the example I had most handy.

### Important Factoids

First mentioned in https://github.com/hashicorp/terraform-cdk/issues/802

### References

- First mentioned in https://github.com/hashicorp/terraform-cdk/issues/802

**Comment by skorfmann** [comment]
Thanks for creating this issue @matschaffer 👍  That's certainly something we'll address. In the best case this would be done in combination with https://github.com/hashicorp/terraform-cdk/issues/227

**Comment by matschaffer** [comment]
Awesome! Maybe to be clear, I'd still want to be able to put sensitive outputs to a file like I do with terraform today, but I wouldn't want them on stdout by default.
