### ISSUE TITLE
Re-enable Snapshot test for windows

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#810]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This snapshot test is currently disabled: https://github.com/hashicorp/terraform-cdk/blob/50476e97feed31990cb84f69242a49586ad650d6/test/typescript/multiple-stacks/test.ts#L62-L64
We should update the snapshot on a windows machine and re-enable it.

**Comment by jsteinich** [comment]
I started looking into this. It seems as though the error is actually with line endings. I'm thinking it may make sense to explicitly use the characters since git configurations tend to manipulate file contents.

**Comment by ansgarm** [comment]
Ah, thanks @jsteinich!
