### ISSUE TITLE
Support HTTP_PROXY/HTTPS_PROXY for Terraform Cloud

### ISSUE THREAD

**Issue by amod-kadam-avq** [hashicorp/terraform-cdk#816]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf- 0.4.1
typescript (node  - 14.7.1)

### Affected Resource(s)

Unable to create project with Terraform Cloud as a backend.

### Expected Behavior

cdktf should create the project and configure backened to be Terraform Cloud. 

### Actual Behavior
Unable to setup Terraform Cloud for the project

Following error is thrown
![image](https://user-images.githubusercontent.com/86761788/124070568-a3ce0880-da5b-11eb-9394-c069e42b44c2.png)

### Steps to Reproduce

1. Ensure proxy is setup and environment variables are pointing to PROXY settings.
```
HTTP_PROXY
HTTPS_PROXY
``` 

2. Create a directory e.g. test-cdktf and run following command from directory
`cdktf init --template="typescript"
`
cdktf will try to create the  project and prompts for connecting to Terraform Cloud and Token subsequently.
3. Provide the token 

 

### References

- https://github.com/hashicorp/terraform-cdk/issues/351

**Comment by skorfmann** [comment]
Had a quick look, the builtin https request library of node which we're using is not and won't respect the ENV - see here for details https://github.com/nodejs/node/issues/8381 

This leaves two options: 

- built custom handing for these envs
- swap the builtin https library for some higher level abstraction

**Comment by greenstevester** [comment]
As a possible workaround, could we add a the same “decorator” functionality as https://github.com/Rob--W/proxy-from-env into https://github.com/hashicorp/terraform-cdk to respect the ENV vars?

**Comment by danieldreier** [comment]
@amod-kadam-avq I've switched this from a bug to an enhancement request and renamed it to show what the underlying improvement needed is. It's tentatively planned for the 0.6 release. Thank you for reporting this!

**Comment by danieldreier** [comment]
@greenstevester given that we're planning on starting work on this in 4-6 weeks I don't think we'll do any interim workarounds before then

**Comment by skorfmann** [comment]
@greenstevester since this seems to be an issue when Terraform Cloud is involved during init, would `cdktf init --template typescript --local` work for you? This would skip the Terraform Cloud step entirely.

**Comment by greenstevester** [comment]
@skorfmann - `cdktf init --template typescript --local  ` does work for me. I am not clear tho on how a synth and deploy would then work with our terraform cloud instance?

**Comment by skorfmann** [comment]
> @skorfmann - `cdktf init --template typescript --local ` does work for me. I am not clear tho on how a synth and deploy would then work with our terraform cloud instance?

I was hoping that this wouldn't be an issue, since that's using another library - However, looking at [this issue](https://github.com/axios/axios/issues/3384), it seems to be a similar story. That's where the the [request is created](https://github.com/mijailr/terraform-cloud/blob/f8c4a91f55b7dc86c2feef8ba347e23bdeac50eb/src/api/terraformCloudApiClient.ts) in the Terraform Cloud library.

Which leaves you the option, to just use the `cdktf synth` command and leave the rest to the Terraform CLI for now. 

For reference: NPM itself will [respect](https://docs.npmjs.com/cli/v7/using-npm/config#https-proxy) the proxy settings.

**Comment by greenstevester** [comment]
@skorfmann  - how then via `cdktf synth` can we instruct to push the generated stack to terraform cloud since, without the ` --local` it will send a cloud token,  which is then stored in ` .terraform.d\credentials.tfrc.json` ?

**Comment by skorfmann** [comment]
> @skorfmann - how then via `cdktf synth` can we instruct to push the generated stack to terraform cloud since, without the ` --local` it will send a cloud token, which is then stored in ` .terraform.d\credentials.tfrc.json` ?

What the `cdktf init` cloud workflow is doing:

- Add a [Remote Backend](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/remote-backend.md) 
- Make sure a cloud workspace is created 

Both can be done manually. If the remote backend was added to the stack it's gonna by synthesized correctly and the Terraform CLI should pick up whatever you configured there. Does this answer you question, or did I miss anything?

**Comment by greenstevester** [comment]
@skorfmann - great thanks, this is what I was missing.

**Comment by danieldreier** [comment]
Quick update - this isn't going to make it into CDK for Terraform 0.6. I still see it as a high priority and am hoping to get it addressed in a release in the near future.
