### ISSUE TITLE
aws_emr_managed_scaling_policy is not part of the generated files

### ISSUE THREAD

**Issue by aaronfeng** [hashicorp/terraform-cdk#823]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm unable to find generated file for `aws_emr_managed_scaling_policy`.  I'm using typescript but I assume it also doesn't exist for other languages.

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/emr_managed_scaling_policy

**Comment by aaronfeng** [comment]
It does exists, for some reason, but grep failed me.  Closing the issue.

**Comment by aaronfeng** [comment]
I see what I did, I was looking at an older version of generated code.  I do see it in version `0.4.1`

**Comment by DanielMSchmidt** [comment]
Depending on the language the resource can be PascalCased, so in this case it could have been `AwsEmrManagedScalingPolicy` as well :)
