### ISSUE TITLE
How to pass module output Between different TerraformHclModule

### ISSUE THREAD

**Issue by emanuele-leopardi** [hashicorp/terraform-cdk#825]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
```
cdktf --version
0.4.0
python3 --version
Python 3.9.5
```

### Affected Resource(s)
TerraformHclModule

  How do I pass `output` from a `TerraformHclModule` to another `TerraformHclModule` ?
### Example

Let's say we call inside our stack a TerraformHclModule
```python

	output = TerraformHclModule(
            self,
            "networking",
            source=yml["modules"]["networking"]["source"],
            variables=variables,
        )
```

this module is expected to produce 

```python
	output "rg-name" {
	  value = azurerm_resource_group.rg.name
	}

	output "vnet-name" {
	  value = azurerm_virtual_network.vnet.name
	}
```

which it does.

In fact If I execute, as a test

```python
	TerraformOutput(self, id=test, value=output.get_string("rg-name"))

```
I can check in the cdktf.out/stacks/my-stack/cdk.tf.json that the output is correct.

Then if I invoke another module how am I supposed to pass these variables to that module?

I tried including them into a dictionary like so

```python
	variables = {}
	variables.update({"rg-name": output.get_string("rg-name")})
        variables.update({"vnet-name": output.get_string("vnet-name")})
	otherOutput = TerraformHclModule(
            self,
            "nodes",
            source=yml["modules"]["nodes"]["source"],
            variables=variables,
        )

```
If I print the variables here's what I get:
```python
{'rg-name': '${module.networking.rg-name}', 'vnet-name': '${module.networking.vnet-name}'}
```

But I get 
```bash
Error: Extraneous JSON object property
│ 
│   on cdk.tf.json line 60, in module.nodes:
│   60:       "rg-name": "${module.networking.rg-name}",
│ 
│ No argument or block type is named "rg-name".
╵
╷
│ Error: Extraneous JSON object property
│ 
│   on cdk.tf.json line 61, in module.nodes:
│   61:       "vnet-name": "${module.networking.vnet-name}",
│ 
│ No argument or block type is named "vnet-name".
```

**Comment by emanuele-leopardi** [comment]
I'm closing this as after a few temptative I figured out that this is actually working fine but I was missing the 2 variables declared into the second module 😄

**Comment by ansgarm** [comment]
Glad you figured it out @emanuele-leopardi 🎉
