### ISSUE TITLE
Synth Hides Errors

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#828]
Similar to what's been described in this issue https://github.com/hashicorp/terraform-cdk/issues/35#issuecomment-877766920 running synth where an error happens, might spin endlessly without printing out the error messages on stdout / stderr

In my case it was that `esuild` had been built and bundled on linux and I was using it on osx, which lead to an error message. I was able to see the error when running `app` of `cdktf.json` by hand.

**Comment by danieldreier** [comment]
may be fixed in https://github.com/hashicorp/terraform-cdk/pull/829
