### ISSUE TITLE
Document separation of concerns enterprise architecture guidance

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#834]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We need to provide documentation guidance on how to implement separation of concerns between engineering teams, and between engineering and security. A common workflow is that a platform team provides Terraform + CDK for Terraform as a basic platform, and wants to provide patterns, examples, and reusable code components to application teams. One of the platform team's stakeholders is a security team who is responsible for ensuring that certain guard rails exist, for example hard that publicly-accessible S3 buckets cannot be created.

We should give the specific guidance that:

* Platform teams should build and distribute reusable common components, such as opinionated, secure S3 bucket configurations or VPC configurations, as components. They should default to writing them in TypeScript in order to be able to generate other languages, unless they are certain these won't be needed
* Describe the concepts of L2 and L3 abstractions and give examples. If application teams need to adapt the reusable components, they can. This is not a security concern, because the guard rails are the policy-as-code
* Security teams should write policy in OPA or Sentinel, and pair those policies with specific reusable components. Platform teams should provide a platform and pipeline to automate these. Application teams should not be able to deploy to production or staging without going through these secure pipelines. They must have a test environment that has identical policy-as-code rules in order to test their code outside of production.
* We should give explicit guidance about the relationship between multiple stacks and separation of concerns

**Comment by DanielMSchmidt** [comment]
We added the documentation to https://www.terraform.io/cdktf/create-and-deploy/best-practices#application-architecture a while back, if we need more specific examples / guidance we should create a new issue
