### ISSUE TITLE
Unable to Integrate - Cdktf + Terraform Cloud + with GitLab (VCS provider).

### ISSUE THREAD

**Issue by prashant-eppalpalli** [hashicorp/terraform-cdk#839]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf- 0.4.1
"types/node": "^16.3.3"
"typescript": "^4.3.5"

### Affected Resource(s)
Unable to create / update resources through GitLab integration (VCS provider) in Terraform cloud.
![Cdktf-Issue-01](https://user-images.githubusercontent.com/87750895/126455170-bc1f41cd-986f-44e1-89a1-e64f01588319.png)

### Debug Output
Please check actual behavior section.

### Expected Behavior
After committing and pushing changes in GitLab, VCS triggers the plan from terraform cloud. This should successfully create the plan.

### Actual Behavior
VCS provider triggers the plan but fails to proceed and throwing following error.
![Cdktf-Issue](https://user-images.githubusercontent.com/87750895/126455217-63643b05-ee94-4c7e-8da1-c03357850e21.png)

### Steps to Reproduce
1. Add GitLab VCS provider inside Terraform cloud.
2. Add callback URL in GitLab (GitLab User setting --> add applications).
3. Connect Terraform Cloud workspace to VCS and specify branch name.
4. Commit and Push changes in GitLab.
5. Check Run section inside Terraform Cloud.

### References

- #0000

**Comment by ansgarm** [comment]
Hi @prashant-eppalpalli,

this is currently not supported right out of the box. Currently, you can either commit the generated `cdktf.out` directory to use a VCS integration or you have to use some CI workflow that synthesizes your CDKTF stacks first and then deploys it using Terraform Cloud via the remote execution mode.
There is a short term issue to describe these current workarounds in more detail: https://github.com/hashicorp/terraform-cdk/issues/586.
However in the mid to long term, we want to support this, of course.

**Comment by eppalpalliprashant** [comment]
Hi @ansgarm ,

I have tried to apply a workaround for this. Below are the steps which I tried.

1. I have committed the entire **cdktf.out directory** : 
    Here terraform cloud triggered the plan after committing changes in GitLab, but resulted in below error somehow.
![image](https://user-images.githubusercontent.com/87754185/126665493-6cc26ab3-4f02-4ff4-96fe-7ac42c129d0a.png)



2. Moved **cdk.tf.json** file outside (where main.ts file is located) from /cdk.out/stacks/project-name/ directory : 
    Here terraform cloud triggered the plan and applied the resources successfully after committing the changes in GitLab.
![image](https://user-images.githubusercontent.com/87754185/126667639-3d7a9665-98c5-4bff-abe1-db999e4b6d21.png)

**Comment by prashant-eppalpalli** [comment]
Hi @ansgarm 

I have tried to apply a workaround for this. Below are the steps which I tried. I would like to hear your comments on this.

1. I have committed the entire **cdktf.out directory** :
Here terraform cloud triggered the plan after committing changes in GitLab, but resulted in below error somehow.
![cdktf-1](https://user-images.githubusercontent.com/87750895/126669497-e6dc4aee-a77c-4594-b831-e60a76d56187.png)



2. Moved **cdk.tf.json** file outside (where main.ts file is located) from /cdk.out/stacks/project-name/ directory :
Here terraform cloud triggered the plan and applied the resources successfully after committing the changes in GitLab.
![cdktf-2](https://user-images.githubusercontent.com/87750895/126669519-2234d655-c72d-4cdd-b9da-ef77736334f0.png)

**Comment by ansgarm** [comment]
Hi @prashant-eppalpalli,

Is there other Terraform code (`.tf` or `.tfvars` files) in the main directory?
Did you set the Terraform working directory to the directory where the `cdk.tf.json` file was located in your first try?

**Comment by prashant-eppalpalli** [comment]
Hi @ansgarm 

There is no other terraform code in the main directory. only one file(main.ts).

After looking at your comment, I changed the Terraform working directory in the Terraform cloud console where cdk.tf.json is located. It is working for me. Below are the steps which I performed.

- Terraform directory change.
- Changes in main.ts file.
- cdktf synth
- Committed the changes and pushed to GitLab.
After that terraform cloud successfully triggered the plan and applied the resources. I can see my changes. Please share your views on this.
![Terraform-Working-Directory](https://user-images.githubusercontent.com/87750895/126740552-d6aa3257-a8bb-427a-a0a4-a73dfe4b731f.png)


![cdktf-3](https://user-images.githubusercontent.com/87750895/126740555-ab2cb1a1-07e7-4718-973b-11029ca470bb.png)

**Comment by ansgarm** [comment]
Happy to hear it works now 👍
This is one of the current workarounds and I'm going to put them into our docs soon (as of this issue: https://github.com/hashicorp/terraform-cdk/issues/586).

Is this issue ready to be closed from your point of view?

**Comment by prashant-eppalpalli** [comment]
Hi @ansgarm 

Yes we can close this issue. Thank you for your support on this.
