### ISSUE TITLE
Convert: Expressions are not fully understood when converting

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#842]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Convert needs to understand Terraform expressions to extract references from it and to create an equivalent template string. This is currently done by splitting the reference string into it's parts and searching for known ids in the existing parts. This behaviour mimics a lexer, but due to the oversimplified implementation fails in certain edge cases. 

This is a shortcut over using a similar approach to the `@cdktf/hcl2json` package and [using the Go implementation for expression parsing](https://github.com/hashicorp/hcl/blob/0827c2f3e6483d3a7680d41b4399f4a374747c14/json/public.go#L76) through WASM.

An alternative solution is using a proper parser like [ANTLR](https://www.antlr.org/). To use such tools a formal grammar for Terraform Expressions needs to be written.

This step would also enable us to determine the result type of an expression, that would remove another limitation of the current implementation, the missing type casts when the terraform expressions result in a different type than string.

**Comment by jsteinich** [comment]
Found a reference that is unknown: ${filebase64sha256("./lambda-sources.zip")} has reference "".". Seems like it tried to interpret a string literal relative file path as a reference

**Comment by jsteinich** [comment]
Found a reference that is unknown: ${var.env}support.${local.dns_zone} has reference "support.". Again, tried to interpret a literal string as a reference.

**Comment by jsteinich** [comment]
Found a reference that is unknown: ${[aws_security_group.fe_sg.id, aws_security_group.epb_sg_internal.id, aws_security_group.support_sg_internal.id][count.index]} has reference "[aws_security_group.fe_sg.id". This is an in-place list definition with a lookup.

**Comment by bollohz** [comment]
When I launch `cdktf convert` command in a stack that have something like that `prefix = join("-", [var.tags.app, var.tags.env])` I have this error:

```
Error: Internal Error: Unexpected token, expected "}" (58:75)
  56 |   "description": "The VPC IDs that should be able to access the bucket"
  57 | });
> 58 | const prefix = `\${join("-", [var.tags.app, ${tags.env.value}, ${tags.opco].value})}`;
```

As you can see there's something wrong with parenthesis that can break the process.

**Comment by DJAlPee** [comment]
I was told to leave a message here 😄 
```
Found a reference that is unknown: ${trimsuffix(each.key, ".${each.value}")} has reference "".". The id was not found in ["aws.dev","aws.int","aws.cons","aws.prod","var.delegations","var.domains","var.prodOnlyDomains","local.default_tags","out.nameservers","out.nameservers_prod_only","aws_route53_delegation_set.main","aws_route53_delegation_set.prod_only","aws_route53_record.cons_delegation","aws_route53_record.dev_delegation","aws_route53_record.int_delegation","aws_route53_record.parent_delegation","aws_route53_zone.cons","aws_route53_zone.dev","aws_route53_zone.int","aws_route53_zone.prod_only","aws_route53_zone.root"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
Found a reference that is unknown: ${trimsuffix(each.key, ".${each.value}")} has reference "".". The id was not found in ["aws.dev","aws.int","aws.cons","aws.prod","var.delegations","var.domains","var.prodOnlyDomains","local.default_tags","out.nameservers","out.nameservers_prod_only","aws_route53_delegation_set.main","aws_route53_delegation_set.prod_only","aws_route53_record.cons_delegation","aws_route53_record.dev_delegation","aws_route53_record.int_delegation","aws_route53_record.parent_delegation","aws_route53_zone.cons","aws_route53_zone.dev","aws_route53_zone.int","aws_route53_zone.prod_only","aws_route53_zone.root"] with temporary values [].
        Please leave a comment at https://cdk.tf/bugs/convert-expressions if you run into this issue.
```

Seems, that it doesn't like `".${each.value}"`

**Comment by breeswish** [comment]
```hcl
resource "aws_instance" "play" {
  ami                         = "ami-03a0c45ebc70f98ea"
  instance_type               = "t3.small"
  key_name                    = aws_key_pair.master_key.id
  vpc_security_group_ids      = [aws_security_group.ssh.id]
  subnet_id                   = aws_subnet.main.id
  associate_public_ip_address = true

  connection {
    type        = "ssh"
    user        = "ubuntu"
    private_key = file("./terraform_key")
    host        = self.public_ip
  }

  # ...
}
```

```
Found a reference that is unknown: ${self.public_ip} has reference "self.public_ip".
Found a reference that is unknown: ${file("./terraform_key")} has reference "".". 
```
