### ISSUE TITLE
Import from Terraform doesn't reference module outputs correctly

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#859]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Latest build from main

### Affected Resource(s)

Any module output

### Expected Behavior

module outputs accessed via appropriate get method on TerraformHclModule

### Actual Behavior

Module outputs are accessed as if they went through the code generation process, i.e. <moduleName>.<outputName>Output

### Steps to Reproduce

1. Create terraform file referencing a module output when module is not from the registry
2. Run cdtkf init from terraform
3. Run cdktf synth

**Comment by DanielMSchmidt** [comment]
The problem would need to be solved in [`referenceToAst`](https://github.com/hashicorp/terraform-cdk/blob/fe4a10f1f48bb6dfd2d5e1f34f4d4fe61e0c037b/packages/%40cdktf/hcl2cdk/lib/expressions.ts#L250), it already detects modules, it just does the same for local and remote modules. This means we need to find out there if a module is remote or local, probably we can add this in the scope to decouple detection from action.
