### ISSUE TITLE
Import from Terraform can output in an incorrect order

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#861]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Latest build from main

### Affected Resource(s)

Provider definitions. Possibly others

### Expected Behavior

Code is output in an order that compiles

### Actual Behavior

Code is output in ways that variables are referenced before being defined.

### Steps to Reproduce

1. Create Terraform file that has a provider definition that references variables or module outputs
2. Run cdktf init from terraform
3. Run cdktf synth

**Comment by DanielMSchmidt** [comment]
Hey @jsteinich Could you provide a small example here? We got a test for this: https://github.com/hashicorp/terraform-cdk/blob/main/packages/%40cdktf/hcl2cdk/test/hcl2cdk.test.ts#L750 I flipped the order in HCL and the output was the same so I'm not really sure what's going on here

**Comment by jsteinich** [comment]
I narrowed it down to having two AWS providers (default and and alias in a different region) that both depend on variables. One of the providers is correctly placed after the dependent variables are declared and the other is placed before hand. I believe the aliased one is always placed earlier, but I haven't confirmed.

**Comment by DanielMSchmidt** [comment]
Thank you! I could reproduce it and I'm working on a fix 👍
