### ISSUE TITLE
Watch: Support nested `.gitignore` files

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#865]
Currently the `cdktf watch` command only supports reading the projects root `.gitignore` file to check which files to ignore when watching files for synth.
It should also support nested `.gitignore` files.

E.g. this utility could be extended:
https://github.com/hashicorp/terraform-cdk/blob/962ffa75e726d0506e72fe559e2c50331aba9180/packages/cdktf-cli/lib/server/util.ts#L10-L13

**Comment by skorfmann** [comment]
As stated in https://github.com/hashicorp/terraform-cdk/issues/882#issuecomment-891038757 this should also take into account a monorepo structure, where the `.gitignore` file might be located in the root directory, but cdktf is executed in one of the sub directories.

**Comment by ansgarm** [comment]
As of #1658 watch is not using any `.gitignore` files anymore, so this issue is obsolete.
