### ISSUE TITLE
Watch: Support remote execution in Terraform Cloud

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#866]
Currently `cdktf watch` only supports local execution.
For users that have secrets configured in Terraform Cloud and thus would like to use remote execution, we should support it.

Related lines of code:
https://github.com/hashicorp/terraform-cdk/blob/962ffa75e726d0506e72fe559e2c50331aba9180/packages/cdktf-cli/lib/server/WatchClient.ts#L253-L259

https://github.com/hashicorp/terraform-cdk/blob/962ffa75e726d0506e72fe559e2c50331aba9180/packages/cdktf-cli/lib/server/WatchClient.ts#L177-L180
(this already contains implementation, that could work, but is not yet tested).

### Tasks
- [ ] Watch supports Terraform Cloud remote execution
- [ ] Test written for this

**Comment by liviuignat** [comment]
hi @ansgarm is there any way to sync configuration with Terraform Cloud or any workaround?

**Comment by ansgarm** [comment]
Hi @liviuignat, currently you can only set your Terraform Cloud Workspace to local execution mode to be able to use it with `watch`. That way it will still store your state in Terraform Cloud but it won't be able to use secrets and environment variables configured in Terraform Cloud.
Do you need Terraform to run in Terraform Cloud for your use case?

**Comment by ansgarm** [comment]
Does Watch happen to work with TFC remote execution due to the refactor #1658, @DanielMSchmidt?

**Comment by DanielMSchmidt** [comment]
Yes it does work remote execution, it uses the same mechanism as our normal `cdktf deploy` command 👍
