### ISSUE TITLE
Bundle CLI for distribution

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#881]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It might be worthwhile to bundle the CLI for distribution and include all dependencies via esbuild 

- We have a known, tested state in terms of dependencies which we're distributing
- It's probably faster to install
- Using the CLI as a dependency in other projects becomes less of a headache when thinking about conflicting package versions (react, graphql, express, ...)

**Comment by skorfmann** [comment]
An example of what I mean is pretty well illustrated by this diff of `yarn.lock` over here https://github.com/terraform-cdk-providers/cdktf-provider-external/pull/149/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2de

**Comment by ansgarm** [comment]
This would probably have prevented #1113

**Comment by skorfmann** [comment]
> So this will also do some tree-shaking to only bundle the code that is used? Similar to how webpack does it in frontend projects?

Yes, exactly

**Comment by DanielMSchmidt** [comment]
Closed by #913
