### ISSUE TITLE
Watch: Don't expect .gitignore to be present

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#882]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

- 0.5.0

### Affected Resource(s)

- cli watch

### Debug Output

```
[2021-08-02T11:42:11.393] [DEBUG] default - CONNECTED to GraphqlEndpoint
[2021-08-02T11:42:11.399] [DEBUG] cli-server - [2021-08-02T11:42:11.398] [ERROR] default - [Error: ENOENT: no such file or directory, open '/some/path/.gitignore'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/some/path/.gitignore'
}

```

### Expected Behavior

It shouldn't require a `.gitignore` file to be present

### Actual Behavior

The graphql server throws an error when no `.gitignore` file is present

### References

- Slightly related to https://github.com/hashicorp/terraform-cdk/issues/865

**Comment by skorfmann** [comment]
After reading the [docs](https://github.com/hashicorp/terraform-cdk/blob/fe4a10f1f48bb6dfd2d5e1f34f4d4fe61e0c037b/docs/working-with-cdk-for-terraform/watch.md) on this again, it probably doesn't make a lot of sense to not have a `.gitignore` right now. 

In my particular case, the correct thing would have been to find the closest `.gitignore` file in one of the parent directories. 

Longer term, we should still have an option which works without `.gitignore` though.

**Comment by ansgarm** [comment]
Watch does not require a `.gitignore` anymore due to the explicit files glob introduced by #1658, right @DanielMSchmidt?

**Comment by DanielMSchmidt** [comment]
That's right, we can close this one now 👍
