### ISSUE TITLE
Pre Built Providers Should Update Automatically Again

### ISSUE THREAD

**Issue by squaresun** [hashicorp/terraform-cdk#884]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf `0.5.0` with TypeScript

### Affected Resource(s)

`aws_s3_bucket_object` is missing argument `sourceHash` (a.k.a. `source_hash` in [aws provider docs](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#source_hash))

### Expected Behavior

Definition of `sourceHash` argument in resource `aws_s3_bucket_object` should be in place

### Actual Behavior

The readonly property `sourceHash` is missing in the [definition](https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/master/src/s3-bucket-object.ts#L85), and the related implementation on that property as well

### References

- [cdktf-provider-aws definition](https://github.com/terraform-cdk-providers/cdktf-provider-aws/blob/master/src/s3-bucket-object.ts#L85) on resource `aws_s3_bucket_object`
- [`source_hash` argument in `aws_s3_bucket_object`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_object#source_hash)

**Comment by jsteinich** [comment]
@skorfmann any idea why pre-built provider hasn't updates since June 24th? Looks to be impacting all pre-built providers.

**Comment by skorfmann** [comment]
Yes - that's a bug in the actions workflow. Since we're in the process of moving these into the HashiCorp org, this will be addressed as part of this.

**Comment by skorfmann** [comment]
Should be working again
