### ISSUE TITLE
Convert: Provide guidance for imports

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#885]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

```
import * as cdktf from "cdktf";
import * as docker from "./.gen/providers/docker";

const image = new cdktf.TerraformVariable(this, "image", {});
const imageWithTag = `\${${image.value}}:latest`;
const dockerImageUbuntu = new docker.Image(this, "ubuntu", {
  name: imageWithTag,
});
const dockerContainerFoo = new docker.Container(this, "foo", {
  image: dockerImageUbuntu.latest,
  name: "foo",
});
new cdktf.TerraformOutput(this, "logs", {
  value: dockerContainerFoo.containerLogs,
});
```

While the `./.gen/....` path is the default path for generating providers, it's still a bit arbitrary and in particular for new users a bit puzzling. Since that's probably nothing we can solve on a technical level, perhaps a generated comment might help here.

**Comment by DanielMSchmidt** [comment]
Adding a comment is as easy as writing `t.addComment(ast, "leading", "The comment");`, we already do this [here](https://github.com/hashicorp/terraform-cdk/blob/fe4a10f1f48bb6dfd2d5e1f34f4d4fe61e0c037b/packages/%40cdktf/hcl2cdk/lib/index.ts#L245-L252)
