### ISSUE TITLE
Initial implementation of testing workflow

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#886]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Users frequently ask for guidance on how to test CDK for Terraform code.

[Pocket](https://github.com/Pocket/terraform-modules/blob/main/jest.config.js) successfully uses snapshot tests and [assertions](https://github.com/Pocket/terraform-modules/blob/main/src/pocket/PocketPagerDuty.spec.ts) to test their CDK for Terraform code, which closely mirrors how AWS CDK [recommends](https://docs.aws.amazon.com/cdk/latest/guide/testing.html) testing their code.

**Must-have**
- [ ] Opinionated documentation on how to write and run tests
- [ ] Must work in TypeScript

**Nice-to-have**
- [ ] Ideally we would use / extend / copy [aws-cdk/assert](https://github.com/aws/aws-cdk/tree/master/packages/@aws-cdk/assertions) in order to get support for all languages and align efforts with AWS, but I'm not sure if it's too tied to CloudFormation; we can implement this as docs on an opinionated way to use Jest if the effort to re-use `aws-cdk/assert` is prohibitive
- [ ] Opinionated CLI tooling for running tests and updating snapshots
- [ ] (if we switch to `aws-cdk/assert`) We should dogfood these tests by using the new assertion testing system for our own internal snapshot tests

**Key Decisions**
[ ] Pick between Jest and `aws-cdk/assert`

### References
[aws-cdk/assert](https://github.com/aws/aws-cdk/tree/master/packages/@aws-cdk/assertions)
[AWS RFC for polyglot assert](https://github.com/aws/aws-cdk-rfcs/blob/master/text/0328-polyglot-assert.md)
[Example of Pocket CDK for Terraform Jest testing](https://github.com/Pocket/terraformmodules/blob/main/src/pocket/PocketPagerDuty.spec.ts)

**Comment by jsteinich** [comment]
The AWS cdk assertions packages depends on CloudFormation and some other internals of AWS cdk. Conceptually we should be able to build something similar.
