### ISSUE TITLE
Switching Providers Removes Knowledge of Resource

### ISSUE THREAD

**Issue by bondsb** [hashicorp/terraform-cdk#887]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

```
❯ cdktf --version
0.4.1
```

### Affected Resource(s)

AWS Instance

### Expected Behavior

When I switch an AWS instance from one provider to another (different AWS accounts/VPCs), I expect the CDK to delete the existing instance and deploy a new one using the new provider.  The state should be updated to match.

### Actual Behavior

The old instance is NOT terminated in AWS.  There is no indication in the plan that the instance should be destroyed.  The state is updated as if the old instance were destroyed.

The new instance is created as expected.

### Steps to Reproduce

1. Add two AwsProvider objects to your project, for different AWS accounts with different AWS VPCs.
2. Add an Instance to your project referencing the first provider.
3. Run `cdktf deploy` and type yes.
4. Switch the Instance object to reference the second provider.  You may also need to explicitly specify a subnet if this is not the default VPC.
5. Run `cdktf deploy` and type yes.

There are now two instances, one in each VPC, and the state only includes knowledge of the last one deployed.

**Comment by skorfmann** [comment]
Were the providers aliased or how are the distinguished in your code?

**Comment by bondsb** [comment]
@skorfmann Yes.  The AwsProvider objects each have their `id` set to the appropriate value `aws-1234567890` (the account number).  They use the same string as the `alias`.

**Comment by bondsb** [comment]
I reproduced identical behavior in Python.  The original used Typescript.

**Comment by skorfmann** [comment]
> @skorfmann Yes. The AwsProvider objects each have their `id` set to the appropriate value `aws-1234567890` (the account number). They use the same string as the `alias`.

I'm assuming, that the other provider was commented out? 

Given this setup:

```ts
    new AwsProvider(this, 'primary', {
      region: 'eu-central-1',
      alias: 'identical'
    });

    new AwsProvider(this, 'secondary', {
      region: 'eu-west-1',
      alias: 'identical'
    });
```

Terraform raises the following error when trying to plan this:

```
╷
│ Error: Duplicate provider configuration
│
│   on cdk.tf.json line 18, in provider:
│   18:     "aws": [
│
│ A provider configuration for "aws" with alias "identical" was already given
│ at cdk.tf.json:18,12-13. Each configuration for the same provider must have
│ a distinct alias.
```

I believe, that Terraform treats the provider alias as the only way for identification when it comes to storing the state. Which means, when using the same provider alias there's no change in terms of the stored state.

So, to fix your issue, you should use a distinct alias for each provider.

**Comment by bondsb** [comment]
@skorfmann 
> I'm assuming, that the other provider was commented out?

No.  The aliases (and IDs) are different from each other, so they didn't need to be commented out.  But completely removing the first provider doesn't fix the issue anyway.

**Comment by skorfmann** [comment]
> > I'm assuming, that the other provider was commented out?
> 
> No. The aliases (and IDs) are different from each other, so they didn't need to be commented out. But completely removing the first provider doesn't fix the issue anyway.

Right ok, got it. I don't see a way how Terraform would be able to remove the existing resource of the removed provider - since that removed provider holds all the information about the provider connection. You'd need to do an explicit destroy before removing the provider.

**Comment by bondsb** [comment]
I'm finding that the behavior also exists in Terraform.  I ran `terraform plan` on the synthesized output and got the same result.  I also converted form JSON to HCL just to be sure, same result.

But I can't reproduce the behavior when the resource names are different from each other.  I'm not sure what is happening there.  Now I'm getting the proper behavior if the old and new resource names are different, while the bug occurs when the old and new resource names are the same.

**Comment by bondsb** [comment]
The behavior is different if the resource name is changed.  This works as expected, where the original instance is deleted and the new one is created.

The unexpected behavior occurs when the name of the new object is the same as the old.  Terraform apparently does not query the original provider, but only the new provider which has no knowledge of the original instance.  Terraform then flags the resource as deleted outside of Terraform, and therefore does not attempt any further action on it.

In any case, I do not believe this behavior is directly related to the CDK, so I'll close the issue.  Thanks!
