### ISSUE TITLE
Add pre-built providers for pagerduty/pagerduty , archive , and local

### ISSUE THREAD

**Issue by danieldreier** [hashicorp/terraform-cdk#888]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Pocket requested that we add pre-built providers for pagerduty/pagerduty , archive , and local. These are among our top-used providers so I think this would be helpful to a wide range of users.

**Comment by jsteinich** [comment]
Is it possible to do #766 before this?

**Comment by skorfmann** [comment]
Done 

- https://www.npmjs.com/package/@cdktf/provider-archive 
- https://www.npmjs.com/package/@cdktf/provider-local
- https://www.npmjs.com/package/@cdktf/provider-pagerduty
