### ISSUE TITLE
Convert command throws error when count is present

### ISSUE THREAD

**Issue by scottenriquez** [hashicorp/terraform-cdk#889]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

Terraform version: 1.0.3
CDK for Terraform version: 0.5

### Debug Output
[Link to Gist](https://gist.github.com/scottenriquez/eb4902650760464f693c31a8bae1bde3)

### Expected Behavior
**Source Terraform:**
```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

resource "aws_instance" "multiple_servers" {
  count = 4

  ami           = "ami-0c2b8ca1dad447f8a"
  instance_type = "t2.micro"

  tags = {
    Name = "Server ${count.index}"
  }
}
```

**Command:**
```shell
cat terraform.tf | cdktf convert --language typescript
```

**Expected**
One or more `Instance`s to be generated.

```typescript
new aws.Instance(this, "multiple_server", {
  ami: "ami-0c2b8ca1dad447f8a",
  instanceType: "t2.micro",
  tags: {
    name: "Server ${count.index}",
  },
});
```

### Actual Behavior

`Error: Internal Error: input.startsWith is not a function`

### Steps to Reproduce

- Copy HCL above into a file named `terraform.tf`
- Run `cat terraform.tf | cdktf convert --language typescript`

**Comment by DanielMSchmidt** [comment]
My guess for the root cause is that its in the [`extractReferencesFromExpression`](https://github.com/hashicorp/terraform-cdk/blob/main/packages/%40cdktf/hcl2cdk/lib/expressions.ts#L18) function.
