### ISSUE TITLE
Convert/import from TF: Use override logical id on construct id collision

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#890]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

#845 handled construct id collisions by appending a number. We should override the logical id to be the original resource id when that happens so existing state could be used without having to rename.

### References

#845 
#329

**Comment by DanielMSchmidt** [comment]
The collision detection is [here](https://github.com/hashicorp/terraform-cdk/blob/fe4a10f1f48bb6dfd2d5e1f34f4d4fe61e0c037b/packages/%40cdktf/hcl2cdk/lib/expressions.ts#L198) and the overrides get added [here](https://github.com/hashicorp/terraform-cdk/blob/main/packages/%40cdktf/hcl2cdk/lib/generation.ts#L207).
