### ISSUE TITLE
cdktf convert for Go support

### ISSUE THREAD

**Issue by cameronelliott** [hashicorp/terraform-cdk#893]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`cdktf convert` will convert HCL files to four languages, but not Go. _"typescript", "python", "csharp", "java"_

Congrations to the team for cdktf and the `convert` feature, it's all looking fantastic.

It would be really fantastic to have Go support for the `convert` feature, and I suspect other Go developers
looking at the cdktf would like it also.

**Comment by jsteinich** [comment]
This is currently blocked by https://github.com/aws/jsii/issues/2439

**Comment by aloom0626** [comment]
@jsteinich What is the status of this? I noticed go support might have been added to the JSII library here: https://github.com/aws/jsii/pull/3376

**Comment by jsteinich** [comment]
@aloom0626 thanks for pointing out that change. It should be a relatively simple change to enable it now.
