### ISSUE TITLE
Getting The Number of Availability Zones in an AWS Region

### ISSUE THREAD

**Issue by aboarya** [hashicorp/terraform-cdk#906]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
cdktf version 0.5.0 with python bindings of AWS Provider

### Affected Resource(s)
`class DataAwsAvailabilityZones`

### Expected Behavior
This may be just a miss-understanding on my part on how this is supposed to work.  I though that by constructing a `DataAwsAvailabilityZones` object, that the names property (the availability zones) would be evaluated at python compile time, and not at plan time.  

So when I look up the names property I expected that I would have a list with length equal to the number of availability zones in the region.

In HCL I was able to do the following

```
num_azs            = length(data.aws_availability_zones.available.names[*])
```

To have a dynamic number of AZ's for deployments to different regions.

How can this be achieved in `CDKTF`?

### Actual Behavior
```
azs = DataAwsAvailabilityZones(scope, f'{name}-zones', all_availability_zones=True, state = "available")
print(f"azs.names returns {azs.names}") # should return a list with X num AZs, depending on region
# ['#{Token[TOKEN.0]}']
```

### References

- #0000

**Comment by DanielMSchmidt** [comment]
With the current implementation you can use an [override](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/escape-hatch.md) to get the same functionality, e.g.

``` py
other = OtherResource(this, "new", 
  numberOfAvailabilityZones= 0
)
other.addOverride("numberOfAvailabilityZones", "length("+ azs.fqn + ".available.names[*])")
```

Please be aware that you will never have the actual number inside of your program, this is only determined when terraform runs, which is after the program ran and synthesised the terraform code.

We currently have a PR open to make this easier, #903 so there is a better way to solve this coming. You would do


```py
from cdktf import Fn
...

OtherResource(this, "new", 
  numberOfAvailabilityZones= Fn.lengthOf(azs.names)
)

```

**Comment by DanielTeraSky** [comment]
I personally use the same functionality when provisioning a VPC module, and although I didn't find a way to print the number of AZs, the actual number is passed  correctly to the module.

This is what I did:
```bash
azs = sorted(DataAwsAvailabilityZones(self, 'azs', state='available').names)

TerraformHclModule(self, 'vpc',
                    source=AWS_VPC_MODULE_SOURCE,
                    version=AWS_VPC_MODULE_VERSION,
                    variables={
                        'name': network_config['name'],
                        'cidr': network_config['vpc_cidr'],
                        'azs': azs[0:max(len(network_config['public_subnets']), len(network_config['private_subnets']))],
                        'public_subnets': network_config['public_subnets'],
                        'private_subnets': network_config['private_subnets'],
                    })
```

(I first query for the full list of AZs and then pass only a subset of the list to the module for subnet creation)

**Comment by DanielMSchmidt** [comment]
The Terraform functions PR is merged, so I'd consider this closed. Let me know if there is still an issue that's unaddressed 👍
