### ISSUE TITLE
Automatically Format PRs 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#916]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm imagining a dedicated PR action, which checks for formatting issues and automatically creates a PR to fix these via `yarn format`

**Comment by DanielMSchmidt** [comment]
I think out pre-commit hook is not properly working, maybe we can fix it instead: https://prettier.io/docs/en/precommit.html
