### ISSUE TITLE
generated json files reference submodules incorrectly

### ISSUE THREAD

**Issue by figadore** [hashicorp/terraform-cdk#920]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

cdktf-cli: 0.5.0-pre.299
go: 1.16

### Affected Resource(s)

submodules

### Debug Output

```
│ Error: Unreadable module directory
│ 
│ Unable to evaluate directory symlink: lstat ../tf-modules: no such file or
│ directory
╵

╷
│ Error: Failed to read module directory
│ 
│ Module directory  does not exist or cannot be read.
```

### Expected Behavior

stack terraform generated at `cdktf.out/stacks/<stack-name>`

submodules are referenced correctly (`../../../tf-modules`)

### Actual Behavior

stack terraform generated at `cdktf.out/stacks/<stack-name>`

submodules are referenced at a single directory up (`../tf-modules`)

### Steps to Reproduce

1. Add a terraform submodule in a directory such as `tf-modules/my-module`
2. Reference module in cdktf.json
3. run `cdktf get`
4. run `cdktf synth`
5. run `cdktf diff`

### Important Factoids

Seems related to the new folder structure that supports multiple stacks

**Comment by ansgarm** [comment]
Hi @figadore! You're right. It seems to be due to this bug: https://github.com/hashicorp/terraform-cdk/issues/664

**Comment by figadore** [comment]
> Hi @figadore! You're right. It seems to be due to this bug: #664

thanks, following and closing as a duplicate

in the meantime, i had to publish all of my submodules to github as a workaround
