### ISSUE TITLE
cdktf get - reduce execution duration

### ISSUE THREAD

**Issue by abaki007** [hashicorp/terraform-cdk#924]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Each time `cdktf get` is run, it will destroy and rebuild the required terraform modules & packages, even if the required packages are already in the imports directory. 

Can we add a check or change the default behaviour so `cdktf get` won't rebuild packages that are already present in the imports directory. This will reduce the time taken to run `cdktf get`

I am using cdktf in a python environment:
cdktf  version = 0.5.0
python version = 3.9.6
Terraform version = 0.13.5

**Comment by ansgarm** [comment]
Hi @abaki007!

This seems similar to this feature request: https://github.com/hashicorp/terraform-cdk/issues/578

**Comment by abaki007** [comment]
Hi @ansgarm 
Yes, #578 is the same - thanks! I'll close this issue.
