### ISSUE TITLE
unknown type set(string) 

### ISSUE THREAD

**Issue by hd-deman** [hashicorp/terraform-cdk#928]
Module generation fails if it contains variables with `type = set(string)`.

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

terraform-cdk: 0.5.0

### Debug Output

```
❯ cdktf get

Error: Internal Error: unknown type set(string)
    at Object.Internal (/usr/local/lib/node_modules/cdktf-cli/lib/errors.js:20:21)
    at parseType (/usr/local/lib/node_modules/cdktf-cli/lib/get/generator/module-generator.js:104:27)
    at ModuleGenerator.emitSubmodule (/usr/local/lib/node_modules/cdktf-cli/lib/get/generator/module-generator.js:38:91)
    at new ModuleGenerator (/usr/local/lib/node_modules/cdktf-cli/lib/get/generator/module-generator.js:12:18)
    at ConstructsMaker.generateTypeScript (/usr/local/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:186:13)
    at async ConstructsMaker.generate (/usr/local/lib/node_modules/cdktf-cli/lib/get/constructs-maker.js:190:9)
    at async get (/usr/local/lib/node_modules/cdktf-cli/bin/cmds/ui/get.js:50:17) {
  type: 'set(string)'
}
⠏ downloading and generating modules and providers...
Internal Error: unknown type set(string)
```

### Expected Behavior

It should generate a module which use  type `set(string)` in the variables.

### Actual Behavior
It fails on cdktf get command. 

### Steps to Reproduce

Just add module with  type `set(string)` (https://github.com/terraform-aws-modules/terraform-aws-iam/tree/master/modules/iam-assumable-role-with-oidc in this example) to cdktf.json 
```
{
...
  "terraformModules": ["terraform-aws-modules/iam/aws//modules/iam-assumable-role-with-oidc@4.3.0"],
...
}
```

**Comment by jsteinich** [comment]
Caused by https://github.com/hashicorp/terraform-cdk/blob/a8692c713d8c78d934f231df4474e47631b33e5f/packages/cdktf-cli/lib/get/generator/module-generator.ts#L136 not matching set and no case for it farther down.

Set is also not fully supported in general since jsii doesn't support them (https://github.com/aws/jsii/issues/1). Could be worked around, possibly with ideas from #424.

**Comment by LumaKernel** [comment]
Any workaround for this today like `.addOverride()`? I tried to use `TerraformModule` but this is abstract class.

**Comment by LumaKernel** [comment]
I can use `TerraformHclModule` and `cdktf synth` + `tf init`, followed by `tf` command itself.

**Comment by jsteinich** [comment]
@LumaKernel glad that you were able to find that workaround. As the issue occurs during code generation, that's really the only way currently.

Out of curiosity, why are you running tf directly after synthing?

**Comment by LumaKernel** [comment]
At that time I got the error and I felt the change to `tf` command itself solved my problem, but now I checked it and it works. ( no version up ). I don't remember was it dream or not but if I get it again, I'll write it down.
Thank you.
