### ISSUE TITLE
To use github packages and maven, what do we use as the groupId and artifactId in the dependency?

### ISSUE THREAD

**Issue by gmsharpe** [hashicorp/terraform-cdk#937]
To use github packages and maven, what do we use as the groupId and artifactId in the dependency?

### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### References

- #0000

**Comment by jsteinich** [comment]
We actually stopped publishing to Github packages awhile ago. Packages are available on maven central.

<dependency>
  <groupId>com.hashicorp</groupId>
  <artifactId>cdktf</artifactId>
  <version>0.5.0</version>
</dependency>

**Comment by DanielMSchmidt** [comment]
Seems like this is outdated / answered, closing this for now, please let me know if this is still relevant :)
