### ISSUE TITLE
Terraform Meta Arguments - Provisioners 

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#94]
Just stumble upon missing meta data for Terraform Resources: [Provisioners](https://www.terraform.io/docs/provisioners/index.html). They should be supported, in particular useful in regards to `NullResources`.

**Comment by ansgarm** [comment]
@skorfmann Is this an (older) duplicate of https://github.com/hashicorp/terraform-cdk/issues/411?

**Comment by danieldreier** [comment]
I'm closing this in favor of #411
