### ISSUE TITLE
Not able to use S3Backend for terraform-cdk-go

### ISSUE THREAD

**Issue by richie-tt** [hashicorp/terraform-cdk#944]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions

`github.com/hashicorp/terraform-cdk-go/cdktf v0.5.0`

### Affected Resource(s)

`S3Backend`

### Debug Output

```sh
panic: "No stack could be identified for the construct at path 'backend'"

goroutine 1 [running]:
github.com/aws/jsii-runtime-go/runtime.Create({0x18fd145, 0xf}, {0xc0003bfe38, 0x2, 0x2}, {0x1722260, 0xc000d02400})
        /home/rtkocz/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.34.0/runtime/runtime.go:185 +0x794
github.com/aws/jsii-runtime-go.Create(...)
        /home/rtkocz/go/pkg/mod/github.com/aws/jsii-runtime-go@v1.34.0/deprecated.go:83
github.com/hashicorp/terraform-cdk-go/cdktf.NewS3Backend({0x7f51eb6a63d8, 0xc000d02180}, 0xc000d04f70)
        /home/rtkocz/go/pkg/mod/github.com/hashicorp/terraform-cdk-go/cdktf@v0.5.0/cdktf.go:9963 +0xbc
main.newMyStack({0x7f51eb6a63d8, 0xc000d02180}, {0xc000d02180, 0x1})
        /home/rtkocz/git/AboveCloudDevops/maintanance-tools/disaster-recovery-go/go-cdk/main.go:33 +0x175
main.main()
        /home/rtkocz/git/AboveCloudDevops/maintanance-tools/disaster-recovery-go/go-cdk/main.go:71 +0x8a
exit status 2
```

### Expected Behavior
I would like to use s3backend as a backend for Terraform state.  I was not able to find any example of how to use s3backend in Go, so  If I make a mistake in configuration, please let me know.

### Actual Behavior
It crashes  according to the debug output

### Steps to Reproduce

```go
package main

import (
	"fmt"
	"cdk.tf/go/stack/generated/hashicorp/aws"
	"github.com/aws/constructs-go/constructs/v3"
	"github.com/aws/jsii-runtime-go"
	"github.com/hashicorp/terraform-cdk-go/cdktf"
)


func getBackend() *cdktf.S3BackendProps {

	bucket := "s3_bucket"
	key := "cdktf-test"
	region := "eu-central-1"
	dynamodb := "lock-tf"

	return &cdktf.S3BackendProps{

		Bucket:        &bucket,
		Key:           &key,
		Region:        &region,
		DynamodbTable: &dynamodb,
	}
}

func newMyStack(scope constructs.Construct, id string) cdktf.TerraformStack {

	cdktf.NewS3Backend(scope, getBackend())
	stack := cdktf.NewTerraformStack(scope, &id)

	aws.NewAwsProvider(
		stack,
		jsii.String("aws"),

		&aws.AwsProviderConfig{
			Region: jsii.String("eu-central-1"),
		},
	)

	instance := aws.NewInstance(
		stack,
		jsii.String("test Machine"),
		&aws.InstanceConfig{
			Ami:          jsii.String("ami-01456a894f71116f2"),
			InstanceType: jsii.String("t2.micro"),
		},
	)

	cdktf.NewTerraformOutput(stack, jsii.String("public_ip"), &cdktf.TerraformOutputConfig{Value: instance.PublicIp()})

	return stack
}

func main() {
	app := cdktf.NewApp(nil)

	newMyStack(app, "go-cdk")

	app.Synth()
}


```

### References

- #0000

**Comment by jsteinich** [comment]
I haven't really used the go version, but a couple things that I can think to try:

1. Try creating the stack prior to creating the backend
2. May need to use `jsii.String()` when creating the bucket props

**Comment by ansgarm** [comment]
> May need to use jsii.String() when creating the bucket props

That shouldn't make a difference. [jsii.String()](https://github.com/aws/jsii-runtime-go/blob/d0fe389f3c9c9326eb5ae996862fc653e71359da/helpers.go#L30) is only a helper to get a pointer to a string, the same can also be achieved by specifying a variable first (as done by @richie-tt).

I think you need to supply the stack to the backend. Currently you're passing `scope` which is going to be the app.
```go
// change this
cdktf.NewS3Backend(scope, getBackend())
// to
cdktf.NewS3Backend(stack, getBackend())
```
(you also have to move that line below the one instantiating the stack)

Hope this solves it!

**Comment by richie-tt** [comment]
Thank you both of you @jsteinich  @ansgarm  for help, after changing to the example from @ansgarm  it's working as expected. 

```go
	stack := cdktf.NewTerraformStack(scope, &id)
	cdktf.NewS3Backend(stack, getBackend())
```

`Visual Studio Code` tricked me by suggesting the following type of variables which I can pass to function `NewS3Backend`

`func cdktf.NewS3Backend(scope constructs.Construct, props *cdktf.S3BackendProps) cdktf.S3Backend`

If I may ask you about one more question, when I see a both of you are experts in cdktf, is there a possibility to show what will be changed in resources. In the following example, I want to update TAGS for `AWS_INSTANCE`, I just think maybe in code need to be added special function which will show up exactly the changes or it should be resolved in another way, if you can give me any TIP it will be very helpful for me.

```sh
❯ cdktf diff
Stack: go-cdk
Resources
 ~ AWS_INSTANCE         testMachine         aws_instance.testMachine

Diff: 0 to create, 1 to update, 0 to delete.
```

**Comment by richie-tt** [comment]
I think I figure out it by changing the  `log-level`, then I can see more about changes

```sh
....
[2021-09-03T11:42:13.350] [DEBUG] default -   # aws_instance.testMachine will be updated in-place
  ~ resource "aws_instance" "testMachine" {
        id                                   = "i-0be30f46e5887d8cb"
        tags                                 = {}
      ~ tags_all                             = {} -> (known after apply)
        # (27 unchanged attributes hidden)





        # (5 unchanged blocks hidden)
    }
...
```

**Comment by ansgarm** [comment]
Hi @richie-tt

Glad it works now, going to close this issue then 👍

> is there a possibility to show what will be changed in resources

Currently not, but the logs you found serve as a workaround for the meantime. But yeah, we plan to add support for this. You can subscribe to this issue to stay up to date on this: https://github.com/hashicorp/terraform-cdk/issues/807
