### ISSUE TITLE
Async / Promises in Constructs

### ISSUE THREAD

**Issue by skorfmann** [hashicorp/terraform-cdk#95]
While building the equivalent of the [EcrAssets](https://github.com/aws/aws-cdk/tree/f44ae607670bccee21dfd390effa7d0e8701efd4/packages/%40aws-cdk/aws-ecr-assets) package for the Terraform CDK, I stumble upon the lack of async / Promises support for generating a hash of the folder content as a trigger for the Docker image build. 

A quick search in the AWS CDK repo revealed, that others have tried this as well, but there's not a way to do it at the moment.  See https://github.com/aws/aws-cdk/issues/8156 and https://github.com/aws/aws-cdk/issues/8273

@eladb mentioned in https://github.com/aws/aws-cdk/issues/8156#issuecomment-634472434 that "it's not supported in the current CDK programming model". Is this primarily due to implementations in the AWS CDK and the `Constructs` package could support this in theory? Or are there other reasons which are blocking this?

**Comment by anubhavmishra** [comment]
@skorfmann can we close this issue?

**Comment by skorfmann** [comment]
> @skorfmann can we close this issue?

Yeah, I think for now this can be closed.
