### ISSUE TITLE
Use Terraform cloud private registry modules in CDKTF project

### ISSUE THREAD

**Issue by prashant-eppalpalli** [hashicorp/terraform-cdk#951]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### cdktf & Language Versions
- cdktf- 0.4.1
- types/node": "^16.3.3
- typescript": "^4.3.5

### Affected Resource(s)

CDKTF project with Terraform cloud private registry modules.

### Expected Behavior

We want to use our Terraform cloud private registry modules inside the CDKTF project. Modules are written in HCL.

### Actual Behavior

At the moment we can only use Terraform public registry modules and not private modules in our CDKTF project.

Is there any workaround for this or any solution that you suggest ?

**Comment by ansgarm** [comment]
Hi @prashant-eppalpalli!

Do you use generated module bindings or the [`TerraformHclModule`](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-modules.md#terraformhclmodule) construct?
What kind of error are you encountering when trying to use the private registry?

**Comment by prashant-eppalpalli** [comment]
Hi @ansgarm

Do you use generated module bindings or the TerraformHclModule construct?
- Nope, we are not using TerraformHclModule construct. We are generating our own modules (written in HCL) in our private registry.

What kind of error are you encountering when trying to use the private registry?
- To use our private registry, I am passing the entire private module registry URL inside the cdktf.json file. Not really sure about what exactly I need to pass in cdktf.json file to fetch private modules inside cdktf project. 
![image](https://user-images.githubusercontent.com/87750895/132188122-c429c2bb-7915-4e8d-8cfe-965ba5f05ab3.png)

  I am getting below error message when I do cdktf get.
![image](https://user-images.githubusercontent.com/87750895/132189070-97abc9f5-7306-4a89-9c1b-d9261e8de641.png)

**Comment by ansgarm** [comment]
@prashant-eppalpalli 

Could you try passing it as an object?
```jsonc
{
  // ...
  "terraformModules": [
    "terraform-aws-modules/vpc/aws@ ~> 3.6.0",
    "terraform-aws-modules/security-group/aws@ ~> 4.3.0",
    {
      "name": "aws_eks_irsa_policy",
      "source": "app.terraform.io/yourorg/eks/aws/modules/irsa_policy",
      "version": "~> 0.1.1"
    }
  ]
}
```

**Comment by prashant-eppalpalli** [comment]
@ansgarm 

Yes, now I can fetch private module in my cdktf project if I pass it as an object. Thanks for this !!

**Comment by ansgarm** [comment]
You're welcome 👍 We should add an explicit example to our docs though.
