### ISSUE TITLE
imports.aws.awsprovider

### ISSUE THREAD

**Issue by henry333666999** [hashicorp/terraform-cdk#954]
doesn't work on eclipse or intellj. couldn't get anything from https://maven.pkg.github.com/hashicorp/terraform-cdk either

**Comment by ansgarm** [comment]
Hi @henry333666999!

Could you describe the commands you are running, what configuration you are using and the error with which they fail?

**Comment by henry333666999** [comment]
I’m on windows, installed nodejs and terraform is in path, using java 11, latest maven is in path
Then I did command

npm install -g cdktf-cli
npm i-g cdtf

cdktf init --template="java" –local
imported maven project on eclipse or intellj, and now import.aws.AwsProvider can’t be found

and I tried
https://maven.pkg.github.com/hashicorp/terraform-cdk
if I try that link on the browser it says doesn’t exist, if I try git clone, it asks for username/pass or access token and I don’t get past that

***@***.***
***@***.***

**Comment by jsteinich** [comment]
@henry333666999 make sure the aws provider is listed in your `cdktf.json` file and run `cdktf get` to generate the provider code. Take a look at https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/using-providers.md#importing-providers-and-modules for some more information.

**Comment by henry333666999** [comment]
Doing cdktf synth creates a tf file, but I still get the red import doesn’t exist issue on the ide

***@***.***

***@***.***

**Comment by jsteinich** [comment]
@henry333666999 running `cdktf get` should generate providers files within the same source tree as the application. Are you seeing them?

**Comment by ansgarm** [comment]
If `cdktf synth` runs without error, the problem probably lies within the configuration of the IDE. Maybe you need to mark the generated code as "source" or some other way to tell Eclipse / IntelliJ IDEA how to use those source files?

**Comment by piyussharma6** [comment]
I got Error message while setting Java code  "package imports.aws does not exist"

import com.hashicorp.cdktf.TerraformStack;
import imports.aws.AwsProvider;
import imports.aws.Instance;
import software.constructs.Construct;


public class terraformBuilder extends TerraformStack {

        public terraformBuilder(final Construct scope, final String id) {
                super(scope, id);

                AwsProvider.Builder.create(this, "aws").region("eu-central-1").build();
        }


}
----------
 
        <dependency>
            <groupId>com.hashicorp</groupId>
            <artifactId>cdktf</artifactId>
            <version>0.5.0</version>
        </dependency>
---------

What dependency is missing?

**Comment by DanielMSchmidt** [comment]
No answer for a few months, closing this for now 👍
