### ISSUE TITLE
csharp: how to handle a resource count and count.index?

### ISSUE THREAD

**Issue by rgl** [hashicorp/terraform-cdk#959]
How to I convert the following HCL to C#?

```hcl
data "template_cloudinit_config" "xxx" {
  count = 123
  gzip = true
  base64_encode = true
  part {
    content_type = "text/cloud-config"
    content = <<-EOF
      #cloud-config
      hostname: xxx${count.index}
    EOF
  }
}
```

Should the following work (please note the `{count.index}` usage, which I think would not work, but I don't known how to implement that)?

```csharp
var cloudInit = new DataTemplateCloudinitConfig(this, "xxx", new DataTemplateCloudinitConfigConfig
{
    Count = 123,
    Gzip = true,
    Base64Encode = true,
    Part = new[]
    {
        new DataTemplateCloudinitConfigPart
        {
            ContentType = "text/cloud-config",
            Content = $@"
#cloud-config
hostname: xxx{count.index}
",
        },
    },
});
```

Or although `Count` is reflected in the generated classes, its not really supported? And instead I should instantiate several `DataTemplateCloudinitConfig` objects?

**Comment by jsteinich** [comment]
If count is know at compile time, than simply creating the desired amount in a for loop is better supported.

It is possible to use `count.index`. You'll need to do some escaping in the string, but effectively you want it to be exactly as it is in the Terraform config.

**Comment by rgl** [comment]
Understood, thank you!
