### ISSUE TITLE
[Docs page] What is CDKTF?

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#966]
**Description**
This page should help new users understand CDK for Terraform's value proposition and make a decision about whether they should use it for their projects. 

Content should go in: [/website/docs/cdktf/index.html.md
](https://github.com/hashicorp/terraform-cdk/blob/terraform-io-docs/website/docs/cdktf/index.html.md)

This page has the following sections:
- **High-Level intro:** Explain what CDK for Terraform is and why it's useful. Include the image currently in the README.
- **How does CDK for Terraform work?** Explain to users at a high level what using this entails (make app, define infrastructure in app, deploy - either with CLI or by synthesizing a config file and using directly with Terraform). 
- **When to use CDK for Terraform:** Explain when users should choose this option rather than learning and writing their configs in HCL. Let users know about any caveats (e.g. production use) that might help them make an informed decision.
- **Project Maturity:** Let users know that this is in active/early development.
- **Get Started:** Links to Install learn tutorials and key concepts for new users.

**Engineering support** is required for:
- Review existing page content for accuracy
- Add additional content where appropriate - including drafting the content for the When do use CDK for Terraform section.

-----
Transfer relevant existing content from README - Done!

**Comment by laurapacilio** [comment]
I have:
- Transferred content from the original outputs GitHub page
- Copyedited the content
- Written some new conceptual overview content 
- Added some TODOs on the page that need engineering attention

Once engineering reviews the content and makes any necessary additions, I will review/copyedit again and we can mark this ready for publishing.

**Comment by danieldreier** [comment]
@laurapacilio I've reviewed this, and it looks great - thank you for putting this together. I think the only open writing task remaining is when to use HCL vs CDK, and I'm inclined to write that page first and then summarize content from there for this.

**Comment by laurapacilio** [comment]
awesome! And yes I agree with you 100% so you can just make those edits whenever that page is done and you're ready to summarize.

**Comment by danieldreier** [comment]
@laurapacilio I've added a brief "when to use" description, created and pushed a draft of the interoperability doc, and could use review/copy-editing on both. @schersh a second opinion on the "when to use" language + logic would be super useful here too.

**Comment by laurapacilio** [comment]
Awesome! I made a PR that you and @schersh can add feedback to :-) Thank you for working on this! 

https://github.com/hashicorp/terraform-cdk/pull/1065

**Comment by schersh** [comment]
merged to `stable-website`
