### ISSUE TITLE
[Docs page] Troubleshoot

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#968]
**Description**

:tickets: [Asana ticket](https://app.asana.com/0/1200893566367079/1200893566782688)

:mag: File path: /website/docs/cdktf/troubleshoot.html.md

- Troubleshooting - note about how you can circumvent CDK in certain situations if you need to with a link to the CLI commands that do that. Mention use of synth and convert commands for troubleshooting. 
- How to get verbose output from Terraform
- Debugging | note about which environment variables to set, where to find logs
- Known limitations

**Comment by danieldreier** [comment]
* This is related to https://github.com/hashicorp/terraform-cdk/issues/218 which plans engineering work to make this easier
