### ISSUE TITLE
[Docs page] CDKTF and Terraform

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#973]
**Description**

:tickets: [Asana ticket](https://app.asana.com/0/1200893566367079/1200893566367089)

:mag: File path: /website/docs/cdktf/concepts/intro-to-cdktf-and-terraform.html.md

Give a very brief overview of what Terraform is, how it works, and how key constructs map to things in CDKTF | This is geared toward beginners who have no experience with Terraform or with CDKTF so they can build a mental model without hunting through Terraform docs. We will focus on telling users just enough and then linking to more detailed documentation in Terraform and also for CDKTF.

**Comment by danieldreier** [comment]
I'm going to take a first pass at this, then hand it over to @skorfmann

**Comment by danieldreier** [comment]
@schersh and I looked at this and decided it's a bit too vague. I've worked on writing something for it and am not convinced it's needed.
