### ISSUE TITLE
[Docs page] Constructs

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#976]
**Description**
The purpose of this documentation is to explain to a user how and why to write a custom construct. This is primarily technical documentation. This is the primary source of technical reference documentation users will use when they want to write L2 and L3 constructs 

This should also describe:
- How to bundle up custom constructs, e.g. show example of a custom repo that can be packaged up and can be consumed
- Publishing constructs, distributing them in a company (how to use private registries)
- Link back to dual publishing content (in HCL interoperability)

We don't need to give in-depth documentation of _how_ to publish to npm, for example - this is documented elsewhere. It's sufficient to assume that the users are proficient in these language tools, and we would ideally link to external official documentation specific to npm, pypi, etc.

**reference**
"Writing your own constructs" section of [AWS CDK Construct documentation](https://docs.aws.amazon.com/es_es/cdk/latest/guide/constructs.html).

**languages**: we _must_ document this in TypeScript and Python. Ideally, examples would be provided in all supported languages. It's acceptable to use convert-generated translations that aren't super idiomatic if necessary.

:tickets: [Asana ticket](https://app.asana.com/0/1200893566367079/1200945781318955)

:mag: File path: [/website/docs/cdktf/create-and-deploy/custom-constructs.html.md](https://github.com/hashicorp/terraform-cdk/blob/terraform-io-docs/website/docs/cdktf/create-and-deploy/constructs.html.md)

This page should also include docs on consuming constructs (https://github.com/hashicorp/terraform-cdk/issues/982)

**Comment by laurapacilio** [comment]
Also - I know so little about this with CDKTF that I can't do much for this page. Daniel already scoped it quite nicely in the comments, so I'm going to mark this as "Ready for Engineering." @skorfmann if you could write a rough draft, I can help shape it and provide feedback!

**Comment by ansgarm** [comment]
https://www.terraform.io/docs/cdktf/concepts/constructs.html 🎉
