### ISSUE TITLE
[Docs page] Resources

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#981]
**Description**

:tickets: [Asana ticket](https://app.asana.com/0/1200893566367079/1200893566367111)

:mag: File path: /website/docs/cdktf/fundamentals/resources.html.md

Resources ([escape hatch](https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/escape-hatch.md), Importing existing resources (TBD)

**Comment by danieldreier** [comment]
I'm wondering if this content should be rolled into the [providers ticket](https://github.com/hashicorp/terraform-cdk/issues/978) - it feels super related.

**Comment by laurapacilio** [comment]
Saw Daniel's comment about rolling this into providers, and I think I agree even though this isn't how the terraform docs are set up. I'm going to put up a PR to combine them and y'all can see what you think :-)

**Comment by laurapacilio** [comment]
Here's the PR. @schersh and @danieldreier let me know what you think!

**Comment by schersh** [comment]
closed in favor of https://github.com/hashicorp/terraform-cdk/issues/978
