### ISSUE TITLE
[Docs page] Variables 

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#986]
**Description**
The purpose of this document is to explain to a user who has never used CDK for Terraform or Terraform what variables are, the role they play in infrastructure management, and how to think about using them to manage infrastructure with CDK for Terraform.

Content should go in: [/website/docs/cdktf/fundamentals/variables.html.md](https://github.com/hashicorp/terraform-cdk/blob/terraform-io-docs/website/docs/cdktf/concepts/fundamentals/variables.html.md)

This document has several sections. **Engineering support** is required for the following:
- Review existing content (already on the page) for accuracy
- Help author conceptual content about what variables are, how they are used by Terraform, and how they are used and managed by CDK for Terraform. Laura has written a draft of this, but it needs engineering review.
- Respond to a couple of TODOs - Can we get a description above the example? Can we also help explain to users what's going to happen when the example gets synthesized? Does it create the `tfvars` file?

-------

Migrate existing https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/terraform-variables.md - DONE

**Comment by laurapacilio** [comment]
I have:
- Transferred content from the original outputs GitHub page
- Copyedited the content
- Added more conceptual information at the beginning
- Added some TODOs on the page that need engineering attention

Once engineering reviews the content and makes any necessary additions, I will review/copyedit again and we can mark this ready for publishing.

**Comment by schersh** [comment]
Closed in favor of https://github.com/hashicorp/terraform-cdk/issues/987
