### ISSUE TITLE
[Docs page] Variables and Outputs

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#987]
**Description**

The purpose of this document is to explain to a user who has never used CDK for Terraform or Terraform what outputs are, the role they play in infrastructure management, and how to think about using them to manage infrastructure with CDK for Terraform.

Content should go in: [/website/docs/cdktf/concepts/fundamentals/outputs.html.md](https://github.com/hashicorp/terraform-cdk/blob/terraform-io-docs/website/docs/cdktf/concepts/fundamentals/outputs.html.md)

This document has several sections. **Engineering support** is required for the following:
- Review existing content (already on the page) for accuracy
- Help author conceptual content about what outputs are, how they are used by Terraform, and how they are used and managed by CDK for Terraform. Laura has written a draft of this, but it needs engineering review.
- Can we add a block at the end of the page that shows what this output example looks like when printed for the user? Also, does it look different when it's printed when we deploy through CDKTF vs. when we synthesize and run the configuration from Terraform?
- Can we also take a minute at the top of the page to explain when folks should consider using Terraform Outputs, rather than just sticking with what's available in their programming language? 

-------

Migrate existing https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/terraform-outputs.md - DONE

**Comment by danieldreier** [comment]
This work is also contingent on whether https://github.com/hashicorp/terraform-cdk/issues/227 is built during 0.7

**Comment by laurapacilio** [comment]
I have:
- Transferred content from the original outputs GitHub page
- Copyedited the content
- Added more conceptual information at the beginning
- Added a TODO at the bottom of the page for engineering

Once engineering reviews the content and addresses the TODO, I will review again and we can mark this ready for publishing.

**Comment by laurapacilio** [comment]
FYI: @skorfmann made an initial PR here: https://github.com/hashicorp/terraform-cdk/pull/1078#event-5356242451
After some discussion with @schersh this morning, I started PR with edits here: https://github.com/hashicorp/terraform-cdk/pull/1080

**Comment by schersh** [comment]
Updated to title to reflect more content will be included in this page

**Comment by schersh** [comment]
https://github.com/hashicorp/terraform-cdk/pull/1078 is in progress

**Comment by DanielMSchmidt** [comment]
@schersh Can this be closed since #1078 is merged?

**Comment by schersh** [comment]
Yes, thanks!
