### ISSUE TITLE
Unit test helpers only work in Typescript/Javascript

### ISSUE THREAD

**Issue by jsteinich** [hashicorp/terraform-cdk#990]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Expected Behavior

Test matchers are available for all supported languages.

### Actual Behavior

They are only available in Typescript/Javascript

### Important Factoids

We should remove the python example in https://github.com/hashicorp/terraform-cdk/blob/main/docs/working-with-cdk-for-terraform/testing.md#writing-your-own-adapter- and also call out the limitations of the current version.

Could turn into a feature request to implement something similar to https://docs.aws.amazon.com/cdk/api/latest/docs/assertions-readme.html

### References

- https://docs.aws.amazon.com/cdk/api/latest/docs/assertions-readme.html
- #942

**Comment by DanielMSchmidt** [comment]
This is a part of the 0.12 release 🎉
