### ISSUE TITLE
Replace `ComplexComputedList` with native array with a single `ComplexComputedObject`

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#993]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently we have a very limited way of working with lists as outputs of providers and the things we support make it clear that we don't deal with a native array but something else.
To make lists behave seamlessly we need to make them first class citizens by using native arrays.

To implement this properly we need to 

- return a list of Complex Elements from the getter, where
  - each native property is a token
  - each computed property is readonly
  - each complex property with computed attributes adds a `put${propertyName}` method to the element that takes an object with only the not-computed types as a property
- Enhance the resolve workflow to to recognize complex lists and resolve them properly
- Make the list 1 element long and throw an error if that element is used directly (i.e. through accessing the array)

This also enables us to advance the work of https://github.com/hashicorp/terraform-cdk/pull/925 and expose computed types as well. The current problem there is that the interface expects a getter to have the type `DataKubernetesPersistentVolumeClaimSpecResource[]`, but in the current implementation it has `(index: string) => DataKubernetesPersistentVolumeClaimSpecResources`.

### What this should enable
Currently inputs that are passed to a resource share the same type with references to that same attribute. For example, if we pass a string, we get back a string (which is an token encoded reference, but still appears to be a string). This is true for almost all types but not for lists. We want to achieve this for lists which contain objects (nested blocks) instead of plain values (lists of numbers or strings already return tokens encoded as a list of number / string containing the reference to that attribute).

#### Referencing list arguments also works in other languages than TS
When a list exists which can be set as input by the user, referencing that list does not work in other languages than TS (see: https://github.com/hashicorp/terraform-cdk/issues/1371). This allows the following to work:

todo: in Go referencing a list, passing it to e.g. `Fn.length`

#### Passing a reference to a list works without "fqn" hack
Example in HCL
```hcl
data "aws_availability_zones" "azs" {
  state = "available"
}

resource "aws_subnet" "this" {
  # ...
  availability_zone_id = data.aws_availability_zones.azs.zone_ids[0]
}
```

This equivalent now works:
```ts
const azs = new DataAvailabilityZones(this, 'azs', { state: "available" })
new aws.Subnet(this, 'this', {
	availabilityZoneId: Fn.element(azs.zoneIds, 0);
	// Note: this would throw an error (as we cannot know this at synth time)
	// availabilityZoneId: azs.zoneIds[0]
})
```

Formerly this workaround was required (and did not work in other languages than TypeScript)
```ts
const azs = new DataAvailabilityZones(this, 'azs', { state: "available" })
new aws.Subnet(this, 'this', {
	availabilityZoneId: Fn.element(Fn.lookup(azs.fqn, 'zone_ids'), 0);
})
```

#### No more `listAttribute(index)` method
As passing a list reference into `Fn.element()` works now this type of method is not needed anymore. It was not very idiomatic anyway as it treated the output (reference) to an attribute of a resources as a different type than the input for said attribute.
Formerly `listAttribute` was a function (wat!?):
```ts
const item = resource.listAttribute('0'); // will be removed
```
Now it is a list, just like the related input:
```ts
const item = Fn.element(resource.listAttribute, 0);
```

### References

- https://github.com/hashicorp/terraform-cdk/issues/856
- https://github.com/hashicorp/terraform-cdk/pull/925
- https://github.com/hashicorp/terraform-cdk/issues/663
- check if this solves: https://github.com/hashicorp/terraform-cdk/issues/1371

**Comment by skorfmann** [comment]
> Example in HCL
> 
> ```terraform
> data "aws_availability_zones" "azs" {
>   state = "available"
> }
> 
> resource "aws_subnet" "this" {
>   # ...
>   availability_zone_id = data.aws_availability_zones.azs.zone_ids[0]
> }
> ```

Isn't this just a string list and therefore a string list token already?

**Comment by ansgarm** [comment]
> Isn't this just a string list and therefore a string list token already?

Whoops, you're right @skorfmann. I'll find a better example that uses a list of objects.
