### ISSUE TITLE
Enable Array Iterations / passing blocks

### ISSUE THREAD

**Issue by DanielMSchmidt** [hashicorp/terraform-cdk#994]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To make looping over lists nicer we want to allow users to write something like

```ts

const myVpc = new Vpc(...);
myVpc.publicSubnets.forEach(subnet => {
  new MyModule(..., {
    subnetId: subnet.id
  }
})
```

To make this work we need to analyse the graph of nodes and their references to see where all elements have been used.
There are cases that we can not support with this method, but we believe that we will enable a good chunk of use-cases in a very nice syntax like this.

This would be implemented using dynamic blocks, so we could enable users to assign blocks with `max_items > 1` in their resource / data source definitions

### References

- Depends on https://github.com/hashicorp/terraform-cdk/issues/993 being done
- https://github.com/hashicorp/terraform-cdk/issues/434
- https://github.com/hashicorp/terraform-cdk/issues/288
- https://github.com/hashicorp/terraform-cdk/issues/663
- https://github.com/hashicorp/terraform-cdk/issues/42

**Comment by ansgarm** [comment]
Has this been superseeded by [Iterators](https://www.terraform.io/cdktf/concepts/iterators) or is there more to this that makes it worth keeping?

**Comment by DanielMSchmidt** [comment]
I think we can close this one, the functionality has been implemented
