### ISSUE TITLE
Harmonious deployments using both AWS and TF CDKs?

### ISSUE THREAD

**Issue by brad-lucas** [hashicorp/terraform-cdk#995]
Noob here when it comes to both AWS and Terraform CDKs, so apologies if I missed this information in searching elsewhere.

My team currently has its existing control plane and data plane deployments built using AWS CDK, but we're looking to start adding Azure resources into the data plane and have all but signed off on using TF CDK for deployments for Azure, where output values from Azure are fed into the AWS stack.

Can the two CDKs co-exist within a shared deployment scope?

Thanks in advance for the help!

**Comment by danieldreier** [comment]
Hi Brad! Using both CDKs together like this isn't something we support right now, but please keep watching for future announcements. This is a relatively common scenario and we'd like to help you and other folks with the same use case.

**Comment by brad-lucas** [comment]
Thanks for getting back to me quickly, @danieldreier!

So are you saying I can't have the two CDKs interact at all or just that the code isn't compatible?

Let's say as a super simple example I want to be able to log into Azure from code hosted in AWS, so I need to create a service principal with a password in Azure AD and want to save the outcome in an AWS Secrets Manager instance (and obviously add the code to do the auth):
1. create the service principal and password using Terraform CDK
2. output the client ID and secret into a local variable
3. call `synth()` for the TF CDK
4. feed the Azure AD values into existing AWS CDK for the Secrets Manager
5. call `synth()` on the AWS CDK
6. reference the Secrets Manager values in auth flow

Are you saying this type of handoff wouldn't be possible? If not, how else could I get going with TF CDK for Azure without replacing our existing IaC?

**Comment by brad-lucas** [comment]
I've had the chance to dig deeper and think I understand why this isn't possible: deployment of resources from both CDKs are eventually tied back to invoking of their own CLI command, and our existing codebase is using a subprocess of packaged AWS CDK to do so remotely.

Back to the drawing board; this is going to be interesting...

**Comment by jsteinich** [comment]
For both cdks, the synth step simply generates json/cloudformation based on your code. The actual execution is done separately.

If you are able to move the secrets manager secret value into Terraform CDK, then the AWS CDK side could simply reference that secret. That would also require running the cdks in sequence instead of directly in one process.

**Comment by ansgarm** [comment]
I'm going to close this, as since this issue was created, the (experimental) AWS Adapter came into existence: https://developer.hashicorp.com/terraform/cdktf/create-and-deploy/aws-adapter
