### ISSUE TITLE
[Docs page] Integration Tests

### ISSUE THREAD

**Issue by schersh** [hashicorp/terraform-cdk#997]
**Description**

:tickets: [Asana ticket]() n/a

:mag: File path: /website/docs/cdktf/tests/integration-tests.html.md

TBD

**Comment by danieldreier** [comment]
I'm tentatively milestoning this to 0.7 on the assumption we'll be building the integration test tooling in that timeframe but it'll obviously need to be moved if we postpone that

**Comment by danieldreier** [comment]
I'm going to close this issue on the assumption that #1096 implicitly covers documenting it
